### ISSUE TITLE
@size variable is null in select

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#6394] opened 2016-07-07 17:22 UTC
## Expected behavior and actual behavior

select @size from #33:1 

where the record is binary record 
<pre>
----+------
#   |@CLASS
----+------
0   |null  
----+------
</pre>

i can't know the size of the binary record

## Steps to reproduce the problem

select @size from #33:1 

## Important Questions

- [ ] v2.0.x - Please specify last number: 
- [x ] v2.1.x - Please specify last number: 2.1.18
- [ ] v2.2.x - Please specify last number: 

### Operating System
- [x ] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [ ] 7
- [x ] 8

**Comment by publicocean0** [comment] 2016-07-07 18:08
in addition 
this select 

select 1 as prova from (select from binarycluster ) 

<pre>
----+------
#   |@CLASS
----+------
0   |null  
1   |null  
2   |null  
3   |null  
4   |null  
5   |null  
6   |null  
7   |null  
8   |null  
9   |null  
10  |null  
11  |null  
12  |null  
13  |null  
14  |null  
15  |null  
16  |null  
17  |null  
18  |null 
</pre>

**Comment by publicocean0** [comment] 2016-07-07 18:11
probably also other special attributes starting with @  are not visible

**Comment by luigidellaquila** [comment] 2016-07-15 11:23
Hi @publicocean0 

I fixed this in 2.2.x, the fix will be released with 2.2.5

Thanks

Luigi

**Closed by luigidellaquila** 2016-07-15 11:23 UTC
Labels: bug

**Comment by publicocean0** [comment] 2016-07-17 09:57
[INFO] OrientDB ........................................... SUCCESS [  5.478 s]
[INFO] OrientDB Test Commons .............................. SUCCESS [  3.232 s]
[INFO] OrientDB Core ...................................... SUCCESS [ 17.477 s]
[INFO] OrientDB Client .................................... SUCCESS [  1.404 s]
[INFO] OrientDB Object .................................... SUCCESS [  2.420 s]
[INFO] OrientDB Tools ..................................... SUCCESS [  1.828 s]
[INFO] OrientDB Server .................................... SUCCESS [  3.871 s]
[INFO] OrientDB GraphDB ................................... SUCCESS [  4.612 s]
[INFO] OrientDB Tests ..................................... FAILURE [  3.173 s]
[INFO] OrientDB Distributed Server ........................ SKIPPED
[INFO] OrientDB Lucene full text index .................... SKIPPED
[INFO] OrientDB JDBC Driver ............................... SKIPPED
[INFO] OrientDB ETL ....................................... SKIPPED
[INFO] OrientDB Community Distribution .................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 43.676 s
[INFO] Finished at: 2016-07-17T11:56:24+02:00
[INFO] Final Memory: 83M/483M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project orientdb-tests: Could not resolve dependencies for project com.orientechnologies:orientdb-tests:jar:2.2.5-SNAPSHOT: Could not find artifact com.orientechnologies:orientdb-core:jar:tests:2.2.5-SNAPSHOT in sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :orientdb-tests

**Comment by luigidellaquila** [comment] 2016-07-18 07:37
mmm... this is strange, I have no problems to build here.

Could you please try

```
mvn clean
```
and then
```
mvn install
```

Thanks

Luigi

**Comment by luigidellaquila** [comment] 2016-07-18 08:03
ok, it seems we have some problems with the build, I'll keep you posted

Thanks

Luigi

**Comment by publicocean0** [comment] 2016-07-18 08:37
hi , already done yesterday but it is not working. 
Probably if you go to your .m2/repository directory and you delete the 2.2.5 snapshot forcely from your local system ... then
mvn clean install -Dmaven.test.skip=true you might to see the problem

**Comment by luigidellaquila** [comment] 2016-07-18 08:47
Hi @publicocean0 

yep, I reproduced it, it's a problem with the build  due to one of our last commits (not related to this issue). We are working to fix it 

Thanks

Luigi

**Comment by luigidellaquila** [comment] 2016-07-21 08:59
Hi @publicocean0 

the problem with the build should be fixed

Thanks

Luigi

**Comment by publicocean0** [comment] 2016-07-21 19:22
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] OrientDB ........................................... SUCCESS [  4.315 s]
[INFO] OrientDB Test Commons .............................. SUCCESS [  4.449 s]
[INFO] OrientDB Core ...................................... SUCCESS [ 27.637 s]
[INFO] OrientDB Client .................................... SUCCESS [  2.411 s]
[INFO] OrientDB Object .................................... SUCCESS [  3.476 s]
[INFO] OrientDB Tools ..................................... SUCCESS [  2.812 s]
[INFO] OrientDB Server .................................... SUCCESS [  6.155 s]
[INFO] OrientDB GraphDB ................................... SUCCESS [  4.984 s]
[INFO] OrientDB Tests ..................................... FAILURE [  3.798 s]
[INFO] OrientDB Distributed Server ........................ SKIPPED
[INFO] OrientDB Lucene full text index .................... SKIPPED
[INFO] OrientDB JDBC Driver ............................... SKIPPED
[INFO] OrientDB ETL ....................................... SKIPPED
[INFO] OrientDB Community Distribution .................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:00 min
[INFO] Finished at: 2016-07-21T21:22:16+02:00
[INFO] Final Memory: 87M/670M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project orientdb-tests: Could not resolve dependencies for project com.orientechnologies:orientdb-tests:jar:2.2.6-SNAPSHOT: Could not find artifact com.orientechnologies:orientdb-core:jar:tests:2.2.6-SNAPSHOT in sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :orientdb-tests

**Comment by publicocean0** [comment] 2016-07-21 19:25
Maybe do  you set core with scope test?

**Comment by publicocean0** [comment] 2016-07-21 19:33
https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-core/2.2.6-SNAPSHOT/maven-metadata.xml

**Comment by publicocean0** [comment] 2016-07-21 19:37
i read pom in tests module. I think there the pom definition could be not corrrect.

**Comment by publicocean0** [comment] 2016-07-21 20:34
i solved ... there is a problem in tests and lucene modules

**Comment by publicocean0** [comment] 2016-07-21 20:34
remove type attribute from those module pom

**Comment by publicocean0** [comment] 2016-07-21 20:52
i tested also the fix 
but there is ....



orientdb {db=streamer}> select sum(@size) from (select  expand(data)  from 36:149)

+----+----+
|#   |sum |
+----+----+
|0   |    |
+----+----+

**Comment by publicocean0** [comment] 2016-07-21 20:53
sum function is not executed

**Comment by publicocean0** [comment] 2016-07-22 06:02
in addition is there a way for calculating a accumulative sum?

**Comment by luigidellaquila** [comment] 2016-07-22 06:44
Hi @publicocean0 

with current execution layer it's quite tricky to support complex expression evaluation for binary records, I risk to give you wrong results, this is why I only implemented basic cases.
In v 3.0 the problem root cause of the problem will be removed, so the problem will be completely fixed.

For now, I suggest you to use a subquery:

SELECT sum(size) from (select @size as size from  (select expand(data) from 36:149) )

Thanks

Luigi

**Comment by publicocean0** [comment] 2016-07-22 06:50
yes also this works select from ( select sum(data.@size) from 36:149 unwind data ) it works.

but the sum is global. is there a way for creating a function or a method for calculatiing a incremental sum for every row?

**Comment by publicocean0** [comment] 2016-07-22 06:51
row 1 10
row 2  20 
row 3 5 



result 

10
30
35

**Comment by luigidellaquila** [comment] 2016-07-22 06:59
Mmm... got the point

Try this 

```
select $p  from (SELECT FROM ... ) let $p = eval("$p + @size")
```

But please consider that it is a very extreme usage of LET assignment and that this behavior could change in 3.0 as we are re-writing the engine

Thanks

Luigi

**Comment by publicocean0** [comment] 2016-07-22 07:04
ok thanks for the info. sorry last question :) 
In addition i would ask you if you foresee for version 3.0 lucene will have index on  embedded properties ( i can search also a property inside dinamically )? and eventually what is the deadline (about) for version 3? 

i have to decide if create a new lucene module or not based on you answer. :)

**Comment by luigidellaquila** [comment] 2016-07-22 07:58
Indexes on embedded properties are in the roadmap, so the answer is "yes".
Our goal is to release it in Q4 2016

Thanks

Luigi

**Comment by publicocean0** [comment] 2016-07-22 07:59
wow so you evoid a lot of work to do :)

**Comment by publicocean0** [comment] 2016-07-23 07:36
Considering you want remake orientdb engine i posted also a problem actually difficult to solve with orientdb. Maybe remaking it you can design a global solution including also it. 

https://github.com/orientechnologies/orientdb/issues/5136#problem
