### ISSUE TITLE
OutOfMemoryError: Requested array size exceeds VM limit

### ISSUE THREAD

**Issue by adithyank** [orientechnologies/orientdb#3303] opened 2014-12-31 00:50 UTC
OrientDB version : 2.0-M3
JDK : Oracle JDK 1.7.0_71
OS : CentOS 6.5

The below Exception came only once while starting our server application after crash. So, OrientDB was not shutdown properly.

```
java.lang.OutOfMemoryError: Requested array size exceeds VM limit
Dumping heap to /cygnet/heapdump/ ...
Unable to create /cygnet/heapdump/: Is a directory
Exception in thread "pool-1-thread-36" java.lang.OutOfMemoryError: Requested array size exceeds VM limit
        at java.util.Arrays.copyOf(Arrays.java:2219)
        at java.util.ArrayList.grow(ArrayList.java:242)
        at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:216)
        at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:208)
        at java.util.ArrayList.add(ArrayList.java:440)
        at com.orientechnologies.orient.core.index.sbtree.local.OSBTree.findBucket(OSBTree.java:1514)
        at com.orientechnologies.orient.core.index.sbtree.local.OSBTree.get(OSBTree.java:188)
        at com.orientechnologies.orient.core.index.engine.OSBTreeIndexEngine.get(OSBTreeIndexEngine.java:226)
        at com.orientechnologies.orient.core.index.OIndexOneValue.get(OIndexOneValue.java:57)
        at com.orientechnologies.orient.core.index.OIndexOneValue.get(OIndexOneValue.java:44)
        at com.orientechnologies.orient.core.index.OIndexAbstractDelegate.get(OIndexAbstractDelegate.java:59)
        at com.orientechnologies.orient.core.index.OIndexTxAwareOneValue.get(OIndexTxAwareOneValue.java:233)
        at com.orientechnologies.orient.core.index.OIndexTxAwareOneValue.get(OIndexTxAwareOneValue.java:41)
        at com.orientechnologies.orient.core.sql.operator.OQueryOperatorEquals.executeIndexQuery(OQueryOperatorEquals.java:129)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchForIndexes(OCommandExecutorSQLSelect.java:1448)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchInClasses(OCommandExecutorSQLSelect.java:713)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.assignTarget(OCommandExecutorSQLResultsetAbstract.java:184)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.assignTarget(OCommandExecutorSQLSelect.java:414)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:396)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:367)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:64)
        at com.orientechnologies.orient.core.storage.OStorageEmbedded.executeCommand(OStorageEmbedded.java:86)
        at com.orientechnologies.orient.core.storage.OStorageEmbedded.command(OStorageEmbedded.java:75)
        at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:70)
        at com.orientechnologies.orient.core.sql.query.OSQLSynchQuery.run(OSQLSynchQuery.java:84)
        at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
        at com.orientechnologies.orient.core.metadata.security.OSecurityShared.getUser(OSecurityShared.java:447)
        at com.orientechnologies.orient.core.metadata.security.OSecurityShared.getUser(OSecurityShared.java:181)
        at com.orientechnologies.orient.core.metadata.security.OSecurityShared.authenticate(OSecurityShared.java:157)
        at com.orientechnologies.orient.core.metadata.security.OSecurityProxy.authenticate(OSecurityProxy.java:86)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:254)
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire(OPartitionedDatabasePool.java:192)
```

But, many times when OrientDB was not shutdown properly it used to rebuild the indices while restarting our application. This Exception has not come those times.

It occurred only once. So, I don't feel it is reproducible from my side.

Pls tell me If I have to give any other information

**Comment by laa** [comment] 2015-01-22 06:53
It is the same index corruption which we already discussed.

**Comment by adithyank** [comment] 2015-01-22 07:48
No. It occurred in a new server machine. Not anything that was reported earlier

**Comment by laa** [comment] 2015-01-22 08:36
Is it reproduced when disk cache according to settings consumes all available RAM ?

**Comment by lvca** [comment] 2015-01-22 08:38
Happens also with 2.0 final?

**Comment by laa** [comment] 2015-01-22 08:42
We discussed the reason where data read issues happened, typically it is happened when setting are set to use borders of available ram so in reality we go into swap.

**Comment by laa** [comment] 2015-05-22 07:24
Is it still valid ?

**Comment by adithyank** [comment] 2015-05-27 12:52
We did not see this after the reported instance....!
It may be closed now. We will request reopening when we see it again

**Comment by lvca** [comment] 2015-05-27 14:16
Cool, I'm closing it.

**Closed by lvca** 2015-05-27 14:16 UTC
Labels: waiting reply
