### ISSUE TITLE
Lucene index over multiple fields discard valid keys

### ISSUE THREAD

**Issue by ivanofenix** [orientechnologies/orientdb#2428] opened 2014-06-04 13:55 UTC
Customer ID 49 - Lucene index over multiple fields discard records that have one or more of those fields with null value.

**Comment by MarcelPitch** [comment] 2015-03-03 16:07
Hi all,

Just to know if you have milestone for this issue.

Thanks and have a nice day !

**Comment by MarcelPitch** [comment] 2015-03-04 08:21
Hi,

Sorry, I didn't explain the context.

I'm working with **orientDB community 2.0.2**.

I would like to create a *Lucene FullText Index* on a `User`vertex class, like this :

```SQL
CREATE INDEX User.fullname ON User (firstname, lastname, maidenname) FULLTEXT ENGINE LUCENE
```

The problem is on `maidenname`. This field is `null` for many `User` (logical...) and the `REBUILD INDEX` command seems to stop indexing when the cursor reaches a `null` value.

When I create an Index only with `firstname` and `lastname` properties, which are mandatory, the Index building is OK.

Thanks for your answer !

**Comment by MarcelPitch** [comment] 2015-03-04 16:40
Sorry, my bad !!! :-1: 

RTM !!!

with :
```SQL
METADATA { ignoreNullValues : false }
```
it's really better !

Sorry for the inconvenience...

and have a nice day !

**Comment by luigidellaquila** [comment] 2015-06-05 14:55
Ok, closing and marking as invalid

**Closed by luigidellaquila** 2015-06-05 14:55 UTC
