### ISSUE TITLE
automated class-creation script generated bad class-name, cannot drop it anymore

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#7102] opened 2017-01-20 13:22 UTC
## OrientDB Version, operating system, or hardware.
- v2.2.14

## Operating System
- [x] Linux

## Expected behavior and actual behavior
We have an automated class-creation script, but during its development it has created a class with an incorrect name: "cdr_eno-xxx" ; apparently the "-" in this name is blocking any kind of "ALTER CLASS" or "DROP CLASS" commands.

-> how to rename or drop such a class ? Can some kind of a class-ID be used to specify which class we want to action on ?

**Comment by luigidellaquila** [comment] 2017-01-20 13:46
Hi @rdelangh 

how are you dropping it? with SQL? Did you try with back-tick syntax?

```
DROP CLASS `cdr_eno-xxx`
```

If I'm not wrong, there are also a couple of fixes about this in v 2.2.15, so if you have problems with 2.2.14 it's definitely worth trying to update

Thanks

Luigi

**Comment by rdelangh** [comment] 2017-01-26 11:46
@luigidellaquila 
I have executed that command

DROP CLASS `cdr_eno-xxx`

in the web interface; the reply was "command executed succesfully". However when I list the classes again, this wrong-named-class is still there, not dropped.

**Comment by rdelangh** [comment] 2017-01-30 12:49
anyone has some suggestions, please?

**Comment by luigidellaquila** [comment] 2017-01-30 12:58
Hi @rdelangh 

I just tried it on v. 2.2.12 and 2.2.16-SNAPSHOT and it works fine, are you sure you spelled the name correctly? Do you have a script to reproduce the problem?

Thanks

Luigi

**Comment by rdelangh** [comment] 2017-01-30 14:43
@luigidellaquila 

- In the web browser, under "schema", I see this class named "cdr_eno-11128"
- in the web browser, under "browse", I run the command "drop class `cdr_eno-11128`" ; the reply is "command executed succesfully"
- when I refresh the list of classes under "schema", this class named "cdr_eno-11128" is still there

- in the CLI "console.sh", i run the command "classes"; altough the names of the classes are displayed abbreviated, I see the cluster names of this same class
- I run the command "drop class `cdr_eno-11128`" ; the reply is "Removed class in 0.053000 sec(s)."
- I run the command "classes" again, that same list of cluster names of this class is still present:
```
orientdb {db=mobile}> classes
CLASSES
+----+---------+---------+---------+-----------------------------------------------------------------------------------------------------------------------+
|#   |    COUNT|SUPER-CLA|NAME     |CLUSTERS                                                                                                               |
+----+---------+---------+---------+-----------------------------------------------------------------------------------------------------------------------+
|0   |        1|         |_studio  |_studio(171),_studio_1(172),_studio_2(173),_studio_3(174),_studio_4(175),_studio_5(176),_studio_6(177),_studio_7(178...|
|1   |        4|         |cdr_en...|cdr_eno_-11128(441),cdr_eno_-11128_1(442),cdr_eno_-11128_2(443),cdr_eno_-11128_3(444),cdr_eno_-11128_4(445),cdr_eno_...|
|2   | 94698606|         |cdr_en...|cl_cdr_eno_20161218_p0(327),cl_cdr_eno_20161218_p1(328),cl_cdr_eno_20161218_p2(329),cl_cdr_eno_20161218_p3(330),cl_c...|
...
```

**Comment by luigidellaquila** [comment] 2017-01-30 15:46
Mmmm... ok there must be something strange in that db, do you think you can share it? 
Even a copy without any data

Thanks

Luigi

**Comment by rdelangh** [comment] 2017-01-30 16:30
hey Luigi, how can I take a copy without data? The dbase is a few 100's GB in size...

**Comment by luigidellaquila** [comment] 2017-01-30 17:06
Hi @rdelangh 

if you have a chance to copy the db, you can drop the clusters and leave the schema as is.
Otherwise you can try to export the db with `-includeRecords=false` http://orientdb.com/docs/2.2.x/Console-Command-Export.html

Thanks

Luigi

**Comment by rdelangh** [comment] 2017-01-31 13:31
@luigidellaquila 
ok, that worked, resulting export file is some 8K size. See attached file "mobile.exp.gz"
[mobile.exp.gz](https://github.com/orientechnologies/orientdb/files/742044/mobile.exp.gz)

**Comment by rdelangh** [comment] 2017-02-07 10:31
@luigidellaquila 
hi Luigi, any update on this, please ?
Version of ODB is now 2.2.15

**Comment by luigidellaquila** [comment] 2017-02-07 12:10
Hi @rdelangh 

I just imported your db in latest 2.2.x snapshot and I was able to drop the class with a simple

DROP CLASS `cdr_eno_-11128`

I did it from Studio, maybe the problem is only in the refresh of the schema in the console? If it's the case, it's a known issue, next 3.0 will have automatic push notifications on schema change

Thanks

Luigi

**Comment by rdelangh** [comment] 2017-02-22 13:33
using v2.2.17, this is now possible to drop a class with such malformed name.

-> issue can be closed.

**Comment by luigidellaquila** [comment] 2017-02-22 13:36
Great, thanks for confirming that @rdelangh 

Closing then, thanks!

Luigi

**Closed by luigidellaquila** 2017-02-22 13:36 UTC
Labels: question
