### ISSUE TITLE
ArrayIndex out of bound error

### ISSUE THREAD

**Issue by Raycoms** [orientechnologies/orientdb#7426] opened 2017-05-17 18:16 UTC
### OrientDB Version: <version here>  
Newest
### Java Version: <version here>  
8
### OS: <os here>  
Linux

com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #18:23497 (cluster: node_1)
	DB name="OrientDB3"
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1926)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.loadRecord(OTransactionOptimistic.java:220)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.loadRecord(OTransactionOptimistic.java:194)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.loadRecord(OTransactionOptimistic.java:324)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:1628)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:103)
	at com.orientechnologies.orient.core.id.ORecordId.getRecord(ORecordId.java:330)
	at com.tinkerpop.blueprints.impls.orient.OrientElementIterator.next(OrientElementIterator.java:62)
	at com.tinkerpop.blueprints.impls.orient.OrientElementIterator.next(OrientElementIterator.java:35)
	at main.java.com.bag.server.database.OrientDBDatabaseAccess.applyUpdate(OrientDBDatabaseAccess.java:272)
	at main.java.com.bag.operations.UpdateOperation.apply(UpdateOperation.java:34)
	at main.java.com.bag.server.AbstractRecoverable.executeCommit(AbstractRecoverable.java:527)
	at main.java.com.bag.server.GlobalClusterSlave.executeCommit(GlobalClusterSlave.java:246)
	at main.java.com.bag.server.GlobalClusterSlave.appExecuteBatch(GlobalClusterSlave.java:107)
	at bftsmart.tom.server.defaultservices.DefaultRecoverable.executeBatch(DefaultRecoverable.java:87)
	at bftsmart.tom.server.defaultservices.DefaultRecoverable.executeBatch(DefaultRecoverable.java:68)
	at bftsmart.tom.ServiceReplica.receiveMessages(ServiceReplica.java:432)
	at bftsmart.tom.core.DeliveryThread.deliverMessages(DeliveryThread.java:293)
	at bftsmart.tom.core.DeliveryThread.run(DeliveryThread.java:225)
Caused by: java.lang.ArrayIndexOutOfBoundsException: -9
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.readFullEntry(OPaginatedCluster.java:1795)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.readRecord(OPaginatedCluster.java:666)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.readRecord(OPaginatedCluster.java:628)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doReadRecord(OAbstractPaginatedStorage.java:3329)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:2959)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:1086)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx$SimpleRecordReader.readRecord(ODatabaseDocumentTx.java:3238)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1888)

**Comment by laa** [comment] 2017-05-22 12:29
Do you have any additional description? Is this exception thrown inside the tests or this exception is thrown on a production server? What from the point of view is the newest version? Are you able to reproduce this exception one more time? Do you have OOM or server crash before this exception happened? Is database was created under the same version which is used when you got this exception?

**Comment by laa** [comment] 2017-05-24 10:21
Hi, @Raycoms could you answer our questions?

**Comment by Raycoms** [comment] 2017-05-24 12:20
The exception is thrown in my thesis tests, it seems to be related to
concurrent access on the database within the server. I was able to
reproduce this easily.
I don't have OOM or similar and the database has been created under the
same version.
Version 2.2.1.7

2017-05-24 7:21 GMT-03:00 Andrey Lomakin <notifications@github.com>:

**Comment by laa** [comment] 2017-05-24 14:44
Hi, @Raycoms thank you very much for the answer. Could you send us test which you used to reproduce this exception? I will be very grateful for that.

**Comment by Raycoms** [comment] 2017-05-24 18:11
I think running two of those:
https://github.com/Raycoms/thesis/blob/working/src/main/java/main/java/com/bag/server/database/OrientDBDatabaseAccess.java
Should cause this problem after a certain amount of requests.
My test cases are quite complex and require up to 8 servers to correctly
reproduce, and, I unfortunately don't have the time to create a isolated
test to reproduce it since I have to finish my thesis =)

2017-05-24 11:44 GMT-03:00 Andrey Lomakin <notifications@github.com>:

**Comment by laa** [comment] 2017-05-29 13:25
Hi @Raycoms, unfortunately, I do not see how to run this class. Could you provide a detailed description of steps which you used to reproduce the issue ? We will be glad to repeat them even if your test cases are complex.

**Comment by laa** [comment] 2017-06-13 08:02
Hi @Raycoms , could you kindly provide a testing scenario. Otherwise, it is pretty hard to fix it because we can not reproduce it.

**Comment by laa** [comment] 2017-06-16 08:34
Hi @Raycoms , could you kindly provide a testing scenario. Otherwise, it is pretty hard to fix it because we can not reproduce it.

**Comment by Raycoms** [comment] 2017-06-16 13:00
Sorry guys, I'm super busy with my thesis at the moment, as soon as I
wrapped up the last things I will try to reproduce it and provide you with
an example.

2017-06-16 5:34 GMT-03:00 Andrey Lomakin <notifications@github.com>:

**Comment by laa** [comment] 2017-06-16 15:41
Hi @Raycoms we will be waiting for your case. Thank you very much for the help !

**Comment by laa** [comment] 2017-07-17 16:24
Hi @Raycoms, hope you are doing well.  A small friendly reminder that we are looking forward to receiving detailed information how to reproduce an issue.

**Comment by laa** [comment] 2017-08-14 15:49
Hi @Raycoms, hope you are doing well. A small friendly reminder that we are looking forward to receiving detailed information how to reproduce an issue.

**Comment by laa** [comment] 2017-09-13 13:27
Hi @Raycoms, hope you are doing well. A small friendly reminder that we are looking forward to receiving detailed information how to reproduce an issue.

**Comment by Raycoms** [comment] 2017-09-13 13:36
Okay, it seems like it happens when you access several instances on the
same machine over Java. And the main memory of the machine is exhausted

On Sep 13, 2017 10:27 AM, "Andrey Lomakin" <notifications@github.com> wrote:

Hi @Raycoms <https://github.com/raycoms>, hope you are doing well. A small
friendly reminder that we are looking forward to receiving detailed
information how to reproduce an issue.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/orientechnologies/orientdb/issues/7426#issuecomment-329167352>,
or mute the thread

**Comment by laa** [comment] 2017-09-19 05:52
Hi @Raycoms , could you be more specific. What does it mean " main memory of the machine is exhausted" , how did you detect that memory is exhausted? Do you have OOM or something?

**Comment by laa** [comment] 2017-09-21 12:17
ok, I suppose I will close it for now if you have information which was asked please reopen the issue. We are waiting for about half of the year without any progress, unfortunately ((.

**Closed by laa** 2017-09-21 12:17 UTC
Labels: bug, storage team, waiting reply

**Comment by Raycoms** [comment] 2017-09-21 12:18
Sorry, I'm still quite busy, I know the memory is exhausted because java
started to complain about lack of available memory.

2017-09-21 13:17 GMT+01:00 Andrey Lomakin <notifications@github.com>:
