### ISSUE TITLE
Broken lucene index (fail on reindex, fail on backup)

### ISSUE THREAD

**Issue by nin-jin** [orientechnologies/orientdb#4012] opened 2015-04-24 10:24 UTC
```
PS C:\xxx\db> ./bin/console.bat

OrientDB console v.2.0.8 (build UNKNOWN@r${buildNumber}; 2015-04-22 20:47:49+0000) www.orientechnologies.com
Type 'help' to display all the supported commands.
Installing extensions for GREMLIN language v.2.6.0

orientdb> connect plocal:-/databases/xxx admin admin

Connecting to database [plocal:-/databases/xxx] with user 'admin'...OK
orientdb {db=xxx}> restore database -/backup/xxx-20150419184439.zip

Restoring database database -/backup/xxx-20150419184439.zip...
Error: java.lang.NullPointerException

orientdb {db=xxx}>
```

**Comment by lvca** [comment] 2015-04-24 17:16
Could you provide us the backup file?

**Comment by nin-jin** [comment] 2015-04-27 10:18
I have this errors in log while backuping:

```
- Compressing file luceneIndexes\xxx-service.title\write.lock... [OAutomaticBackup$1$2]
2015-04-27 13:11:48:964 INFO  error: java.io.IOException: Процесс не может получить доступ к файлу, так как часть этого файла заблокирована другим процессом [OAutomaticBackup$1$2]Cannot compress file: C:\xxx\db\.\-\databases\skeddy\luceneIndexes\skeddy-service.title\write.lock
java.io.IOException: Процесс не может получить доступ к файлу, так как часть этого файла заблокирована другим процессом
        at java.io.FileInputStream.readBytes(Native Method)
        at java.io.FileInputStream.read(Unknown Source)
        at com.orientechnologies.common.io.OIOUtils.copyStream(OIOUtils.java:163)
        at com.orientechnologies.orient.core.compression.impl.OZIPCompressionUtil.addFolder(OZIPCompressionUtil.java:142)
        at com.orientechnologies.orient.core.compression.impl.OZIPCompressionUtil.addFolder(OZIPCompressionUtil.java:120)
        at com.orientechnologies.orient.core.compression.impl.OZIPCompressionUtil.addFolder(OZIPCompressionUtil.java:120)
        at com.orientechnologies.orient.core.compression.impl.OZIPCompressionUtil.addFolder(OZIPCompressionUtil.java:120)
        at com.orientechnologies.orient.core.compression.impl.OZIPCompressionUtil.compressDirectory(OZIPCompressionUtil.java:51)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.backup(OLocalPaginatedStorage.java:152)
        at com.orientechnologies.orient.server.distributed.ODistributedStorage.backup(ODistributedStorage.java:1231)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.backup(ODatabaseDocumentTx.java:2525)
        at com.orientechnologies.orient.server.handler.OAutomaticBackup$1.run(OAutomaticBackup.java:158)
        at java.util.TimerThread.mainLoop(Unknown Source)
        at java.util.TimerThread.run(Unknown Source)
[OAutomaticBackup] - Error on exporting database 'plocal:./-/databases/skeddy' to file: ./-/backup/skeddy_2015-04-27_13-11-48.zip
```

Translation: "The process can not access the file because part of the file is locked by another process"

Can you print non localized error messages?

**Comment by nin-jin** [comment] 2015-04-30 15:02
```
2015-04-30 17:55:01:541 INFO  - Rebuilding index xxx.xxx-service.title (estimated 176 items)... [OIndexRebuildOutputListener]Exception in threa
d "Thread-15" java.lang.RuntimeException: java.io.IOException: Cannot overwrite: C:\xxx\db\-\databases\xxx\luceneIndexes\xxx-service.title\_
0.cfs                                                                                                                                                
        at org.apache.lucene.search.ControlledRealTimeReopenThread.run(ControlledRealTimeReopenThread.java:247)                                      
Caused by: java.io.IOException: Cannot overwrite: C:\xxx\db\-\databases\xxx\luceneIndexes\xxx-service.title\_0.cfs                          
        at org.apache.lucene.store.FSDirectory.ensureCanWrite(FSDirectory.java:293)                                                                  
        at org.apache.lucene.store.FSDirectory.createOutput(FSDirectory.java:282)                                                                    
        at org.apache.lucene.store.TrackingDirectoryWrapper.createOutput(TrackingDirectoryWrapper.java:44)                                           
        at org.apache.lucene.store.CompoundFileWriter.getOutput(CompoundFileWriter.java:103)                                                         
        at org.apache.lucene.store.CompoundFileWriter.createOutput(CompoundFileWriter.java:231)                                                      
        at org.apache.lucene.store.CompoundFileDirectory.createOutput(CompoundFileDirectory.java:332)                                                
        at org.apache.lucene.store.Directory.copy(Directory.java:184)                                                                                
        at org.apache.lucene.store.TrackingDirectoryWrapper.copy(TrackingDirectoryWrapper.java:50)                                                   
        at org.apache.lucene.index.IndexWriter.createCompoundFile(IndexWriter.java:4645)                                                             
        at org.apache.lucene.index.DocumentsWriterPerThread.sealFlushedSegment(DocumentsWriterPerThread.java:535)                                    
        at org.apache.lucene.index.DocumentsWriterPerThread.flush(DocumentsWriterPerThread.java:502)                                                 
        at org.apache.lucene.index.DocumentsWriter.doFlush(DocumentsWriter.java:506)                                                                 
        at org.apache.lucene.index.DocumentsWriter.flushAllThreads(DocumentsWriter.java:616)                                                         
        at org.apache.lucene.index.IndexWriter.getReader(IndexWriter.java:370)                                                                       
        at org.apache.lucene.index.StandardDirectoryReader.doOpenFromWriter(StandardDirectoryReader.java:288)                                        
        at org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:263)                                         
        at org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:253)                                         
        at org.apache.lucene.index.DirectoryReader.openIfChanged(DirectoryReader.java:170)                                                           
        at org.apache.lucene.search.SearcherManager.refreshIfNeeded(SearcherManager.java:118)                                                        
        at org.apache.lucene.search.SearcherManager.refreshIfNeeded(SearcherManager.java:58)                                                         
        at org.apache.lucene.search.ReferenceManager.doMaybeRefresh(ReferenceManager.java:176)                                                       
        at org.apache.lucene.search.ReferenceManager.maybeRefreshBlocking(ReferenceManager.java:253)                                                 
        at org.apache.lucene.search.ControlledRealTimeReopenThread.run(ControlledRealTimeReopenThread.java:245)                                      
```

**Comment by lvca** [comment] 2015-04-30 15:29
Looks like a problem of permissions:

    Caused by: java.io.IOException: Cannot overwrite: C:\xxx\db\-\databases\xxx\luceneIndexes\xxx-    service.title\_0.cfs                          
            at org.apache.lucene.store.FSDirectory.ensureCanWrite(FSDirectory.java:293)

**Comment by nin-jin** [comment] 2015-05-01 07:27
All this files and directories was created by OrientDB. I did not change any permissions.

**Comment by nin-jin** [comment] 2015-05-01 07:32
Same problem in JIRA: https://jira.atlassian.com/browse/JRA-42913

**Comment by nin-jin** [comment] 2015-05-01 07:43
http://jarvis.cs.ucdavis.edu/code_essence/functions/60192#n64
"on Windows,attempts to delete or overwrite the files will result in an exception; on other platforms, which typically have a 'delete on last close' semantics, while such operations will succeed, the bytes are still consuming space on disk."

I am using Windows 8.1

**Comment by StarpTech** [comment] 2015-05-01 12:30
I've had the same issue. Try to close orientdb during you perform your backup. AFAIK it happens only on windows.

**Comment by nin-jin** [comment] 2015-05-05 15:28
I am using automatic backup plugin.

**Comment by lvca** [comment] 2015-09-23 22:57
@maggiolo00 is this fixed with the commit of 2 days ago?

**Comment by prjhub** [comment] 2015-10-07 11:43
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.

**Closed by prjhub** 2015-10-07 11:43 UTC
Labels: waiting reply
