### ISSUE TITLE
getting old version of vertex after update :

### ISSUE THREAD

**Issue by udibeck** [orientechnologies/orientdb#5758] opened 2016-02-22 13:45 UTC
steps: 
1. get vertex by id 
2. in transactions update vertex properties
3. calling get vertex by id from another thread return the old data (when we do the call in the same thread the data is correct - the updated)

**Comment by tglman** [comment] 2016-02-23 07:24
hi @udibeck,

if you have a scenario:
```
T1: v1 = getVertex();
T1: v1Id = vi.getId();
T2: v2 = getVertex(v1Id);
T2: v2.setProperty("some","value:);
T2: save(v2);
T2: commit();
T1: v1 = getVertex(v1Id);
// the value in v1 is the same of before the T2 transaction, because of the local cache
T1: v1.getProperty("some");
```
for fix this just call v1.reload() for force the reload of the vertex skipping the cache.

is it this the case ?

**Comment by tglman** [comment] 2016-02-23 07:24
hi @udibeck,

if you have a scenario:
```
T1: v1 = getVertex();
T1: v1Id = vi.getId();
T2: v2 = getVertex(v1Id);
T2: v2.setProperty("some","value:);
T2: save(v2);
T2: commit();
T1: v1 = getVertex(v1Id);
// the value in v1 is the same of before the T2 transaction, because of the local cache
T1: v1.getProperty("some");
```
for fix this just call v1.reload() for force the reload of the vertex skipping the cache.

is it this the case ?

**Comment by udibeck** [comment] 2016-02-23 10:29
Hey,

We looked into the solution but we gave a simple case of one object , 

1. we get the same problem when we do search and get thousand of objects

> T1: v1 = getVertex();
> T1: v1Id = vi.getId();
> T2: v2 = getVertex(v1Id);
> T2: v2.setProperty("some","value:);
> T2: save(v2);
> T2: commit();
search

and then the results are not updated, in this case we can not do reload all the objects

2. another use case with the same problem is in the traverse -  when we updated and link the objects, the traverse function doesn’t return the updated path.

**Comment by tglman** [comment] 2016-02-24 00:44
hi @udibeck,

There is a way to clear the whole cache so you have not this problem:
` graph.getRawGraph().getLocalCache().clear();`

anyway i would like to understand what's your use case and how you use the graph, we usually suggest to do:
```
OrientGraphFactory factory = ....
OrientGraph graph = factory.getTx();
try {
//Do on graph operations
} finally{
   graph.shutdown();
}
```

this block usually match the size of one application transaction. the shutdown clean all the cache and give back the database to the pool so can be reused by other threads.

if you are keeping the graph instance for longer time let's say for all the life of one thread, you may need to clean the cache manually, so we strongly suggest to get an release it from the factory for just the time you need it.

**Comment by udibeck** [comment] 2016-02-25 09:15
hey

We change the code to: 

OrientGraphFactory factory = ....
OrientGraph graph = factory.getTx();
try {
//Do on graph operations
} finally{
   graph.shutdown();
}

it worked fine for a short time and then  we started to get errors about closed database.

Caused by: com.orientechnologies.orient.core.exception.ODatabaseException: Database 'plocal:/opt/orientdb-wlp-node/databases/RuleEngineDB' is closed
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.checkOpeness(ODatabaseDocumentTx.java:2930)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.begin(ODatabaseDocumentTx.java:2186)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.begin(ODatabaseDocumentTx.java:2182)
        at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.begin(OrientTransactionalGraph.java:185)
        at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.<init>(OrientTransactionalGraph.java:73)
        at com.tinkerpop.blueprints.impls.orient.OrientGraph.<init>(OrientGraph.java:131)

**Comment by udibeck** [comment] 2016-02-25 12:58
we also checked:


OrientGraph getGraph(String _dbName, String _userName, String _password) {
  final String dbUrl = OServerMain.server().getStoragePath(_dbName);
  final OPartitionedDatabasePool pool = OServerMain.server().getDatabasePoolFactory().get(dbUrl, _userName, _password);
  
  OrientGraph  result = new OrientGraph(pool);
  result.setAutoStartTx(false);
  return result;
}

---------------------------------------

OrientGraph graph = getGraph(...);
try {

} finally {
  graph.shutdown();
}

after using this code after calling couple of times : getGraph(...) we get the same exception of database closed.


Next We tried to change the parameter of the graph.shutdown() to  graph.shutdown(false) ,
 In this case we return to our original problem that the data is not consist ( return from cache)

**Comment by luigidellaquila** [comment] 2016-02-25 17:06
Hi @udibeck 

Are you using the same graph instance on multiple threads? The problem seems to be related to a multi-threading issue. Please consider that OrientGraph is not thread-safe, so the same instance should not be used concurrently on multiple threads.

Thanks

Luigi

**Comment by udibeck** [comment] 2016-02-25 17:16
hey, we are not using the same graph.
our application is web based application, in every call when we appoint to the DAO (taking thread from the pool, get a new graph , update data and call graph shutdown - all of this in the same transaction ) 

OrientGraph graph = getGraph(...);
try {

} finally {
graph.shutdown();
}

we found the the update works fine but getting the new information is the problem

**Comment by luigidellaquila** [comment] 2016-02-25 17:24
Ok, got it.

Could you please make sure that you are not closing the factory too early in your code?

The best thing would be to have a simple test case to reproduce the problem, it would help me a lot to find the root cause


Thanks

Luigi

**Comment by luigidellaquila** [comment] 2016-02-25 17:24
Ok, got it.

Could you please make sure that you are not closing the factory too early in your code?

The best thing would be to have a simple test case to reproduce the problem, it would help me a lot to find the root cause


Thanks

Luigi

**Comment by udibeck** [comment] 2016-02-25 18:03
hey,

we checked and we are not closing the factory too early, we will try to build a simple test case in order to reproduce the problem.

**Comment by udibeck** [comment] 2016-02-28 17:42
Hey,

We work with multi databases , we created a multifactory connection to the databases and it looks like it solve the problem

**Closed** 2016-03-01 07:55 UTC
Labels: bug
