### ISSUE TITLE
2.0-rc1 - Binary Protocol - Token issue

### ISSUE THREAD

**Issue by Ostico** [orientechnologies/orientdb#3305] opened 2014-12-31 02:57 UTC
The token related to a REQUEST_DB_OPEN command stores information about the opened database.

So, a simple test can be made to get the bad behaviour:

- Connect a client to Orient with root credentials and create a database
- Connect another client to the just created new database, request the token and save the session token somewhere.
- Connect again with root credentials and drop the new database
- Connect the client with previous stored token and do a simple select ( obviously no database is found )

A this point, the server silently close the connection without response to the client breaking the protocol. An exception "no database found" should be raised instead and the token invalidated.

Moreover on a database drop request, all tokens related to that database should be deleted and all connections with a deleted token should be refused with a bad token authentication Exception.

Documentation seems wrong here [Version 27](https://github.com/orientechnologies/orientdb/wiki/Network-Binary-Protocol#version-27):
- if used the token the connections can be shared between users and db of the same server, not needed to have connection associated to db and user.

This is not true if the session is related to the opened database.

**Comment by tglman** [comment] 2015-04-24 14:47
We don't keep any session(in case of token session) server side, that was designed on purpose, and for invalidate all of them you can just change the key, there is no way to invalidate a token for a specific user today, the solution is to put a incremental number that if changed invalidate all the session of that user, but is not implemented yet. can be implemented solution for invalidate also a specific session but this may be out of scope for a database engine.

In case of db not existent we should give an error back, going to check and fix it, for the fact that the connection is dropped is because there is no way to clean the additional data in the socket in the today protocol specification.

About the docs i may need to write them in a better way, the main point is that with token connections are not bound anymore to a specific user/database but could be shared between all the session of specific client and server.

**Comment by Ostico** [comment] 2015-04-24 20:53
I understand, a simple exception ( ie: no database found ) as response, instead of closing the socket should be enough.
The server close the connection before send any data and the header is not already sent, so the socket is clean.

 Is a client matter take the right decision.

**Comment by tglman** [comment] 2015-05-20 14:14
Hi Ostico,

I added the error send in case of token error, but i had to keep there  the close of the connection because the reading channel has some data that wasn't read, this will be solved as soon as i re-factor the network code.

I'm closing this.

**Closed by tglman** 2015-05-20 14:14 UTC
