### ISSUE TITLE
Enable SQL CREATE PROPERTY to set ATTRIBUTES such as NOT NULL,  MANDATORY, and READONLY

### ISSUE THREAD

**Issue by mmacfadden** [orientechnologies/orientdb#5360] opened 2015-11-22 23:17 UTC
Presently quite a few commands are required to create a property in a class that is "not null", "mandatory", or "read only".  For example:

``` SQL
CREATE Property User.username STRING
ALTER PROPERTY User.username MANDATORY true
ALTER PROPERTY User.username NOTNULL true
ALTER PROPERTY User.username READONLY true
```

It would be convenient to be able to do the following (or a mix of the attributes):

``` SQL
CREATE Property User.username STRING MANDATORY NOTNULL READONLY
```

These attributes would come at the end of the statement.  For example if this property was a linked element:

``` SQL
CREATE Property Employee.supervisor LINK Employee MANDATORY NOTNULL READONLY
```

This would make defining properties in SQL much more succinct.  Other properties could be defined as well (DEFAULT, MIN, MAX, etc.). It appears that this change could be made in the OCommandExecutorSQLCreateProperty parse and execute methods.

If this seems like a good feature, I would be willing to create a PR.

**Comment by mmacfadden** [comment] 2015-11-23 00:59
I have an initial stab at this implemented and unit tested.  It's targeted to the develop branch.  I was planning on submitting a PR.  To start, I thought it would be simpler to support just the first three.

**Comment by mmacfadden** [comment] 2015-11-23 03:33
PR #5361 is most likely read to go.  It is failing CI for an issue that is not related to the PR.  Many other PRs are failing for the same reason now.

**Comment by lvca** [comment] 2015-11-23 04:53
Thanks for the PR, @luigidellaquila will look at it soon.

**Comment by mmacfadden** [comment] 2015-11-23 07:06
Thanks.  If this is accepted, I will likely continue it to add a few of the other parameters like DEFAULT, MIN, MAX, REGEX as well.  But wanted to get this incrementally in first since it is the immediate item of interest.

**Comment by smolinari** [comment] 2015-11-23 07:34
:+1: @mmacfadden 

Scott

**Comment by mmacfadden** [comment] 2015-12-15 02:39
@lvca Given that the initial code was merged, would you like me to implement some of the other properties I mentioned above, or do you want to close this out for 2.2?

**Comment by lvca** [comment] 2015-12-15 04:58
@mmacfadden 2.2.0 is closed as features, but you can still work on develop branch so they will be merged for the next release

**Comment by mmacfadden** [comment] 2015-12-15 05:03
@lvca I guess I meant something more specific.  This associated PR has already been merged, and this issues is slated for 2.2.0-beta (according to the milestones).  However this issue hasn't been marked as closed.  So I was wondering if we should just close this issue since its already been merged in and targeted for the 2.2.0 release?

I can open up a new PR in the develop branch for additional functions.  I just wasn't sure why this issue was still open.  I thought perhaps you were waiting for me to add more features.  If the 2.2.0 is some what locked down, then perhaps we should just close this out?

**Comment by lvca** [comment] 2015-12-15 05:16
You're right, this issue is closed :-) Opening a new issue to support additional features is a good idea. Thank you so far.

**Comment by mmacfadden** [comment] 2015-12-15 05:20
Will do.  I will provide a new PR / Issue sometime this week.

**Comment by mmacfadden** [comment] 2016-06-06 13:28
Hello, I just noticed that it looks like the PR that fixed this initial issue was reverted.  Was there a specific reason?  If so I can take a stab at fixing any issues that were there.  Should this issue be reopened?

**Comment by luigidellaquila** [comment] 2016-06-06 14:57
Hi @mmacfadden 

Sure, I'm reopening it now. I think I commented it somewhere, but I don't remember where exactly... the reason of the revert was a problem of coherence in the SQL grammar.

I think adding a comma between the properties will solve the incoherence

Thanks

Luigi

**Comment by mmacfadden** [comment] 2016-06-06 15:06
@luigidellaquila,  Do you mean to say a comma between the various attributes of the property (e.g. MANDATORY, NOTNULL, etc.).  If so I can take a look at that.

**Comment by luigidellaquila** [comment] 2016-06-06 15:09
Yep, exactly. We should also fix the OrientSQL.jjt grammar (in 2.2 also DDL are managed by the new parser), but I can do it easily

Thanks

Luigi

**Comment by mmacfadden** [comment] 2016-06-06 15:11
I am familiar with the grammar and the new parser, so I can take care of that also.  I will look at this asap.  We have a lot of scripts where we are defining schema, this syntax would greatly reduce the length!!

**Comment by mmacfadden** [comment] 2016-06-10 14:21
Can you expand on the syntax you would like to see:

```CREATE PROPERTY test.prop1 STRING, NOTNULL, MANDATORY, READONLY```

or

```CREATE PROPERTY test.prop1 STRING NOTNULL, MANDATORY, READONLY```

Or something else?

**Comment by smolinari** [comment] 2016-06-10 14:34
Why even need commas?

Scott

**Comment by mmacfadden** [comment] 2016-06-10 14:39
@smolinari I am not sure.  The original grammar is this:

```CREATE PROPERTY <class>.<property> <type> [<linked-type>|<linked-class>] [UNSAFE]```

My first attempt simply did this:

```CREATE PROPERTY <class>.<property> <type> [<linked-type>|<linked-class>] [UNSAFE | MANDATORY | READONLY | NOTNULL]```

Apparently there was some issue, but I am not sure what the issue was.

**Comment by luigidellaquila** [comment] 2016-06-10 15:46
Hi guys,

the problem is mainly for LINKLIST, EMBEDDEDLIST and so on, that can have a linked class/type, eg.

```
CREATE PROPERTY Foo.bar LINKLIST MANDATORY
```

In this case, is `MANDATORY` a class name for the linklist or is it the MANDATORY attribute for the property?

A comma will remove the ambiguity:

```
CREATE PROPERTY Foo.bar LINKLIST, MANDATORY
```

Thanks

Luigi

**Comment by mmacfadden** [comment] 2016-06-10 15:52
@luigidellaquila  I see.  Two comments. 1) How was this handled for UNSAFE before? I could do:

```CREATE PROPERTY Foo.bar LINKLIST UNSAFE```

My initial stab at this just followed the same pattern as UNSAFE, where there were no commas

If you would like a comma do we need commas between the attributes themsleves:

e.g. ```CREATE PROPERTY Foo.bar LINKLIST, MANDATORY, READONLY, UNSAFE```

Or is it sufficient to just have the comma separating the properties form the rest?

```CREATE PROPERTY Foo.bar LINKLIST, MANDATORY READONLY NOTNULL```

What about UNSAFE, that didn't require a comma before does that need to be updated?

**Comment by smolinari** [comment] 2016-06-10 16:03
How about also making MANDATORY, READONLY, NOTNULL, UNSAFE etc. reserved words? 

Somehow making a class named MANDATORY reminds me of little Bobby Tables. (although it has nothing really to do with sanitizing database inputs :smile:).

![10-06-_2016_18-00-08](https://cloud.githubusercontent.com/assets/3314957/15970584/921f6ce0-2f35-11e6-8a9c-d43fa9c76872.jpg)




Scott

**Comment by mmacfadden** [comment] 2016-06-10 16:10
@smolinari In my mind this is also a potential option.  Ultimately, I think what we want is the following types of things to work:

```
CREATE PROPERTY Foo.bar Integer MANDATORY
CREATE PROPERTY Foo.bar Integer READONLY
CREATE PROPERTY Foo.bar Integer UNSAFE
CREATE PROPERTY Foo.bar Integer NONNULL
CREATE PROPERTY Foo.bar Integer MIN 5
CREATE PROPERTY Foo.bar Integer MAX 10
CREATE PROPERTY Foo.bar String DEFAULT 0
```

etc. and combinations of them.  So:

```CREATE PROPERTY Foo.bar Integer MANDATORY NONNULL READONLY MIN 5 MAX 4 DEFAULT 0```

I am not so concerned with the placement of commas.  Also, can't you use backticks or quotes if you wanted to make a class named mandatory and use it.  Something like

```CREATE PROPERTY Foo.bar LINKLIST `MANDATORY` MANDATORY```

Again, I would point out that I assume we were already in this situation with the UNSAFE keyword.

**Comment by luigidellaquila** [comment] 2016-06-10 16:23
Little Bobby Tables is always in my heart 😆 

I think UNSAFE just didn't work ;-) 
What I'm trying to do with the new grammar is to make things as strict as possible, to avoid corner cases and have predictable behavior.

Adding new reserved keywords is an option, but it can make migrations very tricky, so I always try to avoid it if I can, in this case I think commas are an acceptable alternative.

Thanks

Luigi

**Comment by mmacfadden** [comment] 2016-06-10 16:27
@luigidellaquila Can you comment on this one:

https://github.com/orientechnologies/orientdb/issues/5360#issuecomment-225221102

Given an answer I can get it going.

**Comment by luigidellaquila** [comment] 2016-06-10 16:32
Right:
1) I just checked, there is no need of commas for UNSAFE because it is a reserved keyword (I had to make it reserved because it's already used in too many places...)

2) I'd prefer the following:
```
CREATE PROPERTY Foo.bar LINKLIST, MANDATORY, READONLY UNSAFE
```
with commas that separate property constraints and with UNSAFE at the end, without the comma, but maybe we can also allow a comma before UNSAFE... Actually in terms of language consistency it makes no big difference, it's just a matter of personal preferences, so please comment on this and let's find the best solution together

Thanks

Luigi

**Comment by mmacfadden** [comment] 2016-06-10 16:40
@luigidellaquila Thanks.  Great thoughts.  It's nice to really understand where you are coming from.  I now know what the main issue is.  There are a couple options.  I do think the commas look somewhat ugly and unbalanced.  Like you said, its just personal preference though.  What if we groupd the properties in parenthesis.  Like so:

```CREATE PROPERTY Foo.bar LINKLIST (MANDATORY, READONLY, NOTNULL) UNSAFE```

```CREATE PROPERTY Foo.bar INTEGER (MANDATORY, READONLY, NOTNULL, MAX 5, DEFAULT 1) UNSAFE```

Now, the properties are clearly grouped in a nice neat list bound by parens.  Separated from both the type (class) and unsafe.  The whole (...) block is optional so is backwards compatible.

Thoughts?

**Comment by smolinari** [comment] 2016-06-11 05:09
I don't like the mix with UNSAFE hanging out in the wind like that. I'm for the pure comma solution, if commas must be there to avoid having more reserved words. Notice though below, I don't have a comma after `LINKLIST`. Not sure that is important, but I find it cleaner. 

`CREATE PROPERTY Foo.bar LINKLIST MANDATORY, READONLY, UNSAFE`

That would mean a single attribute would look like this.

 `CREATE PROPERTY Foo.bar LINKLIST READONLY`

I also like the back ticks for denoting the class name. Notice too how the missing comma helps keep it cleaner with the class name. How would you do it otherwise?

`CREATE PROPERTY Foo.bar LINKLIST `Mandatory` MANDATORY, READONLY, UNSAFE`

That looks really clean to me. But, that is just me. :smile: 

Also, what about `DEFAULT`? Can we have this?

`CREATE PROPERTY Foo.bar STRING DEFAULT='Hello world!'`

Or with multiple attributes

`CREATE PROPERTY Foo.bar STRING MANDATORY, DEFAULT='Hello world!'`

Scott

**Comment by mmacfadden** [comment] 2016-06-11 18:43
@smolinari A couple things.  

1. As you see here [https://github.com/orientechnologies/orientdb/issues/5360#issuecomment-225225952](https://github.com/orientechnologies/orientdb/issues/5360#issuecomment-225225952), Default is already part of the proposal.

2. I think we have gotten of track with the commas.  The only reason for having the commas at all is to separate them from the potential class / type name, to disambiguate things like MANDATORY and READONLY from Types/Classes.

As @luigidellaquila pointed out in this scenario:

```CREATE PROPERTY Foo.bar LINKLIST MANDATORY```

Is MANDATORY a class name or a property?  Hard for the parser to tell.  So his solution was to separate the part of the query that sets up the name and type of the property from the part that sets attributes with a comma. 

```CREATE PROPERTY Foo.bar LINKLIST, MANDATORY, READONLY``` 

Technically it is only the first comma is the only one that 'really' matters.  The following would disambiguate just as much.

```CREATE PROPERTY Foo.bar LINKLIST, MANDATORY READONLY NOTNULL```
vs.
```CREATE PROPERTY Foo.bar LINKLIST MANDATORY, READONLY NOTNULL```  

In the first case, MANDATORY is an attribute, where as in the second case it is a class name.  Now if we make these properties MANDATORY, NOTNULL, READONLY, MAX, MIN, DEFAULT, etc. reserved keywords, then we don't need commas at all.

```CREATE PROPERTY Foo.bar LINKLIST MANDATORY READONLY NOTNULL```
We know that this is the key word.

```CREATE PROPERTY Foo.bar LINKLIST `MANDATORY` READONLY NOTNULL```
We know that this is a class name, and we don't need commas at all to disambiguate.  So we don't need backquotes and commas.  That essentially duplicates multiple approaches to disambiguation.

Also UNSAFE is semantically different than everything else.  It is not an attribute of the property at all.  It doesn't help specify the name, type, or constraints of the property.  It's not part of the definition of the property.  It is simply an instruction to the database whether to check the existing records when running this command.  It's semantically different than the whole rest of the command.  So to me it makes a lot of sense to keep syntactically separate from the rest of the command.

Give all of this, I am going to try a couple different syntaxes and we can see what we like.  The main effort is going to be getting the functionality right, and then we can tweak the syntax if we need to without to much trouble.

**Comment by smolinari** [comment] 2016-06-12 11:46
Hmmm..ok. I understand the situation better. 

Like I said, I like the reserved word route the best. :smile: That way, there is no uncertainty, no ambiguation and no need for a separator. I do believe the parser would also be easier to build. So...

This won't work.

`CREATE PROPERTY Foo.bar LINKLIST Manditory MANDATORY, READONLY NOTNULL`

This will.

`CREATE PROPERTY Foo.bar LINKLIST MyMandatoryClass MANDATORY, READONLY NOTNULL`

Is this the list that holds ODB's reserved word list? http://orientdb.com/docs/2.2/SQL-Syntax.html If yes, could it be outdated? UNSAFE is missing. 

Scott

**Comment by luigidellaquila** [comment] 2016-06-13 07:23
Hi guys,

Thanks for the comments, @mmacfadden waiting for your experiments :) please let me know if you need help.

@smolinari good point, I'm updating the docs

Thanks

Luigi

**Comment by francisco1844** [comment] 2016-06-26 17:33
Shouldn't things like min/max be "check constraints" instead of property attributes? In my mind anything we can do that is similar to the SQL standards makes it easier for newcomers, like myself, to get up to speed.

**Comment by mmacfadden** [comment] 2016-06-26 17:40
@Francisco that is a good idea, but I think a separate overall issue from this one.  MIN and MAX are already defined semantically in OrientDB.  This is just updating the create property to allow setting those things.  What you are talking about is creating an entirely new semantic.  E.g. a check constraint, which I would assume would be a expression that would be checked on insert / update.  I think that this is an interesting and more powerful idea than the current MIN / MAX attributes.  I would recommend adding a separate issue, that might be appropriate for 3.x.

**Comment by francisco1844** [comment] 2016-06-26 18:19
Thanks for the feedback @mmacfadden. Will create a new issue.

**Closed** 2021-08-04 14:53 UTC
Labels: enhancement
