### ISSUE TITLE
[2.1-rc6] Can't import graph with circular references

### ISSUE THREAD

**Issue by bmcgavin** [orientechnologies/orientdb#4713] opened 2015-08-03 14:18 UTC
Given this data : https://gist.github.com/bmcgavin/9add5667812fdf3d7bf6 and this ETL import json : https://gist.github.com/bmcgavin/908445dbab47c929cb19

I would expect to be able to create a graph that has two article vertices and two link edges, one going from article 1 to article 2, and one going from article 2 to article 1.

This works as expected on 2.0.13 and 2.1-rc2.

However on 2.1-rc6 I get this output : 

```
root@local:/home/vagrant# /data/orientdb/bin/oetl.sh /home/vagrant/bugreport_testcase_load_minimal.json
OrientDB etl v.2.1-rc6 (build @BUILD@) www.orientdb.com

2015-08-03 14:10:42:789 WARNI Not enough physical memory available for DISKCACHE: 1,002MB (heap=247MB). Set lower Maximum Heap (-Xmx setting on JVM) and restart OrientDB. Now running with DISKCACHE=256MB [orientechnologies][orientdb] INFO Dropping existent database 'plocal:/data/orientdb_databases/bugreport'...
BEGIN ETL PROCESSOR
[file] DEBUG Reading from file /home/vagrant/bugreport_testcase_minimal.json
[orientdb] DEBUG - OrientDBLoader: created vertex class 'Article' extends 'V'
[orientdb] DEBUG orientdb: found 0 vertices in class 'null'
[orientdb] DEBUG - OrientDBLoader: created property 'Article.articleId' of type: string
[orientdb] DEBUG - OrientDocumentLoader: created index 'Article.articleId' type 'UNIQUE_HASH_INDEX' against Class 'Article', fields [articleId:string]
+ extracted 0 entries (0 entries/sec) - 0 entries -> loaded 0 vertices (0 vertices/sec) Total time: 1001ms [0 warnings, 0 errors]
[0:merge] DEBUG Transformer input: {articleId:1,linkedArticles:[1]}
[0:merge] DEBUG joinValue=1, lookupResult=null
[0:merge] DEBUG Transformer output: {articleId:1,linkedArticles:[1]}
[0:vertex] DEBUG Transformer input: {articleId:1,linkedArticles:[1]}
[0:vertex] DEBUG Transformer output: v(Article)[#11:0]
[0:edge] DEBUG Transformer input: v(Article)[#11:0]
[0:edge] DEBUG joinCurrentValue=2, lookupResult=null
[0:edge] DEBUG created new vertex=Article#11:1{articleId:2} v1
[0:edge] DEBUG created new edge=e[#12:0][#11:0-Link->#11:1]
[0:edge] DEBUG Transformer output: v(Article)[#11:0]
[0:field] DEBUG Transformer input: v(Article)[#11:0]
[0:field] DEBUG removed linkedArticles (value=[2]) from document=Article#11:0{articleId:1,linkedArticles:null,out_Link:[#12:0]} v2
[0:field] DEBUG Transformer output: v(Article)[#11:0]
[1:merge] DEBUG Transformer input: {articleId:2,linkedArticles:[1]}
[1:merge] DEBUG joinValue=2, lookupResult=Article#11:1{articleId:2,in_Link:[#12:0]} v2
[1:merge] DEBUG merged record Article#11:1{articleId:2,in_Link:[#12:0],linkedArticles:[1]} v2 with found record={articleId:2,linkedArticles:[1]}
[1:merge] DEBUG Transformer output: Article#11:1{articleId:2,in_Link:[#12:0],linkedArticles:[1]} v2
[1:vertex] DEBUG Transformer input: Article#11:1{articleId:2,in_Link:[#12:0],linkedArticles:[1]} v2
[1:vertex] DEBUG Transformer output: v(Article)[#11:1]
[1:edge] DEBUG Transformer input: v(Article)[#11:1]
[1:edge] DEBUG joinCurrentValue=1, lookupResult=Article#11:0{articleId:1,out_Link:[#12:0]} v3
Error in Pipeline execution: java.lang.IllegalArgumentException: destination vertex is null
java.lang.IllegalArgumentException: destination vertex is null
	at com.tinkerpop.blueprints.impls.orient.OrientVertex.addEdge(OrientVertex.java:888)
	at com.tinkerpop.blueprints.impls.orient.OrientVertex.addEdge(OrientVertex.java:832)
	at com.orientechnologies.orient.etl.transformer.OEdgeTransformer.createEdge(OEdgeTransformer.java:184)
	at com.orientechnologies.orient.etl.transformer.OEdgeTransformer.executeTransform(OEdgeTransformer.java:109)
	at com.orientechnologies.orient.etl.transformer.OAbstractTransformer.transform(OAbstractTransformer.java:37)
	at com.orientechnologies.orient.etl.OETLPipeline.execute(OETLPipeline.java:114)
	at com.orientechnologies.orient.etl.OETLProcessor.executeSequentially(OETLProcessor.java:487)
	at com.orientechnologies.orient.etl.OETLProcessor.execute(OETLProcessor.java:291)
	at com.orientechnologies.orient.etl.OETLProcessor.main(OETLProcessor.java:161)
ETL process halted: com.orientechnologies.orient.etl.OETLProcessHaltedException: java.lang.IllegalArgumentException: destination vertex is null
```

**Comment by goruha** [comment] 2015-08-07 12:12
+1 Have the same issue

**Comment by fc7** [comment] 2015-08-08 07:55
Same thing here, though in my case I do not even have circular references, only edges connecting different vertices of the same class. No problem on 2.0.12

**Comment by fc7** [comment] 2015-09-10 11:31
I have found the cause and will submit a pull request.

**Comment by lvca** [comment] 2015-09-21 17:30
The PR is merged, closing this issue. Thanks.

**Closed by lvca** 2015-09-21 17:30 UTC

**Comment by cosimosimeoneTR** [comment] 2015-10-02 08:37
Hi there Guys! 
When will this bug fix be released?

```
debBase:~/myCode$ oetl.sh /home/user/myCode/orientdb_bugreport_testcase_load.json
OrientDB etl v.2.1.2 (build @BUILD@) www.orientdb.com
BEGIN ETL PROCESSOR
[*SNIP*]
Error in Pipeline execution: java.lang.IllegalArgumentException: destination vertex is null
java.lang.IllegalArgumentException: destination vertex is null
        at com.tinkerpop.blueprints.impls.orient.OrientVertex.addEdge(OrientVertex.java:888)
        at com.tinkerpop.blueprints.impls.orient.OrientVertex.addEdge(OrientVertex.java:832)
        at com.orientechnologies.orient.etl.transformer.OEdgeTransformer.createEdge(OEdgeTransformer.java:188)
        at com.orientechnologies.orient.etl.transformer.OEdgeTransformer.executeTransform(OEdgeTransformer.java:109)
        at com.orientechnologies.orient.etl.transformer.OAbstractTransformer.transform(OAbstractTransformer.java:37)
        at com.orientechnologies.orient.etl.OETLPipeline.execute(OETLPipeline.java:114)
        at com.orientechnologies.orient.etl.OETLProcessor.executeSequentially(OETLProcessor.java:487)
        at com.orientechnologies.orient.etl.OETLProcessor.execute(OETLProcessor.java:291)
        at com.orientechnologies.orient.etl.OETLProcessor.main(OETLProcessor.java:161)
ETL process halted: com.orientechnologies.orient.etl.OETLProcessHaltedException: java.lang.IllegalArgumentException: destination vertex is null
```

Cheers!
