### ISSUE TITLE
OObjectLazyList can not be looped using a Stream

### ISSUE THREAD

**Issue by diegomtassis** [orientechnologies/orientdb#7535] opened 2017-07-07 12:20 UTC
### Java Version: 8  

OObjectLazyList instances returned by the object API can not be streamed (initially).

The following IT reproduces the bug.
https://github.com/CompartAG/orientdb-tryouts/blob/master/2.2.x/src/test/java/com/compart/tec/orientdb/object/OObjectLazyListRegressionIT.java

**Comment by tglman** [comment] 2017-07-10 09:47
hi @diegomtassis,

thank you to report this, we will check it soon.

Regards

**Comment by tglman** [comment] 2017-07-10 14:24
hi @diegomtassis,

I cannot really fix this in 2.2.x, the issue is that OObjectLazyList extends ArrayList, that in java 8 has a specialized implementation of splitIterator, to fix this I should override the splitIterator implementation, but in 2.2.x we are compatible to jdk 1.6+ so I cannot refer to `java.util.Spliterator` that exists only from java 8.

I Can fix this in 3.x anyway.

**Comment by tglman** [comment] 2017-07-10 15:22
hi,

Pushed the fix with the relative test case in develop branch.

Bye

**Comment by diegomtassis** [comment] 2017-07-11 09:01
thanks

**Comment by tglman** [comment] 2017-07-11 11:17
hi @diegomtassis,

Do you need a fix for 2.2.x or can we close this issue ?

Regards

**Comment by diegomtassis** [comment] 2017-07-19 14:33
What we are doing is to remember not to use the stream interface with Lists returned from the object API.

If this can be fixed in 2.2.x it is easier for us, but in any case it is not blocking.

**Comment by lvca** [comment] 2017-08-05 07:01
Workaround available, closing the issue because it's already fixed in 3.0.

**Closed by lvca** 2017-08-05 07:01 UTC
