### ISSUE TITLE
Multiple statement functions - new problems in 3.03, worked in 3.0.0?

### ISSUE THREAD

**Issue by keith-hinde** [orientechnologies/orientdb#8379] opened 2018-07-05 13:06 UTC
## Expected behavior  
In version 3.0.0, I was able to create and use functions which comprised several statements - similar to stored procedures, e.g.

```
let entity = SELECT FROM Entity WHERE entityId = :entityId;
IF ($entity.size() == 0) { return "entity_not_found"; }
```

But since a move to 3.0.3, these refuse to work, issuing a parse error.

## Actual behavior  
```
{
    "errors": [
        {
            "reason": 400,
            "code": 400,
            "content": "Error parsing query:<exact query contents removed>...Encountered \" \"#\" \"# \"\" at line 2, column 1. Was expecting: <EOF> DB name="<db removed>" Error Code="1"
        }
    ]
}
```

## Steps to reproduce  
Add a multi-line function similar to above with a parameter, try to run a test through the console (or REST api, which also fails) and get a parse error.

Any suggestions?

**Comment by luigidellaquila** [comment] 2018-07-05 13:08
Hi @keith-hinde 

Thank you for reporting, I think I know where the problem is.
I'll fix it asap

Thanks

Luigi

**Comment by luigidellaquila** [comment] 2018-07-06 11:04
Hi @keith-hinde 

I just pushed a fix, now batch scripts work fine in SQL functions

Thanks

Luigi

**Closed** 2018-07-06 11:15 UTC
Labels: bug
