### ISSUE TITLE
after truncate class command , the select from command shows the deleted records in result .

### ISSUE THREAD

**Issue by saeedtabrizi** [orientechnologies/orientdb#6530] opened 2016-08-05 12:20 UTC
## OrientDB Version, operating system, or hardware.
v2.2.5

## Operating System
- Windows
 

## Expected behavior and actual behavior
expect return empty array in result but returns the deleted records in result .
## Steps to reproduce the problem
1. create a class named by 'Invoice' and insert 5 records to it .
2. `select from Invoice`; -> returns 5 record and it's true  .
3. `truncate  class Invoice` -> must delete all of records in Invoice class now .
4. `select from Invoice` -> shows the deleted record !!! its not true . 
5. i guess the query result has been cached so i restart my oriendb service .
6. run `select from Invoice` -> shows the empty array and its true !!!  

i guess there is a bug in query caching mechanism . 

Thanks
Saeed Tabrizi

**Comment by luigidellaquila** [comment] 2016-08-05 12:43
Hi @saeedtabrizi 

do you have the command cache enabled?

Thanks

Luigi

**Comment by saeedtabrizi** [comment] 2016-08-06 08:51
Hi @luigidellaquila 
Yes its enabled.

Thanks 
Saeed

**Comment by luigidellaquila** [comment] 2016-08-06 08:56
Hi @saeedtabrizi 

Thank you for confirming this, I think I know where the problem is, I'll fix it asap

Thanks

Luigi

**Comment by luigidellaquila** [comment] 2016-08-09 07:57
Hi @saeedtabrizi 

I just pushed a fix on both 2.2.x and develop.
Please let me know if it fixes your problem

Thanks

Luigi

**Closed by luigidellaquila** 2016-08-09 07:57 UTC
Labels: bug

**Comment by saeedtabrizi** [comment] 2016-09-19 16:45
Hi @luigidellaquila 
I test it in 2.2.10 and works fine .
Thanks 
Saeed Tabrizi
