### ISSUE TITLE
Property case insensitive settings ignored when IN/OUT is used in WHERE

### ISSUE THREAD

**Issue by petervavro** [orientechnologies/orientdb#7356] opened 2017-04-21 21:53 UTC
## Expected behavior  
Query : SELECT name, out('InsidePlace').name AS placeName FROM Point WHERE out('InsidePlace').name CONTAINSTEXT 'c'
Query should return records with uppercase "C" because collate in property is set to Case Insensitive.

## Actual behavior  
Query does not return records with uppercase "C".

<img width="1666" alt="screen shot 2017-04-21 at 16 48 47" src="https://cloud.githubusercontent.com/assets/4742672/25297336/a5a0361c-26b2-11e7-97d8-9627e775fd04.png">

<img width="1665" alt="screen shot 2017-04-21 at 16 49 11" src="https://cloud.githubusercontent.com/assets/4742672/25297338/ac392fc4-26b2-11e7-8da4-bb5df3e203d1.png">

## Steps to reproduce  
<img width="1657" alt="screen shot 2017-04-21 at 16 34 06 1" src="https://cloud.githubusercontent.com/assets/4742672/25297214/067163c2-26b2-11e7-91ba-1ae400ef625f.png">

<img width="1643" alt="screen shot 2017-04-21 at 16 34 20" src="https://cloud.githubusercontent.com/assets/4742672/25297229/154be692-26b2-11e7-9a79-31fa277800d0.png">

<img width="1639" alt="screen shot 2017-04-21 at 16 34 51" src="https://cloud.githubusercontent.com/assets/4742672/25297237/1ee8c31e-26b2-11e7-8440-4f7ac87e8d54.png">

<img width="1667" alt="screen shot 2017-04-21 at 16 36 07" src="https://cloud.githubusercontent.com/assets/4742672/25297242/23496062-26b2-11e7-8820-fb8fd06ec306.png">

**Comment by luigidellaquila** [comment] 2017-05-02 12:56
Hi @petervavro 

This is a duplicate of https://github.com/orientechnologies/orientdb/issues/4827

I'm closing this one, please monitor the existing issue for updates

Thanks

Luigi

**Closed by luigidellaquila** 2017-05-02 12:56 UTC
Labels: bug
