### ISSUE TITLE
ORecordDuplicatedException upon new record after cluster has been truncated but index still has it

### ISSUE THREAD

**Issue by mecp** [orientechnologies/orientdb#5448] opened 2015-12-10 10:32 UTC
```java
com.orientechnologies.orient.core.storage.ORecordDuplicatedException: Cannot index record Some_Class{xxxxx}: found duplicated key 'xxxxx' in index 'some_key' previously assigned to the record #28:0 RID=#28:0
	at com.orientechnologies.orient.core.index.OIndexTxAwareOneValue.checkEntry(OIndexTxAwareOneValue.java:224)
	at com.orientechnologies.orient.core.index.OClassIndexManager.checkIndexedPropertiesOnCreation(OClassIndexManager.java:341)
	at com.orientechnologies.orient.core.index.OClassIndexManager.checkIndexes(OClassIndexManager.java:585)
	at com.orientechnologies.orient.core.index.OClassIndexManager.onRecordBeforeCreate(OClassIndexManager.java:410)
	at com.orientechnologies.orient.core.hook.ODocumentHookAbstract.onTrigger(ODocumentHookAbstract.java:226)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.callbackHooks(ODatabaseDocumentTx.java:1069)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1966)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:159)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2568)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:121)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1768)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1759)
```

We face this issue when we truncate the clusters upon application restart and we add a record which previously existed(meaning a new record with same key as before) but it fails because index still has the record from past. 

For our application it is okay to clear the index upon start, so we can solve the issue currently by clearing the index using 
```java
OIndex.clear();
```
Though we have solution for us but issue seems important in general.

**Comment by luigidellaquila** [comment] 2015-12-10 10:49
Hi @mecp 

which version are you using? If it's 2.1.7 it's definitely a bug.

Thanks

Luigi

**Comment by mecp** [comment] 2015-12-10 11:00
We are using 2.1.7

regards.

**Comment by laa** [comment] 2016-02-23 12:21
Hi @mecp .
How did you truncate cluster ?
By call of com.orientechnologies.orient.core.metadata.schema.OClassImpl#truncate or directly through com.orientechnologies.orient.core.storage.OCluster#truncate ?

In case of last one , that is expected behaviour, because cluster does not know anything about indexes and indexes are managed on higher class level.

**Comment by mecp** [comment] 2016-02-24 05:25
That's how we truncate the cluster.

```java
db.command(new OCommandSQL("truncate cluster " + clusterName)).execute();
````

This issue was marked **next hotfix** at 2.1.7, It's 2.1.11 already but reply came only yesterday. Anyway for us it is not urgent as I had mentioned, because in our use case we have a workaround.

> How did you truncate cluster ?
> By call of com.orientechnologies.orient.core.metadata.schema.OClassImpl#truncate or directly through com.orientechnologies.orient.core.storage.OCluster#truncate ?

Related to above question, I would like to suggest that the Java Native API should have clearly documented boundaries for user APIs and internal-only APIs.

**Comment by laa** [comment] 2016-02-24 06:42
Well , about next hotfix milestone. It means next hotfix after it will be fixed by developer.
If you need next hotfix in literally next released hotfix I suggest you to subscribe to commercial support.

About issue itself, you should use 

`db.command(new OCommandSQL("truncate class " + className)).execute();`

For the reason declared above.
>I would like to suggest that the Java Native API should have clearly documented boundaries for user APIs and internal-only APIs.
We are working on the way to separate this API.
I am closing this issue but if solution will not work for you, I will appreciate if you reopen it.

**Comment by mecp** [comment] 2016-02-24 07:49
> Well , about next hotfix milestone. It means next hotfix after it will be fixed by developer.
> If you need next hotfix in literally next released hotfix I suggest you to subscribe to commercial support.

No as I told it was only for understanding purposes, thanks for clarification.

> 
> About issue itself, you should use
> 
> db.command(new OCommandSQL("truncate class " + className)).execute();

Why should I use your suggestion when what I want is to truncate a cluster only, but not all the data from a class, wouldn't I loose all the class data instead of just a cluster if I do what you suggest? And why should records from a truncated cluster have an entry in some index, shouldn't process of truncating the cluster also remove those records from indexes?

**Comment by laa** [comment] 2016-02-29 11:19
Well you persuaded me, I will fix this issue in couple of hours.

**Comment by laa** [comment] 2016-03-01 14:52
Fixed

**Closed by laa** 2016-03-01 14:52 UTC
Labels: bug, in progress

**Comment by mecp** [comment] 2016-03-03 03:07
Thanks. :+1:
