### ISSUE TITLE
OutOfMemory due to hanging client(?)

### ISSUE THREAD

**Issue by smil2k** [orientechnologies/orientdb#6499] opened 2016-08-02 17:50 UTC
## OrientDB Version, operating system, or hardware.
- v2.2.5, 2.2.7

## Operating System
- [x] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior

We experienced a memory leak / out-of-memory error. Looking at the heap dump a bufferedoutputstream took all the memory:
[big.zip](https://github.com/orientechnologies/orientdb/files/397737/big.zip)

Heapdump is available on request.

Most likely the client was disconnected or blocked or simply very slow, and orient stored the data in memory.

Side node:
How can I figure out which query needed  500mb data to be transferred?

**Comment by laa** [comment] 2016-08-03 14:25
All memory is consumed by binary protocol objects assigned to @tglman .

**Comment by tglman** [comment] 2016-08-05 13:11
hi @smil2k,

I just made a fix that help clean up invalid session also when the socket remain open for long time, from your domp seems that there were a lot of session in memory, anyway did you change any limit of maximun connection or similar ?

the fix should be out in 2.2.7

**Comment by smil2k** [comment] 2016-08-05 15:30
Hi,

I did not change anything particular from the default settings.
I've just looked into the dump again and seen than orient had 26k
OClientSessions/Connection objects.
We don't use that many for sure.

Why are they accumulating?
How can you monitor the amount of them?

We use OPartitionedDatabasePool to acquire the connection to the DB, and
always close the resulting DB connection:

    public void executeCommand(Consumer<ODatabaseDocumentTx> command,
OTransaction.TXTYPE type) {
        ODatabaseDocumentTx db = getPool().acquire().begin(type);
        try {
            command.accept(db);
        } finally {
            db.close();
        }
    }

Cheers,

Tamas



tglman <notifications@github.com> ezt írta (időpont: 2016. aug. 5., P,
15:11):

**Comment by tglman** [comment] 2016-08-11 13:17
hi @smil2k,

We did some refactor in session management in 2.2.7, this should be solved, i'm closing.

**Comment by smil2k** [comment] 2016-08-25 12:49
Hi,

The fix made issues worse/more visible on 2.2.7:

2016-08-25 12:09:17:232 WARNI Reached maximum number of concurrent connections (max=1000, current=6153), reject incoming connection from /172.20.0.12:41276 [OServerNetworkListener]

According to netstat NO TCP connection is active towards orientdb!
(JMap dump available on demand.)

It seems that sessions are never savaged. Looking at the dump:
0 expired at Mon Aug 22 2016 15:21:57 GMT+0200 (CEST) (49 hrs 29 mins 58 sec)
1 expired at Wed Aug 24 2016 10:49:19 GMT+0200 (CEST) (6 hrs 2 mins 36 sec)
2 expired at Wed Aug 24 2016 11:17:49 GMT+0200 (CEST) (5 hrs 34 mins 6 sec)
3 expired at Mon Aug 22 2016 14:45:07 GMT+0200 (CEST) (50 hrs 6 mins 49 sec)
4 expired at Mon Aug 22 2016 13:50:48 GMT+0200 (CEST) (51 hrs 1 mins 7 sec)
5 expired at Wed Aug 24 2016 10:35:14 GMT+0200 (CEST) (6 hrs 16 mins 42 sec)
6 expired at Tue Aug 23 2016 11:04:49 GMT+0200 (CEST) (29 hrs 47 mins 6 sec)
7 expired at Tue Aug 23 2016 17:26:44 GMT+0200 (CEST) (23 hrs 25 mins 12 sec)
8 expired at Tue Aug 23 2016 11:09:25 GMT+0200 (CEST) (29 hrs 42 mins 30 sec)

All of the session tokens were expired! (OClientSessions.token.valid == false)

Is there a savage thread, which deletes the old sessions?

Cheers,

Tamas

**Comment by smil2k** [comment] 2016-08-25 12:50
status:open

**Comment by tglman** [comment] 2016-08-25 12:56
Fi @smil2k,

Yes we have a thread that clean up the session that are expired, going to double check if there are all the needed check, not only for expired sessions, but for the one that may not be opened correctly.

**Comment by smil2k** [comment] 2016-08-25 13:32
hi,

Looking at the dump again, we have 19809 OClientConnection instances. 
The difference between "since" and "stats.lastCommandReceived" is around 0 ms. It seems that a connection is made per command. Many of them executed only 1-5 requests and then die. There are some connections though with fairly high task count though.

Additionally connection seems to be kept for 1 hour:
19805 conn at Wed Aug 24 2016 16:08:31 GMT+0200 (CEST) (0 hrs 43 mins 24 sec) 
expired at Wed Aug 24 2016 16:40:56 GMT+0200 (CEST) (0 hrs 10 mins 59 sec)

Can I lower this amount?

Cheers,

Tamas

**Comment by tglman** [comment] 2016-08-25 14:56
hi @smil2k,

Yes most the timeout of a connection is 1h, so that why you see that, as far as i understood in some case of handshaking failure the sessions are not properly cleaned up, so i'm trying to identify the case and fix it.

regards

**Comment by tglman** [comment] 2016-08-25 14:56
hi @smil2k,

Yes most the timeout of a connection is 1h, so that why you see that, as far as i understood in some case of handshaking failure the sessions are not properly cleaned up, so i'm trying to identify the case and fix it.

regards

**Comment by smil2k** [comment] 2016-08-25 15:05
I have a tool which can scan through the dump file. Tell me if you want to check attributes or anything.

**Comment by tglman** [comment] 2016-08-25 17:54
hi @smil2k, 

I figured out what was the cause, in case of a request with invalid token the session was not cleaned up, i fixed that right now.

Thanks anyway

Regards

**Comment by smil2k** [comment] 2016-08-26 07:16
In case of restarts, we did not restarted the clients, so they were throwing invalid tokens at the beginning, good catch.

Still I'm not convinced, that this is the root of the issue. I'm thinking along the line of the web manger. Sometimes I leave the manager open, which pings the server periodically. Last time I left it open for a day, and we got the error much much earlier.
Can you check whether the connections used for hearth beat are cleared up?

This plays along with the fact, that we had 6k sessions and 19k connections. Session tokens were all old. The tokens in the connection were mostly ok.

Cheers,

Tamas

**Comment by tglman** [comment] 2016-08-26 09:29
Hi,

The reason is actually the restart of the server, we use for sign tokens a key randomly generated at server startup, when you restart the server the key is regenerated but all the client try to send tokens signed with the old key, that was causing the problem.

**Comment by smil2k** [comment] 2016-08-26 10:22
Yes, but the clients are using 10 something connections. After a while they throw out old connections and use them. Still we had much much more connections on the server side and none in the client side.

Additionally look at the error: 1000 connection allowed and we have 6k! The other connections must come from "inside" I guess.

**Comment by tglman** [comment] 2016-08-30 10:59
hi @smil2k,

Well, the instances of OClientConnection are note the same of the connections(sockets) but they correspond more to de sessions that you open, that said in a different way correspond to how many instances of `ODatabaseDocument` you have in the client, as well we have some retry logic that would have created more "invalid session" than what are actually in the client.

In any case most if most of the session in your dump have the flag isValid set to false, they came from the flow i just fixed.

the fix will be released in 2.2.9

**Comment by smil2k** [comment] 2016-08-30 13:33
Invalid / Valid:
45/19809

There is another problem with the client library causes much bigger problem!

13656 of the connections has no session! 
(
var sess = factory.findAll("com.orientechnologies.orient.server.OClientSessions");
var s = new java.util.HashSet();
for (i in sess) { s.addAll(sess[i].connections); }
var ns = new java.util.ArrayList();
var conn = factory.findAll("com.orientechnologies.orient.server.OClientConnection");
for (c in conn) { if ( s.contains(conn[c]) ==false) { ns.add(conn[c]); } }
---ns.size() == 13656
var inv=0; for (n in ns) { if (ns[n].token.valid == false) inv++ };
-- inv = 0

I think the connection close is not cleanly done! 

Additionally I doubt that the 6k sessions is ok, as non of the sessions has a valid token: (maybe it is all right)
var inv=0; for (n in sess) { if (sess[n].token.valid == false) inv++ };
--inv=6153

Could you please look into this part of the code as well?

Thanks,

Cheers,

Tamas

**Comment by lvca** [comment] 2016-09-03 04:16
@tglman is this issue the same are you working now?

**Comment by mikayeln** [comment] 2016-09-06 08:26
Hi @tglman,

I've just tried the server from branch 2.2.x. The problem with growing OClientConnection map (sometimes extremely fast) remains.

**Comment by tglman** [comment] 2016-09-06 10:30
hi @mikayeln,

Did you update as well the client in your application ? the fix was actually client side.

Regards.

**Comment by mikayeln** [comment] 2016-09-06 12:12
Hi @tglman, 

Yes I did. 

executing following script

var server = com.orientechnologies.orient.server.OServerMain.server();
if(server != null) {    
    var cm = server.getClientConnectionManager();
    if(cm != null) {        
        cm.cleanExpiredConnections();
        var conns = cm.getConnections().toArray();
        var arr = [];
        arr.push("Connections:" + conns.length);
        for(var i = 0;i < conns.length;i++){
          
          var tokens = conns[i].getStats().lastCommandInfo + ";" +conns[i].getStats().lastCommandDetail + ";" + (conns[i].getToken()===null?"":conns[i].getToken().getDatabase() + ";" + conns[i].getToken().getDatabaseType() + ";" + new Date(conns[i].getToken().getExpiry()) + ";" + conns[i].getToken().isNowValid() + ";" + conns[i].getToken().getIsValid());
          arr.push(tokens);          
          
        }
      conns = cm.getConnections().toArray();        	
        	arr.push("Connections After:" + conns.length);
        return arr;
    } else {
        print('cannot get cm from server');
    }
} else {
    print('cannot get server');
}

i'm getting interesing output. There are a lot of following "connections"

"Retrieve ceiling positions;-;ws1;plocal;Tue Sep 06 2016 18:01:38 GMT+0600 (NOVT);false;true",
"Count cluster elements;-;ws1;plocal;Tue Sep 06 2016 18:08:51 GMT+0600 (NOVT);true;true",
 "Get the begin/end range of data in cluster;-;ws1;plocal;Tue Sep 06 2016 18:01:38 GMT+0600 (NOVT);false;true"

network.maxConcurrentSessions is set to 200. And now for idle application I have 98 "connections".

**Comment by smil2k** [comment] 2016-09-08 13:26
@tglman:
Do you have any progress on this topic? Can I help you with the investigation?

The need of restarting orient daily makes our life hard here.

**Comment by tglman** [comment] 2016-09-08 17:44
hi @smil2k,

Yes i'm on it, other users/clients as well reported and i'm trying to reproduce the problem, i dod some fix on the invalid session and in the pool client side, without completely sort out the problem, if you can try the last 2.2.9 and get a client and a server dump would be amazing.

Thanks

**Comment by smil2k** [comment] 2016-09-08 17:50
I'll upgrade our systems to 2.2.9 and send you the dumps. 

Where can I upload them? I would not like to post them here if one option exists.

**Comment by tglman** [comment] 2016-09-09 13:30
hi @smil2k,

I think i just figured out the sources of the problem, it was more the one issue actually, like i said some are already fixed in 2.2.9 and the fix i just did will be released in 2.2.10 in almost a couple of weeks, in any case feel free to upload the dumps on any cloud storage (dropbox,google file, ecc) if you want to keep them private yuo can send a mail whit the reference to this issue to support@orientdb.com, we will have a look at them.

**Comment by smil2k** [comment] 2016-09-15 13:45
Hi,

I just made some dump for you. do you have an ETA for 2.2.10?

Cheers,

Tamas

**Comment by tglman** [comment] 2016-09-15 13:50
hi @smil2k,

the 2.2.10 has just been relased, i'll check as well your dump to be sure it was the same source.

Regards.

**Comment by smil2k** [comment] 2016-09-24 16:11
Hi @tglman,

Did you have the time to validate the dump? I did not see the problem for a week. So if you confirm, that your found bugs caused the open connections, I'm ok with closing this issue.

Cheers,

Tamas

**Comment by tglman** [comment] 2016-09-26 11:50
hi @smil2k,

Yes from the dumps i saw what i expexted, so i confirm that it should be fixed and we can close this.

Regards

**Closed** 2016-09-26 13:46 UTC
Labels: bug, resolved
