### ISSUE TITLE
Creating index on Datetime field trims the time part (v1.7.10)

### ISSUE THREAD

**Issue by emresebat** [orientechnologies/orientdb#4135] opened 2015-05-12 12:31 UTC
Here is a screenshot to explain the problem, the database date time format is yyyy-MM-dd'T'HH:mm:ss.sssZ

![image](https://cloud.githubusercontent.com/assets/2254943/7586478/ecf7ee06-f8b5-11e4-9446-0b070cfc9d39.png)

As you can see the createdAt has valid date and time but after I run the create property command the values change. The strange part is also when I drop the property the values revert back to normal.

**Comment by tglman** [comment] 2015-10-28 18:10
hi @emresebat 

I think this is not anymore valid, i was not able to reproduce it, from what you described seems a viewing problem, I'm closing this, reopen it if you can reproduce it.

**Closed by tglman** 2015-10-28 18:10 UTC
Labels: bug
