### ISSUE TITLE
client cannot connect without token setting

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#5299] opened 2015-11-10 20:11 UTC
Using this option on the client connection doesn't work.

`-Dclient.session.tokenBased=false`

**Comment by tglman** [comment] 2015-11-11 12:31
the 2.2 client it work only with the token by design, the refactor was done for stabilize the support of live query.

The client should not read that flag anymore, just changed now the code, closing this.

**Closed by tglman** 2015-11-11 12:31 UTC
Labels: bug
