### ISSUE TITLE
OException: Cannot find best cluster for class

### ISSUE THREAD

**Issue by odbuser2** [orientechnologies/orientdb#2981] opened 2014-10-27 05:09 UTC
OrientDB develop branch
Embedded
Clustered but with only one node running
Using default-distrubuted-db-conf.json

The following error occurs sometimes during startup after having run successfully for awhile.  On every startup I'm updating a property on a vertex of a class.
```
Caused by: com.orientechnologies.common.exception.OException: Cannot find best cluster for class 'SomeClass'. ClusterStrategy=local
    at com.orientechnologies.orient.server.hazelcast.OLocalClusterStrategy.readConfiguration(OLocalClusterStrategy.java:90)
    at com.orientechnologies.orient.server.hazelcast.OLocalClusterStrategy.getCluster(OLocalClusterStrategy.java:61)
    at com.orientechnologies.orient.core.metadata.schema.OClassImpl.getClusterForNewInstance(OClassImpl.java:762)
    at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1655)
    at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1644)
    at com.tinkerpop.blueprints.impls.orient.OrientElement.save(OrientElement.java:277)
    at com.tinkerpop.blueprints.impls.orient.OrientElement.save(OrientElement.java:259)
    at com.tinkerpop.blueprints.impls.orient.OrientElement.setProperty(OrientElement.java:167)
    at com.test.Test.test(Test.java:10)
```
This occurs here:
```
com.orientechnologies.orient.server.hazelcast.OLocalClusterStrategy@90
      throw new OException("Cannot find best cluster for class '" + cls.getName() + "'. ClusterStrategy=" + getName());
```
My workaround has been to turn off clustering or to delete the database which is not going to be acceptable.

**Comment by kadishmal** [comment] 2015-01-03 09:02
I am encountering the same problem in 2.0-rc1 after enabling the distributed mode with three nodes. The mentioned `MyClass` is an EDGE class. The error occurs on creating an edge. The interesting things is the first several thousand edges are created with no problem, then this errors starts occurring more and more frequently.

All three nodes reports the following error at the same time.

The error is:

        Cannot route COMMAND operation to the distributed node
        com.orientechnologies.common.exception.OException: Cannot find best cluster for class 'MyClass'. ClusterStrategy=local
                at com.orientechnologies.orient.server.hazelcast.OLocalClusterStrategy.readConfiguration(OLocalClusterStrategy.java:91)
                at com.orientechnologies.orient.server.hazelcast.OLocalClusterStrategy.getCluster(OLocalClusterStrategy.java:62)
                at com.orientechnologies.orient.core.metadata.schema.OImmutableClass.getClusterForNewInstance(OImmutableClass.java:271)
                at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2233)
                at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:117)
                at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1672)
                at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1663)
                at com.tinkerpop.blueprints.impls.orient.OrientElement.save(OrientElement.java:306)
                at com.tinkerpop.blueprints.impls.orient.OrientVertex.addEdge(OrientVertex.java:933)
                at com.orientechnologies.orient.graph.sql.OCommandExecutorSQLCreateEdge$1.call(OCommandExecutorSQLCreateEdge.java:155)
                at com.orientechnologies.orient.graph.sql.OCommandExecutorSQLCreateEdge$1.call(OCommandExecutorSQLCreateEdge.java:114)
                at com.orientechnologies.orient.graph.sql.OGraphCommandExecutorSQLFactory.runInTx(OGraphCommandExecutorSQLFactory.java:90)
                at com.orientechnologies.orient.graph.sql.OGraphCommandExecutorSQLFactory.runInTx(OGraphCommandExecutorSQLFactory.java:105)
                at com.orientechnologies.orient.graph.sql.OCommandExecutorSQLCreateEdge.execute(OCommandExecutorSQLCreateEdge.java:114)
                at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:64)
                at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1163)
                at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1152)
                at com.orientechnologies.orient.server.distributed.ODistributedStorage.command(ODistributedStorage.java:241)
                at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
                at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1179)
                at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:385)
                at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:216)
                at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)
        Sent run-time exception to the client /123.123.123.123:52083: com.orientechnologies.orient.core.exception.OStorageException: Cannot route COMMAND operation to the distributed node
        com.orientechnologies.orient.core.exception.OStorageException: Cannot route COMMAND operation to the distributed node
                at com.orientechnologies.orient.server.distributed.ODistributedStorage.handleDistributedException(ODistributedStorage.java:1191)
                at com.orientechnologies.orient.server.distributed.ODistributedStorage.command(ODistributedStorage.java:398)
                at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
                at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1179)
                at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:385)
                at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:216)
                at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)
        Caused by: com.orientechnologies.common.exception.OException: Cannot find best cluster for class 'MyClass'. ClusterStrategy=local
                at com.orientechnologies.orient.server.hazelcast.OLocalClusterStrategy.readConfiguration(OLocalClusterStrategy.java:91)
                at com.orientechnologies.orient.server.hazelcast.OLocalClusterStrategy.getCluster(OLocalClusterStrategy.java:62)
                at com.orientechnologies.orient.core.metadata.schema.OImmutableClass.getClusterForNewInstance(OImmutableClass.java:271)
                at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2233)
                at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:117)
                at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1672)
                at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1663)
                at com.tinkerpop.blueprints.impls.orient.OrientElement.save(OrientElement.java:306)
                at com.tinkerpop.blueprints.impls.orient.OrientVertex.addEdge(OrientVertex.java:933)
                at com.orientechnologies.orient.graph.sql.OCommandExecutorSQLCreateEdge$1.call(OCommandExecutorSQLCreateEdge.java:155)
                at com.orientechnologies.orient.graph.sql.OCommandExecutorSQLCreateEdge$1.call(OCommandExecutorSQLCreateEdge.java:114)
                at com.orientechnologies.orient.graph.sql.OGraphCommandExecutorSQLFactory.runInTx(OGraphCommandExecutorSQLFactory.java:90)
                at com.orientechnologies.orient.graph.sql.OGraphCommandExecutorSQLFactory.runInTx(OGraphCommandExecutorSQLFactory.java:105)
                at com.orientechnologies.orient.graph.sql.OCommandExecutorSQLCreateEdge.execute(OCommandExecutorSQLCreateEdge.java:114)
                at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:64)
                at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1163)
                at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1152)
                at com.orientechnologies.orient.server.distributed.ODistributedStorage.command(ODistributedStorage.java:241)
                ... 5 more

**Comment by lvca** [comment] 2015-01-04 15:54
Please can you try with 2.0-SNAPSHOT?

**Comment by kadishmal** [comment] 2015-01-04 16:04
Ok, I will try now. But where do I get it? Do you mean the master branch?

**Comment by lvca** [comment] 2015-01-04 16:07
If you use maven, just use `2.0-SNAPSHOT`, otherwise download latest from:

https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-community/2.0-SNAPSHOT/

**Comment by kadishmal** [comment] 2015-01-04 16:50
Have no luck even running it. Gives the following error on server start:

	2015-01-04 16:45:09:640 INFO  OrientDB Server v2.0-SNAPSHOT is active. [OServer]
	2015-01-04 16:47:27:116 INFO  OrientDB auto-config DISKCACHE=1,378MB (heap=455MB os=3,881MB disk=9,311MB) [orientechnologies]
	2015-01-04 16:47:27:121 INFO  Loading configuration from: /opt/orientdb/config/orientdb-server-config.xml... [OServerConfigurationLoaderXml]
	2015-01-04 16:47:27:363 INFO  OrientDB Server v2.0-SNAPSHOT (build UNKNOWN@r; 2015-01-03 02:07:57-0500) is starting up... [OServer]
	2015-01-04 16:47:27:395 INFO  Databases directory: /opt/orientdb/databases [OServer]
	2015-01-04 16:47:27:431 INFO  Listening binary connections on 127.0.0.1:2424 (protocol v.28, socket=default) [OServerNetworkListener]
	2015-01-04 16:47:27:435 INFO  Installing dynamic plugin 'studio-2.0.zip'... [OServerPluginManager]Error on installing dynamic plugin 'studio'
	com.orientechnologies.orient.core.exception.OConfigurationException: HTTP listener not registered while installing Static Content command
	        at com.orientechnologies.orient.server.plugin.OServerPluginManager.registerStaticDirectory(OServerPluginManager.java:207)
	        at com.orientechnologies.orient.server.plugin.OServerPluginManager.installDynamicPlugin(OServerPluginManager.java:357)
	        at com.orientechnologies.orient.server.plugin.OServerPluginManager.updatePlugin(OServerPluginManager.java:194)
	        at com.orientechnologies.orient.server.plugin.OServerPluginManager.updatePlugins(OServerPluginManager.java:283)
	        at com.orientechnologies.orient.server.plugin.OServerPluginManager.startup(OServerPluginManager.java:85)
	        at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:811)
	        at com.orientechnologies.orient.server.OServer.activate(OServer.java:247)
	        at com.orientechnologies.orient.server.OServerMain.main(OServerMain.java:36)

I've put it inside a Docker [container](https://registry.hub.docker.com/u/lighthopper/orientdb-centos/). You can try to run it as follows:

sudo docker run -d -v /home/user/orientdb/node1/config:/opt/orientdb/config -v /home/user/orientdb/node1/databases:/opt/orientdb/databases -p 2480:2480 -p 2424:2424 lighthopper/orientdb-centos:latest

**Comment by lvca** [comment] 2015-01-04 16:54
Seems it cannot find the orientdb-server-config.xml with network listeners.

**Comment by kadishmal** [comment] 2015-01-04 16:58
Can start up the server in a non-distributed mode. The file is available and writable on the host.

**Comment by kadishmal** [comment] 2015-01-05 01:43
It was my fault that the server couldn't start up because it couldn't find the `config` directory. For some reason my servers had different `home` vs `home1` directories. Now 2.0-SNAPSHOT starts up fine, however nodes cannot join the cluster. Each node runs separately because each reports that the connection is refused to others after which they blacklist each other.

	2015-01-05 01:34:05:001 INFO  OrientDB auto-config DISKCACHE=1,378MB (heap=455MB os=3,881MB disk=9,311MB) [orientechnologies]
	2015-01-05 01:34:05:010 INFO  Loading configuration from: /opt/orientdb/config/orientdb-server-config.xml... [OServerConfigurationLoaderXml]
	2015-01-05 01:34:05:378 INFO  OrientDB Server v2.0-SNAPSHOT (build UNKNOWN@r; 2015-01-03 02:07:57-0500) is starting up... [OServer]
	2015-01-05 01:34:05:412 INFO  Databases directory: /opt/orientdb/databases [OServer]
	2015-01-05 01:34:05:467 INFO  Listening binary connections on 0.0.0.0:2424 (protocol v.28, socket=default) [OServerNetworkListener]
	2015-01-05 01:34:05:469 INFO  Listening http connections on 0.0.0.0:2480 (protocol v.10, socket=default) [OServerNetworkListener]
	2015-01-05 01:34:05:488 INFO  Installing dynamic plugin 'studio-2.0.zip'... [OServerPluginManager]

	...

	2015-01-05 01:34:05:590 INFO  Installing GREMLIN language v.2.6.0 - graph.pool.max=50 [OGraphServerHandler]
	2015-01-05 01:34:06:631 WARNING Assigning distributed node name: node1420421646630 [OHazelcastPlugin]
	2015-01-05 01:34:06:709 INFO  Starting distributed server 'node1420421646630'... [OHazelcastPlugin]
	2015-01-05 01:34:06:754 INFO  Configuring Hazelcast from '/opt/orientdb/config/hazelcast.xml'. [FileSystemXmlConfig]
	2015-01-05 01:34:07:222 INFO  [LOCAL] [orientdb] [3.3] Interfaces is disabled, trying to pick one address from TCP-IP config addresses: [123.123.123.123, 123.123.123.124, 123.123.123.125] [DefaultAddressPicker]
	2015-01-05 01:34:07:222 INFO  [LOCAL] [orientdb] [3.3] Prefer IPv4 stack is true. [DefaultAddressPicker]
	2015-01-05 01:34:07:235 WARNING [LOCAL] [orientdb] [3.3] Could not find a matching address to start with! Picking one of non-loopback addresses. [DefaultAddressPicker]
	2015-01-05 01:34:07:246 INFO  [LOCAL] [orientdb] [3.3] Picked Address[172.17.0.2]:2434, using socket ServerSocket[addr=/0.0.0.0,localport=2434], bind any local is true [DefaultAddressPicker]
	2015-01-05 01:34:07:288 INFO  [172.17.0.2]:2434 [orientdb] [3.3] Starting with 4 generic operation threads and 4 partition operation threads. [BasicOperationScheduler]
	2015-01-05 01:34:07:389 INFO  [172.17.0.2]:2434 [orientdb] [3.3] Hazelcast 3.3 (20140907) starting at Address[172.17.0.2]:2434 [system]
	2015-01-05 01:34:07:389 INFO  [172.17.0.2]:2434 [orientdb] [3.3] Copyright (C) 2008-2014 Hazelcast.com [system]
	2015-01-05 01:34:07:391 INFO  [172.17.0.2]:2434 [orientdb] [3.3] Creating TcpIpJoiner [Node]
	2015-01-05 01:34:07:393 INFO  [172.17.0.2]:2434 [orientdb] [3.3] Address[172.17.0.2]:2434 is STARTING [LifecycleService]
	2015-01-05 01:34:07:526 INFO  [172.17.0.2]:2434 [orientdb] [3.3] Connecting to /123.123.123.123:2434, timeout: 0, bind-any: true [SocketConnector]
	2015-01-05 01:34:07:529 INFO  [172.17.0.2]:2434 [orientdb] [3.3] Could not connect to: /123.123.123.123:2434. Reason: SocketException[Connection refused to address /123.123.123.123:2434] [SocketConnector]
	2015-01-05 01:34:07:529 INFO  [172.17.0.2]:2434 [orientdb] [3.3] Address[123.123.123.123]:2434 is added to the blacklist. [TcpIpJoiner]
	2015-01-05 01:34:07:534 INFO  [172.17.0.2]:2434 [orientdb] [3.3] Connecting to /123.123.123.124:2434, timeout: 0, bind-any: true [SocketConnector]
	2015-01-05 01:34:07:538 INFO  [172.17.0.2]:2434 [orientdb] [3.3] Connecting to /123.123.123.125:2434, timeout: 0, bind-any: true [SocketConnector]
	2015-01-05 01:34:07:539 INFO  [172.17.0.2]:2434 [orientdb] [3.3] Could not connect to: /123.123.123.125:2434. Reason: SocketException[Connection refused to address /123.123.123.125:2434] [SocketConnector]
	2015-01-05 01:34:07:539 INFO  [172.17.0.2]:2434 [orientdb] [3.3] Address[123.123.123.125]:2434 is added to the blacklist. [TcpIpJoiner]
	2015-01-05 01:34:07:540 INFO  [172.17.0.2]:2434 [orientdb] [3.3] Could not connect to: /123.123.123.124:2434. Reason: SocketException[Connection refused to address /123.123.123.124:2434] [SocketConnector]
	2015-01-05 01:34:07:540 INFO  [172.17.0.2]:2434 [orientdb] [3.3] Address[123.123.123.124]:2434 is added to the blacklist. [TcpIpJoiner]
	2015-01-05 01:34:08:535 INFO  [172.17.0.2]:2434 [orientdb] [3.3]


	Members [1] {
	        Member [172.17.0.2]:2434 this
	}

The same on other 2 nodes.

**Comment by lvca** [comment] 2015-01-05 04:53
What's your hazelcast cfg? Are you using multicast? Are your machine in a network where Multicast is enabled?

**Comment by kadishmal** [comment] 2015-01-05 06:46
Multicast is disabled. Specified fixed IP address of Docker hosts as follows:

        <hazelcast
                xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.0.xsd"
                xmlns="http://www.hazelcast.com/schema/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
                <group>
                        <name>orientdb</name>
                        <password>orientdb</password>
                </group>
                <network>
                        <port auto-increment="true">2434</port>
                        <join>
                                <multicast enabled="false">
                                        <multicast-group>235.1.1.1</multicast-group>
                                        <multicast-port>2434</multicast-port>
                                </multicast>
                                <tcp-ip enabled="true">
                                        <member>123.123.123.123:2434</member>
                                        <member>123.123.123.124:2434</member>
                                        <member>123.123.123.125:2434</member>
                                </tcp-ip>
                        </join>
                </network>
                <executor-service>
                        <pool-size>16</pool-size>
                </executor-service>
        </hazelcast>

I have posted a related question in Google Groups https://groups.google.com/forum/#!topic/orient-database/ehfKcInWZXs.

**Comment by lvca** [comment] 2015-01-05 06:57
By reading your log this address is taken: 172.17.0.2

**Comment by kadishmal** [comment] 2015-01-05 07:00
What do you mean by "taken"?

**Comment by lvca** [comment] 2015-01-05 07:04
Look at your log:

    2015-01-05 01:34:07:246 INFO  [LOCAL] [orientdb] [3.3] Picked Address[172.17.0.2]:2434, using socket ServerSocket[addr=/0.0.0.0,localport=2434], bind any local is true [DefaultAddressPicker]

**Comment by kadishmal** [comment] 2015-01-05 07:05
Just in case, `172.17.0.2` is accessible only on the same host. However, my ODB nodes are running on separate physical machines each of which has its own `172.17.0.2` free or occupied. On each host Docker creates the same networking bridge.

What I don't understand is that when ODB on host B receives a connection from host A on port 2434, why does it reject the connection request just because the host A tried to connect to host B on IP 123.123.123.123 while ODB in host B is running in an isolated network under IP 172.17.0.2?

**Comment by kadishmal** [comment] 2015-01-05 07:09
Attaching ODB container directly to the host network still generate the same error:

	2015-01-05 07:06:03:912 INFO  [172.17.42.1]:2434 [orientdb] [3.3] Accepting socket connection from /123.123.123.124:44369 [SocketAcceptor]
	2015-01-05 07:06:03:913 INFO  [172.17.42.1]:2434 [orientdb] [3.3] Established socket connection between /123.123.123.123:2434 and /123.123.123.124:44369 [TcpIpConnectionManager]
	2015-01-05 07:06:03:914 WARNING [172.17.42.1]:2434 [orientdb] [3.3] Wrong bind request from Address[172.17.42.1]:2434! This node is not requested endpoint: Address[123.123.123.123]:2434 [TcpIpConnectionManager]
	2015-01-05 07:06:03:915 INFO  [172.17.42.1]:2434 [orientdb] [3.3] Connection [/123.123.123.124:44369] lost. Reason: Socket explicitly closed [TcpIpConnection]

**Comment by lvca** [comment] 2015-01-05 07:20
I see "Socket explicitly closed" as reason, so this is a cfg problem. Is 172.17.42.1 the address of your physical machine?

**Comment by kadishmal** [comment] 2015-01-05 07:32
No, `172.17.42.1` is the address of the Docker bridge inside the first host. It's not accessible outside the host. The host IP is 123.123.123.123 for host A, and host B is 123.123.123.124. If my understanding is correct, ODB can't be run inside Docker which I really doubt. I still believe there is something doable.

**Comment by lvca** [comment] 2015-01-05 07:38
Look at: http://docs.hazelcast.org/docs/3.1/manual/html/ch14s02.html#ConfigTcpIp under "Specifying Network Interfaces". You could force it to use the eth0 inteface.

**Comment by kadishmal** [comment] 2015-01-05 08:26
Interfaces will not work inside the docker container because inside there is only one interface `eth0` which is bound to `docker0` bridge on host. A container doesn't see the host interfaces.

**Comment by lvca** [comment] 2015-01-05 12:11
Does the output of the command "/sbin/ifconfig" have been executed on virtual host or physical?

**Comment by kadishmal** [comment] 2015-01-05 17:59
Physical host. I have a Docker server running on it. Has there been any multi-host Docker deployment before among your customers? So far from my experiments the best approach is to use domain names for peer ODB nodes, however my current problem is that each peer recognizes only its own domain name. Other two host names don't resolve naturally via the central DNS. The last option is to hardcore them into the image which will make the image usable only by me. Kind of not beat but expectedly working solution.

**Comment by kadishmal** [comment] 2015-01-07 07:58
I will comment back when I get a reliable solution.

**Comment by kadishmal** [comment] 2015-01-23 01:26
I seem to have found a solution for the clustering problem caused when running ODB in Docker containers on multiple hosts. Since this problem was in Hazelcast, I have looked whether there are successful cases of marring Hazelcast with Docker. And indeed there are. Vert.x also uses Hazelcast and here is the config that works for them https://gist.github.com/nscavell/a7727f16c402a1e6e4fa.

- Original Hazelcast group post with no help https://groups.google.com/forum/#!topic/hazelcast/m1KKS28E5To.
- But here is the same post in Vert.x group https://groups.google.com/forum/#!topic/vertx/MvKcz_aTaWM that points to the above gist.

I haven't tried this solution yet, but it looks very promising. If it does work, proper instructions should be added to Docker + ODB manual because this is what people will try to do when using ODB with Docker.

**Comment by lvca** [comment] 2015-01-23 08:53
@kadishmal Great! Let us know and we can put it also in OrientDB manual ;-)

**Comment by lvca** [comment] 2015-02-10 18:51
Please could you try with 2.0.2?

**Comment by ugavnholt** [comment] 2015-02-19 22:44
Another work-around is to enable lightweight edges on the database - at least in ver 2.1

**Comment by lvca** [comment] 2015-03-15 10:38
Fixed in 2.0.5

**Closed** 2015-03-15 10:38 UTC
Labels: bug, distributed, In Progress

**Comment by ugavnholt** [comment] 2015-03-24 21:15
I'm seeing this issue with 2.1, 2.0.6 SNAPSHOT, and 2.0.5 SNAPSHOT

**Comment by ugavnholt** [comment] 2015-03-24 21:29
I'm still seeing this problem in 2.0.5 SNAPSHOT

**Comment by lvca** [comment] 2015-03-25 15:41
Please, could you retry with 2.0.6-SNAPSHOT?

**Comment by ugavnholt** [comment] 2015-03-26 23:28
its running wih the 2.0.6 SNAPSHOT from the 25th now, I'll let you know if I see this error again

**Comment by franshamk** [comment] 2015-04-02 01:03
In case it helps someone:  I was seeing this error (Cannot find best cluster for class) in 2.0.6 when using a nodeName that contained an underscore and an ip address:  node_192.168.1.1

Not sure if it's the underscore or the period(s) causing the trouble, but when I changed the node names all ran smoothly.

**Comment by lvca** [comment] 2015-04-02 02:04
Cool you found a workaround. I'm creating a new issue at low pri about this. Thanks.

**Comment by ryan-stateless** [comment] 2015-04-07 23:30
I'm experiencing this problem with 2.0.6 in a Docker container. 
Worth noting - I've been running 1.7.10 this way with no issues for months.
