### ISSUE TITLE
IllegalArgumentException: newPosition > limit

### ISSUE THREAD

**Issue by johny65** [orientechnologies/orientdb#9694] opened 2021-10-06 13:40 UTC
## Expected behavior  

To execute scripts in the database without problems.

## Actual behavior 

I had a database in 3.2.0 running fine with a ETL process importing data to it daily without problems. When I switched to 3.2.2, the ETL failed in some scripts that were previously running fine with the following exception:

```
Error: com.orientechnologies.orient.core.exception.OStorageException: Error on executing command: 
...[SCRIPT CONTENT]...
	DB name="mydatabase"

Error: java.lang.IllegalArgumentException: newPosition > limit: (4966672 > 65536)
```
The numbers in `newPosition` vary between different thrown exceptions.

## Steps to reproduce  

I don't know exactly. SQL scripts running fine in 3.2.0 started to fail in 3.2.2.

**Comment by andrii0lomakin** [comment] 2021-10-06 13:59
Hi,
Could you provide a full stack trace of exception?

**Comment by andrii0lomakin** [comment] 2021-10-06 14:04
Also if you provide the script and data to reproduce the problem it would really help to fix the exception. Or probably you would be able to create a reproducer with a minimum amount of code to reproduce this issue.

**Comment by johny65** [comment] 2021-10-06 14:09
Hi @laa, no full stacktrace is logged, only that message in the client (console.sh running the script), the server side logs nothing. I don't know if it depends on data or script, I will try my best to create a minimum reproducer if it's possible.

**Comment by andrii0lomakin** [comment] 2021-10-06 18:32
Thank you very much for your efforts.

**Comment by andrii0lomakin** [comment] 2021-10-07 05:19
@johny65 I am quite worried by your report, are you sure that there are no stack traces in server logs files once this exception is thrown?

**Comment by johny65** [comment] 2021-10-07 12:30
> @johny65 I am quite worried by your report, are you sure that there are no stack traces in server logs files once this exception is thrown?

Yes, nothing is logged. But investigating further, I have found that the exception occurs in lines with an indexed `select` like this:

```
orientdb {db=mydatabase}> select from AClass where prop = 1891571;

Error: com.orientechnologies.orient.core.exception.OStorageException: Error on executing command: select from AClass where prop = 1891571
	DB name="mydatabase"

Error: java.lang.IllegalArgumentException: newPosition > limit: (36230671 > 65536)
```

The `prop` attribute is indexed with a unique index (`create index AClass_prop on AClass(prop) unique`). This index in particular starts failing with numbers >= 1889767 (`where prop = 1889767` fails, `where prop = 1889766` works fine). The same occurs for other classes and other indexes with different problematic ranges.

**Comment by andrii0lomakin** [comment] 2021-10-07 15:19
Got it. I will try to provide a possible fix for this issue soon, but you will need to rebuild the index. I will let you know once fix is submitted.

**Comment by andrii0lomakin** [comment] 2021-10-12 15:01
Hi @johny65 , I can not reproduce your issue. Are there any chances that you provide me load script to reproduce the problem?

**Comment by andrii0lomakin** [comment] 2021-10-13 14:44
Hi @johny65 , your issue is very important for us because it affects the stability of the system, would be good if you provide us means to reproduce the problem.

**Comment by andrii0lomakin** [comment] 2021-10-18 07:18
Hi @johny65 , could you help us to resolve the given issue?

**Comment by johny65** [comment] 2021-10-18 15:57
Hello @laa, sorry for the late. I've tried but can't reproduce the issue in a fresh and clean database, I don't know how to reproduce it. One approach could be to pass you the problematic database deleting first all non-necesary records (it has millions and several GB of size), but deleting millions of records takes so much time and every time I try my PC hangs...

**Comment by leszekgruchala** [comment] 2021-12-09 08:22
@laa We are facing a similar issue after upgrading from 3.1.12 to 3.2.3. So far, we face the problem only in one environment so it must be related to the amount of data and indices required to be built. On a fresh 3.2.3 DB so far no problem.

The stacktrace

```
2021-12-08 14:13:12:817 WARNI {db=mydatabase} Token signature failure: <SECRET> [OTokenSignImpl]Exception `34C76FF4` in storage `plocal:/orientdb-3.2.3/databases/mydatabase`: 3.2.3 (build dc98198215aa57baf29b32adb657dc3733acdb55, branch develop)
com.orientechnologies.orient.core.exception.OStorageException: Exception during execution of component operation inside of storage mydatabase
DB name="mydatabase"
at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.calculateInsideComponentOperation(OAtomicOperationsManager.java:235)
at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.calculateInsideComponentOperation(OAtomicOperationsManager.java:222)
at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.calculateInsideComponentOperation(ODurableComponent.java:96)
at com.orientechnologies.orient.core.storage.index.sbtree.singlevalue.v3.CellBTreeSingleValueV3.update(CellBTreeSingleValueV3.java:243)
at com.orientechnologies.orient.core.storage.index.sbtree.singlevalue.v3.CellBTreeSingleValueV3.put(CellBTreeSingleValueV3.java:227)
at com.orientechnologies.orient.core.index.engine.v1.OCellBTreeMultiValueIndexEngine.put(OCellBTreeMultiValueIndexEngine.java:418)
at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.putRidIndexEntryInternal(OAbstractPaginatedStorage.java:3420)
at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.putRidIndexEntry(OAbstractPaginatedStorage.java:3381)
at com.orientechnologies.orient.core.index.OIndexMultiValues.doPutV1(OIndexMultiValues.java:227)
at com.orientechnologies.orient.core.index.OIndexMultiValues.doPut(OIndexMultiValues.java:155)
at com.orientechnologies.orient.core.index.OIndexAbstractDelegate.doPut(OIndexAbstractDelegate.java:436)
at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.applyTxChanges(OAbstractPaginatedStorage.java:2543)
at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitIndexes(OAbstractPaginatedStorage.java:2527)
at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:2444)
at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:2258)
at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.internalCommit(ODatabaseDocumentEmbedded.java:1978)
at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:621)
at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:114)
at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:1593)
at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:1563)
at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeCommit38(OConnectionBinaryExecutor.java:1551)
at com.orientechnologies.orient.client.remote.message.OCommit38Request.execute(OCommit38Request.java:141)
at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:355)
at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:239)
at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:68)
Caused by: java.lang.IllegalArgumentException: newPosition < 0: (-87358466 < 0)
at java.base/java.nio.Buffer.createPositionException(Buffer.java:318)
at java.base/java.nio.Buffer.position(Buffer.java:293)
at java.base/java.nio.ByteBuffer.position(ByteBuffer.java:1094)
at java.base/java.nio.MappedByteBuffer.position(MappedByteBuffer.java:226)
at java.base/java.nio.MappedByteBuffer.position(MappedByteBuffer.java:67)
at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OWALPageChangesPortion.readData(OWALPageChangesPortion.java:282)
at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OWALPageChangesPortion.getBinaryValue(OWALPageChangesPortion.java:119)
at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.getBinaryValue(ODurablePage.java:182)
at com.orientechnologies.orient.core.storage.index.sbtree.singlevalue.v3.CellBTreeSingleValueBucketV3.getRawValue(CellBTreeSingleValueBucketV3.java:338)
at com.orientechnologies.orient.core.storage.index.sbtree.singlevalue.v3.CellBTreeSingleValueV3.lambda$update$1(CellBTreeSingleValueV3.java:273)
at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.calculateInsideComponentOperation(OAtomicOperationsManager.java:230)
... 24 more
Exception `34C76FF4` in storage `plocal:/orientdb-3.2.3/databases/mydatabase`: 3.2.3 (build dc98198215aa57baf29b32adb657dc3733acdb55, branch develop)
com.orientechnologies.orient.core.exception.OStorageException: Exception during execution of component operation inside of storage mydatabase
DB name="mydatabase"
at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.calculateInsideComponentOperation(OAtomicOperationsManager.java:235)
at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.calculateInsideComponentOperation(OAtomicOperationsManager.java:222)
at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.calculateInsideComponentOperation(ODurableComponent.java:96)
at com.orientechnologies.orient.core.storage.index.sbtree.singlevalue.v3.CellBTreeSingleValueV3.update(CellBTreeSingleValueV3.java:243)
at com.orientechnologies.orient.core.storage.index.sbtree.singlevalue.v3.CellBTreeSingleValueV3.put(CellBTreeSingleValueV3.java:227)
at com.orientechnologies.orient.core.index.engine.v1.OCellBTreeMultiValueIndexEngine.put(OCellBTreeMultiValueIndexEngine.java:418)
at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.putRidIndexEntryInternal(OAbstractPaginatedStorage.java:3420)
at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.putRidIndexEntry(OAbstractPaginatedStorage.java:3381)
at com.orientechnologies.orient.core.index.OIndexMultiValues.doPutV1(OIndexMultiValues.java:227)
at com.orientechnologies.orient.core.index.OIndexMultiValues.doPut(OIndexMultiValues.java:155)
at com.orientechnologies.orient.core.index.OIndexAbstractDelegate.doPut(OIndexAbstractDelegate.java:436)
at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.applyTxChanges(OAbstractPaginatedStorage.java:2543)
at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitIndexes(OAbstractPaginatedStorage.java:2527)
at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:2444)
at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:2258)
at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.internalCommit(ODatabaseDocumentEmbedded.java:1978)
at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:621)
at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:114)
at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:1593)
at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:1563)
at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeCommit38(OConnectionBinaryExecutor.java:1551)
at com.orientechnologies.orient.client.remote.message.OCommit38Request.execute(OCommit38Request.java:141)
at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:355)
at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:239)
at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:68)
Caused by: java.lang.IllegalArgumentException: newPosition < 0: (-87358466 < 0)
at java.base/java.nio.Buffer.createPositionException(Buffer.java:318)
at java.base/java.nio.Buffer.position(Buffer.java:293)
at java.base/java.nio.ByteBuffer.position(ByteBuffer.java:1094)
at java.base/java.nio.MappedByteBuffer.position(MappedByteBuffer.java:226)
at java.base/java.nio.MappedByteBuffer.position(MappedByteBuffer.java:67)
at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OWALPageChangesPortion.readData(OWALPageChangesPortion.java:282)
at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OWALPageChangesPortion.getBinaryValue(OWALPageChangesPortion.java:119)
at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.getBinaryValue(ODurablePage.java:182)
at com.orientechnologies.orient.core.storage.index.sbtree.singlevalue.v3.CellBTreeSingleValueBucketV3.getRawValue(CellBTreeSingleValueBucketV3.java:338)
at com.orientechnologies.orient.core.storage.index.sbtree.singlevalue.v3.CellBTreeSingleValueV3.lambda$update$1(CellBTreeSingleValueV3.java:273)
at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.calculateInsideComponentOperation(OAtomicOperationsManager.java:230)
... 24 more
$ANSI{green {db=mydatabase}} Error on transaction commit `34C76FF4`
com.orientechnologies.orient.core.exception.OStorageException: Exception during execution of component operation inside of storage mydatabase
DB name="mydatabase"
at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.calculateInsideComponentOperation(OAtomicOperationsManager.java:235)
at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.calculateInsideComponentOperation(OAtomicOperationsManager.java:222)
at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.calculateInsideComponentOperation(ODurableComponent.java:96)
at com.orientechnologies.orient.core.storage.index.sbtree.singlevalue.v3.CellBTreeSingleValueV3.update(CellBTreeSingleValueV3.java:243)
at com.orientechnologies.orient.core.storage.index.sbtree.singlevalue.v3.CellBTreeSingleValueV3.put(CellBTreeSingleValueV3.java:227)
at com.orientechnologies.orient.core.index.engine.v1.OCellBTreeMultiValueIndexEngine.put(OCellBTreeMultiValueIndexEngine.java:418)
at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.putRidIndexEntryInternal(OAbstractPaginatedStorage.java:3420)
at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.putRidIndexEntry(OAbstractPaginatedStorage.java:3381)
at com.orientechnologies.orient.core.index.OIndexMultiValues.doPutV1(OIndexMultiValues.java:227)
at com.orientechnologies.orient.core.index.OIndexMultiValues.doPut(OIndexMultiValues.java:155)
at com.orientechnologies.orient.core.index.OIndexAbstractDelegate.doPut(OIndexAbstractDelegate.java:436)
at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.applyTxChanges(OAbstractPaginatedStorage.java:2543)
at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitIndexes(OAbstractPaginatedStorage.java:2527)
at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:2444)
at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:2258)
at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.internalCommit(ODatabaseDocumentEmbedded.java:1978)
at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:621)
at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:114)
at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:1593)
at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:1563)
at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeCommit38(OConnectionBinaryExecutor.java:1551)
at com.orientechnologies.orient.client.remote.message.OCommit38Request.execute(OCommit38Request.java:141)
at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:355)
at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:239)
at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:68)
Caused by: java.lang.IllegalArgumentException: newPosition < 0: (-87358466 < 0)
at java.base/java.nio.Buffer.createPositionException(Buffer.java:318)
at java.base/java.nio.Buffer.position(Buffer.java:293)
at java.base/java.nio.ByteBuffer.position(ByteBuffer.java:1094)
at java.base/java.nio.MappedByteBuffer.position(MappedByteBuffer.java:226)
at java.base/java.nio.MappedByteBuffer.position(MappedByteBuffer.java:67)
at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OWALPageChangesPortion.readData(OWALPageChangesPortion.java:282)
at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OWALPageChangesPortion.getBinaryValue(OWALPageChangesPortion.java:119)
at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.getBinaryValue(ODurablePage.java:182)
at com.orientechnologies.orient.core.storage.index.sbtree.singlevalue.v3.CellBTreeSingleValueBucketV3.getRawValue(CellBTreeSingleValueBucketV3.java:338)
at com.orientechnologies.orient.core.storage.index.sbtree.singlevalue.v3.CellBTreeSingleValueV3.lambda$update$1(CellBTreeSingleValueV3.java:273)
at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.calculateInsideComponentOperation(OAtomicOperationsManager.java:230)
... 24 more
```

**Comment by andrii0lomakin** [comment] 2021-12-09 08:27
Hi, we know about the reason for this problem and working on the fix.

**Comment by michele-pinto-kensu** [comment] 2021-12-09 08:36
> Hi, we know about the reason for this problem and working on the fix.

Hi, in the meanwhile, do you recommend using a previous version? If yes, to which version exactly? 

We wanted to try to repair the indexes, but at this point, I don't know if it can help.

Thanks.

**Comment by andrii0lomakin** [comment] 2021-12-09 08:38
@michele-pinto-kensu 3.2.1 version should work. I am sorry for this inconvenience, we have pretty big coverage of tests on indexes but collapsing of BTrees after items deletion causes corner cases which is really hard to reproduce.

**Comment by leszekgruchala** [comment] 2021-12-09 08:43
@laa Will reindexing on 3.2.3 fix the problem?

**Comment by andrii0lomakin** [comment] 2021-12-09 08:50
@leszekgruchala unfortunately you will see it later again. But as far as you do not perform updates you should be OK.

**Comment by michele-pinto-kensu** [comment] 2021-12-09 09:35
@laa do you know if 3.1.15 could be affected by the same issue? I'm asking this because we see several commits dedicated to fix the index space consumption: https://github.com/orientechnologies/orientdb/compare/3.1.12...3.1.15

Thanks!

**Comment by andrii0lomakin** [comment] 2021-12-09 15:55
@michele-pinto-kensu yes those changes are in both versions.

**Comment by michele-pinto-kensu** [comment] 2021-12-19 07:49
Hi @laa, any news on this issue? 

Thanks

**Comment by andrii0lomakin** [comment] 2021-12-20 07:06
Hi, going to provide a fix this week.

**Comment by andrii0lomakin** [comment] 2021-12-23 06:53
Hi, fixed both in 3.1 and 3.2 versions. Please try and let me know if it works on your side.

**Comment by johny65** [comment] 2022-03-04 14:11
Using 3.2.5 it seems that this is effectively fixed.

**Comment by tglman** [comment] 2022-03-07 15:29
Thanks to let as know, closing this

**Closed as completed by tglman** 2022-03-07 15:29 UTC
