### ISSUE TITLE
Bug in import/export 

### ISSUE THREAD

**Issue by dharmax** [orientechnologies/orientdb#3551] opened 2015-02-09 09:38 UTC
In my attempt to reproduce another orientdb bug on a different machine, i exported the database and tried to import it on the other machine. 
Both machines are ubuntu, the first with Java 7 and the target with java 8. 
Both have plenty of ram and disk space. 
Both with orientdb 2.0.1

this is what i got on the import:
```
Importing database database /home/avit/db_dump.json.gz...
Started import of database 'remote:127.0.0.1/ontology-test' from /home/avit/db_dump.json.gz...
Non merge mode (-merge=false): removing all default non security classes
- Class NameString was removed.
- Class taggedWith was removed.
- Class ORIDs was removed.
- Class Source was removed.
- Class originatedFrom was removed.
- Class OFunction was removed.
- Class NamedEntity was removed.
- Class createdFrom was removed.
- Class stringOf was removed.
- Class isA was removed.
- Class OTriggered was removed.
- Class ORestricted was removed.
- Class OSchedule was removed.
- Class Tag was removed.
- Class titleOf was removed.
- Class relatesTo was removed.
- Class systemEdge was removed.
- Class V was removed.
- Class E was removed.
Removed 19 classes.
Importing database info...OK
Importing clusters...
- Creating cluster 'internal'...OK, assigned id=0
- Creating cluster 'default'...OK, assigned id=3
- Creating cluster 'orole'...OK, assigned id=4
- Creating cluster 'ouser'...OK, assigned id=5
- Creating cluster 'ofunction'...OK, assigned id=6
- Creating cluster 'oschedule'...OK, assigned id=7
- Creating cluster 'orids'...OK, assigned id=8
- Creating cluster 'v'...OK, assigned id=9
- Creating cluster 'e'...OK, assigned id=10
- Creating cluster 'namedentity'...OK, assigned id=11
- Creating cluster 'source'...OK, assigned id=12
- Creating cluster 'namestring'...OK, assigned id=13
- Creating cluster 'tag'...OK, assigned id=14
- Creating cluster 'isa'...OK, assigned id=15
- Creating cluster 'titleof'...OK, assigned id=16
- Creating cluster 'taggedwith'...OK, assigned id=17
- Creating cluster 'originatedfrom'...OK, assigned id=18
- Creating cluster 'stringof'...OK, assigned id=19
- Creating cluster 'relatesto'...OK, assigned id=20
- Creating cluster '_studio'...OK, assigned id=21
Rebuilding indexes of truncated clusters ...Error on database import happened just before line 0, column 868
com.orientechnologies.orient.core.exception.OCommandExecutionException: Index 'tagname' not found
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLRebuildIndex.execute(OCommandExecutorSQLRebuildIndex.java:89)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:64)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1176)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1165)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1180)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:385)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:216)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)

Error: com.orientechnologies.orient.core.db.tool.ODatabaseExportException: Error on importing database 'ontology-test' from file: /home/avit/db_dump.json.gz

Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Index 'tagname' not found

orientdb {db=ontology-test}> select from source 

Error: com.orientechnologies.orient.core.exception.OQueryParsingException: Error on parsing query
Query:  source
------^

Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Class 'SOURCE' was not found in current database

orientdb {db=ontology-test}> list classes


CLASSES
----------------------------------------------+------------------------------------+------------+----------------+
 NAME                                         | SUPERCLASS                         | CLUSTERS   | RECORDS        |
----------------------------------------------+------------------------------------+------------+----------------+
 OIdentity                                    |                                    | -          |              0 |
 ORole                                        | OIdentity                          | 4          |              0 |
 OUser                                        | OIdentity                          | 5          |              0 |
----------------------------------------------+------------------------------------+------------+----------------+
 TOTAL = 3                                                                                                     0 |
----------------------------------------------+------------------------------------+------------+----------------+
```

 - so eventually, the import failed completely
 - i tried again, with a completely empty database, and still the same results.

**Comment by lvca** [comment] 2015-02-09 09:51
Please execute import not with remote, but with plocal connection until we fix this problem.

**Comment by tglman** [comment] 2015-03-03 17:04
duplicate of   https://github.com/orientechnologies/orientdb/issues/3226

**Closed by tglman** 2015-03-03 17:04 UTC
Labels: bug, duplicate
