### ISSUE TITLE
NullPointerException on index.getVersion()

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#6651] opened 2016-09-02 16:48 UTC
## OrientDB Version, operating system, or hardware.
- v2.2.8
## Operating System
- [ ] Linux
- [ ] MacOSX
- [ X] Windows
- [ ] Other Unix
- [ ] Other, name? 
## Expected behavior and actual behavior

2016-09-02 09:46:01 t.c.s.a.hr [ERROR] failed to drop old indexes:null
java.lang.NullPointerException: null
    at com.orientechnologies.orient.core.index.OIndexAbstract.getVersion(OIndexAbstract.java:812)
    at com.orientechnologies.orient.core.index.OIndexAbstractDelegate.getVersion(OIndexAbstractDelegate.java:275)
    ..
    at com.stimulus.archiva.domain.bz$a.run(MailArchiva:169)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

Expecting not to get NullPtr

**Comment by laa** [comment] 2016-09-05 07:16
@jamieb22 this issue should be fixed. Could you try latest version ?

**Comment by jamieb22** [comment] 2016-09-11 17:59
I tried on the latest version 2.2.9 and it doesn't work. 
2016-09-11 19:55:44 h.c.s.a.d.b.BluePrintDatabaseUtil [ERROR] failed to drop old indexes:null
java.lang.NullPointerException: null
	at com.orientechnologies.orient.core.index.OIndexAbstract.getVersion(OIndexAbstract.java:787)
	at com.orientechnologies.orient.core.index.OIndexAbstractDelegate.getVersion(OIndexAbstractDelegate.java:275)
	at com.stimulus.archiva.database.blueprints.BluePrintDatabaseUtil.dropOldIndexes(BluePrintDatabaseUtil.java:121)
	at com.stimulus.archiva.database.blueprints.BluePrintDatabaseUtil.initGraphFactory(BluePrintDatabaseUtil.java:327)
	at com.stimulus.archiva.database.blueprints.BluePrintDatabase.connect(BluePrintDatabase.java:86)
	at com.stimulus.archiva.database.DatabaseService.startup(DatabaseService.java:328)
	at com.stimulus.archiva.domain.Services$ServiceStartup.run(Services.java:169)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by jamieb22** [comment] 2016-09-11 18:04
This happens on v_statistic.subtype and v_blob.mgn

**Comment by laa** [comment] 2016-09-12 08:45
Hi @jamieb22 by latest I meant 2.2.10 which was in snapshot stage when I wrote it. 
If you check OIndexAbstract#getVersion 
you will see following code:
-------------------------------------------------------------------------------------------------------------
    final ODocument document = conf.getDocument();
    if (document == null)
      return -1;
    return document.field(OIndexInternal.INDEX_VERSION);
------------------------------------------------------------------------------------------------------------
So NPE on a document should not happen.

**Comment by laa** [comment] 2016-09-27 15:27
Close issue because of no reply. If you reproduce given issue and have information which is requested in issue feel free to reopen it.

**Comment by jamieb22** [comment] 2017-01-12 10:12
[database.zip](https://github.com/orientechnologies/orientdb/files/701305/database.zip)
This bug is still happening in v2.2.14.
```
java.lang.NullPointerException: null
	at com.orientechnologies.orient.core.index.OIndexAbstract.getVersion(OIndexAbstract.java:787)
	at com.orientechnologies.orient.core.index.OIndexAbstractDelegate.getVersion(OIndexAbstractDelegate.java:275)
	at com.stimulus.archiva.database.blueprints.BluePrintDatabaseUtil.dropOldIndexes(BluePrintDatabaseUtil.java:124)
```

**Comment by laa** [comment] 2017-01-13 15:32
Fixed, sorry for inconvenience

**Closed by laa** 2017-01-13 15:32 UTC
Labels: bug, storage team
