### ISSUE TITLE
Getting ODistributedRecordLockedException creating edge in distributed mode

### ISSUE THREAD

**Issue by stefomak** [orientechnologies/orientdb#5012] opened 2015-09-24 15:27 UTC
Hi, I have orientdb 2.1-SNAPSHOT
running with the -cluster option, but I have only one node running (to make it simpler).
When my java application tries to commit a transaction that involves creations of vertices and edges I get:

 Error on transaction commit 
com.orientechnologies.orient.server.distributed.task.ODistributedRecordLockedException
    at com.orientechnologies.orient.server.distributed.task.OTxTask.execute(OTxTask.java:102)
    at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.executeOnLocalNode(OHazelcastPlugin.java:805)
    at com.orientechnologies.orient.server.hazelcast.ODistributedWorker.onMessage(ODistributedWorker.java:296)
    at com.orientechnologies.orient.server.hazelcast.ODistributedWorker.run(ODistributedWorker.java:119)

In the last three days I tried a lot of combination in order to isolate the problem.
I found out that if the transaction creates only vertices (no edges!!) it doesn't fire any exception.

Do you know any workaround, please?
I'm getting crazy...............

**Comment by stefomak** [comment] 2015-09-24 15:28
....Thank you!

**Comment by lvca** [comment] 2015-10-07 06:50
ODistributedRecordLockedException is raised when a concurrent operation is executed on that record. is this your case? What level of concurrency do you have?

In case of TX, it' automatically repeated up to 10 times (by default, setting "distributed.concurrentTxMaxAutoRetry"), so to receive that message seems you have high contention on the same vertices. Can you confirm?

**Comment by stefomak** [comment] 2015-10-07 08:31
Hi Luca,
my java application tries to commit a transaction that involves creations of vertices and edges: vertex A and other stuff.
I found out that I do something else in a hook.
In the afterCreate method I create a new vertex B and an edge between A e B.
Then I discovered that I need to set DISTRIBUTED_EXECUTION_MODE.
I tried the three options, but only TARGET_NODE works without exceptions.
But doing so, and in distributed mode, I get a new vertex B in the first node of the cluster with a rid different from the rid of the new vertex B in the second node of the cluster.
This solutions doesn't work fine because in this scenario it's impossible to delete the vertex. I got another exception about quorum... 
I guess the right DISTRIBUTED_EXECUTION_MODE should be BOTH, but it doesn't work.

Thanks
Stefano

**Comment by stefomak** [comment] 2015-10-16 15:11
Hi, any idea?

**Comment by jack18jack** [comment] 2016-03-08 12:59
@stefomak @lvca  i got this error too.i try to use spark-orientdb-connector to access distributed orientdb with two nodes.i raise a question in their github page.do u guys have any findings?
https://github.com/metreta/spark-orientdb-connector/issues/4

**Comment by nishantkumar1292** [comment] 2017-06-09 10:49
I got this error too. And as @lvca pointed out that this error is _**raised when a concurrent operation is executed on that record**_. I have Vertex A connected to Vertex B1 and Vertex B2 with the same edge class.
My objective is to delete edge between both and I am doing this in loop. First this is executed.
`DELETE EDGE FROM #13:438 TO #12:65377`
Works fine. Then when executing this 
`DELETE EDGE FROM #13:438 TO #12:65375` 
gives error:
`com.orientechnologies.orient.server.distributed.task.ODistributedRecordLockedException: Timeout (3756ms) on acquiring lock on record #13:438 on server 'node2'. It is locked by request 0.10791....` 

Any idea how to solve this?

**Comment by lvca** [comment] 2017-06-09 12:36
@nishantkumar1292 what release?

**Comment by nishantkumar1292** [comment] 2017-06-09 16:44
I am running two server nodes in distributed mode in OrientDB 2.2.17 .

**Comment by lvca** [comment] 2017-06-10 10:13
Please use v2.2.21.

**Comment by nishantkumar1292** [comment] 2017-06-13 08:40
Started using v2.2.21 but now I am not able to start the server nodes. Every node starts as master and the members list does not show the other server. The distributed mode was running fine in 2.2.17. I have the same hazelcast.xml file.
Am I missing something?
Error:
`2017-06-13 08:21:49:839 INFO  OrientDB Server is active v2.2.21 (build 491997a502b8b90210b269824755c56981765034). [OServer]`
`2017-06-13 08:23:51:712 INFO  [172.87.45.743]:2434 [orientdb] [3.6.5] Could not connect to:/172.31.75.96:2435. Reason: SocketException[Connection timed out to address /172.31.17.48:2435] [InitConnectionTask]`
`2017-06-13 08:23:51:712 INFO  [172.87.45.743]:2434 [orientdb] [3.6.5] Could not connect to: /[ip]:2434. Reason: SocketException[Connection timed out to address /[172.31.75.96]:2434] [InitConnectionTask]`
...and this continues. The same is happening for the other server as well.

**Comment by lvca** [comment] 2017-06-13 16:40
Please check the network configuration in `config/hazelcast.xml` and `config/orientdb-server-config.xml`

**Comment by nishantkumar1292** [comment] 2017-06-22 09:16
The servers and connections are working fine. However I am still getting the `ODistributedRecordLockedException` error.

`Error: com.orientechnologies.orient.server.distributed.task.ODistributedRecordLockedException: Timeout (5000ms) on acquiring lock on record #12:84870 on server 'node1'. It is locked by request 0.90132.`
`DB name="db_development"`
`DB name="db_development"`

I am running `REPAIR DATABASE --fix-graph -skipEdges=5673222` command in console.

Any idea why is it happening?

**Comment by lvca** [comment] 2017-06-22 13:24
@nishantkumar1292 Was that exception given during REPAIR DATABASE?

**Comment by nishantkumar1292** [comment] 2017-06-23 06:36
yes

**Comment by roots-ai** [comment] 2017-06-30 09:30
+1 @nishantkumar1292 
@Ivca! We plan to use  orientdb, in production, where there would be ~10,000 requests/sec. We couldn't find any way to resolve ODistributedRecordLockedException error while even working with only 2 parallel requests on a node, unsure how this is going to scale up.

Is this a bug with Orientdb 2.2.21, or any other way to get this resolved?

**Comment by lvca** [comment] 2017-06-30 18:05
Hi guys,
OrientDB has an optimistic approach avoiding locks as much as possible. Only in this way you can scale up massively. In the case there is a concurrent write operation on the same vertices, the infamous `ODistributedRecordLockedException` is thrown. It's not a bug, this exception extends `ONeedRetryException` that means it has to be managed on the client side.

All the client code should be like:

```
for( int retry = 0; retry < 10; ++retry ){
 try {
  // EXECUTE YOUR COMMAND
  break;

 } catch( ONeedRetryException e ){
   // CONTINUE
 }
}
```

In this way any concurrent operation will be retried (in this case up to 10 times).

**Comment by nishantkumar1292** [comment] 2017-07-03 08:47
We are getting this error when executing delete command over an edge class `DELETE EDGE edge_class_name` through OrientDB studio. 
Error: `com.orientechnologies.orient.server.distributed.task.ODistributedRecordLockedException: Timeout (592ms) on acquiring lock on record #13:3 on server 'node1'. It is locked by request 0.26 DB name=db_development`
Even 10 minutes minutes after this error, we are not able to execute update command on `#13:3`.
Firstly, how do we solve this?
Secondly, is there a way to figure out which request is locking the node as the error mentions request 0.26. How do we know what is request 0.26?

**Comment by roots-ai** [comment] 2017-07-10 04:31
@lvca Can you please reply?

**Comment by lvca** [comment] 2017-07-10 05:12
@roots-ai can you execute a `kill -5 <pid>` to get from the system output the internal status of the server?

**Comment by nishantkumar1292** [comment] 2017-07-10 13:43
The command `kill -5 <pid>` gave [this](http://m.uploadedit.com/ba3s/1499693616822.log) output.
The output is hosted as it was too long to be pasted in the comment.
@lvca Can you please look at the log and tell us where are we going wrong.

We added the following code as you suggested:
```
for( int retry = 0; retry < 10; ++retry ){
 try {
  // EXECUTE YOUR COMMAND
  break;

 } catch( ONeedRetryException e ){
   // CONTINUE
 }
}
```

But the retry continues for indefinite time and the record is not unlocked. So this does not solve our issue.

**Comment by roots-ai** [comment] 2017-07-11 11:09
Hi @lvca ! We've shared the output above, please help.

**Comment by nishantkumar1292** [comment] 2017-07-12 06:27
We also have another major issue here!!
The contents of our database get erased without our knowledge and this is happening frequently. This generally happens when there is the database is not shut down properly or heavy query is run on the database. Also sometimes, the query gets interrupted due to some reason and when we restart the server, the database folder is empty.
@lvca ..What is happening here?

**Comment by lvca** [comment] 2017-07-12 07:15
About this issue, I see there is a problem here:
```
+----------+------+-----------------------+----------+-----------+
|rid       |server|acquiredOn             |reqId     |threadCount|
+----------+------+-----------------------+----------+-----------+
|#12:5470  |node1 |2017-07-10 04:48:06:735|0.17009966|1          |
|#12:5544  |node1 |2017-07-10 04:33:02:517|0.14821725|1          |
|#12:5760  |node1 |2017-07-10 04:27:25:125|0.13881368|1          |
|#12:7498  |node1 |2017-07-09 17:00:58:168|0.12585373|1          |
|#12:8981  |node1 |2017-07-07 17:01:40:835|0.10516242|1          |
|#12:271967|node1 |2017-07-10 12:47:07:750|0.24484296|1          |
|#12:443953|node1 |2017-07-10 12:07:22:760|0.24458014|1          |
|#13:111   |node1 |2017-07-10 12:13:29:786|0.24468003|1          |
+----------+------+-----------------------+----------+-----------+
```

The locks are kept for way too much time causing this problem. It looks like the background thread that checks the timeout is not working. I'm investigating it.

**Comment by lvca** [comment] 2017-07-12 07:18
Question: is it possible you're running some commands non in transaction?

**Comment by nishantkumar1292** [comment] 2017-07-12 09:53
@lvca **Answer to your question**: Earlier we were running the queries with `transaction=true` but later to solve `ODistributedRecordLockedException` we made `transaction=false`. So currently we are running commands not in transaction.

**About emptying of database**: The database folder gets erased - all the contents of the folder. The folder is there but the contents are erased.
```
2017-07-11 13:06:59:773 INFO  Loading configuration from: /home/ubuntu/orientdb-community-2.2.21/config/orientdb-server-config.xml... [OServerConfigurationLoaderXml]
2017-07-11 13:06:59:950 INFO  OrientDB Server v2.2.21 (build 491997a502b8b90210b269824755c56981765034) is starting up... [OServer]
2017-07-11 13:06:59:955 INFO  Databases directory: /home/ubuntu/data/databases [OServer]
2017-07-11 13:06:59:993 INFO  OrientDB auto-config DISKCACHE=26,200MB (heap=3,925MB direct=524,288MB os=32,174MB) [OMemoryAndLocalPaginatedEnginesInitializer]
2017-07-11 13:07:00:123 INFO  Listening binary connections on 0.0.0.0:2424 (protocol v.36, socket=default) [OServerNetworkListener]
2017-07-11 13:07:00:126 INFO  Listening http connections on 0.0.0.0:2480 (protocol v.10, socket=default) [OServerNetworkListener]
2017-07-11 13:07:00:132 INFO  Installing dynamic plugin 'orientdb-studio-2.2.21.zip'... [OServerPluginManager]
2017-07-11 13:07:00:135 INFO  ODefaultPasswordAuthenticator is active [ODefaultPasswordAuthenticator]
2017-07-11 13:07:00:136 INFO  OServerConfigAuthenticator is active [OServerConfigAuthenticator]
2017-07-11 13:07:00:136 INFO  OSystemUserAuthenticator is active [OSystemUserAuthenticator]
2017-07-11 13:07:00:151 INFO  Installed GREMLIN language v.2.6.0 - graph.pool.max=50 [OGraphServerHandler]$ANSI{green {db=OSystem}} Exception `1FC53E33` in storage `OSystem`
com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/home/ubuntu/data/databases/OSystem' with mode=rw
	DB name="OSystem"
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:299)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:258)
	at com.orientechnologies.orient.server.OServer.openDatabaseBypassingSecurity(OServer.java:980)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:947)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:932)
	at com.orientechnologies.orient.server.OSystemDatabase.openSystemDatabase(OSystemDatabase.java:92)
	at com.orientechnologies.orient.server.OSystemDatabase.execute(OSystemDatabase.java:99)
	at com.orientechnologies.orient.server.security.ODefaultServerSecurity.getSystemUser(ODefaultServerSecurity.java:284)
	at com.orientechnologies.orient.server.security.authenticator.OSystemUserAuthenticator.getUser(OSystemUserAuthenticator.java:126)
	at com.orientechnologies.orient.server.security.ODefaultServerSecurity.getUser(ODefaultServerSecurity.java:411)
	at com.orientechnologies.orient.server.OServer.getUser(OServer.java:773)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.config(ODistributedAbstractPlugin.java:172)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.config(OHazelcastPlugin.java:107)
	at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:1233)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:397)
	at com.orientechnologies.orient.server.OServerMain$1.run(OServerMain.java:46)
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Can not open storage it is acquired by other process
	DB name="OSystem"
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedStorageDirtyFlag.lockFile(OPaginatedStorageDirtyFlag.java:96)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedStorageDirtyFlag.open(OPaginatedStorageDirtyFlag.java:129)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.preOpenSteps(OLocalPaginatedStorage.java:395)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:250)
	... 15 more

2017-07-11 13:07:00:207 SEVER getUser() Exception: Cannot open local storage '/home/ubuntu/data/databases/OSystem' with mode=rw
	DB name="OSystem" [OSystemUserAuthenticator]
2017-07-11 13:07:00:247 INFO  Configuring Hazelcast from '/home/ubuntu/orientdb-community-2.2.21/config/hazelcast.xml'. [FileSystemXmlConfig]
2017-07-11 13:07:00:283 WARNI Name of the hazelcast schema location incorrect using default [AbstractXmlConfigHelper]
2017-07-11 13:07:00:502 INFO  [LOCAL] [root] [3.6.5] Interfaces is disabled, trying to pick one address from TCP-IP config addresses: [10.2.2.2, 10.1.1.1] [DefaultAddressPicker]
2017-07-11 13:07:00:502 INFO  [LOCAL] [root] [3.6.5] Prefer IPv4 stack is true. [DefaultAddressPicker]
2017-07-11 13:07:00:508 INFO  [LOCAL] [root] [3.6.5] Picked Address[10.1.1.1]:2481, using socket ServerSocket[addr=/0:0:0:0:0:0:0:0,localport=2481], bind any local is true [DefaultAddressPicker]
2017-07-11 13:07:00:518 INFO  [10.1.1.1]:2481 [root] [3.6.5] Hazelcast 3.6.5 (20160823 - e4af3d9) starting at Address[10.1.1.1]:2481 [system]
2017-07-11 13:07:00:518 INFO  [10.1.1.1]:2481 [root] [3.6.5] Copyright (c) 2008-2016, Hazelcast, Inc. All Rights Reserved. [system]
2017-07-11 13:07:00:518 INFO  [10.1.1.1]:2481 [root] [3.6.5] Configured Hazelcast Serialization version : 1 [system]
2017-07-11 13:07:00:660 INFO  [10.1.1.1]:2481 [root] [3.6.5] Backpressure is disabled [OperationService]
2017-07-11 13:07:00:678 INFO  [10.1.1.1]:2481 [root] [3.6.5] Starting with 1 generic operation threads and 1 partition operation threads. [ClassicOperationExecutor]
2017-07-11 13:07:00:979 INFO  [10.1.1.1]:2481 [root] [3.6.5] Creating TcpIpJoiner [Node]
2017-07-11 13:07:00:980 INFO  [10.1.1.1]:2481 [root] [3.6.5] Address[10.1.1.1]:2481 is STARTING [LifecycleService]
2017-07-11 13:07:01:048 INFO  [10.1.1.1]:2481 [root] [3.6.5] TcpIpConnectionManager configured with Non Blocking IO-threading model: 3 input threads and 3 output threads [NonBlockingIOThreadingModel]
2017-07-11 13:07:01:066 INFO  [10.1.1.1]:2481 [root] [3.6.5] Connecting to /10.2.2.2:2482, timeout: 0, bind-any: true [InitConnectionTask]
2017-07-11 13:07:01:067 INFO  [10.1.1.1]:2481 [root] [3.6.5] Connecting to /10.2.2.2:2481, timeout: 0, bind-any: true [InitConnectionTask]
2017-07-11 13:07:01:067 INFO  [10.1.1.1]:2481 [root] [3.6.5] Connecting to /10.1.1.1:2480, timeout: 0, bind-any: true [InitConnectionTask]
2017-07-11 13:07:01:067 INFO  [10.1.1.1]:2481 [root] [3.6.5] Connecting to /10.2.2.2:2480, timeout: 0, bind-any: true [InitConnectionTask]
2017-07-11 13:07:01:068 INFO  [10.1.1.1]:2481 [root] [3.6.5] Connecting to /10.1.1.1:2482, timeout: 0, bind-any: true [InitConnectionTask]
2017-07-11 13:07:01:068 INFO  [10.1.1.1]:2481 [root] [3.6.5] Could not connect to: /10.2.2.2:2480. Reason: SocketException[Connection refused to address /10.2.2.2:2480] [InitConnectionTask]
2017-07-11 13:07:01:068 INFO  [10.1.1.1]:2481 [root] [3.6.5] Could not connect to: /10.1.1.1:2482. Reason: SocketException[Connection refused to address /10.1.1.1:2482] [InitConnectionTask]
2017-07-11 13:07:01:069 INFO  [10.1.1.1]:2481 [root] [3.6.5] Address[10.1.1.1]:2482 is added to the blacklist. [TcpIpJoiner]
2017-07-11 13:07:01:069 INFO  [10.1.1.1]:2481 [root] [3.6.5] Could not connect to: /10.2.2.2:2482. Reason: SocketException[Connection refused to address /10.2.2.2:2482] [InitConnectionTask]
2017-07-11 13:07:01:069 INFO  [10.1.1.1]:2481 [root] [3.6.5] Could not connect to: /10.2.2.2:2481. Reason: SocketException[Connection refused to address /10.2.2.2:2481] [InitConnectionTask]
2017-07-11 13:07:01:069 INFO  [10.1.1.1]:2481 [root] [3.6.5] Address[10.2.2.2]:2481 is added to the blacklist. [TcpIpJoiner]
2017-07-11 13:07:01:070 INFO  [10.1.1.1]:2481 [root] [3.6.5] Address[10.2.2.2]:2482 is added to the blacklist. [TcpIpJoiner]
2017-07-11 13:07:01:070 INFO  [10.1.1.1]:2481 [root] [3.6.5] Address[10.2.2.2]:2480 is added to the blacklist. [TcpIpJoiner]
2017-07-11 13:07:01:074 INFO  [10.1.1.1]:2481 [root] [3.6.5] Established socket connection between /10.1.1.1:57901 and /10.1.1.1:2480 [TcpIpConnectionManager]
2017-07-11 13:07:06:062 INFO  [10.1.1.1]:2481 [root] [3.6.5] 


Members [1] {
	Member [10.1.1.1]:2481 this
}
 [TcpIpJoiner]
2017-07-11 13:07:06:062 WARNI [10.1.1.1]:2481 [root] [3.6.5] Config seed port is 2480 and cluster size is 1. Some of the ports seem occupied! [Node]
2017-07-11 13:07:06:085 INFO  [10.1.1.1]:2481 [root] [3.6.5] Address[10.1.1.1]:2481 is STARTED [LifecycleService]
2017-07-11 13:07:06:086 INFO  Starting distributed server 'node1' (hzID=6898f945-c104-4980-9b05-3f516b7c627c)... [OHazelcastPlugin]
2017-07-11 13:07:06:089 INFO  Distributed cluster time=Tue Jul 11 13:07:06 UTC 2017 (delta from local node=0)... [OHazelcastPlugin]
2017-07-11 13:07:06:109 INFO  [10.1.1.1]:2481 [root] [3.6.5] Initializing cluster partition table arrangement... [InternalPartitionService]
2017-07-11 13:07:06:170 INFO  [node1] Registered local server with nodeId=0 [OHazelcastPlugin]
2017-07-11 13:07:06:187 INFO  Distributed Lock Manager server is 'node1' [OHazelcastPlugin]
2017-07-11 13:07:06:194 INFO  [node1] Loaded configuration for database 'OSystem' from disk: /home/ubuntu/orientdb-community-2.2.21/config/default-distributed-db-config.json [ODistributedStorage]
2017-07-11 13:07:06:203 INFO  [node1] Servers in cluster: [node1] [OHazelcastPlugin]
2017-07-11 13:07:06:207 INFO  [node1] Opening database 'db_development'... [OHazelcastPlugin]
2017-07-11 13:07:06:209 INFO  [node1] Loaded configuration for database 'db_development' from disk: /home/ubuntu/data/databases/db_development/distributed-config.json [ODistributedStorage]
2017-07-11 13:07:06:222 INFO  [node1] Distributed servers status (*=current @=lockmgr[node1]):

+-----------+--------+---------+-----+---------+-----------------+-----------------+-----------------------+
|Name       |Status  |Databases|Conns|StartedOn|Binary           |HTTP             |UsedMemory             |
+-----------+--------+---------+-----+---------+-----------------+-----------------+-----------------------+
|node1(*)(@)|STARTING|         |1    |13:07:00 |10.1.1.1:2424    |10.1.1.1:2480    |355.14MB/3.83GB (9.05%)|
+-----------+--------+---------+-----+---------+-----------------+-----------------+-----------------------+
 [OHazelcastPlugin]
2017-07-11 13:07:06:224 INFO  [node1] Current node started as MASTER for database 'db_development' [OHazelcastPlugin$6]$ANSI{green {db=db_development}} Exception `6880A525` in storage `db_development`
com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/home/ubuntu/data/databases/db_development' with mode=rw
	DB name="db_development"
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:299)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:258)
	at com.orientechnologies.orient.server.OServer.openDatabaseBypassingSecurity(OServer.java:980)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:947)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:932)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.reassignClustersOwnership(ODistributedAbstractPlugin.java:733)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin$6.call(OHazelcastPlugin.java:740)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin$6.call(OHazelcastPlugin.java:727)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.executeInDistributedDatabaseLock(ODistributedAbstractPlugin.java:1649)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.loadLocalDatabases(OHazelcastPlugin.java:727)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.startup(OHazelcastPlugin.java:254)
	at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:1242)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:397)
	at com.orientechnologies.orient.server.OServerMain$1.run(OServerMain.java:46)
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Can not open storage it is acquired by other process
	DB name="db_development"
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedStorageDirtyFlag.lockFile(OPaginatedStorageDirtyFlag.java:96)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedStorageDirtyFlag.open(OPaginatedStorageDirtyFlag.java:129)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.preOpenSteps(OLocalPaginatedStorage.java:395)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:250)
	... 13 more
[node1] Error on starting distributed plugin
com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/home/ubuntu/data/databases/db_development' with mode=rw
	DB name="db_development"
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:299)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:258)
	at com.orientechnologies.orient.server.OServer.openDatabaseBypassingSecurity(OServer.java:980)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:947)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:932)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.reassignClustersOwnership(ODistributedAbstractPlugin.java:733)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin$6.call(OHazelcastPlugin.java:740)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin$6.call(OHazelcastPlugin.java:727)
	at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.executeInDistributedDatabaseLock(ODistributedAbstractPlugin.java:1649)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.loadLocalDatabases(OHazelcastPlugin.java:727)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.startup(OHazelcastPlugin.java:254)
	at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:1242)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:397)
	at com.orientechnologies.orient.server.OServerMain$1.run(OServerMain.java:46)
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Can not open storage it is acquired by other process
	DB name="db_development"
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedStorageDirtyFlag.lockFile(OPaginatedStorageDirtyFlag.java:96)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedStorageDirtyFlag.open(OPaginatedStorageDirtyFlag.java:129)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.preOpenSteps(OLocalPaginatedStorage.java:395)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:250)
	... 13 more

2017-07-11 13:07:12:363 WARNI Received signal: SIGINT [OSignalHandler]
2017-07-11 13:07:12:364 INFO  [10.1.1.1]:2481 [root] [3.6.5] Running shutdown hook... Current state: ACTIVE [Node]
2017-07-11 13:07:12:364 INFO  [10.1.1.1]:2481 [root] [3.6.5] Address[10.1.1.1]:2481 is SHUTTING_DOWN [LifecycleService]
2017-07-11 13:07:12:364 WARNI [10.1.1.1]:2481 [root] [3.6.5] Terminating forcefully... [Node]
2017-07-11 13:07:12:364 INFO  [10.1.1.1]:2481 [root] [3.6.5] Shutting down connection manager... [Node]
```

**Comment by lvca** [comment] 2017-07-13 08:02
About the original error, I found a bug with non-tx locks. Fixed in 2.2.x branch. About the other error, during the installation of the database, something went wrong, but it should be in the logs. Do you still have them?

**Comment by nishantkumar1292** [comment] 2017-07-13 09:46
This was the latest log I had which was related to the issue from the logs folder. Are database installation logs stored separately? If no, then I might not have it. Any way fix this issue.. @lvca . We are using Ruby and [active-orient](https://github.com/topofocus/active-orient) to enter data into OrientDB.
Moreover for the original locks error, do I have to update my OrientDB or will it be released with the next 2.2.x version? We have to use this in production so cant use OrientDB from development branch.

**Comment by nishantkumar1292** [comment] 2017-07-17 09:00
Hi @lvca ...any updates how do we resolve the `ODistributedRecordLockedException` bug on our end?

**Comment by lvca** [comment] 2017-07-18 16:09
@nishantkumar1292 this bug has been fixed. You can try with last 2.2.x snapshot.

**Closed** 2017-08-02 18:49 UTC
Labels: question, waiting reply

**Comment by decebal** [comment] 2017-10-31 12:44
I still get this in 2.2.29

**Comment by decebal** [comment] 2017-10-31 16:55
Nope, sorry won't work.
 I can't of want to blame this commit for all my problems:
https://github.com/orientechnologies/orientdb/commit/07c48dc9a9a74b227d7dbd98d280503d320e4067

**Comment by tglman** [comment] 2017-11-15 18:05
hi @decebal,

This commit refer to 3.0.0 SNAPSHOT, you don't have this change in 2.2.29.

Regards
