### ISSUE TITLE
Timeout on acquiring lock when insert duplicated record in distributed mode

### ISSUE THREAD

**Issue by ray3888** [orientechnologies/orientdb#7391] opened 2017-05-03 15:31 UTC
## issue:
when inserting duplicated record (with unique index) in distributed mode, have following exception:
ODistributedRecordLockedException: Timeout (3938ms) on acquiring lock on record #13:1 on server 'node2'. It is locked by request 0.14
For version 2.1.x, OrientDB will throw ORecordDuplicatedException, which I think make sense. because I can handle it immediately without delay.  
why v2.2.x does not throw ORecordDuplicatedException, did I miss something? 

## Expected behavior  
should throw ORecordDuplicatedException

## Actual behavior  
ODistributedRecordLockedException: Timeout (3938ms) on acquiring lock on record #13:1 on server 'node2'. It is locked by request 0.14

## Steps to reproduce  
1. create unique index:
drop class orion_v unsafe;
create class orion_v extends v;
create property orion_v.pk string;
alter property orion_v.pk mandatory true;
drop index idx_orion_v_pk;
create index idx_orion_v_pk on orion_v(pk) unique_hash_index;

2. run java code:
String pk1="11";
graph.addVertex("class:orion_v","pk",pk1);
graph.addVertex("class:orion_v","pk",pk1);
graph.commit();

**Comment by lvca** [comment] 2017-05-03 22:33
In your pseudo code to reproduce the problem I don't see any edge. It's weird that you have a `ODistributedRecordLockedException` with just adding vertices. If this is the case, can you please provide a test case?

**Comment by ray3888** [comment] 2017-05-04 02:55
yes, no need edge. I just tested it on win 10, same exception.
	@Test
	public void testDserver() throws Exception {
		OrientGraphFactory factory = new OrientGraphFactory("remote:localhost:2424/orion" , "admin", "admin").setupPool(1,50);
		OrientBaseGraph graph=factory.getTx();
		String pk1="11";
		graph.addVertex("class:orion_v","pk",pk1);
		graph.addVertex("class:orion_v","pk",pk1);
		graph.commit();
		graph.shutdown();
	}

**Comment by lvca** [comment] 2017-05-04 05:42
What record is #13:1 ? Can you print here the result of `select from #13:1`?

**Comment by ray3888** [comment] 2017-05-04 05:56
the result is empty, seem orientdb server catch the ORecordDuplicatedException and commit fail. 
output of above test case is : 

com.orientechnologies.orient.server.distributed.task.ODistributedRecordLockedException: Timeout (3963ms) on acquiring lock on record #22:0 on server 'node1'. It is locked by request 0.7
	DB name="db1"
	DB name="db1"
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.throwSerializedException(OChannelBinaryAsynchClient.java:442)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:393)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:275)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:167)
	at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:2225)
	at com.orientechnologies.orient.client.remote.OStorageRemote$28.execute(OStorageRemote.java:1396)
	at com.orientechnologies.orient.client.remote.OStorageRemote$28.execute(OStorageRemote.java:1368)
	at com.orientechnologies.orient.client.remote.OStorageRemote$2.execute(OStorageRemote.java:198)
	at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:243)
	at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperationRetry(OStorageRemote.java:195)
	at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperation(OStorageRemote.java:206)
	at com.orientechnologies.orient.client.remote.OStorageRemote.commit(OStorageRemote.java:1368)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:533)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:104)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2840)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2809)
	at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.commit(OrientTransactionalGraph.java:182)
	at com.smy.util.OrientDBUtilTest.testDserver(OrientDBUtilTest.java:469)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by ray3888** [comment] 2017-05-04 06:04
additionally, there is following log in orient-server.log.0 after changing log level to FINE,  seems orientdb server catch the ORecordDuplicatedException but not unlock the record.

2017-05-03 19:11:23:900 FINE  }109 Committing transaction 69 on database 'orion' (items=1)... [OLocalPaginatedStorage]Error during transaction commit, transaction will be rolled back (tx-id=69)
com.orientechnologies.orient.core.storage.ORecordDuplicatedException: Cannot index record #11:7036: found duplicated key '11' in index 'idx_orion_v_pk' previously assigned to the record #11:7035
        DB name="orion" INDEX=idx_orion_v_pk RID=#11:7035

**Comment by lvca** [comment] 2017-05-04 09:08
This is interesting. So the problem is on duplicated key in the same distributed transaction?

**Comment by ray3888** [comment] 2017-05-04 09:14
yes

**Comment by lvca** [comment] 2017-05-04 09:14
In branch 2.2.x we improved the management of timeouts with distributed. Could you please try with 2.2.20-SNAPSHOT if the error persists?

**Comment by ray3888** [comment] 2017-05-04 16:30
I tried 2.2.20-SNAPSHOT from git, the code stuck at line "graph.commit()", still failed. 

```
@Test
public void testDserver() throws Exception {
	OrientGraphFactory factory = new OrientGraphFactory("remote:localhost:2424/db1" , "admin", "admin").setupPool(1,50);
	OrientBaseGraph graph=factory.getTx();
	String pk1="11";
	graph.command(new OCommandSQL("drop class v1 unsafe")).execute();
	graph.command(new OCommandSQL("create class v1 extends v")).execute();
	graph.command(new OCommandSQL("create property v1.pk string")).execute();
	graph.command(new OCommandSQL("alter property v1.pk mandatory true")).execute();
	graph.command(new OCommandSQL("drop index idx_v1_pk")).execute();
	graph.command(new OCommandSQL("create index idx_v1_pk on v1(pk) unique_hash_index")).execute();
	graph.addVertex("class:v1","pk",pk1);
	graph.addVertex("class:v1","pk",pk1);
	graph.commit();
	graph.shutdown();
}
```

**Comment by lvca** [comment] 2017-05-19 06:13
We pushed a fix a few hours ago that seems the very same bug. Could you please build an OrientDB distribution from 2.2.x and check if this is working now? Thanks in advance.

**Comment by ray3888** [comment] 2017-05-19 08:11
I tried to start orientdb with -Ddistributed=true in IDEA, but have following exception, did I miss something.
BTW I can start with -Ddistributed=false, and pass the test case.

> 
> com.orientechnologies.orient.server.distributed.ODistributedStartupException: Error on starting distributed plugin
> 	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.startup(OHazelcastPlugin.java:309)
> 	at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:1242)
> 	at com.orientechnologies.orient.server.OServer.activate(OServer.java:397)
> 	at com.orientechnologies.orient.server.OServerMain$1.run(OServerMain.java:46)
> Caused by: com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage 'D:/1ray/tool/database/graph/OrientDB/orientdb-2.2.x/databases/db1' with mode=rw
> 	DB name="db1"
> 	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:298)
> 	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:258)
> 	at com.orientechnologies.orient.server.OServer.openDatabaseBypassingSecurity(OServer.java:980)
> 	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:947)
> 	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:932)
> 	at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.reassignClustersOwnership(ODistributedAbstractPlugin.java:727)
> 	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin$6.call(OHazelcastPlugin.java:740)
> 	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin$6.call(OHazelcastPlugin.java:727)
> 	at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.executeInDistributedDatabaseLock(ODistributedAbstractPlugin.java:1643)
> 	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.loadLocalDatabases(OHazelcastPlugin.java:727)
> 	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.startup(OHazelcastPlugin.java:254)
> 	... 3 more
> Caused by: com.orientechnologies.orient.core.exception.OStorageException: File with name internal.pcl does not exist in storage db1
> 	DB name="db1"
> 	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.loadFile(OWOWCache.java:428)
> 	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.openFile(ODurableComponent.java:183)
> 	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.open(OPaginatedCluster.java:215)
> 	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.openClusters(OAbstractPaginatedStorage.java:353)
> 	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:268)
> 	... 13 more

**Comment by lvca** [comment] 2017-05-19 08:39
Which release are you using? The error is `File with name internal.pcl does not exist in storage db1`. It looks like some file is missing?

**Comment by ray3888** [comment] 2017-05-19 09:26
I can start it using branch 2.2.18, but after checkout to 2.2.x , it fail to start .  with same config.

**Comment by ray3888** [comment] 2017-05-19 13:38
the test case passed just now, thanks. 
will run other test cases later.

**Comment by lvca** [comment] 2017-05-19 14:55
Cool, I'm closing this exception, in case the problem persists, please comment this issue, so I can reopen it. Thanks.

**Closed by lvca** 2017-05-19 14:55 UTC
Labels: bug

**Comment by sblommers** [comment] 2017-05-31 09:03
Just to confirm.

I had this same problem with Object API in distributed mode, using 2.2.20 it did not throw me this exception and halts everything, in my case it deadlocks without a timeout. After building 2.2.21 snapshot all is fine

**Comment by giggs131400** [comment] 2017-08-22 15:21
I'm using orientdb 2.22 in distribute environment, when i use concurrent thread to write the data and it occurs the exception 
Error: com.orientechnologies.orient.server.distributed.task.ODistributedRecordLockedException: Timeout (5000ms) on acquiring lock on record #46:0 on server 'node75'. It is locked by request 0.324309
	DB name="graphics"
	DB name="graphics"

below is my code:

i will create the sql by my java code, and then using java api to execute it.

java code:
OrientGraph graph = getOrientGraphTx();
graph.command(new OCommandScript(sql)).execute();

sql:<br/>
BEGIN <br/>
 LET a0 = CREATE EDGE tic FROM #17:0 TO #52:0<br/>
LET a1 = CREATE EDGE trip FROM #17:0 TO #28:0<br/>
LET a2 = CREATE EDGE tmtel FROM #17:0 TO #59:0<br/>
 COMMIT RETRY 0<br/>
 RETURN [$a0, $a1, $a2]<br/>

I have some questions:<br/>
a. is that possible if a connection disconnected, and the record still locked?<br/>
b. how long the lock will be released? is there any way to unlock the recored?<br/>
c. Is there any better way to avoid such exceptipn?<br/>
d. if it is caused by a deallock, how can i config it to found it?

Thanks

**Comment by arpitaagarwal** [comment] 2018-11-15 08:30
I am using Orient 3.0.10 and facing same issue on concurrent write. I have created following setup - 
- 2 node cluster
- copied orientdb folder at 2 different locations and started ./dserver.sh file. Both nodes connected to  each other through multicast
- Using Person-FriendOf example code to write 10k Person-FriendOf-Person (vertex-edge-vertex). There are multiple threads writing same data each.
- Person:name has unique index

It works well for 2 threads but as number of threads increases, it times out.
Getting following logs - Timeout (1244ms) on waiting for synchronous responses from nodes=[node2, node1] responsesSoFar=[node2] request=(id=1.105226 task=TxPhase1) [ODistributedDatabaseImpl]

Any clues?

**Comment by jonsalvas** [comment] 2019-08-01 06:45
Same issue in 3.0.13. Any ideas how we can fix this?
