### ISSUE TITLE
OConcurrentModificationException: Also after recreating my db I can not bootstrap my db anymore.

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientdb#5219] opened 2015-10-25 17:20 UTC
Orientdb: 2.0.14 - 2.0.15
OrientJs

This issue happens after this transaction (The transaction has worked since months !!)
```
LET $0 = SELECT max($depth) as InsertedAtDepth, @rid, * " + "FROM ( TRAVERSE out('%s') FROM %s ) WHERE @class = '%s' or @class = 'Root'
LET $1 = create vertex Node cluster %s content %s
LET $2 = create edge %s cluster %s from $t0 to $t1
```

suddenly I got the following issue
```
java.lang.NullPointerException [ONetworkProtocolHttpDb]
2015-10-25 16:47:31:801 SEVERE Internal server error:
```

after some time I figure out orientdb breaks when I use the wildcard `*` projection in the query. I removed the wildcard projection and used this one.

```
SELECT max($depth) as InsertedAtDepth, @rid as @rid...
```

But after another try I got following issue:

Stack trace:

```
Sent run-time exception to the client /10.0.2.2:54193: com.orientechnologies.orient.core.exception.OConcurrentModificationException: Cannot UPDATE the record #19:0 because the version is not the latest. Probably you are updating an old record or it has been modified by another user (db=v1 your=v0)
com.orientechnologies.orient.core.exception.OConcurrentModificationException: Cannot UPDATE the record #19:0 because the version is not the latest. Probably you are updating an old record or it has been modified by another user (db=v1 your=v0)
        at com.orientechnologies.orient.core.conflict.OVersionRecordConflictStrategy.checkVersions(OVersionRecordConflictStrategy.java:55)
        at com.orientechnologies.orient.core.conflict.OVersionRecordConflictStrategy.onUpdate(OVersionRecordConflictStrategy.java:42)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.checkAndIncrementVersion(OAbstractPaginatedStorage.java:1887)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doUpdateRecord(OAbstractPaginatedStorage.java:1552)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.updateRecord(OAbstractPaginatedStorage.java:710)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1757)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.addRecord(OTransactionOptimistic.java:312)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.saveRecord(OTransactionOptimistic.java:253)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2316)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:118)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1727)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1718)
        at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:76)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.recursiveLinkSave(ORecordSerializerBinaryV0.java:680)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeOptimizedLink(ORecordSerializerBinaryV0.java:694)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:574)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:262)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:105)
        at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2100)
        at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:695)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitEntry(OAbstractPaginatedStorage.java:1936)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:919)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:488)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:147)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2437)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2407)
        at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.commit(OrientTransactionalGraph.java:162)
        at com.orientechnologies.orient.graph.sql.OGraphCommandExecutorSQLFactory.runInTx(OGraphCommandExecutorSQLFactory.java:126)
        at com.orientechnologies.orient.graph.sql.OGraphCommandExecutorSQLFactory.runInTx(OGraphCommandExecutorSQLFactory.java:142)
        at com.orientechnologies.orient.graph.sql.OCommandExecutorSQLCreateEdge.execute(OCommandExecutorSQLCreateEdge.java:126)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:64)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1191)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1180)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
        at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeCommand(OCommandExecutorScript.java:324)
        at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeLet(OCommandExecutorScript.java:414)
        at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeSQLScript(OCommandExecutorScript.java:199)
        at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeSQL(OCommandExecutorScript.java:148)
        at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.executeInContext(OCommandExecutorScript.java:93)
        at com.orientechnologies.orient.core.command.script.OCommandExecutorScript.execute(OCommandExecutorScript.java:83)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1191)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1180)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1183)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:390)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:217)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
```

***Now I cannot bootstrap my db anymore this error still occurs even when I delete the db.***

**Comment by StarpTech** [comment] 2015-10-25 17:46
After a fresh installation of orientdb and the use of the old query with the wildcard `*` it works. This is very strange. Another issue here is that the transaction must not create a vertex after the first query has failed.

**Comment by tglman** [comment] 2016-05-25 16:27
hi @StarpTech,

Do you still have this issue?

I just noticed now that you are using a the result of a select with projection in a create edge, that is not allowed, because the result of a query with projection is not a proper persistent record but just a projection of it.

In any case how can we reproduce this ?

**Comment by tglman** [comment] 2016-06-22 15:28
any news about this ? from the stack trace i can say that this problem cannot occur in 2.2, i'm going to close it for now, reopen if you have a way to reproduce the problem.

**Closed** 2016-08-11 13:14 UTC
Labels: bug, invalid
