### ISSUE TITLE
IllegalArgumentException OPaginatedClusterV1.internalReadRecord(OPaginatedClusterV1.java:653)

### ISSUE THREAD

**Issue by jayaramcs** [orientechnologies/orientdb#9021] opened 2019-09-27 11:12 UTC
## Expected behavior  
No exception during reads

## Actual behavior  
```
com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #121:8 (cluster: session)
	DB name="myDb"
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.executeReadRecord(ODatabaseDocumentAbstract.java:1379)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.loadRecord(OTransactionNoTx.java:109)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.load(ODatabaseDocumentAbstract.java:1111)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.load(ODatabaseDocumentAbstract.java:85)
	at com.orientechnologies.orient.core.record.impl.ODocument.getProperty(ODocument.java:360)
	at com.orientechnologies.orient.core.record.impl.OEdgeDocument.getTo(OEdgeDocument.java:33)
	at com.orientechnologies.orient.core.record.impl.OEdgeToVertexIterator.next(OEdgeToVertexIterator.java:32)
	at com.orientechnologies.orient.core.record.impl.OEdgeToVertexIterator.next(OEdgeToVertexIterator.java:12)
... 14 common frames omitted
Caused by: java.lang.IllegalArgumentException: 5 > -1274947359
	at java.util.Arrays.copyOfRange(Arrays.java:3519)
	at com.orientechnologies.orient.core.storage.cluster.v1.OPaginatedClusterV1.internalReadRecord(OPaginatedClusterV1.java:653)
	at com.orientechnologies.orient.core.storage.cluster.v1.OPaginatedClusterV1.readRecord(OPaginatedClusterV1.java:609)
	at com.orientechnologies.orient.core.storage.cluster.v1.OPaginatedClusterV1.readRecord(OPaginatedClusterV1.java:592)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doReadRecord(OAbstractPaginatedStorage.java:4792)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:4466)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:1595)
	at com.orientechnologies.orient.core.db.document.SimpleRecordReader.readRecord(SimpleRecordReader.java:21)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.executeReadRecord(ODatabaseDocumentAbstract.java:1342)
	... 14 common frames omitted

```

## Steps to reproduce  
We got this reported from a customer. So not exactly sure how to reproduce it. But the db is corrupted and is unusable. 

Please have a look
Thanks 
Jayaram (Jay)

**Comment by laa** [comment] 2019-09-27 11:16
Hi @jayaramcs what do you mean by unusable? Could you provide more details? May we have logs from customer side?

**Comment by jayaramcs** [comment] 2019-09-27 11:36
By unusable, I mean to say that we are unable to open the db. Queries to open the db result in the above error trace. 

I have been reviewing customer logs and there are no other exceptions or errors reported - either from Orient or from our application. 

The customer shut down the application (we are using embedded mode - so the db as well) and then started back up and started to experience this issue.

**Comment by laa** [comment] 2019-09-27 11:38
@jayaramcs could you send me logs related to OrientDB there is other information aside exceptions which can be useful for me.

**Comment by laa** [comment] 2019-09-27 12:03
@jayaramcs please send me logs to the a.lomakin@sap.com . I will check them.

**Comment by jayaramcs** [comment] 2019-09-27 12:39
I have emailed the log file to your address. The database is hard to acquire since it has customer data.

**Comment by laa** [comment] 2020-06-12 11:45
That caused by the fact that tracking of the length of the cluster was not transactional in early versions. It should be fixed already.

**Closed by laa** 2020-06-12 11:45 UTC
