### ISSUE TITLE
How to properly delete a db?

### ISSUE THREAD

**Issue by kerner1000** [orientechnologies/orientdb#6904] opened 2016-11-10 21:03 UTC
OrientDB v. 2.1.16

Operation System Linux

I use the following code to delete a db:

```
public static void delete(final String url, final DatabaseProvider provider) {

		provider.execute(() -> {
			@SuppressWarnings("resource")
			final ODatabaseDocumentTx documentDatabase = new ODatabaseDocumentTx(url);
			if(documentDatabase.exists()) {
				if(!documentDatabase.isClosed())
					documentDatabase.drop();
			} else {
				logger.warn("Database " + url + " does not exist");
			}
			try {
				final File directory = new File(url.substring(url.indexOf(":") + 1));
				logger.debug("Deleting " + directory);
				FileUtils.deleteDirectory(directory);
			} catch(final Exception e) {
				logger.error(e.getLocalizedMessage(), e);
			}
		});
	}
```
```
public class DatabaseProviderSameThread extends DatabaseProviderProto {

	@Override
	public void execute(final Runnable r) {

		r.run();
	}
[...]

```

When I try to create a db with the same name right after, it fails since the db exists already.

How to properly delete a db?

**Comment by lvca** [comment] 2016-11-11 12:18
Try calling this before to delete the directory `Orient.instance().closeAllStorages();`

**Comment by kerner1000** [comment] 2016-11-11 14:44
Hmm, not quite sure.
This should happen already during the call of `db.drop()`:

```
@Override
  public void drop() {
    checkOpeness();
    checkIfActive();

    checkSecurity(ORule.ResourceGeneric.DATABASE, ORole.PERMISSION_DELETE);

    callOnDropListeners();

    if (metadata != null) {
      metadata.close();
      metadata = null;
    }

    closeOnDelete();

    try {
      if (storage == null)
        storage = Orient.instance().loadStorage(url);

      storage.delete();
      storage = null;

      status = STATUS.CLOSED;
      ODatabaseRecordThreadLocal.INSTANCE.remove();

    } catch (OException e) {
      // PASS THROUGH
      throw e;
    } catch (Exception e) {
      throw new ODatabaseException("Cannot delete database", e);
    }
  }
```

**Comment by lvca** [comment] 2016-11-11 16:36
You're right, `drop()` is enough. Sometimes happens the files remain locker for a while.

**Comment by kerner1000** [comment] 2016-11-14 09:58
Obviously it is not enough, since `db.exists()` returns `true` after the drop. So how can I delete it properly?

**Comment by lvca** [comment] 2016-11-14 14:40
If the `db.exists()` returns true it's a bug. Reopened it. How can I reproduce it? I see in your code you have:

```
if(documentDatabase.exists()) {
                if(!documentDatabase.isClosed())
                    documentDatabase.drop();
            }
```

So if the db is closed it's never dropped. You should change your code with:

```
final ODatabaseDocumentTx documentDatabase = new ODatabaseDocumentTx(url);
if(documentDatabase.exists()) {
  documentDatabase.open("admin","admin");
  documentDatabase.drop();
} 
```

**Comment by lvca** [comment] 2016-11-14 14:40
Please let me know if the problem was in your code, so I can close the issue.

**Comment by kerner1000** [comment] 2016-11-16 08:59
Hi @lvca 
many thanks for your help, it seems to work now!

**Closed** 2016-11-22 09:56 UTC
Labels: question
