### ISSUE TITLE
In Studio Creating edges in Graph view 

### ISSUE THREAD

**Issue by lorlik** [orientechnologies/orientdb#7339] opened 2017-04-14 17:03 UTC
## Expected behavior  
In Graph view when I create an edge between 2 veticies I shouldn't have to manually enter rid of each vertecy.

## Actual behavior  
In Graph view even though I visually selected 2 verticies to create an edge I am still asked to manually enter rids.

## Steps to reproduce  
Create and edge between 2 verticies in Graph view

**Comment by maggiolo00** [comment] 2017-04-14 17:06
hi @lorlik 

which Graph View do you mean?

how do you create an edge?

**Comment by lorlik** [comment] 2017-04-14 17:35
@maggiolo00 , I'm talking about the Web Front end to Orient DB, which you call Studio. In Studio there's a "Graph" tab, which allows one to visualize a graph returned by a query and also to manipulate it.
In that view you can click on an verticy and get then click on a "link" icon which then allows you to connect an arrow (edge) to another verticy on the graph and by clicking on it. Once you click on the second verticy you get a dialog to choose the type of edge you want to create, then it asks you to enter rids for verticies, but it should already know which verticies I clicked on.

**Comment by maggiolo00** [comment] 2017-04-14 17:42
Hi @lorlik 

Studio does not asks the rids of the vertices. Can you post a screenshot?

**Comment by maggiolo00** [comment] 2017-04-14 17:47
I get this

<img width="1280" alt="screen shot 2017-04-14 at 19 44 14" src="https://cloud.githubusercontent.com/assets/98812/25051008/d311fb7a-214a-11e7-8b8f-438ae693da88.png">

and then this 

<img width="1275" alt="screen shot 2017-04-14 at 19 45 55" src="https://cloud.githubusercontent.com/assets/98812/25051053/050f3dcc-214b-11e7-8705-f80bd6e9ceac.png">

By clicking on `Create Edge` the edge will be created without manually insert the rids.

**Comment by lorlik** [comment] 2017-04-14 18:04
I'm creating a specific edge (HasAddress in my case), not E. When I create E, it works as it should.
![image](https://cloud.githubusercontent.com/assets/27507606/25051529/157fe54c-211b-11e7-91d4-42ad7b02ba67.png)

**Comment by maggiolo00** [comment] 2017-04-14 18:06
Ok that should not be visible. 

As temporary workaround remove them. 
They are not used in the creation process

Pleas Tell me if it works

**Comment by lorlik** [comment] 2017-04-14 18:08
What do you mean by "Remove"? If I do not specify rids i get an error.

**Comment by maggiolo00** [comment] 2017-04-14 18:10
@lorlik 

try to remove in/out fields with red trash icon and then click `Create edge`

**Comment by lorlik** [comment] 2017-04-14 18:14
That works, sort of. It let me create the edge, but if I rerun the query I have 2 edges instead of 1.

**Comment by lorlik** [comment] 2017-04-14 18:17
The issue with multiple edges may actually be that deleting an edge using Graph view isn't working. I have multiple duplicate edges after deleting and recreating edges a few times.

**Comment by maggiolo00** [comment] 2017-04-14 18:20
@lorlik 

i was not able to reproduce this with multiple edges

which are the step to reproduce this?

Thanks

**Comment by lorlik** [comment] 2017-04-14 18:20
Confirmed. Edge deletion doesn't work at all.

1. Create an edge between two verticies
2. Remove the edge using the broken link icon
3. Rerun query - everything seems fine
4. Navigate to Schema view
5. Come back to Graph view - the edge is back

**Comment by maggiolo00** [comment] 2017-04-14 18:24
hi @lorlik 

i think it's not a problem of Edge deletion.

The graph is cached so when you navigate Studio and come back to the
Graph view you will see the previously populated Graph.

I think the edge deletion does not update the cache.

I think if you clear the canvas and execute the query again you will see the deletion

**Comment by maggiolo00** [comment] 2017-04-14 18:57
@lorlik 

i confirm it's a cache problem

I've created a new issue to track this

https://github.com/orientechnologies/orientdb-studio/issues/466

Thanks

**Comment by maggiolo00** [comment] 2017-04-18 11:08
Hi @lorlik 

this has been fixed by removing in/out. It will be available in 2.2.19

Thanks

**Closed by maggiolo00** 2017-04-18 11:08 UTC
Labels: bug
