### ISSUE TITLE
HIGH SEVERITY..I was able to retrieve an edge using graph.getVertex(edgeId)! (2.1.3)

### ISSUE THREAD

**Issue by zifnab87** [orientechnologies/orientdb#5089] opened 2015-10-10 02:50 UTC
Possibly related/causing my other issues (#5068, #5033, #5048)
```
		OrientGraph graph = factory.getTx();
		Vertex v = graph.getVertex("#26:0");
		Edge e = graph.getEdge("#26:0");
		System.out.println(v+" "+e);
```

```
v(ContainsPrimitive)[#26:0] e[#26:0][#21:102-ContainsPrimitive->#30:1]
```

I stumbled upon that because it was giving a NullPointer exception trying to access properties that were not there.. The code was supposed to be retrieving a vertex but I debugged it and it was an edge retrieved as a vertex!

@lvca , @laa This happens with any edges that I tried from two classes! I would appreciate it if you could investigate it as soon as possible - you already have my copy of db in the email. I almost switched to a different product and still thinking of it.. 

I checked with every single backup (about 20 of them) from the first one 4 months ago till the last one and all of them are behaving exactly the same way!  I really don't know why my database became so messed up...so early on!

**Comment by lvca** [comment] 2015-10-10 09:24
I checked in the code and there is this check:

    if (!doc.getSchemaClass().isSubClassOf(OrientEdgeType.CLASS_NAME))
      throw new IllegalArgumentException("Class '" + doc.getClassName() + "' is not an edge class");

Trying to create a new test case for it.

**Comment by zifnab87** [comment] 2015-10-10 12:05
@lvca Thanks for the quick response.. What I would expect in my case is
Class ContainsPrimitive is not a *vertex* class. Also what I don't understand is how this edge got into my  code as edge.. I wonder if there is a bug that instead of the DIRECTION.OUT vertex it returns the edge as a vertex too at least for my db

**Comment by zifnab87** [comment] 2015-10-10 15:40
@lvca I recreated my database from scratch and the same thing happens!

``` v(ContainsEntity)[#21:0] e[#21:0][#18:0-ContainsEntity->#13:5]```

**Comment by lvca** [comment] 2015-10-10 20:21
@zifnab87 How can I reproduce it? Do you have a script to generate it?

**Comment by zifnab87** [comment] 2015-10-10 20:45
Yeah I am able anytime.. give me some time I will send it :)

**Comment by zifnab87** [comment] 2015-10-10 20:56
@lvca 

CREATE DATABASE remote:localhost/test2 root admin plocal
CONNECT remote:localhost/test2 admin admin
CREATE CLASS Date extends V
CREATE CLASS Number extends V
CREATE CLASS Has extends E
CREATE VERTEX Date // #11:0
CREATE VERTEX Number //#12:0
CREATE EDGE Has FROM #11:0 TO #12:0 /[Has#13:0{out:#11:0,in:#12:0} v1]

OrientGraphFactory factory = new OrientGraphFactory("remote:localhost/test2");
OrientGraph graph = factory.getTx();
Vertex v = graph.getVertex("#13:0");
Edge e = graph.getEdge("#13:0");
System.out.println(v+" "+e);

Oct 10, 2015 4:56:10 PM com.orientechnologies.common.log.OLogManager log
INFO: OrientDB auto-config DISKCACHE=7,419MB (heap=2,706MB os=12,173MB disk=36,272MB)
v(Has)[#13:0] e[#13:0][#11:0-Has->#12:0]

**Comment by lvca** [comment] 2015-10-12 18:22
This test pass: 

```java

  @Test
  public void edgesCannotBeVertices() {
    OrientGraphNoTx gNoTx = new OrientGraphNoTx(URL, "admin", "admin");
    try {
      OrientVertex v = gNoTx.addVertex(null);
      OrientVertex loadedV = gNoTx.getVertex(v.getIdentity());
      try {
        OrientEdge e = gNoTx.getEdge(v.getIdentity());
        Assert.fail();
      } catch (IllegalArgumentException e) {
        // OK
      }
    } finally {
      gNoTx.shutdown();
    }

    OrientGraph g = new OrientGraph(URL, "admin", "admin");
    try {
      OrientVertex v = g.addVertex(null);
      OrientVertex loadedV = g.getVertex(v.getIdentity());
      try {
        OrientEdge e = g.getEdge(v.getIdentity());
        Assert.fail();
      } catch (IllegalArgumentException e) {
        // OK
      }
    } finally {
      g.shutdown();
    }
  }
```

**Comment by lvca** [comment] 2015-10-12 18:22
So at this point could be the remote connection, let me check it...

**Comment by lvca** [comment] 2015-10-12 18:29
Tested against remote, 2.1.x and develop branch and in all the cases a `IllegalArgumentException` is thrown. @zifnab87 please could you provide an executable test case that shows the problem?

**Comment by zifnab87** [comment] 2015-10-12 20:03
ok I will send it

**Comment by lvca** [comment] 2015-10-12 20:22
Tried with specific vertex class and same result: everything works as expected:

```java

  @Test
  public void edgesCannotBeVertices() {
    OrientGraphNoTx gNoTx = new OrientGraphNoTx(URL, "admin", "admin");
    try {
      gNoTx.createVertexType("TestV");
      gNoTx.createEdgeType("TestE");

      OrientVertex v = gNoTx.addVertex("class:TestV");
      OrientVertex loadedV = gNoTx.getVertex(v.getIdentity());
      try {
        OrientEdge e = gNoTx.getEdge(v.getIdentity().toString());
        Assert.fail();
      } catch (IllegalArgumentException e) {
        // OK
      }
    } finally {
      gNoTx.shutdown();
    }

    OrientGraph g = new OrientGraph(URL, "admin", "admin");
    try {
      OrientVertex v = g.addVertex("class:TestV");
      OrientVertex loadedV = g.getVertex(v.getIdentity().toString());
      try {
        OrientEdge e = g.getEdge(v.getIdentity());
        Assert.fail();
      } catch (IllegalArgumentException e) {
        // OK
      }
    } finally {
      g.shutdown();
    }
  }
```

**Comment by zifnab87** [comment] 2015-10-12 20:37
@lvca I think you are checking the inverse thing as I said in this comment earlier (https://github.com/orientechnologies/orientdb/issues/5089#issuecomment-147082204)

I am requesting an edge through getVertex..

**Comment by lvca** [comment] 2015-10-12 20:56
Got it, I think this is possible because we use Vertex as generic schema-less type, so I guess there is no check if the vertex is an edge. I can check on it, but my question is: why are you retrieving an edge as vertex? I mean, wha's the purpose and why it's so critical? Could you just retrieve it as edge with getEdge()?

**Comment by zifnab87** [comment] 2015-10-12 21:12
Well I didn't do it on purpose @lvca It happened in my code after a complicated insert.. In my models I keep a reference of a vertex about to be updated or just inserted.. For some reason after a specific (tested) use case that I add a big hierarchy of objects, I find an edge in the place of a vertex. This throws an exception because I try to use this vertex to find vertex properties that of course are not on the edge.. This is the bug that led me to find the bug we are discussing. That's why I am very frustrated. This is a case I have many integration tests and yet it manages to fail when some of the nodes are newly inserted..

**Comment by zifnab87** [comment] 2016-03-07 02:20
@lvca this is definitely a bug I don't understand why cannot replicate was added.. I have moved away from OrientDB to TitanDB since December unfortunately.

**Comment by lvca** [comment] 2016-05-12 07:43
@zifnab87 You were right, added check.

**Closed by lvca** 2016-05-12 07:43 UTC
Labels: bug, in progress
