### ISSUE TITLE
Performance goes down on performing huge inserts

### ISSUE THREAD

**Issue by grachit** [orientechnologies/orientdb#5475] opened 2015-12-16 06:49 UTC
I am trying to extract data from sql server to orientdb 2.1.6 for following expected number of edges and vertices:

E       13,797,575
V           14,519

Inserts till now:
E:  6,827,805
V:    12599

My Observation: As we progress with more number of inserts, performance goes down. Profiler does not show any unusual increase in heap. It remains to be within limit of 400 MB(worst case). But When i look under window processes, Working memory utilization set for process continue to increase above 3 GB. Never comes down. 
I believe that, if i ve to look for expected inserts then Memory utilization will go up to 6 GB or more, system will slow down

I ve also enabled command cache.

![image](https://cloud.githubusercontent.com/assets/3464075/11834070/01399a38-a3ef-11e5-90d4-b486f9cb6627.png)

any idea?

**Comment by lvca** [comment] 2015-12-16 08:14
Can you provide us more information like:
- how are you importing data from SQL source? ETL? Your own code?
- how many indexes?

**Comment by grachit** [comment] 2015-12-16 08:18
I have my own code for ETL.
I have 3 types of edges and 3 types of vertices. Only one edge  and each vertices have one index .

**Comment by grachit** [comment] 2015-12-16 08:23
Now working memory utilization is above 6GB and still more to progress
heap usage is around 300 MB

**Comment by grachit** [comment] 2015-12-16 09:00
After completion of process, working memory set for process is still around 6.7 GB:
![image](https://cloud.githubusercontent.com/assets/3464075/11836541/5f3ab768-a401-11e5-8be7-f88c45d21adc.png)

**Comment by laa** [comment] 2015-12-16 13:13
Hi
What is your RAM size ?

On Wed, Dec 16, 2015 at 11:20 AM Luca Garulli <notifications@github.com>
wrote:

> Assigned #5475 <https://github.com/orientechnologies/orientdb/issues/5475>
> to @laa <https://github.com/laa>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/5475#event-493233192>
> .
>
-- 
Best regards,
Andrey Lomakin, R&D lead.
OrientDB Ltd

twitter:@Andrey_Lomakin linkedin:https://ua.linkedin.com/in/andreylomakin

**Comment by grachit** [comment] 2015-12-16 14:14
12 GB

**Comment by grachit** [comment] 2015-12-16 14:18
It's still around 6.7 GB

**Comment by grachit** [comment] 2015-12-21 14:48
any update over it

**Comment by laa** [comment] 2016-04-06 07:44
That is caused by https://github.com/orientechnologies/orientdb/issues/4491 and https://github.com/orientechnologies/orientdb/issues/5267 once they will be fixed this issue will be fixed automatically

**Closed** 2021-08-05 07:41 UTC
Labels: performance
