### ISSUE TITLE
Command not found studio/main.js.map

### ISSUE THREAD

**Issue by sephib** [orientechnologies/orientdb#7469] opened 2017-06-04 08:09 UTC
Hi,
I'm a newbe and when trying to access the OrientDB community version via web studio I get the following error:
```Json
code:405, reason:405, content:Command not found: studio/main.js.map
```
I've updated the `orientdb-server-config.xml` with the following params
```xml
class="com.....handler.OserverSideScriptInterpreter"
<paramaters>
    <parameter value="true" name ="enabled"/>
    <parameter value="SQL, Javascript" name ="allowedLanguages"/>
</paramaters>
```
* I reinstalled NodeJS.
* The installation is on an Intranet environment 
* I'm able to run the console and create and connect to databases

But still I'm not able to access the orient web studio - Any suggestions?
Thx

**Comment by tglman** [comment] 2017-06-05 07:42
hi @sephib,

From your first error seems you have something missing in studio, did you get OrientDB from the official distribution ?

You don't need to enable javascript and run nodeJS to use Studio, nodeJS is needed only in the development flow not at runtime.

Bye

**Comment by maggiolo00** [comment] 2017-06-05 08:53
Hi @sephib 

which browser do you use?

**Comment by sephib** [comment] 2017-06-06 08:49
Hi

1.  Got it from the official OrientDB site
2.  Chrome

**Comment by maggiolo00** [comment] 2017-06-06 08:56
Hi @sephib 

what do you see when go with the browser to the Studio Page?

Is it blank?

**Comment by sephib** [comment] 2017-06-07 16:36
Hi,
It is blank page that looks like this 

[Interrupt](http://javascript:void(0)) 
*

**Comment by maggiolo00** [comment] 2017-06-07 16:45
hi @sephib 

which version of Chrome ? Are you on Windows?
could you try with Firefox?

Thanks

**Comment by maggiolo00** [comment] 2017-07-20 13:39
hi @sephib 

do you have news on this issue?

**Comment by sephib** [comment] 2017-07-23 04:00
Currently no, thx for your response.
S

**Comment by lvca** [comment] 2017-08-05 06:55
Cannot reproduce the issue, closing for now. @sephib, in case you still have this problem, please comment here. Thanks.

**Closed by lvca** 2017-08-05 06:55 UTC
