### ISSUE TITLE
Navigate to Vertices from edge edition in Studio [moved]

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#1023] opened 2012-12-10 16:07 UTC
This is [Issue 1023](http://code.google.com/p/orient/issues/detail?id=1023) moved from a Google Code project.
Added by 2012-08-17T02:34:37.000Z by [pellyado...@yahoo.es](http://code.google.com/u/101429257832963669166/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Medium, Release
### Original description

```
It would be useful in the Form for a edge in the Studio displaying the source and target vertices (or blank if death link) to perform data checking.
```

**Comment by santo-it** [comment] 2017-01-12 16:27
Thanks, closing as duplicate of https://github.com/orientechnologies/orientdb-studio/issues/435

**Closed by santo-it** 2017-01-12 16:27 UTC
Labels: enhancement, studio
