### ISSUE TITLE
Bad IP used in the network configuration

### ISSUE THREAD

**Issue by Pro-Vizion** [orientechnologies/orientdb#6305] opened 2016-06-15 16:20 UTC
## Expected behavior and actual behavior
Each Node server can have a local IP address and a public one.

In previous version (2.1.x) of OrientDB, we could give the public ip address of the current node in hazelcast.xml

```
<network>
	<public-address>195.X.X.46</public-address>
</network>
```
Since v2.2, when starting OrientDB server, it doesn't pick up this value, but take the local preferred ip address. 

`2016-06-15 16:58:56:842 INFO  Registered the new available server '192.168.1.XX:2424' [OStorageRemote]`

It forwards this info to the other nodes. All the nodes outside the networks are then trying to reach this incorrect IP, giving connection errors.

Here the log of the second node called "nodeb" :

```
2016-06-15 16:00:14:420 INFO  Starting distributed server 'nodeb' (hzID=-1)... [OHazelcastPlugin]
2016-06-15 16:00:30.728 [main] INFO com.node.ui.LoggerStream(39)  - [nodeb] Error on starting distributed plugin
java.io.IOException: Cannot connect to host 192.168.1.XX:2424
    at com.orientechnologies.orient.client.binary.OChannelBinaryClientAbstract.<init>(OChannelBinaryClientAbstract.java:73)
    at com.orientechnologies.orient.client.binary.OChannelBinarySynchClient.<init>(OChannelBinarySynchClient.java:32)
    at com.orientechnologies.orient.server.distributed.ORemoteServerChannel.connect(ORemoteServerChannel.java:143)
    at com.orientechnologies.orient.server.distributed.ORemoteServerChannel.<init>(ORemoteServerChannel.java:68)
    at com.orientechnologies.orient.server.distributed.ORemoteServerController.<init>(ORemoteServerController.java:35)
    at com.orientechnologies.orient.server.distributed.impl.ODistributedAbstractPlugin.getRemoteServer(ODistributedAbstractPlugin.java:672)
    at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.startup(OHazelcastPlugin.java:208)
    at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:1182)
    at com.orientechnologies.orient.server.OServer.activate(OServer.java:389)
    at com.node.launcher.Main.startOrientDB(Main.java:278)
    at com.node.launcher.Main.startNode(Main.java:618)
    at com.node.launcher.Main.main(Main.java:650)
Caused by: java.net.SocketTimeoutException: connect timed out
    at java.net.TwoStacksPlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
    at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
    at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
    at java.net.PlainSocketImpl.connect(Unknown Source)
    at java.net.SocksSocketImpl.connect(Unknown Source)
    at java.net.Socket.connect(Unknown Source)
    at com.orientechnologies.orient.client.binary.OChannelBinaryClientAbstract.<init>(OChannelBinaryClientAbstract.java:68)
    ... 11 more
```

## Steps to reproduce the problem
Simply declare a public-ip address in hazelcast.xml and check if this address is beeing used when the node is starting.

## Important Questions
If hazelcast.xml is not used anymore, where do we declare the public-ip address of each node?
The only place i see where we can give an ip address is in `orientdb-server-config.xml ` in the listener section, but this ip address is used to query the database. On our case it must stays : `0.0.0.0`

### Runninng Mode
- [X] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [X] Remote

### Misc
- [X] I have a distributed setup with multiple servers. How many? 2
- [X] I'm using the Enterprise Edition

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [X] v2.2.x - Please specify last number: 2.2.2

### Operating System
- [ ] Linux
- [ ] MacOSX
- [X] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [ ] 7
- [X] 8

**Comment by Pro-Vizion** [comment] 2016-06-17 12:42
Hi, do you have a clue or lead? Our project is stuck on this.
Any help appreciate.
regards

**Comment by andreaiacono** [comment] 2016-06-17 12:59
Hi @Pro-Vizion,
we've found where the problem is, but we didn't find any quick workaround for now. We're working on a fix.

**Comment by Pro-Vizion** [comment] 2016-06-17 13:03
Cool, thanks.

**Comment by Pro-Vizion** [comment] 2016-07-18 09:03
Hi, no news on this?

**Comment by lvca** [comment] 2016-07-18 12:11
@Pro-Vizion have you already tried to set `195.X.X.46` in your orientdb-server-config.xml file for both binary and http protocols? In this way OrientDB is forced to use that IP address.

**Comment by Pro-Vizion** [comment] 2016-08-08 12:31
Hi, yes we tried. As i mentionned in the summary : 
```
The only place i see where we can give an ip address is in orientdb-server-config.xml in the listener section, but this ip address is used to query the database. **On our case it must stays : 0.0.0.0**
```
Also, The public IP address is not necessarily known by the host itself, as it could be forwarded by an external hardware, or a firewal rule, or whatever.

**Comment by lvca** [comment] 2016-08-08 15:00
This has been fixed in v2.2.7-SNAPSHOT.

**Closed by lvca** 2016-08-08 15:00 UTC

**Comment by tanhv90** [comment] 2016-11-14 07:15
Hello @lvca ,

I'm facing the same issue in v2.2.12.
Seem that only place I can setup an IP address is in orientdb-server-config.xml in the listener section. But on my case it must stays : 0.0.0.0

So, when starting, the below error msg occurred
`com.orientechnologies.orient.server.distributed.ODistributedException: Cannot connect to the remote server '10.0.2.15:2424'`

Please refer to [this link on stackoverflow](https://stackoverflow.com/questions/40582190/cannot-run-orientdb-in-distributed-mode-with-server-has-2-ip-address) for more details about my case.
Could you please guide me how to fix or workaround this issue?

Thanks.
Tan

**Comment by tglman** [comment] 2016-11-14 12:32
hi @tanhv90,

You can set the hazelcast [`public-address`](http://docs.hazelcast.org/docs/3.5/manual/html/networkconfiguration.html) field, orient is going to read it and use it.

Hope it helps.

**Comment by tanhv90** [comment] 2016-11-15 03:27
Hello @tglman,

Thanks so much for your support.

Best regards.
