### ISSUE TITLE
[2.1] record.rid returning an object instead of proper RID

### ISSUE THREAD

**Issue by dmarcelino** [orientechnologies/orientdb#3619] opened 2015-02-18 17:39 UTC
Hi guys,

I've tried to add 2.1-SNAPSHOT to `waterline-orientdb` [builds](https://travis-ci.org/appscot/waterline-orientdb/builds/50996659) and it breaks some of my tests. I've looked deeper into it and it seems that OrientDB 2.1 is returning different things than 2.0.2 in certain conditions.

For a SELECT that fetches a vertex linked to another through an edge and using a fetch plan, I get the following.

1.7.10 and 2.0.2 return:
```javascript
[ { '@type': 'd',
    rid: { cluster: 11, position: 0 },
    name: 'Luca',
    out_Eat: 
     { '@type': 'd',
       '@class': 'Eat',
       someProperty: 'something',
       out: [Object],
       in: [Object],
       '@rid': [Object] },
    '@rid': { cluster: -2, position: 1 } } ]
```

2.1 returns:
```javascript
[ { '@type': 'd',
    rid: 
     { '@type': 'd',
       '@class': 'Person',
       name: 'Luca',
       out_Eat: [Object],
       '@rid': [Object] },
    name: 'Luca',
    out_Eat: [ [Object] ],
    '@rid': { cluster: -2, position: 0 } } ]
```

The test in [17e368](https://github.com/dmarcelino/oriento/commit/17e368251c21897d51cd3ca7c84478fbed4ef0ca) passes on 1.7.10 and 2.0.2 but fails on 2.1.

**Comment by phpnode** [comment] 2015-02-18 17:47
@dmarcelino could be an Oriento bug, suspect that `rid` is being replaced with its target because it's not called `@rid`

**Comment by dmarcelino** [comment] 2015-02-18 17:50
@phpnode, does Oriento run different code between OrientDB v2.0.2 and v2.1? I assumed the protocol didn't change... I've tested with both Oriento master and latest npm versions.

**Comment by phpnode** [comment] 2015-02-18 18:14
@dmarcelino no it's the same code for both, probably something *has* changed but use the result of `db.exec(yourQuery)` instead of `db.query(...)` to check as it doesn't do any transformations.

**Comment by dmarcelino** [comment] 2015-02-18 18:38
Indeed OrientDB is returning something different. After trying `.exec()`:

2.1
``` javascript
{ status: { code: 0, sessionId: 43 },
  results: 
   [ { type: 'p',
       content: 
        { classId: 0,
          type: 'd',
          cluster: 13,
          position: 0,
          version: 1,
          value: 
           { '@type': 'd',
             '@class': 'Eat',
             someProperty: 'something',
             out: [Object],
             in: [Object] } } },
     { type: 'p',
       content: 
        { classId: 0,
          type: 'd',
          cluster: 12,
          position: 0,
          version: 2,
          value: 
           { '@type': 'd',
             '@class': 'Restaurant',
             name: 'Dante',
             type: 'Pizza',
             in_Eat: [Object] } } },
     { type: 'r',
       content: 
        { classId: 0,
          type: 'd',
          cluster: -2,
          position: 1,
          version: 0,
          value: { '@type': 'd', rid: [Object], name: 'Luca', out_Eat: [Object] } } },
     payloadStatus: 0 ] }
```

vs.

```javscript
{ status: { code: 0, sessionId: 2 },
  results: 
   [ { type: 'p',
       content: 
        { classId: 0,
          type: 'd',
          cluster: 13,
          position: 0,
          version: 3,
          value: 
           { '@type': 'd',
             '@class': 'Eat',
             someProperty: 'something',
             out: [Object],
             in: [Object] } } },
     { type: 'p',
       content: 
        { classId: 0,
          type: 'd',
          cluster: 11,
          position: 0,
          version: 2,
          value: 
           { '@type': 'd',
             '@class': 'Person',
             name: 'Luca',
             out_Eat: [Object] } } },
     { type: 'p',
       content: 
        { classId: 0,
          type: 'd',
          cluster: 12,
          position: 0,
          version: 2,
          value: 
           { '@type': 'd',
             '@class': 'Restaurant',
             name: 'Dante',
             type: 'Pizza',
             in_Eat: [Object] } } },
     { type: 'r',
       content: 
        { classId: 0,
          type: 'd',
          cluster: -2,
          position: 0,
          version: 0,
          value: { '@type': 'd', rid: [Object], name: 'Luca', out_Eat: [Object] } } },
     payloadStatus: 0 ] }
```

Notice that there is one less `type: 'p'` record, namely the one with ` name: 'Luca'`.

**Comment by dmarcelino** [comment] 2015-02-24 11:35
@phpnode, regarding that extra 'p' record, is that something Oriento should handle or is OrientDB sending extraneous data given the same data already exists the 'r' record?

```javascript
     { type: 'p',
       content: 
        { classId: 0,
          type: 'd',
          cluster: 11,
          position: 0,
          version: 2,
          value: 
           { '@type': 'd',
             '@class': 'Person',
             name: 'Luca',
             out_Eat: [Object] } } },
```

**Comment by phpnode** [comment] 2015-02-24 11:49
@dmarcelino I think it's an OrientDB bug, it shouldn't prefetch a record that exists in the main result set.

**Comment by dmarcelino** [comment] 2015-02-24 11:50
Makes sense, thanks.

**Comment by lvca** [comment] 2015-02-25 16:51
What does mean `[Object]` ?

**Comment by dmarcelino** [comment] 2015-02-25 16:54
Hi @lvca, by default node's util.inspect() only expands objects until a certain depth to avoid putting out too much output. `[Object]` means the referenced object is beyond that depth and because of that it's not expanded.

**Comment by dmarcelino** [comment] 2015-03-10 16:53
@lvca, this looks like a regression, can we add it to the 2.1 milestone please?

**Comment by dmarcelino** [comment] 2015-03-19 14:56
@lvca, sorry for insisting, but given v2.1 is not out yet and given this is a regression introduced in v2.1 I believe it's best to fix this issue before the release. This has the potential to impact anyone running fetch plans with `oriento` and by extension it will break class associations in [waterline-orientdb](https://github.com/appscot/waterline-orientdb).

@phpnode, what are your thoughts on this?

**Comment by lvca** [comment] 2015-04-16 17:33
@tglman oriento is based on this and 2.1 breaks compatibility with oriento. Could you please take a look at this soon?

**Comment by dmarcelino** [comment] 2015-04-16 17:34
Thanks @lvca, @tglman.

**Comment by tglman** [comment] 2015-04-20 11:02
Hi @dmarcelino,

We have done some fix in the fetch plan for 2.1 that may changes some behaviour,for the specific case is possible that the record with name 'Luca' will be returned as type='p' because some other record refer to it, and the fact that is there a result(the type 'r' ) that came from the same record it's not wrong because is just a projection of that record, and not the whole record.

by the way can you post here the fetch plan that is causing this, we have done a lot of fix since 2.0.

**Comment by dmarcelino** [comment] 2015-04-20 11:07
Hi @tglman, my full test is in https://github.com/dmarcelino/oriento/commit/17e368251c21897d51cd3ca7c84478fbed4ef0ca, and the query/fetch plan is:
```javascript
this.db.query('SELECT @rid, name, out_Eat from Person WHERE name = "Luca"', { fetchPlan: 'out_Eat:1 out_Eat.in:1' }).all()
```

So it sounds like OrientDB is slightly changing its API for 2.1 in what concerns returned records.

**Comment by dmarcelino** [comment] 2015-04-20 12:08
@tglman, if I understand correctly there is no relevant difference between the "Luca" `type: 'r'` and `type: 'p'` records. So this means that for a fetch plan like this OrientDB is effectively sending duplicate data. If this is just one operation done occasionally that doesn't sound too bad but if we are talking of thousands of fetch plans on a busy server we are potentially  talking of a lot of redundant data sending across the wire consuming extra bandwidth. Maybe I'm misunderstanding something but this does sound like an ideal solution.

**Comment by tglman** [comment] 2015-04-20 16:12
i just written the same test case in java and it's seems correct it just send one the result plus the 'Eat' and 'Resturant' record, i'm going to try to run your node.js test and i'll let you know

**Comment by tglman** [comment] 2015-04-20 17:19
hi, 

I checked out the https://github.com/dmarcelino/oriento on the branch 3619-rid_object and i tried to run the `npm test`, but it look like the test for reproduce the problem is not running, i'm not the most expert of nodejs, am i doing something wrong ?

**Comment by dmarcelino** [comment] 2015-04-20 17:29
That's weird... I can see it when I run `npm test`. Funny enough now it seems to pass:
```
  Bug #3619: returning rid as object
    Query a graph with fetchplan
      ✓ should return valid @rid with @this.toJSON(fetchPlan) 
people: [ { '@type': 'd',
    rid: { cluster: 11, position: 0 },
    name: 'Luca',
    out_Eat: [ [Object] ],
    '@rid': { cluster: -2, position: 0 } } ]
      ✓ should "rid" with proper RecordID when running query 
      ✓ should "rid" with proper RecordID 
```
I wonder if some other change (OrientDB or Oriento) fixed this.

**Comment by tglman** [comment] 2015-04-20 17:43
ok, closing it.
reopen it if the issue return

**Comment by dmarcelino** [comment] 2015-04-20 17:48
Thanks @tglman, I'll need to check what else happened with 2.1 because sails-orientdb tests still break. Anyway I hope you still add the java test you've created to test suite as that will be a good way to prevent regressions.

**Comment by lvca** [comment] 2015-04-20 21:22
I guess @tglman forgot to close it... Closing it.

**Closed by lvca** 2015-04-20 21:22 UTC
