### ISSUE TITLE
Question on Traversal sql. What are inE(), outV()

### ISSUE THREAD

**Issue by bytebrahma** [orientechnologies/orientdb#5818] opened 2016-03-10 17:33 UTC
Hi ,

Suppose my data model is as below.
* {Menus} *contain* {pages} *contains* {records} *contains* {fields}
* Menus, pages, records and fields are vertices
* each contains between each of above is a separate edge class with different attributes. (eg. menu_pages, Page_records etc..)

If I input a field(eg. EMPLID), I need all possible paths running all the way(only one direction) through the records, fields till menus. 

When I try the below sql, it seems not giving all paths. 
1. What is the significance of  ```inE(), outV()``` ? 
2. How many such functions are there for Traverse command? I could not find these in the docs.
3. What is the correct sql to achieve my requirement?
```
select * from(traverse outV(), inE() from (select * from fields where fieldname='EMPLID')   strategy DEPTH_FIRST)```

**Comment by luigidellaquila** [comment] 2016-03-11 09:21
Hi @bytebrahma 

if your graph is a tree, then this approach will work fine, but if a single field belongs to multiple pages/menus, then it won't.
The problem is that the TRAVERSE avoids to re-traverse already traversed nodes, so if you have

```
           -> record1 ->
        /                \ ->
field                      -> page 1 -> menu 1
        \                /
           -> record2 ->
```

Then page1 will be listed only once (not twice - once per path).

If you want all the full paths, given that you know the depth of the graph, I suggest you to use a SELECT instead:

```
select field, record, page, out("page_menu") as menu  from (
  select field, record, record.out("record_page") as page from (
     select @rid as field, out("field_record") as record from fields where fieldname='EMPLID unwind record
  ) unwind page
) unwind menu
```

This will give you one complete path per row

I hope it helps

Thanks

Luigi

**Comment by luigidellaquila** [comment] 2016-03-14 12:01
Hi @bytebrahma 

Did it solve your problem?
Can I close this issue?

Thanks

Luigi

**Comment by luigidellaquila** [comment] 2016-03-15 09:19
Hi @bytebrahma 

I'm closing this issue, if you sill need help on this please reopen or continue the discussion on StackOverflow (use "orientdb" tag)

Thanks

Luigi

**Closed by luigidellaquila** 2016-03-15 09:19 UTC
Labels: question
