### ISSUE TITLE
Password saved as plain text

### ISSUE THREAD

**Issue by voondo** [orientechnologies/orientdb#6816] opened 2016-10-17 05:47 UTC
## OrientDB Version, operating system, or hardware.
- v2.2.12-SNAPSHOT
## Operating System
- Linux
## Expected behavior and actual behavior

Passwords are expected to be saved as encrypted form (`{PBKDF2WithHmacSHA256}....`) but some of them are stored as plain text (i.e only the first three).
## Steps to reproduce the problem

```
graph.getMetadata().getSecurity().createUser('myUser', 'myPassword', 'myRoleA', 'myRoleB')
graph.commit()
```

(also hitting `Local node 'node-03' is not the owner for cluster 'ouser' (it is 'node-02')
↵ DB name="devaprint-production"` when committing this operation not on `node-02`)

**Comment by luigidellaquila** [comment] 2016-10-17 07:58
Hi @voondo 

does it happen on a single node or on a distributed deployment?

Thanks

Luigi

**Comment by voondo** [comment] 2016-10-17 08:01
@luigidellaquila on a distributed deployment (3 nodes)

**Comment by luigidellaquila** [comment] 2016-10-17 08:30
Ok, it must be a problem with the hooks, I'm forwarding this to the distributed team

Thanks

Luigi

**Comment by dominioon** [comment] 2016-11-09 16:14
@luigidellaquila, when creating a user via Studio or via Java API the node where the command ran will get the password as plain text. To other nodes it is synced in encrypted format. So it is more likely an problem of incorrect inserting.

**Comment by lvca** [comment] 2017-02-18 07:57
@dominioon can you reproduce this problem against 2.2.17?

**Comment by santo-it** [comment] 2017-04-07 22:17
Hi,

Many thanks for submitting this issue

@lvca, I reproduced this with 2.2.18. Just create an user with Studio. Then select * from OUser from the same node where you created the user

Thanks,

**Comment by lvca** [comment] 2017-06-06 03:38
Closing this issue because of no response after a long time.

**Comment by tglman** [comment] 2024-01-08 12:14
Hi,

This should be fixed long ago in all supported version, closing

**Closed by tglman** 2024-01-08 12:14 UTC
Labels: bug
