### ISSUE TITLE
dijkstra hangs out

### ISSUE THREAD

**Issue by iw2rmb** [orientechnologies/orientdb#4946] opened 2015-09-09 16:43 UTC
select dijkstra(#from, #to, 'weight', 'BOTH')
hangs out even if there is edge between #from and #to with weight = 1.0
v2.1.1
shortestpath runs correctly and fast on same rids

**Comment by iw2rmb** [comment] 2015-09-10 09:13
Any clue how can I speed it up? 484 secs is the fastest result I have right now for two vertexes connected directly.

**Comment by lvca** [comment] 2015-09-10 13:41
dijkstra() was based on shortestPath() function, but we improved this last one and dijkstra remained old and slow. @luigidellaquila Could you adapt dijkstra with the enhancements we did in shortestPath()

**Comment by mbhulin** [comment] 2015-09-16 09:21
@luigidellaquila The main reason for the very long runtime of the dijkstra function even if you call it for directly connected vertices is that the funktion does not terminate if the destination vertex is settled. It runs through the whole graph. If you include a new termination condition
```Java
while (continueTraversing()) {
      final OrientVertex node = getMinimum(unSettledNodes);
      if (node.getIdentity().equals(paramDestinationVertex.getIdentity())) break; // new termination condition
```
the runtime is reduced dramatically for vertices near by.

I have developed a new version of the dijkstra function using a priority queue. For a graph with 10^6 vertices forming a quadratic grid the existing algorithm but with the additional termination condition needs about 1500 s on my computer to find a path from one corner to the opposite corner. The new version with priority queue runs 1000 s. (The existing algorithm without the additional termination condition needs about 1600 s regardless of the destination vertex). Are you interested in my new version or do you have already developed an own new version?

**Comment by luigidellaquila** [comment] 2015-09-16 09:37
Hi @mbhulin 

yes, of course I am!

Thanks

Luigi

**Comment by luigidellaquila** [comment] 2016-05-24 10:21
Hi @iw2rmb 

We just replaced Dijkstra function with a more optimized implementation (develop branch, next v 2.2.1). Could you please let me know if the problem is fixed?

Thanks

Luigi

**Comment by luigidellaquila** [comment] 2016-06-09 15:41
Hi @iw2rmb 

I'm closing this issue, please reopen if you see any related problems

Thanks

Luigi

**Closed by luigidellaquila** 2016-06-09 15:41 UTC
Labels: performance, waiting reply
