### ISSUE TITLE
Inside [] support full SQL functions and operators [moved]

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#513] opened 2012-12-10 15:20 UTC
This is [Issue 513](http://code.google.com/p/orient/issues/detail?id=513) moved from a Google Code project.
Added by 2011-08-19T11:45:28.000Z by [l.garu...@gmail.com](http://code.google.com/u/111607061083712272202/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Low, v2.1

### Original description

    Extend the &quot;field part&quot; of square brackets supporting full SQL functions and operators.
    
    Now the supported syntax is: http://code.google.com/p/orient/w/edit/Document_Field_Part

**Comment by pembeci** [comment] 2015-04-16 12:10
Eagerly waiting for this feature. Thanks. Any plans on when 2.1-rc1 will be available?

**Comment by lvca** [comment] 2015-04-16 15:14
2.1-rc1 was supposed to be released today, but we had a small regression with Lucene, so it will be released in the next 24h. This feature has been moved to 2.1-rc2. @luigidellaquila can you confirm it?

**Comment by pembeci** [comment] 2015-04-16 17:17
OK, thanks. Waiting for 2.1-rc2 will not be so bad since we know that it is close enough.

**Comment by luigidellaquila** [comment] 2015-04-20 21:23
I'm afraid it's not trivial with current query executor, but I'll see what I can do

**Comment by pembeci** [comment] 2015-04-20 22:41
Thanks for the update. I know your hands are full with a lot of stuff. So this is just nice to have to write shorter and easier to grasp queries but as long as there other ways to achieve the same, I don't think it is a priority.

**Comment by eugene-kamenev** [comment] 2015-05-19 10:39
@lvca @luigidellaquila any news on this issue?

**Comment by luigidellaquila** [comment] 2016-02-16 09:54
Fixed in 2.1.x and develop branches. The fix will be released with 2.1.12

Closing, please reopen if you see any unexpected behaviors

Thanks

Luigi

**Closed by luigidellaquila** 2016-02-16 09:54 UTC
Labels: approved feature, enhancement

**Comment by karolmie1** [comment] 2017-06-12 06:06
Documentation should be updated I guess: 
https://orientdb.com/docs/last/Document-Field-Part.html

**Comment by luigidellaquila** [comment] 2017-06-12 08:22
Hi @karolmie1 

Updated, thanks! The docs will be re-generated in short.

Luigi
