### ISSUE TITLE
Cannot rebuild a lucene index in 3.2.0

### ISSUE THREAD

**Issue by aberdev** [orientechnologies/orientdb#9721] opened 2021-11-22 12:42 UTC
## Expected behavior  
Lucene Indexes can be rebuilt normally

## Actual behavior  
Error triggers when trying to redbuild an index 

## Steps to reproduce  
1-Create a new Class
2-Add some properties
3-Create a lucene index on one of the properties
4-Try de rebuild the created index
The attached capture shows the error's informations
![error building index lucene](https://user-images.githubusercontent.com/72909882/142863473-b62621cf-6393-4c07-b6a1-1ebe461ab944.png)

The above scenario runs without problem in 3.0.27
Thanks for any help or explanation

**Comment by aberdev** [comment] 2021-11-23 14:47
@laa can you confirm that is a regression comparing to 3.0.x version ?
Thanks

**Comment by andrii0lomakin** [comment] 2021-11-24 08:11
@aberdev yes , sure that is regression which we will fix.

**Comment by johny65** [comment] 2021-11-29 12:49
This is related to #9498 (see comment https://github.com/orientechnologies/orientdb/issues/9498#issuecomment-898586327). The problem is that the database gets unusable until the server is restarted, no new connections are possible. Every exception thrown by Lucene turns the database into that broken state.

**Comment by aberdev** [comment] 2021-11-29 15:22
Yes ,the issue is caused by the same behavior.
Is that mean we can't rebuilt lucene indexes  ? But, we can only drop&create them ?

**Comment by timw** [comment] 2022-04-11 07:14
It looks like the fixes applied in 72e7d639a5f96be237dc49c43c815ef7c9255400 to stop the DB going into an internal error status on read errors would fix this in 3.2.x/develop as well.

The root cause is actually that a rebuild index on a Lucene index has always (at least in 3.1/3.2) thrown an UnsupportedOperationException when it is rebuilt.
The delete/doDelete method in OIndexAbstract isn't designed for extension, so when an index is rebuilt it executes the private `OIndexAbstract.doDelete`, which attempts to iterate all index items and remove them before removing the index engine.
If `OLuceneIndexNotUnique` provided an override of `doDelete` that does what it's `delete` does now (which is simply to remove the engine from the storage), it would probably eliminate the actual error.

**Comment by tglman** [comment] 2022-06-09 11:16
Hi,

Rolling 3.2.7 with the relative fix, closing this.

**Closed as completed by tglman** 2022-06-09 11:16 UTC
Labels: bug
