### ISSUE TITLE
Very slow performance when querying from java

### ISSUE THREAD

**Issue by adepase** [orientechnologies/orientdb#7744] opened 2017-09-15 09:17 UTC
## Expected behavior  
Faster response (at least, almost as fast as from the Web tool (Studio)

## Actual behavior  
When I run from Java a query it is too slow in getting the result. The same query run from Studio performs as fast I expected. The slow down seems to get bigger when the returned number of records grows (not measured, however: the issue exists anyway). Both queries (from Studio web tool and from Java) were executed from the same development PC (client and server) on the same LAN against the same DB (remote, on localhost). I repeated the sequence tens of times, always with similar results.
Performance parameters of the PC during execution shows it was not under pressure:
RAM (8G total): stable for all the run, free 18%
CPU: ranging from 17% to 24% 
**Query**: SELECT expand(shortestPath(start, (select from synset where id_lemma='n#00008019' and lang='it'), 'OUT', 'hypernym'))  from (SELECT @rid as start from synset where lemmas LUCENE 'gatto' and lang='it' and verified is null)
**Studio**: Query executed in 0.284 sec. Returned 17 record(s).
**Java log**:
2017-09-15 10:44:20.802 **Starting query**: SELECT expand(shortestPath(start, (select from synset where codLemma=:parentId and lang=:lang), 'OUT', 'hypernym')) from (SELECT @rid as start from synset where lemmas LUCENE :lemma and lang=:lang)
2017-09-15 10:44:20.802 **Getting OrientGraph**: SELECT expand(shortestPath(start, (select from synset where codLemma=:parentId and lang=:lang), 'OUT', 'hypernym')) from (SELECT @rid as start from synset where lemmas LUCENE :lemma and lang=:lang)
2017-09-15 10:44:20.802 **Before OSQLSynchQuery:** SELECT expand(shortestPath(start, (select from synset where codLemma=:parentId and lang=:lang), 'OUT', 'hypernym')) from (SELECT @rid as start from synset where lemmas LUCENE :lemma and lang=:lang)
2017-09-15 10:44:20.803 **Before command:** SELECT expand(shortestPath(start, (select from synset where codLemma=:parentId and lang=:lang), 'OUT', 'hypernym')) from (SELECT @rid as start from synset where lemmas LUCENE :lemma and lang=:lang)
2017-09-15 10:44:20.803 **Before execute query:** SELECT expand(shortestPath(start, (select from synset where codLemma=:parentId and lang=:lang), 'OUT', 'hypernym')) from (SELECT @rid as start from synset where lemmas LUCENE :lemma and lang=:lang)
2017-09-15 10:44:47.219 **After execute query**: SELECT expand(shortestPath(start, (select from synset where codLemma=:parentId and lang=:lang), 'OUT', 'hypernym')) from (SELECT @rid as start from synset where lemmas LUCENE :lemma and lang=:lang)
2017-09-15 10:44:47.220 **Detatching results**
2017-09-15 10:44:47.223 **Detatching results**
2017-09-15 10:44:47.223 **Ending query:** SELECT expand(shortestPath(start, (select from synset where codLemma=:parentId and lang=:lang), 'OUT', 'hypernym')) from (SELECT @rid as start from synset where lemmas LUCENE :lemma and lang=:lang)
2017-09-15 10:44:47.224 **returning from query:** [...]

This is a tipical log from the second run on (the first run is slower, as expected).
So, there are 2 points very very slow:
1.  Getting OrientGraph: takes from 0.3 seconds to 0.7 seconds 
2.  Executing the command: takes from 19 seconds (27 seconds in this run) to 60 seconds
Each point consist in a single method call.

So, while Studio runs under 0.3 seconds, Java runs over 20 seconds (to over 60 seconds).
Needless to say, it is too much difference

## Steps to reproduce  
Above mentioned query (I don't think the query itself or the db structure and records number should impact, because the issue is that with the same query the answer is very different).
Java code generating that log:

```
OrientGraphFactory orientFactory= new OrientGraphFactory(orientUrl,orientUsername, orientPassword).setupPool(orientMinPool,orientMaxPool); //min=1, max=10, url=remote:localhost/myDB
logger.debug("Starting query: "+queryString);
ArrayList<OrientVertex> result = new ArrayList<OrientVertex>();
logger.debug("Getting OrientGraph: "+queryString);
OrientGraph graph = orientFactory.getTx();
try{
	logger.debug("Before OSQLSynchQuery: "+queryString);
	OSQLSynchQuery<OrientVertex> query = new OSQLSynchQuery<OrientVertex>(queryString);
	logger.debug("Before command: "+queryString);
	OCommandRequest command= graph.command(query);
	logger.debug("Before execute query: "+queryString);
	Iterable<OrientVertex>resultIterable = command.execute(params); //params is an hashMap with the following values: {lemma=gatto, lang=it, parentId=n#00008019}
	logger.debug("After execute query: "+queryString);

	if (resultIterable!=null) {
		logger.debug("Detatching results");

		for(OrientVertex v: resultIterable){
			v.detach();
			result.add(v);
		}
		logger.debug("End Detatching results");
	}
	logger.debug("Ending query: "+queryString);
} catch (OCommandExecutionException e) {
	logger.debug("*** Executing OrientDB query: "+queryString+" resulted in the following Exception:"+e.getMessage());
} finally {
	graph.shutdown();
}
logger.debug("returning from query: "+queryString);
```

Can you help me, please?
Thank you in advance
Alessandro Depase

**Comment by luigidellaquila** [comment] 2017-09-15 09:43
Hi Alessandro,

As a quick check, you should verify if Studio and Java are returning the same number of records. Studio by default has a LIMIT 20, so this can be the reason for the difference of performance.

This said, if you could share a dataset to reproduce the problem, it would help me a lot to understand the root cause

Thanks

Luigi

**Comment by adepase** [comment] 2017-09-15 10:26
Same number of records (17).
It will not so easy to produce a subset of data, (I cannot send you the
whole database).
I will try and see if I find a way. I think it will be difficult before
next Monday,  however, let's try.
Thank you for your very fast feedback, in the meanwhile
Kind regards
Alessandro

Il 15 Set 2017 11:43 AM, "luigidellaquila" <notifications@github.com> ha
scritto:

**Comment by adepase** [comment] 2017-09-15 11:33
Just to add an information, I'm using spring boot, configured with
spring-boot-orientdb-autoconfigure version 0.14 (
https://mvnrepository.com/artifact/com.orientechnologies/spring-boot-orientdb-autoconfigure
seems to be pretty recent) and, obviously, the first line of the code I
posted is, in my implementation, a spring singleton bean.
Apart for the possibility to send you a dataset, don't you think that the
1st point, which is dataset independent, is too slow anyway? According to
the documentation I found it has to be repeated every time, and for a
single query it becomes a lot of time...
Thank you again
Kind regards
Alessandro


Il 15 Set 2017 12:26 PM, "Alessandro Depase" <alessandro.depase@gmail.com>
ha scritto:

Same number of records (17).
It will not so easy to produce a subset of data, (I cannot send you the
whole database).
I will try and see if I find a way. I think it will be difficult before
next Monday,  however, let's try.
Thank you for your very fast feedback, in the meanwhile
Kind regards
Alessandro

Il 15 Set 2017 11:43 AM, "luigidellaquila" <notifications@github.com> ha
scritto:

**Comment by adepase** [comment] 2017-09-17 21:59
Dear Luigi and all,
I found it. The difference was due to the fact I didn't exactly performed
the same query. But this has to be explained better.
I had a field, named id_lemma (as in the first query in the issue text), on
which I defined an index. For several reasons I renamed it in codLemma (as
in the log i reported in the issue text). No warning, no 'unsafe' (as it
happens, for example, when you rename an edge).
Then I continued to run the query from Studio, using id_lemma and from Java
using codLemma.
But it resulted not to be a "real" rename: the rename resulted in a
different field. The index remains on the first field, the second field has
no index.
Maybe the issue has to be changed from "Very slow performance..." to
"Rename is not a rename..."

However now I know what to do.

Thank you
Best regards
Alessandro


2017-09-15 13:32 GMT+02:00 Alessandro Depase <alessandro.depase@gmail.com>:

**Comment by adepase** [comment] 2017-09-17 22:00
I found it. The difference was due to the fact I didn't exactly performed the same query. But this has to be explained better.
I had a field, named id_lemma (as in the first query in the issue text), on which I defined an index. For several reasons I renamed it in codLemma (as in the log i reported in the issue text). No warning, no 'unsafe' (as it happens, for example, when you rename an edge).
Then I continued to run the query from Studio, using id_lemma and from Java using codLemma.
But it resulted not to be a "real" rename: the rename resulted in a different field. The index remains on the first field, the second field has no index.
Maybe the issue has to be changed from "Very slow performance..." to "Rename is not a rename..." (or closed and reopened, your choice)

However now I know what to do.
Thank you
Alessandro Depase

**Comment by adepase** [comment] 2017-09-17 22:03
ooops, no: there is the first point, which remains very slow.
To summarize: from 0.3 seconds to 0.7 seconds to perform orientFactory.getTx();
So, we have 2 issues now: this slow execution and the "Rename is not a rename"
Alessandro

**Comment by adepase** [comment] 2017-09-17 22:05
There is an update on the comments for this issue, because it remains slow
on the first point.
More on the comments.
Thank you
Alessandro


2017-09-17 23:59 GMT+02:00 Alessandro Depase <alessandro.depase@gmail.com>:

**Comment by adepase** [comment] 2017-09-17 22:24
I have to apologize: today the first point seems to be not repeatable (it takes about 1ms). I really don't know why I measured that time, reported also in the log I inserted in the issue.
No matter why, it seems it is no more an issue.
So it remains just the rename behaviour.

**Comment by luigidellaquila** [comment] 2017-09-18 06:28
Hi @adepase 

Thank you for the update. To keep things as clean as possible, could you please open a separate issue for the rename problem?

In the meantime I'm closing this issue and marking as not reproducible. If you still see a performance problem here, please feel free to comment on the issue and I'll reopen it

Thanks

Luigi

**Closed by luigidellaquila** 2017-09-18 06:28 UTC
