### ISSUE TITLE
Using reserved words in let statement variables

### ISSUE THREAD

**Issue by shekhei** [orientechnologies/orientdb#3937] opened 2015-04-16 10:56 UTC
With the previous version, we used to have some statement that says
```
begin
let user = select from User where ...
create vertex someedge from $user to #12:0 // for example
commit
```
After upgrading to 2.0.7, we realised that we end up having OUser linked instead of User, apparently $user seems to become a reserved word, but, no error or warning has been thrown when we use let user.

I recommend that, either, reserved words can be "overridden" in scope, or, an error should be raised?

**Comment by luigidellaquila** [comment] 2015-05-22 15:34
Hi @shekhei 

$user is a reserved word, but it can be overridden.
There was an issue in 2.0.9 about batch scripts, related to the fact that the context was not passed correctly between let statements; this could be the cause for this. I fixed it a few days ago, could you please try again on latest snapshot and let me know if it's fixed?

Thanks

**Comment by shekhei** [comment] 2015-06-03 10:27
@luigidellaquila how do i try it on the latest snapshot? does it require any building?

**Comment by luigidellaquila** [comment] 2015-06-04 06:05
Hi @shekhei 

you can find snapshot releases here:
https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-community/

As an alternative, you can ```git clone``` the main repository and then launch ```ant clean install``` this way you will have a fresh build with last changes

Luigi

**Comment by luigidellaquila** [comment] 2015-06-04 06:06
let me know if it's fixed for you so that I can close it

**Comment by shekhei** [comment] 2015-06-04 09:07
Just tested it, working fine

**Comment by luigidellaquila** [comment] 2015-06-05 09:50
Thanks for you feedback!

Closing

**Closed by luigidellaquila** 2015-06-05 09:50 UTC
Labels: waiting reply
