### ISSUE TITLE
Cluster already belongs to class on re-named class

### ISSUE THREAD

**Issue by SpareShade** [orientechnologies/orientdb#3434] opened 2015-01-21 23:45 UTC
This could be a minor bug:
- created a class ie. EmailAddress
- renamed it to EmailAddressOld
- when trying to to (re)create class EmailAddress it throws the bellow error
```com.orientechnologies.orient.core.exception.OSchemaException: Cluster with id 15 already belongs to class EmailAddressOld```

**Comment by ganeshp0001** [comment] 2015-01-31 11:19
I am facing similar issue.
<ul>
<li>I have Record class registered with multiple clusters(approx 200+). </li>
<li>Later when I tried creating new class in OrientDb got following exception:</li>
</ul>

<code>
Exception in thread "Thread-0" com.orientechnologies.orient.core.exception.OSchemaException: Cluster with id 18 already belongs to class Record
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.checkClustersAreAbsent(OSchemaShared.java:1160)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.doCreateClass(OSchemaShared.java:907)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.createClass(OSchemaShared.java:362)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaProxy.createClass(OSchemaProxy.java:111)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLCreateClass.execute(OCommandExecutorSQLCreateClass.java:144)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:64)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1173)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1162)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1180)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:385)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:216)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)
</code>

**Comment by lvca** [comment] 2015-01-31 18:12
OrientDB Version?

**Comment by ganeshp0001** [comment] 2015-02-01 18:54
OriendDB version:
VERSION 2.0-RC2

P.S. : I have fixed issue. I had a code in my app which used to check empty clusters (Clusters with 0 records) & used to drop those clusters using "odb.dropCluster(clusterName, true);" . May be this method just deletes the cluster but does not de-registers cluster id from associated class. 
Now I modified that removes clusterId from associated claass using OClass instance of that class & then drops cluster. 
Code snippet : 
<code><pre>
        OClass oClass = odb.getMetadata().getSchema().getClass("Record");
.....
.....
		for(String clusterName: clusters){
			if(clusterName.length() > 4 && (clusterName.contains("cls_")){
					if(odb.countClusterElements(clusterName) == 0){
						System.out.println("REMOVING: " + clusterName);
						oClass.removeClusterId(odb.getClusterIdByName(clusterName));
						odb.dropCluster(clusterName, true);
					}
			}
		}
</pre>
</code>

**Comment by tglman** [comment] 2015-02-13 16:49
Hi @SpareShade, @ganeshp0001,

I did a simple test to reproduce this, with no success, does this issue happen only if you have multiple cluster associated to the same class?

**Comment by tglman** [comment] 2015-04-03 11:09
i finally found the reason and fixed, closing.

**Closed** 2015-04-06 08:37 UTC
Labels: bug
