### ISSUE TITLE
Orient storage doesn't support Windows UNC paths

### ISSUE THREAD

**Issue by jdillon** [orientechnologies/orientdb#3911] opened 2015-04-10 18:28 UTC
Looks like orientdb is unable to use a windows UNC path as a location for databases.

Java supports this with either new File("//SERVER/share/path") or new File ("\\\\SERVER\\share\\path"), but so far all of our attempts to get orient to use this will result in it using "c:\SERVER\share\path".

Related: https://issues.sonatype.org/browse/NEXUS-8389

It appears that the uri/path "normalization" is actually mangling valid paths.  I'd expect that unix-style "//SERVER/share/path" should work to access UNC path.

**Comment by rseddon** [comment] 2015-04-10 19:25
This problem is of particular concern to us because we embed orientdb in nexus, and many of our customers run nexus as a service on windows.  And unfortunately, using UNC paths to access network drives is the Microsoft recommendation for services:

https://msdn.microsoft.com/en-us/library/windows/desktop/ms685143%28v=vs.85%29.aspx

"A service should not directly access local or network resources through mapped drive letters, nor should it call the net use command to map drive letters at run time. The net use command is not recommended..."

Newer versions of windows do have symbolic links support mklink, so you can hack around this by creating a link to the shared drive.  But most of our customers are currently using the UNC paths, so this is going to have an impact on us as we expand our use of orientdb in Nexus.

Also, I'm concerned there is a larger problem here.  If you're using the standard Java API's for path manipulation support of UNC paths should be seamless. So there may be other path related bugs lurking here.

**Comment by lvca** [comment] 2015-04-22 15:23
@SDIPro fixed this problem and he's committing in few minutes. We're releasing 2.0.8 today with this fix too.

**Comment by SDIPro** [comment] 2015-04-22 16:25
Removed a replace "//" with "/" in Orient.java.

**Comment by jdillon** [comment] 2015-04-22 17:43
cool beans

**Comment by tglman** [comment] 2015-04-30 10:05
unluckily i had to revert the fix because was creating some problem with a test cases, it happen that in other places we build path with double slash in the middle like "server/databases//test" we should fix this before reintroduce this fix

**Comment by peterlynch** [comment] 2015-05-01 18:40
@tglman Please elaborate - we are depending on 2.0.8 which is already released. Does this mean that 2.0.8 still has a problem?

**Comment by lvca** [comment] 2015-05-02 06:31
@peterlynch if you use paths like `\\D\a\b` is ok. The problem @tglman is reporting is when you have backslash in the middle, like: `\\D\a\\b`.

**Comment by lvca** [comment] 2015-05-04 10:04
Fixing it again in 2.0.9 and 2.1-rc2.

**Comment by lvca** [comment] 2015-05-06 20:58
@SDIPro Why reopened?

**Comment by tglman** [comment] 2015-05-06 21:22
We tested latest fix on windows and it's not working, probably due to the fact that we replace "\" with "/" before reach the point the fix is applied, so we need to redesign the fix a bit.

**Comment by lvca** [comment] 2015-05-07 09:25
@tglman where did you find this sort of replace? I see this in the code:

```java
    if (iURL.endsWith("/"))
      iURL = iURL.substring(0, iURL.length() - 1);

    iURL = iURL.replace("//", "/");

    if (iURL.indexOf("\\\\") > 0)
      // REMOVE DOUBLE BACKSLASHES NOT AS PREFIX (WINDOWS PATH COULD NEED STARTING FOR "\\". EXAMPLE: "\\mydrive\db")
      iURL = iURL.charAt(0) + iURL.substring(1).replace("\\\\", "\\");

```

**Comment by peterlynch** [comment] 2015-05-12 19:08
@tglman @SDIPro can we have some reproduce case where the changes do not work?

**Comment by tglman** [comment] 2015-05-13 10:14
we tested the second fix on windows, and wasn't working, the reason i think is somewhere else not in that specific method, we manipulate path in different parts of the code so in the place the fix is introduced is too late for do that check, I'll do some investigation on all the flow and i'll try to get out a all cases fix.

**Closed** 2015-05-13 12:37 UTC
Labels: bug

**Comment by lvca** [comment] 2015-05-13 12:40
@SDIPro Please could you test it on Windows?

**Comment by SDIPro** [comment] 2015-05-13 16:16
Revised.  Tested on Windows.  Committed.
