### ISSUE TITLE
Problem with nested collections

### ISSUE THREAD

**Issue by dominik-kopczynski** [orientechnologies/orientdb#7548] opened 2017-07-14 07:52 UTC
### OS: ubuntu 16.04

Hi folks,

Thank you for providing this very lovely database. Currently, I am restructuring our program, that it utilizes orientDB but I stuck in a problem I cannot solve. Within my class (say MyClass1) I have a nested collection, for instance: HashMap<String, ArrayList<MyClass2>>
When storing in the database, I get the following error:
Exception in thread "main" java.lang.NullPointerException
	at com.orientechnologies.orient.core.record.ORecordInternal.track(ORecordInternal.java:127)
	at com.orientechnologies.orient.core.db.record.OTrackedList.addOwnerToEmbeddedDoc(OTrackedList.java:125)
	at com.orientechnologies.orient.core.db.record.OTrackedList.add(OTrackedList.java:67)
	at com.orientechnologies.orient.core.db.record.ORecordLazyList.add(ORecordLazyList.java:178)
	at com.orientechnologies.orient.core.db.record.ORecordLazyList.add(ORecordLazyList.java:48)
	at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.multiValueToStream(OObjectEntitySerializer.java:1378)
	at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.typeToStream(OObjectEntitySerializer.java:796)
	at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.multiValueToStream(OObjectEntitySerializer.java:1391)
	at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.typeToStream(OObjectEntitySerializer.java:799)
	at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.toStream(OObjectEntitySerializer.java:1211)
	at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.serializeObject(OObjectEntitySerializer.java:145)
	at com.orientechnologies.orient.object.db.OObjectDatabaseTx.save(OObjectDatabaseTx.java:453)
	at com.orientechnologies.orient.object.db.OObjectDatabaseTx.save(OObjectDatabaseTx.java:398)

I checked, both classes MyClass1 and MyClass2 have correct getters and setters for all attributes.  When I use one flat collection, everything works fine. Could you give me a suggestion how to solve this error? Do you need more information? Thank you very much.

Cheers,
Dominik

**Comment by tglman** [comment] 2017-07-17 11:56
hi @dominik-kopczynski,

Do you have a example test case for reproduce the issue ? Looking to the trace I think I found the reason of the problem, but I would like to have a test to prove the fix.

Regards.

**Comment by dominik-kopczynski** [comment] 2017-07-17 12:48
Hi,

Thank you for the massage. I attached two classes. Please register both 
classes, create an instance of CoolContainer and try to store it. Thank 
you very much.

Cheers,
Dominik

**Comment by tglman** [comment] 2017-07-17 13:00
Hi @dominik-kopczynski,

I think github removed the attachment in your email, could you put them on a gist ?

Thank you

**Comment by dominik-kopczynski** [comment] 2017-07-17 13:04
Here it is: 
https://gist.github.com/dominik-kopczynski/daf5b3acd5474db69c67485faff7fe00

Cheers

**Comment by tglman** [comment] 2017-07-17 14:02
hi @dominik-kopczynski,

Thanks for the case, I could reproduce the issue and verify the fix, pushed everything right now, I'll close this issue, the fix will be released with 2.2.24 and with 3.0.0.

Regards

**Closed by tglman** 2017-07-17 14:02 UTC
