### ISSUE TITLE
Running in distributed mode don't sync data across all nodes.

### ISSUE THREAD

**Issue by anber500** [orientechnologies/orientdb#6714] opened 2016-09-20 01:38 UTC
## OrientDB Version, operating system, or hardware.
- v2.2.9
- v2.2.10
- v2.2.11_SNAPSHOT
## Operating System
- [x] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

I have 3 nodes running in distributed mode, call them node1, node2 and node3. I mostly use node1 as a master read/write database with the rest as "read" servers. However all nodes can be written too but very little writing happens to the redundant "read" nodes. 

After a few days, I noticed that node1 was sitting with 2.8 million edges on the other two nodes only had 2.4 million edges. I checked the logs and found no obvious errors. 

I tried creating a new Class on node1 and tested if it was replicated to the other two nodes. The replication was successful. I then deleted the new Class on node2 and it was removed in node1. To me, this was a sign that replication was working but I could not figure out why  node2 and node3 were obviously missing information.

I tried restarting node1. When node1 came online, it started to sync with the other two nodes and then only had 2.4 million edges! I lost 400,000 edges and who knows what other data just like that!

It's gone and I can never get that data back :(

I started to monitor the 3 nodes. I can see that some data is replicated to node2 and node3 but even after a few hours, they are already 30,000 records behind node1.

I'm sure that there must be something wrong with my setup but there is one thing that is more important to us than anything, it's our customer's data.

The expected behaviour was that after restarting node1, that node2 and node3 would see that they don't have the latest version of the data and sync the data from node1. This obviously didn't work.

Even after the restart, I can see that some data is synced to node2 and node3 but not everything.
Just the fact that some data, but not all, are synced is a very worrying indeed.

Here is my hazelcast.xml

```
<?xml version="1.0" encoding="UTF-8"?>
<hazelcast xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.3.xsd"
       xmlns="http://www.hazelcast.com/schema/config"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <group>
            <name>orientdb</name>
            <password>orientdb</password>
    </group>
    <properties>
            <property name="hazelcast.local.localAddress">172.31.6.32</property>
            <property name="hazelcast.icmp.enabled">true</property>
            <property name="hazelcast.mancenter.enabled">false</property>
            <property name="hazelcast.memcache.enabled">false</property>
            <property name="hazelcast.rest.enabled">false</property>
            <property name="hazelcast.wait.seconds.before.join">5</property>
            <property name="hazelcast.operation.thread.count">1</property>
            <property name="hazelcast.operation.generic.thread.count">1</property>
            <property name="hazelcast.client.event.thread.count">1</property>
            <property name="hazelcast.event.thread.count">1</property>
    </properties>
    <network>
            <port auto-increment="true">2434</port>
            <join>
                    <multicast enabled="false">
                            <multicast-group>235.1.1.1</multicast-group>
                            <multicast-port>2434</multicast-port>
                    </multicast>
                    <tcp-ip enabled="true">
                            <member>172.31.6.32</member>
                            <member>172.31.4.191</member>
                            <member>172.31.4.192</member>
                    </tcp-ip>
                    <aws enabled="false">
                    </aws>
            </join>
            <interfaces enabled="false">
                    <interface>172.31.6.32</interface>
            </interfaces>
    </network>
    <executor-service>
            <pool-size>16</pool-size>
    </executor-service>
</hazelcast>
```

Here is my default-distributed-db-config.json:

```
{
  "autoDeploy": true,
  "readQuorum": 1,
  "writeQuorum": 1,
  "executionMode": "synchronous",
  "readYourWrites": true,
  "servers": {
    "*": "master"
  },
  "clusters": {
    "internal": {
    },
    "*": {
      "servers": ["<NEW_NODE>"]
    }
  }
}
```

I don't really know how to replicate this issue. I'm running this setup on AWS and this is the behaviour I'm experiencing. 

Ironically, getting OrientDB running with replication on the master nodes was very important in order to secure data integrity. Now it seems like running OrientDB with replication accomplish exactly the opposite of that.

**Comment by lvca** [comment] 2016-09-20 04:12
Why did you change `writeQuorum` to 1 even if you have 3 nodes? In this way, the database could be not consistent between nodes. Please restore the "majority" and you'll see everything will be replicated.

Look at the documentation about `writeQuorum`: http://orientdb.com/docs/2.2/Distributed-Configuration.html.

**Comment by anber500** [comment] 2016-09-20 05:28
OK, maybe I'm not clear about the severity of this issue. I can lose my job over this!

If I set it to "majority", I can't use the database at all. The other two nodes, node2 and node3 keeps arguing with node1. They simply can't reach quorum.

In your documentation, it states that :

> By default writeQuorum is "majority". This means that it waits and checks the answer from at least N/2+1 (where N is the number of available nodes) nodes before to send the ACK to the client. After the quorum is reached, the responses are managed asyncrhonously. For example, with 3 nodes and writeQuorum: "majority", then after the 2nd node's answer, the collecting and check of the 3rd node answer is managed asynchronously. **You could also set this to 1 to have all the writes asynchronous**.

I read it a few times and no where does it mention that by NOT using "majority", I run the risk of destroying my data. And yes, that spelling mistake "asyncrhonously" in your documentation.

The documentation also states:

> On "write" operation (any write on database) is the number of responses to be coherent before to send the response to the client. **Set to 1 if you don't want this check at write time**. 

No where does it mention that setting it to 1 will destroy my data.

So here is the facts:

- If I have it set to writeQuorum: "majority", I can't write to node1.
- The documentation downplay the severity of setting writeQuorum to 1. 

The database should protect us against bad configurations. At least if there is a chance of destroying our data, it should warn us or prevent syncing if things are mis-configured. We trust that OrientDB will keep our data safe above all else.

Protecting the data of your users should be your biggest and number one priority. Even if security is compromised, you can alway fix it and restore the database with it's data intact. If you lose data it's gone forever.

We are taking a huge gamble and are betting our entire business on OrientDB. Increasingly it's starting to feel like we are carrying all the risk :(

This is not a simple question. I refuse to believe that a simple little variable just destroyed 4 days worth of data. Something is wrong. Very wrong!

**Comment by lvca** [comment] 2016-09-20 07:04
Hey @anber500, if you have 3 servers with writeQuorum=1, in the case of conflict and no winner, your database could be not consistent. It's not OrientDB, but it's ANY database based on quorum. Take a look at https://en.wikipedia.org/wiki/Quorum_(distributed_computing). We have an issue to declare what happen in this case, namely who is the winner: https://github.com/orientechnologies/orientdb/issues/6376.

Now, your data loss is due to the fact that you restarted the server with more records, so the other server (with fewer records) created the backup for the server when it reattached to the cluster. 

To have servers with the same data, the `majority` is the minimum as `writeQuorum`. Why did you use 1? Because you want a minor latency?

Now you probably migrated from a previous version of OrientDB that contained a bug in the undo operation (in the case of conflict the operation wasn't undone correctly in some cases). With 2.2.10 this should be fine.

So with v2.2.10 if you use writeQuorum=1 the database should remain consistent in case one of the 3 servers disagrees, but in the case that every server provides a different result, there is no majority, so OrientDB can't decide what's the final value.

If you have inconsistency when only one node is not aligned, this is a bug.

**Comment by anber500** [comment] 2016-09-20 07:52
I have writeQuorum as 1 because I want low latency between the write node and the read nodes.
I need the read nodes to be up to date with the write node at all times but I'm not concerned with it the other way around. The write queries on on node2 and node3 are not critical.

Also, I had issues with the nodes not reaching quorum as per the following post:

http://stackoverflow.com/questions/39494800/orientdb-keeps-locking-records-indefinitely/39503578#39503578

I used "asynchronous" mode because I need low latency and because that was the only way I could get node1 to write to the database. I didn't really need **writeQuorum** to block writes to node1. I mostly need node2 and node3 to follow node1's lead but incase of a write action on any of those nodes, I still need the data to propagate to node1, ...eventually. The result of that experiment was that OrientDB would lock the records and not release the records unless the database was restarted. 

I have a slight issue with the "writeQuorum" only accepting the majority as the winner. At the moment, I have 1 main write node, this may change in future. I have multiple read nodes for performance purposes as well as keeping data nicely replicated. The problem is that my main write node will always be the odd one out and will always lose to the majority. 

Reaching quorum by the majority should be fine if there are a small set of data that's not aligned but if the differences are too big, then there is obviously a problem and the nodes should not get to decide the fate of an entire database.

In cases where I may start an instance of a pre configured node on AWS, I can't risk that older instances could decide a coup on node1.

What I take away from this is that version 2.2.10 has fixes in place to prevent this writeQuorum issue?

So does that mean I can still use writeQuorum=1 if I deploy the new version of OrientDB?

**Comment by lvca** [comment] 2016-09-20 08:05
If you have only 1 node among 3 that execute writes, then writeQuorum=1 should never encounter any conflicts. So even with releases before of 2.2.10 it should work. The fact your database wasn't consistent even with only one node writing, means that you have more than 1 node that writes, or this is a bug. Could you confirm this? If yes, how can we reproduce the issue?

**Comment by anber500** [comment] 2016-09-20 08:25
I can guarantee that at this time, I only write to node1. 

My code connects via IP on port 2424 to node1. Unless hazelcast is sending writes off to node2 and node3, I'm sure that I'm only writing and reading on node1. The other nodes should only replicate.

This is also not the only issue we are experiencing. We are using PyOrient and also discovered too late that pyorient does not support distributed mode. There is a develop branch on /mogui/pyorient that has a binary implementation of the serialiser but it contains a nasty memory leak:

https://github.com/mogui/pyorient/issues/215

I'm not sure how to replicate this as setting this up locally has proven futile. All I can do is share whatever logs will help and whatever information I can provide.

I'm in the process of upgrading to version 2.2.10 with the hope that it will help the as per the issue #6376.

**Comment by anber500** [comment] 2016-09-20 10:06
I have finished updating to version 2.2.10 and things are still not working for me.

I upgraded my AWS instances to version 2.2.10.

My default-distributed-db-config.json is as follows:

    {
      "autoDeploy": true,
      "readQuorum": 1,
      "writeQuorum": "majority",
      "executionMode": "synchronous",
      "readYourWrites": true,
      "servers": {
        "*": "master"
      },
      "clusters": {
        "internal": {
        },
        "*": {
          "servers": ["<NEW_NODE>"]
        }
      }
    }

My main node (node1) seem to have been working. As soon as I started node2, celery started throwing errors like this:

> Exception: Could not complete the command [CREATE EDGE post FROM #1746:77 TO #1833:36214 SET created_at=DATE("2016-09-20 08:56:56");]
[2016-09-20 09:51:21,967 :] com.orientechnologies.orient.core.exception.OConcurrentModificationException - Cannot UPDATE the record #1746:77 because the version is not the latest. Probably you are updating an old record or it has been modified by another user (db=v2905 your=v2904)
	DB name="MyDatabase"
[2016-09-20 09:51:21,984 :] Retry 6: [CREATE EDGE post FROM #1746:77 TO #1833:36214 SET created_at=DATE("2016-09-20 08:56:56");]
[2016-09-20 09:51:21,990 :] com.orientechnologies.orient.core.exception.OConcurrentModificationException - Cannot UPDATE the record #1746:77 because the version is not the latest. Probably you are updating an old record or it has been modified by another user (db=v2905 your=v2904)
	DB name="MyDatabase"


In order to confirm that this is not a celery issue, which it's not, I attempted to run the command in the error via the studio on node1.

    CREATE EDGE post FROM #1746:77 TO #1833:36214 SET created_at=DATE("2016-09-20 08:56:56");

I got the following error:

    com.orientechnologies.orient.core.exception.OConcurrentModificationException: Cannot UPDATE the record #1746:77 because the version is not the latest. Probably you are updating an old record or it has been modified by another user (db=v2905 your=v2904) DB name="MyDatabse"

I thought that maybe it's because node2 may have ownership so I tried running the command on node2.

Same error. 

It doesn't matter on which node I run the command, I can't update records if I I have  "writeQuorum" as "majority".

**Comment by anber500** [comment] 2016-09-20 11:12
I can only write that record to the DB if I restart orientDB.

**Comment by lvca** [comment] 2016-09-21 03:01
If the database has been created in non distributed mode, it could be a bug we already fixed in 2.1.11-SNAPSHOT. Please, can you try this release? https:////oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-community/2.2.11-SNAPSHOT/orientdb-community-2.2.11-20160920.171157-6.tar.gz

**Comment by anber500** [comment] 2016-09-21 04:29
cool, will give it a try.

**Comment by anber500** [comment] 2016-09-21 09:15
I have upgraded all 3 nodes to 2.1.11-SNAPSHOT. Within a minute, I start getting errors.

I can't write to the database because the records is always out of date.

From the logs, I can see an awful lot of NullPointerExceptions.

Here is a copy of the log on node1:

https://gist.githubusercontent.com/anber500/41f742852047b753aff447a64ce5cd5e/raw/0ca0c49b006e0cbdacd9d9849069f7396e724c95/orientdb.err

**Comment by lvca** [comment] 2016-09-23 06:52
Weird: in the log I can find `Caused by: java.lang.NullPointerException` but not where the exception is thrown. Is there any way to provide me a test case that reproduce it?

**Comment by lvca** [comment] 2017-06-06 03:34
Closing this because of no answer after a long time.

**Closed by lvca** 2017-06-06 03:34 UTC
Labels: question

**Comment by chaudharisuresh997** [comment] 2022-05-23 09:14
Still this issue comes up lets say we have two instances of orientdb pointed to service.One instance of db always updates to latest version and other one is not able to catch up with latest changes and falls behind.is there any config.
