### ISSUE TITLE
Magic number verification failed for page - Distributed mode

### ISSUE THREAD

**Issue by hoangvu2k2** [orientechnologies/orientdb#8685] opened 2018-11-30 18:27 UTC
## Expected behavior  
No exception while writing data to OrientDB

#### No writing is allowed after 3-4 hours of continuously pushing data to orientdb. Got the following exception: 
![image](https://user-images.githubusercontent.com/10359953/49307389-aaa6d000-f49a-11e8-8e30-0579a6840de0.png)

#### In orientDB, got the following exception 
![image](https://user-images.githubusercontent.com/10359953/49306686-96fa6a00-f498-11e8-9e5b-1bee36506076.png)

#### Sometime orientdb could not be restarted because some database files were missing 
![image](https://user-images.githubusercontent.com/10359953/49307137-ea20ec80-f499-11e8-9346-0ac6b40d9bab.png)

**Comment by hoangvu2k2** [comment] 2018-12-03 20:31
**Update on this issue:** 
I took the advice from the other tickets: Export data into JSON file and import into a empty database  - but it did not help. The same issue happened again 

The question is do we have any work-around in case this issue  happens?

**Comment by laa** [comment] 2018-12-04 07:15
Guys the problem is not in storage but in  the way how distributed send database to other node assigned to @tglman

**Comment by laa** [comment] 2018-12-05 12:04
Yes, that is interesting. None the less could you try on completely not distributed node. I have to be sure. 
What is the size of the files for this specific edge class? You see I expect that issue in distributed replication because `index.cpm` file is completely absent according to your screenshot, that can not happen in standalone mode because we never remove files (obviously :-) )

**Comment by laa** [comment] 2019-05-10 10:38
Should be fixed on latest 3.0.x but you should import/export your database to resolve it.

**Closed by laa** 2019-05-10 10:38 UTC
