### ISSUE TITLE
java.util.ConcurrentModificationException on commit in remote for document with LINKSET

### ISSUE THREAD

**Issue by wouterv** [orientechnologies/orientdb#4303] opened 2015-06-05 07:12 UTC
When saving a document containing a LINKSET with 2 new other documents, the server throws an exception on commit:

````
{db=beeyondmemory} Sent run-time exception to the client /127.0.0.1:53164: com.orientechnologies.orient.core.exception.OStorageException: Error during transaction commit.
com.orientechnologies.orient.core.exception.OStorageException: Error during transaction commit.
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:941)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:488)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:147)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2427)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2397)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.commit(ONetworkProtocolBinary.java:1088)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:390)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:217)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextEntry(HashMap.java:922)
	at java.util.HashMap$EntryIterator.next(HashMap.java:962)
	at java.util.HashMap$EntryIterator.next(HashMap.java:960)
	at com.orientechnologies.orient.core.db.record.ORecordLazySet$1.next(ORecordLazySet.java:98)
	at com.orientechnologies.orient.core.db.record.ORecordLazySet$1.next(ORecordLazySet.java:75)
	at com.orientechnologies.orient.core.db.record.OLazyRecordIterator.next(OLazyRecordIterator.java:68)
	at com.orientechnologies.orient.core.db.record.OLazyRecordIterator.next(OLazyRecordIterator.java:38)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeLinkCollection(ORecordSerializerBinaryV0.java:698)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:569)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:261)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:104)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2105)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:714)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitEntry(OAbstractPaginatedStorage.java:1968)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:922)
	... 8 more
````

It looks like we are having the same issue as #3861, but with version 2.0.10, it still occurs.

I have started the server with debug mode and attached an intellij project with the orient source to the running server and some interesting stuff happens. When I set a breakpoing when it is committing, I can see in the txEntries the record is fine. It contains the document that has a lazy set with 2 documents in it.
But when the exception occurs, the debug screen suddenly shows 3 records, one of which is a duplicate of another element in the set.

See screen shots
Record ok:
![screenshot tx record ok](https://cloud.githubusercontent.com/assets/616997/8001073/69db931e-0b62-11e5-904c-a139f5420c0d.png)
Record not ok, this is the state when the exception is thrown:
![screenshot tx record not ok](https://cloud.githubusercontent.com/assets/616997/8001081/7a9c5120-0b62-11e5-8571-e9076b809e9e.png)

**Comment by lvca** [comment] 2015-06-11 08:31
Thanks for the PR ;-)

**Comment by iamlogiq** [comment] 2015-08-19 02:27
@lvca Hey there... I'm using verision 2.1 and i'm still getting the same error above. Is that normal? 
I can't seem to create a linkset insert with 2 or more records. I get this error: java.util.ConcurrentModificationException

please help

**Comment by dtriharta** [comment] 2015-09-01 07:58
I'm getting exactly the same error. Using version 2.1-rc3

**Comment by lvca** [comment] 2015-09-02 04:57
@dtriharta please don't use RC after we release the official ones (now 2.1.1) ;-)
@iamlogiq could you please provide us few lines of code that reproduce this problem?

**Comment by wouterv** [comment] 2015-10-15 12:47
I am seeing this too again. But only in distributed mode. When trying to reproduce locally in single mode, the error does not occur.

```
     ... 65 common frames omitted com.orientechnologies.orient.core.exception.OTransactionException: Error on committing distributed transaction 
    at com.orientechnologies.orient.server.distributed.ODistributedStorage.commit(ODistributedStorage.java:984) 
    at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:488) 
    at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:147) 
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2437) 
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2407) 
    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.commit(ONetworkProtocolBinary.java:1092) 
    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:394) 
    at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:217) 
    at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69) com.orientechnologies.orient.core.exception.ODatabaseException: Error on saving record #5202:4 
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1795) 
    at com.orientechnologies.orient.core.tx.OTransactionOptimistic.addRecord(OTransactionOptimistic.java:312) 
    at com.orientechnologies.orient.core.tx.OTransactionOptimistic.saveRecord(OTransactionOptimistic.java:253) 
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2316) 
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:118) 
    at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1727) 
    at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1718) 
    at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:76) 
    at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.recursiveLinkSave(ORecordSerializerBinaryV0.java:680) 
    at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeOptimizedLink(ORecordSerializerBinaryV0.java:694) 
    at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:574) 
    at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:262) 
    at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:105) 
    at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2100) 
    at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:695) 
    at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitEntry(OAbstractPaginatedStorage.java:1936) 
    at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:919) 
    at com.orientechnologies.orient.server.distributed.ODistributedStorage.commit(ODistributedStorage.java:847) 
    at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:488) 
    at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:147) 
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2437) 
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2407) 
    at com.orientechnologies.orient.server.distributed.task.OTxTask.execute(OTxTask.java:116) 
    at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.executeOnLocalNode(OHazelcastPlugin.java:753) 
    at com.orientechnologies.orient.server.hazelcast.ODistributedWorker.onMessage(ODistributedWorker.java:298) 
    at com.orientechnologies.orient.server.hazelcast.ODistributedWorker.run(ODistributedWorker.java:121) 
Caused by: java.util.ConcurrentModificationException: null 
    at java.util.HashMap$HashIterator.nextEntry(HashMap.java:922) 
    at java.util.HashMap$EntryIterator.next(HashMap.java:962) 
    at java.util.HashMap$EntryIterator.next(HashMap.java:960) 
    at com.orientechnologies.orient.core.db.record.ORecordLazySet$1.next(ORecordLazySet.java:98) 
    at com.orientechnologies.orient.core.db.record.ORecordLazySet$1.next(ORecordLazySet.java:75) 
    at com.orientechnologies.orient.core.db.record.OLazyRecordIterator.next(OLazyRecordIterator.java:68) 
    at com.orientechnologies.orient.core.db.record.OLazyRecordIterator.next(OLazyRecordIterator.java:38) 
    at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeLinkCollection(ORecordSerializerBinaryV0.java:706) 
    at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:571) 
    at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:262) 
    at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:105) 
    at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2100) 
    at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:695) 
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1693) 
     ... 25 common frames omitted
```

**Comment by wouterv** [comment] 2015-10-15 13:01
Tried the test locally again. When running the server on single mode. All is well. When running distributed: I get the exception.

**Comment by wouterv** [comment] 2015-10-15 13:27
I have tested the issue with a standalone Orient db. Everything works fine.
But when running distributed, I get the above error. The original bugfix I have never tested in distribution, only standalone.

**Comment by wouterv** [comment] 2015-10-15 13:30
Exception on server side:

```
com.orientechnologies.orient.core.exception.ODatabaseException: Error on saving record #5202:4
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1944)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.addRecord(OTransactionOptimistic.java:432)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.saveRecord(OTransactionOptimistic.java:363)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2468)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:120)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1768)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1759)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:81)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.recursiveLinkSave(ORecordSerializerBinaryV0.java:675)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeOptimizedLink(ORecordSerializerBinaryV0.java:689)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:574)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:260)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:105)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2285)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:671)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitEntry(OAbstractPaginatedStorage.java:2328)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1111)
	at com.orientechnologies.orient.server.distributed.ODistributedStorage.commit(ODistributedStorage.java:969)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:609)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:156)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2582)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2551)
	at com.orientechnologies.orient.server.distributed.task.OTxTask.execute(OTxTask.java:131)
	at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.executeOnLocalNode(OHazelcastPlugin.java:802)
	at com.orientechnologies.orient.server.hazelcast.ODistributedWorker.onMessage(ODistributedWorker.java:296)
	at com.orientechnologies.orient.server.hazelcast.ODistributedWorker.run(ODistributedWorker.java:119)
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextEntry(HashMap.java:922)
	at java.util.HashMap$EntryIterator.next(HashMap.java:962)
	at java.util.HashMap$EntryIterator.next(HashMap.java:960)
	at com.orientechnologies.orient.core.db.record.ORecordLazySet$1.next(ORecordLazySet.java:96)
	at com.orientechnologies.orient.core.db.record.ORecordLazySet$1.next(ORecordLazySet.java:73)
	at com.orientechnologies.orient.core.db.record.OLazyRecordIterator.next(OLazyRecordIterator.java:68)
	at com.orientechnologies.orient.core.db.record.OLazyRecordIterator.next(OLazyRecordIterator.java:38)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeLinkCollection(ORecordSerializerBinaryV0.java:708)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:568)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:260)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:105)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2285)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:671)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1834)
	... 25 more
```

**Comment by wouterv** [comment] 2015-10-15 14:00
It looks like the following scenario

Document 1 and Document 2 are existing object in the database
Document 1 and 2 have a LINKSET collection with links to some distinct other Documents.

In one transaction:
create a new Document 3, add to Document LINKSET 1, and Document LINKSET 2.
save Document 1, save Document 2.

The Document 3 gets a new id on save in the first save call and in the second save call the set is messed up because it still contains a item with the previous temporary ids of Document 3

**Comment by wouterv** [comment] 2015-10-20 14:26
Hi guys. As I believe the new error is in a different case than for which I supplied a patch, I have create a new issue, with error and code to reproduce: #5172

**Comment by lvca** [comment] 2015-10-20 21:41
Since #5172 is closed, can I consider this closed as well?

**Comment by wouterv** [comment] 2015-10-21 13:01
Fine by me, don't know about @dtriharta and @iamlogiq

**Comment by dtriharta** [comment] 2015-10-21 13:06
that's fine by me too!

**Comment by lvca** [comment] 2015-10-21 14:41
Thanks, closing it.

**Closed by lvca** 2015-10-21 14:41 UTC
Labels: bug, contributor friendly
