### ISSUE TITLE
Live query: throws LINKBAG should never appear in a projection

### ISSUE THREAD

**Issue by gianluca-valentini** [orientechnologies/orientdb#8752] opened 2019-02-04 16:20 UTC
## Expected behavior  
During execute live query on Vertex, the Create/Update/Delete (and other events) should be notificated without exception even if the vertex is joined to other vertex with edges.

## Actual behavior  
I have a ODatabaseSession graph where I execute a live query using `live() method`.
When I start the live execution I have a server error:

> $ANSI{green {db=MySchema}} Error executing live query subscriber.
java.lang.UnsupportedOperationException: LINKBAG should never appear in a projec
tion
        at com.orientechnologies.orient.core.serialization.serializer.result.bin
ary.OResultSerializerNetwork.serializeValue(OResultSerializerNetwork.java:426)
        at com.orientechnologies.orient.core.serialization.serializer.result.bin
ary.OResultSerializerNetwork.serialize(OResultSerializerNetwork.java:134)
        at com.orientechnologies.orient.core.serialization.serializer.result.bin
ary.OResultSerializerNetwork.toStream(OResultSerializerNetwork.java:649)
        at com.orientechnologies.orient.client.remote.message.OMessageHelper.wri
teProjection(OMessageHelper.java:411)
        at com.orientechnologies.orient.client.remote.message.OMessageHelper.wri
teResult(OMessageHelper.java:448)
        at com.orientechnologies.orient.client.remote.message.OLiveQueryPushRequ
est.write(OLiveQueryPushRequest.java:64)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkP
rotocolBinary.push(ONetworkProtocolBinary.java:875)
        at com.orientechnologies.orient.server.OServerLiveQueryResultListener.se
ndEvent(OServerLiveQueryResultListener.java:34)
        at com.orientechnologies.orient.server.OServerLiveQueryResultListener.on
Update(OServerLiveQueryResultListener.java:47)
        at com.orientechnologies.orient.core.sql.executor.LiveQueryListenerImpl.
onLiveResult(LiveQueryListenerImpl.java:147)
        at com.orientechnologies.orient.core.query.live.OLiveQueryQueueThreadV2.
run(OLiveQueryQueueThreadV2.java:57)

I tried version **3.0.8, 3.0.10, 3.0.13** too but I have the same exceptions

## Steps to reproduce  
Create two Vertices A, B and an edge E from A to B like this:

`A (out) --- E ---> (in) B`

Now create a java code where execute a live query:

> 
                     graph.live("select from B", new OLiveQueryResultListener() {

			@Override
			public void onUpdate(ODatabaseDocument database, OResult before, OResult after) {
				System.out.println("onUpdate");
				
			}

			@Override
			public void onError(ODatabaseDocument database, OException exception) {
				System.out.println("onError");
			}

			@Override
			public void onEnd(ODatabaseDocument database) {
				System.out.println("Live query terminate with unsubscribe");

			}

			@Override
			public void onDelete(ODatabaseDocument database, OResult data) {
				System.out.println("onDelete");
				
			}

			@Override
			public void onCreate(ODatabaseDocument database, OResult data) {
				System.out.println("onCreate");
			}
		}, new HashMap<String, String>());

When I update a data on the Vertex B, live query does not works but give me the exposed exception.

**Comment by luigidellaquila** [comment] 2019-02-06 10:47
Hi @gianluca-valentini 

I think this problem is already fixed in v 3.0.14 (https://github.com/orientechnologies/orientdb/commit/1ef562ffabbfcefaaa5bfed229be9d671b1f27dd) 
I tested it on the snapshot and it seems to be the case. Please let me know if you still can reproduce it

Thanks

Luigi

**Comment by gianluca-valentini** [comment] 2019-02-06 11:58
Hi @luigidellaquila 
thanks for your update.
How I can update my docker distribution if is not preset on the docker hub repository?
Looking on [docker hub](https://hub.docker.com/_/orientdb?tab=tags) I cannot find the **3.0.14** tag
thanks
Gianluca

**Comment by luigidellaquila** [comment] 2019-02-06 13:38
Hi @gianluca-valentini 

checking now, probably it's still in approval

Thanks

Luigi

**Comment by luigidellaquila** [comment] 2019-02-06 13:44
Hi @gianluca-valentini 

You are right, it's not yet on DockerHub (missed a little step, I did it now). 
It should be a matter of a few hours for it to be available

Thanks

Luigi

**Comment by gianluca-valentini** [comment] 2019-02-06 14:00
Hi @luigidellaquila 
thanks for your answer. I'm trying to use the windows installation.

I downloaded from [Orientdb 3.0.14](https://orientdb.org/download), copied the previous database (from OrientDB 3.0.13 to the new one) e started the posted code (with the aligned orientdb client).

When I update, using the OrientDB GUI a property on Vertex B (object of the live query) I continue to have the same exception

I upload the server log with the complete exception
[orient-server.log](https://github.com/orientechnologies/orientdb/files/2836584/orient-server.log)

Please let me know how to proceed

**Comment by gianluca-valentini** [comment] 2019-02-06 14:20
@luigidellaquila ,
looking the code about the exception

> java.lang.UnsupportedOperationException: LINKBAG should never appear in a projection
> 	at com.orientechnologies.orient.core.serialization.serializer.result.binary.OResultSerializerNetwork.serializeValue(OResultSerializerNetwork.java:426)


the _com.orientechnologies.orient.core.serialization.serializer.result.binary.OResultSerializerNetwork_ code at 426 row for  `serializeValue ` method we can see:

> 
@SuppressWarnings("unchecked")
>   public void serializeValue(final BytesContainer bytes, Object value, final OType type, final OType linkedType) {
> 
> final int pointer;
> switch (type) {
> case INTEGER:
> case LONG:
> ...
> case LINKBAG:
> throw new UnsupportedOperationException("LINKBAG should never appear in a projection");

Currently I'm using livequery on a Vertex with edges. Is there some limitations on live execution on this vertices scenario? Does Livequery work only on Vertices without edges?

**Comment by luigidellaquila** [comment] 2019-02-06 14:22
hi @gianluca-valentini 

The point is that the execution should not get there, because the ridbags should be converted to normal lists before they arrive to the serialization layer.

Do you have  a full running test case to reproduce the problem?

Thanks

Luigi

**Comment by gianluca-valentini** [comment] 2019-02-06 14:29
Hi @luigidellaquila 
tell me what you need. I can give you the myschema.zip if you want.
Then you need to open a remote connection with the schema and execute the live query. I can give you my Junit test if you need

**Comment by luigidellaquila** [comment] 2019-02-06 14:39
Hi @gianluca-valentini 

the schema and a JUnit would be fantastic

thanks

Luigi

**Comment by gianluca-valentini** [comment] 2019-02-06 14:40
@luigidellaquila 
is there a place where post my database?

**Comment by gianluca-valentini** [comment] 2019-02-06 15:33
@luigidellaquila 
I attached here my java class and database zip.

Let me know if you have some news about this issue as we are working hard on this task currently
[test_scenario.zip](https://github.com/orientechnologies/orientdb/files/2836984/test_scenario.zip)

**Comment by luigidellaquila** [comment] 2019-02-08 14:14
Hi @gianluca-valentini 

I just checked your test and it seems to work fine. 
The new 3.0.14 is now available on DockerHub, could you please try with it and see if it's solved?

Thanks

Luigi

**Comment by gianluca-valentini** [comment] 2019-02-08 14:21
Hi @luigidellaquila 
did you test it on orientdb-3.0.14 Windows server? 

I'm curious to understand why, with the win distribution, my test does not work to me

Thanks
Gianluca.

**Comment by luigidellaquila** [comment] 2019-02-08 14:38
Hi @gianluca-valentini 

I do not have a windows machine to test it now, but it should not do much difference...

**Comment by gianluca-valentini** [comment] 2019-02-08 15:05
Thanks
I tested it on win server downloaded from Orient host, without success.
This is very strange for me

**Comment by gianluca-valentini** [comment] 2019-02-14 10:20
@luigidellaquila 
Looking on [docker hub](https://hub.docker.com/_/orientdb?tab=tags) I found the **3.0.15** tag.
I'm trying to work with 3.0.14 version without success. Is there some news about my issue?

I don't understand if now I need to move to LiveQuery on 3.0.15 as current issue is still in open status

**Comment by gianluca-valentini** [comment] 2019-02-14 11:28
@luigidellaquila 
update:
I tested it on win 3.0.15 distro and I continue to have the same issue

![image](https://user-images.githubusercontent.com/3224592/52784022-0cb3b200-3054-11e9-8dbd-008440500659.png)

**Comment by gianluca-valentini** [comment] 2019-02-14 12:13
@luigidellaquila 
it works on linux. So it seems that the problem is presento no windows server only

I hope that this news can help you

**Comment by luigidellaquila** [comment] 2019-02-14 14:08
Hi @gianluca-valentini 

thank you for confirming it, I'll see if someone in the team can test it on Windows (I don't have a win machine unfortulately)

Thanks

Luigi

**Closed** 2021-08-06 11:40 UTC
Labels: bug
