### ISSUE TITLE
Named Parameters in Traverse statements are not replaced

### ISSUE THREAD

**Issue by plgregoire** [orientechnologies/orientdb#5225] opened 2015-10-26 15:13 UTC
In this situation :

* VerticeA (#12:20598) is connected to VerticeB by edge1.
* Edge1 has a label property with value = "Test" 

If you execute this query: 
**Traverse in,out_E[Label="Test"] From #12:20598**
VerticeA, VerticeB and Edge1 will be returned.

However, if you use named parameters like this:
**Traverse in,out_E[Label=:param1] From #12:20598**
with this hashmap<String, Object>:
**["param1":"Test"]**
Only VerticeA will be returned.

*Also, using the same Java Code if I introduce named parameters in the where clause of a select, those named parameters seems to be replaced with appropriate values. It is only in the Traverse statements that this replacement does not occur.

Could you try to reproduce it and confirm if this is a bug please ?

Thank you

**Comment by maggiolo00** [comment] 2015-10-26 16:03
hi @plgregoire which version of OrientDB?

**Comment by plgregoire** [comment] 2015-10-26 16:16
sorry I forgot to specify it.
We use version 2.1.4.

**Comment by plgregoire** [comment] 2015-10-28 13:51
Just wondering if you had time to reproduce it
Do you need more information ?

**Comment by luigidellaquila** [comment] 2015-10-30 12:03
Hi @plgregoire 

I could reproduce the problem, I'm working on it right now.

Thanks

Luigi

**Comment by luigidellaquila** [comment] 2015-10-30 12:51
Hi @plgregoire 

I just pushed a fix on branch 2.1.x
Now I'm checking if the issue is also present in develop branch

**Comment by plgregoire** [comment] 2015-10-30 12:57
Great !!
Thank you

**Comment by luigidellaquila** [comment] 2015-10-30 13:24
And I can confirm that it worked fine in 2.2 (develop)
I'm closing this, please reopen in case of other problems

Thanks

Luigi

**Closed by luigidellaquila** 2015-10-30 13:24 UTC
Labels: bug
