### ISSUE TITLE
Deadlock in embedded server

### ISSUE THREAD

**Issue by vantonov1** [orientechnologies/orientdb#6578] opened 2016-08-17 13:57 UTC
v 2.2.7

Threads dump attached. I also made heap dump, but it is 42MB zipped. It is a rather big web app, I cant provide test code to reproduce

[threads_report.txt](https://github.com/orientechnologies/orientdb/files/422714/threads_report.txt)

**Comment by laa** [comment] 2016-08-17 15:46
Hi @vantonov1 we already had similar issue, so my first question did you set --XX:MaxDirectMemorySize parameters before start ?

**Comment by jamieb22** [comment] 2016-08-17 19:11
Andrey.. may you kindly explain how this occurs when MaxDirectMemorySize is not set? I'd like to understand the underlying cause. Surely if the cache size is smaller, Orient will just use a smaller cache. Why would it stop working altogether.

**Comment by laa** [comment] 2016-08-18 06:08
Hi @jamieb22 , the problem with absence of MaxDirectMemorySize  is that Java may not provide direct memory on request , as result internal error may be thrown but locks keep hold.

**Comment by laa** [comment] 2016-08-18 06:27
Hi @vantonov1, @jamieb22 I found reason of the deadlock I will provide fix in couple of hours.

**Comment by jamieb22** [comment] 2016-08-18 06:34
If I right understand, this matter concerns a cache. Why is a cache preventing the database from functioning normally? If direct memory cannot be allocated, then shouldn't the database simply use a smaller cache?

**Comment by laa** [comment] 2016-08-18 06:51
Because we can not know before head how much of direct memory Java will allow. Well, we do some guesses on system start but as we can see they are not 100% precise.  Also I think that setting of one system parameter is not provide huge overhead.

**Comment by jamieb22** [comment] 2016-08-18 07:15
Since the cache is an optional facility designed to enhance performance, can we just bypass the cache, or reduce the size of the cache dynamically should it fail to allocate direct memory?

**Comment by laa** [comment] 2016-08-18 07:17
We can not bypass cache because we need to have some shared memory area to perform operations. But we may reduce size as an option. The problem is that it is big programming overhead, so if it is done not as first priority.

**Comment by jamieb22** [comment] 2016-08-18 07:37
Are you pre-allocating a fixed size cache on startup or dynamically on demand? The advantage of the former approach would be that the system could reserve the memory upfront, thereby guaranteeing that the memory will be available for later usage. It also has the advantage, that an appropriate size of the cache could be determined on startup.

**Comment by laa** [comment] 2016-08-18 07:52
Size of the cache is set by startup , the problem of this situation is only that Java does not allow to allocate required memory , why setting of Java parameter is not applicable ?

**Comment by laa** [comment] 2016-08-18 07:53
@vantonov1 I have fixed the issue. You may build fix from source code. Also, it will be in next 2.2.8 release.

**Closed by laa** 2016-08-18 07:53 UTC
Labels: bug, storage team

**Comment by vantonov1** [comment] 2016-08-18 08:06
Hi!

No, Im not started to tune performance yet, it was just integration test. But its also interesting for me how it is related to deadlock :)

**Comment by vantonov1** [comment] 2016-08-18 08:08
Oops, I didnt saw your answer. Thanks!
