### ISSUE TITLE
Import/Export Does Fails in OrientDB Studio

### ISSUE THREAD

**Issue by edalorzo** [orientechnologies/orientdb#1640] opened 2013-08-22 22:30 UTC
### Steps to Reproduce

1. Start OrientDB server.
2. Open OrientDB Studio (http://localhost:2480)
3. Create a new Database sample.
4. Log in to Tinkerpo Database
5. Go to import/export tab.
6. Create an export file of Tinkerpop database.
7. Disconnect
8. Connect to the new sample database.
9. Go to the import/export tab.
10. Run an import of the same exported file.

The output of OrientDB Studio reports nothing, the server output console shows:

```
2013-08-22 16:25:15:075 INFO Started import of database 'local:${ORIENTDB_HOME}/databases/sample' from streaming.json... [OServerCommandPostImportData
base]Error on database import happened just before line 0, column 0
java.util.zip.ZipException: invalid stored block lengths
        at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164)
        at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:116)
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:283)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:325)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.fill(BufferedReader.java:154)
        at java.io.BufferedReader.read(BufferedReader.java:175)
        at com.orientechnologies.orient.core.serialization.serializer.OJSONReader.nextChar(OJSONReader.java:230)
        at com.orientechnologies.orient.core.serialization.serializer.OJSONReader.jump(OJSONReader.java:206)
        at com.orientechnologies.orient.core.serialization.serializer.OJSONReader.readNext(OJSONReader.java:116)
        at com.orientechnologies.orient.core.serialization.serializer.OJSONReader.readNext(OJSONReader.java:107)
        at com.orientechnologies.orient.core.serialization.serializer.OJSONReader.readNext(OJSONReader.java:102)
        at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importDatabase(ODatabaseImport.java:157)
        at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostImportDatabase.execute(OServerCommandPostImportDat
abase.java:59)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:145)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:482)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:45)
Error on formatting message
Conversion = '_'
-> java.util.Formatter.checkText(Formatter.java:2547)
-> java.util.Formatter.parse(Formatter.java:2533)
-> java.util.Formatter.format(Formatter.java:2469)
-> java.util.Formatter.format(Formatter.java:2423)
-> java.lang.String.format(String.java:2797)
-> com.orientechnologies.common.log.OLogManager.log(OLogManager.java:45)
-> com.orientechnologies.common.log.OLogManager.warn(OLogManager.java:95)
-> com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:452)
-> com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:45)
```
### System Information

 * **OrientDB Version**.......: 1.5.0
 * **Tinkerpop Blueprints**.......: 2.4.0
 * **Operating System**......: Windows 7 Enterprise
 * **Installed RAM**............: 8 GB
 * **Processor**.................: Intel Core i5/2.6Ghz
 * **System Type**.............: 64/bit
 * **Java Version**..............: JDK-1.7.0_25-b17/64-bit

**Comment by luigidellaquila** [comment] 2016-05-30 14:56
This functionality was removed from Studio, so the issue is no longer valid

Closing, thanks

Luigi

**Closed by luigidellaquila** 2016-05-30 14:56 UTC
Labels: bug
