### ISSUE TITLE
2.2: comma is not allowed in custom value (can't add custom attribute with multiple values for the class or property)

### ISSUE THREAD

**Issue by a-unite** [orientechnologies/orientdb#6263] opened 2016-06-06 11:18 UTC
## Expected behavior and actual behavior

These queries used to work before 2.2.0:

`ALTER CLASS v CUSTOM attirbutes=attribute1,attribute2`
`ALTER PROPERTY x.p CUSTOM attirbutes=attribute1,attribute2`

Not true for 2.2.0 anymore.

`ALTER CLASS v CUSTOM attirbutes=attribute1` works as expected.

## Steps to reproduce the problem
Example of the syntax discussed (with comma, not quoted) could be found here: 
http://orientdb.com/docs/2.2/SQL-Alter-Class.html

### OrientDB Version
- [*] v2.2.x - Please specify last number: 

### Operating System
- [*] Linux

### Java Version
- [*] 8

**Comment by luigidellaquila** [comment] 2016-06-06 11:20
Hi @a-unite 

Custom attributes are just strings, you can use the following syntax (quoted value):
```
ALTER CLASS v CUSTOM attirbutes="attribute1,attribute2"
ALTER PROPERTY x.p CUSTOM attirbutes="attribute1,attribute2"
```

Thanks

Luigi

**Comment by a-unite** [comment] 2016-06-06 11:54
@luigidellaquila, thanks!

I know this, of course, but could you please give us an idea, if it is intended behaviour and will stay there for the future.

Because we will have, then, to rewrite our API to skip escaped quotas in result of the way you proposed:
`{"attirbutes":"\"attribute1,attribute2\""}`
(documentation (see above) might need to be reviewed too, I think)

Actually, my first thoughts were that you started to use typed customs, but no, they are still strings and it is hard to understand, why should you need to put strings into the strings then.

Regards,
Ata

**Comment by luigidellaquila** [comment] 2016-06-06 12:22
Hi @a-unite 

The API is there to stay, the value of a custom variable is a string, so it has to be passed as a string (with single or double quotes). In next versions we will also allow full expression definition as the right value, eg (not yet supported) `ALTER CLASS v CUSTOM attirbutes = myFunction() + "foo" + $contextVar`

But I don't get how you are using that, where did you find `{"attirbutes":"\"attribute1,attribute2\""}` in the docs? The change is only on the SQL language, not on other APIs

Thanks

Luigi

**Comment by a-unite** [comment] 2016-06-06 12:46
@luigidellaquila,
thank you!
Will rewrite this part then, before migration to v2.2.

Sorry I had to explain that `{"attirbutes":"\"attribute1,attribute2\""}` is result of the query:

`select customFields from (select expand(classes) from metadata:schema) where name='V'`

which is applied to check customsFields added by customs quoted (`ALTER CLASS v CUSTOM attirbutes="attribute1,attribute2"`).

OK. I think, value for this query should be quoted for consistency in ordinal case too:
`ALTER CLASS v CUSTOM attirbutes="attribute1"`

And please, consider to rewrite docs [here](http://orientdb.com/docs/2.2/SQL-Alter-Class.html) and [here](http://orientdb.com/docs/2.2/SQL-Alter-Property.html) and some [more samples here](http://orientdb.com/docs/2.2/SQL.html#query-the-schema).

My best regards,
Ata

**Comment by a-unite** [comment] 2016-06-08 11:44
Luigi,

to close this ticket - I would ask you to review and anounce your decision.

If current behaviour will stay - to make it consistent - we will have to rewrite logic, adding quotes to all kinds of current customs values (and adjust existing production and devs databases), then remove quotes (as they escaped and included in values) after schema reading. 

But if syntax like `ALTER CLASS v CUSTOM attirbutes="attribute1"` will become mandatory, then that will mean we will need to rewrite (and fix databases) again, because there are good chances, that extra quotes will be ommited already by ODB engine.

Thanks in advance!

**Comment by luigidellaquila** [comment] 2016-06-08 15:37
Hi @a-unite 

I can confirm that to set custom attributes you will have to use quotes.
Anyway there seems to be a bug somewhere: the values should be saved without quotes, so the result of the query should be `{"attirbutes":"attribute1,attribute2"}` and not `{"attirbutes":"\"attribute1,attribute2\""}`. 

It already works fine for custom attributes of properties, so the bug seems to be only on custom attributes of classes. I'm working to a fix, I'll keep you posted

Thanks

Luigi

**Comment by luigidellaquila** [comment] 2016-06-08 16:03
Hi @a-unite 

I just pushed a fix, now the quoted custom values are correcty stored as plain strings (without quotes).
Please let me know if it solves your problem (or if it makes your migration easier)

Thanks

Luigi

**Comment by a-unite** [comment] 2016-06-09 03:45
Dear @luigidellaquila,
thank you very much!

From this moment forward we will always quote custom values. Refactoring will take some time, but consistency is much more important.

With my best regards,
Ata

**Closed** 2016-06-09 03:52 UTC

**Comment by a-unite** [comment] 2016-06-09 05:36
BTW, I still think new syntax should be documented somewhere (at least altered [here](http://orientdb.com/docs/2.2/SQL-Alter-Class.html) for comma containing custom attribute's value), and, maybe, cases like `ALTER CLASS v CUSTOM c_attirbutes="c_value"` should be marked as deprecated.

**Comment by luigidellaquila** [comment] 2016-06-09 08:42
Hi @a-unite 

Good point, I'm updating the docs

Thanks

Luigi
