### ISSUE TITLE
OPaginatedCluster.deleteRecord null (Orient DB 2.1 RC5)

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#4567] opened 2015-07-14 09:54 UTC
2015-07-14 05:46:35 c.s.a.nk [ERROR] null
com.orientechnologies.orient.core.exception.OStorageException: null
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.deleteRecord(OPaginatedCluster.java:730) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doCreateRecord(OAbstractPaginatedStorage.java:1685) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.createRecord(OAbstractPaginatedStorage.java:698) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1869) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.addRecord(OTransactionOptimistic.java:419) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.saveRecord(OTransactionOptimistic.java:350) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2435) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:120) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1710) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1701) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:80) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag.serialize(OSBTreeRidBag.java:791) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.db.record.ridbag.ORidBag.toStream(ORidBag.java:266) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:578) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:258) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:104) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2216) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:664) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1804) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.addRecord(OTransactionOptimistic.java:419) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.saveRecord(OTransactionOptimistic.java:350) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2435) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:120) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1710) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1701) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:80) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.recursiveLinkSave(ORecordSerializerBinaryV0.java:671) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeOptimizedLink(ORecordSerializerBinaryV0.java:685) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:569) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:258) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:104) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2216) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:664) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitEntry(OAbstractPaginatedStorage.java:2139) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1016) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:596) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:148) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2549) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2518) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.commit(OrientTransactionalGraph.java:161) ~[orientdb-graphdb-2.1-rc5.jar:2.1-rc5]
	at com.stimulus.archiva.ej.a(MailArchiva:566) ~[ej.class:na]
	at com.stimulus.archiva.ej.a(MailArchiva:532) ~[ej.class:na]
	at com.stimulus.archiva.database.DatabaseService.a(MailArchiva:591) [DatabaseService.class:na]
	at com.stimulus.archiva.database.DatabaseService.a(MailArchiva:490) [DatabaseService.class:na]
	at com.stimulus.archiva.database.DatabaseService.a(MailArchiva:432) [DatabaseService.class:na]
	at com.stimulus.archiva.database.DatabaseService.a(MailArchiva:356) [DatabaseService.class:na]
	at com.stimulus.archiva.database.DatabaseService.a(MailArchiva:334) [DatabaseService.class:na]
	at com.stimulus.archiva.mb.b(MailArchiva:637) [mb.class:na]
	at com.stimulus.archiva.mb.a(MailArchiva:612) [mb.class:na]
	at com.stimulus.archiva.di$f.a(MailArchiva:592) [di$f.class:na]
	at com.stimulus.archiva.di$f.a(MailArchiva:552) [di$f.class:na]
	at com.stimulus.archiva.di$b.b(MailArchiva:616) [di$b.class:na]
	at com.stimulus.archiva.di$b.onSuccess(MailArchiva:602) [di$b.class:na]
	at com.google.api.client.googleapis.batch.BatchUnparsedResponse.parseAndCallback(BatchUnparsedResponse.java:197) [google-api-client-1.20.0.jar:1.20.0]
	at com.google.api.client.googleapis.batch.BatchUnparsedResponse.parseNextResponse(BatchUnparsedResponse.java:155) [google-api-client-1.20.0.jar:1.20.0]
	at com.google.api.client.googleapis.batch.BatchRequest.execute(BatchRequest.java:253) [google-api-client-1.20.0.jar:1.20.0]
	at com.stimulus.archiva.cv.a(MailArchiva:332) [cv.class:na]
	at com.stimulus.archiva.di.a(MailArchiva:124) [di.class:na]
	at com.stimulus.archiva.di.a(MailArchiva:205) [di.class:na]
	at com.stimulus.archiva.di.a(MailArchiva:103) [di.class:na]
	at com.stimulus.archiva.di.call(MailArchiva:58) [di.class:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_71]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_71]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_71]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]

**Comment by jamieb22** [comment] 2015-07-14 10:00
2015-07-14 05:56:23 c.s.a.nk [ERROR] null
com.orientechnologies.orient.core.exception.OStorageException: null
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.deleteRecord(OPaginatedCluster.java:730) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doCreateRecord(OAbstractPaginatedStorage.java:1685) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.createRecord(OAbstractPaginatedStorage.java:698) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1869) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.addRecord(OTransactionOptimistic.java:419) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.saveRecord(OTransactionOptimistic.java:350) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2435) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:120) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1710) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1701) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:80) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag.serialize(OSBTreeRidBag.java:791) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.db.record.ridbag.ORidBag.toStream(ORidBag.java:266) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:578) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:258) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:104) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2216) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:664) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1804) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.addRecord(OTransactionOptimistic.java:419) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.saveRecord(OTransactionOptimistic.java:350) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2435) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:120) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1710) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1701) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:80) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.recursiveLinkSave(ORecordSerializerBinaryV0.java:671) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeOptimizedLink(ORecordSerializerBinaryV0.java:685) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.writeSingleValue(ORecordSerializerBinaryV0.java:569) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.serialize(ORecordSerializerBinaryV0.java:258) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:104) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2216) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:664) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitEntry(OAbstractPaginatedStorage.java:2139) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1016) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:596) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:148) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2549) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2518) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.commit(OrientTransactionalGraph.java:161) ~[orientdb-graphdb-2.1-rc5.jar:2.1-rc5]
	at com.stimulus.archiva.ej.a(MailArchiva:566) ~[ej.class:na]
	at com.stimulus.archiva.ej.a(MailArchiva:532) ~[ej.class:na]
	at com.stimulus.archiva.database.DatabaseService.a(MailArchiva:591) [DatabaseService.class:na]
	at com.stimulus.archiva.database.DatabaseService.a(MailArchiva:490) [DatabaseService.class:na]
	at com.stimulus.archiva.database.DatabaseService.a(MailArchiva:432) [DatabaseService.class:na]
	at com.stimulus.archiva.database.DatabaseService.a(MailArchiva:356) [DatabaseService.class:na]
	at com.stimulus.archiva.database.DatabaseService.a(MailArchiva:334) [DatabaseService.class:na]
	at com.stimulus.archiva.mb.b(MailArchiva:637) [mb.class:na]
	at com.stimulus.archiva.mb.a(MailArchiva:612) [mb.class:na]
	at com.stimulus.archiva.di$f.a(MailArchiva:592) [di$f.class:na]
	at com.stimulus.archiva.di$f.a(MailArchiva:552) [di$f.class:na]
	at com.stimulus.archiva.di$b.b(MailArchiva:616) [di$b.class:na]
	at com.stimulus.archiva.di$b.onSuccess(MailArchiva:602) [di$b.class:na]
	at com.google.api.client.googleapis.batch.BatchUnparsedResponse.parseAndCallback(BatchUnparsedResponse.java:197) [google-api-client-1.20.0.jar:1.20.0]
	at com.google.api.client.googleapis.batch.BatchUnparsedResponse.parseNextResponse(BatchUnparsedResponse.java:155) [google-api-client-1.20.0.jar:1.20.0]
	at com.google.api.client.googleapis.batch.BatchRequest.execute(BatchRequest.java:253) [google-api-client-1.20.0.jar:1.20.0]
	at com.stimulus.archiva.cv.a(MailArchiva:332) [cv.class:na]
	at com.stimulus.archiva.di.a(MailArchiva:124) [di.class:na]
	at com.stimulus.archiva.di.a(MailArchiva:205) [di.class:na]
	at com.stimulus.archiva.di.a(MailArchiva:103) [di.class:na]
	at com.stimulus.archiva.di.call(MailArchiva:58) [di.class:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:262) [na:1.7.0_71]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_71]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_71]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Error during removal of mapping between logical and physical record position.
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OClusterPositionMap.remove(OClusterPositionMap.java:266) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.deleteRecord(OPaginatedCluster.java:724) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	... 64 common frames omitted
Caused by: com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.ONestedRollbackException: Atomic operation was rolled back by internal component
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.endAtomicOperation(OAtomicOperationsManager.java:129) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.endAtomicOperation(ODurableComponent.java:107) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OClusterPositionMap.endAtomicOperation(OClusterPositionMap.java:522) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OClusterPositionMap.remove(OClusterPositionMap.java:261) ~[orientdb-core-2.1-rc5.jar:2.1-rc5]
	... 65 common frames omitted

**Comment by laa** [comment] 2015-07-14 11:07
Hi,
1. Was this database created at 2.1 version ? 
2. If not was restore procedure for the database passed ?

**Comment by jamieb22** [comment] 2015-07-14 11:10
This database was the first db that you fixed.

**Comment by laa** [comment] 2015-07-14 11:22
Ok . Next questions:
1. Is this DB from client where the log is filled with exceptions during data flush ?
2. Do you have wal_backup directory inside of storage ?

**Comment by jamieb22** [comment] 2015-07-14 11:42
1. Is this DB from client where the log is filled with exceptions during data flush ?
Its a different client, however, interesting I see data flush errors in their log too, but they appear to be from when RC4 version was installed
2. I don't see a storage directory at all, but I do see some WAL files in the archiva.db folder.

**Comment by laa** [comment] 2015-07-14 11:51
it may be related issues then, did you received my jars with additional logging ?

**Comment by jamieb22** [comment] 2015-07-14 11:53
Nope. Valentin went on holiday. Perhaps you can send them to me again, and explain what must be done.

**Comment by laa** [comment] 2015-07-14 17:23
Hi, could you do following:
1. Clear all logs.
2. Use this distribution https://www.dropbox.com/s/xs2w59sncv9ln4m/orientdb-community-2.1-SNAPSHOT-distribution.zip?dl=0 .
3. During JVM start use following flag -Dfile.trackFileClose=true.

Please use it for both distributions, as for case when you have only flush exception and for this case too.

Locking forward to see new logs from your side.

**Comment by laa** [comment] 2015-07-15 05:35
This issue is super important so I am looking forward to fix it at once I have enough data from your side.

**Comment by jamieb22** [comment] 2015-07-15 08:18
Ok. Andrey I have updated the customer system, set env, and  log level to DEBUG. I will report back shortly.

**Comment by jamieb22** [comment] 2015-07-15 08:30
Andrey 
Please refer to https://www.dropbox.com/s/h0qnxwx8hz1udce/orient_debug.zip?dl=0
Let me know if it has everything you need.

**Comment by laa** [comment] 2015-07-15 08:51
@jamieb22 that is exception which was caused by file flush exception. Could you send me database I will fix it, to avoid those exceptions and we will wait for file flush exception to check is this cause of one which you reported. What about log from other client, you reported that his log is filled with file flush exception ?

**Comment by jamieb22** [comment] 2015-07-15 09:00
We already sent this one for you to fix. It is a very large db and will take a long time to upload. Do you not have a repair utility I can run on the box directly? I believe it would be handy if there were a OrientDBFix utility in Java that one could run to resolve all kinds of known issues. The other client's log is https://www.dropbox.com/s/uj3hdt80hb89p7r/dvdebug.log.zip?dl=0. It also has a lot of file flush errors.

**Comment by laa** [comment] 2015-07-15 09:45
I can not find "file close tracking", did you run this server with upgraded jar and option -Dfile.trackFileClose=true ?

**Comment by jamieb22** [comment] 2015-07-15 09:51
Definitely yes. I added -Dfile.trackFileClose=true and updated the libs to the snapshot versions.

**Comment by jamieb22** [comment] 2015-07-15 09:56
Here another link to expanded log file https://www.dropbox.com/s/mjtc65ivlhb7bfr/orient_debug2.zip?dl=0

**Comment by laa** [comment] 2015-07-15 09:56
Could you explain me one thing then, in last line of the log which you sent to me 
there is line:

at java.io.RandomAccessFile.length(Native Method) ~[na:1.7.0_75]
	at com.orientechnologies.orient.core.storage.fs.OFileClassic.write(OFileClassic.java:213) ~[orientdb-core-2.1-rc4.jar:2.1-rc4]

but in distributions which I sent file is called not orientdb-core-2.1-rc4.jar but orientdb-core-2.1-SNAPSHOT 

Did you renamed file in distribution ?
I am asking because in new distribution line  com.orientechnologies.orient.core.storage.fs.OFileClassic.write(OFileClassic.java:213) does not cause call of java.io.RandomAccessFile.length(Native Method)  ?

**Comment by jamieb22** [comment] 2015-07-15 09:58
Ok. I forgot to clear the stdout log before the server started. You should be able see where the server starts further down the log.

**Comment by laa** [comment] 2015-07-15 09:59
It the latest line in the log.

~[orientdb-core-2.1-rc4.jar:2.1-rc4]
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:145) ~[orientdb-core-2.1-rc4.jar:2.1-rc4]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2548) ~[orientdb-core-2.1-rc4.jar:2.1-rc4]
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2517) ~[orientdb-core-2.1-rc4.jar:2.1-rc4]
	at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.commit(OrientTransactionalGraph.java:161) ~[orientdb-graphdb-2.1-rc4.jar:2.1-rc4]
	at com.stimulus.archiva.ek.a(MailArchiva:819) ~[ek.class:na]
	at com.stimulus.archiva.fa.a(MailArchiva:128) ~[fa.class:na]
	at com.stimulus.archiva.ns.run(MailArchiva:459) ~[ns.class:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_75]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304) [na:1.7.0_75]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_75]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_75]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_75]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_75]
Caused by: java.util.concurrent.ExecutionException: java.io.IOException: Stream Closed
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) [na:1.7.0_75]
	at java.util.concurrent.FutureTask.get(FutureTask.java:188) [na:1.7.0_75]
	at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.flush(OWOWCache.java:555) ~[orientdb-core-2.1-rc4.jar:2.1-rc4]

what is name of jar of distribution in this log ?

**Comment by jamieb22** [comment] 2015-07-15 10:01
I'll delete the existing log...restart the server.. and try to generate a new log file.. but definitely the patched libs are installed and env variable is set.

**Comment by laa** [comment] 2015-07-15 10:01
patched libs have other names and even do not contain those file line numbers

**Comment by jamieb22** [comment] 2015-07-15 10:04
<img width="817" alt="screen shot 2015-07-15 at 12 03 53 pm" src="https://cloud.githubusercontent.com/assets/6212848/8696063/9d303174-2ae9-11e5-95a2-427557d62bc4.png">

**Comment by laa** [comment] 2015-07-15 10:05
cool, lets wait for the log data then.

**Comment by jamieb22** [comment] 2015-07-15 10:13
https://www.dropbox.com/s/2sk2aw8kaumx2bz/orientdebug3.zip?dl=0

**Comment by laa** [comment] 2015-07-15 10:58
I did not find any flush exceptions,  is there  this log from client where flush exception happens every time ? I want to look at the reason of it and extrapolate to current one.

About restore of broken db, it was taken so much time to restore it because code responsible for data restore was different, now it should take about an hour to restore it, could you send me this db for restore ?

My point is following if we observer flush exceptions in both clients reason of errors during record delete  may be the same, on first client we may easily reproduce this exception lets do following:
1. fix database content.
2. observer log client with updated distribution to find reason of flush exception.
3. fix it.
4. check that db works fine on both clients.

do you see my point ?

**Comment by jamieb22** [comment] 2015-07-15 11:01
The dvdebug.zip file is from a different client to orientdebug1.zip, orientdebug2.zip and orientdebug3.zip

**Comment by jamieb22** [comment] 2015-07-15 11:02
The DB is very large. around 6.78GB.

**Comment by jamieb22** [comment] 2015-07-15 11:03
Why are we getting these critical errors in the first place... its seems there are serious errors in OrientDB

**Comment by jamieb22** [comment] 2015-07-15 11:09
We are really not storing that much information in the DB, so I am curious to know why Orient DB gets so huge.

**Comment by laa** [comment] 2015-07-15 11:10
I have good internet connection it matters of several minutes for me to download such db.
 
If we are right and we get flush exceptions in this client too, then it is simple, we added new page in file tried to flush it but it is already closed, so we can not flush page and when we load it we have null instead of page.

About DB size , let me look at it and I will answer.

**Comment by jamieb22** [comment] 2015-07-15 13:45
Did you receive the DB? Any luck?

**Comment by laa** [comment] 2015-07-16 08:13
I got "Connection refused" message.

**Comment by jamieb22** [comment] 2015-07-16 08:57
I sent you the correct link. Please let me know.

**Comment by laa** [comment] 2015-07-27 14:37
Fixed in rc6 version which will be released today.

**Closed by laa** 2015-07-27 14:37 UTC
Labels: bug, waiting reply

**Comment by jamieb22** [comment] 2015-07-27 18:52
I'm glad these bugs are getting fixed, but you've been telling us each day for the past week that RC6 will be released by end of day. It never happens!
