### ISSUE TITLE
[2.0-M1] Unexpected behavior with delete edge

### ISSUE THREAD

**Issue by Ndrou** [orientechnologies/orientdb#2848] opened 2014-09-26 08:16 UTC
Hi,
I have a unexpected behavior when i try to delete edges with ranges.

![image](https://cloud.githubusercontent.com/assets/7899853/4417474/a52bb266-4554-11e4-8fac-ad04b890a473.png)

When I execute the command : 

```sql
DELETE EDGE TestEdge FROM (SELECT FROM Account Where @rid = '#32:0') TO (Select from City)
```

It deletes the 3 edges !

When I execute this command : 
```sql
DELETE EDGE FROM (SELECT FROM Account Where @rid = '#32:0') TO (Select from City) WHERE @class='TestEdge'
```

It works, it deletes only 1 edge !

**Comment by luigidellaquila** [comment] 2015-03-09 11:35
Hi @Ndrou 

it seems to be already fixed in 2.1 (I cannot reproduce it).
I'm closing this issue, please reopen if needed

**Closed by luigidellaquila** 2015-03-09 11:35 UTC
Labels: bug, In Progress, low priority, sql
