### ISSUE TITLE
OObjectEntitySerializer.multiValueToStream breaks on mixed types

### ISSUE THREAD

**Issue by stebbi** [orientechnologies/orientdb#3063] opened 2014-11-16 14:39 UTC
Description - when using an OObjectDatabaseTx to save instances of registered entity classes with map fields with mixed type values, the entity serializer throws a OSerializationException out of OObjectEntitySerializer.multiValueToStream. This happens because the first value checked gets type EMBEDDED, and a subsequent value needs a type like EMBEDDEDLIST (for example). 

Reproduction - run the unit test in the comment below, with the TypeMixer class in the other comment... 

OrientDB version - 1.7.7, 1.7.9, 2.0-M2

Custom settings - see the OObjectEntitySerializerTest.setup method. 

Expected output - new database object, no exception.

**Comment by busbaby** [comment] 2016-08-11 02:19
Hi There. Is there a work around for this? This bug is biting me. Any help from the dev team would be greatly appreciated!

**Comment by busbaby** [comment] 2016-08-12 12:50
According to [http://orientdb.com/docs/2.2/Types.html](url) type OType.ANY is defined as:

> Not determinated type, used to specify Collections of mixed type, and null

Shouldn't we be able to use this to store a Map of mixed value types? I tried it and it still fails:
<pre><code>
        OObjectDatabaseTx objectDatabaseTx = new OObjectDatabaseTx(databaseDocumentTx);
        objectDatabaseTx.getEntityManager().registerEntityClass(TypeMixer.class);
        OClass oClass = objectDatabaseTx.getMetadata().getSchema().getClass(TypeMixer.class);
        oClass.createProperty("map", OType.ANY);
        //oClass.createProperty("map", OType.ANY, OType.ANY); //<-- DOESN'T WORK EITHER
        //oClass.createProperty("map", OType.EMBEDDEDMAP, OType.ANY); //<-- DOESN'T WORK EITHER

        Map map = new HashMap();
        map.put("aString", "v");
        map.put("aList", new ArrayList() {{
            add("v");
        }});
        TypeMixer foo = new TypeMixer(map);
        foo = objectDatabaseTx.save(foo); //<-- EXCEPTION THROW HERE
</code></pre>
Exception:
<pre><code>
Caused by: java.lang.IllegalArgumentException: Type ANY must be a multi value type (collection or map)
	at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.multiValueToStream(OObjectEntitySerializer.java:1377)
	at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.typeToStream(OObjectEntitySerializer.java:805)
	at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.toStream(OObjectEntitySerializer.java:1216)
	at com.orientechnologies.orient.object.enhancement.OObjectEntitySerializer.serializeObject(OObjectEntitySerializer.java:144)
	... 9 more
</code></pre>
**Please** provide help with a solution for storing a POJO with a Map<String, Object> field using the OObjectDatabaseTx API. This is currently a show-stopper for our team to migrate to OrientDB.

**Comment by stebbi** [comment] 2016-08-14 06:30
I'm using ODatabaseDocumentTx to work around this bug, don't know if that is helpful for you. I don't want to create struct-like model classes for my types anyways, so this was actually nice for me in the end. I don't think I would go back to OObjectDatabaseTx even if the bug were fixed. (Caveat - I may have forgotten a lot of details here...)

**Comment by stebbi** [comment] 2016-08-14 06:31
Argh - I had no intent to close it, fat fingers. Sorry.

**Comment by tglman** [comment] 2017-02-27 17:38
hi @stebbi,

I fixed some issues on multivalue type recently in the Object database layer, this should be fixed as well, the fix will be released with the 2.2.19.

Regards

**Comment by tglman** [comment] 2017-12-29 13:39
Hi @stebbi ,

This was released long time ago, closing

Regards

**Closed by tglman** 2017-12-29 13:39 UTC
Labels: bug
