### ISSUE TITLE
how to clear the custom fields

### ISSUE THREAD

**Issue by Ivanov-Yuriy** [orientechnologies/orientdb#6562] opened 2016-08-15 12:03 UTC
Hi.
I started use OrientDB 2.2.6
but I can't clear custom fields

for it I use command "alter class myClass custom clear" 

this command worked in OrientDB 2.1.19

**Comment by luigidellaquila** [comment] 2016-08-16 07:52
Hi @Ivanov-Yuriy 

It seems to be a regression, I'll fix it in short 

Thanks

Luigi

**Comment by Ivanov-Yuriy** [comment] 2016-08-16 08:41
command "custom clear" works in properties
"alter property test.myProp custom clear" // OK

**Comment by luigidellaquila** [comment] 2016-08-16 09:23
Hi @Ivanov-Yuriy 

I just pushed a fix on 2.2.x 

Thanks

Luigi

**Closed by luigidellaquila** 2016-08-16 09:23 UTC
Labels: bug
