### ISSUE TITLE
Lucene index with multiple fields not returning any results

### ISSUE THREAD

**Issue by robfrank** [orientechnologies/orientdb#5184] opened 2015-10-21 07:56 UTC
_From @Ziink on October 15, 2015 22:50_

orientdb-community-2.1.4 and probably orientdb-community-2.1.3. Works fine in orientdb-community-2.1.2

```sql
create class Item extends V
create property Item.title string
create property Item.summary string
create index Item.i_lucene on Item(title, summary) fulltext engine lucene
insert into Item set title = 'test', summary = 'this is a test'

select * from Item where title lucene 'test'
select * from Item where [title, summary] lucene 'test'
```

Neither of the select statements return a result.

_Copied from original issue: orientechnologies/orientdb-lucene#76_

**Comment by wcraigtrader** [comment] 2015-10-21 20:08
Doesn't work in Orient 2.0.10.

**Comment by wcraigtrader** [comment] 2015-10-21 20:15
I'm seeing a variant of this problem:

1. `select * from Item where title lucene 'test'` returns results.
1. `select * from Item where [title, summary] lucene 'test'` returns no results.
1. `select * from Item where summary lucene 'test'` returns no results.

This is consist in OrientDB Community 2.1.2, 2.1.4, and 2.0.10.

**Comment by Ndrou** [comment] 2015-10-26 10:33
Same bug. When will the next orientdb hotfix be released ? Our development database is unusable...

**Comment by maggiolo00** [comment] 2015-10-31 01:40
@Ziink i tried your script with 2.1.5 and worked.

Can you tell me how to replicate the issue?

There is also a test that cover multi field
https://github.com/orientechnologies/orientdb/blob/2.1.x/lucene/src/test/java/com/orientechnologies/lucene/test/LuceneMultiFieldTest.java

**Comment by Ziink** [comment] 2015-10-31 02:01
The earlier set of steps does indeed work now. However, the following which used to work in 2.1.2 still doesn't work. It might actually be a different bug, in which case I can open a separate issue.

```sql
create class ItemBase extends V, OTriggered abstract
create class Item extends ItemBase
create property Item.title string
create property Item.summary string
create index Item.i_lucene on Item(title, summary) fulltext engine lucene
insert into Item set title = 'test', summary = 'this is a test'

select * from Item where title lucene 'test'
select * from Item where [title, summary] lucene 'test'
```

Note that the 'indexed' class now extends an abstract class. In my case, the abstract class is the one that has the properties and is indexed, and that too doesn't work.

**Comment by maggiolo00** [comment] 2015-11-01 14:08
@Zlink 
can you try with 2.1.5?
i've tried this in 2.1.5 and it worked.
There was a bug indeed in 2.1.4 with inheritance but it was fixed

**Comment by smolinari** [comment] 2015-11-01 14:43
@maggiolo00 you didn't mention @Ziink correctly. Just an @ mention to help. :smile: 

Scott

**Comment by Ziink** [comment] 2015-11-01 17:02
It works with a fresh database. I had indeed tried it with 2.1.5 and it hadn't worked. Let me see if I can figure out why it hadn't worked. Please don't close this yet and I'll follow up within a day whether or not I could reproduce the problem.

However, I entered another lucene bug [5257](https://github.com/orientechnologies/orientdb/issues/5257) that is blocking me from upgrading from 2.1.2

**Comment by maggiolo00** [comment] 2015-11-01 17:44
I will not close this.
Let me know

**Comment by Ziink** [comment] 2015-11-01 20:18
Tried again with the earlier setup but couldn't reproduce it. Please go ahead and close. Thanks.

**Closed** 2015-11-01 20:49 UTC
Labels: bug
