### ISSUE TITLE
Nice to have feature: support RAND() function

### ISSUE THREAD

**Issue by studiodev** [orientechnologies/orientdb#1946] opened 2014-01-09 18:35 UTC
Hello,

What do you think about supporting the RAND function? 
It's absolutely not critical, just a nice to have feature, especially for random requests.

Select a random vertex: 
`SELECT FROM X ORDER BY RAND() LIMIT 1`

Select randomly one vertex from two:
`SELECT FROM X WHERE RAND() > 0.5`

Generate a random value:
`SELECT RAND()*100`

**Comment by PaulWoodIII** [comment] 2015-01-06 11:05
I agree, I was surprised when I didn't find this feature

**Comment by lvca** [comment] 2015-01-06 18:22
Very easy to implement, unfortunately we're in RC stage, so we can't add new features now. This will go for 2.1

**Comment by tsouza** [comment] 2015-04-30 15:12
I'm currently evaluating OrientDB and this feature is a blocker to me. Any chance this could make into v2.1?

@Ivca if it's very easy to implement, maybe you could could give me a hint on how to do it and I would do it myself.

Cheers

**Comment by fabriziofortino** [comment] 2015-04-30 15:20
@tsouza I think this could be considered a duplicate of #2573 I am currently trying to bind all the Java Math methods into sql functions. I think I will create a PR within the weekend.

**Comment by tsouza** [comment] 2015-04-30 15:28
@fabriziofortino extending orientdb function is a great feature! But what I am really looking for is a way to randomly select an element. 

Going into details, what I am looking for is a way to randomly select an element from an index with a key range constraint

**Comment by lvca** [comment] 2015-04-30 15:28
@fabriziofortino I really love you ;-)

**Comment by StarpTech** [comment] 2015-06-18 18:18
Status? Does exist a way to select random records?

**Comment by karolmie1** [comment] 2017-01-15 09:52
In the meantime, what is the suggested way to get random vertex of specific class?

**Comment by Rucchao** [comment] 2017-02-03 15:08
What is the current situation? I also need this feature too. Thanks !

**Comment by andreafalzetti** [comment] 2017-04-06 13:03
Any chance we get the RAND() method?

**Comment by lvca** [comment] 2017-08-04 14:12
Already available by using math_rand() function and ordering by it. Example:

```
select a, b, math_rand() as c from X order by c
```

**Comment by luigidellaquila** [comment] 2017-08-07 07:30
The function name is math_random()

**Closed by luigidellaquila** 2017-08-07 07:30 UTC
Labels: enhancement

**Comment by DarkKnight1992** [comment] 2017-10-20 00:09
math_random() or math_rand() doesn't work my suggestion to everybody just make a simple function for generating random number and you are good to go

**Comment by lvca** [comment] 2017-10-23 23:07
@DarkKnight1992 what do you mean with doesn't work?

**Comment by DarkKnight1992** [comment] 2017-11-21 20:39
@Ivca sorry for the late reply i didn't saw your comment all this time.

but when i said it doesn't work i mean when i tried this it gives me an error all the time 

> No function with name 'math_random', available names are : [date,encode,dijkstra,traversedelement,decode,bothv,uuid,GETCITYFORESTA,mode,sysdate,GETITEM,LAST_30_DAYS,WHERECOND,shortestpath,UPEVT,symmetricdifference,traversedvertex,if,bothe,unionall,JOINSTR,last,in,coalesce,count,format,concat,list,both,sequence,gremlin,eval,percentile,median,difference,decimal,astar,distance,document,distinct,CONVERTTOARR,sum,out,CREATE_RANDOM,avg,min,traversededge,ifnull,stddev,outv,map,ine,set,oute,intersect,max,UPCOMINGEVENTS,CHECKSTR,label,inv,abs,variance,FNGEODISTANCE,first]
>	DB name="iconoland"
![screenshot 17](https://user-images.githubusercontent.com/15063261/33095529-f79216e6-cf29-11e7-9bf8-5151a546cfb4.png)

**Comment by luigidellaquila** [comment] 2017-11-22 08:41
Hi @julien-lafont 

I guess we missed a little point here... math_random() was implemented in v 3.0, I guess you are trying with v 2.2.x

Thanks

Luigi

**Comment by DarkKnight1992** [comment] 2017-11-22 09:36
Hi @luigidellaquila,

Its nice to know this feature will be available in 3.0 but considering the fact that 3.0 is not production ready yet we can't use this which is extremely important to us before launch. Any estimates when will be released ?

**Comment by luigidellaquila** [comment] 2017-11-22 09:45
Hi @DarkKnight1992 

if you need it in v 2.2, you can easily implement it in javascript:

<img width="667" alt="schermata 2017-11-22 alle 10 44 28" src="https://user-images.githubusercontent.com/459289/33120366-25bd92dc-cf72-11e7-915b-9b64de9ca888.png">

and use it like follows:

```
select expand(rid) from (
   select @rid, random() as c from v order by c
)
```

V 3.0 will be released between the end of this year and the begin of next year

Thanks

Luiig

**Comment by DarkKnight1992** [comment] 2017-11-22 11:03
i tired something similar making a random function but that was taking too long for the query to work.  
![screenshot 18](https://user-images.githubusercontent.com/15063261/33124398-ce3d7b68-cfa2-11e7-88be-f56ac9457a55.png)

**Comment by luigidellaquila** [comment] 2017-11-22 11:14
Well, that's pretty obvious, the query has to apply a random function for all the records in the target and then do a sorting, on a big class it will take time.

If you need a single random record (or a small set of records) maybe you can write a function that:
- gets the maximum clusterId/s for your target
- generates a random number
- loads the record by RID (generated as `<clusterId>:<randomNumber>`
- retries in case the record does not exist

For sure this will be much more efficient

thanks

Luigi

**Comment by DarkKnight1992** [comment] 2017-11-22 11:27
I understand but the whole purpose of random function is kinda lost like this since the database will keep growing as of now currently this was applied for class with 75k records and will keep growing exponentially with time.
yeah that will be more efficient for sure but this approach has also one downside only the selected data will be randomize which again looses the whole idea of randomizing records.
