### ISSUE TITLE
Prepared query not working with more than one unnamed parameter

### ISSUE THREAD

**Issue by mohamnag** [orientechnologies/orientdb#5325] opened 2015-11-16 16:02 UTC
I have following DB structure:
product <--- reservationHasProduct ----- reservation ----- reservationHasUser ---> user

I'm trying to get the reservations for a given pair of user and product (reservations that connect given user and product).

following query works perfectly when ids are hardcoded:
```java
DatabaseFactory.getGraph().command(new OSQLSynchQuery<>(
    "SELECT FROM (" +
        "  SELECT EXPAND( IN('reservationHasUser') ) FROM `user` WHERE @rid=#172:184" +
        ") " +
        "WHERE ( " +
        "  #49:199 IN OUT('reservationHasProduct') " +
        ")"
)).execute();
```
above query returns 1 result which is the expected number.

however due to the fact that ids are dynamic and mostly provided by clients, I tried to rewrite above query as follows:
```java
DatabaseFactory.getGraph().command(new OSQLSynchQuery<>(
    "SELECT FROM (" +
        "  SELECT EXPAND( IN('reservationHasUser') ) FROM `user` WHERE @rid=?" +
        ") " +
        "WHERE ( " +
        "  ? IN OUT('reservationHasProduct') " +
        ")"
)).execute("#172:184", "#49:199");
```
which simply gives me empty result! The problem persists as long as BOTH ids are provided as place holders, however if I hardcode one and leave the other as placeholder, then the query works.

I'm using OrientDB v2.1.5 on both client and server.

**Comment by mohamnag** [comment] 2015-11-16 16:10
PS: replacing those placeholders with named parameters fixes the problem

**Comment by luigidellaquila** [comment] 2016-05-24 15:18
Hi @mohamnag 

I think the problem is in how you are passing the parameters. If you pass them as strings, the query will be resolved as:

```
SELECT FROM (
   SELECT EXPAND( IN('reservationHasUser') ) FROM `user` WHERE @rid = "#172:184"
   ) 
    WHERE (
       "#49:199" IN OUT('reservationHasProduct')
      )
```
(see the quotes).

Could you please try to rewrite it as follows:

```
DatabaseFactory.getGraph().command(new OSQLSynchQuery<>(
    "SELECT FROM (" +
        "  SELECT EXPAND( IN('reservationHasUser') ) FROM `user` WHERE @rid=?" +
        ") " +
        "WHERE ( " +
        "  ? IN OUT('reservationHasProduct') " +
        ")"
)).execute(new ORecordId(172, 184), new ORecordId(49, 199));
```


Thanks

Luigi

**Comment by mohamnag** [comment] 2016-05-25 07:23
would love to test it but don't have the code anymore as we moved on to Postgres.

**Comment by luigidellaquila** [comment] 2016-05-25 08:01
Ok, thanks @mohamnag 
I did some internal tests (together with existing unit tests) and it seems to work fine. I'm closing this issue, please reopen if you still see similar problems

Thanks

Luigi

**Closed by luigidellaquila** 2016-05-25 08:01 UTC
Labels: bug
