### ISSUE TITLE
Couldn't insert N number of edges in orientDB

### ISSUE THREAD

**Issue by naseem91** [orientechnologies/orientdb#9392] opened 2020-09-15 10:16 UTC
## Expected behavior  
add N of edges

## Actual behavior  
````
INFO: Windows OS is detected, 262144 limit of open files will be set for the disk cache.
Sep 14, 2020 10:06:56 AM com.orientechnologies.common.log.OLogManager log
SEVERE: Error on transaction commit `2E3CD732`
com.orientechnologies.orient.core.exception.OStorageException: Exception during execution of component operation inside of storage healthEmptyDB
    DB name="healthEmptyDB"
    DB name="healthEmptyDB"
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
    at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleException(OChannelBinaryAsynchClient.java:357)
    at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:305)
    at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:327)
    at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:211)
    at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:169)
    at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:2221)
    at com.orientechnologies.orient.client.remote.OStorageRemote.lambda$networkOperationRetryTimeout$2(OStorageRemote.java:385)
    at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:447)
    at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperationRetryTimeout(OStorageRemote.java:365)
    at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperationNoRetry(OStorageRemote.java:400)
    at com.orientechnologies.orient.client.remote.OStorageRemote.commit(OStorageRemote.java:1304)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.internalCommit(ODatabaseDocumentAbstract.java:2466)
    at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:602)
    at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:106)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:1984)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:1954)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:741)
    at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.commit(OrientTransactionalGraph.java:183)
    at graph.orient.utils.InsertNEdges.commitGraph(InsertNEdges.java:73)
    at graph.orient.utils.InsertNEdges.main(InsertNEdges.java:66)
    Suppressed: com.orientechnologies.orient.core.exception.OStorageException: Exception during execution of component operation inside of storage healthEmptyDB
    DB name="healthEmptyDB"
        at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideComponentOperation(OAtomicOperationsManager.java:218)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideComponentOperation(OAtomicOperationsManager.java:205)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.executeInsideComponentOperation(ODurableComponent.java:102)
        at com.orientechnologies.orient.core.storage.index.sbtreebonsai.local.OSBTreeBonsaiLocal.create(OSBTreeBonsaiLocal.java:109)
        at com.orientechnologies.orient.core.storage.ridbag.sbtree.OSBTreeCollectionManagerShared.createEdgeTree(OSBTreeCollectionManagerShared.java:139)
        at com.orientechnologies.orient.core.storage.ridbag.sbtree.OSBTreeCollectionManagerShared.createEdgeTree(OSBTreeCollectionManagerShared.java:47)
        at com.orientechnologies.orient.core.storage.ridbag.sbtree.OSBTreeCollectionManagerAbstract.createSBTree(OSBTreeCollectionManagerAbstract.java:175)
        at com.orientechnologies.orient.core.storage.ridbag.sbtree.OSBTreeCollectionManagerShared.createSBTree(OSBTreeCollectionManagerShared.java:197)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.HelperClasses.writeSBTreeRidbag(HelperClasses.java:411)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.HelperClasses.writeRidBag(HelperClasses.java:356)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV1.writeRidBag(ORecordSerializerBinaryV1.java:731)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV1.serializeValue(ORecordSerializerBinaryV1.java:1020)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV1.serializeValues(ORecordSerializerBinaryV1.java:404)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV1.serializeDocument(ORecordSerializerBinaryV1.java:462)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV1.serialize(ORecordSerializerBinaryV1.java:483)
        at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:132)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitEntry(OAbstractPaginatedStorage.java:6012)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:2427)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:2241)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.internalCommit(ODatabaseDocumentAbstract.java:2466)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:602)
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:106)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:1984)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.commit(ODatabaseDocumentAbstract.java:1954)
        at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeCommit38(OConnectionBinaryExecutor.java:1698)
        at com.orientechnologies.orient.client.remote.message.OCommit38Request.execute(OCommit38Request.java:139)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:354)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:238)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:67)
    Caused by: com.orientechnologies.orient.core.exception.OStorageException: Ridbag component with name collections_22.sbc does not exist
    DB name="healthEmptyDB"
        at com.orientechnologies.orient.core.storage.index.sbtreebonsai.local.OSBTreeBonsaiLocal.lambda$create$1(OSBTreeBonsaiLocal.java:121)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideComponentOperation(OAtomicOperationsManager.java:213)
        ... 28 more
    [CIRCULAR REFERENCE:com.orientechnologies.orient.core.exception.OStorageException: Ridbag component with name collections_22.sbc does not exist
    DB name="healthEmptyDB"]

com.orientechnologies.orient.core.exception.OStorageException: Exception during execution of component operation inside of storage healthEmptyDB
````

## Steps to reproduce  
<add here>  
<An SQL script to reproduce the problem or a JUnit test case will increase **A LOT** the chance to have a quick fix>

**Comment by andrii0lomakin** [comment] 2020-09-15 10:24
Hi @naseem91 . I will provide a fix in a couple of weeks.

**Comment by naseem91** [comment] 2020-09-15 10:40
thanks

**Comment by andrii0lomakin** [comment] 2020-10-19 14:58
Hi @naseem91 to verify that we provided the fix I need test case from your side, because your description is quite general and I had to guess what problem did you encounter. Could you provide such test case.

**Comment by lvca** [comment] 2020-12-21 14:50
No answer, closing the issue for now. In case, please comment on this very issue.

**Closed as completed by lvca** 2020-12-21 14:50 UTC
Labels: bug, invalid

**Comment by mcgarnagle** [comment] 2021-05-06 04:25
Hi Luca,

We are seeing this issue in our environment at the moment. I have a database where I cannot add an edge between two vertices as I get the same error. I can provide the database with a description of what I am doing to get the error. Is it possible to get this looked at again?


OrientDB Version: 3.1.2 (under docker on linux and native on MacOs)

Java Version: 8

OS: Occurred on both MacOS and Amazon Linux


Expected behavior

add edge between two vertices

Actual Behavior

Exception `494405C1` in storage `plocal:/Users/rickpezzimenti/develop/orientdb/orientdb-tp3-3.1.2/databases/Cosight_Busines`: 3.1.2 - Veloce (build 8b6ef394ce7b45017e84a65efb9ce7534c56aa8e, branch 3.1.x)
com.orientechnologies.orient.core.exception.OStorageException: Exception during execution of component operation inside component collections_16.sbc in storage Cosight_Busines
	DB name="Cosight_Busines"
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideComponentOperation(OAtomicOperationsManager.java:221)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideComponentOperation(OAtomicOperationsManager.java:206)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.executeInsideComponentOperation(ODurableComponent.java:102)
	at com.orientechnologies.orient.core.storage.index.sbtreebonsai.local.OSBTreeBonsaiLocal.create(OSBTreeBonsaiLocal.java:109)
	at com.orientechnologies.orient.core.storage.ridbag.sbtree.OSBTreeCollectionManagerShared.createEdgeTree(OSBTreeCollectionManagerShared.java:139)
	at com.orientechnologies.orient.core.storage.ridbag.sbtree.OSBTreeCollectionManagerShared.createEdgeTree(OSBTreeCollectionManagerShared.java:47)
	at com.orientechnologies.orient.core.storage.ridbag.sbtree.OSBTreeCollectionManagerAbstract.createSBTree(OSBTreeCollectionManagerAbstract.java:175)
	at com.orientechnologies.orient.core.storage.ridbag.sbtree.OSBTreeCollectionManagerShared.createSBTree(OSBTreeCollectionManagerShared.java:197)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.HelperClasses.writeSBTreeRidbag(HelperClasses.java:411)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.HelperClasses.writeRidBag(HelperClasses.java:356)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV1.writeRidBag(ORecordSerializerBinaryV1.java:731)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV1.serializeValue(ORecordSerializerBinaryV1.java:1020)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV1.serializeValues(ORecordSerializerBinaryV1.java:404)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV1.serializeDocument(ORecordSerializerBinaryV1.java:462)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV1.serialize(ORecordSerializerBinaryV1.java:483)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.toStream(ORecordSerializerBinary.java:132)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitEntry(OAbstractPaginatedStorage.java:6143)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:2444)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:2257)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.internalCommit(ODatabaseDocumentAbstract.java:2466)
	at com.orientechnologies.orient.core.storage.impl.local.OMicroTransaction.doCommit(OMicroTransaction.java:357)
	at com.orientechnologies.orient.core.storage.impl.local.OMicroTransaction.commit(OMicroTransaction.java:173)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.endMicroTransaction(ODatabaseDocumentEmbedded.java:816)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.saveAll(ODatabaseDocumentEmbedded.java:1248)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:208)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.saveInternal(ODatabaseDocumentAbstract.java:1854)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:1802)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:1685)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentAbstract.save(ODatabaseDocumentAbstract.java:135)
	at com.orientechnologies.orient.core.sql.executor.SaveElementStep$1.next(SaveElementStep.java:37)
	at com.orientechnologies.orient.core.sql.executor.OInsertExecutionPlan.executeInternal(OInsertExecutionPlan.java:46)
	at com.orientechnologies.orient.core.sql.parser.OCreateEdgeStatement.execute(OCreateEdgeStatement.java:59)
	at com.orientechnologies.orient.core.sql.parser.OStatement.execute(OStatement.java:72)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.command(ODatabaseDocumentEmbedded.java:586)
	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.executeStatement(OServerCommandPostCommand.java:200)
	at com.orientechnologies.tinkerpop.command.OServerCommandPostCommandGremlin.executeStatement(OServerCommandPostCommandGremlin.java:47)
	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:104)
	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommandGraph.execute(OServerCommandPostCommandGraph.java:34)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:253)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:811)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:67)
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Ridbag component with name collections_16.sbc does not exist
	DB name="Cosight_Busines"
	at com.orientechnologies.orient.core.storage.index.sbtreebonsai.local.OSBTreeBonsaiLocal.lambda$create$1(OSBTreeBonsaiLocal.java:121)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideComponentOperation(OAtomicOperationsManager.java:214)
	... 40 more

**Comment by mcgarnagle** [comment] 2021-05-07 03:44
As a workaround to resolve this issue, we ended up doing the following

Exported the corrupted database from OrientDB studio.
Deleted the database
Created a new database with the same name
Started the console and connected to the database using plocal 
Ran an import using the following command
_import database ../../Cosight_Busines.gz -deleteRIDMapping=false -rebuildIndexes=true -merge=false -migrateLinks=true -preserveClusterIDs=true_

The database was then fully operational again, allowing us to add edges
