### ISSUE TITLE
Query error only on distributed

### ISSUE THREAD

**Issue by thiagopm** [orientechnologies/orientdb#4098] opened 2015-05-06 19:34 UTC
Hi Guys, This error happens only when is running on distributed server: 
sql.SELECT UserId FROM User WHERE OrganizationId = 1
server.java.lang.ClassCastException: com.orientechnologies.orient.server.distributed.ODistributedStorage cannot be cast to com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage

Thanks

**Comment by tglman** [comment] 2015-09-02 15:26
this issue is a duplicate of this: https://github.com/orientechnologies/orientdb/issues/4177, closed few months ago.

**Closed by tglman** 2015-09-02 15:26 UTC
Labels: bug
