### ISSUE TITLE
Upgrade from Orient 2.2.6 to 2.2.7

### ISSUE THREAD

**Issue by lucevers** [orientechnologies/orientdb#6560] opened 2016-08-14 10:34 UTC
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[ ] - .rc1[ ] .beta2[ ] .beta1[ ]
  V 2.2.7
  ## Operating System
- [X ] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 
  java 8
## Expected behavior and actual behavior

   Upgrade database to a new stable version.
   Normal behavior should be no impact on the databases .
  Problem:   If the database is running in distributed mode , the issues: 
     https://github.com/orientechnologies/orientdb/issues/6319
     And
     https://github.com/orientechnologies/orientdb/issues/6491

```
 Are not solved!  
A single Orient server has no problems.
```
## Steps to reproduce the problem

   1) Install Orient 2.2.7
   2) copy databases from version 2.2.6 to  the version 2.2.7
   3) start as single server (./server.sh)  , change databases.
   4) start Orient 2.2.7 on a second server and put the servers in distributed mode.
   5) removing classes is not possible the same for inserting data.

**Comment by lvca** [comment] 2016-09-23 18:55
@lucevers I don't understand the problem. Could you please elaborate it?

**Comment by lucevers** [comment] 2016-10-12 08:49
Ivca, If you do the steps 1->4 you cannot insert data in the database.
I can not make it easier.
 
1) Install Orient 2.2.7
2) copy existing databases from version 2.2.6 to the version 2.2.7
3) start as single server (./server.sh) , change databases.
4) start Orient 2.2.7 on a second server and put the servers in distributed mode.

 I shall start the 4 steps again for version 2.2.11 .

**Comment by lvca** [comment] 2017-06-09 10:02
Closing because duplicate of https://github.com/orientechnologies/orientdb/issues/7480.

**Closed by lvca** 2017-06-09 10:02 UTC
Labels: question
