### ISSUE TITLE
new OrientGraph java.lang.OutOfMemoryError: Direct buffer memory

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#7656] opened 2017-08-15 08:36 UTC
## Expected behavior  
Java params -Xmx1024m -Xms256m
storage.diskCache.bufferSize=128
graph = new OrientGraph(settings.getUrl(), settings.getLogin(), settings.getPassword());
No error...

## Actual behavior  
2017-08-15 10:36:34 s.c.s.a.d.b.BluePrintDatabaseUtil [ERROR] orient cannot restore WAL file:Direct buffer memory
java.lang.OutOfMemoryError: Direct buffer memory
	at java.nio.Bits.reserveMemory(Bits.java:658)
	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)
	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
	at com.orientechnologies.common.directmemory.OByteBufferPool.allocateBuffer(OByteBufferPool.java:328)
	at com.orientechnologies.common.directmemory.OByteBufferPool.acquireDirect(OByteBufferPool.java:279)
	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.load(OWOWCache.java:769)
	at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.updateCache(O2QCache.java:1149)
	at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.doLoad(O2QCache.java:347)
	at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.allocateNewPage(O2QCache.java:398)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperation.commitChanges(OAtomicOperation.java:434)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.endAtomicOperation(OAtomicOperationsManager.java:468)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.endAtomicOperation(OAtomicOperationsManager.java:412)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.endAtomicOperation(ODurableComponent.java:116)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.create(OPaginatedCluster.java:195)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.addClusterInternal(OAbstractPaginatedStorage.java:4136)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doAddCluster(OAbstractPaginatedStorage.java:4117)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.create(OAbstractPaginatedStorage.java:459)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.create(OLocalPaginatedStorage.java:127)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.create(ODatabaseDocumentTx.java:438)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.create(ODatabaseDocumentTx.java:398)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.openOrCreate(OrientBaseGraph.java:1980)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.<init>(OrientBaseGraph.java:162)
	at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.<init>(OrientTransactionalGraph.java:102)
	at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.<init>(OrientTransactionalGraph.java:98)
	at com.tinkerpop.blueprints.impls.orient.OrientGraph.<init>(OrientGraph.java:103)
	at ..

Thereafter, try to reconnect to db... 

2017-08-15 10:37:46 s.c.s.a.d.Services [ERROR] error:stop:com.orientechnologies.orient.core.exception.ODatabaseException: Database created with orientdb version not supported anymore, use export+import to migrate the database
	DB name="archiva$sueZ0E_CWnbNnsPv6otyw_BztqxW2eiQM6uYfQ9B7OU"
com.orientechnologies.orient.core.exception.ODatabaseException: Database created with orientdb version not supported anymore, use export+import to migrate the database
	DB name="archiva$sueZ0E_CWnbNnsPv6otyw_BztqxW2eiQM6uYfQ9B7OU"
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.initAtFirstOpen(ODatabaseDocumentTx.java:3163)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:270)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.openOrCreate(OrientBaseGraph.java:1978)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.<init>(OrientBaseGraph.java:162)
	at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.<init>(OrientTransactionalGraph.java:102)
	at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.<init>(OrientTransactionalGraph.java:98)
	at com.tinkerpop.blueprints.impls.orient.OrientGraph.<init>(OrientGraph.java:103)
	at ..

Restart server. try to reconnect with .24
com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/Library/Application Support/MailArchiva/sueZ0E_CWnbNnsPv6otyw_BztqxW2eiQM6uYfQ9B7OU/database/archiva$sueZ0E_CWnbNnsPv6otyw_BztqxW2eiQM6uYfQ9B7OU' with mode=rw
	DB name="archiva$sueZ0E_CWnbNnsPv6otyw_BztqxW2eiQM6uYfQ9B7OU"
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:299)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:258)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.openOrCreate(OrientBaseGraph.java:1978)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.<init>(OrientBaseGraph.java:162)
	at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.<init>(OrientTransactionalGraph.java:102)
	at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.<init>(OrientTransactionalGraph.java:98)
	at com.tinkerpop.blueprints.impls.orient.OrientGraph.<init>(OrientGraph.java:103)
	at ..
Caused by: com.orientechnologies.common.io.OIOException: You cannot access outside the file size (0 bytes). You have requested portion 0-4 bytes. File: File: database.ocf os-size=1024, stored=0
	at com.orientechnologies.orient.core.storage.fs.OFileClassic.checkRegions(OFileClassic.java:517)
	at com.orientechnologies.orient.core.storage.fs.OFileClassic.readInt(OFileClassic.java:250)
	at com.orientechnologies.orient.core.storage.impl.local.OStorageConfigurationSegment.load(OStorageConfigurationSegment.java:103)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:240)
	... 14 common frames omitted

It should not try to allocate more direct memory than is available. Also, why is it now, showing a database compatibility / acess errors? 

## Steps to reproduce  

See above

**Comment by laa** [comment] 2017-08-15 08:38
Already fixed in 2.2.26 in issue https://github.com/orientechnologies/orientdb/issues/7627 explanation is also provided there.

**Comment by laa** [comment] 2017-08-15 08:41
I suppose that it shows compatibility error because the connection to the database was not fully initialized so it relies on wrong data.

**Comment by jamieb22** [comment] 2017-08-15 08:47
Yes, but, the database should never get into this state in the first place. We are creating a new database from scratch, if it runs out of direct memory, it should roll back the changes, such that the db can be created again. Also, why does Orient run out of memory in the first place? I dont understand?! Surely, Orient can detect the amount of direct memory available, and then resize the cache accordingly. Also, I have specified a small size for the cache, but it runs of out of memory in any case.

**Comment by laa** [comment] 2017-08-15 08:51
@jamieb22 As I wrote above explanation of issue is provided in https://github.com/orientechnologies/orientdb/issues/7627#issuecomment-322227242 .  Could you point me what is unclear there?

**Comment by jamieb22** [comment] 2017-08-15 09:00
Even if in .26 you are now detecting direct memory size and  adjusting cache size, the fact that orient db gets into an indeterminate state due to faild memory allocation is a surely bug.  It surely roll back changes?
--

**Comment by jamieb22** [comment] 2017-08-15 09:21
Andrey.. I just upgraded to latest .26 snapshot, and the direct memory error is still present? Any ideas on how I can resolve this? Do I need to downgrade?

**Comment by jamieb22** [comment] 2017-08-15 09:55
Interestingly .. when I call...

> OGlobalConfiguration.DISK_CACHE_SIZE.setValue(128L);

instead of..

> System.setProperty("storage.diskCache.bufferSize",Long.toString(128L));

It works.

**Comment by laa** [comment] 2017-08-15 10:02
@jamieb22 did you provide system properties by calling `System.setProperty("storage.diskCache.bufferSize",Long.toString(128L));` inside of Java code or that is parameter of application when you start it ?

**Comment by jamieb22** [comment] 2017-08-15 10:25
Yes, its in a static initializer. It used to work, but no longer works.

**Comment by laa** [comment] 2017-08-17 06:50
@jamieb22 We expect that system properties will be provided during application startup if some of them worked it just coincidence. Could you send me to log data which are printed when the application is started first 10 minutes will be enough? For latest 2.2.26 snapshot. Answering your question we always roll back intermediate txs because they literally not written on disk yet.

**Comment by laa** [comment] 2017-08-23 10:23
@jamieb22 could you try this build https://drive.google.com/file/d/0B2oZq2xVp841VWlFSkFMRHhpeFU/view?usp=sharing ?

**Comment by laa** [comment] 2017-08-30 09:47
@jamieb22 could you try this build and check that issue is gone?

**Comment by laa** [comment] 2017-09-01 13:22
@jamieb22 could you try this build and check that issue is gone?

**Comment by laa** [comment] 2017-09-02 10:47
Close issue because of no reply. If you reproduce given issue and have information which is requested in issue feel free to reopen it.

**Closed by laa** 2017-09-02 10:47 UTC
Labels: bug, storage team
