### ISSUE TITLE
maximum allowed chunk length error on remote access with default settings

### ISSUE THREAD

**Issue by grexe** [orientechnologies/orientdb#6311] opened 2016-06-16 12:46 UTC
When accessing OrientDB 2.2.2 remote and creating an empty database, with default settings, I get this error:
``` 
com.orientechnologies.common.io.OIOException: Impossible to read a chunk of length:1949459553 max allowed chunk length:16777216 see NETWORK_BINARY_MAX_CONTENT_LENGTH settings 
        at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinary.readBytes(OChannelBinary.java:157)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.solveSession(ONetworkProtocolBinary.java:274)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.onBeforeRequest(ONetworkProtocolBinary.java:227)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:185)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
```
The fact that the documentation is wrongly stating the size unit (bytes instead of kB) doesn't help, either,-) See #6310 

### Runninng Mode
- [ ] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [X] Remote

### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [X] v2.2.x - Please specify last number: 2

### Operating System
- [X] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [ ] 7
- [X] 8

**Comment by tglman** [comment] 2016-06-16 17:56
Hi @grexe,

did it happen using the console or using OServerAdmin ?

Regards

**Comment by grexe** [comment] 2016-06-17 19:01
using the console, also using a slightly adapted version of the official Docker image.

**Comment by tglman** [comment] 2016-06-20 11:53
hi @grexe,

What combination of commands did you do ? i tried a few:
direct create:
```
create database remote:localhost/test root root plocal
```
connect before and after create:
```
connect remote:localhost root root;
list databases;
create database remote:localhost/test1 root root plocal
```

connect disconnect and create:
```
connect remote:localhost root root;
disconnect;
create database remote:localhost/test2 root root plocal;
```

I could not reproduce the problem, do you have a list of command for rerpoduce the problem ? i think the issue came from a specific sequence of commands.

**Comment by lvca** [comment] 2016-08-27 19:29
Closing because no answer after a while. In case please reopen/comment this.

**Closed by lvca** 2016-08-27 19:29 UTC
Labels: bug, waiting reply

**Comment by e-d** [comment] 2016-09-06 16:06
Using 2.2.3 I sometimes get this error when automatic "reconnects" happen. 

Sep 01, 2016 7:00:23 PM com.orientechnologies.common.log.OLogManager log
WARNING: Caught I/O errors, trying to reconnect (error: Impossible to read a chunk of length:16777217 max allowed chunk length:16777216 see NETWORK_BINARY_MAX_CONTENT_LENGTH settings )

Once my application gets into this state, I have to restart my application (not the database) to get it to work again. I'm using the Java API and I get my connections from a database pool.

OPartitionedDatabasePool databasePool = new OPartitionedDatabasePool(dbName, dbUser, dbPassword, 64, 6);

Each time I need a connection to the database I'll call databasePool.acquire(), and if I need it to be an objection database connection I'll wrap it in an OObjectDatabaseTx object. For example:  OObjectDatabaseTx(databasePool.acquire()).

**Comment by tglman** [comment] 2016-09-06 16:36
hi @e-d,

We fixed few issue on reconnection in different hotfix, with 2.2.8 this error should be solved.

**Comment by e-d** [comment] 2016-09-20 14:09
Thank you @tglman! We upgraded to the 2.2.9 version (latest at the time), and we've been running smoothly ever since.

**Comment by nagarajasr** [comment] 2016-12-12 04:03
i had the same issue, using 2.2.13
i reinstalled and then it worked. 
very strange.
