### ISSUE TITLE
dijkstra throws exception

### ISSUE THREAD

**Issue by agarciaGIT** [orientechnologies/orientdb#7818] opened 2017-10-13 11:58 UTC
## Expected behavior  
Running dijkstra  will return the cheapest path between two vertices 

## Actual behavior  
The dijkstra(#30:5, #39:3,'weight', 'both') call throws an error Error: java.lang.NullPointerException 

## Steps to reproduce  
I have a simple graph where two vertices are connected by two other vertices via 4 edges forming a diamond. V1 <-E1- VA -E2-> V2 and V1 <-E3- VB -E4-> V2. 

The dijkstra(#30:5, #39:3,'weight', 'both') call throws an error Error: java.lang.NullPointerException

**Comment by luigidellaquila** [comment] 2017-10-19 15:33
Hi @agarciaGIT 

I just tried it with latest 2.2.29 and it seems to work fine.
I think this problem was fixed long time ago.

Could you please try to upgrade and, in case it still fails, post an SQL script to reproduce the problem?

Thanks

Luigi

**Comment by agarciaGIT** [comment] 2017-10-27 11:51
So it seems in a brand new database astar() and dijkstra() are working. But
in my existing database where I have subclasses for E and V and many nodes
they do not. I have put the property 'weight' on the class E itself, no
sure if this is an issue.

If I do ShortestPath I get this:

orientdb {db=SpinOffIntelligence}> SELECT shortestPath(#13:834, #39:27)

+----+-----------------------+
|#   |shortestPath           |
+----+-----------------------+
|0   |[#13:834,#23:74,#39:27]|
+----+-----------------------+

If I do the other I get this:

orientdb {db=SpinOffIntelligence}> SELECT astar(#13:834, #39:27, 'weight')

+----+-----+
|#   |astar|
+----+-----+
|0   |[]   |
+----+-----+

orientdb {db=SpinOffIntelligence}> SELECT dijkstra(#13:834, #39:27,
'weight')

+----+--------+
|#   |dijkstra|
+----+--------+
|0   |[]      |
+----+--------+

In this case it did not throw an exception. I did set weight = 100 for ALL
nodes though.

Question is why do these not return any data now?

Thanks,

AG

**Comment by luigidellaquila** [comment] 2017-10-27 12:49
Hi @agarciaGIT 

Having the property on E class is definitely OK, that should not be the problem.
As the issue is easily reproducible on your DB, but not on other databases, is there any chance to have your DB (or a DB with the same issue) so that I can debug it locally?

Thanks

Luigi

**Comment by agarciaGIT** [comment] 2017-10-27 13:04
Sure here it is.

Thanks!

AG

**Comment by luigidellaquila** [comment] 2017-10-27 13:27
Hi @agarciaGIT 

I didn't get the attachment (GitHub does not allow to send them via email), could you please link it to the issue?

Thanks

Luigi

**Comment by agarciaGIT** [comment] 2017-10-27 15:19
OK, here.
[SpinOffIntelligence (1).gz](https://github.com/orientechnologies/orientdb/files/1422524/SpinOffIntelligence.1.gz)

**Comment by agarciaGIT** [comment] 2017-10-28 13:08
Here is a very simple DB with Just E and V where I have size and weight as Integers and astar and dijkstra both choose the more expensive path!

orientdb {db=SOI2}> SELECT dijkstra(#9:0, #9:1, size)

+----+----------------+
|#   |dijkstra        |
+----+----------------+
|0   |[#9:0,#9:2,#9:1]|
+----+----------------+

1 item(s) found. Query executed in 0.002 sec(s).
orientdb {db=SOI2}> SELECT astar(#9:0, #9:1, size)

+----+----------------+
|#   |astar           |
+----+----------------+
|0   |[#9:0,#9:2,#9:1]|
+----+----------------+

[SOI2.gz](https://github.com/orientechnologies/orientdb/files/1424249/SOI2.gz)

**Comment by luigidellaquila** [comment] 2017-10-30 08:37
Hi @agarciaGIT 

I think I found the problem with the NullPointer, it happens when the source or the destination vertex do not exist. I'm fixing it now.
About your last comment, you have to quote the weight field name, eg.

```
SELECT dijkstra(#9:0, #9:1, "size")
```

I tested it locally and it works fine

Thanks

Luigi

**Comment by luigidellaquila** [comment] 2017-10-30 09:24
Hi @agarciaGIT 

I just pushed a fix for the NPE.
Please feel free to re-open if you see other problems

Thanks

Luigi

**Closed** 2017-10-30 09:23 UTC
