### ISSUE TITLE
Problems with commas in strings using an 'in [...]' query

### ISSUE THREAD

**Issue by maddyrenstrom** [orientechnologies/orientdb#3336] opened 2015-01-05 16:09 UTC
Hi, I have the following problem:

create a document with a field with a comma in it, e.g.:
      create Vertex DumClass set someProp = 'Hi, there' 

The query: 
    select from DumClass where someProp = 'Hi, there'
works but not the query:
    select from DumClass where someProp in ['Hi, there']

due to the comma in the string. Doing the exact same thing without the comma works just as intended. The comma is probably recognized as a separator rather than a character in the query. 
Am I missing something or is this a bug? Is there a workaround?

**Comment by lvca** [comment] 2015-01-05 16:15
OrientDB version?

**Comment by n0lf** [comment] 2015-01-05 16:56
tried it on OrientDB 2.0-rc1 and OrientDB 1.7.9. works on neither

**Comment by n0lf** [comment] 2015-01-07 12:05
should mention that it works if you use a Prepared query with name parameters.

**Comment by luigidellaquila** [comment] 2015-03-09 13:52
Hi @n0lf 

I was not able to reproduce it in 2.1, probably it was fixed as a consequence of new parser implementation.

I'm closing it. Please, reopen if needed

**Closed by luigidellaquila** 2015-03-09 13:52 UTC
Labels: bug, sql
