### ISSUE TITLE
Cannot drop database in distributed mode

### ISSUE THREAD

**Issue by tanhv90** [orientechnologies/orientdb#6815] opened 2016-10-15 06:59 UTC
## OrientDB Version, operating system, or hardware.
- v2.2.11

## Operating System
- [x] Linux
- [ ] MacOSX
- [x] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Steps to reproduce the problem

- Run OrientDB with distributed mode (only 1 node)
- Use console tool to create a new database

`create database remote:localhost/test root 123@123 plocal graph;`

- Use console tool to drop database

`drop database remote:localhost/test root 123@123;`

Exception occurred:  
> Error: com.orientechnologies.orient.core.exception.OStorageException: Cannot delete the remote storage: test
Error: com.orientechnologies.orient.server.distributed.ODistributedException: No nodes configured for partition 'test.null' request: id=0.0 task=drop_database

**Comment by lvca** [comment] 2016-10-18 04:54
Reproduced, working for a solution.

**Comment by lvca** [comment] 2016-10-18 04:57
Fixed in 2.2.x branch and it will be in the next 2.2.x release.

**Closed by lvca** 2016-10-18 04:57 UTC
Labels: bug

**Comment by tanhv90** [comment] 2016-10-18 05:00
Thank you!

**Comment by lvca** [comment] 2016-10-18 05:01
(The problem was when only 1 server was running as distributed)
