### ISSUE TITLE
TRAVERSE from RecordID Issue in binary serialization

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientdb#5289] opened 2015-11-06 19:23 UTC
Works in studio 2.1.5
```
begin
LET t0 = SELECT @rid as rid FROM (TRAVERSE References FROM #18:0 )
commit retry 100
return $t0
```

but fails in orientjs as transaction:
```
begin
LET t0 = SELECT @rid as rid FROM (TRAVERSE References FROM #18:0 )
commit retry 100
return $t0
```

Result:
```
{ classId: -2, value: null }
```

References is type from `LINKSET`

What shall I say to this. This is my fourth issue in the last 30 days for the transaction feature. I have to say I don't write complex querys....

We use orientdb in production and this very horrible. We have to make mulltiple requests as a workaround.

**Comment by maggiolo00** [comment] 2015-11-10 09:22
hi @StarpTech 

which error do you get?

**Comment by ggoodman** [comment] 2015-11-10 12:41
I'm facing a similar issue.

The problem is that it appears to be impossible to return the **persistent** `RecordID` for documents created as a part of a transaction with certain features. I have not yet been able to isolate what those specific features are.

In my case, the following transaction is returning a `RecordID` with a **negative** (temporary) cluster position:

```sql
BEGIN
 LET revision = UPDATE revision SET created_at = date("2015-11-08 17:23:40.570", "yyyy-MM-dd HH:mm:ss.SSS", "UTC"), commit_sha = "91942513f1005150bf388e9de0039fbca9f7d585", tree_sha = "86c7c2795938aa76962a46972279edd718a4efb7", type = "create" UPSERT RETURN AFTER WHERE commit_sha = "91942513f1005150bf388e9de0039fbca9f7d585"
 LET plunk = CREATE vertex plunk SET id = "iZx0yR3UIvfbfrG57Ewg", title = "plot trends", tags = ["angularjs"], created_at = date("2013-02-26 16:11:27.308", "yyyy-MM-dd HH:mm:ss.SSS", "UTC"), deleted_at = null, updated_at = date("2013-02-26 16:11:27.308", "yyyy-MM-dd HH:mm:ss.SSS", "UTC"), session_id = "4SyHwY0pA9PDbODU", readme = "", head = $revision
 LET created_by = CREATE edge created_by FROM $plunk TO #17:272
 LET history = CREATE edge history FROM $plunk TO $revision
 LET response = SELECT *, last(out('history')) as head, head.tree_sha as tree_sha, head.commit_sha as commit_sha FROM $plunk

COMMIT RETRY 100 
 RETURN $response```

**Comment by StarpTech** [comment] 2015-11-10 17:38
@maggiolo00 I get no error

**Comment by StarpTech** [comment] 2015-11-13 02:26
@maggiolo00 @lvca a feedback or short answer within 6 days would be nice.

**Comment by maggiolo00** [comment] 2015-11-13 09:14
hi @StarpTech 

i've tested this script against 2.1.5

```JAVASCRIPT
	var OrientDB = require('orientjs');
	var server = OrientDB({
	    host: 'localhost',
	    port: 2424,
	    username: 'root',
	    password: 'root'
	});
	var db = server.use('GratefulDeadConcerts');
	db.open('admin','admin').then(function(db){
		 var tx = db.createQuery();

		 tx.let('t0',function($t0){
		 	$t0.select('@rid as rid').from('(Traverse out_written_by from #9:1)')
		 })
		 tx.commit(100)
		 .return('$t0')
		 tx.all().then(function(response){
				console.log(response);
				process.exit();
		 })
		 
	})
	
```

Can you help me replicate the issue?

**Comment by StarpTech** [comment] 2015-11-13 09:22
@maggiolo00 I think you have to traverse over a LINKSET. I can't check it right now please try.

**Comment by maggiolo00** [comment] 2015-11-13 09:24
ok @StarpTech 

i will test it over a LINKSET

**Comment by maggiolo00** [comment] 2015-11-13 12:04
@StarpTech 

i've tested also with LINKSET and i got the right results

**Comment by maggiolo00** [comment] 2015-11-13 17:43
hi @StarpTech 

here is the full test with LinkSet

**OrientDB 2.1.4**
**OrientJS 2.0.0**

```JAVASCRIPT
var OrientDB = require('orientjs');
var server = OrientDB({
  host: 'localhost',
  port: 2424,
  username: 'root',
  password: 'root'
});

var db = server.use('GratefulDeadConcerts');
db.open('admin', 'admin').then(function (db) {
  db.class.create('Link').then(function (cls) {
    cls.property.create({
      name: 'links',
      type: 'linkset'
    }).then(function () {
      cls.create([{
        name: 'one'
      },
        {
          name: 'two'
        },
        {
          name: 'three'
        },
        {
          name: 'four'
        }
      ]).then(function (records) {

        cls.create({
          name: 'five',
          links: records.map(function (record) {
            return record['@rid'];
          })
        }).then(function (five) {
          var tx = db.createQuery();
          tx.let('t0', function ($t0) {
            $t0.select('@rid as rid').from('(traverse links from ' + five['@rid'].toString() +')')
          })
          tx.commit(100)
            .return('$t0')
          console.log(tx.toString());
          tx.all().then(function (response) {
          	console.log(response);
          	db.class.drop('Link').then(function () {
            	process.exit();
          	})
          })
          
        })

      })
    })
  });

})
```

**Comment by StarpTech** [comment] 2015-11-13 18:40
Thanks I will try it ABAP.  Can you also try my query without the Transaktion builder and with the 's' Class Flag?

**Comment by StarpTech** [comment] 2015-11-13 18:44
@maggiolo00 with db.query,  { class: "s"}

**Comment by maggiolo00** [comment] 2015-11-14 12:30
@StarpTech 
same result with 
 db.query, { class: "s"}

**Comment by maggiolo00** [comment] 2016-02-02 16:22
@StarpTech 
have you solved this issue?

**Comment by maggiolo00** [comment] 2016-06-09 17:09
@StarpTech 

do you still have this issue?

**Comment by lvca** [comment] 2016-08-27 19:17
Closing because no answer after months. In case please reopen/comment this.

**Closed by lvca** 2016-08-27 19:17 UTC
Labels: bug, waiting reply
