### ISSUE TITLE
It is not possible to have abstract classes with unique constraints and different child class objects with same value on abstract class constraint

### ISSUE THREAD

**Issue by KIC** [orientechnologies/orientdb#3771] opened 2015-03-17 14:40 UTC
I have no idea (and the exception is not really helping me to track down) what the problem is. But when I save a document (using DocumentAPI), I will face the following exception:
<pre>
2015-03-17 15:23:59 ERROR OrientDb:121 - Exception on db save com.orientechnologies.orient.core.exception.ODatabaseException: Error on saving record in cluster #16
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1758)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:94)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2274)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2111)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:117)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.createRecord(OBinaryNetworkProtocolAbstract.java:349)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.createRecord(ONetworkProtocolBinary.java:1373)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:350)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:216)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)
Caused by: java.lang.NullPointerException
	at com.orientechnologies.orient.core.index.OIndexTxAwareOneValue.checkEntry(OIndexTxAwareOneValue.java:215)
	at com.orientechnologies.orient.core.index.OClassIndexManager.checkIndexedPropertiesOnCreation(OClassIndexManager.java:322)
	at com.orientechnologies.orient.core.index.OClassIndexManager.checkIndexes(OClassIndexManager.java:581)
	at com.orientechnologies.orient.core.index.OClassIndexManager.onRecordBeforeCreate(OClassIndexManager.java:423)
	at com.orientechnologies.orient.core.hook.ODocumentHookAbstract.onTrigger(ODocumentHookAbstract.java:218)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.callbackHooks(ODatabaseDocumentTx.java:966)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1686)
	... 9 more
</pre>

My document "Model" looks like this:
{"name":{},"text":{"user":"test"},"userid":"xxx","title":"test"}

EDIT: Just to be mentioned, hitting on the empty "name" is not the reason since this document leads to the very same exception: {"name":{"user":"test"},"text":{"user":"test"},"userid":"xxx","title":"test"}

And my scheme like this:

<pre>
{"info":{"name":"test2","default-cluster-id":3,"exporter-version":11,"engine-version":"2.0.2","engine-build":"UNKNOWN@r; 2015-02-09 12:03:03+0000","storage-config-version":14,"schema-version":4,"mvrbtree-version":3,"schemaRecordId":"#0:1","indexMgrRecordId":"#0:2"},"clusters":[{"name":"internal","id":0},{"name":"index","id":1},{"name":"manindex","id":2},{"name":"default","id":3},{"name":"orole","id":4},{"name":"ouser","id":5},{"name":"ofunction","id":6},{"name":"oschedule","id":7},{"name":"orids","id":8},{"name":"v","id":9},{"name":"e","id":10},{"name":"profile","id":11},{"name":"_studio","id":12},{"name":"sgroup","id":13},{"name":"love","id":14},{"name":"follow","id":15},{"name":"model","id":16}],"schema":{"version":1,"classes":[{"name":"Class","default-cluster-id":-1,"cluster-ids":[-1],"abstract":true,"cluster-selection":"round-robin"},{"name":"E","default-cluster-id":10,"cluster-ids":[10],"cluster-selection":"round-robin"},{"name":"Follow","default-cluster-id":15,"cluster-ids":[15],"super-class":"E","cluster-selection":"round-robin"},{"name":"Love","default-cluster-id":14,"cluster-ids":[14],"super-class":"E","cluster-selection":"round-robin"},{"name":"Model","default-cluster-id":16,"cluster-ids":[16],"oversize":0.0,"super-class":"Ownable","cluster-selection":"round-robin","properties":[{"name":"title","type":"STRING","collate":"default"}]},{"name":"OFunction","default-cluster-id":6,"cluster-ids":[6],"cluster-selection":"round-robin","properties":[{"name":"code","type":"STRING","collate":"default"},{"name":"idempotent","type":"BOOLEAN","collate":"default"},{"name":"language","type":"STRING","collate":"default"},{"name":"name","type":"STRING","collate":"default"},{"name":"parameters","type":"EMBEDDEDLIST","linked-type":"STRING","collate":"default"}]},{"name":"OIdentity","default-cluster-id":-1,"cluster-ids":[-1],"abstract":true,"cluster-selection":"round-robin"},{"name":"ORIDs","default-cluster-id":8,"cluster-ids":[8],"cluster-selection":"round-robin"},{"name":"ORestricted","default-cluster-id":-1,"cluster-ids":[-1],"abstract":true,"cluster-selection":"round-robin","properties":[{"name":"_allow","type":"LINKSET","linked-class":"OIdentity","collate":"default"},{"name":"_allowDelete","type":"LINKSET","linked-class":"OIdentity","collate":"default"},{"name":"_allowRead","type":"LINKSET","linked-class":"OIdentity","collate":"default"},{"name":"_allowUpdate","type":"LINKSET","linked-class":"OIdentity","collate":"default"}]},{"name":"ORole","default-cluster-id":4,"cluster-ids":[4],"super-class":"OIdentity","cluster-selection":"round-robin","properties":[{"name":"inheritedRole","type":"LINK","linked-class":"ORole","collate":"default"},{"name":"mode","type":"BYTE","collate":"default"},{"name":"name","type":"STRING","mandatory":true,"not-null":true,"collate":"ci"},{"name":"rules","type":"EMBEDDEDMAP","linked-type":"BYTE","collate":"default"}]},{"name":"OSchedule","default-cluster-id":7,"cluster-ids":[7],"cluster-selection":"round-robin","properties":[{"name":"arguments","type":"EMBEDDEDMAP","collate":"default"},{"name":"function","type":"LINK","mandatory":true,"not-null":true,"linked-class":"OFunction","collate":"default"},{"name":"name","type":"STRING","mandatory":true,"not-null":true,"collate":"default"},{"name":"rule","type":"STRING","mandatory":true,"not-null":true,"collate":"default"},{"name":"start","type":"BOOLEAN","collate":"default"},{"name":"starttime","type":"DATETIME","collate":"default"},{"name":"status","type":"STRING","collate":"default"}]},{"name":"OTriggered","default-cluster-id":-1,"cluster-ids":[-1],"abstract":true,"cluster-selection":"round-robin"},{"name":"OUser","default-cluster-id":5,"cluster-ids":[5],"super-class":"OIdentity","cluster-selection":"round-robin","properties":[{"name":"name","type":"STRING","mandatory":true,"not-null":true,"collate":"ci"},{"name":"password","type":"STRING","mandatory":true,"not-null":true,"collate":"default"},{"name":"roles","type":"LINKSET","linked-class":"ORole","collate":"default"},{"name":"status","type":"STRING","mandatory":true,"not-null":true,"collate":"default"}]},{"name":"Ownable","default-cluster-id":-1,"cluster-ids":[-1],"oversize":0.0,"super-class":"searchable","abstract":true,"cluster-selection":"round-robin","properties":[{"name":"userid","type":"STRING","collate":"default"}]},{"name":"Profile","default-cluster-id":11,"cluster-ids":[11],"oversize":0.0,"super-class":"Ownable","cluster-selection":"round-robin","properties":[{"name":"membership","type":"EMBEDDEDSET","collate":"default"},{"name":"profileid","type":"STRING","collate":"default"}]},{"name":"SGroup","default-cluster-id":13,"cluster-ids":[13],"cluster-selection":"round-robin"},{"name":"V","default-cluster-id":9,"cluster-ids":[9],"oversize":2.0,"cluster-selection":"round-robin"},{"name":"_studio","default-cluster-id":12,"cluster-ids":[12],"cluster-selection":"round-robin"},{"name":"searchable","default-cluster-id":-1,"cluster-ids":[-1],"oversize":0.0,"super-class":"V","abstract":true,"cluster-selection":"round-robin","properties":[{"name":"name","type":"EMBEDDEDMAP","linked-type":"STRING","collate":"default"},{"name":"text","type":"EMBEDDEDMAP","linked-type":"STRING","collate":"default"}]}]},"indexes":[{"name":"OUser.name","type":"UNIQUE","clustersToIndex":["ouser"],"definition":{"defClass":"com.orientechnologies.orient.core.index.OPropertyIndexDefinition","stream":{"@type":"d","@version":0,"className":"OUser","field":"name","keyType":"STRING","collate":"ci","nullValuesIgnored":true}}},{"name":"dictionary","type":"DICTIONARY","definition":{"defClass":"com.orientechnologies.orient.core.index.OSimpleKeyIndexDefinition","stream":{"@type":"d","@version":0,"keyTypes":["STRING"],"collate":"default","nullValuesIgnored":true}},"metadata":{"@type":"d","@version":0,"durableInNonTxMode":true,"trackMode":"FULL"}},{"name":"searchable.name","type":"FULLTEXT","clustersToIndex":["profile","model"],"definition":{"defClass":"com.orientechnologies.orient.core.index.OPropertyMapIndexDefinition","stream":{"@type":"d","@version":0,"className":"searchable","field":"name","keyType":"STRING","collate":"default","nullValuesIgnored":true,"mapIndexBy":"VALUE"}},"metadata":{"@type":"d","@version":0,"durableInNonTxMode":true,"trackMode":"FULL"}},{"name":"Profile.profileid","type":"UNIQUE","clustersToIndex":["profile"],"definition":{"defClass":"com.orientechnologies.orient.core.index.OPropertyIndexDefinition","stream":{"@type":"d","@version":0,"className":"Profile","field":"profileid","keyType":"STRING","collate":"default","nullValuesIgnored":true}}},{"name":"Model.title","type":"UNIQUE","clustersToIndex":["model"],"definition":{"defClass":"com.orientechnologies.orient.core.index.OPropertyIndexDefinition","stream":{"@type":"d","@version":0,"className":"Model","field":"title","keyType":"STRING","collate":"default","nullValuesIgnored":true}}},{"name":"ORole.name","type":"UNIQUE","clustersToIndex":["orole"],"definition":{"defClass":"com.orientechnologies.orient.core.index.OPropertyIndexDefinition","stream":{"@type":"d","@version":0,"className":"ORole","field":"name","keyType":"STRING","collate":"ci","nullValuesIgnored":true}}},{"name":"Ownable.userid","type":"UNIQUE","clustersToIndex":["profile","model"],"definition":{"defClass":"com.orientechnologies.orient.core.index.OPropertyIndexDefinition","stream":{"@type":"d","@version":0,"className":"Ownable","field":"userid","keyType":"STRING","collate":"default","nullValuesIgnored":true}},"metadata":{"@type":"d","@version":0,"durableInNonTxMode":true,"trackMode":"FULL"}}],"manualIndexes":[{"name":"dictionary","content":[]}]}
</pre>

EDIT 2: Interesting fact, when I use the Studio and execute INSERT INTO Model DOCUMENT {"name":{"user":"test"},"text":{"user":"asdsada"},"userid":"xxx","title":"test"} the Studio prompts OK, but a select * from Model results in 0 rows.

EDIT 3: When I use the Studio and Schema -> Model -> Add Record -> Save then I will face the Nullpointer too. PS I have upgraded to OrientDB 2.0.5 the same issue still remains. 

I think it has to do with a unique constraint on a super class (abstract class), which is not working well if one use different child classes and when the different documents use the same value on the abstract class's unique constraint. I see the point that there is a unique constraint violation but I think this should be possible if you allow inheritance on classes (which by the way is a very great feature!)

**Comment by KIC** [comment] 2015-03-18 09:36
This is how you can reproduce the issue:

<pre>
create abstract class foo abstract
create property foo.name string
create index Foo.name unique

create class bar1 extends foo
create property bar1.aa string

create class bar2 extends foo
create property bar2.bb string

insert into bar1 content {"name" : "testname", "aa" : "test aa"}

insert into bar2 content {"name" : "testname", "bb" : "test bb"}
</pre>

**Comment by a-unite** [comment] 2015-03-18 10:41
Dear KIC,

from my point of view - this is more a feature, than a bug...

Why don't you repeat "name" field  (or, better, create particular indexes) in both "bar"s then?
All possible queries will remain the same, and even better - index look-ups will be partitioned and localized to bar1 (or bar2) respectively.

WBR, AU

**Comment by KIC** [comment] 2015-03-18 11:04
Thanks for your respone a-unite!

Well because the whole sense of object oriented modeling is not to repeat yourself. Of course I "fixed" it be repeating the attributes in every bar. But lets quickly talk about my use case: I would like to have an abstract class called "Ownable" and every child class inherits the property userId from the Ownable class. So for example you will end up with a "Posting" class extending the Ownable and an "Article" class and so on. When you write an application there is a use case where you just want to know if a user is allowed to do an operation on an object (if he is the owner) or not. From an oo point of view I would model an abstract class just telling me the owner of an object. Now you can write a generic webservice just asking like so: 

<pre>
Ownable ownable = select userid from ownable where id = #1:2
return ownable.getUserId().equals(session.userId);
<pre>

This is pretty neat because you can use the same service for any class, you just show a "Save" button or not based on an abstract class "Ownable".
 
Well maybe you will do me a favor and discuss this with some team members at coffee time just to collect some opinions. 

Thanks
KIC

**Comment by a-unite** [comment] 2015-03-19 07:44
Dear KIC, sorry for delay, I see that Luca already marked this issue as a bug.

I'm fully support your way of using OOP-like futures!
The only thing I wanted to mention is that classes are inherited, but indexes are independent entities.

I see the part of the problem is that property value uniqueness could be achieved only with indexes, but not with class declaration. But it is not so bad, as it could be seen. You might want to make unique indexes for every derived class and it should work with your primer:

```sql
create class foo abstract
create property foo.name string

create class bar1 extends foo
create class bar2 extends foo
  create index bar1.name unique
  create index bar2.name unique

insert into bar1 content {"name" : "testname"}
insert into bar2 content {"name" : "testname"}
```

While making 
```sql
create index foo.name unique
```
still could help to keep unique records aver all sub-classes.

**Comment by KIC** [comment] 2015-03-20 19:48
Thanks for your comment mentioning to just separate the index out of the abstract class. You are right this indeed works. Since an abstract class can never be instantiated but only sub classes can, it is just not logical to me :-) I think it would make sense to pull a unique index from an abstract(!) class to its derived classes automatically / internally. But I am fine with the current solution and with a fix of the "strange" Nullpointer exception.

**Comment by a-unite** [comment] 2015-03-21 07:32
Dear KIC, I'm glad it works for you.
You are right, abstract classes could not be instantiated, but they still could be queried (here is the power of concept); and indexes are more about retrieving, not storing.

**Comment by luigidellaquila** [comment] 2015-07-06 11:18
Hi guys,

I fixed the NullPointerException in the storage, but the behavior is the expected one:
declaring the unique property in the abstract class means that for all the instances of that class (so also for the union of subclasses) only one record can have a single attribute value at a time.

Thanks

**Closed by luigidellaquila** 2015-07-06 11:18 UTC
