### ISSUE TITLE
java.lang.NullPointerException ORecordSerializerBinaryV0.readSingleValue (2.1 RC6 - database corrupted?)

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#4676] opened 2015-07-29 13:33 UTC
java.lang.NullPointerException: null
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.readSingleValue(ORecordSerializerBinaryV0.java:291) ~[orientdb-core-2.1-rc6.jar:2.1-rc6]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.readEmbeddedMap(ORecordSerializerBinaryV0.java:433) ~[orientdb-core-2.1-rc6.jar:2.1-rc6]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.readSingleValue(ORecordSerializerBinaryV0.java:363) ~[orientdb-core-2.1-rc6.jar:2.1-rc6]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.deserialize(ORecordSerializerBinaryV0.java:193) ~[orientdb-core-2.1-rc6.jar:2.1-rc6]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.fromStream(ORecordSerializerBinary.java:74) ~[orientdb-core-2.1-rc6.jar:2.1-rc6]
	at com.orientechnologies.orient.core.record.impl.ODocument.deserializeFields(ODocument.java:1774) ~[orientdb-core-2.1-rc6.jar:2.1-rc6]
	at com.orientechnologies.orient.core.record.impl.ODocument.checkForFields(ODocument.java:2354) ~[orientdb-core-2.1-rc6.jar:2.1-rc6]
	at com.orientechnologies.orient.core.record.impl.ODocument.field(ODocument.java:992) ~[orientdb-core-2.1-rc6.jar:2.1-rc6]
	at com.orientechnologies.orient.core.record.impl.ODocument.field(ODocument.java:877) ~[orientdb-core-2.1-rc6.jar:2.1-rc6]
	at com.tinkerpop.blueprints.impls.orient.OrientElement.setProperty(OrientElement.java:200) ~[orientdb-graphdb-2.1-rc6.jar:2.1-rc6]
	at com.stimulus.archiva.database.blueprints.BluePrintDatabase.setProperty(BluePrintDatabase.java:818) ~[BluePrintDatabase.class:na]
	at com.stimulus.archiva.database.blueprints.BluePrintTreeItem.setProperty(BluePrintTreeItem.java:138) ~[BluePrintTreeItem.class:na]
	at com.stimulus.archiva.statistics.StatisticsService.run(StatisticsService.java:459) ~[StatisticsService.class:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471) [na:1.7.0_71]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304) [na:1.7.0_71]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178) [na:1.7.0_71]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.7.0_71]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_71]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_71]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]

**Comment by laa** [comment] 2015-07-29 13:38
Did you make database repair or updated jars of problem database ?

**Comment by jamieb22** [comment] 2015-07-29 14:01
Andrey... this is a database that you repaired. It also has errors on rebuilding indexes:
2015-07-29 15:58:00 t.c.s.a.d.DatabaseService [ERROR] failed to connect to database:Error on rebuilding the index for clusters: [v_statistic]
com.orientechnologies.orient.core.index.OIndexException: Error on rebuilding the index for clusters: [v_statistic]
	at com.orientechnologies.orient.core.index.OIndexAbstract.rebuild(OIndexAbstract.java:452) ~[orientdb-core-2.1-rc6.jar:2.1-rc6]
	at com.orientechnologies.orient.core.index.OIndexAbstract.create(OIndexAbstract.java:253) ~[orientdb-core-2.1-rc6.jar:2.1-rc6]
	at com.orientechnologies.orient.core.index.OIndexOneValue.create(OIndexOneValue.java:128) ~[orientdb-core-2.1-rc6.jar:2.1-rc6]
	at com.orientechnologies.orient.core.index.OIndexOneValue.create(OIndexOneValue.java:45) ~[orientdb-core-2.1-rc6.jar:2.1-rc6]
	at com.orientechnologies.orient.core.index.OIndexManagerShared.createIndex(OIndexManagerShared.java:169) ~[orientdb-core-2.1-rc6.jar:2.1-rc6]
	at com.orientechnologies.orient.core.index.OIndexManagerProxy.createIndex(OIndexManagerProxy.java:79) ~[orientdb-core-2.1-rc6.jar:2.1-rc6]
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.createIndex(OClassImpl.java:1714) ~[orientdb-core-2.1-rc6.jar:2.1-rc6]
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.createIndex(OClassImpl.java:1686) ~[orientdb-core-2.1-rc6.jar:2.1-rc6]
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.createIndex(OClassImpl.java:1676) ~[orientdb-core-2.1-rc6.jar:2.1-rc6]
	at com.orientechnologies.orient.core.metadata.schema.OClassImpl.createIndex(OClassImpl.java:1672) ~[orientdb-core-2.1-rc6.jar:2.1-rc6]
	at com.orientechnologies.orient.core.metadata.schema.OClassAbstractDelegate.createIndex(OClassAbstractDelegate.java:348) ~[orientdb-core-2.1-rc6.jar:2.1-rc6]
	at com.tinkerpop.blueprints.impls.orient.OrientElementType.access$301(OrientElementType.java:35) ~[orientdb-graphdb-2.1-rc6.jar:2.1-rc6]
	at com.tinkerpop.blueprints.impls.orient.OrientElementType$4.call(OrientElementType.java:80) ~[orientdb-graphdb-2.1-rc6.jar:2.1-rc6]
	at com.tinkerpop.blueprints.impls.orient.OrientElementType$4.call(OrientElementType.java:77) ~[orientdb-graphdb-2.1-rc6.jar:2.1-rc6]
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.executeOutsideTx(OrientBaseGraph.java:1740) ~[orientdb-graphdb-2.1-rc6.jar:2.1-rc6]
	at com.tinkerpop.blueprints.impls.orient.OrientElementType.createIndex(OrientElementType.java:77) ~[orientdb-graphdb-2.1-rc6.jar:2.1-rc6]
	at com.stimulus.archiva.database.blueprints.BluePrintDatabaseUtil.initSchema(BluePrintDatabaseUtil.java:358) ~[BluePrintDatabaseUtil.class:na]
	at com.stimulus.archiva.database.blueprints.BluePrintDatabaseUtil.initGraphFactory(BluePrintDatabaseUtil.java:296) ~[BluePrintDatabaseUtil.class:na]
	at com.stimulus.archiva.database.blueprints.BluePrintDatabase.connect(BluePrintDatabase.java:86) ~[BluePrintDatabase.class:na]
	at com.stimulus.archiva.database.DatabaseService.startup(DatabaseService.java:306) ~[DatabaseService.class:na]
	at com.stimulus.archiva.domain.Services$ServiceStartup.run(Services.java:165) [Services$ServiceStartup.class:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_71]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_71]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_71]
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -40
	at java.lang.String.checkBounds(String.java:371) ~[na:1.7.0_71]
	at java.lang.String.<init>(String.java:415) ~[na:1.7.0_71]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.stringFromBytes(ORecordSerializerBinaryV0.java:796) ~[orientdb-core-2.1-rc6.jar:2.1-rc6]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.readString(ORecordSerializerBinaryV0.java:753) ~[orientdb-core-2.1-rc6.jar:2.1-rc6]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.readSingleValue(ORecordSerializerBinaryV0.java:302) ~[orientdb-core-2.1-rc6.jar:2.1-rc6]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinaryV0.deserializePartial(ORecordSerializerBinaryV0.java:141) ~[orientdb-core-2.1-rc6.jar:2.1-rc6]
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.fromStream(ORecordSerializerBinary.java:72) ~[orientdb-core-2.1-rc6.jar:2.1-rc6]
	at com.orientechnologies.orient.core.record.impl.ODocument.deserializeFields(ODocument.java:1774) ~[orientdb-core-2.1-rc6.jar:2.1-rc6]
	at com.orientechnologies.orient.core.record.impl.ODocument.checkForFields(ODocument.java:2354) ~[orientdb-core-2.1-rc6.jar:2.1-rc6]
	at com.orientechnologies.orient.core.record.impl.ODocument.rawField(ODocument.java:760) ~[orientdb-core-2.1-rc6.jar:2.1-rc6]
	at com.orientechnologies.orient.core.record.impl.ODocument.field(ODocument.java:785) ~[orientdb-core-2.1-rc6.jar:2.1-rc6]
	at com.orientechnologies.orient.core.index.OPropertyIndexDefinition.getDocumentValueToIndex(OPropertyIndexDefinition.java:77) ~[orientdb-core-2.1-rc6.jar:2.1-rc6]
	at com.orientechnologies.orient.core.index.OIndexAbstract.indexCluster(OIndexAbstract.java:1045) ~[orientdb-core-2.1-rc6.jar:2.1-rc6]
	at com.orientechnologies.orient.core.index.OIndexAbstract.rebuild(OIndexAbstract.java:434) ~[orientdb-core-2.1-rc6.jar:2.1-rc6]
	... 23 common frames omitted

**Comment by laa** [comment] 2015-07-29 14:10
It is repaired under rc4 we need to repair it under rc6 because bugs cuased data corruption were fixed in rc6. Could Valentin send me this DB ?

**Comment by lvca** [comment] 2015-09-21 23:26
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.

**Closed by lvca** 2015-09-21 23:26 UTC
