### ISSUE TITLE
Support for (automatic) rename of existing edge class 

### ISSUE THREAD

**Issue by charlesporter** [orientechnologies/orientdb#2081] opened 2014-02-28 06:24 UTC
if I create vertex type Node, an edge type ARC, create two Node instance and connect them by an ARC, then change the class name of ARC to 'CONNECT', the name of the Node property remains 'ARC', even though the class is now called CONNECT
#### repro in console

``` SQL
# disable lightweight edge to force doc creation
orientdb {T1}> alter database custom useLightweightEdges=false
Database updated successfully

orientdb {T1}> create class N extends V
Class created successfully. Total classes in database now: 11

orientdb {T1}> create class ARC extends E
Class created successfully. Total classes in database now: 12

orientdb {T1}> create vertex N set name = '0'
Created vertex 'N#11:0{name:0} v1' in 0.019000 sec(s).

orientdb {T1}> create vertex N set name = '1'
Created vertex 'N#11:1{name:1} v1' in 0.001000 sec(s).

orientdb {T1}> create edge ARC from #11:0 to #11:1
Created edge '[e[#12:0][#11:0-ARC->#11:1]]' in 0.007000 sec(s).

orientdb {T1}> select expand(out('ARC')) from #11:0
----+-----+----+------
#   |@RID |name|in_ARC
----+-----+----+------
0   |#11:1|1   |#12:0 
----+-----+----+------
1 item(s) found. Query executed in 0.001 sec(s).

# NOTE without commit before schema change database is corrupted
orientdb {T1}> commit
Transaction 8 has been committed in 1ms

# change name of edge class
orientdb {T1}> alter class ARC NAME CONNECT
Class updated successfully

# confirm renamed class
orientdb {T1}> browse class CONNECT
----+-----+-----+-----
#   |@RID |out  |in   
----+-----+-----+-----
0   |#12:0|#11:0|#11:1
----+-----+-----+-----

# tested with and with commit here. makes no difference
orientdb {T1}> commit
Transaction 9 has been committed in 0ms

#select with old name still works
orientdb {T1}> select expand(out('ARC')) from #11:0
----+-----+----+------
#   |@RID |name|in_ARC
----+-----+----+------
0   |#11:1|1   |#12:0 
----+-----+----+------
1 item(s) found. Query executed in 0.006 sec(s).

# select with new name returns nothing 
orientdb {T1}> select expand(out('CONNECT')) from #11:0
0 item(s) found. Query executed in 0.002 sec(s).
```

**Comment by tglman** [comment] 2015-07-06 11:34
this depends on #3742, moving it forward

**Comment by a-unite** [comment] 2016-01-10 12:47
hope this will come to live soon

**Comment by santo-it** [comment] 2017-06-09 09:19
Hi,

Thanks for opening this issue. The command:

```
ALTER CLASS OldEdgeClassName NAME NewEdgeClassName
```

in more recent versions than 1.7rc now returns the following error message:

```
Cannot alter class 'OldEdgeClassName' because is an Edge class and could break vertices. Use UNSAFE if you want to force it DB name="2081"
```

For this reason I'd change this from bug to enhancement, as the command is not executed and the graph is not broken.

While edge class rename is not directly supported, there's a possible workaround you can use, provided that you know what you are doing and consider that this could have high computational cost and it is not transactional (you may consider to block any other connections while you execute the commands below).

Suppose you have OldEdgeClassName edges from vertices in vClass1 to vertices in vClass2 and you would like to rename OldEdgeClassName to NewEdgeClassName. Workaround (full script):

```
CREATE CLASS vClass1 extends V;
CREATE CLASS vClass2 extends V;

CREATE VERTEX vClass1 SET name = '1';
CREATE VERTEX vClass2 SET name = '2';

CREATE CLASS OldEdgeClassName extends E;

CREATE EDGE OldEdgeClassName from (SELECT FROM vClass1) TO (SELECT FROM vClass2);

# test
SELECT EXPAND(out('OldEdgeClassName')) FROM (SELECT FROM vClass1 WHERE name = '1');

ALTER CLASS OldEdgeClassName NAME NewEdgeClassName UNSAFE;

# test (before updates)
SELECT EXPAND(out('OldEdgeClassName')) FROM (SELECT FROM vClass1 WHERE name = '1');
SELECT EXPAND(out('NewEdgeClassName')) FROM (SELECT FROM vClass1 WHERE name = '1');

UPDATE V SET out_NewEdgeClassName = out_OldEdgeClassName WHERE out_OldEdgeClassName IS NOT NULL;
UPDATE V REMOVE out_OldEdgeClassName WHERE out_OldEdgeClassName IS NOT NULL;
UPDATE V SET in_NewEdgeClassName = in_OldEdgeClassName WHERE in_OldEdgeClassName IS NOT NULL;
UPDATE V REMOVE in_OldEdgeClassName WHERE in_OldEdgeClassName IS NOT NULL;

# test (after updates)
SELECT EXPAND(out('OldEdgeClassName')) FROM (SELECT FROM vClass1 WHERE name = '1');
SELECT EXPAND(out('NewEdgeClassName')) FROM (SELECT FROM vClass1 WHERE name = '1');
```

**Comment by msluser** [comment] 2018-10-25 01:54
I have tried renaming an edge in 3.0.9 using the SQL statement
`ALTER CLASS Edge1 NAME Edge2 UNSAFE
`
It Fails saying that I need to use unsafe 
`Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Cannot alter class 'Edge1' because is an Edge class and could break vertices. Use UNSAFE if you want to force it
`
However it succeeds with version 3.1.0-M2.
I thought renaming edges was a feature in 3.0. Is that true ?

**Comment by luigidellaquila** [comment] 2018-10-25 07:10
Hi @msluser 

No, renaming an edge is not a feature in v 3.0, in the sense that you cannot rename an edge out of the box; you have to do it manually, using UNSAFE.
This said, that exception is strange, I'm checking it now

Thanks

Luigi

**Comment by luigidellaquila** [comment] 2018-10-26 08:41
Hi @msluser 

I just tried it in latest 3.0.10 and it seems to work fine with unsafe...
Can you please share some info on how to reproduce?

Thanks

Luigi

**Comment by smolinari** [comment] 2018-10-26 08:49
What does "unsafe" mean? Sorry for barging in on the conversation, but it would interest me and I couldn't find anything in the docs.

Scott

**Comment by luigidellaquila** [comment] 2018-10-26 09:15
Hi @smolinari 

There are some operations that do not guarantee data consistency if executed in some particular conditions. 

As an example, consider a `TRUNCATE CLUSTER ...` on a cluster that contains vertices: it will result in edges that point to non existing vertices. The correct operation would be `DELETE VERTEX ...`, that also deletes connected edges, but it a DELETE VERTEX can take minutes on big clusters, while a TRUNCATE CLUSTER takes milliseconds. OrientDB does not allow you to do such kind of operations (ie. TRUNCATE CLUSTER will result in an exception if you do it on a vertex cluster); the UNSAFE keyword allows you to override this behavior and do the operation at your own risk

For this specific case, renaming an edge class does not rename the corresponding `out_*`,`in_*` on the connected vertices, so it will result in a broken graph, this is why you need UNSAFE to explicitly force it

Thanks

Luigi

**Comment by smolinari** [comment] 2018-10-26 12:35
@luigidellaquila - As always super helpful. I appreciate the time you took to explain UNSAFE.

If you tell me everywhere UNSAFE can be used, I'll update the docs to show this feature. (If you want....). :smiley:  

Scott

**Comment by luigidellaquila** [comment] 2018-10-30 11:32
Hi @smolinari 

That would be awesome!
For now, UNSAFE is supported on:
- DELETE (no checks on edges)
- TRUNCATE CLASS (no checks on edges)
- TRUNCATE CLUSTER (no checks on edges)
- ALTER CLASS (no check for edge class and for existing indexes)
- DROP CLASS (no checks on edges)
- CREATE PROPERTY (no checks for values compatibility with the new property type)

Thanks!

Luigi

**Comment by smolinari** [comment] 2018-11-01 06:53
I have one question, before I make the docs changes. @luigidellaquila 

For everything that you mentioned above, if UNSAFE isn't used, will ODB throw an error? For instance, if a user tries to delete a vertex or an edge with DELETE, ODB will give them an error and only with UNSAFE can the command be carried out?

Scott

**Comment by luigidellaquila** [comment] 2018-11-02 08:29
Hi @smolinari 

Yes, exactly, UNSAFE allows you to force the execution of a statement that would fail with an exception.

I'd say you can use 3.0.x and 3.1.x branches:

https://github.com/orientechnologies/orientdb-docs/tree/3.0.x
https://github.com/orientechnologies/orientdb-docs/tree/3.1.x

Thanks!

Luigi

**Comment by smolinari** [comment] 2018-11-03 06:15
@luigidellaquila - I had to mess around with Gitbook to realize it wasn't going to do the job for me for editing. So, I went to back my trusted local editor. :)

At any rate. Please check [this PR on DELETE](https://github.com/orientechnologies/orientdb-docs/pull/332). If the wording is correct, I'll continue with all the other commands and in each version.

Scott

**Closed** 2021-08-04 09:17 UTC
Labels: enhancement
