### ISSUE TITLE
Class create by a select query for lightweigth edges

### ISSUE THREAD

**Issue by tglman** [orientechnologies/orientdb#3938] opened 2015-04-16 11:13 UTC
in some cases a class is created by a select query.
for example if in GratefulDeadConcerts you drop written_by and sung_by class an run this query:

```
select name, $sungbyrecord as x_sungby 
from V 
let $sungby = outE()[ @class = 'sung_by' ], 
    $sungbyrecord = list( (select in.name, in.type from $sungby ) ) 
where name='HEY BO DIDDLEY'
```

the class are recreated automatically missing some information like the extension to E

**Comment by tglman** [comment] 2015-04-16 11:16
the problem could be that when we do outE() we need and Edge that have inside an ODocument of that class, and i think that is true also for lightweigth edeges, and today when we create the odocument we create also the class if not exist, we could do a specific constructor for that case.... but not sure if we are covering all the cases

**Comment by lvca** [comment] 2015-04-18 16:33
I cannot reproduce it with 2.0.8, seems already fixed. Closing it, in case reopen it please.

**Closed by lvca** 2015-04-18 16:33 UTC
Labels: bug
