### ISSUE TITLE
Exception:  "com.orientechnologies.orient.core.index.sbtree.local.OSBTreeException: Null keys are not supported." when using Orient DB build 2.0.13 with 1.7.x database.

### ISSUE THREAD

**Issue by shlapkov** [orientechnologies/orientdb#4666] opened 2015-07-28 15:41 UTC
jvm 1    | ERROR [OCommandExecutorSQLSelect] {db=spectrum} Error on using index IndexChain{platform-
DataflowStage0_idx, platform-Dataflow_pk} in query 'select @class, id, serverId, stageLabel, stageNa
me, stageId, dataflow, versions from platform-DataflowStage WHERE (dataflow.id = "Microflow_Sort_sf"
 AND versions CONTAINS "LatestSaved") SKIP 0 LIMIT 2147483647'. Probably you need to rebuild indexes
. Now executing query using cluster scan
jvm 1    | com.orientechnologies.orient.core.index.sbtree.local.OSBTreeException: Null keys are not
supported.
jvm 1    |      at com.orientechnologies.orient.core.index.sbtree.local.OSBTree.checkNullSupport(OSB
Tree.java:789) ~[orientdb-core-2.0.13.jar:2.0.13]
jvm 1    |      at com.orientechnologies.orient.core.index.sbtree.local.OSBTree.get(OSBTree.java:176
) ~[orientdb-core-2.0.13.jar:2.0.13]
jvm 1    |      at com.orientechnologies.orient.core.index.engine.OSBTreeIndexEngine.get(OSBTreeInde
xEngine.java:224) ~[orientdb-core-2.0.13.jar:2.0.13]
jvm 1    |      at com.orientechnologies.orient.core.index.OIndexMultiValues$1.nextEntry(OIndexMulti
Values.java:398) ~[orientdb-core-2.0.13.jar:2.0.13]
jvm 1    |      at com.orientechnologies.orient.core.sql.OChainedIndexProxy.cursorToList(OChainedInd
exProxy.java:367) ~[orientdb-core-2.0.13.jar:2.0.13]
jvm 1    |      at com.orientechnologies.orient.core.sql.OChainedIndexProxy.applyFirstIndex(OChained
IndexProxy.java:351) ~[orientdb-core-2.0.13.jar:2.0.13]
jvm 1    |      at com.orientechnologies.orient.core.sql.OChainedIndexProxy.applyTailIndexes(OChaine
dIndexProxy.java:338) ~[orientdb-core-2.0.13.jar:2.0.13]
jvm 1    |      at com.orientechnologies.orient.core.sql.OChainedIndexProxy.get(OChainedIndexProxy.j
ava:293) ~[orientdb-core-2.0.13.jar:2.0.13]
jvm 1    |      at com.orientechnologies.orient.core.sql.operator.OQueryOperatorEquals.executeIndexQ
uery(OQueryOperatorEquals.java:129) ~[orientdb-core-2.0.13.jar:2.0.13]
jvm 1    |      at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchForIndexes(
OCommandExecutorSQLSelect.java:1509) [orientdb-core-2.0.13.jar:2.0.13]
jvm 1    |      at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchInClasses(O
CommandExecutorSQLSelect.java:740) [orientdb-core-2.0.13.jar:2.0.13]
jvm 1    |      at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.assign
Target(OCommandExecutorSQLResultsetAbstract.java:194) [orientdb-core-2.0.13.jar:2.0.13]
jvm 1    |      at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.assignTarget(OCom
mandExecutorSQLSelect.java:420) [orientdb-core-2.0.13.jar:2.0.13]
jvm 1    |      at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCo
mmandExecutorSQLSelect.java:402) [orientdb-core-2.0.13.jar:2.0.13]
jvm 1    |      at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandE
xecutorSQLSelect.java:373) [orientdb-core-2.0.13.jar:2.0.13]
jvm 1    |      at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OComman
dExecutorSQLDelegate.java:64) [orientdb-core-2.0.13.jar:2.0.13]
jvm 1    |      at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.ex
ecuteCommand(OAbstractPaginatedStorage.java:1191) [orientdb-core-2.0.13.jar:2.0.13]
jvm 1    |      at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.co
mmand(OAbstractPaginatedStorage.java:1180) [orientdb-core-2.0.13.jar:2.0.13]
jvm 1    |      at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:71) [ori
entdb-core-2.0.13.jar:2.0.13]
jvm 1    |      at com.orientechnologies.orient.core.sql.query.OSQLSynchQuery.run(OSQLSynchQuery.jav
a:85) [orientdb-core-2.0.13.jar:2.0.13]
jvm 1    |      at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.jav
a:33) [orientdb-core-2.0.13.jar:2.0.13]
jvm 1    |      at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinar
y.command(ONetworkProtocolBinary.java:1183) [orientdb-server-2.0.13.jar:2.0.13]
jvm 1    |      at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinar
y.executeRequest(ONetworkProtocolBinary.java:390) [orientdb-server-2.0.13.jar:2.0.13]
jvm 1    |      at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtoco
lAbstract.execute(OBinaryNetworkProtocolAbstract.java:217) [orientdb-server-2.0.13.jar:2.0.13]
jvm 1    |      at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69) [orientd
b-core-2.0.13.jar:2.0.13]

**Comment by shlapkov** [comment] 2015-07-28 15:50
Running rebuild all doesn't help

**Comment by tglman** [comment] 2015-07-28 16:39
Hi @shlapkov 
Can you tell me the indexes defined on platform-DataflowStage class?

**Comment by shlapkov** [comment] 2015-07-28 16:55
platform-DataflowStage1_idx	NOTUNIQUE	["serverId"]	SBTREE	 Rebuild    Drop
platform-DataflowStage3_idx	NOTUNIQUE	["versions"]	SBTREE	 Rebuild    Drop
platform-DataflowStage2_idx	NOTUNIQUE	["stageName"]	SBTREE	 Rebuild    Drop
platform-DataflowStage_pk	UNIQUE	["id"]	SBTREE	 Rebuild    Drop
platform-DataflowStage0_idx	NOTUNIQUE	["dataflow"]	SBTREE	 Rebuild    Drop

**Comment by shlapkov** [comment] 2015-07-28 16:55
the same steps are working fine for 2.0.7 build.

**Comment by tglman** [comment] 2015-07-29 09:48
hi @shlapkov,

I wrote a test case for try to reproduce your issue here it is: https://gist.github.com/tglman/cf82e0e47978fd175733, but i couldn't, can you check it or can you send us the database with the platform-DataflowStage and platform-Dataflow classes with relative data and indexes.

thank you

**Comment by shlapkov** [comment] 2015-07-29 22:10
sent to @lvca

**Comment by tglman** [comment] 2015-07-30 11:10
downloading and investigating.

**Comment by shlapkov** [comment] 2015-07-30 14:20
ok, your unit test which posted yesterday unrelated to this ticket. Please pay attentions on the title: "... Orient DB build 2.0.13 with 1.7.x database." not in memory connection

**Comment by tglman** [comment] 2015-07-30 15:12
hi @shlapkov,

The reason you are getting that error is the null support fix happend in 2.0.9, for get it work as before you have to drop and recreate the index in this way :
```
drop index  platform-DataflowStage0_idx

create index platform-DataflowStage0_idx  on platform-DataflowStage(dataflow) NOTUNIQUE METADATA {"ignoreNullValues":false}

```

we are investigation if is possible to detect that the database was created when this management was broken so we could apply the flag in automatic

**Comment by shlapkov** [comment] 2015-07-30 15:24
Hello @tglman Thank you for your comments but it doesn't helps. Because once I am trying to "Rebuild all Indexed" I am getting different exception similar to the old ticket: http://www.prjhub.com/#/issues/4633 serName =admin) against database 'spectrum.[]' to nodes [node_VA005SH_AUS1_8080] jvm 1 | --> com.orientechnologies.orient.server.distributed.ODistributedException: Quorum 1 not r eached for request (id=1383 from=node_VA005SH_AUS1_8080 task=command_sql(REBUILD INDEX ) 

Do you need an new ticket for this?

**Comment by tglman** [comment] 2015-07-30 15:47
It's ok keep the old one.

**Comment by tglman** [comment] 2015-07-30 18:22
I just tried to rebuild the index with the last 2.0.x snapshot, with two nodes and it worked, also tried the previous commands and they solve the problem.

**Comment by lvca** [comment] 2015-07-30 18:27
@shlapkov could you please confirm this is closed?

**Comment by shlapkov** [comment] 2015-07-30 19:56
Hello @lvca not I am able to. After updating code from SVN for 2.0.x branch I am not able create database with remote connection: getting exception: jvm 1    | WrapperSimpleApp Error: Caused by: java.lang.IncompatibleClassChangeError: Expecting non-
static method com.orientechnologies.orient.core.index.OIndexManagerRemote.getDatabase()Lcom/orientec
hnologies/orient/core/db/ODatabaseDocumentInternal;
jvm 1    | WrapperSimpleApp Error:      at com.orientechnologies.orient.core.index.OIndexManagerRemo
te.createIndex(OIndexManagerRemote.java:63)
jvm 1    | WrapperSimpleApp Error:      at com.orientechnologies.orient.core.index.OIndexManagerProx
y.createIndex(OIndexManagerProxy.java:79)
jvm 1    | WrapperSimpleApp Error:      at com.orientechnologies.orient.core.metadata.schema.OClassI
mpl.createIndex(OClassImpl.java:1444)
jvm 1    | WrapperSimpleApp Error:      at com.orientechnologies.orient.core.metadata.schema.OClassI
mpl.createIndex(OClassImpl.java:1409)
jvm 1    | WrapperSimpleApp Error:      at com.orientechnologies.orient.core.metadata.schema.OClassI
mpl.createIndex(OClassImpl.java:1399)
jvm 1    | WrapperSimpleApp Error:      at com.orientechnologies.orient.core.metadata.schema.OClassI
mpl.createIndex(OClassImpl.java:1395)

**Comment by shlapkov** [comment] 2015-07-30 20:07
With plocal no issue to create db

**Comment by shlapkov** [comment] 2015-07-30 22:34
@lvca, @tglman issue with IncompatibleClassChangeError appears to be related to my local repository. After clean build I can create db no issues. I can rebuild all indexes no issues here. However I still see original issue:  jvm 1    | ERROR [OCommandExecutorSQLSelect] {db=spectrum} Error on using index IndexChain{platform-
DataflowStage0_idx, platform-Dataflow_pk} in query 'select @class, id, serverId, stageLabel, stageNa
me, stageId, dataflow, versions from platform-DataflowStage WHERE (dataflow.id = "Microflow_Sort_sf"
 AND versions CONTAINS "LatestSaved") SKIP 0 LIMIT 2147483647'. Probably you need to rebuild indexes
. Now executing query using cluster scan
jvm 1    | com.orientechnologies.orient.core.index.sbtree.local.OSBTreeException: Null keys are not
supported.
jvm 1    |      at com.orientechnologies.orient.core.index.sbtree.local.OSBTree.checkNullSupport(OSB
Tree.java:789) ~[orientdb-core-2.0.14-SNAPSHOT.jar:2.0.14-SNAPSHOT]
jvm 1    |      at com.orientechnologies.orient.core.index.sbtree.local.OSBTree.get(OSBTree.java:176
) ~[orientdb-core-2.0.14-SNAPSHOT.jar:2.0.14-SNAPSHOT]
jvm 1    |      at com.orientechnologies.orient.core.index.engine.OSBTreeIndexEngine.get(OSBTreeInde
xEngine.java:224) ~[orientdb-core-2.0.14-SNAPSHOT.jar:2.0.14-SNAPSHOT]
jvm 1    |      at com.orientechnologies.orient.core.index.OIndexMultiValues$1.nextEntry(OIndexMulti
Values.java:398) ~[orientdb-core-2.0.14-SNAPSHOT.jar:2.0.14-SNAPSHOT]
jvm 1    |      at com.orientechnologies.orient.core.sql.OChainedIndexProxy.cursorToList(OChainedInd
exProxy.java:367) ~[orientdb-core-2.0.14-SNAPSHOT.jar:2.0.14-SNAPSHOT]
jvm 1    |      at com.orientechnologies.orient.core.sql.OChainedIndexProxy.applyFirstIndex(OChained
IndexProxy.java:351) ~[orientdb-core-2.0.14-SNAPSHOT.jar:2.0.14-SNAPSHOT]
jvm 1    |      at com.orientechnologies.orient.core.sql.OChainedIndexProxy.applyTailIndexes(OChaine
dIndexProxy.java:338) ~[orientdb-core-2.0.14-SNAPSHOT.jar:2.0.14-SNAPSHOT]
jvm 1    |      at com.orientechnologies.orient.core.sql.OChainedIndexProxy.get(OChainedIndexProxy.j
ava:293) ~[orientdb-core-2.0.14-SNAPSHOT.jar:2.0.14-SNAPSHOT]
jvm 1    |      at com.orientechnologies.orient.core.sql.operator.OQueryOperatorEquals.executeIndexQ
uery(OQueryOperatorEquals.java:129) ~[orientdb-core-2.0.14-SNAPSHOT.jar:2.0.14-SNAPSHOT]
jvm 1    |      at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchForIndexes(
OCommandExecutorSQLSelect.java:1509) [orientdb-core-2.0.14-SNAPSHOT.jar:2.0.14-SNAPSHOT]
jvm 1    |      at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchInClasses(O
CommandExecutorSQLSelect.java:740) [orientdb-core-2.0.14-SNAPSHOT.jar:2.0.14-SNAPSHOT]
jvm 1    |      at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.assign
Target(OCommandExecutorSQLResultsetAbstract.java:194) [orientdb-core-2.0.14-SNAPSHOT.jar:2.0.14-SNAP
SHOT]
jvm 1    |      at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.assignTarget(OCom
mandExecutorSQLSelect.java:420) [orientdb-core-2.0.14-SNAPSHOT.jar:2.0.14-SNAPSHOT]
jvm 1    |      at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCo
mmandExecutorSQLSelect.java:402) [orientdb-core-2.0.14-SNAPSHOT.jar:2.0.14-SNAPSHOT]
jvm 1    |      at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandE
xecutorSQLSelect.java:373) [orientdb-core-2.0.14-SNAPSHOT.jar:2.0.14-SNAPSHOT]
jvm 1    |      at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OComman
dExecutorSQLDelegate.java:64) [orientdb-core-2.0.14-SNAPSHOT.jar:2.0.14-SNAPSHOT]
jvm 1    |      at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.ex
ecuteCommand(OAbstractPaginatedStorage.java:1191) [orientdb-core-2.0.14-SNAPSHOT.jar:2.0.14-SNAPSHOT
]
jvm 1    |      at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.co
mmand(OAbstractPaginatedStorage.java:1180) [orientdb-core-2.0.14-SNAPSHOT.jar:2.0.14-SNAPSHOT]
jvm 1    |      at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:71) [ori
entdb-core-2.0.14-SNAPSHOT.jar:2.0.14-SNAPSHOT]
jvm 1    |      at com.orientechnologies.orient.core.sql.query.OSQLSynchQuery.run(OSQLSynchQuery.jav
a:85) [orientdb-core-2.0.14-SNAPSHOT.jar:2.0.14-SNAPSHOT]
jvm 1    |      at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.jav
a:33) [orientdb-core-2.0.14-SNAPSHOT.jar:2.0.14-SNAPSHOT]
jvm 1    |      at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinar
y.command(ONetworkProtocolBinary.java:1183) [orientdb-server-2.0.14-SNAPSHOT.jar:2.0.14-SNAPSHOT]
jvm 1    |      at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinar
y.executeRequest(ONetworkProtocolBinary.java:390) [orientdb-server-2.0.14-SNAPSHOT.jar:2.0.14-SNAPSH
OT]
jvm 1    |      at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtoco
lAbstract.execute(OBinaryNetworkProtocolAbstract.java:217) [orientdb-server-2.0.14-SNAPSHOT.jar:2.0.
14-SNAPSHOT]
jvm 1    |      at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69) [orientd
b-core-2.0.14-SNAPSHOT.jar:2.0.14-SNAPSHOT]

**Comment by tglman** [comment] 2015-07-31 07:57
@shlapkov for solve this problem you need to recreate the index with the ignoreNullValues set at false:

```
drop index  platform-DataflowStage0_idx

create index platform-DataflowStage0_idx  on platform-DataflowStage(dataflow) NOTUNIQUE METADATA {"ignoreNullValues":false}
```

**Comment by lvca** [comment] 2015-07-31 08:34
@shlapkov Any chance to try the @tglman steps?

**Comment by shlapkov** [comment] 2015-07-31 14:13
So you are not going to fix the issue and we need to apply "workaround" to be able to use Orient do I understand this correctly? 

Not sure if it will work for use I need to discuss with our team.

**Comment by jillray7** [comment] 2015-07-31 15:01
The reason you are getting that error is the null support fix occurred in 2.0.9, so you have to drop and recreate the index as described. It should be a quick workaround. @tglman How do users avoid this issue in the future? Are we able to provide clearer documentation or perhaps detection of whether the database was created when this management was broken in order to apply the flag automatically?

**Comment by jillray7** [comment] 2015-07-31 16:21
@lvca see above please

**Comment by tglman** [comment] 2015-07-31 17:06
Hi all,
I tried to find a way to detect this issue, but is not possible because all the persistent data is correct, the only solution is drop and recreate the index with the correct flags.

**Comment by shlapkov** [comment] 2015-07-31 19:59
Hello @lvca, @jillray7 Can Orient provide a tool which will convert DB from 1.7.x to 2.0.x formats?

**Comment by jillray7** [comment] 2015-08-03 05:45
@tglman @lvca Can we add to the documentation to clearly explain this issue and the way to work around it, so that users know what to do before experiencing this exception? What kind of effort would it take to build a tool like @shlapkov is requesting?

**Comment by tglman** [comment] 2015-08-03 13:49
Hi @all,

I continued to investigate, and i found out that the problem could be solved in the query engine where the index chain is solved, the real issue was that if the lookup in the first index returned no result was going to call the second index with null key, the fix avoid that call.

So now is solved

**Comment by shlapkov** [comment] 2015-08-03 16:30
Hello #tglman now with 2.0.14-SNAPSHOT I am not see original issue. However, when I run rebuild all from studio I am getting exceptions: jvm 1    | INFO  [OIndexRebuildOutputListener] --> 6.11% progress, 5,479 indexed so far (547 items/s
ec)
jvm 1    | WARN  [OHazelcastDistributedDatabase] [node_VA005SH_AUS1_8080] timeout (60005ms) on waiti
ng for synchronous responses from nodes=[node_VA005SH_AUS1_8080] responsesSoFar=[] request=id=1364 f
rom=node_VA005SH_AUS1_8080 task=command_sql(REBUILD INDEX *) userName=admin
jvm 1    | WARN  [ODistributedResponseManager] [node_VA005SH_AUS1_8080] no response received from lo
cal node about request id=1364 from=node_VA005SH_AUS1_8080 task=command_sql(REBUILD INDEX *) userNam
e=admin
jvm 1    | WARN  [ODistributedResponseManager] [node_VA005SH_AUS1_8080] detected 1 node(s) in timeou
t or in conflict and quorum (1) has not been reached, rolling back changes for request (id=1364 from
=node_VA005SH_AUS1_8080 task=command_sql(REBUILD INDEX *) userName=admin)
jvm 1    | WARN  [ODistributedResponseManager] [node_VA005SH_AUS1_8080] Quorum 1 not reached for req
uest (id=1364 from=node_VA005SH_AUS1_8080 task=command_sql(REBUILD INDEX *) userName=admin). Elapsed
=60008ms No server in conflict. Received: {node_VA005SH_AUS1_8080=waiting-for-response}
jvm 1    | ERROR [ONetworkProtocolHttpDb] Internal server error:
jvm 1    | com.orientechnologies.orient.server.distributed.ODistributedException: Error on executing
 distributed request (id=1364 from=node_VA005SH_AUS1_8080 task=command_sql(REBUILD INDEX *) userName
=admin) against database 'spectrum.[]' to nodes [node_VA005SH_AUS1_8080]
jvm 1    | --> com.orientechnologies.orient.server.distributed.ODistributedException: Quorum 1 not r
eached for request (id=1364 from=node_VA005SH_AUS1_8080 task=command_sql(REBUILD INDEX *) userName=a
dmin). Elapsed=60008ms No server in conflict. Received: {node_VA005SH_AUS1_8080=waiting-for-response

**Comment by jillray7** [comment] 2015-08-04 12:17
@tglman @lvca Ideas on the comment above?

**Comment by tglman** [comment] 2015-08-04 13:50
Hi @shlapkov, 

From the error you posted seams that the rebuild index operation is failed for a timeout of 60005ms, but it should have a timeout of 86400000ms (1 day), I'll try to reproduce it and I'll let you know.

**Comment by lvca** [comment] 2015-08-04 13:51
Seems a timeout problem: the rebuild took more than 60 seconds. OrientDB 2.0 doesn't support per-command timeouts introduced in 2.1. Working on back-porting it.

**Comment by lvca** [comment] 2015-08-04 13:55
However in your case just ignore it: the command is not reverted, so the indexes are correctly rebuilt anyway.

**Comment by jillray7** [comment] 2015-08-04 14:24
Ok so @shlapkov canot ignore it for now because the command is not reverted. The indexes are fine. @lvca  has reopened this ticket to backport support per-command timeouts for 2.0.

**Comment by lvca** [comment] 2015-08-04 14:24
@tglman in 2.0 the timeout is 60 secs for any commands. I'm working on it ;-)

**Comment by shlapkov** [comment] 2015-08-04 15:19
No way to ignore it. After getting this exceptions on server side client dead.

**Comment by lvca** [comment] 2015-08-04 16:01
what do you mean foe "dead"?

**Comment by jillray7** [comment] 2015-08-04 19:05
@shlapkov Can you elaborate on why you cannot ignore the exception? What do you mean by "dead" client.

**Comment by shlapkov** [comment] 2015-08-04 19:41
@jillray7, @lvca Hard to said. Because with today build I am not able to verify this ticket at all see issue:
http://www.prjhub.com/#/issues/4907

**Comment by jillray7** [comment] 2015-08-06 07:02
@shlapkov Are you able to ignore the exception above now that 4907 is closed?

**Comment by shlapkov** [comment] 2015-08-06 13:52
Hello @jillray7 original issue fixed in 2.0.14-SNAPSHOT but we can't ignore exceptions. It produce errors on client and Orient studio UI. I think this issue can be closed but I submitted new on for exception during rebuild all: http://www.prjhub.com/#issues/4917

**Comment by lvca** [comment] 2015-08-07 01:01
Forwarded to @tglman

**Comment by tglman** [comment] 2015-08-07 11:14
yes i think we can close this.

**Closed by tglman** 2015-08-07 11:14 UTC
Labels: bug
