### ISSUE TITLE
Selecting edges doesn't throw error if class name is misspelled

### ISSUE THREAD

**Issue by garrett-gottlieb** [orientechnologies/orientdb#2988] opened 2014-10-28 03:21 UTC
`select out(PostHasComment) from #18:9` and `select out(PostHasCommmmmmmmmmment) from #18:9` return the same thing for me. Instead of throwing an error that the class is not found, it returns all the out()s.

**Comment by lvca** [comment] 2015-07-03 22:58
Not high priority, postponed.

**Comment by luigidellaquila** [comment] 2016-05-23 15:35
It's not a bug, that syntax is accepted and valid in a schemaless database.

The query 

```
select out(PostHasComment) from #18:9 
```
will evaluate `PostHasComment` attribute of each record, cast it to string and use it as an edge class name.

It can seem strange, but it's valid in schemaless SQL

Closing

Thanks

Luigi

**Closed by luigidellaquila** 2016-05-23 15:35 UTC
Labels: bug
