### ISSUE TITLE
Last position of provided data interval [2988528] is more than size of allocated area [65552]

### ISSUE THREAD

**Issue by adithyank** [orientechnologies/orientdb#3190] opened 2014-12-13 17:57 UTC
OrientDB version : 2.0-M3
JDK : Oracle JDK 1.7.0_55
OS : CentOS 6.5

The below Exception came during commit......

```
ERROR [2014-12-07T17:31:57,232] : [InventoryDataPersister] : InventoryDataPersister: saveDAOData(): catching
com.orientechnologies.orient.core.exception.OStorageException
        at com.orientechnologies.orient.core.index.hashindex.local.OLocalHashTable.put(OLocalHashTable.java:442) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.index.engine.OHashTableIndexEngine.put(OHashTableIndexEngine.java:160) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.index.OIndexMultiValues.commitSnapshot(OIndexMultiValues.java:255) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.index.OIndexAbstract.commit(OIndexAbstract.java:643) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic$CommitIndexesCallback.run(OTransactionOptimistic.java:98) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:864) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:455) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:142) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2261) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2231) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at in.co.nmsworks.documenttdb.db.DocDB.commit(DocDB.java:366) ~[cygnetOTNMS.jar:?]
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.store.RcaInvWriter.addAll(RcaInvWriter.java:71) ~[cygnetOTNMS.jar:?]
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.dao.InventoryDAO.save(InventoryDAO.java:122) ~[cygnetOTNMS.jar:?]
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.queue.InventoryDataPersister.saveDAOData(InventoryDataPersister.java:192) [cygnetOTNMS.jar:?]
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.queue.InventoryDataPersister.processAddition(InventoryDataPersister.java:166) [cygnetOTNMS.jar:?]
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.queue.InventoryDataPersister.run(InventoryDataPersister.java:68) [cygnetOTNMS.jar:?]
Caused by: com.orientechnologies.common.directmemory.ODirectMemoryViolationException: Last position of provided data interval [2988528] is more than size of allocated area [65552]
        at com.orientechnologies.common.directmemory.ODirectMemoryPointer.rangeCheck(ODirectMemoryPointer.java:219) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.common.directmemory.ODirectMemoryPointer.get(ODirectMemoryPointer.java:77) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.common.serialization.types.OStringSerializer.deserializeFromDirectMemoryObject(OStringSerializer.java:147) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.common.serialization.types.OStringSerializer.deserializeFromDirectMemoryObject(OStringSerializer.java:31) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.deserializeFromDirectMemory(ODurablePage.java:117) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.index.hashindex.local.OHashIndexBucket.getEntry(OHashIndexBucket.java:128) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.index.hashindex.local.OHashIndexBucket$EntryIterator.next(OHashIndexBucket.java:350) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.index.hashindex.local.OHashIndexBucket$EntryIterator.next(OHashIndexBucket.java:333) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.index.hashindex.local.OLocalHashTable.splitBucketContent(OLocalHashTable.java:1891) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.index.hashindex.local.OLocalHashTable.splitBucket(OLocalHashTable.java:1953) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.index.hashindex.local.OLocalHashTable.doPut(OLocalHashTable.java:1543) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.index.hashindex.local.OLocalHashTable.put(OLocalHashTable.java:434) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        ... 15 more
```

When I tried to further narrow-down the cause of the issue,

I observed the below things

1. When I try to write the below ODocument this Exception comes
  * DocumentType name : POR_SEQUENCE
  * It has two indices
     * one UNIQUE_HASH_INDEX on key
     * another NOTUNIQUE_HASH_INDEX on patternKey
  * Fields and values of the doc : {patternKey=**61fd7608bf1ccf970462af1975ea3f53**, index=1, lookedUpNode=false, patternEntityType=DER_PAT_SEQUENCE, classifier=PORTION, circuitOrSNCName=ckt-233044-29-Nov-2014-13-14-58-Member, type=POR_SEQUENCE, key=58ccde588c976e3bb9ec9878e7de2571}
2. Stack trace shows OIndexMultiValues. So, I conclude that why trying to process the value of patternKey field above (whose value is '61fd7608bf1ccf970462af1975ea3f53'), this Exception is thrown
3. When I insert this record in a empty database, the insertion is successful. If I try to insert this again and again in the database, where I observed this issue, this Exception is coming always.
4. Following files are available for this type inside the database dir

```
-rw-rw-r-- 1 cygnet cygnet  17M Dec 13 18:20 POR_SEQUENCE.key0.hib
-rw-rw-r-- 1 cygnet cygnet  33M Dec 13 18:20 POR_SEQUENCE.key1.hib
-rw-rw-r-- 1 cygnet cygnet  65M Dec 13 18:20 POR_SEQUENCE.key2.hib
-rw-rw-r-- 1 cygnet cygnet  65K Dec 13 18:20 POR_SEQUENCE.key.him
-rw-rw-r-- 1 cygnet cygnet  65K Dec 13 18:20 POR_SEQUENCE.key.hit
-rw-rw-r-- 1 cygnet cygnet  17M Dec 13 18:20 POR_SEQUENCE.patternKey0.hib
-rw-rw-r-- 1 cygnet cygnet 275M Dec 13 18:20 POR_SEQUENCE.patternKey1.hib
-rw-rw-r-- 1 cygnet cygnet  65K Dec 13 18:20 POR_SEQUENCE.patternKey.him
-rw-rw-r-- 1 cygnet cygnet  65K Dec 13 18:20 POR_SEQUENCE.patternKey.hit
-rw-rw-r-- 1 cygnet cygnet 7.6M Dec 13 18:20 POR_SEQUENCE.patternKey.irs
-rw-rw-r-- 1 cygnet cygnet 6.1M Dec 13 18:20 por_sequence.cpm
-rw-rw-r-- 1 cygnet cygnet 515M Dec 13 18:20 por_sequence.pcl
```

Will you be able to have some clue with this information !

**Comment by laa** [comment] 2015-01-06 06:25
Hi,
Could you provide data log and program to reproduce given issue ?

**Comment by adithyank** [comment] 2015-01-06 07:03
I am working on it now.

**Comment by adithyank** [comment] 2015-01-06 07:49
> I will do the following exercise again and update the results...
>
> 1. Using a standalone code, I will take all the records from this table POR_SEQUENCE of the created database and create a new database and write only these records. I will not populate other tables of this database. This standalone JVM will not have any Xmx configured
> 2. After writing all the records only from POR_SEQUENCE table of the main DB to this new database, I will run the same main() method and update the results

When I did this, I am not getting this ODirectMemoryViolation Exception. All the records are inserted fully.

I did this exercise in the below ways

1. one time with Xmx4g and 1000 records in one transaction
2. another time with Xmx17g and 1000 records in one transaction
3. another time with Xmx17g and 100 records in one transaction

What else can I do to reproduce this?

**Comment by adithyank** [comment] 2015-01-06 07:52
I observed another thing when I did the above exercise.

In the offline data I took from the POR_SEQUENCE class of the orinetdb database, there were lot of duplicate records in the field in which UNIQUE_HASH_INDEX is available.

You may say that it may be due to this ODirectMemoryViolation. But, we are calling rollback() methods properly. In that case, how can these duplicate records stay in the database. Should i open another issue for this duplicate records?

Pls advice

**Comment by laa** [comment] 2015-01-06 11:35
Hi,
We need to reproduce this issue because you are only user which has such problem.
Could you send me log with data which you use to reproduce this issue and program which you used for this exercise ?

**Comment by laa** [comment] 2015-01-09 05:22
We have several similar issues , but can not reproduce them. Could we concrete on reproducing this specific issue, and probably find reason for rest of them. Could you send me code and data log which you use to reproduce given issue and I will start to work on it ASAP. Will really appreciate your help.

**Comment by adithyank** [comment] 2015-01-09 10:50
The following are my issues in getting you the required data

1. The Exception is not coming every time
2. What we store in OrientDB is not readily available data. It is a processed data from some other source data.

So, I am writing code to serialize and dump in flat files all the data. I am running that process repeatedly to expect the Exception. Then, I will be able to give it.

Pls give me some time. I will give you the data and independent code to reproduce the issue, for sure.

**Comment by laa** [comment] 2015-01-12 10:11
Thank you very much. I do appreciate your help.

**Comment by laa** [comment] 2015-01-19 17:58
Close it because it is not reporducable, but feel free to reopen it.

**Closed by laa** 2015-01-19 17:58 UTC
Labels: bug, core

**Comment by kishykumar** [comment] 2017-04-13 06:16
Hit this issue when "saving" the ODocument. OrientDB 1.7.0. 

```
2017-04-12 22:48:23,786 -  ERROR! creating the object: com.orientechnologies.orient.core.exception.OStorageException: File with id 105 does not exist.
  at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.openFile(OWOWCache.java:529)
  at com.orientechnologies.orient.core.index.hashindex.local.cache.OReadWriteDiskCache.openFile(OReadWriteDiskCache.java:125)
  at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.create(OSBTreeBonsaiLocal.java:134)
  at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.create(OSBTreeBonsaiLocal.java:119)
  at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OIndexRIDContainerSBTree.<init>(OIndexRIDContainerSBTree.java:52)
  at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OIndexRIDContainer.convertToSbTree(OIndexRIDContainer.java:201)
  at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OIndexRIDContainer.checkTopThreshold(OIndexRIDContainer.java:174)
  at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OIndexRIDContainer.add(OIndexRIDContainer.java:117)
  at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OIndexRIDContainer.add(OIndexRIDContainer.java:36)
  at com.orientechnologies.orient.core.index.OIndexMultiValues.put(OIndexMultiValues.java:116)
  at com.orientechnologies.orient.core.index.OIndexMultiValues.put(OIndexMultiValues.java:46)
  at com.orientechnologies.orient.core.tx.OTransactionNoTx.addIndexEntry(OTransactionNoTx.java:188)
  at com.orientechnologies.orient.core.index.OIndexTxAware.put(OIndexTxAware.java:94)
  at com.orientechnologies.orient.core.index.OIndexTxAware.put(OIndexTxAware.java:38)
  at com.orientechnologies.orient.core.index.OClassIndexManager.processIndexUpdateFieldAssignment(OClassIndexManager.java:402)
  at com.orientechnologies.orient.core.index.OClassIndexManager.processSingleIndexUpdate(OClassIndexManager.java:368)
  at com.orientechnologies.orient.core.index.OClassIndexManager.updateIndexEntries(OClassIndexManager.java:155)
  at com.orientechnologies.orient.core.index.OClassIndexManager.onRecordAfterUpdate(OClassIndexManager.java:130)
  at com.orientechnologies.orient.core.hook.ODocumentHookAbstract.onTrigger(ODocumentHookAbstract.java:270)
  at com.orientechnologies.orient.core.db.record.ODatabaseRecordAbstract.callbackHooks(ODatabaseRecordAbstract.java:1466)
  at com.orientechnologies.orient.core.db.record.ODatabaseRecordAbstract.executeSaveRecord(ODatabaseRecordAbstract.java:1138)
  at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:84)
  at com.orientechnologies.orient.core.db.record.ODatabaseRecordTx.save(ODatabaseRecordTx.java:322)
  at com.orientechnologies.orient.core.db.record.ODatabaseRecordTx.save(ODatabaseRecordTx.java:40)
  at com.orientechnologies.orient.core.record.ORecordAbstract.save(ORecordAbstract.java:335)
  at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1439)
  at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1428)
  at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1417)
  at com.baasbox.dao.NodeDao.save(NodeDao.java:171)
  at com.baasbox.dao.business.ObjectDao.save(ObjectDao.java:76)

```

**Comment by kishykumar** [comment] 2017-04-13 06:20
Is there a workaround for this issue on OrientDB 1.7.0?

**Comment by laa** [comment] 2017-04-13 06:40
Hi @kishykumar for OrientDB 1.7.0 you need to make export/import from to JSON to fix this issue.

**Comment by kishykumar** [comment] 2017-04-13 06:51
What does "make export/import from to JSON" mean?

**Comment by kishykumar** [comment] 2017-04-13 08:10
Thanks. It works. I figured out it's IMPORT AND EXPORT database. :)

**Comment by kishykumar** [comment] 2017-11-19 05:41
@laa Andrey, has this issue been fixed in a recent release of orientdb? I hit this issue once a month. I Once we go live, I don't know how to deal with this issue as this issue completely stops all save() operations in the db. Can you recommend what to do here?

**Comment by laa** [comment] 2017-11-20 02:28
Hi @kishykumar you need not only to make export/import but to migrate to the latest version. Sorry I did not write you in my last message. The 1.7 version is very old and lacks many critical features.
