### ISSUE TITLE
Dead database after ungraceful shutdown or 3.0.14: OEmptyWALRecord

### ISSUE THREAD

**Issue by andreyvk** [orientechnologies/orientdb#8935] opened 2019-07-02 08:12 UTC
### OS: Ubuntu 18.04

Hi,

We're getting an exception on our database after server shut down abruptly:

```
2019-07-02 08:00:01:914 INFO  Looking for last checkpoint... [OLocalPaginatedStorage]Exception during storage data restore
com.orientechnologies.orient.core.exception.OStorageException: Unknown checkpoint record type com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OEmptyWALRecord
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.restoreFromWAL(OAbstractPaginatedStorage.java:5297)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.recoverIfNeeded(OAbstractPaginatedStorage.java:4504)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:374)
        at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthenticate(OrientDBEmbedded.java:210)
        at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthenticate(OrientDBEmbedded.java:60)
        at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:936)
        at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:913)
        at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeDatabaseOpen(OConnectionBinaryExecutor.java:1144)
        at com.orientechnologies.orient.client.remote.message.OOpenRequest.execute(OOpenRequest.java:150)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:304)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:206)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
Exception `737183F2` in storage `plocal:/ns0/orientdb/orientdb-3.0.14/databases/prod`: 3.0.14 - Veloce (build ac128c5a9ba4c6dc9d25a32b92962d8863774423, branch 3.0.x)
com.orientechnologies.orient.core.exception.OStorageException: Unknown checkpoint record type com.orientechnologies.orient.core.storage.impl.local.paginated.wal.cas.OEmptyWALRecord
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.restoreFromWAL(OAbstractPaginatedStorage.java:5297)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.recoverIfNeeded(OAbstractPaginatedStorage.java:4504)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:374)
        at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthenticate(OrientDBEmbedded.java:210)
        at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthenticate(OrientDBEmbedded.java:60)
        at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:936)
        at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:913)
        at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeDatabaseOpen(OConnectionBinaryExecutor.java:1144)
        at com.orientechnologies.orient.client.remote.message.OOpenRequest.execute(OOpenRequest.java:150)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:304)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:206)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
```

**Comment by laa** [comment] 2019-07-02 08:30
Hi, that means that you created a database under the version bigger and use under the version lower than it was created. Please use lates 3.0.21 and that issue will be fixed.

**Comment by andreyvk** [comment] 2019-07-02 08:50
@laa ,

Pretty sure that's not the case. It's was a copy of db from 3.0.12 and we upped the version to 3.0.14.

**Comment by laa** [comment] 2019-07-02 08:56
Hi, @andreyvk record detection based on `instanceof` operator of Java. That means that you either have an older version of mix of libraries on classpath. I am quite sure that this error is absent in distribution because this functionality was tested many times both in production and during the running of test cases.

**Comment by andreyvk** [comment] 2019-07-02 09:20
Hi, @laa it was a fresh instance of ubuntu 18.04 and only a single DB was installed there. Normally I wouldnt mix any libraries on purpose.  

Btw, it's not possible to move to 3.0.21 because of the PhpOrient driver, which doesnt behave well once you up to the latest version + I cant move to the REST protocol, because it's not feasible with the workaround available (see #8762). It's pretty much a dead end.

**Comment by laa** [comment] 2019-07-02 09:33
Hi, @andreyvk could you crash database and send it to me so I will reproduce the issue on your version?

**Comment by laa** [comment] 2019-07-02 09:35
Please do not restore it of course or an exception will dissappear.

**Comment by laa** [comment] 2019-07-12 14:11
Hi @andreyvk any updates on that? Will you send a broken database?

**Comment by laa** [comment] 2019-08-01 19:41
Hi @andreyvk any updates on that? Will you send a broken database?

**Comment by laa** [comment] 2020-06-12 13:59
Closed, because of no answer.

**Closed by laa** 2020-06-12 13:59 UTC
Labels: waiting reply
