### ISSUE TITLE
Escaped quotes not processed correctly in JSON 

### ISSUE THREAD

**Issue by rore** [orientechnologies/orientdb#1787] opened 2013-11-02 19:42 UTC
Version 1.6. 
Updating the following JSON using the REST api (sql command) :

create vertex Post content {
    "text" : "\"‎ה, כן?...‎\""
}

Getting an error:

Internal server error:
com.orientechnologies.orient.core.exception.OSerializationException: Error on unmarshalling JSON content: wrong format. Use <field> : <value> [ONetworkProtocolHttpDb]

**Comment by luigidellaquila** [comment] 2015-02-26 13:56
there is a regression on this in 2.1. It will be addressed ASAP

**Comment by luigidellaquila** [comment] 2015-07-06 11:51
I added a test case for this and it seems to be fixed.

**Comment by luigidellaquila** [comment] 2015-07-07 12:54
reopening, it works fine on my Mac but not on the CI machine, it must be a matter of charset

**Comment by kiejo** [comment] 2015-10-24 10:54
Are there any suggested workarounds for this bug? Can we expect this to be fixed in the 2.2 release?
I'm running OrientDB 2.1.4 on Ubuntu 14.04 and it's causing me problems.

**Comment by luigidellaquila** [comment] 2015-10-26 08:02
Hi @kiejo 

The only thing I can suggest is to try to play with charsets on your machine. The problem here is that I was still not able to reproduce the problem on my machine, while on other machines the exact same test case fails...

Thanks

Luigi

**Closed** 2021-08-04 09:10 UTC
Labels: bug
