### ISSUE TITLE
Long built time

### ISSUE THREAD

**Issue by mlawsonca** [orientechnologies/orientdb#9551] opened 2021-02-27 08:30 UTC
## Expected behavior  
Builds in under 1 hour

## Actual behavior  
Has not build after more than 3 hours

## Steps to reproduce  
```
git clone https://github.com/orientechnologies/orientdb
cd orientdb/
git checkout develop
mvn clean install -DskipTests
```

It is hanging on 
`exec-maven-plugin:1.4.0:exec (build-db) @ orientdb-community`

**Comment by luigidellaquila** [comment] 2021-03-01 09:06
Hi @mlawsonca 

That is strange, we have a few different installations (local machines, Jenkins and more) and all them can perform this task properly.
I think we will need some more details to understand where the problem is.
As a quick test, I'd suggest to try with Java 8 and see if it succeeds

Thanks

Luigi

**Comment by tglman** [comment] 2022-06-15 14:29
Hi,

A while ago we had some build problems, should all be fixed right now, closing this, feel free to re-open it if you experience still the problems.

Regards

**Closed as completed by tglman** 2022-06-15 14:29 UTC
