### ISSUE TITLE
Index Engine error at startup for OrientDB 2.2.0

### ISSUE THREAD

**Issue by laa** [orientechnologies/orientdb#6202] opened 2016-05-24 11:16 UTC
I just upgraded to OrientDB 2.2.0 GA release from OrientDB 2.2.0-beta. Now every time I start my application with embeded OrientDB, I see the error message below

SEVERE: $ANSI{green {db=$graphdb}} Index 'expressible.name' cannot be created and will be removed from configuration

Then immediately follow that I will see a warning

WARNING: $ANSI{green {db=$graphdb}} Index engine with name 'expressible.name' already contained in database configuration

OrientDB seems up and running correctly. However, every time I restart my application, I will see the exact same error and warning. Just wondering what it is and I could get rid of it.

Thanks,

Tai

**Comment by laa** [comment] 2016-05-25 10:23
Hi could you download this link and send me stack trace of exception which you see https://drive.google.com/file/d/0B2oZq2xVp841S2RyaFlCd05PTDg/view?usp=sharing

**Comment by taihu** [comment] 2016-06-01 23:23
Sorry, I did not see your message until today. Here is the exception

Jun 01, 2016 7:20:29 PM com.orientechnologies.common.log.OLogManager log
INFO: OrientDB auto-config DISKCACHE=7,139MB (heap=7,196MB direct=8,096MB os=16,384MB)
Jun 01, 2016 7:20:30 PM com.orientechnologies.common.log.OLogManager log
SEVERE: $ANSI{green {db=$Users$hutai$Documents$Vero Projects$Test Project$verodb}} Error during load of index 'datasource.name'
com.orientechnologies.orient.core.exception.OStorageException: Cannot put key value entry in index
	Storage URL="plocal:$Users$hutai$Documents$Vero Projects$Test Project$verodb"
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doCallIndexEngine(OAbstractPaginatedStorage.java:1859)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.callIndexEngine(OAbstractPaginatedStorage.java:1827)
	at com.orientechnologies.orient.core.index.OIndexAbstract.onIndexEngineChange(OIndexAbstract.java:1027)
	at com.orientechnologies.orient.core.index.OIndexAbstract.loadFromConfiguration(OIndexAbstract.java:316)
	at com.orientechnologies.orient.core.index.OIndexManagerShared.fromStream(OIndexManagerShared.java:414)
	at com.orientechnologies.orient.core.type.ODocumentWrapperNoClass.reload(ODocumentWrapperNoClass.java:74)
	at com.orientechnologies.orient.core.index.OIndexManagerAbstract.load(OIndexManagerAbstract.java:85)
	at com.orientechnologies.orient.core.index.OIndexManagerAbstract.load(OIndexManagerAbstract.java:57)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault$2.call(OMetadataDefault.java:191)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault$2.call(OMetadataDefault.java:181)
	at com.orientechnologies.common.concur.resource.OSharedContainerImpl.getResource(OSharedContainerImpl.java:58)
	at com.orientechnologies.orient.core.storage.OStorageAbstract.getResource(OStorageAbstract.java:149)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault.init(OMetadataDefault.java:181)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault.load(OMetadataDefault.java:89)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.initAtFirstOpen(ODatabaseDocumentTx.java:3004)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:243)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPolled.internalOpen(OPartitionedDatabasePool.java:140)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.openDatabase(OPartitionedDatabasePool.java:394)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire(OPartitionedDatabasePool.java:353)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.<init>(OrientBaseGraph.java:140)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphNoTx.<init>(OrientGraphNoTx.java:62)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.getNoTx(OrientGraphFactory.java:149)
	at com.vero.model.graph.GraphDB.getDb(GraphDB.java:54)
	at com.vero.model.graph.GraphOps.findVertexWhere(GraphOps.java:184)
	at com.vero.model.graph.GraphOps.findFirstWhere(GraphOps.java:169)
	at com.vero.model.services.AbstractModelService.findByName(AbstractModelService.java:70)
	at com.vero.client.service.ModelService.getProjectByName(ModelService.java:77)
	at com.vero.client.service.ProjectService.updateRootProject(ProjectService.java:386)
	at com.vero.client.service.ProjectService.setProject(ProjectService.java:356)
	at com.vero.client.VeroClient$1.call(VeroClient.java:151)
	at com.vero.client.VeroClient$1.call(VeroClient.java:1)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.orientechnologies.lucene.engine.OLuceneIndexEngineDelegate.init(OLuceneIndexEngineDelegate.java:201)
	at com.orientechnologies.orient.core.index.OIndexAbstract$1.callEngine(OIndexAbstract.java:1030)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doCallIndexEngine(OAbstractPaginatedStorage.java:1848)
	... 33 more

Jun 01, 2016 7:20:30 PM com.orientechnologies.common.log.OLogManager log
WARNING: $ANSI{green {db=$Users$hutai$Documents$Vero Projects$Test Project$verodb}} Cannot load index 'datasource.name' rebuilt it from scratch
Jun 01, 2016 7:20:30 PM com.orientechnologies.common.log.OLogManager log
SEVERE: $ANSI{green {db=$Users$hutai$Documents$Vero Projects$Test Project$verodb}} Error during index 'datasource.name' delete
Jun 01, 2016 7:20:30 PM com.orientechnologies.common.log.OLogManager log
SEVERE: $ANSI{green {db=$Users$hutai$Documents$Vero Projects$Test Project$verodb}} Error during index rebuild
java.lang.NullPointerException
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doClearIndex(OAbstractPaginatedStorage.java:1767)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.clearIndex(OAbstractPaginatedStorage.java:1754)
	at com.orientechnologies.orient.core.index.OIndexAbstract.rebuild(OIndexAbstract.java:449)
	at com.orientechnologies.orient.core.index.OIndexAbstract.rebuild(OIndexAbstract.java:377)
	at com.orientechnologies.orient.core.index.OIndexAbstract.loadFromConfiguration(OIndexAbstract.java:325)
	at com.orientechnologies.orient.core.index.OIndexManagerShared.fromStream(OIndexManagerShared.java:414)
	at com.orientechnologies.orient.core.type.ODocumentWrapperNoClass.reload(ODocumentWrapperNoClass.java:74)
	at com.orientechnologies.orient.core.index.OIndexManagerAbstract.load(OIndexManagerAbstract.java:85)
	at com.orientechnologies.orient.core.index.OIndexManagerAbstract.load(OIndexManagerAbstract.java:57)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault$2.call(OMetadataDefault.java:191)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault$2.call(OMetadataDefault.java:181)
	at com.orientechnologies.common.concur.resource.OSharedContainerImpl.getResource(OSharedContainerImpl.java:58)
	at com.orientechnologies.orient.core.storage.OStorageAbstract.getResource(OStorageAbstract.java:149)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault.init(OMetadataDefault.java:181)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault.load(OMetadataDefault.java:89)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.initAtFirstOpen(ODatabaseDocumentTx.java:3004)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:243)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPolled.internalOpen(OPartitionedDatabasePool.java:140)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.openDatabase(OPartitionedDatabasePool.java:394)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire(OPartitionedDatabasePool.java:353)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.<init>(OrientBaseGraph.java:140)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphNoTx.<init>(OrientGraphNoTx.java:62)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.getNoTx(OrientGraphFactory.java:149)
	at com.vero.model.graph.GraphDB.getDb(GraphDB.java:54)
	at com.vero.model.graph.GraphOps.findVertexWhere(GraphOps.java:184)
	at com.vero.model.graph.GraphOps.findFirstWhere(GraphOps.java:169)
	at com.vero.model.services.AbstractModelService.findByName(AbstractModelService.java:70)
	at com.vero.client.service.ModelService.getProjectByName(ModelService.java:77)
	at com.vero.client.service.ProjectService.updateRootProject(ProjectService.java:386)
	at com.vero.client.service.ProjectService.setProject(ProjectService.java:356)
	at com.vero.client.VeroClient$1.call(VeroClient.java:151)
	at com.vero.client.VeroClient$1.call(VeroClient.java:1)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

Jun 01, 2016 7:20:30 PM com.orientechnologies.common.log.OLogManager log
SEVERE: $ANSI{green {db=$Users$hutai$Documents$Vero Projects$Test Project$verodb}} Cannot rebuild index 'datasource.name' because 'com.orientechnologies.orient.core.index.OIndexException: Error on rebuilding the index for clusters: [datasource]
	Storage URL="plocal:$Users$hutai$Documents$Vero Projects$Test Project$verodb"'. The index will be removed in configuration
com.orientechnologies.orient.core.exception.OStorageException: Cannot put key value entry in index
	Storage URL="plocal:$Users$hutai$Documents$Vero Projects$Test Project$verodb"
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doCallIndexEngine(OAbstractPaginatedStorage.java:1859)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.callIndexEngine(OAbstractPaginatedStorage.java:1827)
	at com.orientechnologies.orient.core.index.OIndexAbstract.onIndexEngineChange(OIndexAbstract.java:1027)
	at com.orientechnologies.orient.core.index.OIndexAbstract.loadFromConfiguration(OIndexAbstract.java:316)
	at com.orientechnologies.orient.core.index.OIndexManagerShared.fromStream(OIndexManagerShared.java:414)
	at com.orientechnologies.orient.core.type.ODocumentWrapperNoClass.reload(ODocumentWrapperNoClass.java:74)
	at com.orientechnologies.orient.core.index.OIndexManagerAbstract.load(OIndexManagerAbstract.java:85)
	at com.orientechnologies.orient.core.index.OIndexManagerAbstract.load(OIndexManagerAbstract.java:57)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault$2.call(OMetadataDefault.java:191)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault$2.call(OMetadataDefault.java:181)
	at com.orientechnologies.common.concur.resource.OSharedContainerImpl.getResource(OSharedContainerImpl.java:58)
	at com.orientechnologies.orient.core.storage.OStorageAbstract.getResource(OStorageAbstract.java:149)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault.init(OMetadataDefault.java:181)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault.load(OMetadataDefault.java:89)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.initAtFirstOpen(ODatabaseDocumentTx.java:3004)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:243)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPolled.internalOpen(OPartitionedDatabasePool.java:140)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.openDatabase(OPartitionedDatabasePool.java:394)
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire(OPartitionedDatabasePool.java:353)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.<init>(OrientBaseGraph.java:140)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphNoTx.<init>(OrientGraphNoTx.java:62)
	at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.getNoTx(OrientGraphFactory.java:149)
	at com.vero.model.graph.GraphDB.getDb(GraphDB.java:54)
	at com.vero.model.graph.GraphOps.findVertexWhere(GraphOps.java:184)
	at com.vero.model.graph.GraphOps.findFirstWhere(GraphOps.java:169)
	at com.vero.model.services.AbstractModelService.findByName(AbstractModelService.java:70)
	at com.vero.client.service.ModelService.getProjectByName(ModelService.java:77)
	at com.vero.client.service.ProjectService.updateRootProject(ProjectService.java:386)
	at com.vero.client.service.ProjectService.setProject(ProjectService.java:356)
	at com.vero.client.VeroClient$1.call(VeroClient.java:151)
	at com.vero.client.VeroClient$1.call(VeroClient.java:1)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.orientechnologies.lucene.engine.OLuceneIndexEngineDelegate.init(OLuceneIndexEngineDelegate.java:201)
	at com.orientechnologies.orient.core.index.OIndexAbstract$1.callEngine(OIndexAbstract.java:1030)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doCallIndexEngine(OAbstractPaginatedStorage.java:1848)
	... 33 more

**Comment by robfrank** [comment] 2016-06-02 08:57
This problem should be resolved in next 2.2.1. In the meanwhile, could you try with latests snapshot?
You can download from: https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-community/2.2.1-SNAPSHOT/orientdb-community-2.2.1-20160601.231400-49.tar.gz

**Comment by taihu** [comment] 2016-06-03 04:23
Thanks so much for the fix. When will 2.2.1 will be released?

Thanks,

Tai

**Comment by maggiolo00** [comment] 2016-06-15 15:46
@taihu 

OrientDB 2.2.2 is available [here](http://orientdb.com/download/).
Can you confirm that is fixed?

**Comment by maggiolo00** [comment] 2016-06-22 14:24
@taihu 

did you have the chance to try it with OrientDB 2.2.2/3?

Thanks

**Comment by taihu** [comment] 2016-06-22 16:02
Enrico,
      I could not try that yet. It is because I have much bigger problem with OrientDB which prevent me from upgrading to OrientDB 2.2.x release. My application works perfectly fine in OrientDB 2.2.0-beta. However, after I upgraded to OrientDB official 2.2.x release. My newly created vertices cannot be shown in our UI. I investigated issue and do not know what cause it. But I found that for all those newly created vertices, the edge information is only stored in one of two ends. So it depends on how I traverse the graph, if I am coming from vertex with edge information, I could reach the other end of edge. However, I could traverse starting from the other end. Do you have any idea what could cause this?

Thanks,

Tai

**Comment by maggiolo00** [comment] 2016-06-22 16:12
Do you have some logs / exception?

How do you create edges?

Do you use Tx or noTX?

**Comment by taihu** [comment] 2016-06-22 16:19
There is no exception at all. I am using Tx (embedded OrientDB instance) and I also made sure that I called shutdown() method on Graph instance. I also noticed that on the same thread I created these vertices, I could see them. However, from other thread I could not see those vertices at all (I already committed changes, before OrientDB 2.2.x official release, it worked. Other thread could see those vertices). If I shut down my application and restart, then no one could see those newly created vertices at all.

Thanks,

Tai

**Comment by maggiolo00** [comment] 2016-06-22 16:42
do you have some code snippet?
or some way to reproduce this issue?

**Comment by maggiolo00** [comment] 2016-06-30 18:10
@taihu let me know if you need some help.
If the issue is different from this one please advice me so i can close this and open another

Thanks

**Comment by taihu** [comment] 2016-06-30 19:22
Enrico,
     Thanks so much for your help. I will try to extract out some sample
code to reproduce this issue. For the original issue referred in this email
thread, it is fixed.

Thanks,

Tai

**Comment by maggiolo00** [comment] 2016-07-04 10:23
ok @taihu 
I'm closing this. Open a new issue for the other problem
Thanks

**Closed by maggiolo00** 2016-07-04 10:23 UTC
Labels: bug, waiting reply

**Comment by hosseinGanjyar** [comment] 2017-12-26 11:46
I've same problem since insert data to index column...
