### ISSUE TITLE
Please support DEFAULT values for column types via SQL

### ISSUE THREAD

**Issue by vertex-github** [orientechnologies/orientdb#3577] opened 2015-02-12 18:49 UTC
Current SQL support doesn't seem to support DEFAULT keyword.  Being able to set default values for numbers, strings and most importantly timestamps, is a significant assistance during development and continual production upgrades (for instance, changing a column/field from not required to required requires the provision of default values for all existing rows)

**Comment by lvca** [comment] 2015-02-12 19:00
duplicate of #665

**Closed by lvca** 2015-02-12 19:00 UTC
