### ISSUE TITLE
maybe a bug when i select entire index in console?

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#7624] opened 2017-08-07 19:48 UTC
### OrientDB Version: 3

select from index:i.a                   

Error: com.orientechnologies.orient.core.index.sbtree.local.OSBTreeException: Null keys are not supported.

**Comment by laa** [comment] 2017-08-07 19:50
@publicocean0 do you have a full stack trace ?

**Comment by laa** [comment] 2017-08-07 19:51
it should be in the log file for client or server

**Comment by publicocean0** [comment] 2017-08-07 19:54
$ANSI{green {db=s}} Exception `4A0E06E5` in storage `s`
com.orientechnologies.orient.core.index.sbtree.local.OSBTreeException: Null keys are not supported.
	DB name="s"
	Component Name="c.id"
	at com.orientechnologies.orient.core.index.sbtree.local.OSBTree.checkNullSupport(OSBTree.java:963)
	at com.orientechnologies.orient.core.index.sbtree.local.OSBTree.get(OSBTree.java:191)
	at com.orientechnologies.orient.core.index.engine.OSBTreeIndexEngine.get(OSBTreeIndexEngine.java:129)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doGetIndexValue(OAbstractPaginatedStorage.java:2095)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.getIndexValue(OAbstractPaginatedStorage.java:2077)
	at com.orientechnologies.orient.core.index.OIndexOneValue.get(OIndexOneValue.java:52)
	at com.orientechnologies.orient.core.index.OIndexOneValue.get(OIndexOneValue.java:39)
	at com.orientechnologies.orient.core.index.OIndexAbstractDelegate.get(OIndexAbstractDelegate.java:59)
	at com.orientechnologies.orient.core.index.OIndexTxAwareOneValue.get(OIndexTxAwareOneValue.java:243)
	at com.orientechnologies.orient.core.index.OIndexTxAwareOneValue.get(OIndexTxAwareOneValue.java:38)
	at com.orientechnologies.orient.core.sql.executor.FetchFromIndexStep.fetchNullKeys(FetchFromIndexStep.java:284)
	at com.orientechnologies.orient.core.sql.executor.FetchFromIndexStep.processFlatIteration(FetchFromIndexStep.java:277)
	at com.orientechnologies.orient.core.sql.executor.FetchFromIndexStep.init(FetchFromIndexStep.java:187)
	at com.orientechnologies.orient.core.sql.executor.FetchFromIndexStep.init(FetchFromIndexStep.java:174)
	at com.orientechnologies.orient.core.sql.executor.FetchFromIndexStep.syncPull(FetchFromIndexStep.java:57)
	at com.orientechnologies.orient.core.sql.executor.OSelectExecutionPlan.fetchNext(OSelectExecutionPlan.java:34)
	at com.orientechnologies.orient.core.sql.parser.OLocalResultSet.fetchNext(OLocalResultSet.java:27)
	at com.orientechnologies.orient.core.sql.parser.OLocalResultSet.<init>(OLocalResultSet.java:23)
	at com.orientechnologies.orient.core.sql.parser.OSelectStatement.execute(OSelectStatement.java:258)
	at com.orientechnologies.orient.core.command.OSqlScriptExecutor.execute(OSqlScriptExecutor.java:41)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.execute(ODatabaseDocumentEmbedded.java:452)
	at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeQuery(OConnectionBinaryExecutor.java:1151)
	at com.orientechnologies.orient.client.remote.message.OQueryRequest.execute(OQueryRequest.java:122)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:278)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:184)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)

**Comment by laa** [comment] 2017-08-07 20:14
@luigidellaquila what behavior should we get from index when it does not support null keys ? because if we do not get exception how we should be sure that index merely does not support such type of keys ?

**Comment by luigidellaquila** [comment] 2017-08-08 07:16
Hi @laa 

For simple queries, where the target is a class, there is no problem, as the SQL engine checks the index definition and avoids to use the index if it doesn't meet the requirements for the query execution.

For queries where the target is the index, IMHO we should just return the indexed values, not throw exceptions. I guess the problem is on the query executor, I'll check it.

About the index API, for me it's OK that it throws an exception if null values are not supported

Thanks

Luigi

**Comment by luigidellaquila** [comment] 2017-08-08 09:55
Hi @publicocean0 @laa 

I just pushed a fix on develop branch 

I'm closing this issue, please reopen if you see any related problems

Thanks

Luigi

**Closed by luigidellaquila** 2017-08-08 09:55 UTC
Labels: bug

**Comment by publicocean0** [comment] 2017-08-08 12:28
ok thanks
