### ISSUE TITLE
Unexpected result in the composite index with 3 keys

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#4001] opened 2015-04-22 19:55 UTC
```
index_1              | NOTUNIQUE  | mds           | f1       |          3 |
                                              |            |                       | f2        |            |
                                              |            |                       | f3       |            |


  select  from index:index_1  where  key = [#18:0]  
----+------+------------------------------------------------------------+-----
#   |@RID  |key                                                         |rid  
----+------+------------------------------------------------------------+-----
0   |#-1:-1|OCompositeKey{keys=[#18:0, #22:0, a]}                       |#46:2
1   |#-1:-1|OCompositeKey{keys=[#18:0, #22:0, b]}         |#46:0
2   |#-1:-1|OCompositeKey{keys=[#18:0, #22:0, c]}|#46:1
----+------+------------------------------------------------------------+-----

 select  from index:index_1  where  key = [#18:0,#22:0]     

----+------+------------------------------------------------------------+-----
#   |@RID  |key                                                         |rid  
----+------+------------------------------------------------------------+-----
0   |#-1:-1|OCompositeKey{keys=[#18:0, #22:0, a]}                       |#46:2
1   |#-1:-1|OCompositeKey{keys=[#18:0, #22:0, b]}         |#46:0
2   |#-1:-1|OCompositeKey{keys=[#18:0, #22:0, c]}|#46:1
----+------+------------------------------------------------------------+-----

 select  from index:index_1  where  key = [#18:0,#22:0, 'a' ] 


0 item(s) found. Query executed in 0.001 sec(s).
```

the last query might give a row

**Comment by luigidellaquila** [comment] 2016-05-23 15:48
Hi @publicocean0 

Is this issue still valid? Any clue on how to reproduce it? 

I ask because I was not able to reproduce it in current 2.2 GA

Thanks

Luigi

**Comment by lvca** [comment] 2016-08-27 19:15
Closing because no answer after months. In case please reopen/comment this.

**Closed by lvca** 2016-08-27 19:15 UTC
Labels: bug, waiting reply
