### ISSUE TITLE
Orient 3.0 - Issue in executing sql script on console (even from java shows similar behavior)

### ISSUE THREAD

**Issue by careerscale** [orientechnologies/orientdb#7458] opened 2017-05-29 20:11 UTC
## Expected behavior  
Should be able to execute the script with MATCH without any problem.

## Actual behavior  
Steps and error is given below

## Steps to reproduce  

I tried to run simple script but somehow it doesn't work. Not sure if this is with latest snapshots or something.

Here is the script.

```
script SQL
CREATE CLASS Person extends V;
CREATE VERTEX Person set name="Luca";
LET $a = (MATCH {class:Person, as:s} RETURN s);
select expand($a.s);
end
```
Here is the output, I don't understand why it should fail. other thing is that the error is thrice instead of once, so there is something missing here. I am using latest snapshots of orientdb 3.0

```
orientdb {db=demo}> script SQL
[Started multi-line command. Type just 'end' to finish and execute]

Error: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
CREATE CLASS Person extends V;

+----+------------+---------+
|#   |operation   |className|
+----+------------+---------+
|0   |create class|Person   |
+----+------------+---------+
Server side script executed in 0.070000 sec(s). Returned 1 recordsCREATE 
VERTEX Person set name="Luca";
LET $a = (MATCH {class:Person, as:s} RETURN s);
select expand($a.s);
end
Error: 
com.orientechnologies.orient.core.exception.OCommandExecutionException: Class Person already exists
    DB name="demo"
    DB name="demo"

 Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Class Person already exists
    DB name="demo"
    DB name="demo"

 Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Class Person already exists
    DB name="demo"
    DB name="demo"

  Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Class Person already exists
    DB name="demo"
    DB name="demo"

```

**Comment by careerscale** [comment] 2017-05-29 20:12
Also
I don't understand why this gets multiple vertices created with single create stmt, `script SQL CREATE VERTEX Person set name="Luca"; LET $a = (MATCH {class:Person, as:s} RETURN s); select expand($a.s); end`

**Comment by tglman** [comment] 2017-05-31 07:18
hi @careerscale,

Thank you for reporting this bug, the multiple logging is due to some retry we do client side, I'll try to reproduce it and i'll let you know.

Regards

**Comment by careerscale** [comment] 2017-05-31 11:53
@tglman 

thanks for looking into this

**Comment by careerscale** [comment] 2017-06-10 02:35
@tglman ,  is this something resolved already?  right now we are not blocked with this and can take its own time as needed. We went with alternate approach.
So we are good but if it can be fixed, that will be nice. Thank you

**Comment by tglman** [comment] 2017-06-12 09:09
hi @careerscale,

Is not yet solved, we already put in place some code that is needed to fix this, but is not yet fully done, it will be done for the final.

Regards

**Comment by careerscale** [comment] 2017-06-19 07:10
@tglman, thanks for the update. are we looking for M2? or RC1?

**Comment by careerscale** [comment] 2017-06-29 01:02
@luigidellaquila  @tglman  are we good with this ticket?

**Comment by tglman** [comment] 2017-06-29 15:07
hi @careerscale,

this ticket has two problem inside, one was related to the query with the match statements, and as far as I remember this was discussed in another issue and solved, the second problem was that the console does multiple retry, that in some cases should not be done, this is not yet solved, it will be probably done for the RC1.

Regards

**Comment by careerscale** [comment] 2017-07-03 12:42
@tglman thanks for the update.

**Comment by careerscale** [comment] 2017-08-02 10:05
@luigidellaquila , @tglman , is this something planned in the immediate future?

**Comment by luigidellaquila** [comment] 2017-08-02 12:21
Hi @careerscale 

About the MATCH, the problem is that you have to remove the round braces, eg.

```
LET $a = MATCH {class:Person, as:s} RETURN s;
```

instead of 

```
LET $a = (MATCH {class:Person, as:s} RETURN s);
```

About the retry, we still have to do some fixes, they will be in RC1

Thanks

Luigi

**Comment by tglman** [comment] 2017-08-18 09:14
hi @careerscale,

The retry for write operation as been fixed in develop.

Regards

**Comment by santo-it** [comment] 2017-08-21 12:10
Hi all,

If both issues described above have been fixed, can we now close this ticket - or is there anything else we can do to help?

Many thanks,

**Closed** 2017-10-04 01:24 UTC
Labels: bug, waiting reply
