### ISSUE TITLE
javascript scripts dont works in 3.0 version

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#7613] opened 2017-08-06 21:40 UTC
### Java Version: 8 

problem with old javascript scripts
var a=db.command( select from ...)
a is not more a array?

a.field('code') dotn works 

i tried many combinations and possibilities but no way for get a field

**Comment by luigidellaquila** [comment] 2017-08-07 09:14
Hi @publicocean0 

In v 3.0 we changed the APIs a bit, let me double-check it and I'll let you know

Thanks

Luigi

**Comment by luigidellaquila** [comment] 2017-08-07 10:31
I guess we are talking about JS functions. 

The result is an array, so you have to do `a[0].field('code')`.

Anyway, it's still using the old query engine, I think we should change it and use the new one, resulting in a complete change of API... Maybe we can consider leaving it as is and adding another method to invoke the new one. @tglman WDYT?

Thanks

Luigi

**Comment by publicocean0** [comment] 2017-08-07 11:24
in my software i have many scripts in javascripts.  i had complex queries to do from remote ... so i condensed many calls in one using javascript

**Comment by publicocean0** [comment] 2017-08-07 11:45
Anyway 
var a=db.command('select from I')
a[0]

dont show anything. 

instead 
var a=db.command('select from identity')
a

show many rows

**Comment by tglman** [comment] 2017-08-07 12:12
Hi All,

In 3.0 as result of query we have a OResultSet, that is an Iterator of OResult(https://github.com/orientechnologies/orientdb/blob/develop/core/src/main/java/com/orientechnologies/orient/core/sql/executor/OResultSet.java#L18) in 2.2.x we had a List<ODocument> as result of the query.

so the `a[0]` use to work because the result was a List with the current API you need instead `a.next()` that should work also with the old API.


Regards

**Comment by luigidellaquila** [comment] 2017-08-07 12:15
@tglman I think the JS database wrapper is still using the old API, I don't think it's returning an OResultSet...

**Comment by publicocean0** [comment] 2017-08-07 12:17
The iterator is a blessed change :) Very a good emprovement. 
Anyway
var a=db.command('select from identity')
a.next() 

dont works now

**Comment by publicocean0** [comment] 2017-08-07 12:22
It is a sizedIterator or default iterator? is possible the know the result set size?

**Comment by publicocean0** [comment] 2017-08-07 12:23
anyway a.next() works

**Comment by publicocean0** [comment] 2017-08-07 12:32
There also another change ....

a.next().field('code') dont works .... a.next() it seams returns just the rid

**Comment by luigidellaquila** [comment] 2017-08-07 12:33
Hi @publicocean0 

It's a normal iterator (not a sizedIterator) as the query could be very expensive and it cannot be calculated and kept in RAM in all cases.

I'm checking the issue, but I can't get how `a.next()` can work... it's supposed to still use the old API, that just returns a list... Let me do some deeper analysis, any additional info will be very appreciated

Thanks

Luigi

**Comment by luigidellaquila** [comment] 2017-08-07 12:46
Ok, I think we have to take a decision here.

The API is as follows:
```
db.command(String, params)
db.query(String, params)
```

but it still uses the old executor and the old underlying implementation, that is bad in terms of consistency with 3.0, but it helps in terms of backward compatibility.

The new database API in 3.0 is exactly the same, I cannot immagine a more natural method signature or variable naming, so I'd keep it as is and I'd bind it to the new executor. The problem is that this way I'll break backward compatibility for JS scripts. You will have to translate scripts as follows:

```
var a = db.query("select from v");
var name = a[0].field("name");
```

will become

```
var a = db.query("select from v");
var name = a.next().getProperty("name");
```

@tglman @lvca and all, WDYT? 

The change is trivial, it's just a matter of doing it or finding an alternative API

Thanks

Luigi

**Comment by publicocean0** [comment] 2017-08-07 12:51
a.next().getProperty('code') works :) in studio. 
I created orientdb release using 3.0m2 branch

**Comment by luigidellaquila** [comment] 2017-08-07 13:01
ok, trying to reproduce... which version did you download exactly?

Thanks

Luigi

**Comment by luigidellaquila** [comment] 2017-08-07 13:02
ah, ok, you created it from a maven build I guess

**Comment by publicocean0** [comment] 2017-08-07 13:04
yes exactly :)

**Comment by publicocean0** [comment] 2017-08-07 13:20
in a  old script i found also something like .....
 var a=new com.orientechnologies.orient.core.record.impl.ODocument()
a.field('a',3)

just for describing all the panorama for evaluation

**Comment by luigidellaquila** [comment] 2017-08-07 13:22
OK, I'm working to make it consistent, I'll provide APIs to cover all these cases.
I'll keep you updated

Thanks

Luigi

**Comment by luigidellaquila** [comment] 2017-08-07 15:46
Hi @publicocean0 

I pushed a fix on develop branch, now the API should be consistent with the ODatabase API. 

You have the following methods:

```
command(commandString, params) -> returns OResultSet
query(queryString, params) -> returns OResultSet
command(batchScriptString, params) -> returns OResultSet

newInstance(className) -> return OElement
newVertex(className) -> return OVertex
newEdge(fromVertex, toVertex, className) -> return OEdge
save(element)
```

For reference you can see:
http://orientdb.com/docs/3.0.x/java/Java-MultiModel-Data-API.html
http://orientdb.com/docs/3.0.x/java/Java-Query-API.html

I'll update the js docs in next hours
 
This should be enough for typical usage, but please let me know if you need anything more

Thanks

Luigi

**Comment by publicocean0** [comment] 2017-08-07 19:34
Thanks a lot :) I will start the migration of scripts now :)

**Comment by luigidellaquila** [comment] 2017-08-09 10:55
Hi @publicocean0 

Can I close this issue? Do you still need info on it?

Thanks

Luigi

**Comment by publicocean0** [comment] 2017-08-09 11:05
i think yes. It seams to work.

**Comment by luigidellaquila** [comment] 2017-08-09 11:07
Great, thank you, closing then.

Please reopen if you need further help

Thanks

Luigi

**Closed by luigidellaquila** 2017-08-09 11:07 UTC

**Comment by publicocean0** [comment] 2017-08-10 10:39
I checkoout branch develop .... but compiling i have a exception in 
Could not find artifact com.orientechnologies:orientdb-core:jar:tests:3.0.0-SNAPSHOT

**Comment by publicocean0** [comment] 2017-08-10 11:40
do you confirm in javascript i have to replace doc.identity in doc.getProperty('@rid') ?

**Comment by luigidellaquila** [comment] 2017-08-10 12:22
Hi @publicocean0 

You can use `doc.getIdentity()` for this

Thanks

Luigi
