### ISSUE TITLE
shutdown of 400GB dbase hangs

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#6762] opened 2016-09-30 12:19 UTC
## OrientDB Version, operating system, or hardware.
- v2.2.13-20161027.133116-9

## Operating System
- [x] Linux (Ubuntu 14.04LTS)
## Expected behavior and actual behavior

Bundled "shutdown.sh" script, with or without extra arguments, should gracefully shutdown the server, but it does not.
Follow-up of #6705 
## Steps to reproduce the problem

1) launched the "shutdown.sh" script without arguments:
`# bin/shutdown.sh`
pid file detected, killing process
waiting for OrientDB server to shutdown
(never completes)
2) launched the "shutdown.sh" script with the arguments mentioned in issue #6705 by robfrank (of course filled in the correct values for our case):
`# bin/shutdown.sh -h orient1.bc -P 2424-2430 -u root -p ROOT_PASSWORD`
Sending shutdown command to remote OrientDB Server instance...
Sep 30, 2016 2:11:41 PM com.orientechnologies.common.log.OLogManager log
SEVERE: Error on connecting to orient1.bc:2424
java.net.ConnectException: Connection refused
...
3) server process still not shutdown:
`# ps -aef|grep java
root     42254 42252 82 Sep29 ?        13:27:20 java -server -Xms1024m -Xmx16384m -Djna.nosys=true -XX:+HeapDumpOnOutOfMemoryError -XX:MaxDirectMemorySize=512g -Djava.awt.headless=true -Dfile.encoding=UTF8 -Drhino.opt.level=9 -Dstorage.diskCache.bufferSize=65536 -Djava.util.logging.config.file=/opt/orientdb/orientdb-community-2.2.10/config/orientdb-server-log.properties -Dorientdb.config.file=/opt/orientdb/orientdb-community-2.2.10/config/orientdb-server-config.xml -Dorientdb.www.path=/opt/orientdb/orientdb-community-2.2.10/www -Dorientdb.build.number=2.2.x@rc32d4ee06d4c38e27eb66931d027eb54854872ff; 2016-09-15 08:47:27+0000 -cp /opt/orientdb/orientdb-community-2.2.10/lib/orientdb-server-2.2.10.jar:/opt/orientdb/orientdb-community-2.2.10/lib/*:/opt/orientdb/orientdb-community-2.2.10/plugins/* -Ddistributed=true com.orientechnologies.orient.server.OServerMain`

4) logfile:
2016-09-30 13:52:27:477 WARNI Received signal: SIGTERM [OSignalHandler]

**Comment by laa** [comment] 2016-09-30 12:26
@rdelangh could you provide thread dump during shutdown when it is frozen ?

**Comment by rdelangh** [comment] 2016-09-30 13:19
/usr/lib/jvm/jdk1.8.0_92/bin/jstack 42254 > /tmp/odb-
[odb-42254-jstack.txt](https://github.com/orientechnologies/orientdb/files/503023/odb-42254-jstack.txt)
42254-jstack.txt

(file is attached)
[odb-42254-jstack.txt](https://github.com/orientechnologies/orientdb/files/503026/odb-42254-jstack.txt)

**Comment by rdelangh** [comment] 2016-09-30 13:21
sorry, precise command was with "-F" option, cos without that the process did not respond to "jstack"

/usr/lib/jvm/jdk1.8.0_92/bin/jstack -F 42254 > /tmp/odb-42254-jstack.txt

**Comment by laa** [comment] 2016-09-30 14:03
@rdelangh I again see that all threads are blocked. How did you execute shutdown? Did you try to send kill signal first and when it was unsuccessful you tried to execute shutdown with a password, is it correct?

**Comment by rdelangh** [comment] 2016-09-30 14:05
@laa 
yes indeed, pls see my initial post

**Comment by laa** [comment] 2016-09-30 14:09
@rdelangh did you call freeze or backup calls before shutdown ?

**Comment by rdelangh** [comment] 2016-09-30 14:09
@laa 
no

**Comment by laa** [comment] 2016-09-30 14:14
@rdelangh could you send me also memory dump ?

**Comment by laa** [comment] 2016-09-30 14:42
@rdelangh could you check whether in server root or bin directory there is .hprof file ?

**Comment by rdelangh** [comment] 2016-09-30 14:43
@laa 
the compressed filesize is huge (already nearly 25MB and still growing), as generated by

$ /usr/lib/jvm/jdk1.8.0_92/bin/jmap -F -J-d64 -dump:format=b,file=/tmp/odb-42254-jmap-dump 42254
Attaching to process ID 42254, please wait...
Debugger attached successfully.
Server compiler detected.
JVM version is 25.92-b14
Dumping heap to /tmp/odb-42254-jmap-dump ...
(this is still not completed after 30mins, resulting uncompressed file is already >100MB size)

$ ls -l /tmp/odb-42254-jmap-dump
-rw-r--r-- 1 root     root     126763983 Sep 30 16:43 odb-42254-jmap-dump

$ gzip < /tmp/odb-42254-jmap-dump > /tmp/odb-42254-jmap-dump.zip
$ ls -l /tmp/odb-42254-jmap-dump.zip
-rw-r--r-- 1 root     root      24772771 Sep 30 16:42 odb-42254-jmap-dump.zip

-> are these the options you want for the heap dump, or is anything more compact sufficient?
-> if this dump is what you need, how do you want me to transfer this file to you, given its size?

**Comment by rdelangh** [comment] 2016-09-30 14:45
@laa 
no ".hprof" file in server root or bin dir ; see previous comment about how I am collecting the heap dump (still ongoing)

**Comment by laa** [comment] 2016-09-30 14:47
@rdelangh I have a suspicion that during shutdown OOM happens and because of that dump is started to be created all is frozen and threads are stuck and blocked.

**Comment by laa** [comment] 2016-09-30 14:47
@rdelangh also that is a reason why you can not connect to process to make stack trace without force option.

**Comment by rdelangh** [comment] 2016-09-30 14:49
@laa 
I searched entire machine for any file "*.hprof", but none exists.

**Comment by laa** [comment] 2016-09-30 14:52
@rdelangh the only explanation why all threads are blocked at thread dump is that they are in safe point. But let's look at heap dump. Is this shutdown freeze reproducible ?

**Comment by rdelangh** [comment] 2016-09-30 14:56
@laa I did several shutdowns last days that did not hang, always with "shutdown.sh", but this is only one that hangs since previous case #6705 
So likely it's hard to reproduce.
I am attempting (#6666) to add a 2nd node to this one for distributed setup, and did a shutdown of that 2nd node (shutdown not hanging) only some 10s of secs before shutting down this 1st node (shutdown hanging). Maybe related?

**Comment by rdelangh** [comment] 2016-09-30 15:03
@laa 
How shall I transfer this massive heap dump to you ? GZIPd file is now already 75MB and still not completed...

**Comment by laa** [comment] 2016-09-30 15:04
@rdelangh could you open ssh connection to server with user. I will get it then.

**Comment by rdelangh** [comment] 2016-09-30 15:06
no sorry, is all (as should be in modern environments ;-) ) behind strict firewall.

**Comment by laa** [comment] 2016-09-30 15:09
@rdelangh you may use Google Drive or any other file sharing providers if you wish.

**Comment by laa** [comment] 2016-09-30 15:10
@rdelangh also I ask you do not kill a process and wait several hours may be it will be finished. Then we will know for sure that JVM was in safe point.

**Comment by rdelangh** [comment] 2016-09-30 15:13
- ok, will leave the process as is
- the data is a bit confidential, so not a good idea to share that heap dump on a publicly accessible medium, no? Is it realistic to issue some heap analysis myself, guided by you ?

**Comment by rdelangh** [comment] 2016-09-30 15:30
@laa 
The heap summary output was this:
$ /usr/lib/jvm/jdk1.8.0_92/bin/jmap -J-d64 -heap 42254
Attaching to process ID 42254, please wait...
Debugger attached successfully.
Server compiler detected.
JVM version is 25.92-b14

using thread-local object allocation.
Parallel GC with 33 thread(s)

Heap Configuration:
   MinHeapFreeRatio         = 0
   MaxHeapFreeRatio         = 100
   MaxHeapSize              = 17179869184 (16384.0MB)
   NewSize                  = 357564416 (341.0MB)
   MaxNewSize               = 5726273536 (5461.0MB)
   OldSize                  = 716177408 (683.0MB)
   NewRatio                 = 2
   SurvivorRatio            = 8
   MetaspaceSize            = 21807104 (20.796875MB)
   CompressedClassSpaceSize = 1073741824 (1024.0MB)
   MaxMetaspaceSize         = 17592186044415 MB
   G1HeapRegionSize         = 0 (0.0MB)

Heap Usage:
PS Young Generation
Eden Space:
   capacity = 881328128 (840.5MB)
   used     = 881328120 (840.4999923706055MB)
   free     = 8 (7.62939453125E-6MB)
   99.99999909227905% used
From Space:
   capacity = 1304428544 (1244.0MB)
   used     = 0 (0.0MB)
   free     = 1304428544 (1244.0MB)
   0.0% used
To Space:
   capacity = 1317535744 (1256.5MB)
   used     = 0 (0.0MB)
   free     = 1317535744 (1256.5MB)
   0.0% used
PS Old Generation
   capacity = 11453595648 (10923.0MB)
   used     = 11453208768 (10922.631042480469MB)
   free     = 386880 (0.36895751953125MB)
   99.99662219610427% used

16296 interned Strings occupying 1570024 bytes.

-> does this look like an OOM situation?

**Comment by laa** [comment] 2016-09-30 15:49
@rdelangh 
Young gen: 99.99999909227905% used
Old gen: 99.99662219610427% used

So it defenetilly looks like very close to OOM.

**Comment by laa** [comment] 2016-09-30 15:55
@rdelangh the purpose of a heap dump to be sure whether we got deadlock or not. What if I share Google Drive with you? Even if it was OOM heap dump will be useful for analysis of the reason of heap dump.

**Comment by rdelangh** [comment] 2016-09-30 16:02
@laa 
ok then, OOM situation.
I assume this should not happen, right?
Is it preliminary that you get this heap dump, for any further analysis? I won't be allowed to transmit this dump outside the company because of the fairly sensitive data it will contain.

**Comment by laa** [comment] 2016-09-30 16:08
@rdelangh we need to know what caused OOM or deadlock. Without heap dump, it is hard to do.  Could you make heap dump analysis and send me top 10-15 objects consuming memory ?

**Comment by rdelangh** [comment] 2016-09-30 20:08
When I start the server, I redirect its STDOUT and STDERR to a separate logfile ; the messages here differ slightly from what's found in the "orient-server.log.*" files, for example:
...
2016-09-30 13:49:48:747 INFO  [orient1]<-[orient2] Received new status orient2.cdrarch=SYNCHRONIZING [OHazelcastPlugin]
2016-09-30 13:49:48:770 INFO  [orient1]->[orient2] Deploying database cdrarch... [OSyncDatabaseTask]
2016-09-30 13:49:48:773 INFO  [orient1]->[orient2] Creating backup of database 'cdrarch' (compressionRate=7) in directory: /tmp/orientdb/backup_cdrarch.zip. L
SN=OLogSequenceNumber{segment=20518, position=122331103}... [OSyncDatabaseTask]
2016-09-30 13:49:48:774 INFO  [orient1] Received updated status orient1.cdrarch=BACKUP [OHazelcastPlugin]
2016-09-30 13:49:48:776 INFO  [orient1] Received updated status orient1.cdrarch=ONLINE [OHazelcastPlugin]
2016-09-30 13:49:48:777 INFO  [orient1] Distributed servers status:

+--------+--------+------------------------------------+-----+-----------------------+-----------------+-----------------+------------------------+
|Name    |Status  |Databases                           |Conns|StartedOn              |Binary           |HTTP             |UsedMemory              |
+--------+--------+------------------------------------+-----+-----------------------+-----------------+-----------------+------------------------+
|orient2 |STARTING|                                    |0    |13:49:39               |10.49.69.189:2424|10.49.69.189:2480|105.70MB/14.22GB (0.73%)|
|orient1*|ONLINE  |GratefulDeadConcerts=ONLINE (MASTER)|39   |2016-09-29 22:02:33.862|10.49.69.190:2424|10.49.69.190:2480|1.50GB/14.22GB (10.55%) |
|        |        |cdrarch=BACKUP (MASTER)             |     |                       |                 |                 |                        |
|        |        |bvdd-test=ONLINE (MASTER)           |     |                       |                 |                 |                        |
+--------+--------+------------------------------------+-----+-----------------------+-----------------+-----------------+------------------------+
 [OHazelcastPlugin]Exception in thread "OrientDB SyncDatabase node=orient1 db=cdrarch" com.orientechnologies.orient.core.exception.OStorageException: Error on
 freeze of storage 'cdrarch'
        DB name="cdrarch"
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.freeze(OAbstractPaginatedStorage.java:2608)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.backup(OLocalPaginatedStorage.java:173)
        at com.orientechnologies.orient.server.distributed.impl.ODistributedStorage.backup(ODistributedStorage.java:1585)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.backup(ODatabaseDocumentTx.java:2913)
        at com.orientechnologies.orient.server.distributed.impl.task.OSyncDatabaseTask$1.run(OSyncDatabaseTask.java:124)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
        at com.orientechnologies.lucene.engine.OLuceneIndexEngineDelegate.freeze(OLuceneIndexEngineDelegate.java:273)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.freeze(OAbstractPaginatedStorage.java:2600)
        ... 5 more

What I notice here, is that Java error message:
 [OHazelcastPlugin]Exception in thread "OrientDB SyncDatabase node=orient1 db=cdrarch" com.orientechnologies.orient.core.exception.OStorageException: Error on
 freeze of storage 'cdrarch'

Maybe not relevant, but just wanted to pass the message.

Busy now getting the analysis of the huge heap dump (1.9 GB)...

**Comment by lvca** [comment] 2016-09-30 21:00
This is a bug in the lucene module. @maggiolo00 did you already fix this?

**Comment by maggiolo00** [comment] 2016-09-30 22:17
@lvca 
i think not. Seems another kind of issue and more related to this
https://github.com/orientechnologies/orientdb/issues/6703
I will check it

**Comment by rdelangh** [comment] 2016-10-02 10:02
Taking the heap dump took about 2.5 days, the file is about 22GB size. I tried different programs to read this file, but none works. Last one I tried is Memory Analyzer from Eclipse, but this fails with 

!SESSION 2016-10-02 11:32:06.096 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_92
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -application org.eclipse.mat.api.parse -DhprofStrictnessWarning=true /tmp/odb-42254-jmap-dump
Command-line arguments:  -os linux -ws gtk -arch x86_64 -consolelog -application org.eclipse.mat.api.parse -DhprofStri
ctnessWarning=true /tmp/odb-42254-jmap-dump

!ENTRY org.eclipse.osgi 4 0 2016-10-02 11:36:50.205
!MESSAGE Application error
!STACK 1
java.lang.NullPointerException
        at org.eclipse.mat.hprof.HprofParserHandlerImpl.resolveClassHierarchy(HprofParserHandlerImpl.java:587)
        at org.eclipse.mat.hprof.Pass2Parser.readInstanceDump(Pass2Parser.java:205)
        at org.eclipse.mat.hprof.Pass2Parser.readDumpSegments(Pass2Parser.java:159)
        at org.eclipse.mat.hprof.Pass2Parser.read(Pass2Parser.java:89)
        at org.eclipse.mat.hprof.HprofIndexBuilder.fill(HprofIndexBuilder.java:94)
        at org.eclipse.mat.parser.internal.SnapshotFactoryImpl.parse(SnapshotFactoryImpl.java:222)
        at org.eclipse.mat.parser.internal.SnapshotFactoryImpl.openSnapshot(SnapshotFactoryImpl.java:126)
        at org.eclipse.mat.snapshot.SnapshotFactory.openSnapshot(SnapshotFactory.java:145)
        at org.eclipse.mat.internal.apps.ParseSnapshotApp.parse(ParseSnapshotApp.java:134)
        at org.eclipse.mat.internal.apps.ParseSnapshotApp.start(ParseSnapshotApp.java:106)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1488)

-> what tool should I use ?
I need to get the engine operational again, so I can't wait anymore and hence will kill the process, then restart it.

**Comment by rdelangh** [comment] 2016-10-03 11:36
@robfrank , @laa 
I launched the engine yesterday evening, had some 10,000's of records loaded yesterday and this morning ; now I want to stop the engine to restart it in non-distributed mode : 

I tried the method suggested by 'robfrank' in #6705 , i.e.

./shutdown.sh -h orient1.bc -P 2424-2430 -u root -p $ourRootPwd

(in which I have 100% sure triple-checked the value of $ourRootPwd, mind you)

but this command failed : 
- output printed

pid file not present or params detected
allowed parameters
-h | --host hostname : name or ip of the host where OrientDB is running. Deafult to localhost
-P | --ports  ports : ports in the form of single value or range. Default to 2424-2430
-p | --password password : the super user password
-u | --user username: the super user name. Default to root
example: shutdown.sh -h orientserver.mydomain -P 2424-2430 -u root -p securePassword
Sending shutdown command to remote OrientDB Server instance...
Error: null

- logfile got

2016-10-03 13:29:57:590 INFO  Received shutdown command from the remote client /10.49.69.190:59118 [ONetworkProtocolBinary]
2016-10-03 13:29:57:591 SEVER Authentication error of remote client /10.49.69.190:59118: shutdown is aborted. [ONetworkProtocolBinary]

The Java process is still running, obviously.

**Comment by rdelangh** [comment] 2016-10-03 11:52
The 'normal' shutdown command, which sends a TERM signal to the engine's process, did work fine this time:

$ ./shutdown.sh
pid file detected, killing process
waiting for OrientDB server to shutdown
$ ps -aef | grep java
$

In the logs:

2016-10-03 13:47:40:957 WARNI Received signal: SIGTERM [OSignalHandler]
2016-10-03 13:47:40:959 INFO  [10.49.69.190]:2434 [cdrcontrols] [3.6.5] Running shutdown hook... Current state: ACTIVE [Node]
2016-10-03 13:47:40:959 INFO  OrientDB Server is shutting down... [OServer]

Started it up again in non-distributed more:

$ ./bin/server.sh
$ 

In the logs:

2016-10-03 13:50:36:817 INFO  Loading configuration from: /opt/orientdb/orientdb-community-2.2.10/config/orientdb-server-config.xml... [OServerC                         onfigurationLoaderXml]
2016-10-03 13:50:37:112 INFO  OrientDB Server v2.2.10 (build 2.2.x@rc32d4ee06d4c38e27eb66931d027eb54854872ff; 2016-09-15 08:47:27+0000) is start                         ing up... [OServer]
2016-10-03 13:50:37:122 INFO  Databases directory: /opt/orientdb/databases [OServer]
2016-10-03 13:50:37:509 INFO  Listening binary connections on 0.0.0.0:2424 (protocol v.36, socket=default) [OServerNetworkListener]
2016-10-03 13:50:37:513 INFO  Listening http connections on 0.0.0.0:2480 (protocol v.10, socket=default) [OServerNetworkListener]
2016-10-03 13:50:37:524 INFO  Installing dynamic plugin 'studio-2.2.zip'... [OServerPluginManager]
2016-10-03 13:50:37:532 INFO  ODefaultPasswordAuthenticator is active [ODefaultPasswordAuthenticator]
2016-10-03 13:50:37:533 INFO  OServerConfigAuthenticator is active [OServerConfigAuthenticator]
2016-10-03 13:50:37:535 INFO  OSystemUserAuthenticator is active [OSystemUserAuthenticator]
2016-10-03 13:50:37:556 INFO  Installed GREMLIN language v.2.6.0 - graph.pool.max=50 [OGraphServerHandler]
2016-10-03 13:50:37:557 INFO  [OVariableParser.resolveVariables] Error on resolving property: distributed [orientechnologies]
2016-10-03 13:50:37:561 WARNI Authenticated clients can execute any kind of code into the server by using the following allowed languages: [sql]                          [OServerSideScriptInterpreter]
2016-10-03 13:50:37:563 INFO  OrientDB Studio available at http://10.49.69.190:2480/studio/index.html [OServer]
2016-10-03 13:50:37:563 INFO  OrientDB Server is active v2.2.10 (build 2.2.x@rc32d4ee06d4c38e27eb66931d027eb54854872ff; 2016-09-15 08:47:27+0000  

Nothing to worry about the message

2016-10-03 13:50:37:557 INFO  [OVariableParser.resolveVariables] Error on resolving property: distributed [orientechnologies]

?

**Comment by laa** [comment] 2016-10-03 11:54
The start is OK but shutdown is strange @robfrank any comments on the shutdown output ?

**Comment by rdelangh** [comment] 2016-10-06 13:47
@maggiolo00  did you already find anything about that issue about the Lucene index not being 'closed' correctly during a clean shutdown command?
I did this 'clean' shutdown command again, and got following in the output messages:

$ bin/shutdown.sh -h orient1.bc -P 2424-2430 -u root -p $ourPwd
pid file not present or params detected
allowed parameters
-h | --host hostname : name or ip of the host where OrientDB is running. Deafult to localhost
-P | --ports  ports : ports in the form of single value or range. Default to 2424-2430
-p | --password password : the super user password
-u | --user username: the super user name. Default to root
example: shutdown.sh -h orientserver.mydomain -P 2424-2430 -u root -p securePassword
Sending shutdown command to remote OrientDB Server instance...
Shutdown executed correctly

and the logs: 
...

2016-10-06 15:42:57:796 INFO  Received shutdown command from the remote client /10.49.69.190:59129 [ONetworkProtocolBinary]
2016-10-06 15:42:57:810 INFO  Remote client /10.49.69.190:59129 authenticated. Starting shutdown of server... [ONetworkProt
2016-10-06 15:42:57:812 INFO  OrientDB Server is shutting down... [OServer]
...

2016-10-06 15:42:57:815 INFO  Orient Engine is shutting down... [Orient]
2016-10-06 15:42:57:816 INFO  - shutdown storage: OSystem... [Orient]
2016-10-06 15:42:58:105 INFO  - shutdown storage: navi... [Orient]
2016-10-06 15:42:58:667 INFO  - shutdown storage: cdrarch... [Orient]-- error on shutdown storage
java.lang.NullPointerException
        at com.orientechnologies.lucene.engine.OLuceneIndexEngineDelegate.close(OLuceneIndexEngineDelegate.java:117)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doClose(OAbstractPaginatedStorage
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.close(OAbstractPaginatedStorage.j
        at com.orientechnologies.orient.core.storage.OStorageAbstract.shutdown(OStorageAbstract.java:224)
...
Error on closing Lucene index
...

**Comment by maggiolo00** [comment] 2016-10-06 13:50
@rdelangh 

i 'm trying to reproduce it. Is this happening always for you?

**Comment by rdelangh** [comment] 2016-10-06 14:15
@maggiolo00 I (luckily) don't have to stop the engine multiple times a day... And the logs get poluted so much with stuff during operational course that I cannot get back the logs from previous shutdown. But since I end up each time with a long startup timeframe (30-40 mins through which I see him reading all datafiles), I suspect the server is doing kind of a consistency check on the databases, because it did not shutdown cleanly.
So yes, I suspect this particular thingie with the Lucene index file happens each time.

**Comment by rdelangh** [comment] 2016-10-06 14:53
@maggiolo00 Just did a shutdown again, got the same error about the Lucene index file:

...
2016-10-06 16:47:43:430 INFO  Orient Engine is shutting down... [Orient]
2016-10-06 16:47:43:432 INFO  - shutdown storage: OSystem... [Orient]
2016-10-06 16:47:43:771 INFO  - shutdown storage: navi... [Orient]
2016-10-06 16:47:44:246 INFO  - shutdown storage: GratefulDeadConcerts... [Orient]
2016-10-06 16:47:44:471 INFO  - shutdown storage: cdrarch... [Orient]-- error on shutdown storage
java.lang.NullPointerException
        at com.orientechnologies.lucene.engine.OLuceneIndexEngineDelegate.close(OLuceneIndexEngineDelegate.java:117)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doClose(OAbstractPaginatedStorage.java:3595)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.close(OAbstractPaginatedStorage.java:545)
        at com.orientechnologies.orient.core.storage.OStorageAbstract.shutdown(OStorageAbstract.java:224)
        at com.orientechnologies.orient.core.Orient.shutdownAllStorages(Orient.java:390)
        at com.orientechnologies.orient.core.Orient.access$500(Orient.java:56)
        at com.orientechnologies.orient.core.Orient$OShutdownEnginesHandler.shutdown(Orient.java:910)
        at com.orientechnologies.orient.core.Orient.shutdown(Orient.java:331)
        at com.orientechnologies.orient.server.OServer.shutdown(OServer.java:493)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary$3.run(ONetworkProtocolBinary.java:2191)
Error on closing Lucene index

But startup did not take the usual 45mins or so, this time! Started in about 30 secs.

**Comment by rdelangh** [comment] 2016-11-02 13:01
@maggiolo00 
Any update on this issue please ?
I run version 2.2.13-20161027.133116-9 now, but still get the messages in the logs.

**Comment by maggiolo00** [comment] 2016-11-02 13:16
@rdelangh 

can you post the messages in the logs with this version?

**Comment by maggiolo00** [comment] 2016-11-02 13:18
@rdelangh 

i've pushed a fix on 28th of October, so i guess my fix is not in your snapshot version.

Can you try with the last snapshot here ?

https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-community/2.2.13-SNAPSHOT/

**Comment by rdelangh** [comment] 2016-11-02 13:31
@maggiolo00 
ok, installing that version, will be running in a few minutes; will post you if there is any changed behaviour regarding the Lucene index files.

**Comment by maggiolo00** [comment] 2016-11-02 13:44
@rdelangh 
thanks

**Comment by rdelangh** [comment] 2016-11-02 13:46
@maggiolo00 , @lvca 

Problem with latest 2.2.13 snapshot release :
0) stopped previous version with the command
```
bin/shutdown.sh -h orient1.bc -P 2424-2430 -u root -p Yitacen3 ;tail -f log/orient-server.log.0
pid file not present or params detected
allowed parameters
-h | --host hostname : name or ip of the host where OrientDB is running. Deafult to localhost
-P | --ports  ports : ports in the form of single value or range. Default to 2424-2430
-p | --password password : the super user password
-u | --user username: the super user name. Default to root
example: shutdown.sh -h orientserver.mydomain -P 2424-2430 -u root -p securePassword
Sending shutdown command to remote OrientDB Server instance...
Shutdown executed correctly

2016-11-02 14:33:59:294 INFO  - ONetworkProtocolBinary /0.0.0.0:2424: [OServer]
2016-11-02 14:33:59:296 INFO  - ONetworkProtocolHttpDb /0.0.0.0:2480: [OServer]
2016-11-02 14:33:59:296 INFO  Shutting down protocols [OServer]
2016-11-02 14:33:59:300 INFO  Shutting down plugins: [OServerPluginManager]
2016-11-02 14:33:59:301 INFO  - studio [OServerPluginManager]
2016-11-02 14:33:59:301 INFO  - script-interpreter [OServerPluginManager]
2016-11-02 14:33:59:301 INFO  - graph [OServerPluginManager]
2016-11-02 14:33:59:301 INFO  Shutting down databases: [OServer]
2016-11-02 14:33:59:302 INFO  Orient Engine is shutting down... [Orient]
2016-11-02 14:33:59:317 INFO  - shutdown storage: OSystem... [Orient]
2016-11-02 14:33:59:518 INFO  - shutdown storage: navi... [Orient]
2016-11-02 14:33:59:816 INFO  - shutdown storage: cdrarch... [Orient]
2016-11-02 14:34:03:375 INFO  OrientDB Engine shutdown complete [Orient]
2016-11-02 14:34:03:375 INFO  OrientDB Server shutdown complete
```
1) Just started version 2.2.13-20161101.003253-11
2) started console.sh and tried to connect to our dbase "cdrarch":
```
orientdb> use remote:localhost/cdrarch admin $ourpwd
Connecting to database [remote:localhost/cdrarch] with user 'admin'...
Error: com.orientechnologies.orient.core.exception.OStorageException: Can not close file with id 0 because it is still in use
        DB name="cdrarch"
        DB name="cdrarch"
```
nothing appears in the logs of the server
3) connecting to another dbase works fine:
```
orientdb> use remote:localhost/navi admin $ourpwd
Disconnecting from the database [null]...OK
Connecting to database [remote:localhost/navi] with user 'admin'...OK
```
4) trying again to dbase "cdrarch" fails the same way:
```
orientdb {db=navi}> use remote:localhost/cdrarch admin $ourpwd
Disconnecting from the database [navi]...OK
Connecting to database [remote:localhost/cdrarch] with user 'admin'...
Error: com.orientechnologies.orient.core.exception.OStorageException: Can not close file with id 0 because it is still in use
        DB name="cdrarch"
        DB name="cdrarch"
```
Now the server logs receive this message:
```
2016-11-02 14:41:12:839 WARNI {db=cdrarch} Database is open by another process [OPaginatedStorageDirtyFlag]
2016-11-02 14:41:12:897 WARNI {db=cdrarch} MBean with name com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations:id=1078974813,name="cdrarch",type=OAtomicOperationsMangerMXBean has already registered. Probably your system was not shutdown correctly or you have several running applications which use OrientDB engine inside [OAtomicOperationsManager]
```

**Comment by rdelangh** [comment] 2016-11-02 13:50
If I stop version 2.2.13-20161101.003253-11 again, and startup the previously happily running version 2.2.13-20161027.133116-9, then it gives the same error during attempt to connect to our dbase "cdrarch" from a console session:
```
orientdb> use remote:localhost/cdrarch admin $ourpwd
Connecting to database [remote:localhost/cdrarch] with user 'admin'...
Error: com.orientechnologies.orient.core.exception.OStorageException: Can not close file with id 0 because it is still in use
        DB name="cdrarch"
        DB name="cdrarch"
```

--> ??

**Comment by maggiolo00** [comment] 2016-11-02 14:24
@rdelangh 

check if you have multiple OrientDB running.

**Comment by rdelangh** [comment] 2016-11-02 14:25
@maggiolo00 
duh ;-) Of course I checked this out already. Only a single one running at any time.

**Comment by maggiolo00** [comment] 2016-11-02 14:27
@laa 

do you have any idea about this last exception?

**Comment by rdelangh** [comment] 2016-11-02 16:02
@maggiolo00 , @laa 
Using "lsof $filename", I checked if any file in my database directory would still be open by some process after the OrientDB server process is stopped. None of the files is.

**Comment by laa** [comment] 2016-11-03 11:02
Hi, about last one. We reproduced that issue on develop branch , we will work on that soon.

**Comment by rdelangh** [comment] 2016-11-04 09:58
@laa, @maggiolo00 
hi gentlemen, is there any update on this issue ? We can not start our database engine anymore, it is still down... :-(

**Comment by laa** [comment] 2016-11-04 10:33
@rdelangh there are several problems described in one issue, what is  your current problem ? You can not open the database, do not you ?

**Comment by rdelangh** [comment] 2016-11-04 13:10
@laa yes indeed, the database can not be opened anymore.

**Comment by laa** [comment] 2016-11-04 13:40
@rdelangh what exception do you have or may be database is frozen in the middle of open ?

**Comment by rdelangh** [comment] 2016-11-04 16:14
@laa the messages from client ("console.sh") and from server are in the previous comments above

**Comment by rdelangh** [comment] 2016-11-07 08:50
@laa, @maggiolo00 , @lvca 
Gentlemen, can someone please urgently investigate the reasons why the database cannot be opened anymore because it thinks there is still something 'open' ?
```
orientdb> use remote:localhost/cdrarch admin $ourpwd
Connecting to database [remote:localhost/cdrarch] with user 'admin'...
Error: com.orientechnologies.orient.core.exception.OStorageException: Can not close file with id 0 because it is still in use
        DB name="cdrarch"
        DB name="cdrarch"
```

**Comment by laa** [comment] 2016-11-07 09:02
@rdelangh it is not clear for me. You open database and it can not be opened because on open you see message "Can not close file with id 0 because it is still in use     DB name="cdrarch"" Is it  correct ?

**Comment by rdelangh** [comment] 2016-11-07 09:34
@laa opened new issue #6884 for this specific failure to open the dbase

**Comment by rdelangh** [comment] 2016-11-15 10:10
@laa 
1) the database is enabled again (issue #6884 is resolved)
2) meanwhile, using the recent 2.2.13 snapshots, I had no more problems closing the databases; so I hope that this particular issue has been resolved

-> can be closed, will re-open if it would occur again

**Comment by maggiolo00** [comment] 2016-11-18 11:23
Thanks

@rdelangh

**Closed by maggiolo00** 2016-11-18 11:23 UTC
Labels: bug
