### ISSUE TITLE
Binary mode and console mode, "*, @version" and "@version, *" gets different results

### ISSUE THREAD

**Issue by shekhei** [orientechnologies/orientdb#4217] opened 2015-05-25 10:00 UTC
Basically one gets version in response, the other doesnt
"*, @version", gets version in response
"@version, *" doesnt get version in response

Using orientdb 2.0.8

**Comment by luigidellaquila** [comment] 2015-09-22 09:12
Hi @shekhei 

it should be already fixed in 2.1, could you please confirm?

**Comment by prjhub** [comment] 2015-10-07 11:43
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.

**Closed by prjhub** 2015-10-07 11:43 UTC
Labels: bug, waiting reply
