### ISSUE TITLE
2.1-rc4 memory leaking with edges iteration. 

### ISSUE THREAD

**Issue by valenpo** [orientechnologies/orientdb#4384] opened 2015-06-18 08:07 UTC
We found on our database memory leaking with iteration of vertex edges. 

```
graph.getEdges()
``` 
give us about 1 200 000 total edges. 

but 
```
for (Edge edge : graph.getVertex("#12:287").getEdges(Direction.BOTH)) {
				total++;
				if (total % treshold == 0) {
					System.out.println(total);
				}
			}
```

I stopped iteration near 80 000 000 edges ... 

And my conclusion, something definitely wrong with database. 

We have a database to reproduce such error, but can not provide it here. 

@laa already has a link to that database.

Regards,
Valentin

**Comment by lvca** [comment] 2015-06-18 15:05
Do you have regular or lightweight edges?

**Comment by valenpo** [comment] 2015-06-18 15:07
Regular edges. 

> On 18 июня 2015 г., at 18:05, Luca Garulli <notifications@github.com> wrote:
> 
> Do you have regular or lightweight edges?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/orientechnologies/orientdb/issues/4384#issuecomment-113186533>.
> 

Regards,
Valentin Popov

**Comment by lvca** [comment] 2015-06-18 15:13
Please could you write the output of this query?

```sql
select @this.toJSON() from #12:287
```

**Comment by valenpo** [comment] 2015-06-18 15:18
This is with 2GB of HEAP
But as I know, Andrey already working on it. 

июн 18, 2015 7:16:27 PM com.orientechnologies.common.log.OLogManager log
INFO: OrientDB auto-config DISKCACHE=4 323MB (heap=1 820MB os=8 192MB disk=236 268MB)
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:2367)
	at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:130)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:114)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:415)
	at java.lang.StringBuffer.append(StringBuffer.java:237)
	at java.io.StringWriter.write(StringWriter.java:101)
	at java.io.StringWriter.append(StringWriter.java:143)
	at java.io.StringWriter.append(StringWriter.java:41)
	at com.orientechnologies.orient.core.serialization.serializer.OJSONWriter.writeValue(OJSONWriter.java:422)
	at com.orientechnologies.orient.core.fetch.json.OJSONFetchContext.writeLinkedValue(OJSONFetchContext.java:158)
	at com.orientechnologies.orient.core.fetch.json.OJSONFetchListener.parseLinkedCollectionValue(OJSONFetchListener.java:78)
	at com.orientechnologies.orient.core.fetch.OFetchHelper.fetchCollection(OFetchHelper.java:505)
	at com.orientechnologies.orient.core.fetch.OFetchHelper.fetch(OFetchHelper.java:371)
	at com.orientechnologies.orient.core.fetch.OFetchHelper.processRecord(OFetchHelper.java:310)
	at com.orientechnologies.orient.core.fetch.OFetchHelper.fetch(OFetchHelper.java:72)
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerJSON.toString(ORecordSerializerJSON.java:338)
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerStringAbstract.toString(ORecordSerializerStringAbstract.java:668)
	at com.orientechnologies.orient.core.record.ORecordAbstract.toJSON(ORecordAbstract.java:192)
	at com.orientechnologies.orient.core.record.ORecordAbstract.toJSON(ORecordAbstract.java:188)
	at com.stimulus.archiva.database.DBT.main(DBT.java:26)

> On 18 июня 2015 г., at 18:13, Luca Garulli <notifications@github.com> wrote:
> 
> Please could you write the output of this query?
> 
> select @this.toJSON() from #12:287
> —
> Reply to this email directly or view it on GitHub <https://github.com/orientechnologies/orientdb/issues/4384#issuecomment-113188663>.
> 
Thank you! 

Regards
Valentin

**Comment by laa** [comment] 2015-06-18 16:01
Luca,
That is bug caused by MT issue with ribag, I am on it right now. I am
restoring database and will send fixed db to the Valentin.

**Comment by laa** [comment] 2015-06-23 10:54
Fixed in latest distribution.

**Closed by laa** 2015-06-23 10:54 UTC
Labels: bug
