### ISSUE TITLE
java.io.IOException during OrientDB restart

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#7186] opened 2017-02-21 19:51 UTC
### OS: Ubuntu 16.04 

Case: we are using embedded version of OrientDB. Our application has ability for dynamic modules loading. To support this lifecycle full internal restart of app is needed. So we need to be able to stop OrientDB and then start it again. With 2.1.19 it was working perfectly. But during updating of OrientDB version to 2.2.16 we found that this functionality starts to fail with the following Exception in OrientDB core:

```java
2017-02-21 21:05:31:139 INFO  OrientDB Server is active v2.2.16. [OServer]$ANSI{green {db=OrienteerFuture}} Error during data read for file 'internal.pcl' 1-th attempt
java.io.IOException: Bad address
	at sun.nio.ch.FileDispatcherImpl.pread0(Native Method)
	at sun.nio.ch.FileDispatcherImpl.pread(FileDispatcherImpl.java:52)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:220)
	at sun.nio.ch.IOUtil.read(IOUtil.java:192)
	at sun.nio.ch.FileChannelImpl.readInternal(FileChannelImpl.java:741)
	at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:727)
	at com.orientechnologies.orient.core.storage.fs.OFileClassic.readByteBuffer(OFileClassic.java:872)
	at com.orientechnologies.orient.core.storage.fs.OFileClassic.read(OFileClassic.java:148)
	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.cacheFileContent(OWOWCache.java:1281)
	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.load(OWOWCache.java:656)
	at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.updateCache(O2QCache.java:1113)
	at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.doLoad(O2QCache.java:353)
	at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.load(O2QCache.java:298)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.loadPage(ODurableComponent.java:148)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.loadPage(ODurableComponent.java:142)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.open(OPaginatedCluster.java:217)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.openClusters(OAbstractPaginatedStorage.java:394)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:316)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:263)
```

**Comment by laa** [comment] 2017-02-23 06:50
Hi @PhantomYdn , how do you restart OrientDB. Is there chance to provide steps or test to reproduce issue on our side ?

**Comment by PhantomYdn** [comment] 2017-02-23 17:49
Andrey, OrientDB lifecycle is being maintained here: 
https://github.com/OrienteerBAP/wicket-orientdb/blob/master/wicket-orientdb/src/main/java/ru/ydn/wicket/wicketorientdb/OrientDbWebApplication.java#L182-L194
So for application refresh we are calling `onBeforeDestroyed()` then do `onAfterInitialized()`

And as I wrote: it was working perfectly on 2.1.19, but not on 2.2.
Testcase should look like: start OrientDb, stop OrientDB, start OrientDB, stop.  On some irregular basis you can observe this problem on second start.

**Comment by laa** [comment] 2017-02-27 07:44
@PhantomYdn it is wicket app, is not it ? Could you create sample WAR and a list of steps which I can use to reproduce an issue?

**Comment by laa** [comment] 2017-03-13 11:15
@PhantomYdn is it possible? it will make our task much easier to do.

**Comment by laa** [comment] 2017-03-28 14:12
@PhantomYdn I have been running following code https://gist.github.com/laa/e0378b7ec9ac56c318bd2006ac50d022 on Windows and Linux machines. In nutshell it performs start/stop 1000 times and creates about 10000 documents are indexed by two indexes between those calls. I

**Comment by PhantomYdn** [comment] 2017-03-28 15:03
@laa, what version of OrientDB did you use?
I will try to understand what executed inside which leads to the highlighted effect. Probably some OrientDB cache or something.

**Comment by laa** [comment] 2017-03-28 15:46
I used the latest snapshot. I suppose it will be released this week so you can try it too.

**Comment by laa** [comment] 2017-04-09 09:08
@PhantomYdn 2.2.18 is out. Looking forward for your feedback

**Comment by laa** [comment] 2017-04-19 11:56
@PhantomYdn did you have a chance to reproduce given issue in new version ?

**Comment by laa** [comment] 2017-04-24 07:00
Hi @PhantomYdn any updates on this ? Could you tell us when you plan to check new version of ODB ?

**Comment by laa** [comment] 2017-05-04 07:05
Hi @PhantomYdn are there any updates on this issue ?

**Comment by laa** [comment] 2017-06-16 09:36
I am going to create and run following test https://gist.github.com/laa/9666aee30823ea5cd5fc3dd0426d7ce9 if during this test I will not encounter the bug I will close this issue.

**Comment by laa** [comment] 2017-07-04 09:58
The test has been running for six days 20 hours, but I was not able to reproduce given an exception. Taking in an account that during edge insertion a lot of files were affected and that we performed engine start/shutdown 1 700 times I suppose we may close given issue as not reproducible. If you reencounter this problem in the version above 2.2.20, I will appreciate if you reopen the issue. We will try to provide feedback ASAP, so we will have a chance to reproduce it and fix.

**Closed by laa** 2017-07-04 09:58 UTC
Labels: bug, cannot replicate, storage team, waiting reply
