### ISSUE TITLE
Migrating from 2.2.x to 3.0RC2 - some queries throw "Invalild value for $current" exceptions

### ISSUE THREAD

**Issue by andreyvk** [orientechnologies/orientdb#8175] opened 2018-03-27 14:34 UTC
Hi, 

Is there any special migration procedure that needs to be done to make 2.2 databases work with the 3.0RC2 release? I've just copied my old db over, but having troubles on some queries. Here's an example:

```sql
select out('is_a')[@class='Person'].out('belongs_to')[@class='Company']["portal"] as portal 
from #35:12
```

That particular query throws an exception in the log:

```
com.orientechnologies.orient.core.exception.OCommandExecutionException: Invalild value for $current: null
        DB name="dev"
        at com.orientechnologies.orient.core.sql.parser.OMethodCall.execute(OMethodCall.java:92)
        at com.orientechnologies.orient.core.sql.parser.OMethodCall.execute(OMethodCall.java:68)
        at com.orientechnologies.orient.core.sql.parser.OModifier.execute(OModifier.java:91)
        at com.orientechnologies.orient.core.sql.parser.OModifier.execute(OModifier.java:104)
        at com.orientechnologies.orient.core.sql.parser.OModifier.execute(OModifier.java:104)
        at com.orientechnologies.orient.core.sql.parser.OBaseExpression.execute(OBaseExpression.java:125)
        at com.orientechnologies.orient.core.sql.parser.OExpression.execute(OExpression.java:109)
        at com.orientechnologies.orient.core.sql.parser.OProjectionItem.execute(OProjectionItem.java:127)
        at com.orientechnologies.orient.core.sql.parser.OProjection.calculateSingle(OProjection.java:114)
        at com.orientechnologies.orient.core.sql.executor.ProjectionCalculationStep.calculateProjections(ProjectionCalculationStep.java:61)
        at com.orientechnologies.orient.core.sql.executor.ProjectionCalculationStep.access$000(ProjectionCalculationStep.java:13)
        at com.orientechnologies.orient.core.sql.executor.ProjectionCalculationStep$1.next(ProjectionCalculationStep.java:38)
        at com.orientechnologies.orient.core.sql.parser.OLocalResultSet.next(OLocalResultSet.java:55)
        at com.orientechnologies.orient.core.sql.parser.OLocalResultSetLifecycleDecorator.next(OLocalResultSetLifecycleDecorator.java:49)
        at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:96)
        at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommandGraph.execute(OServerCommandPostCommandGraph.java:36)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:172)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:633)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:82)
```

**Comment by luigidellaquila** [comment] 2018-03-27 15:08
Hi @andreyvk 

The query seems to be correct and is supposed to work, so I'd say it's a little bug. 
My quick suggestion is to try with latest snapshot https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-community/3.0.0-SNAPSHOT/ there is a significant chance that it's already fixed.

In case it doesn't work, please give me a way to reproduce the problem and I'll fix it asap

Thanks

Luigi

**Comment by andreyvk** [comment] 2018-03-27 18:53
Hi @luigidellaquila,

The snapshot worked (Im using orientdb-community-3.0.0-20180327.051012-1203.tar.gz), however I had to copy `lucene-backward-codecs.jar` over from the stable 2.2.x version as I got this error right away when I was attempting to rebuild indices:

```
com.orientechnologies.orient.core.index.OIndexException: Error on rebuilding the index for clusters: [geographicalzone] DB name="dev" --> java.lang.IllegalArgumentException: Could not load codec 'Lucene53'. Did you forget to add lucene-backward-codecs.jar? --> java.lang.IllegalArgumentException: An SPI class of type org.apache.lucene.codecs.Codec with name 'Lucene53' does not exist. You need to add the corresponding JAR file supporting this SPI to your classpath. The current classpath supports the following names: [Lucene62, SimpleText]
```

Moreover I was unable to rebuild all indices as I got the following exception:

```
Uncaught exception in thread OrientDB HTTP Connection /10.0.2.15:2480<-/10.0.2.2:56434
java.lang.VerifyError: class org.apache.lucene.codecs.lucene40.Lucene40CompoundReader overrides final method renameFile.(Ljava/lang/String;Ljava/lang/String;)V
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.apache.lucene.codecs.lucene40.Lucene40Codec.<init>(Lucene40Codec.java:43)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at org.apache.lucene.util.NamedSPILoader.reload(NamedSPILoader.java:72)
        at org.apache.lucene.util.NamedSPILoader.<init>(NamedSPILoader.java:51)
        at org.apache.lucene.util.NamedSPILoader.<init>(NamedSPILoader.java:38)
        at org.apache.lucene.codecs.Codec$Holder.<clinit>(Codec.java:47)
        at org.apache.lucene.codecs.Codec.getDefault(Codec.java:143)
        at org.apache.lucene.index.LiveIndexWriterConfig.<init>(LiveIndexWriterConfig.java:121)
        at org.apache.lucene.index.IndexWriterConfig.<init>(IndexWriterConfig.java:151)
        at com.orientechnologies.lucene.engine.OLuceneIndexWriterFactory.createIndexWriterConfig(OLuceneIndexWriterFactory.java:26)
        at com.orientechnologies.lucene.engine.OLuceneIndexWriterFactory.createIndexWriter(OLuceneIndexWriterFactory.java:20)
        at com.orientechnologies.lucene.engine.OLuceneFullTextIndexEngine.createIndexWriter(OLuceneFullTextIndexEngine.java:82)
        at com.orientechnologies.lucene.engine.OLuceneIndexEngineAbstract.open(OLuceneIndexEngineAbstract.java:222)
        at com.orientechnologies.lucene.engine.OLuceneIndexEngineAbstract.reOpen(OLuceneIndexEngineAbstract.java:202)
        at com.orientechnologies.lucene.engine.OLuceneIndexEngineAbstract.openIfClosed(OLuceneIndexEngineAbstract.java:402)
        at com.orientechnologies.lucene.engine.OLuceneIndexEngineAbstract.delete(OLuceneIndexEngineAbstract.java:325)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.deleteIndexEngine(OAbstractPaginatedStorage.java:2339)
        at com.orientechnologies.orient.core.index.OIndexAbstract.rebuild(OIndexAbstract.java:434)
        at com.orientechnologies.lucene.index.OLuceneIndexNotUnique.rebuild(OLuceneIndexNotUnique.java:57)
        at com.orientechnologies.orient.core.index.OIndexAbstract.rebuild(OIndexAbstract.java:366)
        at com.orientechnologies.orient.core.sql.parser.ORebuildIndexStatement.executeSimple(ORebuildIndexStatement.java:37)
        at com.orientechnologies.orient.core.sql.executor.OSingleOpExecutionPlan.executeInternal(OSingleOpExecutionPlan.java:99)
        at com.orientechnologies.orient.core.sql.parser.OSimpleExecStatement.execute(OSimpleExecStatement.java:56)
        at com.orientechnologies.orient.core.command.OSqlScriptExecutor.execute(OSqlScriptExecutor.java:44)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.execute(ODatabaseDocumentEmbedded.java:588)
        at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.executeStatement(OServerCommandPostCommand.java:174)
        at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:84)
        at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommandGraph.execute(OServerCommandPostCommandGraph.java:36)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:172)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:633)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:82)
```


Another problem is that Orient always seems to take quite a bit of a CPU at any point of time. Not sure why this happens. Even if I just started Orient and look at the CPU after some time (allowing it to boot and everything):

![cpu](https://user-images.githubusercontent.com/1415506/37987484-20d305b6-3220-11e8-8936-42e21ae687ed.png)

I was also unable to introduce and successfully get a hit on a compound index that I created right away on my existing database. If I understood correctly about the new execution plan, Orient is supposed to pick correct indices now. That does not seem to happen. Behavior resembles one of the 2.2 version. The truncated (and obfuscated for the reasons of non-disclosure agreement) query is:

```sql
 select from MyClass where type='foobar' and myDate <= '2018-03-27 23:59:59' limit 1
```

I've created a compound index on both the `myDate` and `type` altogether before I ran it. Studio's `Explain` output only picked the old `myDate` index for some reason. Here's the output:

```
+ FETCH FROM INDEX MyClass.myDate 
  myDate <= '2018-03-27 23:59:59'
+ EXTRACT VALUE FROM INDEX ENTRY
  filtering clusters [125]
+ FILTER ITEMS WHERE 
  type = 'foobar'
+ FILTER ITEMS BY CLASS 
  MyClass 
+ LIMIT ( LIMIT 1)
```

**Comment by luigidellaquila** [comment] 2018-03-28 07:26
Hi @andreyvk 

probably the problem with Lucene is due to some internal checks (and incompatibilities) that Lucene itself does on its binary format.

About the index, please check that:
- the properties are declared in the right case, v 3.0 is much more strict, the property names are all case sensitive
- the index allows range queries, ie. it's not a hash index

There is also a chance that OrientDB is someway doing an incorrect estimation on the index "efficiency", but to understand if it's the case I'd need a dataset to reproduce the problem

Thanks

Luigi

**Comment by andreyvk** [comment] 2018-03-28 09:41
@luigidellaquila,

Thanks for the reply!

I figured as much about the Lucene later on, but that's  a small thing.

I've defined index from the Studio, so, if internals are working fine, then I think all case sensitivity should be preserved. The index that I created is NONUNIQUE. That should work just fine, right?

Let's see if we can do anything to provide you a portion of our database or at least some dummy version of it. I guess that would be the best for resolving such issues.

**Comment by luigidellaquila** [comment] 2018-03-28 15:11
Hi @andreyvk 

Thank you very much, I'm checking it.
I'll give you a feedback asap

Thanks

Luigi

**Comment by luigidellaquila** [comment] 2018-03-28 15:48
Hi @andreyvk 

I confirm that I managed to reproduce the problem, it seems to be a matter of how OrientDB collects statistics on index usage, the two indexes have very similar stats, so OrientDB just picks one, that by chance is the wrong one.

I'm trying to see how to refine this calculation, I'll keep you updated

Thanks

Luigi

**Comment by andreyvk** [comment] 2018-03-28 17:28
Thanks @luigidellaquila! Looking forward to a good speed up on this one :)

**Comment by luigidellaquila** [comment] 2018-03-29 08:58
HI @andreyvk 

I just pushed a fix for this, the snapshot will be available in a few minutes

Thanks

Luigi

**Closed by luigidellaquila** 2018-03-29 08:58 UTC

**Comment by andreyvk** [comment] 2018-03-29 09:19
@luigidellaquila much obliged :) Thank you!

**Comment by luigidellaquila** [comment] 2018-04-09 09:55
Hi @andreyvk 

sorry for the late reply, I fixed this problems more than one week ago (just forgot to notify... sorry...)

The new snapshot is much smarter at choosing the right index

Thanks

Luigi

**Comment by andreyvk** [comment] 2018-06-25 10:06
Hi @luigidellaquila 

We are still trying to move to new orient. At the moment we are having a problem with querying a class. The query is simple:

`select from TestClass where in('owns')['@rid'] = #34:56`

The `TestClass` is actually some other existing class, but this same query does not produce any results at all (orient 2.2 is behaves fine of course). The database was just copied from 2.2 to 3.0.

Plz let me know what's needed to resolve the issue. Im not sure what to do next here. Im also able to provide a test database that can be used to replicate the issue

**Comment by luigidellaquila** [comment] 2018-06-25 10:24
Hi @andreyvk 

V 3.0 is much more accurate in evaluating SQL statements, and that query in particular has a lot of problems:

- the in() method returns a list, so you have to use `CONTAINS` instead of `=`  (btw, why are you using `['@rid']`? You just don't need it)

This will do the trick

```
select from TestClass where in('owns') CONTAINS #34:56
```

- filtering on traversal is extremely inefficient, if you re-write the query the other way around it will be much faster:

```
SELECT expand(out('owns')) FROM #34:56
```

I hope it helps

Thanks

Luigi

**Comment by andreyvk** [comment] 2018-06-25 12:49
That worked nicely, thanks! However, i cant figure out now why "Explain" in the studio doesnt print out used indexes. How can i check now?

**Comment by luigidellaquila** [comment] 2018-06-25 12:51
Hi @andreyvk 

The new EXPLAIN is a bit different from the old one, it gives you full information about all the query execution steps. If an index is uses, you'll see a FETCH FROM INDEX step. If you are using both 2.2.x and 3.0 together, please make sure you refresh the browser so that Studio reloads completely, otherwise you could have some weird behavior

Thanks

Luigi
