### ISSUE TITLE
Error wile autodeploy: The process can not access the file because part of the file is locked by another process

### ISSUE THREAD

**Issue by nin-jin** [orientechnologies/orientdb#3819] opened 2015-03-26 15:46 UTC
I start one instantance and create one db on them
Then i start second instance and db not deployed

2015-03-26 18:26:50:585 INFO  [beta] Saving distributed configuration file for database 'skeddy' to: ..\db2\databases\skeddy\distributed-config.json [OHazelcastPlugin]
2015-03-26 18:26:54:608 WARNING [beta]->[[alpha]] requesting deploy of database 'skeddy' on local server... [OHazelcastPlugin]
2015-03-26 18:26:54:647 INFO  [beta]<-[alpha] received updated status beta.skeddy=SYNCHRONIZING [OHazelcastPlugin]
2015-03-26 18:26:54:662 INFO  [beta]<-[alpha] received updated status alpha.skeddy=SYNCHRONIZING [OHazelcastPlugin]
2015-03-26 18:23:05:006 WARNING [beta]->[[alpha]] deploy returned: {alpha=java.io.IOException: The process can not access the file because part of the file is locked by another process}
at java.io.FileInputStream.readBytes(Native Method)
        at java.io.FileInputStream.read(Unknown Source)
        at com.orientechnologies.common.io.OIOUtils.copyStream(OIOUtils.java:156)
        at com.orientechnologies.orient.core.compression.impl.OZIPCompressionUtil.addFolder(OZIPCompressionUtil.java:142)
        at com.orientechnologies.orient.core.compression.impl.OZIPCompressionUtil.addFolder(OZIPCompressionUtil.java:120)
        at com.orientechnologies.orient.core.compression.impl.OZIPCompressionUtil.addFolder(OZIPCompressionUtil.java:120)
        at com.orientechnologies.orient.core.compression.impl.OZIPCompressionUtil.addFolder(OZIPCompressionUtil.java:120)
        at com.orientechnologies.orient.core.compression.impl.OZIPCompressionUtil.compressDirectory(OZIPCompressionUtil.java:51)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocalPaginatedStorage.backup(OLocalPaginatedStorage.java:152)
        at com.orientechnologies.orient.server.distributed.ODistributedStorage.backup(ODistributedStorage.java:1218)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.backup(ODatabaseDocumentTx.java:2495)
        at com.orientechnologies.orient.server.distributed.task.ODeployDatabaseTask.execute(ODeployDatabaseTask.java:129)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.executeOnLocalNode(OHazelcastPlugin.java:757)
        at com.orientechnologies.orient.server.hazelcast.ODistributedWorker.onMessage(ODistributedWorker.java:300)
        at com.orientechnologies.orient.server.hazelcast.ODistributedWorker.run(ODistributedWorker.java:121)
Exception in thread "main" com.orientechnologies.orient.server.distributed.ODistributedException: No response received from remote nodes for auto-deploy of database
        at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.installDatabase(OHazelcastPlugin.java:968)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.installNewDatabases(OHazelcastPlugin.java:1226)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.startup(OHazelcastPlugin.java:185)
        at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.java:871)
        at com.orientechnologies.orient.server.OServer.activate(OServer.java:265)
        at com.orientechnologies.orient.server.OServerMain.main(OServerMain.java:41)

Version: 2.0.5

**Comment by wildroco** [comment] 2015-05-07 06:54
I have same problem while deploying database from first node to second node.

After some tests, I found Lucene index (Spatial) is cause of problem. All job is done well when I delete the index from my class of first node.

But, the index have to be in my database, so the problem is still not solved perfectly.

any suggestions or helps?

**Comment by nin-jin** [comment] 2015-05-07 10:14
https://github.com/orientechnologies/orientdb/issues/4012

**Comment by lvca** [comment] 2015-09-23 23:06
@maggiolo00 Is this already fixed on last snapshots?

**Comment by lvca** [comment] 2015-11-22 19:13
Any news on this?

**Comment by lvca** [comment] 2015-11-22 19:14
I'm closing it in the meanwhile, in case please reopen/comment it.

**Closed by lvca** 2015-11-22 19:14 UTC
Labels: bug
