### ISSUE TITLE
Backslash stripped from latex strings

### ISSUE THREAD

**Issue by stanonyime** [orientechnologies/orientdb#2978] opened 2014-10-24 09:59 UTC
I'm importing a large database from Couchdb into Orientdb using Oriento nodejs library. I found out that the backslashes are stripped from the Latex equations:
Example: \frac{3}{4} is transformed to rac{3}{4}

I'm using Orientdb 1.7.9

**Comment by stanonyime** [comment] 2015-03-13 14:24
The problem still exists Orientdb 2.0.4

**Comment by luigidellaquila** [comment] 2015-09-21 06:26
hi @stanonyime 
Are you creating this property using SQL or from a programmatic API?
Could you please provide a snippet of code?

Thanks

**Comment by prjhub** [comment] 2015-10-07 11:42
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.

**Comment by stanonyime** [comment] 2015-10-11 10:37
From Orientdb studio:
1. create class bugtest
2. insert into bugtest set bd = "\frac{3}{4}"
3. select bd from bugtest

**Comment by luigidellaquila** [comment] 2016-05-23 15:32
Back-slashes have to be quoted in strings, eg.
```
insert into bugtest set bd = "\\frac{3}{4}"
```

Closing

Thanks

Luigi

**Closed by luigidellaquila** 2016-05-23 15:32 UTC
Labels: bug
