### ISSUE TITLE
Getting error while importing database

### ISSUE THREAD

**Issue by vigneshsenapathy** [orientechnologies/orientdb#7815] opened 2017-10-12 17:23 UTC
## Expected behavior  
import should happen without exception  

## Actual behavior  
getting error on schema

## Steps to reproduce  
1)  create a database with multiple schemas and multiple records in it. I have records and schemas in both Vertex Classes and Edge Classes
2) export the database from a different box/container but running
 /orientdb/bin/console.sh "connect remote:${ORIENTDB_ADDRESS}/testing root ${ORIENTDB_ROOT_PASSWORD};EXPORT DATABASE /orientdb/databases/backup_${DATE}.export"
this creates the file locally which is called backup_${DATE}.export.gz
3) now import the db on a different environment using the following command
    /orientdb/bin/console.sh "connect remote:${ORIENTDB_ADDRESS}/testing root ${ORIENTDB_ROOT_PASSWORD};IMPORT DATABASE /orientdb/$s3filename -format=orientdb -preserveClusterIDs=false"

I get an error Importing database schema saying:
com.orientechnologies.orient.core.db.tool.ODatabaseImportException: Invalid format. Found unsupported tag 'cluster-selection'
	at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importDatabase(ODatabaseImport.java:189)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.importDatabase(ONetworkProtocolBinary.java:3000)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:719)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:397)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:220)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:81)

I dont know why full export is not importing the db. I dont know if there any steps missing from the above things i specified

**Comment by vigneshsenapathy** [comment] 2017-10-13 00:12
Please let me know if there is anything wrong in the way i am doing things with the import and export of orientdb

**Comment by luigidellaquila** [comment] 2017-10-19 08:38
Hi @vigneshsenapathy 

I just tried it with latest 2.2.29 and I saw that in the import you are using `-format=orientdb`, that is not supported:

```
Error: java.lang.IllegalArgumentException: Format 'orientdb' is not supported
```

Removing it, the import succeeds on my machine.

Maybe the problem is due to something on your environment? Please give me some more info and I'll try to help further

Thanks

Luigi

**Comment by vigneshsenapathy** [comment] 2017-10-24 14:35
@luigidellaquila : are u doing remove import or local import?

**Comment by luigidellaquila** [comment] 2017-10-24 15:09
Hi @vigneshsenapathy 

I'm using the exact same commands you posted in the original question (so remote), just changing the DB name and the credentials 

Thanks

Luigi

**Comment by acuciureanu** [comment] 2017-11-09 08:00
I had the same issue and it appears that it doesn't reproduce anymore for me in 2.2.29.

**Comment by luigidellaquila** [comment] 2017-11-09 10:48
Hi @acuciureanu @vigneshsenapathy 

yes, I think it was fixed in latest release, @vigneshsenapathy could you please confirm that it also works for you?

Thanks

Luigi

**Comment by luigidellaquila** [comment] 2017-11-24 16:37
Hi @acuciureanu 

As I wrote above, this seems to work fine in latest stable release. I'm closing this ticket, please feel free to re-open if you need any further help

Thanks

Luigi

**Closed by luigidellaquila** 2017-11-24 16:37 UTC
Labels: question, waiting reply
