### ISSUE TITLE
Simple faceted search

### ISSUE THREAD

**Issue by minnownoir** [orientechnologies/orientdb#2444] opened 2014-06-07 20:18 UTC
Need to be able to do simple faceted search (a la Solr or ElasticSearch) within OrientDB document databases.

**Comment by voondo** [comment] 2015-08-23 11:21
Duplicate of https://github.com/orientechnologies/orientdb-lucene/issues/38

**Comment by lvca** [comment] 2017-08-03 13:58
Duplicated, closing

**Closed by lvca** 2017-08-03 13:58 UTC
Labels: duplicate, enhancement
