### ISSUE TITLE
"java.lang.OutOfMemoryError: GC overhead limit exceeded" on massive Insert

### ISSUE THREAD

**Issue by AlexanderRay** [orientechnologies/orientdb#3517] opened 2015-02-03 13:09 UTC
Hi, 

I got an OutOfMemoryError while inserting about 10^6 Nodes in a OrientGraph.

orientdb.err

```
2015-02-03 11:18:03:156 INFO  OrientDB auto-config DISKCACHE=13,880MB (heap=455MB os=16,384MB disk=105,812MB) [orientechnologies]
2015-02-03 11:18:03:160 INFO  Loading configuration from: /usr/local/Cellar/orientdb/2.0.1/libexec/config/orientdb-server-config.xml... [OServerConfigurationLoaderXml]
2015-02-03 11:18:03:398 INFO  OrientDB Server v2.0.1 (build UNKNOWN@r; 2015-01-28 18:33:00+0000) is starting up... [OServer]
2015-02-03 11:18:03:432 INFO  Databases directory: /usr/local/Cellar/orientdb/2.0.1/libexec/databases [OServer]
2015-02-03 11:18:03:487 INFO  Listening binary connections on 0.0.0.0:2424 (protocol v.28, socket=default) [OServerNetworkListener]
2015-02-03 11:18:03:489 INFO  Listening http connections on 0.0.0.0:2480 (protocol v.10, socket=default) [OServerNetworkListener]
2015-02-03 11:18:03:509 INFO  Installing dynamic plugin 'orientdb-lucene-2.0-dist.jar'... [OServerPluginManager]
2015-02-03 11:18:03:661 INFO  Lucene index plugin installed and active. Lucene version: LUCENE_47 [OLuceneIndexPlugin]
2015-02-03 11:18:03:663 INFO  Installing dynamic plugin 'studio-2.0.zip'... [OServerPluginManager]
2015-02-03 11:18:03:692 INFO  Installing GREMLIN language v.2.6.0 - graph.pool.max=50 [OGraphServerHandler]
2015-02-03 11:18:03:693 INFO  [OVariableParser.resolveVariables] Error on resolving property: distributed [orientechnologies]
2015-02-03 11:18:03:694 INFO  Installing Script interpreter. WARN: authenticated clients can execute any kind of code into the server by using the following allowed languages: [sql] [OServerSideScriptInterpreter]
2015-02-03 11:18:03:695 INFO  OrientDB Server v2.0.1 is active. [OServer]%                                                               14:03 log master ❯ cat orientdb.err

2015-02-03 11:18:03:155 INFO  OrientDB auto-config DISKCACHE=13,880MB (heap=455MB os=16,384MB disk=105,812MB) [orientechnologies]
2015-02-03 11:18:03:160 INFO  Loading configuration from: /usr/local/Cellar/orientdb/2.0.1/libexec/config/orientdb-server-config.xml... [OServerConfigurationLoaderXml]
2015-02-03 11:18:03:397 INFO  OrientDB Server v2.0.1 (build UNKNOWN@r; 2015-01-28 18:33:00+0000) is starting up... [OServer]
2015-02-03 11:18:03:432 INFO  Databases directory: /usr/local/Cellar/orientdb/2.0.1/libexec/databases [OServer]
2015-02-03 11:18:03:487 INFO  Listening binary connections on 0.0.0.0:2424 (protocol v.28, socket=default) [OServerNetworkListener]
2015-02-03 11:18:03:488 INFO  Listening http connections on 0.0.0.0:2480 (protocol v.10, socket=default) [OServerNetworkListener]
2015-02-03 11:18:03:509 INFO  Installing dynamic plugin 'orientdb-lucene-2.0-dist.jar'... [OServerPluginManager]
2015-02-03 11:18:03:660 INFO  Lucene index plugin installed and active. Lucene version: LUCENE_47 [OLuceneIndexPlugin]
2015-02-03 11:18:03:663 INFO  Installing dynamic plugin 'studio-2.0.zip'... [OServerPluginManager]
2015-02-03 11:18:03:692 INFO  Installing GREMLIN language v.2.6.0 - graph.pool.max=50 [OGraphServerHandler]
2015-02-03 11:18:03:692 INFO  [OVariableParser.resolveVariables] Error on resolving property: distributed [orientechnologies]
2015-02-03 11:18:03:694 INFO  Installing Script interpreter. WARN: authenticated clients can execute any kind of code into the server by using the following allowed languages: [sql] [OServerSideScriptInterpreter]
2015-02-03 11:18:03:694 INFO  OrientDB Server v2.0.1 is active. [OServer]Exception in thread "Timer-0" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.concurrent.ConcurrentHashMap$EntrySetView.iterator(ConcurrentHashMap.java:4746)
	at com.orientechnologies.orient.server.plugin.OServerPluginManager.updatePlugins(OServerPluginManager.java:277)

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Timer-0"
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at java.util.Arrays.copyOfRange(Arrays.java:3664)
	at java.lang.String.<init>(String.java:201)
	at java.lang.StringBuilder.toString(StringBuilder.java:407)
	at java.io.ObjectStreamField.getClassSignature(ObjectStreamField.java:322)
	at java.io.ObjectStreamField.<init>(ObjectStreamField.java:140)
	at java.io.ObjectStreamClass.matchFields(ObjectStreamClass.java:2259)
	at java.io.ObjectStreamClass.getReflector(ObjectStreamClass.java:2149)
	at java.io.ObjectStreamClass.<init>(ObjectStreamClass.java:517)
	at java.io.ObjectStreamClass.lookup(ObjectStreamClass.java:365)
	at java.io.ObjectStreamClass.<init>(ObjectStreamClass.java:464)
	at java.io.ObjectStreamClass.lookup(ObjectStreamClass.java:365)
	at java.io.ObjectStreamClass.<init>(ObjectStreamClass.java:464)Exception in thread "OrientDB <- BinaryClient (/127.0.0.1:54626)" java.lang.OutOfMemoryError: GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
java.lang.OutOfMemoryError: GC overhead limit exceeded
```

a test class in scala:

```scala
package model.orientdb

import com.orientechnologies.orient.core.intent.OIntentMassiveInsert
import com.orientechnologies.orient.core.sql.OCommandSQL
import com.tinkerpop.blueprints.impls.orient.{OrientVertex, OrientGraphFactory, OrientGraph}
import org.scalatest._
import de.softamrhein.Logger

class OrientDBGraphAPISpec extends FlatSpecLike
  with BeforeAndAfter
  with BeforeAndAfterAll
  with Matchers
  with Logger
{

  var factory: OrientGraphFactory = null
  var graph: OrientGraph = null

  override def beforeAll() = {
    factory = new OrientGraphFactory("remote:localhost/test")
  }

  override def afterAll() = {
    factory.close()
  }

  before {
    graph = factory.getTx
    graph.getRawGraph.declareIntent( new OIntentMassiveInsert() );
  }

  after {
    graph.commit()
    graph.shutdown()
  }


  "Graph" can "remove everything" in {

    graph.command(new OCommandSQL("delete Vertex Structure")).execute()
    graph.command(new OCommandSQL("delete Vertex StructureNode")).execute()

    graph.command(new OCommandSQL("delete Edge childNode")).execute()
    graph.command(new OCommandSQL("delete Edge rootNode")).execute()


    assert(true)
  }



  def createStructure(ident: String, nodePrefix: String, levelCount: Int, nodesPerLevel: Int) = {

    val structureVertex = graph.addVertex("class:Structure", "ident", ident)

    def loop (currentLevel: Int, parentVertex: OrientVertex, edgeClass: String): Unit = {

      if (currentLevel < levelCount) {

        (1 to nodesPerLevel).foreach { idx =>

          val nodeVertex = graph.addVertex("class:StructureNode", "ident", nodePrefix + '-' + currentLevel + '-' + idx)
          parentVertex.addEdge(edgeClass, nodeVertex, edgeClass)

          loop(currentLevel + 1, nodeVertex, "childNode")
        }

      }

    }

    loop(0, structureVertex, "rootNode")
  }

  it can "create small 1-level structure" in {
    createStructure("structure-1-level", "Node1l", 1, 10)
  }

  it can "create 2-level structure" in {
    createStructure("structure-2-level", "Node2l", 2, 10)
  }

  it can "create 3-level structure" in {
    createStructure("structure-3-level", "Node3l", 3, 10)
  }

  it can "create 4-level structure" in {
    createStructure("structure-4-level", "Node4l", 4, 10)
  }

  it can "create 5-level structure" in {
    createStructure("structure-5-level", "Node5l", 5, 10)
  }

  it can "create 6-level structure" in {
    createStructure("structure-6-level", "Node6l", 6, 10)
  }
}
```

**Comment by rtc-draper** [comment] 2015-02-03 14:33
There's a thread on working around this issue here: http://stackoverflow.com/questions/5839359/java-lang-outofmemoryerror-gc-overhead-limit-exceeded

I recommend trying with the GC limit turned off first, then trying one of the other options.

**Comment by 8forty** [comment] 2015-02-03 15:08
I don't know Scala, but FWIW in Java we've had up the heap memory in the orient server (and turn down the off-heap cache memory accordingly) to support multi-threaded clients writing to the database.

**Comment by jingjingbic** [comment] 2015-02-03 21:33
I am getting the same error in my inserts too. I am using OrientDB 2.0.1. Our application uses embedded server and access data through java API.

Thanks,
Jing

**Comment by AlexanderRay** [comment] 2015-02-04 14:11
more infos after some recharge:

1. database "remote:..." - no one of java setting helps. if I use -Xmx8g then it runs without any GC-Errors, but the tests wasn't also finished after 2 hours

2. database "plocal:..."
    * first run (= fresh/empty database):

![screen shot 2015-02-04 at 14 29 21](https://cloud.githubusercontent.com/assets/786006/6041681/ec2a26ac-ac7e-11e4-9827-090c8b738d67.png)
![screen shot 2015-02-04 at 15 05 10](https://cloud.githubusercontent.com/assets/786006/6041712/429b3832-ac7f-11e4-827f-1be50cd13d9e.png)

ca 6500 records per second. its ok. not 150.000 -) records per second. but its ok.

    * second run (= at first delete the records from the first run):
after 20 minutes :

![screen shot 2015-02-04 at 14 56 56](https://cloud.githubusercontent.com/assets/786006/6041732/9166c972-ac7f-11e4-8eb6-160ac5c24f8b.png)
 its create a large file and breaks because of insufficient free space.
ok, I have only 110 GB free in the test drive. but I don't think it is a right behavior

**Comment by AlexanderRay** [comment] 2015-02-04 14:31
if it helps, I can create an java-test-project or upload my scala-test-project to github ...

**Comment by laa** [comment] 2015-02-04 14:51
Hi,
I suppose you insert 10^6 Nodes in single transaction, do not you ?

On Wed, Feb 4, 2015 at 4:31 PM, Alexander Ray <notifications@github.com>
wrote:

> if it helps, I can create an java-test-project or upload my
> scala-test-project to github ...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/3517#issuecomment-72863125>
> .
>



-- 
Best regards,
Andrey Lomakin.

**Comment by AlexanderRay** [comment] 2015-02-04 14:54
yes.

**Comment by laa** [comment] 2015-02-04 15:04
That is reason of huge wal file.
We need to log whole tx operation as single unit.
That is reason of OOM too.
Could you split your tx in few smaller txs.

On Wed, Feb 4, 2015 at 4:54 PM, Alexander Ray <notifications@github.com>
wrote:

> yes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/3517#issuecomment-72867713>
> .
>



-- 
Best regards,
Andrey Lomakin.

**Comment by AlexanderRay** [comment] 2015-02-04 15:07
the huge wal file was created only on the second run. after the Vertexes und Edges was deleted and the transaction was commited

``` scala
  before {
    graph = factory.getTx
    graph.getRawGraph.declareIntent( new OIntentMassiveInsert() );
  }

  after {
    graph.commit()
    graph.shutdown()
  }

  "Graph" can "remove everything" in {
    graph.command(new OCommandSQL("delete Vertex Structure")).execute()
    graph.command(new OCommandSQL("delete Vertex StructureNode")).execute()
    graph.command(new OCommandSQL("delete Edge childNode")).execute()
    graph.command(new OCommandSQL("delete Edge rootNode")).execute()
    assert(true)
  }

```

**Comment by laa** [comment] 2015-02-04 15:15
It is created when tx is commited, but before this all data is collected in
heap.



On Wed, Feb 4, 2015 at 5:07 PM, Alexander Ray <notifications@github.com>
wrote:

> the huge wal file was created only on the second run. after the Vertexes
> und Edges was deleted and the transaction was commited
>
>   before {
>     graph = factory.getTx
>     graph.getRawGraph.declareIntent( new OIntentMassiveInsert() );
>   }
>
>   after {
>     graph.commit()
>     graph.shutdown()
>   }
>
>   "Graph" can "remove everything" in {
>     graph.command(new OCommandSQL("delete Vertex Structure")).execute()
>     graph.command(new OCommandSQL("delete Vertex StructureNode")).execute()
>     graph.command(new OCommandSQL("delete Edge childNode")).execute()
>     graph.command(new OCommandSQL("delete Edge rootNode")).execute()
>     assert(true)
>   }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/3517#issuecomment-72870669>
> .
>



-- 
Best regards,
Andrey Lomakin.

**Comment by AlexanderRay** [comment] 2015-02-04 15:28
i see, it was created in the test "create 6-level structure" during commit. 

1. only on the second run (the database was logically in the same state as in the first run)
2. what for need the database engine that huge (>100GB) wal file by commitment only about 1.000.000 simple records?

**Comment by AlexanderRay** [comment] 2015-02-04 15:40
ok. I see your point. therefore the question:

what are the transaction limits, so that orientdb-engine can handle the commitment properly?

**Comment by laa** [comment] 2015-02-05 07:16
Hi Alexander,
I think in 2.1 we will implement early OOM detection mechanics, if we have
risk of OOM we will rollback tx will suggest to decrease amount of
operations and repeat tx, it will allow to avoid puzzled OOM errors.

On Wed, Feb 4, 2015 at 5:40 PM, Alexander Ray <notifications@github.com>
wrote:

> ok. I see your point. therefore the question:
>
> what are the transaction limits, so that orientdb-engine can handle the
> commitment properly?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/3517#issuecomment-72876952>
> .
>



-- 
Best regards,
Andrey Lomakin.

**Comment by AlexanderRay** [comment] 2015-02-05 08:43
ok.

1. what are the guidelines for using transactions?
2. some tests result without transaction (graph = factory.getNoTx) 
- first run
![wotx - 1 run](https://cloud.githubusercontent.com/assets/786006/6057120/a72fa4ea-ad1a-11e4-988a-2455c0e1cf6b.png)
it is slower as with Tx ca. 7200 records per second
- second run
![screen shot 2015-02-05 at 09 35 06](https://cloud.githubusercontent.com/assets/786006/6057138/d7a74466-ad1a-11e4-9033-718e0c46b4c6.png)
![screen shot 2015-02-05 at 09 34 40](https://cloud.githubusercontent.com/assets/786006/6057140/dab65c28-ad1a-11e4-97aa-5db76c2e304c.png)
    - more slower as the first run 
    - creates about 700 wal files, each ca 150 MB 
    - and _BREAKS BECAUSE OG INSUFFICIENT FREE SPACE_

**Comment by lvca** [comment] 2015-02-05 16:15
Can you share the piece of code that write to the database? Are you
executing SQL statements to create vertices and edges?

Lvc@

**Comment by AlexanderRay** [comment] 2015-02-05 17:10
```scala

/**
 * User: Alexander Ray
 */

package model.orientdb

import com.orientechnologies.orient.core.intent.OIntentMassiveInsert
import com.orientechnologies.orient.core.sql.OCommandSQL
import com.tinkerpop.blueprints.impls.orient.{OrientBaseGraph, OrientVertex, OrientGraphFactory, OrientGraph}
import org.scalatest._
import de.softamrhein.Logger
import scalax.file.Path

class OrientDBGraphAPISpec extends FlatSpecLike
  with BeforeAndAfter
  with BeforeAndAfterAll
  with Matchers
  with Logger
{

  var factory: OrientGraphFactory = null
  var graph: OrientBaseGraph = null
  val dbPath = "/Users/alexanderray/Develop/orientdb/databases/test"

  val createNewDatabase = false
  val localDatabase = true
  val useTx = false

  def createTestClasses() = {
    val g = factory.getNoTx

    g.command(new OCommandSQL("create class Structure extends V")).execute()
    g.command(new OCommandSQL("create class StructureNode extends V")).execute()
    g.command(new OCommandSQL("create property StructureNode.ident STRING")).execute()

    g.command(new OCommandSQL("create class rootNode extends E")).execute()
    g.command(new OCommandSQL("create class childNode extends E")).execute()

    g.shutdown()
  }

  override def beforeAll() = {
    if (createNewDatabase && localDatabase) {
      val path: Path = Path.fromString (dbPath)
      path.deleteRecursively(continueOnFailure = false)
    }

    factory = new OrientGraphFactory(if (localDatabase) "plocal:/" + dbPath else "remote:localhost/test")

    if (createNewDatabase && localDatabase) createTestClasses()
  }

  override def afterAll() = {
    factory.close()
  }

  before {
    graph = if (useTx) factory.getTx else factory.getNoTx
    graph.getRawGraph.declareIntent( new OIntentMassiveInsert() );
  }

  after {
    graph.shutdown()
  }

  "Graph" can "remove everything" in {

    graph.command(new OCommandSQL("delete Vertex Structure")).execute()
    graph.command(new OCommandSQL("delete Vertex StructureNode")).execute()

    graph.command(new OCommandSQL("delete Edge childNode")).execute()
    graph.command(new OCommandSQL("delete Edge rootNode")).execute()


    assert(true)
  }



  def createStructure(ident: String, nodePrefix: String, levelCount: Int, nodesPerLevel: Int) = {

    val structureVertex = graph.addVertex("class:Structure", "ident", ident)

    def loop (currentLevel: Int, parentVertex: OrientVertex, edgeClass: String): Unit = {

      if (currentLevel < levelCount) {

        (1 to nodesPerLevel).foreach { idx =>

          val nodeVertex = graph.addVertex("class:StructureNode", "ident", nodePrefix + '-' + currentLevel + '-' + idx)
          parentVertex.addEdge(edgeClass, nodeVertex, edgeClass)

          loop(currentLevel + 1, nodeVertex, "childNode")
        }

      }

    }

    loop(0, structureVertex, "rootNode")

    if (useTx) graph.commit()
  }

  it can "create small 1-level structure" in {
    createStructure("structure-1-level", "Node1l", 1, 10)
  }

  it can "create 2-level structure" in {
    createStructure("structure-2-level", "Node2l", 2, 10)
  }

  it can "create 3-level structure" in {
    createStructure("structure-3-level", "Node3l", 3, 10)
  }

  it can "create 4-level structure" in {
    createStructure("structure-4-level", "Node4l", 4, 10)
  }

  it can "create 5-level structure" in {
    createStructure("structure-5-level", "Node5l", 5, 10)
  }

  it can "create 6-level structure" in {
    createStructure("structure-6-level", "Node6l", 6, 10)
  }
}
```

**Comment by lvca** [comment] 2015-02-05 17:24
Ok, seems in your loop you have too many objects in transactions (that is RAM consuming). Try rather to put this inside the loop:

    if( useTx && currentLevel % 500 == 0 )
      graph.commit()

**Comment by lvca** [comment] 2015-02-05 17:24
In this way you commit every 500 items.

**Comment by AlexanderRay** [comment] 2015-02-05 17:38
transactions in the last test are disabled (val useTx = false)

**Comment by AlexanderRay** [comment] 2015-02-05 17:47
what is the difference between small transactions and no transactions?  after first small transaction database is in a "dirty-inconsistent-state". and I can't properly rollback anymore in case on some failure ...

**Comment by AlexanderRay** [comment] 2015-02-05 18:14
test with small - 500 items

new code
``` scala

def createStructure(ident: String, nodePrefix: String, levelCount: Int, nodesPerLevel: Int) = {

    val structureVertex = graph.addVertex("class:Structure", "ident", ident)
    var cnt = 0

    def loop (currentLevel: Int, parentVertex: OrientVertex, edgeClass: String): Unit = {

      if (currentLevel < levelCount) {

        (1 to nodesPerLevel).foreach { idx =>

          val nodeVertex = graph.addVertex("class:StructureNode", "ident", nodePrefix + '-' + currentLevel + '-' + idx)
          parentVertex.addEdge(edgeClass, nodeVertex, edgeClass)

          cnt += 1

          if( useTx && cnt % 500 == 0 )
            graph.commit()

          loop(currentLevel + 1, nodeVertex, "childNode")
        }

      }


    }

    loop(0, structureVertex, "rootNode")

    if (useTx) graph.commit()
  }

```

* first run
![screen shot 2015-02-05 at 18 44 41]
(https://cloud.githubusercontent.com/assets/786006/6066120/e3399c8e-ad6a-11e4-86f1-d9a3b602a0e6.png)

* second run
![screen shot 2015-02-05 at 19 10 15](https://cloud.githubusercontent.com/assets/786006/6066123/ef5d7b5c-ad6a-11e4-9df9-4aa76c893746.png)

same behavior as before 
   * creates 600 wal files for 100 GB
   * breakes because of low disc space

**Comment by laa** [comment] 2015-02-06 09:14
It is already fixed in 2.0.2 could you try it ?

On Thu, Feb 5, 2015 at 8:14 PM, Alexander Ray <notifications@github.com>
wrote:

> test with small - 500 items
>
> new code
>
> def createStructure(ident: String, nodePrefix: String, levelCount: Int, nodesPerLevel: Int) = {
>
>     val structureVertex = graph.addVertex("class:Structure", "ident", ident)
>     var cnt = 0
>
>     def loop (currentLevel: Int, parentVertex: OrientVertex, edgeClass: String): Unit = {
>
>       if (currentLevel < levelCount) {
>
>         (1 to nodesPerLevel).foreach { idx =>
>
>           val nodeVertex = graph.addVertex("class:StructureNode", "ident", nodePrefix + '-' + currentLevel + '-' + idx)
>           parentVertex.addEdge(edgeClass, nodeVertex, edgeClass)
>
>           cnt += 1
>
>           if( useTx && cnt % 500 == 0 )
>             graph.commit()
>
>           loop(currentLevel + 1, nodeVertex, "childNode")
>         }
>
>       }
>
>
>     }
>
>     loop(0, structureVertex, "rootNode")
>
>     if (useTx) graph.commit()
>   }
>
>
>    -
>
>    first run
>    [image: screen shot 2015-02-05 at 18 44 41]
>    <https://cloud.githubusercontent.com/assets/786006/6066120/e3399c8e-ad6a-11e4-86f1-d9a3b602a0e6.png>
>    -
>
>    second run
>    [image: screen shot 2015-02-05 at 19 10 15]
>    <https://cloud.githubusercontent.com/assets/786006/6066123/ef5d7b5c-ad6a-11e4-9df9-4aa76c893746.png>
>
> same behavior as before
>
>    - creates 600 wal files for 100 GB
>    - breakes because of low disc space
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/3517#issuecomment-73096709>
> .
>



-- 
Best regards,
Andrey Lomakin.

**Comment by lvca** [comment] 2015-02-06 10:08
This is the URL of last 2.0.2-SNAPSHOT: https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-community/2.0.2-SNAPSHOT/orientdb-community-2.0.2-20150205.232920-6-distribution.tar.gz

**Comment by AlexanderRay** [comment] 2015-02-06 11:11
without TX - same behavior as before

**Comment by AlexanderRay** [comment] 2015-02-06 11:25
with small (500 records) Tx - same behavior as before

**Comment by AlexanderRay** [comment] 2015-02-06 11:27
may be the test-project is linked with wrong libraries, how can I log the current library version at runtime?

**Comment by AlexanderRay** [comment] 2015-02-06 11:38
with one big Tx - same behavior as before

**Comment by laa** [comment] 2015-02-06 12:29
Alexander did you try on 2.0.2 snapshot ?

**Comment by laa** [comment] 2015-02-06 12:30
It should be INFO  OrientDB Server v2.0.2 is active. Did you see such message ?

**Comment by laa** [comment] 2015-02-06 12:35
You may try to download distribution from there https://www.dropbox.com/s/c7l62cd7fgdshy7/orientdb-community-2.0.2-SNAPSHOT-distribution.zip?dl=0

**Comment by AlexanderRay** [comment] 2015-02-06 12:59
1. yes. I have tried it with both snapshots version above and copied the lib folder to my project ... 
2. if I use "plocal" database, then it runs with out any active orientdb server, just linked jars ... 
3. inside of IntelliJ the right libraries are linked to project, 
4. but, may be, at runtime sbt (scala build tool) links something wrong. how can I log at runtime the library versions?

**Comment by AlexanderRay** [comment] 2015-02-06 13:05
so, I have created a war file, it contains right (2.0.2-snapshot) libraries  ..

**Comment by laa** [comment] 2015-02-06 13:17
ok. if test will fail again I will try to repeat the same on my side.

**Comment by AlexanderRay** [comment] 2015-02-06 13:23
it is. I have tested it with the snapshot from dropbox. same results ... on a second run test 6 fails because of many/huge wal files

**Comment by laa** [comment] 2015-02-06 13:24
no way, ok I will try it locally

**Comment by laa** [comment] 2015-02-06 14:29
I ran several times and had only one wal file after test ends.

**Comment by AlexanderRay** [comment] 2015-02-06 14:38
ok, should I upload my test-project? or can you upload yours?

**Comment by laa** [comment] 2015-02-06 14:51
few seconds I have found reason

**Comment by laa** [comment] 2015-02-06 15:17
Could you try now same link to distribution.

**Closed by laa** 2015-02-06 15:17 UTC
Labels: bug

**Comment by AlexanderRay** [comment] 2015-02-06 15:20
which one?

**Comment by laa** [comment] 2015-02-06 15:26
https://www.dropbox.com/s/c7l62cd7fgdshy7/orientdb-community-2.0.2-SNAPSHOT-distribution.zip?dl=0

**Comment by AlexanderRay** [comment] 2015-02-06 15:36
also, it creates many wal files as before ... in test 5. for commit in about 100.000 records, orientdb creates wal files 60 wal files each ca 150MB, also about 10GB of wal files for commitment of 100.000 records. why? 

test 6 runs, for now 219 wal files ...

**Comment by AlexanderRay** [comment] 2015-02-06 16:00
![screen shot 2015-02-06 at 16 57 20](https://cloud.githubusercontent.com/assets/786006/6082414/9c39b3d4-ae21-11e4-9a57-ecb5b3f55947.png)
![screen shot 2015-02-06 at 16 59 56](https://cloud.githubusercontent.com/assets/786006/6082417/a275a366-ae21-11e4-8d1f-c880472ab88b.png)

**Comment by AlexanderRay** [comment] 2015-02-06 16:03
also, nothing changes

**Comment by laa** [comment] 2015-02-06 16:23
I repeated your test and all work, it means that you use old distribution. Is it possible for you to build from sources ? branch hotfix-2.0.2

**Comment by lvca** [comment] 2015-02-06 16:25
Guys, I can force upload on maven if needed.

**Comment by AlexanderRay** [comment] 2015-02-06 16:27
I use that one: 

![screen shot 2015-02-06 at 17 25 05](https://cloud.githubusercontent.com/assets/786006/6082918/1b632674-ae25-11e4-9ee6-4af40861acd9.png)

ehh .. ok, i'll try it ...

**Comment by AlexanderRay** [comment] 2015-02-06 17:16
it fails' don't know why .. 

![screen shot 2015-02-06 at 17 45 25](https://cloud.githubusercontent.com/assets/786006/6083346/33356a3e-ae28-11e4-9bb5-3f50318621e5.png)

**Comment by AlexanderRay** [comment] 2015-02-06 17:17
I have created a java-test project. 

you can upload it here: 
https://www.dropbox.com/s/v6c8ymb5n87vxk8/test-n-level-tree.zip?dl=0

**Comment by laa** [comment] 2015-02-06 17:23
It seems you never recreated database, just replaced jar.  Did you ?

**Comment by laa** [comment] 2015-02-06 17:24
And you missed linkedhashmap dependency, you can find it in distribution.

**Comment by laa** [comment] 2015-02-06 17:24
concurrentlinkedhashmap-lru-1.4.1.jar

**Comment by AlexanderRay** [comment] 2015-02-06 17:26
1. the build from the sources fails. but I don't need it), also it ok
2. the database is always created on the first run

**Comment by laa** [comment] 2015-02-06 17:41
yes, you see it is running and truncated automatically http://screencloud.net/v/22t1

**Comment by laa** [comment] 2015-02-06 17:42
wal files from 18 to 22

**Comment by laa** [comment] 2015-02-06 17:45
hm now it is running huge, but I suppose I will find issue in test ))

**Comment by AlexanderRay** [comment] 2015-02-06 17:45
ok, you can also reproduce it?

**Comment by laa** [comment] 2015-02-06 17:46
yes

**Comment by AlexanderRay** [comment] 2015-02-06 17:48
super-)

**Comment by laa** [comment] 2015-02-06 17:57
and seems found a bug. ))
Lets wait 30 min, I will run 2 times.

**Comment by laa** [comment] 2015-02-06 18:36
Just for next time. If you need to remove all data, do not do "delete all" action.  Do truncate otherwise insertions will be slow.

**Comment by AlexanderRay** [comment] 2015-02-06 18:36
truncate?

**Comment by laa** [comment] 2015-02-06 18:53
truncate class ... command

**Comment by AlexanderRay** [comment] 2015-02-06 18:54
ok, I see, thanks)

**Comment by laa** [comment] 2015-02-06 18:56
Could you try now ? https://www.dropbox.com/s/c7l62cd7fgdshy7/orientdb-community-2.0.2-SNAPSHOT-distribution.zip?dl=0

**Comment by AlexanderRay** [comment] 2015-02-08 20:21
Hi, now it works, but, as you say, after delete, its very slow. it is possible to restructure the database, so I can insert records at the same speed as before delete (for my purposes, I need sometimes to delete 80-90 percent from class records)?

**Comment by AlexanderRay** [comment] 2015-02-08 20:26
how can I speed up my inserts. You say it is possible to make till to 200.000 inserts per second on common hardware. I have I7, ssd, 16GB ram, but the maximum speed is about 11.000 records per second ... can you upload some benchmark test with 200.000 inserts per second, so I can test it on my hardware?

**Comment by laa** [comment] 2015-02-09 06:55
Alexander,
Do not do delete all use truncate, and it will not be slow.

On Sun, Feb 8, 2015 at 10:26 PM, Alexander Ray <notifications@github.com>
wrote:

> how can I speed up my inserts. You say it is possible to make till to
> 200.000 inserts per second on common hardware. I have I7, ssd, 16GB ram,
> but the maximum speed is about 11.000 records per second ... can you upload
> some benchmark test with 200.000 inserts per second, so I can test it on my
> hardware?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/3517#issuecomment-73429701>
> .
>



-- 
Best regards,
Andrey Lomakin.

**Comment by AlexanderRay** [comment] 2015-02-09 10:39
I see, 
1. but what can I do, if I need to delete not all of the records, but only 80 or 90 percent of them? should I use "truncate record".
2. is it possible to restructure the database after "massive delete"? may be with backup/restore?
3. what is about a "speed-insert" example?

**Comment by laa** [comment] 2015-02-09 11:13
Hi

   1. We are developing new cluster design to overcome this issue, I think
   it will take about 1.5 month to release it.
   2. You can do it by export/import.
   3. Sorry did not get it.




On Mon, Feb 9, 2015 at 12:39 PM, Alexander Ray <notifications@github.com>
wrote:

> I see,
> 1. but what can I do, if I need to delete not all of the records, but only
> 80 or 90 percent of them? should I use "truncate record".
> 2. is it possible to restructure the database after "massive delete"? may
> be with backup/restore?
> 3. what is about a "speed-insert" example?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/3517#issuecomment-73488165>
> .
>



-- 
Best regards,
Andrey Lomakin.

**Comment by lvca** [comment] 2015-02-09 11:14
Alexander,
you could create multiple clusters and just drop the clusters the contain the data you want to drop. This would be super fast and efficient. What kind of data do you have? How you filter the 80/90% of data you delete?

**Comment by AlexanderRay** [comment] 2015-02-09 11:22
Thanks, it is a good idea to use multiple clusters for storing data and to drop it by cluster. I will try it so.

**Comment by AlexanderRay** [comment] 2015-02-09 11:27
You write that orientdb can store till to 220.000 records on common hardware. What type of records? which API? Have you an example what achieve that insert speed on yours hardware?

**Comment by lvca** [comment] 2015-02-09 11:32
220k as massive insertion in multi-threads, no wal, no index and Document API with documents with 6 fields.

**Comment by AlexanderRay** [comment] 2015-02-09 11:33
plocal or remote?

**Comment by lvca** [comment] 2015-02-09 11:41
plocal.

**Comment by AlexanderRay** [comment] 2015-02-09 11:43
thanks for your advise)

**Comment by AlexanderRay** [comment] 2015-02-09 18:45
just for info, here are my multithread test results: 

![screen shot 2015-02-09 at 15 12 11](https://cloud.githubusercontent.com/assets/786006/6112957/0515074a-b094-11e4-8e02-03610b768c22.png)

**Comment by saritseal** [comment] 2015-11-12 12:16
Hi,

The OOM error does not seem to be fixed yet. I am using 2.2-alpha. Can you please point me to the JIRA for this issue

Regards
Sarit

**Comment by lvca** [comment] 2015-11-13 03:25
Try getting last snapshot: https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-community/2.2.0-SNAPSHOT/

**Comment by nishantkumar1292** [comment] 2017-07-26 10:31
Hi @lvca .... I am getting this error when inserting records in multiple threads. I am using version 2.2.21.
```
505 HTTP Version Not Supported: {
  "errors": [
    {
      "code": 505,
      "reason": 505,
      "content": "java.lang.OutOfMemoryError: GC overhead limit exceeded"
    }
  ]
}
```

Is the issue fixed? Any ideas how can I get this resolved.

**Comment by laa** [comment] 2017-07-26 11:53
@nishantkumar1292 OOM is to general issue and may be caused by many factors do you have heap dump generated by OOM in server directory?

**Comment by nishantkumar1292** [comment] 2017-07-26 16:45
@laa I have no idea about the heap dump. Where can I find the heap dump?

**Comment by laa** [comment] 2017-07-27 09:35
@nishantkumar1292 how many cores do you have? Yes, that is possible that all memory was consumed by the handling of temporary data generated during query processing? Do you use command cache? Could you switch it off? About heap dump, it should be in server or bin directory and have .hprof extension.

**Comment by nishantkumar1292** [comment] 2017-07-27 12:20
I have 8 cores and they are all being used at around 98-99%.
Yes...found the heap dump file.
No not using command cache. Below is the `command.cache.json` file.
```
{
  "enabled": false,
  "evictStrategy": "INVALIDATE_ALL",
  "minExecutionTime": 10,
  "maxResultsetSize": 500
}

```

**Comment by laa** [comment] 2017-07-27 12:52
@nishantkumar1292 1500 threads too much for 8 cores you will have a lot of context switches and as result bigger memory consumption and worse performance, in reality, big CPU usage does not mean better performance. Amount of threads is up to you of course, could you send me this file I will check it but I am on 99% sure that is caused by big memory consumption of queries

**Comment by nishantkumar1292** [comment] 2017-07-27 13:14
Yes you are right..... decreasing the number of threads improved the performance and also eliminated `Request Timeout`.
What is the maximum number of threads I can work with. Each thread does some CREATE, READ and UPDATE operations.

**Comment by laa** [comment] 2017-07-27 13:24
@nishantkumar1292 it is hard to say, but my preference is not more than 10 for a single core. ok, let say 20. so in our case, it should be 160 but not 1500 it is an enormous number. You can limit the number of threads by handling user requests in the thread pool.

**Comment by nishantkumar1292** [comment] 2017-07-27 13:27
What do you mean by **handling user requests in thread pool**?

**Comment by laa** [comment] 2017-07-27 13:40
I do not know how your architecture I just proposed that you accept HTTP request, for example, parse them and execute a command. So commands may be executed in a separate thread pool.

**Comment by nishantkumar1292** [comment] 2017-07-27 18:27
Was running scripts on 100 parallel threads.
```
Error on client connection
java.lang.OutOfMemoryError: GC overhead limit exceeded
$ANSI{green {db=db_development}} Exception `3AD12824` in storage `db_development`
java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "OrientDB ONetworkProtocolHttpDb listen at 0.0.0.0:2480-2490" java.lang.OutOfMemoryError: GC overhead limit exceeded
Exception in thread "OrientDB Write Cache Flush Task (db_development)" 
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "OrientDB Write Cache Flush Task (db_development)"
```
How can I resolve this?

**Comment by nishantkumar1292** [comment] 2017-07-31 07:42
Hi @laa ...any updates or resolution for the above issue?
