### ISSUE TITLE
File with name config.cd does not exist in <dbname>

### ISSUE THREAD

**Issue by sunilrebel** [orientechnologies/orientdb#9391] opened 2020-09-14 18:46 UTC
## Expected behavior  
Database should be accessible after orientdb starts without exceptions or at least should be exported in case of disaster recovery  

## Actual behavior  
OrientDB is starting correctly, but database is not opening because of which all of our data is lost (in corrupted db files) and not able to run exports and I'm not able to connect to db.

### Stacktrace
```
2020-09-15 00:11:46:972 INFO  OrientDB Studio available at http://192.168.1.50:2480/studio/index.html [OServer]
2020-09-15 00:11:46:972 INFO  OrientDB Server is active v3.0.27 - Veloce (build bc8f77600494cab71fb347d4c29f71c793442464, branch 3.0.x). [OServer]
2020-09-15 00:12:00:487 INFO  Page size for WAL located in /path/to/orientdb-3.0.27/databases/mydb is set to 4096 bytes. [OCASDiskWriteAheadLog]Exception `32A10CAB` in storage `plocal:/path/to/orientdb-3.0.27/databases/mydb`: 3.0.27 - Veloce (build bc8f77600494cab71fb347d4c29f71c793442464, branch 3.0.x)
com.orientechnologies.orient.core.exception.OStorageException: File with name config.cd does not exist in storage mydb
	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.loadFile(OWOWCache.java:732)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.openFile(ODurableComponent.java:192)
	at com.orientechnologies.orient.core.storage.cluster.v1.OPaginatedClusterV1.open(OPaginatedClusterV1.java:204)
	at com.orientechnologies.orient.core.storage.config.OClusterBasedStorageConfiguration.load(OClusterBasedStorageConfiguration.java:176)
	at com.orientechnologies.orient.core.storage.disk.OLocalPaginatedStorage.initConfiguration(OLocalPaginatedStorage.java:455)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:306)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthenticate(OrientDBEmbedded.java:238)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthenticate(OrientDBEmbedded.java:56)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:936)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:913)
	at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeDatabaseOpen37(OConnectionBinaryExecutor.java:1187)
	at com.orientechnologies.orient.client.remote.message.OOpen37Request.execute(OOpen37Request.java:77)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:310)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:212)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)

```

Console output while trying to connect to db
```
Connecting to database [remote:localhost/mydb] with user 'root'...
Error: com.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database 'mydb'

Error: com.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database 'mydb'

Error: com.orientechnologies.orient.core.exception.OStorageException: File with name config.cd does not exist in storage mydb

orientdb {server=remote:localhost/mydb}> 
```

**Comment by florian-stoica-tlabs** [comment] 2021-01-20 13:07
I'm in the same spot Orient version 3.0.22 java 11 os ubuntu is there some news on this? (I don't have a reproduction path, it just happened at some point)

**Comment by ebanchio** [comment] 2021-06-17 11:23
Hi! I had the same problem using orient 3.1.5. Any news about this?

	DWL:database: block size = 4096 bytes, maximum segment size = 347 MB [DoubleWriteLogGL]Exception `18748728` in storage `plocal:/path/to/database`: 3.1.5 - Veloce (build 846eeb77dcb175a9fbd7ed534e039424322f44a7, branch 3.1.x)
	com.orientechnologies.orient.core.exception.OStorageException: Exception during execution of atomic operation inside of storage database
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideAtomicOperation(OAtomicOperationsManager.java:195)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:422)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.open(OrientDBEmbedded.java:483)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.open(OrientDBEmbedded.java:418)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:979)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:947)
	at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeDatabaseOpen37(OConnectionBinaryExecutor.java:1369)
	at com.orientechnologies.orient.client.remote.message.OOpen37Request.execute(OOpen37Request.java:75)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:355)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:239)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:67)
	Caused by: com.orientechnologies.orient.core.exception.OStorageException: Exception during execution of component operation inside component config.cd in storage database
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideComponentOperation(OAtomicOperationsManager.java:221)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideComponentOperation(OAtomicOperationsManager.java:206)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.executeInsideComponentOperation(ODurableComponent.java:102)
	at com.orientechnologies.orient.core.storage.cluster.v2.OPaginatedClusterV2.open(OPaginatedClusterV2.java:211)
	at com.orientechnologies.orient.core.storage.config.OClusterBasedStorageConfiguration.load(OClusterBasedStorageConfiguration.java:250)
	at com.orientechnologies.orient.core.storage.disk.OLocalPaginatedStorage.initConfiguration(OLocalPaginatedStorage.java:558)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.lambda$open$1(OAbstractPaginatedStorage.java:433)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideAtomicOperation(OAtomicOperationsManager.java:189)
	... 10 more
	Caused by: com.orientechnologies.orient.core.exception.OStorageException: File with name config.cd does not exist in storage database
	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.loadFile(OWOWCache.java:760)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationBinaryTracking.loadFile(OAtomicOperationBinaryTracking.java:372)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.openFile(ODurableComponent.java:193)
	at com.orientechnologies.orient.core.storage.cluster.v2.OPaginatedClusterV2.lambda$open$1(OPaginatedClusterV2.java:216)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideComponentOperation(OAtomicOperationsManager.java:214)
	... 17 more

**Comment by andrii0lomakin** [comment] 2021-10-21 07:05
Fixed by PR above.

**Closed as completed by andrii0lomakin** 2021-10-21 07:05 UTC
Labels: bug
