### ISSUE TITLE
select expand(rid) from index:collection.field where key lucene limit N - work slow

### ISSUE THREAD

**Issue by apapacy** [orientechnologies/orientdb#7513] opened 2017-06-29 11:00 UTC
### Java Version: openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-0ubuntu1.16.04.2-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
## Expected behavior  
select expand(rid) from index:collection.field where key lucene 'Харько~0.2' limit 3
mast work fine

## Actual behavior  
Dont work. OrientDB process corrupt. Database not accessible. Need kill + start.sh

## Steps to reproduce  
insert into class more 1 000 000 document with same "word" and select key lucene 'word~0.3' limit 2

select expand(rid) from index:collection.field where key lucene 'Харько~0.2' limit 3 - not work

**Comment by robfrank** [comment] 2017-06-30 12:15
How is the index created? Are you using a Russian analyzer or the standard one?

**Comment by robfrank** [comment] 2017-06-30 12:45
I'm unable to reproduce the problem. The commits I added are a little SQL script to create a sample dataset and a test. Tested in remote too.
May you provide more sample data and command used to create the index?

**Comment by apapacy** [comment] 2017-06-30 13:46
Im use standart OrientDB Version: 2.2.22 community edition.
Im do not specify any additional analyzer.
How can I add Russian analyzer? Are there any instructions in the OrientDB documentation?

**Comment by robfrank** [comment] 2017-06-30 13:51
Documentation about lucene indexes:

http://orientdb.com/docs/last/Full-Text-Index.html

Yoy will find how to configure custom analyzers for fields

Without sample dataset and command used to create the index, I can't do more.

**Comment by apapacy** [comment] 2017-06-30 14:11
I'll do another test with an analyzer.

My simple data is 4 500 000 documents {message: 'Харьков - 1'}, {message: 'Харьков - 2'} ...
My query select expand(rid) from index:test.message key 'Харько~0.3' limit 2.

Maybe the "limit 2" is not working as I thought? And all data in processing?

**Comment by robfrank** [comment] 2017-06-30 14:22
Why don't simply use the select from test where lucene 'Харько~0.3' limit 2?
moreover, it seems that your "message" field are single term, why are you usingn the slop operator '~' ? 
The limit is processed AFTER the search on the index, the lucene index only manage the lucene query, not the sql part. So the index could find 10000 docs and then only the firts 2 will be returned.
This is resonable, because the full-text query could be part of a more complex query, and the limit should work on the global result, not only on the index one.

**Comment by apapacy** [comment] 2017-06-30 14:57
https://github.com/orientechnologies/orientdb/issues/7193

If create 2 indexes on same column (fulltext lucene and some other) select not use right index but first created (Hobson's choice)

**Comment by robfrank** [comment] 2017-06-30 15:05
Thanks for the explanation about the api. How many documents are extracted with the query without the limit clause? I tested only the behavior of the query, but I guess the problem is in the size of the result set in conjunction with expand. May you restrict the query to limit the number of documents retrieved?

**Comment by apapacy** [comment] 2017-06-30 15:24
My create statement
create class russian
create property russian.message string

My insertion

odb.insert().into('russian').set({message: `Харьков - ${k} - ${i}` }).one().catch(function(err){console.log(err);});
k=1...1000
i=1...1000

So. there are 1 000 000 document of class "russian"

select * from russian where message lucene 'Харько~0.1' limit 2 - work fine
select rid from index:russian.message where key lucene 'Харько~0.1' limit 2 - work fine

But this select seems as too heavy (anout 10 s.)
select expand(rid) from index:russian.message where key lucene 'Харько~0.1' limit 2

![image](https://user-images.githubusercontent.com/4279840/27742362-02f1197c-5dc1-11e7-9aa9-69ab3a8d2ac6.png)

If count of document not 1 000 000 but 4 500 000 process corrupt

**Comment by luigidellaquila** [comment] 2017-07-02 07:35
Hi @apapacy 

The problem seems to be in the SQL query executor, not in the Lucene index plugin.
I'm fixing it now

Thanks

Luigi

**Comment by luigidellaquila** [comment] 2017-07-02 07:48
Hi @apapacy 

I just pushed a fix on branch 2.2.x, the fix will be available in V 2.2.23

Thanks

Luigi

**Closed by luigidellaquila** 2017-07-02 07:48 UTC
Labels: bug

**Comment by apapacy** [comment] 2017-07-02 22:34
Thanks.
