### ISSUE TITLE
Lucene Error during exception deserialization: 

### ISSUE THREAD

**Issue by temilmg** [orientechnologies/orientdb#5791] opened 2016-03-01 15:07 UTC
Lucene integration fails after a heavy use with an exception (see below).
It looks like a simple Class not found issue but I have used the following maven dependency

<dependency>
<groupId>com.orientechnologies</groupId>
<artifactId>orientdb-graphdb</artifactId>
<version>2.1.11</version>
</dependency>

and the documentation says lucene is part of orientdb now so I guess I shouldn't have to add a lucene dependency, also initially the queries work!
Furthermore when it starts failing it completely spams my logfile, I have eneded up with 8gb log files full of the exception seen below. When failing the cpu goes to a 100 and orientdb becomes unresponsive. A server restart clears the problem but after a while the problem returns.

Im using orientdb 2.1.11 (in docker)

The failing query looks as follows:
select text,title,subtitle, url from Data_14_0  where i18n=? and [pid,title,subtitle,text,words1,words2] lucene ("text:ergo^4 title:ergo^8 subtitle:ergo^2 pid:ergo^10 words1:ergo^3 words2:ergo^2") skip 0 limit 10

My index: 
CREATE INDEX Data_14_0.pid_title_subtitle_text_words1_words2 ON Data_14_0(pid,title,subtitle,text,words1,words2) FULLTEXT ENGINE LUCENE

Feb 29, 2016 12:58:42 PM com.orientechnologies.common.log.OLogManager log
WARNING: Caught I/O errors from orientdb/172.17.0.2:2424 (local socket=/172.17.0.4:37597), trying to reconnect (error: java.io.IOException: Error during exception deserialization: java.lang.ClassNotFoundException: org.apache.lucene.queryparser.classic.ParseException)
Feb 29, 2016 12:58:42 PM com.orientechnologies.common.log.OLogManager log
WARNING: Connection re-acquired transparently after 3ms and 1 retries to server 'orientdb:2424/tenant-dana': no errors will be thrown at application level
Feb 29, 2016 12:58:42 PM com.orientechnologies.common.log.OLogManager log
SEVERE: Error during exception deserialization
java.lang.ClassNotFoundException: org.apache.lucene.queryparser.classic.ParseException
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:626)
at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1613)
at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518)
at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1774)
at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000)
at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:501)
at java.lang.Throwable.readObject(Throwable.java:914)
at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1058)
at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1900)
at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.throwSerializedException(OChannelBinaryAsynchClient.java:434)
at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:398)
at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:282)
at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:170)
at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:2158)
at com.orientechnologies.orient.client.remote.OStorageRemote.command(OStorageRemote.java:1188)
at com.orientechnologies.orient.client.remote.OStorageRemoteThread.command(OStorageRemoteThread.java:444)
at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:72)
at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
at com.tinkerpop.blueprints.impls.orient.OrientGraphCommand.execute(OrientGraphCommand.java:49)
at dk.mxi.liveapp.integration.ApiSearchEndpoint.lambda$doRoutes$13(ApiSearchEndpoint.java:140)

**Comment by maggiolo00** [comment] 2016-03-02 09:09
hi @temilmg 

yes lucene is part of orientdb. In fact the query works. The problem is when on server side a lucene parsing exception occurs.
The stack trace is serialized and send to the client. We are changing this. For now you should add also orientdb-lucene in your pom
just to handle exception.

**Comment by temilmg** [comment] 2016-03-02 10:25
Thanks for dealing with this. I am temporarily using a regex instead when I get the time I will move back to using lucene.
Its my first time reporting anything here so I dont know what the procedure is, do I just close the issue!?

**Comment by maggiolo00** [comment] 2016-03-02 10:31
hi @temilmg 

i think i will close it an reopen it as an orientdb improvement in managing exception.
BTW if you add orientdb-lucene in your pom the ClassNotFoundException will go away.

**Comment by robfrank** [comment] 2016-05-17 14:28
If you use docker, a better way is to derive your image from the official one: https://hub.docker.com/_/orientdb/

**Closed by robfrank** 2016-05-17 14:28 UTC
Labels: waiting reply
