### ISSUE TITLE
Opening a database in 3.2.2 then cannot be opened in 3.2.0

### ISSUE THREAD

**Issue by johny65** [orientechnologies/orientdb#9693] opened 2021-10-06 13:29 UTC
## Expected behavior  

I don't know if this is the expected behavior or if it was changed, but if I open a 3.2.0 database in a 3.2.2 server, I would expect to be able to open it again in 3.2.0.

I.e. a database should be able to be opened in different 3.2.x servers without problems.

## Actual behavior  

If I open a 3.2.0 database in a 3.2.2 server, and then open it in 3.2.0 again, it fails with an exception and can't be opened:

```
Exception `58252E0E` in storage `plocal:/opt/orientdb-3.2.0/databases/mydatabase`: 3.2.0 (build c08b76230798b477a8abbf2312b30ecddad842ad, branch develop)
java.lang.IllegalStateException: Invalid version of the binary format of startup metadata file found 4 but expected 3
	at com.orientechnologies.orient.core.storage.impl.local.paginated.StorageStartupMetadata.open(StorageStartupMetadata.java:259)
	at com.orientechnologies.orient.core.storage.disk.OLocalPaginatedStorage.checkIfStorageDirty(OLocalPaginatedStorage.java:528)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:368)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.getAndOpenStorage(OrientDBEmbedded.java:543)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.open(OrientDBEmbedded.java:494)
	at com.orientechnologies.orient.core.db.OrientDBDistributed.open(OrientDBDistributed.java:216)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.open(OrientDBEmbedded.java:434)
	at com.orientechnologies.orient.core.db.OrientDBDistributed.open(OrientDBDistributed.java:201)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:855)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:848)
	at com.orientechnologies.orient.server.network.protocol.http.command.OServerCommandAuthenticatedDbAbstract.authenticate(OServerCommandAuthenticatedDbAbstract.java:194)
	at com.orientechnologies.orient.server.network.protocol.http.command.OServerCommandAuthenticatedDbAbstract.beforeExecute(OServerCommandAuthenticatedDbAbstract.java:136)
	at com.orientechnologies.orient.server.network.protocol.http.command.get.OServerCommandGetConnect.beforeExecute(OServerCommandGetConnect.java:55)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:239)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:800)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:67)
```

## Steps to reproduce  

Create a database in 3.2.0, open it in 3.2.2, then open it in 3.2.0.

**Comment by andrii0lomakin** [comment] 2021-10-06 14:02
Once you open the database in a higher version there are migration scripts that change the underlying format. Those scripts are running in the background and newer format can not be read by the database with a lower version.

**Comment by jamieb22** [comment] 2021-10-07 04:35
Andrey, I just like to make you aware that the Orient DB approach to upgrades is problematic.

1) If a user performs a minor version upgrade i.e. 3.2.0 -> 3.2.2, there is the user expectation that this is a minor bug fix to code algorithms and won't necessitate changes to the structure of the database. One would assume that changes to data structure should be reserved for major version updates only i.e. v3 -> v4.

2) Orient DB often introduces major breaking changes between "minor" version updates, like removing functionality that impacts  compatibility with prior versions. Once your database is automatically "upgraded", you cannot downgrade to escape a breaking change, and therefore are stuck on a broken version.

3) Correct me if I am wrong, but there doesn't appear to be any automated tests covering upgrades so performing an upgrade is a high risk operation.

4) The Orient DB team appears to favor feature and performance enhancement above maintaining stability and backwards compatibility. Since the principal function of a database is to preserve data, this approach is misguided.

**Comment by andrii0lomakin** [comment] 2021-10-07 05:05
Hi @jamieb22 , can not admit that there is a sense in the observations which you made. I will think about a smoother approach of the introduction of features. For example, they will be optional until the next major release.

**Comment by andrii0lomakin** [comment] 2021-10-11 07:09
I am closing this issue, it was actually done by design but for future changes, we will consider approaches that allow downgrading DB version in case that is the minor release version.

**Closed as completed by andrii0lomakin** 2021-10-11 07:09 UTC
