### ISSUE TITLE
Exception while creating OObjectDatabaseTx 

### ISSUE THREAD

**Issue by stawny** [orientechnologies/orientdb#3287] opened 2014-12-28 15:14 UTC
I have dependecies:
```
	<dependencies>
		<dependency>
			<groupId>com.orientechnologies</groupId>
			<artifactId>orientdb-jdbc</artifactId>
			<version>2.0-M3</version>
		</dependency>
		<dependency>
			<groupId>javassist</groupId>
			<artifactId>javassist</artifactId>
			<version>3.16.1-GA</version>
		</dependency>
	</dependencies>
```
my class contains only one line

```
OObjectDatabaseTx db = new OObjectDatabaseTx ("remote:localhost/test").open("admin", "admin");
```

and the console output is
```
gru 28, 2014 4:08:34 PM com.orientechnologies.common.log.OLogManager log
INFO: Auto-config DISKCACHE=1 159MB (heap=247MB osMemory=3 454MB)
gru 28, 2014 4:08:34 PM com.orientechnologies.common.log.OLogManager log
WARNING: The Client driver version is different than Server version: client=26, server=21. You could not use the full features of the newer version. Assure to have the same versions on both
gru 28, 2014 4:08:34 PM com.orientechnologies.common.log.OLogManager log
WARNING: Error deserializing record c2NoZW1hVmVyc2lvbjo0LGNsYXNzZXM6PChuYW1lOiJPVHJpZ2dlcmVkIixzaG9ydE5hbWU6LGRlZmF1bHRDbHVzdGVySWQ6LTEsY2x1c3RlcklkczpbLTFdLGNsdXN0ZXJTZWxlY3Rpb246InJvdW5kLXJvYmluIixvdmVyU2l6ZTowLjBmLHN0cmljdE1vZGU6ZmFsc2UsYWJzdHJhY3Q6dHJ1ZSxwcm9wZXJ0aWVzOjw+LHN1cGVyQ2xhc3M6LGN1c3RvbUZpZWxkczopLChuYW1lOiJPU2NoZWR1bGUiLHNob3J0TmFtZTosZGVmYXVsdENsdXN0ZXJJZDo4LGNsdXN0ZXJJZHM6WzhdLGNsdXN0ZXJTZWxlY3Rpb246InJvdW5kLXJvYmluIixvdmVyU2l6ZTowLjBmLHN0cmljdE1vZGU6ZmFsc2UsYWJzdHJhY3Q6ZmFsc2UscHJvcGVydGllczo8KG5hbWU6InN0YXJ0dGltZSIsdHlwZTo2LG1hbmRhdG9yeTpmYWxzZSxyZWFkb25seTpmYWxzZSxub3ROdWxsOmZhbHNlLG1pbjosbWF4OixyZWdleHA6LGN1c3RvbUZpZWxkczosY29sbGF0ZToiZGVmYXVsdCIpLChuYW1lOiJhcmd1bWVudHMiLHR5cGU6MTIsbWFuZGF0b3J5OmZhbHNlLHJlYWRvbmx5OmZhbHNlLG5vdE51bGw6ZmFsc2UsbWluOixtYXg6LHJlZ2V4cDosY3VzdG9tRmllbGRzOixjb2xsYXRlOiJkZWZhdWx0IiksKG5hbWU6InN0YXJ0Iix0eXBlOjAsbWFuZGF0b3J5OmZhbHNlLHJlYWRvbmx5OmZhbHNlLG5vdE51bGw6ZmFsc2UsbWluOixtYXg6LHJlZ2V4cDosY3VzdG9tRmllbGRzOixjb2xsYXRlOiJkZWZhdWx0IiksKG5hbWU6InN0YXR1cyIsdHlwZTo3LG1hbmRhdG9yeTpmYWxzZSxyZWFkb25seTpmYWxzZSxub3ROdWxsOmZhbHNlLG1pbjosbWF4OixyZWdleHA6LGN1c3RvbUZpZWxkczosY29sbGF0ZToiZGVmYXVsdCIpLChuYW1lOiJydWxlIix0eXBlOjcsbWFuZGF0b3J5OnRydWUscmVhZG9ubHk6ZmFsc2Usbm90TnVsbDp0cnVlLG1pbjosbWF4OixyZWdleHA6LGN1c3RvbUZpZWxkczosY29sbGF0ZToiZGVmYXVsdCIpLChuYW1lOiJuYW1lIix0eXBlOjcsbWFuZGF0b3J5OnRydWUscmVhZG9ubHk6ZmFsc2Usbm90TnVsbDp0cnVlLG1pbjosbWF4OixyZWdleHA6LGN1c3RvbUZpZWxkczosY29sbGF0ZToiZGVmYXVsdCIpLChuYW1lOiJmdW5jdGlvbiIsdHlwZToxMyxtYW5kYXRvcnk6dHJ1ZSxyZWFkb25seTpmYWxzZSxub3ROdWxsOnRydWUsbWluOixtYXg6LHJlZ2V4cDosbGlua2VkQ2xhc3M6Ik9GdW5jdGlvbiIsY3VzdG9tRmllbGRzOixjb2xsYXRlOiJkZWZhdWx0Iik+LHN1cGVyQ2xhc3M6LGN1c3RvbUZpZWxkczopLChuYW1lOiJFIixzaG9ydE5hbWU6LGRlZmF1bHRDbHVzdGVySWQ6MTAsY2x1c3RlcklkczpbMTBdLGNsdXN0ZXJTZWxlY3Rpb246InJvdW5kLXJvYmluIixvdmVyU2l6ZTowLjBmLHN0cmljdE1vZGU6ZmFsc2UsYWJzdHJhY3Q6ZmFsc2UscHJvcGVydGllczo8PixzdXBlckNsYXNzOixjdXN0b21GaWVsZHM6KSwobmFtZToiT1JJRHMiLHNob3J0TmFtZTosZGVmYXVsdENsdXN0ZXJJZDo2LGNsdXN0ZXJJZHM6WzZdLGNsdXN0ZXJTZWxlY3Rpb246InJvdW5kLXJvYmluIixvdmVyU2l6ZTowLjBmLHN0cmljdE1vZGU6ZmFsc2UsYWJzdHJhY3Q6ZmFsc2UscHJvcGVydGllczo8PixzdXBlckNsYXNzOixjdXN0b21GaWVsZHM6KSwobmFtZToiT1JvbGUiLHNob3J0TmFtZTosZGVmYXVsdENsdXN0ZXJJZDo0LGNsdXN0ZXJJZHM6WzRdLGNsdXN0ZXJTZWxlY3Rpb246InJvdW5kLXJvYmluIixvdmVyU2l6ZTowLjBmLHN0cmljdE1vZGU6ZmFsc2UsYWJzdHJhY3Q6ZmFsc2UscHJvcGVydGllczo8KG5hbWU6Im5hbWUiLHR5cGU6NyxtYW5kYXRvcnk6dHJ1ZSxyZWFkb25seTpmYWxzZSxub3ROdWxsOnRydWUsbWluOixtYXg6LHJlZ2V4cDosY3VzdG9tRmllbGRzOixjb2xsYXRlOiJjaSIpLChuYW1lOiJpbmhlcml0ZWRSb2xlIix0eXBlOjEzLG1hbmRhdG9yeTpmYWxzZSxyZWFkb25seTpmYWxzZSxub3ROdWxsOmZhbHNlLG1pbjosbWF4OixyZWdleHA6LGxpbmtlZENsYXNzOiJPUm9sZSIsY3VzdG9tRmllbGRzOixjb2xsYXRlOiJkZWZhdWx0IiksKG5hbWU6InJ1bGVzIix0eXBlOjEyLG1hbmRhdG9yeTpmYWxzZSxyZWFkb25seTpmYWxzZSxub3ROdWxsOmZhbHNlLG1pbjosbWF4OixyZWdleHA6LGxpbmtlZFR5cGU6MTcsY3VzdG9tRmllbGRzOixjb2xsYXRlOiJkZWZhdWx0IiksKG5hbWU6Im1vZGUiLHR5cGU6MTcsbWFuZGF0b3J5OmZhbHNlLHJlYWRvbmx5OmZhbHNlLG5vdE51bGw6ZmFsc2UsbWluOixtYXg6LHJlZ2V4cDosY3VzdG9tRmllbGRzOixjb2xsYXRlOiJkZWZhdWx0Iik+LHN1cGVyQ2xhc3M6Ik9JZGVudGl0eSIsY3VzdG9tRmllbGRzOiksKG5hbWU6IlYiLHNob3J0TmFtZTosZGVmYXVsdENsdXN0ZXJJZDo5LGNsdXN0ZXJJZHM6WzldLGNsdXN0ZXJTZWxlY3Rpb246InJvdW5kLXJvYmluIixvdmVyU2l6ZToyLjBmLHN0cmljdE1vZGU6ZmFsc2UsYWJzdHJhY3Q6ZmFsc2UscHJvcGVydGllczo8PixzdXBlckNsYXNzOixjdXN0b21GaWVsZHM6KSwobmFtZToiT0Z1bmN0aW9uIixzaG9ydE5hbWU6LGRlZmF1bHRDbHVzdGVySWQ6NyxjbHVzdGVySWRzOls3XSxjbHVzdGVyU2VsZWN0aW9uOiJyb3VuZC1yb2JpbiIsb3ZlclNpemU6MC4wZixzdHJpY3RNb2RlOmZhbHNlLGFic3RyYWN0OmZhbHNlLHByb3BlcnRpZXM6PChuYW1lOiJpZGVtcG90ZW50Iix0eXBlOjAsbWFuZGF0b3J5OmZhbHNlLHJlYWRvbmx5OmZhbHNlLG5vdE51bGw6ZmFsc2UsbWluOixtYXg6LHJlZ2V4cDosY3VzdG9tRmllbGRzOixjb2xsYXRlOiJkZWZhdWx0IiksKG5hbWU6Im5hbWUiLHR5cGU6NyxtYW5kYXRvcnk6ZmFsc2UscmVhZG9ubHk6ZmFsc2Usbm90TnVsbDpmYWxzZSxtaW46LG1heDoscmVnZXhwOixjdXN0b21GaWVsZHM6LGNvbGxhdGU6ImRlZmF1bHQiKSwobmFtZToicGFyYW1ldGVycyIsdHlwZToxMCxtYW5kYXRvcnk6ZmFsc2UscmVhZG9ubHk6ZmFsc2Usbm90TnVsbDpmYWxzZSxtaW46LG1heDoscmVnZXhwOixsaW5rZWRUeXBlOjcsY3VzdG9tRmllbGRzOixjb2xsYXRlOiJkZWZhdWx0IiksKG5hbWU6Imxhbmd1YWdlIix0eXBlOjcsbWFuZGF0b3J5OmZhbHNlLHJlYWRvbmx5OmZhbHNlLG5vdE51bGw6ZmFsc2UsbWluOixtYXg6LHJlZ2V4cDosY3VzdG9tRmllbGRzOixjb2xsYXRlOiJkZWZhdWx0IiksKG5hbWU6ImNvZGUiLHR5cGU6NyxtYW5kYXRvcnk6ZmFsc2UscmVhZG9ubHk6ZmFsc2Usbm90TnVsbDpmYWxzZSxtaW46LG1heDoscmVnZXhwOixjdXN0b21GaWVsZHM6LGNvbGxhdGU6ImRlZmF1bHQiKT4sc3VwZXJDbGFzczosY3VzdG9tRmllbGRzOiksKG5hbWU6Ik9Vc2VyIixzaG9ydE5hbWU6LGRlZmF1bHRDbHVzdGVySWQ6NSxjbHVzdGVySWRzOls1XSxjbHVzdGVyU2VsZWN0aW9uOiJyb3VuZC1yb2JpbiIsb3ZlclNpemU6MC4wZixzdHJpY3RNb2RlOmZhbHNlLGFic3RyYWN0OmZhbHNlLHByb3BlcnRpZXM6PChuYW1lOiJzdGF0dXMiLHR5cGU6NyxtYW5kYXRvcnk6dHJ1ZSxyZWFkb25seTpmYWxzZSxub3ROdWxsOnRydWUsbWluOixtYXg6LHJlZ2V4cDosY3VzdG9tRmllbGRzOixjb2xsYXRlOiJkZWZhdWx0IiksKG5hbWU6InJvbGVzIix0eXBlOjE1LG1hbmRhdG9yeTpmYWxzZSxyZWFkb25seTpmYWxzZSxub3ROdWxsOmZhbHNlLG1pbjosbWF4OixyZWdleHA6LGxpbmtlZENsYXNzOiJPUm9sZSIsY3VzdG9tRmllbGRzOixjb2xsYXRlOiJkZWZhdWx0IiksKG5hbWU6Im5hbWUiLHR5cGU6NyxtYW5kYXRvcnk6dHJ1ZSxyZWFkb25seTpmYWxzZSxub3ROdWxsOnRydWUsbWluOixtYXg6LHJlZ2V4cDosY3VzdG9tRmllbGRzOixjb2xsYXRlOiJjaSIpLChuYW1lOiJwYXNzd29yZCIsdHlwZTo3LG1hbmRhdG9yeTp0cnVlLHJlYWRvbmx5OmZhbHNlLG5vdE51bGw6dHJ1ZSxtaW46LG1heDoscmVnZXhwOixjdXN0b21GaWVsZHM6LGNvbGxhdGU6ImRlZmF1bHQiKT4sc3VwZXJDbGFzczoiT0lkZW50aXR5IixjdXN0b21GaWVsZHM6KSwobmFtZToiT0lkZW50aXR5IixzaG9ydE5hbWU6LGRlZmF1bHRDbHVzdGVySWQ6LTEsY2x1c3RlcklkczpbLTFdLGNsdXN0ZXJTZWxlY3Rpb246InJvdW5kLXJvYmluIixvdmVyU2l6ZTowLjBmLHN0cmljdE1vZGU6ZmFsc2UsYWJzdHJhY3Q6dHJ1ZSxwcm9wZXJ0aWVzOjw+LHN1cGVyQ2xhc3M6LGN1c3RvbUZpZWxkczopLChuYW1lOiJPUmVzdHJpY3RlZCIsc2hvcnROYW1lOixkZWZhdWx0Q2x1c3RlcklkOi0xLGNsdXN0ZXJJZHM6Wy0xXSxjbHVzdGVyU2VsZWN0aW9uOiJyb3VuZC1yb2JpbiIsb3ZlclNpemU6MC4wZixzdHJpY3RNb2RlOmZhbHNlLGFic3RyYWN0OnRydWUscHJvcGVydGllczo8KG5hbWU6Il9hbGxvd1JlYWQiLHR5cGU6MTUsbWFuZGF0b3J5OmZhbHNlLHJlYWRvbmx5OmZhbHNlLG5vdE51bGw6ZmFsc2UsbWluOixtYXg6LHJlZ2V4cDosbGlua2VkQ2xhc3M6Ik9JZGVudGl0eSIsY3VzdG9tRmllbGRzOixjb2xsYXRlOiJkZWZhdWx0IiksKG5hbWU6Il9hbGxvd1VwZGF0ZSIsdHlwZToxNSxtYW5kYXRvcnk6ZmFsc2UscmVhZG9ubHk6ZmFsc2Usbm90TnVsbDpmYWxzZSxtaW46LG1heDoscmVnZXhwOixsaW5rZWRDbGFzczoiT0lkZW50aXR5IixjdXN0b21GaWVsZHM6LGNvbGxhdGU6ImRlZmF1bHQiKSwobmFtZToiX2FsbG93RGVsZXRlIix0eXBlOjE1LG1hbmRhdG9yeTpmYWxzZSxyZWFkb25seTpmYWxzZSxub3ROdWxsOmZhbHNlLG1pbjosbWF4OixyZWdleHA6LGxpbmtlZENsYXNzOiJPSWRlbnRpdHkiLGN1c3RvbUZpZWxkczosY29sbGF0ZToiZGVmYXVsdCIpLChuYW1lOiJfYWxsb3ciLHR5cGU6MTUsbWFuZGF0b3J5OmZhbHNlLHJlYWRvbmx5OmZhbHNlLG5vdE51bGw6ZmFsc2UsbWluOixtYXg6LHJlZ2V4cDosbGlua2VkQ2xhc3M6Ik9JZGVudGl0eSIsY3VzdG9tRmllbGRzOixjb2xsYXRlOiJkZWZhdWx0Iik+LHN1cGVyQ2xhc3M6LGN1c3RvbUZpZWxkczopPg== send this data for debugging
Exception in thread "main" com.orientechnologies.common.exception.OException: Error on creation of shared resource
	at com.orientechnologies.common.concur.resource.OSharedContainerImpl.getResource(OSharedContainerImpl.java:59)
	at com.orientechnologies.orient.client.remote.OStorageRemoteThread.getResource(OStorageRemoteThread.java:643)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault.init(OMetadataDefault.java:176)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault.load(OMetadataDefault.java:78)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.initAtFirstOpen(ODatabaseDocumentTx.java:2497)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:249)
	at com.orientechnologies.orient.core.db.ODatabaseWrapperAbstract.open(ODatabaseWrapperAbstract.java:55)
	at com.orientechnologies.orient.object.db.OObjectDatabaseTx.open(OObjectDatabaseTx.java:123)
	at Test.main(Test.java:6)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 115
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.fromStream(ORecordSerializerBinary.java:70)
	at com.orientechnologies.orient.core.record.impl.ODocument.deserializeFields(ODocument.java:1699)
	at com.orientechnologies.orient.core.record.impl.ODocument.checkForFields(ODocument.java:2087)
	at com.orientechnologies.orient.core.record.impl.ODocument.rawField(ODocument.java:820)
	at com.orientechnologies.orient.core.record.impl.ODocument.field(ODocument.java:840)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.fromStream(OSchemaShared.java:573)
	at com.orientechnologies.orient.core.type.ODocumentWrapperNoClass.reload(ODocumentWrapperNoClass.java:74)
	at com.orientechnologies.orient.core.metadata.schema.OSchemaShared.load(OSchemaShared.java:732)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault$1.call(OMetadataDefault.java:181)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault$1.call(OMetadataDefault.java:176)
	at com.orientechnologies.common.concur.resource.OSharedContainerImpl.getResource(OSharedContainerImpl.java:57)
	... 8 more
```

**Comment by stawny** [comment] 2015-01-02 15:54
Hi @tglman, I am using orientdb-community-1.7.10.

**Comment by maboalim** [comment] 2015-01-02 16:14
I am getting the same exception while opening the DB. I am using orientdb-community-1.7.10 , centos 6.5 and java version 1.7.0_72
 my code is 
OObjectDatabaseTx db = new OObjectDatabaseTx ("remote:" + dbIP + "/" + dbSchema);
		db.open(dbUserName, dbPassword);

and I got the same exception

     INFO: Auto-config DISKCACHE=968MB (heap=864MB osMemory=3,880MB)
     Jan 02, 2015 8:06:17 PM com.orientechnologies.common.log.OLogManager log
     WARNING: The Client driver version is different than Server version: client=26, server=21. You could not use the full features of the newer version. Assure to have the same versions on both
     Jan 02, 2015 8:06:17 PM com.orientechnologies.common.log.OLogManager log
     WARNING: Error deserializing record      c2NoZW1hVmVy.......6KT4= send this data for debugging
     com.orientechnologies.common.exception.OException: Error on creation of shared resource
	at      com.orientechnologies.common.concur.resource.OSharedContainerImpl.getResource(OSharedContainerImpl.java:59)
	at      com.orientechnologies.orient.client.remote.OStorageRemoteThread.getResource(OStorageRemoteThread.java:643)
	at      com.orientechnologies.orient.core.metadata.OMetadataDefault.init(OMetadataDefault.java:176)
	at com.orientechnologies.orient.core.metadata.OMetadataDefault.load(OMetadataDefault.java:78)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.initAtFirstOpen(ODatabaseDocumentTx.java:2497)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:249)
	at com.orientechnologies.orient.core.db.ODatabaseWrapperAbstract.open(ODatabaseWrapperAbstract.java:55)
	at com.orientechnologies.orient.object.db.OObjectDatabaseTx.open(OObjectDatabaseTx.java:123)
     ......
     ......
     ......
     at      org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:215)
	at      org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132)
	at      org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
	at      org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:749)
	at      org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:689)
	at      org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:83)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:938)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:870)
	at      org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:961)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:852)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:618)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:837)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at      org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at      org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at      org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:537)
	at      org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1085)
	at      org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:658)
	at           org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:222)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1556)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1513)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
     Caused by: java.lang.ArrayIndexOutOfBoundsException: 115

**Comment by tglman** [comment] 2015-01-02 17:32
hi @stawny 

if you are learning I'll suggest to you to start with the rc-1 http://www.orientechnologies.com/download/ also in the server side, the final will be released in few days.

for the current issue is due to the fact that you are doing a connection from a 2.0 client to a 1.7 server, a quick workaround to make this work is set:
`OGlobalConfiguration.DB_DOCUMENT_SERIALIZER.setValue(ORecordSerializerSchemaAware2CSV.NAME);` before get the database.

this will be fixed anyway for 2.0 final

**Comment by maboalim** [comment] 2015-01-02 17:54
Hi @tglman,

It works with me now after adding this line. I hope it will works also with @tglman  who report this issue.

Thanks

**Comment by tglman** [comment] 2015-01-02 18:05
added also the code fix, closing this.

**Closed by tglman** 2015-01-02 18:05 UTC
Labels: bug
