### ISSUE TITLE
Performance impact during simultaneous read and writes

### ISSUE THREAD

**Issue by Ashendra** [orientechnologies/orientdb#5807] opened 2016-03-08 04:26 UTC
Hi,

Orientdb version - 2.1.5 

With only read operations, qps achieved was 40k. But when the writes were performed parallel, the performance dropped to 15k. Write qps was 1k, and are new vertices/edges.

Is this expected behaviour?. I am evaluating orientdb for production, if this is the expected behaviour, I might have to look for other options.

**Comment by smolinari** [comment] 2016-03-08 06:46
Hi Ashendra,

If you are trying out ODB, you really should try out the newest version. 2.1.5 is quite old. 2.1.12 is the current version. The ODB team are constantly making improvements, so it is definitely worth going the the most up-to-date version, when testing.

You might also think about testing 2.2.0, which is in BETA currently, but should be released as GA fairly soon. There have been some noticeable performance improvements made in 2.2 and you might be happier with the test results. I'd be very interested in what you find too.

Scott

**Comment by smolinari** [comment] 2016-03-08 06:48
Oh, and when you ask such questions, it would be helpful for the team, when you explain your testing scenario a bit more in detail. :smile: 

Scott

**Comment by luigidellaquila** [comment] 2016-03-08 16:39
Hi @Ashendra 

Could you please share some details on:
- how are you connecting (remote/plocal)
- which driver (java?)
- your domain model
- indexes
- type of queries you do
- transactions enabled?

Thanks

Luigi

**Comment by Ashendra** [comment] 2016-03-08 17:05
Connecting through remote
Using java driver
Graph domain model
3 Vertices Class, 2 Edge Class, 1 index per Class
Query Type - 
Read - getEdges one level
Write - Add/delete edges
Transaction enabled

Orientdb Server Machine - 64 Gb Ram, 20 core, Intel(R) Xeon(R) CPU E5-2690 v2 @ 3.00GHz
Server config
-Dstorage.diskCache.bufferSize=40960
-Xms8g
-Dindex.embeddedToSbtreeBonsaiThreshold=-1
-DridBag.embeddedToSbtreeBonsaiThreshold=-1

<parameter value="100" name="graph.pool.max"/>

<properties>
        <entry value="100" name="db.pool.max"/>
        <entry value="false" name="profiler.enabled"/>
        <entry value="100" name="client.channel.maxPool"/>
        <entry value="100" name="script.pool.maxSize"/>
    </properties>

Let me know if any other details are required.

**Comment by zella** [comment] 2016-06-17 12:00
I also have same problem. When i do heavy query like `select count(*) from MyUser where random = 100` (no index) my parallel inserts dropped from ~20000/sec to ~20/sec. (remote - default config, 8gb ram laptop, inserts in java api, reads in studio)

**Comment by lvca** [comment] 2016-06-19 12:19
I think the cause is the scan executed by the SELECT: in order to be more efficient it acquire longer locks that could impact your case. Can you try setting this property on the server (the default was 100k)?

`-Dquery.scanBatchSize=100`

**Comment by zella** [comment] 2016-06-20 07:29
@lvca Ok, with `-Dquery.scanBatchSize=100` parallel write perfomance increased from 20 to 3500 /sec. I also measure my select time and it's stays same with and without parameter ~45 sec

**Comment by lvca** [comment] 2016-06-20 12:33
Ok, maybe we should decrease the default value in further releases. Thanks.

**Closed by lvca** 2016-06-20 12:33 UTC
Labels: question, storage team, waiting reply
