### ISSUE TITLE
Error Creating Edges in Server Side Function Transaction

### ISSUE THREAD

**Issue by misamanjarres** [orientechnologies/orientdb#7219] opened 2017-03-08 01:57 UTC
## Expected behavior  
Create edge to vertex created within a server side javascript transaction

## Actual behavior  
Fails with error: No edge has been created because no target vertices

## Steps to reproduce  
```
var db = orient.getGraph();

try{
db.command('sql', "CREATE VERTEX Post CLUSTER cluster1 SET title = ?, text= ?, posterId = ?, timestamp= sysdate()", [title,text,posterId]);

db.command('sql', "CREATE EDGE Posted FROM "+posterId+" TO (SELECT FROM cluster:cluster1 WHERE title = ? and text = ?) SET timestamp = sysdate()",[title,text]);
 

} catch(err){
 db.rollback();
 return(err.toString())
}
```

When I first create the vertices in a separate query and then create the edges it works, but it does not work within one transaction. This error started when I upgraded to version 2.2.15. I was using the same function with prior versions and never had a problem. I reverted to 2.2.0 and the function works again.

**Comment by luigidellaquila** [comment] 2017-03-08 12:21
Hi @misamanjarres

I tried to reproduce this problem on latest stable, but with no success.
What parameters are you passing to the function? How are you invoking it?

Thanks

Luigi

**Comment by misamanjarres** [comment] 2017-03-08 17:05
In my context, the function is a user creating a review for a specific item. First the review vertex is created in POST class in a specific cluster. Then an edge is created from the user to the newly created review vertex. The user vertex already exists in a USER class. The parameters are string parameters like 'text' and 'title' along with the rid that identifies the user vertex.

I am calling it via a POST rest call. It doesn't work there. It also fails when trying to execute it via the studio. Last night I tried upgrading to 2.2.17 and the problem persisted. It was solved when I downgraded to 2.2.0.

**Comment by luigidellaquila** [comment] 2017-03-09 08:57
Hi @misamanjarres 

I did this:

```


CREATE CLASS TestScriptPerson extends V
CREATE CLASS TestScriptVertex extends V
CREATE CLASS TestScriptEdge extends E

insert into TestScriptPerson set name ='Luigi'

//result #73:1
```
Then I created a function as follows:

```
var db = orient.getGraph();

try{
db.command('sql', "CREATE VERTEX TestScriptVertex cluster testscriptvertex SET title = ?, text= ?, posterId = ?, timestamp= sysdate()", [title,text,posterId]);

db.command('sql', "CREATE EDGE TestScriptEdge FROM "+posterId+" TO (SELECT FROM cluster:testscriptvertex WHERE title = ? and text = ?) SET timestamp = sysdate()",[title,text]);

} catch(err){
  err.printStackTrace();
 db.rollback();
 return(err.toString())
}
```

I launched it in Studio, on latest stable version, and it works fine.

Am I missing something?

Thanks

Luigi

**Comment by luigidellaquila** [comment] 2017-09-27 09:59
No answer for a long time, I'm closing this issue as we cannot reproduce it.
Please @misamanjarres feel free to reopen if you have any additional info

Thanks

Luigi

**Closed by luigidellaquila** 2017-09-27 09:59 UTC
Labels: cannot replicate, waiting reply
