### ISSUE TITLE
com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.ONestedRollbackException: Atomic operation was rolled back by internal component, exception which caused this rollback is : java.lang.NullPointerException

### ISSUE THREAD

**Issue by KishoDai** [orientechnologies/orientdb#7745] opened 2017-09-15 09:24 UTC
## Expected behavior  
Can create edge

## Actual behavior  
$ANSI{green {db=sns}} Exception `6EC9E64A` in storage `sns`
com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.ONestedRollbackException: Atomic operation was rolled back by internal component, exception which caused this rollback is :
java.lang.NullPointerException

	DB name="sns"
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.endAtomicOperation(OAtomicOperationsManager.java:457)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.endStorageTx(OAbstractPaginatedStorage.java:3655)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1690)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:541)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:99)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2891)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2860)
	at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.commit(OrientTransactionalGraph.java:182)
	at com.orientechnologies.orient.graph.sql.OGraphCommandExecutorSQLFactory.runInConfiguredTxMode(OGraphCommandExecutorSQLFactory.java:265)
	at com.orientechnologies.orient.graph.sql.OCommandExecutorSQLCreateEdge.execute(OCommandExecutorSQLCreateEdge.java:143)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:74)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:3200)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:3138)
	at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1518)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:642)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:380)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:203)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)

## Steps to reproduce  
<add here>

**Comment by laa** [comment] 2017-09-15 10:32
@KishoDai could you send full stack-trace? I need to see the cause of NPE.

**Comment by laa** [comment] 2017-09-18 11:13
Hi @KishoDai could you send full stack trace?

**Comment by KishoDai** [comment] 2017-09-19 04:36
hi @laa 
    That's the full stack.

**Comment by laa** [comment] 2017-09-19 05:51
@KishoDai it means that is not the first exception in this then, JVM optimize handling of exceptions if that is not the first exception in the log by cutting stack trace, do you have any similar exceptions in the log above?

**Comment by KishoDai** [comment] 2017-09-19 07:05
Hi @laa 
    That's what I can collect.

**Comment by laa** [comment] 2017-09-19 07:32
@KishoDai could you add the following setting to the server.sh "-XX:-OmitStackTraceInFastThrow" it should fix the problem of the removed stack trace. but probably it is the same problem as with ones with distributed which you have seen before, or that was on the standalone server?

**Comment by laa** [comment] 2017-09-22 13:46
@KishoDai could you repeat this issue as I wrote you above?

**Comment by KishoDai** [comment] 2017-09-25 09:24
@laa 
    I will add it. But recently it have no the error stack trace.
    Thank you.

**Comment by laa** [comment] 2017-09-25 09:36
@KishoDai still not bad, let's monitor then the state of the server for a month. If the exception is gone, we will close the issue. I will keep it open for now.

**Comment by KishoDai** [comment] 2017-09-25 09:59
Hi @laa 
      OK. Thank you.

**Comment by laa** [comment] 2017-10-28 08:03
Close the issue because no reports about its presence were done.

**Closed by laa** 2017-10-28 08:03 UTC
Labels: analyzing, reproducing, storage team
