### ISSUE TITLE
Inline fetchplan has no effect on binary protocol

### ISSUE THREAD

**Issue by phpnode** [orientechnologies/orientdb#3515] opened 2015-02-02 23:38 UTC
Sending a query like `SELECT * FROM OUser FETCHPLAN *:2`, the fetchplan has no effect. digging a little deeper, I see [this](https://github.com/orientechnologies/orientdb/wiki/Network-Binary-Protocol-Commands#sql-select-query): 

> **fetch-plan** used only for select queries, otherwise empty

Since I'm sending the fetchplan in the query, rather than separately, I'm sending `null` (or an empty string `""`) here, guessing that Orient is seeing that value and overriding the fetchplan in the query. This is nasty because it means that a query executed in the console or studio doesn't work in Oriento.

**Comment by AhtashamImtiyaz** [comment] 2015-02-04 15:56
```
select from (SELECT EXPAND( $c ) LET $a = ( SELECT expand( out('eat')  ) from #13:0 ), $b = ( select expand( out('Follow').out('eat')  ) from #13:1 ), $c = UNIONALL( $a, $b )) fetchPlan in_eat:2
```

This query isn't working (in binary protocol) either. I want to get all the restaurant where #13:1 and people #13:1 'follows' eat. It works but i also want the names of the people as well so using fetchplan. It works in studio but not working in binary protocol.

**Comment by StarpTech** [comment] 2015-05-12 20:28
How is the status?

**Comment by tglman** [comment] 2015-05-13 10:04
hi, i was not able to reproduce this.

if you can provide a test case, will be much easier to get it fixed :)

**Comment by phpnode** [comment] 2015-05-13 10:29
@tglman in oriento this should do it:
```js
db.query("SELECT FROM OUser FETCHPLAN roles:1").then(console.log);
```

**Comment by tglman** [comment] 2017-12-29 13:35
Hi,

We refactored the query engine in 3.0 deprecating the fetch plan and providing a new way to do this query, fully supported by the binary protocol, closing this.

Regards

**Closed by tglman** 2017-12-29 13:35 UTC
Labels: bug
