### ISSUE TITLE
User or password not valid for database with Admin role

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientdb#4599] opened 2015-07-17 17:28 UTC
Orientdb 2.0.12

```
Connecting to database [plocal:../databases/bodyclub24_prod] with user 'bc24'...
2015-07-17 19:24:37:761 WARNING {db=bc24_test} segment file 'database.ocf' was not closed correctly last time [OSingleFileSegment]
2015-07-17 19:24:37:820 WARNING {db=bc24_test} Storage bodyclub24_prod was not closed properly. Will try to restore from write ahead log. [OL                                                                  ocalPaginatedStorage]
2015-07-17 19:24:37:907 WARNING {db=bc24_test} Record com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OCheckpointEndRecord                                                                  {lsn=OLogSequenceNumber{segment=0, position=352679}} will be skipped during data restore. [OLocalPaginatedStorage]
2015-07-17 19:24:37:908 WARNING {db=bc24_test} Non tx operation was used during data modification we will need index rebuild. [OLocalPaginate                                                                  dStorage]
2015-07-17 19:24:38:127 SEVERE {db=bc24_test}  [OIndexDictionary]
Error: com.orientechnologies.orient.core.exception.OSecurityAccessException: User or password not valid for database: 'bc24_test'

```

Steps:
1. Create database and user `bc24` with admin, read, write rights
2. Shutdown database with `./orientdb.sh stop`
3. Log into console.sh and try to connect to plocal storage `connect plocal:../databases/bc24_test bc24 XXXXXXXX
   `

**Doesn`t occurs in Orientdb 2.0.10**

**Comment by StarpTech** [comment] 2015-07-18 01:05
please help, I would like to upgrade to 2.0.12.

**Comment by nagarajasr** [comment] 2015-07-18 08:06
Unable to reproduce it with the steps given:

```sql
$ ./bin/console.sh

OrientDB console v.2.0.12 (build UNKNOWN@r; 2015-07-18 07:31:23+0000) www.orientechnologies.com
Type 'help' to display all the supported commands.
2015-07-18 13:25:47:674 WARNING Not enough physical memory available for DISKCACHE: 1,542MB (heap=494MB). Set lower Maximum Heap (-Xmx setting on JVM) and restart OrientDB. Now running with DISKCACHE=256MB [orientechnologies]
Installing extensions for GREMLIN language v.2.6.0

orientdb> connect plocal:../databases/bc24_test bc24 bc24

Connecting to database [plocal:../databases/bc24_test] with user 'bc24'...OK

orientdb {db=bc24_test}>
```

however when i try to login using root user, i am getting the same exception reported:

```sql
orientdb> connect plocal:../databases/bc24_test root rootpw

Connecting to database [plocal:../databases/bc24_test] with user 'root'...
2015-07-18 13:32:51:273 WARNING {db=bc24_test} segment file 'database.ocf' was not closed correctly last time [OSingleFileSegment]
Error: com.orientechnologies.orient.core.exception.OSecurityAccessException: User or password not valid for database: 'bc24_test'

```

**Comment by StarpTech** [comment] 2015-07-18 10:56
Hi @nagarajasr do you create the user in the studio?

**Comment by nagarajasr** [comment] 2015-07-18 10:57
yes, in studio.

**Comment by StarpTech** [comment] 2015-07-18 11:01
mmh I will test it again.

**Comment by lvca** [comment] 2015-07-20 19:09
Is this issue still valid?

**Comment by StarpTech** [comment] 2015-07-20 19:19
sry currently no time for testing. I will check it during this week.

**Comment by btym** [comment] 2015-10-16 22:37
@lvca: This issue still exists in 2.1.4 for root user:
```
orientdb> connect plocal:../databases/test_export root admin

Connecting to database [plocal:../databases/test_export] with user 'root'...
Error: com.orientechnologies.orient.core.exception.OSecurityAccessException: User or password not valid for database: 'test_export'
```
Can connect with `remote:` and with studio.

**Comment by AndreaPravato** [comment] 2015-10-26 16:56
+1 This issue still exists in 2.1.4 for root user

**Comment by AndreaPravato** [comment] 2015-10-26 17:05
+1 This issue still exists in 2.1.4 for root user

**Comment by MathildeLemee** [comment] 2015-12-11 09:50
in 2.1.6 too ...

**Comment by luigidellaquila** [comment] 2015-12-11 10:17
Hi all,

I think it's a structural problem: database level users like "admin" are stored in the database itself, so when you connect to a database you can just check them.

On the other hand, root user is stored in the ```orientdb-server-config.xml``` file, inside the /config dir.

Now consider this scenario: you have two different OrientDB instances
```
/instance1/orientdb
/instance2/orientdb
```

if you run 
```
/instance1/orientdb/bin/consile.sh

orientdb> connect plocal:/instance2/orientdb/databases/foo root rootPwd
```

should the console check for the root password in
```
/instance1/orientdb/config/orientdb-server-config.xml
```
or in 
```
/instance2/orientdb/config/orientdb-server-config.xml
```
?

Currently it does neither, this is why it doesn't work.

It is a purely conceptual problem, so any comments are welcome

Thanks

Luigi

**Comment by mamoit** [comment] 2016-04-27 13:48
:+1: same problem with the root user.

**Comment by larryaasen** [comment] 2016-09-10 14:52
+1 I have the same problem with root user. Is there a recommendation on how to get around this?

**Comment by lvca** [comment] 2016-09-10 18:31
Have you guys (@mamoit and @larryaasen) resolved by following the luigi's comment?

**Comment by nagarajasr** [comment] 2016-09-11 14:32
@lvca we can hardly expect a resolution from @luigidellaquila comment, as he himself seems to be asking a fundamental question how server authentication should work. 

@luigidellaquila how about user having to explicitly specify which server-config.xml to use to connect to a DB (used only for opening DB in plocal mode), rather than console client trying to resolve the server-config.xml automatically (with potentially unpredictable results)

**Comment by larryaasen** [comment] 2016-09-11 16:58
I do not have a recommendation for solving this problem. Instead, I used plocal during the connection and used admin/admin which I did not realize was already setup.

**Comment by lvca** [comment] 2017-01-30 21:50
Some of the operations require a server user, like "create database". So a server user has to be provided for such operations. For all the rest, the database's user is ok. By the way, with 2.2 we hashed+salt password of server's users too.

**Closed by lvca** 2017-01-30 21:50 UTC
Labels: waiting reply

**Comment by Shubham-gupta26** [comment] 2017-07-14 10:33
Solved the issue.
enter username and password as "admin" and "admin"
