### ISSUE TITLE
OrientDB documentation is wrong on ETL "dateFormat" field for CSV Extractors

### ISSUE THREAD

**Issue by william76** [orientechnologies/orientdb#6580] opened 2016-08-17 16:43 UTC
## OrientDB Version, operating system, or hardware.
- [X] v2.2.7 community

## Operating System
- [ ] Linux
- [X] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name?

## Expected behavior and actual behavior
The example under the CSV extractors in the [ETL documentation](http://orientdb.com/docs/2.2.x/Extractor.html) is incorrect.  The example   as shown is:

```
{ "csv":
    {  "predefinedFormat": "DEFAULT",
       "nullValue" : "N/A",
       "dateFormat" : "dd-mm-yyyy HH:MM"
    }
}
```

The results of using this will be incorrect.

I have a sample file, **vertices.csv**:

```
label,data,Date
v01,0.1234,2015-01-01 02:30
v02,0.5678,2015-02-20 15:32
v03,0.9012,2015-03-30 11:00
```

but if I follow the format shown in the example in the OrientDB documentation:

```
"extractor": { "csv": { "ignoreEmptyLines": true,
                        "nullValue": "N/A",
                        "columnsOnFirstLine": true,
                        "dateFormat": "yyyy-hh-dd HH:MM"
                      }
             },
```

the resulting fields in the databse will be:

```
orientdb {db=test.orientdb}> SELECT FROM myVertex

+----+-----+--------+------+-------------------+-----+
|#   |@RID |@CLASS  |data  |Date               |label|
+----+-----+--------+------+-------------------+-----+
|0   |#25:0|myVertex|0.1234|2017-06-01 02:00:00|v01  |
|1   |#26:0|myVertex|0.5678|2017-08-20 15:00:00|v02  |
|2   |#27:0|myVertex|0.9012|2014-12-30 11:00:00|v03  |
+----+-----+--------+------+-------------------+-----+
```

which has incorrect dates/time fields.

### Contents of the attached ZIP archive

I have provided a ZIP file containing a sample dataset with scripts to load it with OETL.
The zip file has the following files:

* **00_build_graph.sh** - script to build the graph using the bad dateFormat string.
* **00_build_graph_correct.sh** - script which builds the graph with the corrected dateFormat string.
* **01_query_graph.sh** - script to query the graph and display the vertices.
* **commonVertices-bad-dateFormat.json** - ETL JSON file containing a bad dateFormat string corresponding to the [current                    documentation](http://orientdb.com/docs/2.2.x/Extractor.html).
* **commonVertices-correct.json** - A corrected ETL JSON file using the dateFormat "yyyy-MM-dd hh:mm".
* **vertices.csv** - input data for vertices.
* **vertices.json** - ETL JSON input file for oetl.sh

### Running the test:

1) Download and unzip the OrientDB-Community 2.2.7 archive.
2) Set your $ORIENTDB_HOME directory to the bin directory in the lcoation you unzipped OrientDB in (1).
3) Download and extract the zip file attached to this bug report.
4) Run the 00_build script to construct the graph, then the 01_query script to print out the vertices.
5) Note the incorrect result.

### Result of executing the test

```
orientdb {db=test.orientdb}> SELECT FROM myVertex

+----+-----+--------+------+-------------------+-----+
|#   |@RID |@CLASS  |data  |Date               |label|
+----+-----+--------+------+-------------------+-----+
|0   |#25:0|myVertex|0.1234|2017-06-01 02:00:00|v01  |
|1   |#26:0|myVertex|0.5678|2017-08-20 15:00:00|v02  |
|2   |#27:0|myVertex|0.9012|2014-12-30 11:00:00|v03  |
+----+-----+--------+------+-------------------+-----+

3 item(s) found. Query executed in 0.004 sec(s).
```

Note the dates are inconsistent with the input data in vertices.csv;

```
label,data,Date
v01,0.1234,2015-01-01 02:30
v02,0.5678,2015-02-20 15:32
v03,0.9012,2015-03-30 11:00
```

### Troubleshooting

If oetl.sh doesn't work when you run it because it can't find the CSV or JSON input files, I've found that commenting out the following line from oetl.sh fixes the problem:

```
#set current working directory
cd `dirname $0`
```

I can't speak to all environments, but for me it's an annoying side-effect of this script changing the working directory into $ORIENTDB_HOME/bin when you run it that would force me to run oetl.sh using absolute paths when I'm *running oetl from the directory that contains my JSON  file*.

## Example Test Case File

[bug-ETL-Extractor-csv-dateFormat.zip](https://github.com/orientechnologies/orientdb/files/423059/bug-ETL-Extractor-csv-dateFormat.zip)

**Comment by robfrank** [comment] 2016-08-19 11:34
duplicate of #6581

**Closed by robfrank** 2016-08-19 11:34 UTC
Labels: duplicate
