### ISSUE TITLE
OrientJs + JavaScript server functions using 'orient' crash - 2.1.1

### ISSUE THREAD

**Issue by MVdev1** [orientechnologies/orientdb#4947] opened 2015-09-09 21:51 UTC
I'm trying to call a server function written in JavaScript and it doesn't work if that function uses the database (i.e. uses the 'orient' object).

*Is this a bug or am I calling it incorrectly?  v.2.1.1*

+ I can run the function from the studio function designer [it works]
+ I can call it from studio browse -- e.g. SELECT TestFunction()  [it works]
+ I can test passing parameters and call a simple server function from Node/JavaScript via OrientJs driver [it works]

But when I try to call a server function that uses 'orient' and some database functionality then I'm out of luck.

e.g.

On the server I have this function...

**function name: testfunction - javascript with no parameters**

       var g = orient.getGraph();
       var results = g.command("sql", "SELECT FROM OUser");
       return results;

And I call it like this...

    var server = OrientDB({host: 'localhost', port: 2424, username: 'admin', password: 'admin'});
    var db = server.use({name: 'TestDb', username: 'admin', password: 'admin'});
    db.exec("SELECT testfunction()", {params: {}})
       .then(function (results)
       {
          console.log("Results = " + JSON.stringify(results));
         .......

And I see these errors in the log...

	2015-09-10 00:33:47:730 INFO  OrientDB Server v2.1.1 (build UNKNOWN@r${buildNumber}; 2015-08-31 18:08:38+0000) is active. [OServer]{db=TestDb} Error on unmarshal
	ling record #-2:1 (java.lang.ClassCastException: com.tinkerpop.blueprints.impls.orient.OrientVertex cannot be cast to com.orientechnologies.orient.core.record.O
	Record)
	java.lang.ClassCastException: com.tinkerpop.blueprints.impls.orient.OrientVertex cannot be cast to com.orientechnologies.orient.core.record.ORecord
			at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerStringAbstract.fieldTypeToString(ORecordSerializerStringAbs
	tract.java:197)
			at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerCSVAbstract.embeddedCollectionToStream(ORecordSerializerCSV
	Abstract.java:843)
			at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerCSVAbstract.fieldToStream(ORecordSerializerCSVAbstract.java
	:534)
			at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerSchemaAware2CSV.toString(ORecordSerializerSchemaAware2CSV.j
	ava:506)
			at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerStringAbstract.toStream(ORecordSerializerStringAbstract.jav
	a:689)
			at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerSchemaAware2CSV.toStream(ORecordSerializerSchemaAware2CSV.j
	ava:268)
			at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2282)
			at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:671)
			at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.getRecordBytes(OBinaryNetworkProtocolAbstract.java:424)
			at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.writeRecord(OBinaryNetworkProtocolAbstract.java:443)
			at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.writeIdentifiable(OBinaryNetworkProtocolAbstract.java:141)
			at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.serializeValue(ONetworkProtocolBinary.java:1389)
			at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1337)
			at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:396)
			at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:223)
			at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)

	2015-09-10 00:34:14:152 WARNI {db=TestDb} Cannot serialize record: #-2:1{testfunction:[4]} v0 [ONetworkProtocolBinary]

**Comment by MVdev1** [comment] 2015-09-09 22:04
PS  The SQL version doesn't return exactly what I would expect but there are no errors.

SQL Function...

       SELECT * FROM OUser;

Results in Node/JavaScript:

   Results = {"status":{"code":0,"sessionId":3},"results":[{"type":"l","content":[{"classId":0,"type":"d","cluster":-2,"position":1,"version":0,"value":{"@type":"d","testfunctionsql":["#5:0","#5:1","#5:2","#5:3"]}}]}]}

Results in studio...

	[
		{
			"@type": "d",
			"@rid": "#5:0",
			"@version": 2,
			"@class": "OUser",
			"name": "admin",
			"password": "{SHA-256}AA6C00A14B7C8EC82F1849F51DC96EA55504E1F55E793C6840107848B6724EC2",
			"status": "ACTIVE",
			"roles": [
				"#4:0"
			],
			"@fieldTypes": "roles=n"
		},
		{
			"@type": "d",
			"@rid": "#5:1",
			"@version": 1,
			"@class": "OUser",
			"name": "reader",
			"password": "{SHA-256}AA6C00A14B7C8EC82F1849F51DC96EA55504E1F55E793C6840107848B6724EC2",
			"status": "ACTIVE",
			"roles": [
				"#4:1"
			],
			"@fieldTypes": "roles=n"
		},
		...

PSS My function (the one where I first discovered this problem) returns explicitly listed parameters.

**Comment by tommykennedy** [comment] 2015-10-21 19:32
+1 

This fails on the return of the output of select command

**Comment by digitalacorn** [comment] 2015-12-24 08:49
+1 from me. Using the REST interface returns correctly, but the response in NodeJS is as above. This seem to indicate that the problem is in the Node driver.

**Comment by tglman** [comment] 2016-06-06 11:55
Hi,

I fixed that issue in 2.2 some time ago: https://github.com/orientechnologies/orientdb/commit/e2d98a6c7fbd747446c2df1bf8b3d5616573ad32, just ported the fix in 2.1 as well, closing this.

will be out with 2.1.20

**Closed by tglman** 2016-06-06 11:55 UTC
Labels: bug
