### ISSUE TITLE
Perpetual wait on a reentrant lock while loading from cache

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#6797] opened 2016-10-11 06:32 UTC
## OrientDB Version, operating system, or hardware.
- v2.2.9 - v2.2.11
## Operating System
- [X] Windows Server 2012 R2 (64 bit)
## Hardware

16GB, 4 CPU core. Running in a VMWare virtualized environment.
## Java

Java 8 with heap size set to 6GB. 
## Expected behavior and actual behavior

In our server, Orient DB v2.2.9 - v2.2.11 stops functioning when the database gets to a certain size. There are long pauses in Orient DB calls to perform simple operations like retrieve a value from a vertex. After restarting the database, it works for a short while and then get back into a mode whereby the database freezes again.

The value **-XX:MaxDirectMemorySize=512g**  is set when this error occurs. 

Expected behaviour: We expect that Orient will continue to do useful work.
## Steps to reproduce the problem

This issue is occurring in two production systems and is reproducible by restarting the server using a specific Orient DB database (already provided to Andrey). To the untrained eye, it looks like some kind of caching logic issue. To guard against OME problems we experienced when we moved to v2.2, we limit the size of the cache as follows on startup:

```
long maxDirectMemoryBytes = sun.misc.VM.maxDirectMemory();
long directHintMB = maxDirectMemoryBytes / 1024 / 1024;
long maxMemoryBytes = Runtime.getRuntime().maxMemory();
long maxMemoryHintMB = maxMemoryBytes / 1024 / 1024;
long bufferSizeMB = Math.min(directHintMB, maxMemoryHintMB);
System.setProperty("storage.diskCache.bufferSize", String.valueOf(bufferSizeMB));
```

The cache size ends up being several GB in size, so it shouldn't be an issue that the server would stop working. If we didn't specify the storage.diskCache.bufferSize value, the server would simply OME after some time. Setting **storage.diskCache.bufferSize** to **2GB** doesn't help either.

![chart](https://cloud.githubusercontent.com/assets/6212848/19260924/f819afac-8f8d-11e6-995a-f19c933137c4.png)

If we start from an empty database, Orient DB seems to work fine. When the database grows in size, it gets to a point where the behaviour is observed. 

Access to the Yourkit snapshot and Orient DB database has been provided offline to Andrey.

**Comment by jamieb22** [comment] 2016-10-11 06:34
In our server, Orient DB v2.2.9 - v2.2.11 stops functioning when the database gets to a certain size. There are long pauses in Orient DB calls to perform simple operations like retrieve a value from a vertex. After restarting the database, it works for a short while and then get back into a mode whereby the database freezes again. It seems it does still operate, but slows down to a point where the system is unusable. Incidentally, the value -XX:MaxDirectMemorySize=512g was set when this error occurred. I've also tried setting storage.diskCache.bufferSize to 2GB, but it doesn't resolve the issue.

**Comment by laa** [comment] 2016-10-11 07:30
@jamieb22 could you send full thread dump ? We will start to fix this issue right now but we need full thread dump

**Comment by laa** [comment] 2016-10-11 07:34
@jamieb22 I think I know how to solve your issue could you set property query.scanBatchSize=1 and property query.scanThresholdTip=1 if that will not fix an issue I am working on new locking model right now which minimize scope of provided lock dramatically and as result allows to avoid pauses in execution. I will need 2 weeks to finish it. But I suppose those settings will solve issue too.

**Comment by jamieb22** [comment] 2016-10-11 08:06
What do these settings do? What are the side effects of setting query.scanBatchSize=1? I sent you the Yourkit. Can't you just fix the current locking engine, instead of yet another rewrite, and another set of critical bugs?

**Comment by laa** [comment] 2016-10-11 08:12
@jamieb22  all those settings means that each record will be wrapped in single lock instead of several records which reduce contention and obviously pauses during locks. But as side effect, it decreases average speed of queries which are executed without index.

**Comment by jamieb22** [comment] 2016-10-11 08:14
Did you connect to the VNC session and examine the Yourkit snapshot? Were you able to identify the underlying cause of the problem?

**Comment by laa** [comment] 2016-10-11 08:16
@jamieb22 If had not I would not write you a message about settings.

**Comment by jamieb22** [comment] 2016-10-11 08:20
Ok, but you didn't exactly explain the cause of the problem. As far as I understand, Orient DB is coming to a halt due to excessive contention for locks over groups of records. Your resolution is to lock each record individually, so that it reduces contention, but has a side effect of a slow down in query performance.

**Comment by laa** [comment] 2016-10-11 10:00
@jamieb22 yes exactly.

**Comment by laa** [comment] 2016-11-22 09:36
@jamieb22 any updates about this issue ? Did change of settings help in resolving the issue ?

**Comment by laa** [comment] 2016-11-30 06:06
- [ ] 
Close issue because of no reply. If you reproduce given issue and have information which is requested in issue feel free to reopen it.

**Closed by laa** 2016-11-30 06:06 UTC
Labels: bug, storage team, waiting reply
