### ISSUE TITLE
Failure to open database after recovery: "Can not close file with id 0 because it is still in use"

### ISSUE THREAD

**Issue by Ken-Michalak** [orientechnologies/orientdb#6853] opened 2016-10-27 15:13 UTC
## OrientDB Version, operating system, or hardware.

v2.2.4
## Operating System
- [x] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 
## Java

java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.6) (7u79-2.5.6-0ubuntu1.14.04.1)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)
## Expected behavior and actual behavior

Expected: After recovering a database from a forced shutdown, the server successfully connects to it.

Actual: It fails to open the database and gives this error: `Internal server error:
com.orientechnologies.orient.core.exception.OStorageException: Can not close file with id 0 because it is still in use`
## Steps to reproduce the problem

After attempting to shut down the database for an extended period of time, I had to run a "kill -9". One of the databases that wasn't even in use at the time got corrupted, and I cannot open it when connecting remotely or locally.

This is from orientdb.err:

> 2016-10-27 14:38:15:202 WARNI {db=dbname} Storage 'dbname' was not closed properly. Will try to recover from write ahead log [OLocalPaginatedStorage]
> 2016-10-27 14:38:15:202 INFO  {db=dbname} Looking for last checkpoint... [OLocalPaginatedStorage]
> 2016-10-27 14:38:15:203 INFO  {db=dbname} Checkpoints are absent, the restore will start from the beginning. [OLocalPaginatedStorage]
> 2016-10-27 14:38:15:203 INFO  {db=dbname} Data restore procedure is started. [OLocalPaginatedStorage]
> 2016-10-27 14:38:15:280 WARNI {db=dbname} Non tx operation was used during data modification we will need index rebuild. [OLocalPaginatedStorage]
> 2016-10-27 14:38:15:283 SEVER {db=dbname} Data restore was paused because of exception. The rest of changes will be rolled back and WAL files will be backed up. Please report issue about this exception to bug tracker and provide WAL files which are backed up in 'wal_backup' directory. [OLocalPaginatedStorage]
> 2016-10-27 14:38:27:199 INFO  {db=dbname} Storage data recover was completed [OLocalPaginatedStorage]
> 2016-10-27 14:38:27:205 SEVER {db=dbname} Internal server error:
> com.orientechnologies.orient.core.exception.OStorageException: Can not close file with id 0 because it is still in use
>   DB name="dbname" [ONetworkProtocolHttpDb]

**Comment by laa** [comment] 2016-10-28 07:52
HI @Ken-Michalak " Data restore was paused because of exception. The rest of changes will be rolled back and WAL files will be backed up. Please report issue about this exception to bug tracker and provide WAL files which are backed up in 'wal_backup' directory." Could you send this data to me ?

**Comment by Ken-Michalak** [comment] 2016-11-16 15:37
@laa I sent it to you in an email. Did you get it? Is there another way you would like me to send it to you?
(I noticed that this is still flagged as "waiting reply".)

**Comment by laa** [comment] 2016-11-16 16:27
Hi @Ken-Michalak , it should be fixed in 2.2.13 version. Could you try it  ?

**Comment by laa** [comment] 2016-11-18 11:13
@Ken-Michalak could you confirm ?

**Comment by Ken-Michalak** [comment] 2016-11-28 18:09
It gives a different error. (Sorry for the late response. I already had to restore/recreate the database to work around the issue, and don't need to recover it at this point.)

> 2016-11-28 18:02:56:277 SEVER Internal server error:
com.orientechnologies.orient.core.exception.OStorageException: Cannot open local storage '/opt/orientdb-community-2.2.13/databases/BrokenDB' with mode=rw
        DB name="BrokenDB"
--> com.orientechnologies.orient.core.exception.OStorageException: File with name osequence.pcl does not exist in storage BrokenDB
        DB name="BrokenDB" [ONetworkProtocolHttpDb]

**Comment by laa** [comment] 2016-11-30 06:34
Hi @Ken-Michalak that is because restore process was abnormally terminated in previous scenario and file was not restored. To fix this issue just create an empty database and move two files which have name " sequence" but different extensions to the broken database and after that you will be able to open DB without problems. Those files contain information about sequences, so your data will not be broken.

**Comment by Ken-Michalak** [comment] 2016-12-05 16:22
The database opens with those 2 files copied over, but it shows an empty, clean database. None of the classes that there are files for in that folder are listed with "list classes".

**Comment by laa** [comment] 2016-12-06 10:08
@Ken-Michalak I have one more question did you rename sequence cluster when you use database ?

**Comment by Ken-Michalak** [comment] 2016-12-06 16:25
No. I didn't change anything with the default clusters.

**Comment by laa** [comment] 2016-12-13 12:57
I see. The problem is following. When you started the database, file with data of sequences was absent. Duno why.  So the restore procedure could not proceed from the beginning and restore the data. We would change the algorithm to auto restore file if it was absent so restore procedure will continue even if file is lost, so information will be restored at least partially.

**Comment by laa** [comment] 2016-12-13 12:58
I am in the end of estimation of big project, once I finish it , I will fix it.

**Comment by laa** [comment] 2016-12-28 16:10
Hi @Ken-Michalak could you build latest version of 2.2.x from the branch and open broken DB on this branch ?

**Comment by laa** [comment] 2017-01-03 12:59
Hi @Ken-Michalak any updates on that issue ?

**Comment by laa** [comment] 2017-01-10 08:01
Close issue because of no reply. If you reproduce given issue and have information which is requested in issue feel free to reopen it.

**Closed by laa** 2017-01-10 08:01 UTC
Labels: bug, storage team, waiting reply
