### ISSUE TITLE
Property Not Exist when using ALTER PROPERTY

### ISSUE THREAD

**Issue by na2014** [orientechnologies/orientdb#3400] opened 2015-01-15 17:52 UTC
Item 3134 was closed, though I'm not sure why.  It is still a problem that I can reproduce after installing 2.0-rc2 using the default database.  

Using the sample default GratefulDeadConcerts db, I'm trying to change the collation to be case insensitive. I try the following:

ALTER PROPERTY V.name COLLATE ci

I get the error:
com.orientechnologies.orient.core.exception.OCommandExecutionException: Property 'V.name' not exists

The output of info and info class V are below.

Has anyone figured this out yet? It's frustrating to be stuck on something so basic, even more so that the issue was marked "closed".

orientdb {db=GratefulDeadConcerts}> info
Current database: GratefulDeadConcerts (url=remote:localhost/GratefulDeadConcerts)
DISTRIBUTED CONFIGURATION: none (OrientDB is running in standalone mode)
DATABASE PROPERTIES
--------------------------------+----------------------------------------------------+
NAME | VALUE |
--------------------------------+----------------------------------------------------+
Name | null |
Version | 14 |
Conflict Strategy | version |
Date format | yyyy-MM-dd |
Datetime format | yyyy-MM-dd HH:mm:ss |
Timezone | GMT |
Locale Country | UK |
Locale Language | EN |
Charset | UTF-8 |
Schema RID | #0:1 |
Index Manager RID | #0:2 |
Dictionary RID | null |
--------------------------------+----------------------------------------------------+
CLUSTERS
----------------------------------------------+-------+-------------------+----------------+
NAME | ID | CONFLICT STRATEGY | RECORDS |
----------------------------------------------+-------+-------------------+----------------+
_studio | 14 | | 0 |
default | 3 | | 0 |
e | 10 | | 0 |
followed_by | 11 | | 7047 |
index | 1 | | 2 |
internal | 0 | | 3 |
manindex | 2 | | 1 |
ofunction | 6 | | 0 |
orids | 8 | | 0 |
orole | 4 | | 3 |
oschedule | 7 | | 0 |
ouser | 5 | | 3 |
sung_by | 13 | | 501 |
v | 9 | | 809 |
written_by | 12 | | 501 |
----------------------------------------------+-------+-------------------+----------------+
TOTAL = 15 | 8870 |
------------------------------------------------------+-------------------+----------------+
CLASSES
----------------------------------------------+------------------------------------+------------+----------------+
NAME | SUPERCLASS | CLUSTERS | RECORDS |
----------------------------------------------+------------------------------------+------------+----------------+
_studio | | 14 | 0 |
E | | 10 | 0 |
followed_by | E | 11 | 7047 |
OFunction | | 6 | 0 |
OIdentity | | - | 0 |
ORestricted | | - | 0 |
ORIDs | | 8 | 0 |
ORole | OIdentity | 4 | 3 |
OSchedule | | 7 | 0 |
OTriggered | | - | 0 |
OUser | OIdentity | 5 | 3 |
sung_by | E | 13 | 501 |
V | | 9 | 809 |
written_by | E | 12 | 501 |
----------------------------------------------+------------------------------------+------------+----------------+
TOTAL = 14 8864 |
----------------------------------------------+------------------------------------+------------+----------------+
INDEXES
----------------------------------------------+------------+-----------------------+----------------+------------+
NAME | TYPE | CLASS | FIELDS | RECORDS |
----------------------------------------------+------------+-----------------------+----------------+------------+
dictionary | DICTIONARY | | | 0 |
ORole.name | UNIQUE | ORole | name | 3 |
OUser.name | UNIQUE | OUser | name | 3 |
----------------------------------------------+------------+-----------------------+----------------+------------+
TOTAL = 3 6 |
-----------------------------------------------------------------------------------------------------------------+
orientdb {db=GratefulDeadConcerts}> info class V
Class................: V
Default cluster......: v (id=9)
Supported cluster ids: [9]
Cluster selection....: balanced
orientdb {db=GratefulDeadConcerts}>

**Comment by bfausett** [comment] 2015-01-15 18:04
It has been quite frustrating.  I've opened three issues for this and each time they close the issue without it being resolved.

I'm having other issues as well with Traversal that haven't been resolved.  I've worked with other graph db's and have never had this difficult of a time.  Not sure OrientDB is the correct solution for what I'm trying to accomplish because of the lack of basic graph functionality and support.

**Comment by maggiolo00** [comment] 2015-01-15 18:15
@na2014 

can you execute 
`info class V` 
and paste here the result?

**Comment by na2014** [comment] 2015-01-15 18:53
It's already there - "select * from V"  shows a section titled "Properties" with a field called "name".  I'm using the sample database included with the release candidate, so I think this should be easy to reproduce.

**Comment by maggiolo00** [comment] 2015-01-15 18:58
Yes it is there 
but not in the schema.
see here

http://www.orientechnologies.com/docs/last/orientdb.wiki/Schema.html

**Comment by na2014** [comment] 2015-01-15 19:25
Ok - that was it.  When I made "name" part of the schema, the command worked.  Here are 3 problems that came up when doing this:

- tutorials I saw seemed to use the release candidate, not the stable release, so I'm working with that.  That was a little confusing at first, and I really would prefer to use stable.  

- After creating the property "name" in the Studio, changing the collation to CI in the Studio doesn't work.  I could select CI in the pulldown menu, but clicking "save" didn't do anything.  I had to run the ALTER command as a query instead.  No error message is thrown, making this more confusing.  

- The "info" commands cannot be run from within the studio.

- I can't figure out the commands from the command line to show the schema, so I find myself uncomfortably toggling between the studio and the command line to get all this done.  The documentation shows commands that must be run in some other language, and I can't figure out what language it is or where they go (where do I type "OSchema schema = database.getMetadata().getSchema();"?)

- Trying to capture errors in the studio was annoying since they appeared and then disappeared before I could read them.  Why would error messages disappear automatically instead of letting me dismiss them, and why are they appearing at the bottom of the window instead of inline where we were awaiting the response?  

There's obviously a lot going on here, including both the product shortcomings and my own.  But I think of myself/team as being in your core audience, and thought that this still isn't as smooth a product as it should be, especially for a 2.0 version.  I haven't had this much trouble when trying any other db products out there.  I totally appreciate the work that went into this, and am excited about the potential here.  I think having a release focused on making things more polished would really help.

thanks!

**Comment by na2014** [comment] 2015-01-15 19:27
Also, info class V doesn't seem to change, even after I added "name" to the schema.  The output of the command before adding name to the schema is in my very first posting at the end, here's the output after adding to the schema:

orientdb {db=GratefulDeadConcerts}> info class V

Class................: V
Default cluster......: v (id=9)
Supported cluster ids: [9]
Cluster selection....: balanced
orientdb {db=GratefulDeadConcerts}>

**Comment by maggiolo00** [comment] 2015-01-15 21:04
@na2014 
thank you for your feedback
some quick response for your issues.


- 2.0 stable should arrive the next week

- this is a bug, i will look into it

- info is not available because studio rely on http api and uses orientdb sql
  info is a console only command

- to view schema on console run info/ info class
  in studio go to the schema UI

- this has been changed. Before it was sticky and top but i found it annoying that every time i have to click on x to close the notification. If you catch up the error you can go hover on the notification
it will remain open until you remain on it

**Comment by na2014** [comment] 2015-01-15 22:39
Hi,

Thank you for the feedback.  Seems like the HTTP API is a limiting factor in the UI development. 

Would it be a good idea to see if you could reuse another 3rd party DB UI, such as PHPMyAdmin, and then add in the orientdb specific features?  This would let you reuse their interfaces, which have been proven over time, and focus on db features.  You might also want to use an alternate API if the HTTP one doesn't support the full functionality.  I like the idea of an HTTP API, but find having a fully functional UI far more important and don't care how the UI communicates with the db to do that.  If license terms are an issue, it could be maintained as a separate project, letting development focus on the core db features.  

I hope the group doesn't take this the wrong way - the UI is a good start.  But it got in the way of my ability to work through the system, and that was frustrating.  

Thanks again for the fast resolution and helpful responses here.

**Comment by na2014** [comment] 2015-01-15 22:49
To clarify, having a fully functional UI that uses any API is more important than a UI that uses specifically the HTTP API.  The HTTP API is perfectly good as a separate means to access the db.  But I don't think the UI should be hampered by HTTP API's missing features.

**Comment by lvca** [comment] 2015-09-22 23:05
I'm quite lost here. What's the problem with this issue?

**Comment by prjhub** [comment] 2015-10-07 11:42
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.

**Closed by prjhub** 2015-10-07 11:42 UTC
Labels: waiting reply
