### ISSUE TITLE
OrientJS: Create Binary record fails for 2MB Size in  2.1.14

### ISSUE THREAD

**Issue by saeedtabrizi** [orientechnologies/orientdb#5934] opened 2016-04-05 09:20 UTC
Hi 
I have serious problem with binary records in 2.1.14 now . 
when i create binary record with 2MB size , the orientdb server crashed and logging this output to shell :

>  2016-04-05 13:37:51:996 INFO  {db=Dingo_Core_DB} Looking for last checkpoint... [OLocalPaginatedStorage]
> 2016-04-05 13:37:52:106 INFO  {db=Dingo_Core_DB} Found FUZZY checkpoint. [OLocalPaginatedStorage]
> 2016-04-05 13:37:52:108 INFO  {db=Dingo_Core_DB} Data restore procedure from FUZZY checkpoint is started. [OLocalPaginatedStorage]
> 2016-04-05 13:37:52:112 WARNI {db=Dingo_Core_DB} Record OFuzzyCheckpointStartRecord{lsn=OLogSequenceNumber{segment=0, position=19276756}} com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OFuzzyCheckpointStartRecord{lsn=null, previousCheckpoint=OLogSequenceNumber{segment=0, position=19193491}} will be skipped during data restore. [OLocalPaginatedStorage]
> 2016-04-05 13:37:52:113 WARNI {db=Dingo_Core_DB} Record com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OFuzzyCheckpointEndRecord{lsn=OLogSequenceNumber{segment=0, position=19276796}} will be skipped during data restore. [OLocalPaginatedStorage]
> 2016-04-05 13:37:52:114 INFO  {db=Dingo_Core_DB} Storage data recover was completed [OLocalPaginatedStorage]java.lang.OutOfMemoryError: GC overhead limit exceeded
> Dumping heap to java_pid13688.hprof ...
> Heap dump file created [606260451 bytes in 7.422 secs]

When i test this database with 2.1.13 there is no problem and every file or binary record can be created, but in 2.1.14 i got this error .

Is this a bug ? is there any trick to solve or patch this problem ?

**Comment by laa** [comment] 2016-04-05 09:26
You have oom because big record size did  you try to increase heap size ?

**Comment by saeedtabrizi** [comment] 2016-04-05 09:36
I'd tested again and now got another error in 2.1.14 :

I'm connecting to orientdb via orientjs and following this steps :
1. create a small  binary record (300KB) in database (under 1MB ===> everything works well)
2. create a small  binary record (2MB) in database (above 1MB ===> database hangs and prints following lines in console)


2016-04-05 13:56:08:501 INFO  OrientDB auto-config DISKCACHE=5,596MB (heap=455MB os=8,099MB disk=311,016MB) [orientechnologies]
2016-04-05 13:56:08:582 INFO  Loading configuration from: D:/Install/Databases/OrientDb/orientdb-community-2.1.14/config/orientdb-server-config.xml... [OServerConfigurationLoaderXml]
2016-04-05 13:56:08:739 INFO  OrientDB Server v2.1.14 (build 2.1.x@r4d21d805fc9574c11b334a453161920cc1ed9cb7; 2016-03-30 15:26:04+0000) is starting up... [OServer]
2016-04-05 13:56:08:743 INFO  Databases directory: D:\Install\Databases\OrientDb\orientdb-community-2.1.14\databases [OServer]
2016-04-05 13:56:08:765 INFO  Listening binary connections on 0.0.0.0:2424 (protocol v.32, socket=default) [OServerNetworkListener]
2016-04-05 13:56:08:773 INFO  Listening http connections on 0.0.0.0:2480 (protocol v.10, socket=default) [OServerNetworkListener]
2016-04-05 13:56:08:787 INFO  Installing dynamic plugin 'studio-2.1.zip'... [OServerPluginManager]
2016-04-05 13:56:08:868 INFO  Installing GREMLIN language v.2.6.0 - graph.pool.max=50 [OGraphServerHandler]
2016-04-05 13:56:08:869 INFO  [OVariableParser.resolveVariables] Error on resolving property: distributed [orientechnologies]
2016-04-05 13:56:08:873 INFO  Installing Script interpreter. WARN: authenticated clients can execute any kind of code into the server by using the following allowed languages: [sql] [OServerSideScriptInterpreter]
2016-04-05 13:56:08:874 INFO  OrientDB Server v2.1.14 (build 2.1.x@r4d21d805fc9574c11b334a453161920cc1ed9cb7; 2016-03-30 15:26:04+0000) is active. [OServer]java.lang.OutOfMemoryError: GC overhead limit exceeded
Dumping heap to java_pid5896.hprof ...
Heap dump file created [607120539 bytes in 17.293 secs]
Exception in thread "OrientDB Write Cache Flush Task (Dingo_Ssms_DB)" Exception in thread "OrientDB Write Cache Flush Task (Dingo_Cms_DB)" Exception in thread "Timer-0" java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.addConditionWaiter(Unknown Source)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.addConditionWaiter(Unknown Source)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

2016-04-05 14:01:06:424 INFO  Received signal: SIGINT [OSignalHandler]java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.io.File.listFiles(Unknown Source)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.updatePlugins(OServerPluginManager.java:284)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager.access$000(OServerPluginManager.java:59)
        at com.orientechnologies.orient.server.plugin.OServerPluginManager$1.run(OServerPluginManager.java:101)
        at java.util.TimerThread.mainLoop(Unknown Source)
        at java.util.TimerThread.run(Unknown Source)
Error on client connection
java.lang.OutOfMemoryError: GC overhead limit exceeded
Terminate batch job (Y/N)?

I think this is a new bug in orientdb .

**Comment by saeedtabrizi** [comment] 2016-04-05 09:40
Dear @laa  , 
This scenario worked recently in 2.1.13 . i have no any change in my code and scenario or configuration .

Many thanks for you're reply .

**Comment by laa** [comment] 2016-04-05 09:52
Sure , but if memory consumption is increased that is not a bug, it only means that memory consumption is increased. Did you try to increase heap size ? If it will not help could you send us heap dump.

**Comment by saeedtabrizi** [comment] 2016-04-05 10:02
Dear @laa  
No , i did not any  change in heap  default configuration , because this configuration works well with every size (under 20MB that i tested) of binary record before the 2.1.14 version .

```
set LOG_FILE=%ORIENTDB_HOME%/config/orientdb-server-log.properties
set WWW_PATH=%ORIENTDB_HOME%/www
set ORIENTDB_SETTINGS=-Dprofiler.enabled=true
set JAVA_OPTS_SCRIPT=-Xmx512m -Djna.nosys=true -XX:+HeapDumpOnOutOfMemoryError -Djava.awt.headless=true -Dfile.encoding=UTF8 -Drhino.opt.level=9

rem ORIENTDB MAXIMUM HEAP. USE SYNTAX -Xmx<memory>, WHERE <memory> HAS THE TOTAL MEMORY AND SIZE UNIT. EXAMPLE: -Xmx512m
set MAXHEAP=-Xmx512m
```

Ok , i will try to send heap dump file to you  asap. it's about 592MB .

**Comment by saeedtabrizi** [comment] 2016-04-06 11:46
Ok , i solve this issue after many hour's . orientjs 2.1.11  overwrites my custom files in orientjs module .
in the fact we must store binary data in binary record but orientjs not implemented create or update binary records yet and store it like the document record . 
so when i replaced the custom files everythings works well . 
i think the binary protocol must be updated in orientjs project to support binary records well .
thanks @laa 


[record-update.zip](https://github.com/orientechnologies/orientdb/files/206311/record-update.zip)

**Comment by laa** [comment] 2016-04-06 12:12
Hi @saeedtabrizi , I will assign this issue to responsible person, so fix will be put at next hotfix release.

**Comment by laa** [comment] 2016-04-06 12:12
@saeedtabrizi Thank you very much for your time

**Comment by maggiolo00** [comment] 2016-05-18 15:55
@saeedtabrizi 

i've merged the PR in master and released npm orientjs 2.1.17-beta

can you confirm that is solved?

**Comment by saeedtabrizi** [comment] 2016-05-21 15:19
Hi @maggiolo00 , yes it solved now . 

Thanks 
Saeed Tabrizi

**Comment by maggiolo00** [comment] 2016-06-09 16:38
Ok thanks @saeedtabrizi 

closing this

**Closed by maggiolo00** 2016-06-09 16:38 UTC
Labels: bug
