### ISSUE TITLE
com.orientechnologies.orient.core.exception.OStorageException: Cannot put key value entry in index

### ISSUE THREAD

**Issue by satyasrc** [orientechnologies/orientdb#6234] opened 2016-05-31 11:01 UTC
## Expected behavior and actual behavior
As advised by @laa, I had moved to orientdb v2.2.0 from v2.1.10 to counter issue #6219. I am running the same code as in #6219 on v2.2.0. Consequently, that issue is not happening, but I am facing an OStorageException. I suspect it is again an index issue. Given below is the exception stack for this issue:
**Exception in thread "main" com.orientechnologies.orient.core.exception.OStorageException: Cannot put key value entry in index**
	Storage URL="plocal:/home/intern/orientdb-community-2.2.0/databases/LinkedDataStore"
	Storage URL="plocal:/home/intern/orientdb-community-2.2.0/databases/LinkedDataStore"
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.throwSerializedException(OChannelBinaryAsynchClient.java:431)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:382)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:264)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:152)
	at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:2204)
	at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:2199)
	at com.orientechnologies.orient.client.remote.OStorageRemote$20.execute(OStorageRemote.java:1271)
	at com.orientechnologies.orient.client.remote.OStorageRemote$20.execute(OStorageRemote.java:1244)
	at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperation(OStorageRemote.java:160)
	at com.orientechnologies.orient.client.remote.OStorageRemote.commit(OStorageRemote.java:1244)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:549)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:109)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2664)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2634)
	at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.commit(OrientTransactionalGraph.java:175)
	at org.formcept.knowledge.base.graph.FCOrientGraph.addNode(FCOrientGraph.java:104)
	at org.formcept.knowledge.base.core.KnowledgeBuilder.addResources(KnowledgeBuilder.java:192)
	at org.formcept.knowledge.base.core.KnowledgeBuilder.traverseEntireGraph(KnowledgeBuilder.java:274)
	at org.formcept.knowledge.base.core.KnowledgeBuilder.initKnowledgeGraph(KnowledgeBuilder.java:158)
	at test.TestKnowledgeBase.main(TestKnowledgeBase.java:44)
**Caused by: com.orientechnologies.orient.core.exception.OStorageException: Error during index update**
	Storage URL="plocal:/home/intern/orientdb-community-2.2.0/databases/LinkedDataStore"
	at com.orientechnologies.orient.core.index.hashindex.local.OLocalHashTable.put(OLocalHashTable.java:418)
	at com.orientechnologies.orient.core.index.engine.OHashTableIndexEngine.put(OHashTableIndexEngine.java:153)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doUpdateIndexEntry(OAbstractPaginatedStorage.java:1885)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.updateIndexEntry(OAbstractPaginatedStorage.java:1813)
	at com.orientechnologies.orient.core.index.OIndexFullText.put(OIndexFullText.java:110)
	at com.orientechnologies.orient.core.index.OIndexFullText.put(OIndexFullText.java:45)
	at com.orientechnologies.orient.core.index.OIndexAbstract.putInSnapshot(OIndexAbstract.java:897)
	at com.orientechnologies.orient.core.index.OIndexAbstract.applyIndexTxEntry(OIndexAbstract.java:742)
	at com.orientechnologies.orient.core.index.OIndexAbstract.addTxOperation(OIndexAbstract.java:729)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commitIndexes(OAbstractPaginatedStorage.java:1374)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1335)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:555)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:109)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2664)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2634)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.commit(ONetworkProtocolBinary.java:1255)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:447)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:187)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
**Caused by: java.lang.IllegalArgumentException: Given value is present in bucket.**
	at com.orientechnologies.orient.core.index.hashindex.local.OHashIndexBucket.addEntry(OHashIndexBucket.java:249)
	at com.orientechnologies.orient.core.index.hashindex.local.OLocalHashTable.doPut(OLocalHashTable.java:1501)
	at com.orientechnologies.orient.core.index.hashindex.local.OLocalHashTable.put(OLocalHashTable.java:410)
	... 18 more

### Running Mode
- Remote

### OrientDB Version
- v2.2.0

### Operating System
- Linux

### Java Version
- 8

Prompt reply is much appreciated. It is kind of urgent for us.
Thanks.

**Comment by taburet** [comment] 2016-06-01 15:10
Hi @srthecodexpress! I will work on this issue. In #6219 you said you "printing out the info on the console of each inserted node and edge", I assume the listing contains values of fields being indexed by the hash index in question. Is it possible to share this listing with me along with the index definition? If listing contains indexed values I will be able to reproduce the problem on my machine.

**Comment by srthecodexpress** [comment] 2016-06-02 05:19
Hi @taburet. Actually the listing doesn't contain the value of fields being indexed (and by fields, i mean the properties of nodes & edges.). For your help, I am attaching some files below. 
Here is the method **addNode** where the exception is happening at the tx.commit() line 
[addNode.txt](https://github.com/orientechnologies/orientdb/files/294834/addNode.txt)
The log messages in the above code is to log on which nodes the exception is being thrown.
I am giving you the log file. Search with keyword string: "at creation of node:", and you'll find the nodes on which the exceptions are occurring. Ultimately, these nodes and their respective sub-graphs are not being inserted and are quite a lot in number. Given below is the log file.
[fcOrientKbBuilder.log.gz](https://github.com/orientechnologies/orientdb/files/294847/fcOrientKbBuilder.log.gz)
Finally, given below is the index definition part.
[createIndices.txt](https://github.com/orientechnologies/orientdb/files/294848/createIndices.txt)

Thanks a lot for the prompt reply.

**Comment by taburet** [comment] 2016-06-02 16:31
The problem is with the values of `abstract` property. Downloading now `long abstracts` dbpedia dataset to reproduce the problem, hope the order of the insertions doesn't matter. Could you please include the dbpedia name in the listing for each inserted node *before* it being inserted? That will help to eliminate the possible insertion order dependency.

BTW, where did you get the "full dbpedia dataset" mentioned in #6219? Can't find something with the similar name among datasets listed on this page http://wiki.dbpedia.org/Downloads2015-10#datasets

**Comment by laa** [comment] 2016-06-06 10:37
@srthecodexpress it is hard to understand the reason of this issue without initial data. Could you propose us any approach to reproduce the same state of data in the index ?

**Comment by srthecodexpress** [comment] 2016-06-07 04:55
Sorry @laa for the delay in reply. This thing is quite essential to our technology, so I was trying other vendors.
I tried to debug the code. The error is emanating from the doPut method because somehow the binarySearch method is finding a valid index on the property when that property is null. As for the dbpedia datasets I used. 
[Link:]( http://dbpedia.org/Downloads2015-04)
Take .nt files for all these (all for en)-
1. labels(Titles)
2. Categories (Labels)
3. Article Categories
4. Categories (Skos)
5. Short Abstracts
6. redirects
7. transitive-redirects
8. disambiguations
For 8th go to [](http://oldwiki.dbpedia.org/Downloads39#disambiguation-links)
One short approach to reproduce the same state of data would be something like this:
create a 2-3 level tree where you go on inserting nodes and their properties from the top in BFS manner. At the top and mid level are categories, and resources are the leaf-nodes. But, in case of category nodes, not all properties are inserted when they are created. When you have created all leaf nodes for a branch, go back and insert some property for the parent category node. Like abstracts, or Disambiguated_URIs, basically any property which has a hash-index on it. You should be able to reproduce the problem.
I had already shared with you the indexes i am using. I am sharing with you the property types i used on the vertices and edges.
[createTypes.txt](https://github.com/orientechnologies/orientdb/files/301855/createTypes.txt)

**Comment by laa** [comment] 2016-06-07 05:07
@srthecodexpress I think I may provide you a simple workaround for that case. Please create index but use not graph database but SQL command http://orientdb.com/docs/2.2/SQL-Create-Index.html and pass metadata { ignoreNullValues : true } . Could you provide feedback does it work?

**Comment by srthecodexpress** [comment] 2016-06-07 06:06
@laa Ok. I will try that and let you know.

**Comment by taburet** [comment] 2016-06-07 16:28
Fixed on develop branch, it was an issue with binary data manipulation. As far as I know, 2.2.1 is scheduled within next few days, the fix will be there.

**Comment by srthecodexpress** [comment] 2016-06-09 11:10
@laa The workaround you suggested doesn't work. I used Orient SQL commands from the console to create the schema and indexes as you suggested with metadata { ignoreNullValues : true } setting and then proceeded to upload the dbpedia graph. Still i am getting the same exception. (Actually ignoreNullValues : true are the default settings of the indexes as per the OrientDb docs, so I had my doubts all along whether this would make any difference).
@taburet Thanks, for the update. When would I be able to get the 2.2.1 fix. Can you give me the date. As I said earlier, it is quite urgent for us.

**Comment by laa** [comment] 2016-06-09 12:28
@srthecodexpress we have changed default behaviour, seems like docs are  not updated. We will release 2.2.1 version today.

**Comment by srthecodexpress** [comment] 2016-06-11 08:06
Hi @laa . I cannot find the download link to v2.2.1 anywhere on your site. Is it released ?

**Comment by luigidellaquila** [comment] 2016-06-13 07:36
Hi @srthecodexpress 

Not yet, sorry, we found some little problems during the QA phase, we will retry to release today

Thanks

Luigi

**Comment by luigidellaquila** [comment] 2016-06-23 11:57
Reopening for a check (see https://github.com/orientechnologies/orientdb/issues/6331), it seems it's not completely resolved.

**Comment by taburet** [comment] 2016-07-20 09:11
Hi @srthecodexpress! I successfully imported the abstracts for all the records of the "Communist_Party" family from #6331, all the records before them and 100k records after them. So this must be another issue.

Please provide a full exception stack traces for the exceptions mentioned in #6331.

**Comment by srthecodexpress** [comment] 2016-07-27 07:17
Hi @taburet! Currently, we are busy exploring some other options. Will get back to you as soon as we return to orientDB. 
Thanks for your patience and prompt replies.
Sitanshu.

**Comment by lvca** [comment] 2016-08-27 19:24
Closing because no answer after a while. In case please reopen/comment this.

**Closed by lvca** 2016-08-27 19:24 UTC
Labels: bug, storage team, waiting reply
