### ISSUE TITLE
3.0.0m2 performance result is poor when inserting vertexes and edges

### ISSUE THREAD

**Issue by hyperknob** [orientechnologies/orientdb#7610] opened 2017-08-05 10:26 UTC
## Expected behavior  
When I analysized issue #7589, I found a performance problem about 3.0.0m2. 
The same benchmark test codes executed in orientdb 3.0.0m2 should get better performance result than 2.2.x when inserting vertexes and edges.

## Actual behavior  
The actual result is:
QPS in orientdb 2.2.24 is 2000
QPS in orientdb 3.0.0m2 is 7
I think somthing is wrong, db configuration or benchmark test code itself ?
 

## Steps to reproduce  
1. I downloaded and installed the package community-tp2-3.0.0m2.tar.gz in server side, and didn't change the default configuration.
2. I executed the following db init code:
https://gist.github.com/kinssun/63406b7e8849bd6d249d3e97097626ac
3. And then I developed a simple web app which provides REST api to insert specific vertexes and edges into orientdb 3.0.0m2. The core codes fragment can be got from this link:
https://gist.github.com/kinssun/40011544bb88b994a866ede19a05099d
Note that I also use the 3.0.0m2 client from my pom file:
	    <dependency>
		    <groupId>com.orientechnologies</groupId>
		    <artifactId>orientdb-graphdb</artifactId>
		    <version>3.0.0m2</version>
	    </dependency>
	    <dependency>
		    <groupId>com.orientechnologies</groupId>
		    <artifactId>orientdb-core</artifactId>
		    <version>3.0.0m2</version>
	    </dependency>

4. I use Jmeter to send http request towards this web app, insert vertexs and edges randomly with a memberId range limitation 0 - 5000000.

**Comment by laa** [comment] 2017-08-05 10:43
@kinssun that is a crazy difference )) I am pretty sure that something is wrong. We will do initial analyze the issue and then assign it to the person responsible for a module which has problems.

**Comment by laa** [comment] 2017-08-05 10:46
@taburet to mitigate issue on remote side or vice versa to confirm that, could you run the same benchmark on plocal storage ? @kinssun if that does not require much time for you to do the same, could you run the same code on 2.2.x and 3.x on plolcal (embedded) storage but not remote?

**Comment by laa** [comment] 2017-08-09 10:08
Found issue in SQL parser, assigned to @luigidellaquila . Luigi, once you fix this part please assign it, we suppose that is not the last part which we should fix.

**Comment by luigidellaquila** [comment] 2017-08-09 10:49
Thank you @laa, the problem was not in the SQL parser, but in TinkerPop2 API that did not execute the query as a prepared statement (with positional parameters) so it forced the engine to parse the query again and again at each request (no cached statement could be used).

I pushed a fix for that, now the performance seems to be much better.

I'm reassigning the issue to you for a second check

Thanks

Luigi

**Comment by laa** [comment] 2017-08-09 11:51
@luigidellaquila BTW the same issue in TP3 too, could you check it?

**Comment by luigidellaquila** [comment] 2017-08-09 11:59
In 2.2...? I really have no idea, but I'll double check with @maggiolo00 

Thanks

Luigi

**Comment by luigidellaquila** [comment] 2017-08-09 11:59
Sorry, I mean 3.0

**Comment by maggiolo00** [comment] 2017-08-09 12:26
@laa  @luigidellaquila  

there is not `OrientGraphQuery` yet in TP3

**Comment by laa** [comment] 2017-08-09 12:39
OK lest skip it for now and will be back to it once @kinssun provides more data, how @kinssun performed benchmarks on TP3.

**Comment by laa** [comment] 2017-08-09 13:00
On my PC I get:
2.2.x embedded - 2189
3.0 embedded - 1945 

still slower we will continue investigation

**Comment by kinssun** [comment] 2017-08-10 06:42
@Iaa, sorry for replying you so late. I'm a little busy now. Due to the service deployment topology limitation, My app has to use 'remote' mode connecting to Graph DB. If I has enough time this week, I will try embeded mode, but I think it is meanless to me.

BTW, The poor performance result about 3.0.0m2 occured in both Tp2 and Tp3 plugin. The same test codes executed  much faster in 2.2.24

**Comment by kinssun** [comment] 2017-08-10 06:44
@Iaa, sorry for replying you so late. I'm a little busy now. Due to the service deployment topology limitation, My app has to use 'remote' mode connecting to Graph DB. If I has enough time this week, I will try embeded mode, but I think it is meanless to me.

BTW, The poor performance result about 3.0.0m2 occured in both Tp2 and Tp3 plugin. The same test codes executed much faster in 2.2.24

**Comment by laa** [comment] 2017-08-10 09:01
@kinssun thank you very much for your help. We discovered the final reason of slow down on embedded it will be fixed soon I suppose. Also, @taburet discovered a reason slowdown which we discovered in the last test.

```
On my PC I get:
2.2.x embedded - 2189
3.0 embedded - 1945
```

After refactoring of the life cycle, connection pool consumes 33% of resources.
In 2.2.x http://imgur.com/a/gT5gN
In 3.0 http://imgur.com/a/uu7GH 

Assigned to @tglman to fix this issue.

**Comment by maggiolo00** [comment] 2017-08-10 10:33
hi @kinssun 

do you have the code of the benchmark with Tp3 plugin ?

Thanks

**Comment by careerscale** [comment] 2017-08-10 12:04
sorry for intruding into this ticket. Is this issue with a stand alone instance or cluster? I didn't see much performance issue in stand alone embedded but with cluster I have seen lot slower (with snapshots). 

I use orient 3 latest snapshots (all the time) and TP 3.0

**Comment by laa** [comment] 2017-08-10 14:03
@careerscale that is both standalone embedded and remote but it depends on use case. So it is not like all things are a slower issue. Anyway team works hard to fix all issues. We have solutions for almost all of them.

**Comment by careerscale** [comment] 2017-08-10 14:06
stand alone embedded was good for me. I have problems with cluster getting working yet but thats different thing. I had problem with super nodes, but we removed edges that cause super ndoes. so stand alone embedded, I think I have no complaints.

**Comment by laa** [comment] 2017-08-10 14:08
@careerscale what about super nodes do we have an issue about that?

**Comment by laa** [comment] 2017-08-10 14:09
Anyway, I suppose you can not reproduce it, so probably it is already not so relevant.

**Comment by kinssun** [comment] 2017-08-14 10:32
@Enrico Risa, you could get benchmark test code from this link: https://gist.github.com/kinssun/40011544bb88b994a866ede19a05099d

**Comment by enrico** [comment] 2017-08-14 15:11
@kinssun: you've reached the wrong Enrico :)

**Comment by luigidellaquila** [comment] 2017-08-14 15:25
😄 😄 @maggiolo00 this was for you ;-)

Thanks @enrico for pointing this out

Luigi

**Comment by maggiolo00** [comment] 2017-08-21 08:55
@kinssun 

that seems to be TP2 code not Apache TinkerPop 3

**Comment by kinssun** [comment] 2017-08-21 09:37
Hi, every one, what status about this issue? got sovled in next 3.0 release for Tp2 or Tp3?

**Comment by maggiolo00** [comment] 2017-08-21 09:38
hi @kinssun 

you did not provide a benchmark with TP3. Do you have one with the poor result?

**Comment by tglman** [comment] 2017-08-21 09:53
Hi,

I've run some case with TP3 and was fine, I had to fix some cases for better handling the statement caching in remote with TP3 but in my tests I can do ~900 operations, here is the gist: https://gist.github.com/tglman/5cc8670f9afbcbe11d72512bbe59fd1b for TP3

Regards

**Comment by laa** [comment] 2017-08-21 15:11
Hi @tglman but what is the performance of 2.2.x version?

**Comment by tglman** [comment] 2017-08-21 15:19
Hi,

I Still have to completely run the test case in remote 2.2.x, I tried and it was tacking too much time, I run 2.2.x in embedded and it did ~1700, so I feel as today is pretty close in embedded and better in remote, but I prefer do the full run in both environment to be sure.

Regards

**Comment by tglman** [comment] 2017-11-17 14:39
Hi,

I fixed all the issue on network and result sets in 3.0.0.X, closing this issue.

**Closed by tglman** 2017-11-17 14:39 UTC
Labels: performance
