### ISSUE TITLE
Querying vertex hangs

### ISSUE THREAD

**Issue by ylopotun** [orientechnologies/orientdb#4282] opened 2015-06-03 16:02 UTC
For one of the vertices in our DB, when we query for its edges, the DB server hangs:

edges = vertex.getEdges(Direction.IN, incomingProperty.getEdgeLabel());
for (Edge edge : edges) {
...
}

Here is the thread dump:

	at sun.misc.Unsafe.arrayBaseOffset(Native Method)
	at com.orientechnologies.common.directmemory.OUnsafeMemoryJava7.get(OUnsafeMemoryJava7.java:31)
	at com.orientechnologies.common.directmemory.ODirectMemoryPointer.get(ODirectMemoryPointer.java:79)
	at com.orientechnologies.orient.core.serialization.serializer.binary.impl.OLinkSerializer.deserializeFromDirectMemoryObject(OLinkSerializer.java:108)
	at com.orientechnologies.orient.core.serialization.serializer.binary.impl.OLinkSerializer.deserializeFromDirectMemoryObject(OLinkSerializer.java:43)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.deserializeFromDirectMemory(ODurablePage.java:127)
	at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiBucket.getKey(OSBTreeBonsaiBucket.java:285)
	at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiBucket.find(OSBTreeBonsaiBucket.java:203)
	at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.findBucket(OSBTreeBonsaiLocal.java:1225)
	at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.loadEntriesMajor(OSBTreeBonsaiLocal.java:729)
	at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag$SBTreeMapEntryIterator.prefetchData(OSBTreeRidBag.java:458)
	at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag$SBTreeMapEntryIterator.next(OSBTreeRidBag.java:440)
	at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag$SBTreeMapEntryIterator.next(OSBTreeRidBag.java:420)
	at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag.nextChangedNotRemovedSBTreeEntry(OSBTreeRidBag.java:1011)
	at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag.access$200(OSBTreeRidBag.java:57)
	at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag$RIDBagIterator.next(OSBTreeRidBag.java:329)
	at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag$RIDBagIterator.next(OSBTreeRidBag.java:253)
	at com.orientechnologies.orient.core.iterator.OLazyWrapperIterator.hasNext(OLazyWrapperIterator.java:89)
	at com.orientechnologies.common.collection.OMultiCollectionIterator.hasNext(OMultiCollectionIterator.java:80)

The same happens when we query this vertex from the console:
select from 19:2274

I'll send the DB sample via e-mail.

**Comment by laa** [comment] 2015-06-03 17:59
Which version do you use ?

**Comment by ylopotun** [comment] 2015-06-03 18:10
2.1-rc3

**Comment by tglman** [comment] 2015-06-04 14:51
Hi @ylopotun i got your database and i'm investigating for the  root cause, but anyway checking the data of that record i saw that it didn't have any edged linking in, so i think you can workaround removing the property. 

I'll send you by mail the specific detail.

**Comment by tglman** [comment] 2015-06-11 09:42
Hi @ylopotun, 
we finally found the main problem, created the relative tests and fixed, we are going to release a RC in the next hours with the fix, we created also and additional tool that check for eventual more case with ridbag problem and fix it, you can invoke it using "repair database --fix-ridbags" opening the database with the console in plocal.

closing

**Closed by tglman** 2015-06-11 09:42 UTC
Labels: bug, in progress
