### ISSUE TITLE
2.1-rc3 - Bug?: <>/= don't work properly with @class

### ISSUE THREAD

**Issue by zifnab87** [orientechnologies/orientdb#4286] opened 2015-06-04 00:45 UTC
Continuing from relevant issue #4279 : Those doesn't give any results: 
`traverse outV() from (traverse inE('FactContains') from #12:15) while @class = 'FactGeneral' limit 2000` (In Browse mode: 0 results)

`traverse outV() from (traverse inE('FactContains') from #12:15) while @class = 'FactPersonal' limit 2000` (In Browse mode: 0 results)

while this gives:

`traverse outV() from (traverse inE('FactContains') from #12:15) while @class <> 'FactPersonal' limit 2000` (In Browse mode: 58 results - duplicated)

![image](https://cloud.githubusercontent.com/assets/526062/7974551/02ceaf08-0a31-11e5-97e9-1cce65f9494c.png)

and this gives:

`traverse outV() from (traverse inE('FactContains') from #12:15) while @class <> 'FactGeneral' limit 2000`  (In Browse mode: 40 results - duplicated)

![image](https://cloud.githubusercontent.com/assets/526062/7974565/34b50ba2-0a31-11e5-89f8-eab0da27d151.png)

I thought Entity shouldn't have been returned in those two cases right?

Another situation
`select expand(outV()) from (select expand(inE('FactContains')) from #12:15) where @class <> 'FactPersonal' limit 2000`

`select expand(outV()) from (select expand(inE('FactContains')) from #12:15) where @class <> 'FactGeneral' limit 2000`

returning the same number of rows: 32(where this came from?) all FactGenral in both cases

I tried with = returning no results as with traverse..

FactGeneral (total in my db 53) and FactPersonal (total in my db 7) are subclasses of Fact (total in my db 60)

**Comment by zifnab87** [comment] 2015-06-18 15:56
any comment on that? is that expected?

**Comment by santo-it** [comment] 2017-02-28 19:44
Hi,

Thanks for opening this

I was checking some old issues and noticed this one

I understand this issue was happening in an RC version of 2.1. 2.1 is EOL now

It would be interesting to understand if a similar issue is still happening with latest GA version of OrientDB

This issue does not include comments from other users, which can be seen as a good sign as perhaps this is not happening anymore (?)

I believe it's safe to tag this with "cannot replicate". Please comment if you are affected or you feel this is still current

Many Thanks,

**Comment by zifnab87** [comment] 2017-03-01 03:51
was there a passing test added for this case and if yes could you point to the source code? Thanks

**Comment by santo-it** [comment] 2017-03-01 13:09
Hi,

I made some tests with 2.2.17 - these are some results:

1. SQL to recreate the original graph:

```
CREATE CLASS Fact EXTENDS V;
CREATE PROPERTY Fact.Id LONG;
 
CREATE CLASS FactGeneral EXTENDS V, Fact;
CREATE INDEX FactGeneral.Id ON FactGeneral(Id) UNIQUE;

CREATE CLASS FactPersonal EXTENDS V, Fact;
CREATE INDEX FactPersonal.Id ON FactPersonal(Id) UNIQUE;

CREATE CLASS Entity EXTENDS V;
CREATE PROPERTY Entity.Id LONG;
CREATE INDEX Entity.Id ON Entity(Id) UNIQUE;

INSERT INTO Entity SET Id = 1;

INSERT INTO FactGeneral SET Id = 1;
INSERT INTO FactGeneral SET Id = 2;
INSERT INTO FactGeneral SET Id = 3;
INSERT INTO FactGeneral SET Id = 4;
INSERT INTO FactGeneral SET Id = 5;
INSERT INTO FactGeneral SET Id = 6;
INSERT INTO FactGeneral SET Id = 7;
INSERT INTO FactGeneral SET Id = 8;
INSERT INTO FactGeneral SET Id = 9;
INSERT INTO FactGeneral SET Id = 10;
INSERT INTO FactGeneral SET Id = 11;
INSERT INTO FactGeneral SET Id = 12;
INSERT INTO FactGeneral SET Id = 13;
INSERT INTO FactGeneral SET Id = 14;
INSERT INTO FactGeneral SET Id = 15;
INSERT INTO FactGeneral SET Id = 16;
INSERT INTO FactGeneral SET Id = 17;
INSERT INTO FactGeneral SET Id = 18;
INSERT INTO FactGeneral SET Id = 19;
INSERT INTO FactGeneral SET Id = 20;
INSERT INTO FactGeneral SET Id = 21;
INSERT INTO FactGeneral SET Id = 22;
INSERT INTO FactGeneral SET Id = 23;
INSERT INTO FactGeneral SET Id = 24;
INSERT INTO FactGeneral SET Id = 25;
INSERT INTO FactGeneral SET Id = 26;
INSERT INTO FactGeneral SET Id = 27;
INSERT INTO FactGeneral SET Id = 28;
INSERT INTO FactGeneral SET Id = 29;
INSERT INTO FactGeneral SET Id = 30;
INSERT INTO FactGeneral SET Id = 31;
INSERT INTO FactGeneral SET Id = 32;
INSERT INTO FactGeneral SET Id = 33;
INSERT INTO FactGeneral SET Id = 34;
INSERT INTO FactGeneral SET Id = 35;
INSERT INTO FactGeneral SET Id = 36;
INSERT INTO FactGeneral SET Id = 37;
INSERT INTO FactGeneral SET Id = 38;
INSERT INTO FactGeneral SET Id = 39;
INSERT INTO FactGeneral SET Id = 40;
INSERT INTO FactGeneral SET Id = 41;
INSERT INTO FactGeneral SET Id = 42;
INSERT INTO FactGeneral SET Id = 43;
INSERT INTO FactGeneral SET Id = 44;
INSERT INTO FactGeneral SET Id = 45;
INSERT INTO FactGeneral SET Id = 46;
INSERT INTO FactGeneral SET Id = 47;
INSERT INTO FactGeneral SET Id = 48;
INSERT INTO FactGeneral SET Id = 49;
INSERT INTO FactGeneral SET Id = 50;
INSERT INTO FactGeneral SET Id = 51;
INSERT INTO FactGeneral SET Id = 52;
INSERT INTO FactGeneral SET Id = 53;

INSERT INTO FactPersonal SET Id = 1;
INSERT INTO FactPersonal SET Id = 2;
INSERT INTO FactPersonal SET Id = 3;
INSERT INTO FactPersonal SET Id = 4;
INSERT INTO FactPersonal SET Id = 5;
INSERT INTO FactPersonal SET Id = 6;
INSERT INTO FactPersonal SET Id = 7;

CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=1) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=2) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=3) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=4) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=5) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=6) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=7) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=8) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=9) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=10) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=11) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=12) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=13) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=14) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=15) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=16) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=17) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=18) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=19) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=20) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=21) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=22) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=23) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=24) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=25) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=26) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=27) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=28) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=29) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=30) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=31) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=32) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=33) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=34) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=35) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=36) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=37) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=38) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=39) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=40) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=41) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=42) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=43) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=44) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=45) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=46) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=47) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=48) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=49) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=50) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=51) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=52) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactGeneral WHERE Id=53) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactPersonal WHERE Id=1) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactPersonal WHERE Id=2) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactPersonal WHERE Id=3) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactPersonal WHERE Id=4) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactPersonal WHERE Id=5) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactPersonal WHERE Id=6) TO (SELECT FROM Entity WHERE Id=1);
CREATE EDGE FactContains FROM (SELECT FROM FactPersonal WHERE Id=7) TO (SELECT FROM Entity WHERE Id=1);
 ```
 
1.1 possible additional part in the graph

```
CREATE CLASS OtherClass EXTENDS V;
CREATE PROPERTY OtherClass.Id LONG;
CREATE INDEX OtherClass.Id ON OtherClass(Id) UNIQUE;

INSERT INTO OtherClass SET Id = 1;
CREATE EDGE OtherEdge FROM (SELECT FROM OtherClass WHERE Id=1) TO (SELECT FROM FactPersonal WHERE Id=1);
```


 
2. Queries

2.1 Counts, using match:

a. 53, ok:
```
select count(*) from (match {Class: FactGeneral, as: factgeneral}-FactContains->{class: Entity, as: entity, where:(Id=1)} return factgeneral)
```

b. 7, ok:
```
select count(*) from (match {Class: FactPersonal, as: factpersonal}-FactContains->{class: Entity, as: entity, where:(Id=1)} return factpersonal)
```

c. 60, ok:
```
select count(*) from (match {Class: fact, as: fact}-FactContains->{class: Entity, as: entity, where:(Id=1)} return fact)
```

2.2 Traverses

a. :
```
traverse inE('FactContains') from (SELECT FROM Entity WHERE Id=1)
```

b. count of previous traverse 61, :
```
select count(*) from (traverse inE('FactContains') from (SELECT FROM Entity WHERE Id=1))
```

c. count more in details, ok:
```
select @class, count(*) from (traverse inE('FactContains') from (SELECT FROM Entity WHERE Id=1)) group by @class
```

FactContains 60
Entity 1

d. 0 :
```
traverse outV() from (traverse inE('FactContains') from (SELECT FROM Entity WHERE Id=1)) while @class = 'FactGeneral' limit 2000 
```

e. 0 :
```
traverse outV() from (traverse inE('FactContains') from (SELECT FROM Entity WHERE Id=1)) while @class = 'FactPersonal' limit 2000  
```

f. returns rows
```
traverse outV() from (traverse inE('FactContains') from (SELECT FROM Entity WHERE Id=1)) while @class <> 'FactPersonal' limit 2000
```

g. count of previous traverse , 114
```
select count(*) from (traverse outV() from (traverse inE('FactContains') from (SELECT FROM Entity WHERE Id=1)) while @class <> 'FactPersonal' limit 2000)
```

f. previous count, aggregated by class:
```
select @class, count(*) from (traverse outV() from (traverse inE('FactContains') from (SELECT FROM Entity WHERE Id=1)) while @class <> 'FactPersonal' limit 2000) group by @class
```

FactContains 60
Entity 1
FactGeneral 53

i. returs rows
```
traverse outV() from (traverse inE('FactContains') from (SELECT FROM Entity WHERE Id=1)) while @class <> 'FactGeneral' limit 2000
```

m. return rows
```
traverse outV() from (traverse inE('FactContains') from (SELECT FROM Entity WHERE Id=1)) while @class <> 'FactGeneral' limit 2000
```

n. count of previous rows , 68
```
traverse outV() from (traverse inE('FactContains') from (SELECT FROM Entity WHERE Id=1)) while @class <> 'FactGeneral' limit 2000
```

p. previous count, aggregated by class:
```
select @class, count(*) from (traverse outV() from (traverse inE('FactContains') from (SELECT FROM Entity WHERE Id=1)) while @class <> 'FactGeneral' limit 2000) group by @class
```

FactContains: 60
Entity: 1
FactPersonal: 7


2.3 match queries

a. returns 1 entity, ok:
```
match {as: other}--{Class: fact, as: fact}-FactContains->{class: Entity, as: entity, where:(Id=1)} return entity
```

c. returns 1, expected:
```
match {as: other}--{Class: fact, as: fact}-FactContains->{class: Entity, as: entity, where:(Id=1)} return other.Id
```

2.4 select queries

a. :
```
select expand(inE('FactContains')) from (SELECT FROM Entity WHERE Id=1) limit 2000 
```

b.: 
```
select count(*) from (select expand(inE('FactContains')) from (SELECT FROM Entity WHERE Id=1) limit 2000 )
```
60
  
c.

select expand(outV()) from (select expand(inE('FactContains')) FROM (SELECT FROM Entity WHERE Id=1)) where @class <> 'FactPersonal' limit 2000
 

d. previous count by class

select @class, count(*) from (select expand(outV()) from (select expand(inE('FactContains')) FROM (SELECT FROM Entity WHERE Id=1)) where @class <> 'FactPersonal' limit 2000) group by @class 

FactGeneral 53
FactPersonal 7


e.

select expand(outV()) from (select expand(inE('FactContains')) from (SELECT FROM Entity WHERE Id=1)) where @class <> 'FactGeneral' limit 2000 
 

f. previous count by class  

select @class, count(*) from (select expand(outV()) from (select expand(inE('FactContains')) from (SELECT FROM Entity WHERE Id=1)) where @class <> 'FactGeneral' limit 2000) group by @class


FactGeneral 53
FactPersonal 7

 from (select expand(inE('FactContains')) from (SELECT FROM Entity WHERE Id=1)) where @class = 'OtherEdge' limit 2000


--

**Comment by santo-it** [comment] 2017-03-01 17:12
Hi, based on my tests

Calling 1,2,3,4,5,6,7 and 8 the query you posted:

No results:

1. traverse outV() from (traverse inE('FactContains') from (SELECT FROM Entity WHERE Id=1)) while @class = 'FactGeneral' limit 2000  
2. traverse outV() from (traverse inE('FactContains') from (SELECT FROM Entity WHERE Id=1)) while @class = 'FactPersonal' limit 2000  

58 results:

3. traverse outV() from (traverse inE('FactContains') from (SELECT FROM Entity WHERE Id=1)) while @class <> 'FactPersonal' limit 2000  

40 results:

4. traverse outV() from (traverse inE('FactContains') from (SELECT FROM Entity WHERE Id=1)) while @class <> 'FactGeneral' limit 2000  

No results:

5. select expand(outV()) from (select expand(inE('FactContains')) from (SELECT FROM Entity WHERE Id=1)) where @class ='FactPersonal' limit 2000
6. select expand(outV()) from (select expand(inE('FactContains')) from (SELECT FROM Entity WHERE Id=1)) where @class = 'FactGeneral' limit 2000

32 results:

7. select expand(outV()) from (select expand(inE('FactContains')) from (SELECT FROM Entity WHERE Id=1)) where @class <> 'FactPersonal' limit 2000
8. select expand(outV()) from (select expand(inE('FactContains')) from (SELECT FROM Entity WHERE Id=1)) where @class <> 'FactGeneral' limit 2000

Note: I have replaced #12:15 with a query that identifies the only Entity present in the test case, i.e the one with Id=1: SELECT FROM Entity WHERE Id=1

In 2.1-rc3 this is what you got in terms of count(*):

1. --> 0
2. --> 0
3. --> 58
4. --> 40
5. --> 0
6. --> 0
7. --> 32
8. --> 32

This is what I get in 2.2.17:

1. --> 0
2. --> 0 
3. --> 114 (FactContains 60, Entity 1, FactGeneral 53)  
4. --> 68 (FactContains: 60, Entity: 1, FactPersonal: 7 
5. --> 0
6. --> 0 
7. --> 60 (FactGeneral 53, FactPersonal 7)
8. --> 60 (FactGeneral 53, FactPersonal 7)


So I'd say with 2.2 we are getting correct numbers for those queries.

Let's now try to describe things in words -and see how we can change those queries to get what you (probably) wanted to get

a. we starts from the entity with Id 1: SELECT FROM Entity WHERE Id=1
b. we would like to get all the incoming edges of class 'FactContains' that are connected to this entity. To do this we can execute

traverse inE('FactContains') from (SELECT FROM Entity WHERE Id=1) 

How many records do we find ? if we execute a count * grouped by @class:

select @class,count(*) from (traverse inE('FactContains') from (SELECT FROM Entity WHERE Id=1) ) group by @class

we get:

FactContains 60
Entity 1

So we find all the 60 FactContains edges, as expected 

c. now within all the vertices connected to the edges we found above, we would like to find the ones of class FactGeneral: we know we should get 53 (and only 53) vertices. To do this we can execute:
```
select from (
	traverse in('FactContains') from (
		SELECT FROM Entity WHERE Id=1
	)
) where @class = 'FactGeneral' limit 2000
```
note the use of in('FactContains') - in other words, you can just use in() instead of during two traverses as you were doing in query 1.
 
or using a select:
```
select from (
    select expand(inE('FactContains').outV()) from (
      SELECT FROM Entity WHERE Id=1
    )
) where @class = 'FactGeneral' limit 2000
```

note the position of outV().  You can use this query instead of the one you were using in 6


d. similar to c, but we would like to get all the vertices of class FactPersonal (7 and only those 7). To do this we execute:
```

select from (
	traverse in('FactContains') from (
		SELECT FROM Entity WHERE Id=1
	)
) where @class = 'FactPersonal' limit 2000
```

this is the query to be used instead of 2

or using a select:
```

select from (
    select expand(inE('FactContains').outV()) from (
      SELECT FROM Entity WHERE Id=1
    )
) where @class = 'FactPersonal' limit 2000
```

this is the query to be used instead of 7 

Now, to test the <> operator

e. similar to c, but this time we would like to get all the vertices of class different from FactPersonal (so we want the FactGeneral vertices). They should be 53. To do this we execute:

```
select from (
	traverse in('FactContains') from (
		SELECT FROM Entity WHERE Id=1
	)
) where @class <> 'FactPersonal' limit 2000
```

or using the select:

```
select from (
    select expand(inE('FactContains').outV()) from (
      SELECT FROM Entity WHERE Id=1
    )
) where @class <> 'FactPersonal' limit 2000
```


f. similar to c, but this time we would like to get all the vertices of class different from FactGeneral (so we want the FactPersonal vertices). They should be 7. To do this we execute:

```
select from (
	traverse in('FactContains') from (
		SELECT FROM Entity WHERE Id=1
	)
) where @class <> 'FactGeneral' limit 2000
```

or using the select:
 
```
select from (
    select expand(inE('FactContains').outV()) from (
      SELECT FROM Entity WHERE Id=1
    )
) where @class <> 'FactGeneral' limit 2000
 ```

 
So to get what you (probably) want, please use the **correct queries** above.

Note that the Match syntax can help as well and be more intuitive, e.g. you may use queries like the following:

i) Get all factgeneral linked to that entity:

match {Class: FactGeneral, as: factgeneral}-FactContains->{class: Entity, as: entity, where:(Id=1)} return factgeneral


i) Get all factpersonal linked to that entity:

match {Class: FactPersonal, as: factpersonal}-FactContains->{class: Entity, as: entity, where:(Id=1)} return factpersonal


 
About why "Entity" is returned in the traverse - that's normal, yes. If you use the select I provided (instead of the traverse) you won't get it 


Based on the above, I think this is not a bug, and in 2.2.17 things are working as expected 

To answer your question about a testcase - no there's no testcase.  The issue you were getting (about wrong recordcount) was in fact in an RC version, and at some point of time it has been fixed

You were using "wrong" where conditions anyway - the queries I wrote above filter in the right way using @class and the = and <> operators

I hope these explanations helps. Please let us know if we can go ahead and close the issue or if more help is needed 

Thanks,

**Comment by zifnab87** [comment] 2017-03-01 17:16
Awesome! Thanks @santo-it! I feel that this issue can be closed. I also believe that the tests need to be added in the automated test suite you have because bugs or different behaviors tend to reappear if there aren't any test safeguards

**Closed** 2017-12-29 14:23 UTC
Labels: cannot replicate
