### ISSUE TITLE
updating property attribute LINKEDCLASS works wrong

### ISSUE THREAD

**Issue by Ivanov-Yuriy** [orientechnologies/orientdb#5604] opened 2016-01-19 08:00 UTC
Hi, I use orient server 2.1.9

I found mistake while updating attribute LINKEDCLASS
when I insert NULL in the attribute, it won't change value

**create class v1 extends V**
Class created successfully. Total classes in database now: 11

**create class v2 extends V**
Class created successfully. Total classes in database now: 12

**create property v1.prop LINK**
Property created successfully with id=1

**alter property v1.prop LINKEDCLASS v2**
Property updated successfully

**select expand(properties)  from ( select expand(classes) from metadata:schema) where name = 'v1'**
----+------+----+----+--------+---------+--------+-------+------------+----+----+------+------------+-------+-----------
\#   |@CLASS|name|type|globalId|mandatory|readonly|notNull|defaultValue|min |max |regexp|customFields|collate|linkedClass
----+------+----+----+--------+---------+--------+-------+------------+----+----+------+------------+-------+-----------
0   |null  |prop|13  |20      |false    |false   |false  |null        |null|null|null  |null        |default|v2
----+------+----+----+--------+---------+--------+-------+------------+----+----+------+------------+-------+-----------
1 item(s) found. Query executed in 0.023 sec(s).

**alter property v1.prop LINKEDCLASS NULL**
Property updated successfully

**select expand(properties)  from ( select expand(classes) from metadata:schema) where name = 'v1'**
----+------+----+----+--------+---------+--------+-------+------------+----+----+------+------------+-------+-----------
\#   |@CLASS|name|type|globalId|mandatory|readonly|notNull|defaultValue|min |max |regexp|customFields|collate|linkedClass
----+------+----+----+--------+---------+--------+-------+------------+----+----+------+------------+-------+-----------
0   |null  |prop|13  |20      |false    |false   |false  |null        |null|null|null  |null        |default|v2
----+------+----+----+--------+---------+--------+-------+------------+----+----+------+------------+-------+-----------
1 item(s) found. Query executed in 0.012 sec(s).

**Comment by tglman** [comment] 2016-03-17 06:57
hi,

i added a test with this commit: https://github.com/orientechnologies/orientdb/commit/7675b089a17ce9c7f6249f0ba32361e1e44de965

it seams to work correctly, be aware that in case of remote for refresh the console you have to disconnect and reconnect, we have already issue about that and will be resolved in the next major version.

**Closed by tglman** 2016-03-17 06:57 UTC

**Comment by a-unite** [comment] 2016-07-09 22:18
Dear @tglman,

actually this issue is still reproducible both in 2.19 and 2.2.4.

Steps are performed in Studio, not console (check performed on memory database, remote database, graph or document). Once you've set linkedClass to a property, you couldn't unset it by assigning `null` value.

I see these tests are properly formed, does it mean, that meta updated only on Java client side?

Thanks.

**Comment by tglman** [comment] 2016-07-11 13:19
hi @a-unite,

I think the fact that you don't see the result from the query is due to some caching, if you check the schema from the schema tab you will see that the LINKEDCLASS is removed correctly, we are checking this caching.

Regards

**Comment by a-unite** [comment] 2016-07-11 14:08
@tglman, thank you!

Looks like it happens for SQL requests (to scheme) only.

I'm curious what kind of caching it must be, if it still returns the same result even after server was restarted.

Eagerly looking forward to learn more on how this mystery will be cleared up.

Thanks!

**Comment by petervavro** [comment] 2020-07-17 02:49
I am running OrientDB version : 3.0.32 but this does not seems to be solved yet. I run "ALTER PROPERTY MyEdgeClass.in LINKEDCLASS NULL;" in "Browser" studio but it does nothing. But I can manually remove linked class by editing schema using Studio UI, that is possible. Is there a way to remove linked class via SQL, please ?
