### ISSUE TITLE
Incorrect MATCH result with if/eval on a datetime value

### ISSUE THREAD

**Issue by obi1kenobi** [orientechnologies/orientdb#7160] opened 2017-02-08 19:20 UTC
## Expected behavior  
In the repro section, all MATCH queries are equivalent and should produce identical results -- returning one row with all of the created vertices in it.   

## Actual behavior  
Except for the first query (without any if/eval), all subsequent queries incorrectly return no results.  

## Steps to reproduce  
Database setup:
```
CREATE CLASS Foo EXTENDS V
CREATE CLASS Event EXTENDS V
CREATE PROPERTY Event.name String
CREATE PROPERTY Event.event_date Datetime

CREATE CLASS Foo_Start EXTENDS E
CREATE CLASS Foo_End EXTENDS E
CREATE CLASS Foo_Center EXTENDS E

CREATE VERTEX Foo

CREATE VERTEX Event SET name = 'start', event_date = '1990-01-01 00:00:00'
CREATE VERTEX Event SET name = 'end', event_date = '2017-01-01 00:00:00'
CREATE VERTEX Event SET name = 'center', event_date = '2000-01-01 00:00:00'

CREATE EDGE Foo_Start FROM (SELECT * FROM Foo) TO (SELECT * FROM Event WHERE name = 'start')
CREATE EDGE Foo_End FROM (SELECT * FROM Foo) TO (SELECT * FROM Event WHERE name = 'end')
CREATE EDGE Foo_Center FROM (SELECT * FROM Foo) TO (SELECT * FROM Event WHERE name = 'center')
``` 

All of the following queries attempt to ensure that the `center` Event has an `event_date` between the `start` and `end`.

The following query returns one result, as expected:
```
MATCH {
    class: Foo,
    as: foo
}.out('Foo_Start') {
    as: start
}, {
    class: Foo,
    as: foo
}.out('Foo_End') {
    as: end
}, {
    class: Foo,
    as: foo
}.out('Foo_Center') {
    where: (($matched.start.event_date <= event_date) AND (event_date <= $matched.end.event_date)),
    as: center
}
RETURN $matches
```

Let's allow the `Foo_End` edge to be optional. That means that before using the `as: end` matched value, we must check it against `null`. However, the following query returns no results:
```
MATCH {
    class: Foo,
    as: foo
}.out('Foo_Start') {
    as: start
}, {
    class: Foo,
    as: foo
}.out('Foo_End') {
    optional: true,
    as: end
}, {
    class: Foo,
    as: foo
}.out('Foo_Center') {
    where: (
        (event_date >= $matched.start.event_date) AND 
        (
            if(eval("($matched.end IS NOT null)"), 
               if(eval("(event_date <= $matched.end.event_date)"), 
                  true, 
                  false
               ), 
               true
            ) = true
        )
    ),
    as: center
}
RETURN $matches
```

The following equivalent query with only a single `if/eval` also returns no results:
```
MATCH {
    class: Foo,
    as: foo
}.out('Foo_Start') {
    as: start
}, {
    class: Foo,
    as: foo
}.out('Foo_End') {
    optional: true,
    as: end
}, {
    class: Foo,
    as: foo
}.out('Foo_Center') {
    where: (
        (event_date >= $matched.start.event_date) AND 
        (
            if(eval("(($matched.end IS null) OR (event_date <= $matched.end.event_date))"), 
               true,
               false
            ) = true
        )
    ),
    as: center
}
RETURN $matches
```

Even getting rid of the optionality of the `Foo_End` edge doesn't fix the problem -- this variant also returns no results:
```
MATCH {
    class: Foo,
    as: foo
}.out('Foo_Start') {
    as: start
}, {
    class: Foo,
    as: foo
}.out('Foo_End') {
    as: end
}, {
    class: Foo,
    as: foo
}.out('Foo_Center') {
    where: (
        (event_date >= $matched.start.event_date) AND 
        (
            if(eval("(($matched.end IS null) OR (event_date <= $matched.end.event_date))"), 
               true,
               false
            ) = true
        )
    ),
    as: center
}
RETURN $matches
```

**Comment by obi1kenobi** [comment] 2017-02-13 18:23
@lvca @luigidellaquila just making sure this issue doesn't get buried -- I'd love it if one of you guys could triage and let me know if I can help / if there's a workaround you can think of.

**Comment by luigidellaquila** [comment] 2017-02-14 08:44
Hi @obi1kenobi 

I'd say that the problem here is the `eval()` function, as the string expression is not evaluated at parse time (that is when the execution plan is defined), so probably it remains out of the consistency checks for the optional nodes.

Did you try to rewrite that WHERE condition without using the `eval()`?

Thanks

Luigi

Side note: in V 3.0 I'd like to deprecate the `eval()` function. Now it's needed because there is no full support to math operators in the queries, but with the new executor there is no need for that anymore

**Comment by obi1kenobi** [comment] 2017-02-14 17:43
Hi @luigidellaquila, thanks for taking a look!

I'll double-check the execution plan with a debugger and let you know in the next ~hour if it is indeed an execution plan problem.

I simplified my use case for the sake of the bug report -- my GraphQL compiler work requires the use of nested `if()` statements, which as far as I know require the use of `eval()` in the condition part of the `if()`. Unless there's a different way to use `if()`, there's unfortunately no way to rewrite the WHERE to not use `eval()`, and this is blocking my progress :(

Regarding deprecating `eval()` -- I don't mind at all, so long as there is a way to create nested `if-else` logic.

**Comment by obi1kenobi** [comment] 2017-02-14 18:22
@luigidellaquila your idea was correct -- `getMatchPatternInvolvedAliases()` does not include aliases used in the `eval()` call, and is therefore incorrect. Similarly, I believe that aliases used in `while` conditions are not detected and returned, which can also cause incorrect schedules to be generated.

I believe that if the list of involved aliases is made to cover these two edge cases, the topological scheduler will handle the additional complexity of scheduling the query execution correctly. Let me know how you'd like to proceed -- I'd really like to see this fixed in 2.2.16 if possible so I can move forward on my GraphQL-to-MATCH work.

**Comment by luigidellaquila** [comment] 2017-02-15 08:14
Hi @obi1kenobi 

Good catch for the WHILE condition, that should be an easy fix.
For the `eval()` it's a bit trickier because the string parameter is not parsed by the SQL parser, so I do not have an AST to search for involved aliases, but I'll see what I can do

Thanks

Luigi

**Comment by obi1kenobi** [comment] 2017-02-15 13:59
Thanks, I appreciate it! So I know what to tell my teammates, is this a
2.2.16 kind of fix, or do you think it'll take longer?

**Comment by luigidellaquila** [comment] 2017-02-15 16:09
Hi @obi1kenobi

2.2.16 is already out ;-)
2.2.17 is scheduled for tomorrow, so I'll hardly manage to include a fix, but it will likely be in 2.2.18

Thanks

Luigi

**Comment by obi1kenobi** [comment] 2017-02-15 16:11
Sounds great, thank you and looking forward to it!

**Comment by obi1kenobi** [comment] 2017-02-15 19:33
@luigidellaquila I was testing some workarounds, and it seems like there are more bugs here. Consider the following query:
```
MATCH {
    class: Foo,
    as: foo
}.out('Foo_Start') {
    as: start
}, {
    class: Foo,
    as: foo
}.out('Foo_End') {
    optional: true,
    as: end
}, {
    class: Foo,
    as: foo
}.out('Foo_Center') {
    where: (
        (event_date >= $matched.start.event_date) AND 
        (($matched.end IS null) OR ($matched.end IS NOT null)) AND
        (
            if(eval("(($matched.end IS null) OR (event_date <= $matched.end.event_date))"), 
               true,
               false
            ) = true
        )
    ),
    as: center
}
RETURN $matches
```

The `(($matched.end IS null) OR ($matched.end IS NOT null))` part is not in an `eval()` block, which means that those dependencies are picked up by the topological scheduler and the resulting query plan is correct (verified with a debugger). That clause is also always true -- `$matched.end` is either `null` or not, so this should produce a correct answer with one row.

However, this query still produces no rows as output. I have verified that the `if/eval` part is again to blame, but this time it's not due to a bad query plan. 

Any thoughts on why this might be happening?

**Comment by luigidellaquila** [comment] 2017-02-16 11:35
Hi @obi1kenobi 

Well, this is strange, could you please try the following:

```
MATCH {
    class: Foo,
    as: foo
}.out('Foo_Start') {
    as: start
}, {
    class: Foo,
    as: foo
}.out('Foo_End') {
    optional: true,
    as: end
}, {
    class: Foo,
    as: foo
}.out('Foo_Center') {
    where: (
        (event_date >= $matched.start.event_date) AND 
        (($matched.end IS null) OR ($matched.end IS NOT null) OR ($matched.end IS NOT DEFINED)) AND
        (
            if(eval("(($matched.end IS null) OR (event_date <= $matched.end.event_date))"), 
               true,
               false
            ) = true
        )
    ),
    as: center
}
RETURN $matches
```

If you have a sample dataset to reproduce the issue, I can debug it quickly

Thanks

Luigi

**Comment by obi1kenobi** [comment] 2017-02-16 15:23
@luigidellaquila still no rows. I'm using the database created with the script at the very top of this thread, under "Steps to reproduce".

I verified that of `(($matched.end IS null) OR ($matched.end IS NOT null) OR ($matched.end IS NOT DEFINED))`, only the middle clause is true, and the others are false. That would mean that `(event_date <= $matched.end.event_date)` is false in the `eval`, which is definitely wrong based on the data.

Also -- I've never seen the `IS NOT DEFINED` operator, is it new? Any docs on it?

**Comment by luigidellaquila** [comment] 2017-02-16 15:41
Hi @obi1kenobi 

Ok, now it's much clearer to me, the eval() is not correctly evaluating the `$matched` variable.

The pattern in the queries is evaluated in the exact same order, it's not a matter of involved aliases, just the eval() gets a null when trying to evaluate the $matched variable, so the WHERE evaluates to false.

I'm checking how to fix it

Thanks

Luigi

**Comment by luigidellaquila** [comment] 2017-02-17 08:45
Hi @obi1kenobi 

I just pushed a fix on branch 2.2.x, now your last query works fine.
I'm keeping this issue open because the general problem with the `eval()` is not fixed yet

Thanks

Luigi

**Comment by obi1kenobi** [comment] 2017-02-17 15:32
@luigidellaquila looks good, thank you.

**Comment by obi1kenobi** [comment] 2017-02-17 16:28
Hey @luigidellaquila -- I just realized that 2.2.17 isn't out yet. Any chance the `eval()` fix you made above can make it into 2.2.17, or is it too late now?

**Comment by luigidellaquila** [comment] 2017-02-17 16:42
HI @obi1kenobi 

Actually 2.2.17 is out already, we are updating the website

Thanks

Luigi

**Comment by obi1kenobi** [comment] 2017-02-17 19:50
I'm looking forward to 2.2.18 then :) Thanks for the help!

**Comment by obi1kenobi** [comment] 2017-04-07 13:58
Hi @robfrank -- I think you may have accidentally closed this issue, when in fact @luigidellaquila and I were keeping it open since the general problem with the `eval()` is not fixed yet. The commit that is marked as resolving this issue simply enables a reliable but convoluted workaround.

**Comment by obi1kenobi** [comment] 2017-04-11 16:51
Hi @robfrank and @luigidellaquila! Just a reminder that this issue got accidentally closed, but shouldn't be -- per @luigidellaquila's post above: `I'm keeping this issue open because the general problem with the eval() is not fixed yet`.

**Comment by luigidellaquila** [comment] 2018-05-22 07:02
Hi @obi1kenobi 

I'm not sure, I have to check it. I'll try and let you know

Thanks

Luigi

**Comment by luigidellaquila** [comment] 2018-06-18 13:05
Hi @obi1kenobi 

Yes, the eval() function still has this problem, but please consider that `eval()` is no longer needed in v 3.0, as you can write complex math expressions in plain SQL

Thanks

Luigi

**Closed** 2021-08-05 14:10 UTC
