### ISSUE TITLE
Error when deleting a vertex property

### ISSUE THREAD

**Issue by adriancoca** [orientechnologies/orientdb#9830] opened 2022-06-22 07:42 UTC
## Expected behavior  
deleting a vertex property from orientdb studio

## Actual behavior  

PAYLOAD

DROP PROPERTY `WIDGET`.`tututrrriiry`

java.lang.NumberFormatException: For input string: \"999999999999\"

![image](https://user-images.githubusercontent.com/7643185/174972115-7c9cd646-2a9a-4d75-81a6-c03fefbc4c85.png)

LE: Also when trying to make a new edge.

![image](https://user-images.githubusercontent.com/7643185/174985183-72667cec-7a21-4b27-846f-65f30c4b7290.png)

**Comment by adriancoca** [comment] 2022-06-30 08:06
database seems to be broken 
Error: com.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database 'ztr_globaldes....'

Error: com.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database url=plocal:C:\orientdb-3.1.10\bin\..\databases/ztr_globalde...

Error: java.lang.NumberFormatException: For input string: "999999999999"

**Comment by tglman** [comment] 2022-06-30 08:59
Hi,

Can you manage to get some stack trace, for this error ? 

Bye

**Comment by adriancoca** [comment] 2022-06-30 09:27
Unfortunately the message above is the only thing that is shown when I try connect plocal:../databases/ztr ...   root password. If I try to connect from studio it fails and after that no databases is shown in list after refresh. Maybe a  remote to my pc or an archive with the database can help you? Thx.

**Comment by tglman** [comment] 2022-07-04 10:50
Hi,
Yes if you can share a archive of the database that I can use to reproduce the problem it would be very helpful.

Regards

**Comment by adriancoca** [comment] 2022-07-04 11:24
Can you provide me an email address where I can send you the archive ?

**Comment by tglman** [comment] 2022-07-07 11:07
Hi, you can try to send it to me `data@tglman.org` regards

**Comment by adriancoca** [comment] 2022-07-14 06:54
@tglman you managed to check the database I sent to you ?

**Comment by tglman** [comment] 2022-07-14 11:48
Hi,
Yes I saw the reason of this problem, in a integer property there is a max value that is "999999999" when OrientDB open the database and try to initialize metadata structures try to get a `int` value out of the string and fail.

So for now make sure that you have valid max and min values in the properties, we will try to add check to avoid that invalid values come into the database matadata.

**Comment by tglman** [comment] 2022-07-18 11:19
Hi,

the 3.1.19 just released should work fine in this case, allowing the database to open if if has invalid validation rules(backward comparability), and giving error when setting a rule that is not valid.

Closing this, re-open if you still experience the problem.

**Closed as completed by tglman** 2022-07-18 11:19 UTC
