### ISSUE TITLE
freeze lock for update

### ISSUE THREAD

**Issue by martingg88** [orientechnologies/orientdb#4206] opened 2015-05-22 02:30 UTC
@laa seem like it still lock when doing update/insert. here the thread dump for your debugging. In between we have some discussion at #4090

you can get the thread dump for your debugging.

https://drive.google.com/file/d/0B4HzIyaEAQ5WUDhoM2h4Sm56SDQ/view?usp=sharing

**Comment by laa** [comment] 2015-05-22 10:17
Do you have Skype so we may chat and dubeg or merey code to reproduce this issue ?

**Comment by martingg88** [comment] 2015-05-22 11:34
here is my skype ckgan2004@hotmail.com. what time you about want to do dis discussion?

**Comment by laa** [comment] 2015-05-22 11:35
what about now  ))

**Comment by martingg88** [comment] 2015-05-22 11:36
sorry.. i can't make it now...how about 2 hour later at 19:00+0800 malaysia time?

**Comment by laa** [comment] 2015-05-22 11:39
2 hours later is ok for me

**Comment by martingg88** [comment] 2015-05-22 11:40
ok...see u later..

**Comment by laa** [comment] 2015-05-22 11:42
I can not find your contact in Skype, could you connect to me lomakin_andrey .

**Comment by martingg88** [comment] 2015-05-22 11:42
sure..i will do it later...

**Comment by martingg88** [comment] 2015-05-28 15:32
@laa... as for last conversation over skype. are you able to reproduce this issue?

**Comment by laa** [comment] 2015-05-28 19:16
Hi, Sorry I am super busy by issue #4144 . Once I finish it I will be back
to this one .

**Comment by martingg88** [comment] 2015-05-29 02:26
sure. thanks

**Comment by laa** [comment] 2015-06-04 17:09
Hi, coudl you try this distribution https://www.dropbox.com/s/xs2w59sncv9ln4m/orientdb-community-2.1-SNAPSHOT-distribution.zip?dl=0 . Does deadlock still persist ?

**Comment by martingg88** [comment] 2015-06-05 04:35
i will try it today or tomorrow and let you know the result. thanks.

**Comment by laa** [comment] 2015-06-05 13:55
Thank you for your help !

**Comment by martingg88** [comment] 2015-06-06 18:52
I still facing the issue as follows after tested.
this should be the concurrent issue for update.
OrientDB.RequestError: Error on saving record #59:11062

**Comment by martingg88** [comment] 2015-06-06 18:53
I still facing the issue as follows after tested.

OrientDB.RequestError: Error on saving record #59:11062

**Comment by laa** [comment] 2015-06-08 10:10
Could you send me stack trace from server log for this error ?

**Comment by laa** [comment] 2015-06-08 10:12
Is it correct that there is no freeze now, but there is issue which you reported ?

**Comment by martingg88** [comment] 2015-06-08 11:11
1. this seems like another issue which relate to the following exception.
com.orientechnologies.orient.core.exception.ODatabaseException: Error on
saving record in cluster #56 [ONetworkProtocolBinary]


2. I can't see any freeze there since i had have this issue ever.

**Comment by laa** [comment] 2015-06-08 11:19
Did you see errors in server log, I have to have full stack trace to
resolve it.

On Mon, Jun 8, 2015 at 2:11 PM, martingg88 <notifications@github.com> wrote:

> 1. this seems like another issue which relate to the following exception.
> com.orientechnologies.orient.core.exception.ODatabaseException: Error on
> saving record in cluster #56 [ONetworkProtocolBinary]
>
>
> 2. I can't see any freeze there since i had have this issue ever.
>
> On Mon, Jun 8, 2015 at 6:13 PM, Andrey Lomakin <notifications@github.com>
> wrote:
>
> > Is it correct that there is no freeze now, but there is issue which you
> > reported ?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/orientechnologies/orientdb/issues/4206#issuecomment-109941625
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/4206#issuecomment-109952725>
> .
>



-- 
Best regards,
Andrey Lomakin.

**Comment by martingg88** [comment] 2015-06-08 16:20
i'm a bit confused. this is what i have from server.log. 

com.orientechnologies.orient.core.exception.ODatabaseException: Error on
saving record in cluster #56 [ONetworkProtocolBinary]

**Comment by martingg88** [comment] 2015-06-08 16:22
erm...what logging level should i set to have full stack?

 <entry name="log.console.level" value="info"/>

**Comment by laa** [comment] 2015-06-09 13:54
Sorry was busy to fix given issue.

**Comment by laa** [comment] 2015-06-09 13:58
Could you set property server.log.dumpClientExceptionFullStackTrace to true on sever configuration and set server.log.dumpClientExceptionLevel property value to the fine.

**Comment by martingg88** [comment] 2015-06-09 18:37
i have tried to set the following at orientdb-server-config.xml.

<entry name="server.log.dumpClientExceptionFullStackTrace" value="true" />
<entry name="server.log.dumpClientExceptionLevel" value="fine" />

But i do have following error when start the server.

[OServer]Error on reading protocol version for class com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary
java.lang.IllegalArgumentException: Bad level "fine"

**Comment by laa** [comment] 2015-06-12 07:49
I see and nothing into the log ? Could you do following then, could you do export/import and then use this distribution https://www.dropbox.com/s/xs2w59sncv9ln4m/orientdb-community-2.1-SNAPSHOT-distribution.zip?dl=0

**Comment by martingg88** [comment] 2015-06-12 13:34
well. it look better than ever before. But I still facing freeze update after encounter following error. 

com.orientechnologies.orient.core.exception.ODatabaseException: Impossible save a record during network serialization
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerCSVAbstract.linkToStream(ORecordSerializerCSVAbstract.java:132)
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerCSVAbstract.fieldToStream(ORecordSerializerCSVAbstract.java:364)
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerSchemaAware2CSV.toString(ORecordSerializerSchemaAware2CSV.java:506)
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerStringAbstract.toStream(ORecordSerializerStringAbstract.java:691)
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerSchemaAware2CSV.toStream(ORecordSerializerSchemaAware2CSV.java:268)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2212)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:668)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1818)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:150)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2454)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:144)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1709)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1700)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:87)
	at com.orientechnologies.orient.core.db.record.ridbag.embedded.OEmbeddedRidBag.serialize(OEmbeddedRidBag.java:372)
	at com.orientechnologies.orient.core.db.record.ridbag.ORidBag.toStream(ORidBag.java:266)
	at com.orientechnologies.orient.core.db.record.ridbag.ORidBag.toStream(ORidBag.java:273)
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerCSVAbstract.fieldToStream(ORecordSerializerCSVAbstract.java:556)
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerSchemaAware2CSV.toString(ORecordSerializerSchemaAware2CSV.java:506)
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerStringAbstract.toStream(ORecordSerializerStringAbstract.java:691)
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerSchemaAware2CSV.toStream(ORecordSerializerSchemaAware2CSV.java:268)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2212)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:668)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.getRecordBytes(OBinaryNetworkProtocolAbstract.java:422)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.writeRecord(OBinaryNetworkProtocolAbstract.java:437)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.writeIdentifiable(OBinaryNetworkProtocolAbstract.java:140)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1216)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:391)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:222)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:71)
{db=stream} Error on unmarshalling record #41:165 (com.orientechnologies.orient.core.exception.ODatabaseException: Impossible save a record during network serialization)
com.orientechnologies.orient.core.exception.ODatabaseException: Impossible save a record during network serialization
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerCSVAbstract.linkToStream(ORecordSerializerCSVAbstract.java:132)
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerCSVAbstract.fieldToStream(ORecordSerializerCSVAbstract.java:364)
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerSchemaAware2CSV.toString(ORecordSerializerSchemaAware2CSV.java:506)
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerStringAbstract.toStream(ORecordSerializerStringAbstract.java:691)
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerSchemaAware2CSV.toStream(ORecordSerializerSchemaAware2CSV.java:268)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2212)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:668)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeSaveRecord(ODatabaseDocumentTx.java:1818)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.saveRecord(OTransactionNoTx.java:150)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:2454)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.save(ODatabaseDocumentTx.java:144)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1709)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:1700)
	at com.orientechnologies.orient.core.record.impl.ODocument.save(ODocument.java:87)
	at com.orientechnologies.orient.core.db.record.ridbag.embedded.OEmbeddedRidBag.serialize(OEmbeddedRidBag.java:372)
	at com.orientechnologies.orient.core.db.record.ridbag.ORidBag.toStream(ORidBag.java:266)
	at com.orientechnologies.orient.core.db.record.ridbag.ORidBag.toStream(ORidBag.java:273)
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerCSVAbstract.fieldToStream(ORecordSerializerCSVAbstract.java:556)
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerSchemaAware2CSV.toString(ORecordSerializerSchemaAware2CSV.java:506)
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerStringAbstract.toStream(ORecordSerializerStringAbstract.java:691)
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerSchemaAware2CSV.toStream(ORecordSerializerSchemaAware2CSV.java:268)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2212)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:668)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.getRecordBytes(OBinaryNetworkProtocolAbstract.java:422)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.writeRecord(OBinaryNetworkProtocolAbstract.java:437)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.writeIdentifiable(OBinaryNetworkProtocolAbstract.java:140)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1216)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:391)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:222)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:71)

**Comment by laa** [comment] 2015-06-15 06:58
Well did you do export to JSON and import back, or you  upgraded jars in distribution ?

**Comment by martingg88** [comment] 2015-06-15 08:25
yes... i did export and import in json by using following method.

http://orientdb.com/docs/last/Export-and-Import.html

**Comment by laa** [comment] 2015-06-15 08:33
Ok, I see you use CSV it is not supported for an year, which JavaScript
driver do you use ?

**Comment by martingg88** [comment] 2015-06-15 11:45
sorry. i'm confused. Can you provide me the steps what should i need to do?

**Comment by laa** [comment] 2015-06-15 11:59
Is it correct that you use node.js for your application development, how do you connect to database ?

**Comment by martingg88** [comment] 2015-06-15 14:18
yes..i'm using node.js for development. Meanwhile i'm using the following driver to connect the database. I think this library is using binary protocol

https://github.com/codemix/oriento

**Comment by laa** [comment] 2015-06-16 17:17
No it is not. Main problem with your issue is that we can not reproduce it, may you send us database and code which you use for testing, and instruction how to run it, you may send them privately to a.lomakin@orientdb.com .We are close to release new version and we looking forward to include fix of your but into it.

**Comment by martingg88** [comment] 2015-06-17 10:35
@laa. i send you a test script to your private email. Please check it out and let me know if you have any issue to run the test script. 

1. you do not need to create a database as the test script will create the database itself for each test you run. 
2. this file will have two test scripts . 
 one for freeze update issue.  (update.js)
 one for transaction roll back issue.  (commit.js).

**Comment by martingg88** [comment] 2015-06-18 03:49
@laa i just open a discussion on the following link that is about to official orientdb node driver. 

https://github.com/orientechnologies/orientjs/issues/1

**Comment by laa** [comment] 2015-06-23 10:56
Hi I ran tests and saw exceptions (sorry for delay) in Lucene library.
Assigned to @maggiolo00 .

**Comment by martingg88** [comment] 2015-06-23 10:58
sure. thanks.

**Comment by maggiolo00** [comment] 2015-06-23 14:44
@martingg88 
i tried your test and the exceptions seems related to this one
https://github.com/orientechnologies/orientjs/issues/1
I thought it was resolved in 2.0.11 but is not. 
It is in 2.0.x so will be released in 2.0.12 and 2.1 GA

**Comment by martingg88** [comment] 2015-06-23 14:54
ok. thanks.

**Comment by lvca** [comment] 2015-06-28 19:18
So @maggiolo00 is this problem caused by the wrong way the Node.js driver sent the same connection-id even with multiple connections?

**Comment by maggiolo00** [comment] 2015-07-07 13:52
yeah the fix we did should avoid freezing

**Comment by lvca** [comment] 2015-07-15 17:31
@martingg88 Any chance to retest this?

**Comment by martingg88** [comment] 2015-07-15 17:43
r u sure @maggiolo00 have fixed the issue? he said will release fix version in  2.0.12 and 2.1 GA? isn't?

**Comment by lvca** [comment] 2015-07-15 21:34
It's already released in 2.0.12 and 2.1-rc5

**Comment by martingg88** [comment] 2015-07-16 13:36
ok..will try it as soon as possible

**Comment by martingg88** [comment] 2015-07-16 13:49
In between, if i  can't reply you in timely manner. You can ask @laa to test it as he have my test script for two cases (etc: concurrent update and transaction roll back issue). Thanks.

**Comment by martingg88** [comment] 2015-07-31 05:37
test script working fine for orientjs- 2.0.0 and orientdb-2.1-rc5 enterprise version. 

1. test run update 1000 record with lock mechanism in concurrent/parallel. 
    - passed without error.
    - it takes 2919ms to complete.  2919ms is acceptable performance to handle 1000 records?

**Comment by lvca** [comment] 2015-07-31 12:51
How you did insert those records?

**Comment by martingg88** [comment] 2015-08-01 06:51
can you get the test script from @laa. he have the test script for both update and commit in concurrent. 
from the test scripts, you should be able to see how i update the records. thanks.

**Comment by martingg88** [comment] 2015-10-01 15:26
any update?

**Comment by maggiolo00** [comment] 2016-02-02 16:04
@martingg88 

have you solved this?

**Comment by martingg88** [comment] 2016-02-03 06:24
You should check with your team members please.

**Comment by maggiolo00** [comment] 2016-05-16 14:06
@martingg88 

this should  been fixed
can you confirm that?

**Comment by maggiolo00** [comment] 2016-05-18 16:16
@martingg88 

i'm closing this. If you still have problem with this issue, you can reopen it

**Closed by maggiolo00** 2016-05-18 16:17 UTC
Labels: bug
