### ISSUE TITLE
Retool the automatic backup plugin to perform incremental backups

### ISSUE THREAD

**Issue by finid** [orientechnologies/orientdb#5150] opened 2015-10-19 07:38 UTC
When enabled, the  automatic backup plugin will make a full backup of all databases except the GratefulDeadConcert into a `backup` folder in OrientDB's `bin` directory. 

This issue is being used to request that the automatic backup plugin be capable of preforming incremental backups.

In addition, it would be good if the `backup` folder be created in the `databases` folder, or in the root of the OrientDB installation.

See [issue 5149](https://github.com/orientechnologies/orientdb/issues/5149#issuecomment-149124665).

**Comment by Ziink** [comment] 2015-10-19 16:19
Has been approved as a feature in [#5155](https://github.com/orientechnologies/orientdb/issues/5155)

**Comment by lvca** [comment] 2015-11-03 20:19
Ok, closing this because duplicate of #5155 (as also reported by @Ziink)

**Closed by lvca** 2015-11-03 20:19 UTC
