### ISSUE TITLE
Saving an embedded list as null prevents the list from being updated later using the Object API.

### ISSUE THREAD

**Issue by dalegarv** [orientechnologies/orientdb#7398] opened 2017-05-05 14:50 UTC
## Expected behavior  
I should be able to save an embedded list property as null and update it later with a non-empty list using the object API.

## Actual behavior  
When I try to update the object with a non-empty list it's staying as null.  This doesn't happen if I initially set it to an empty list instead.

## Steps to reproduce  
Create an object with a null embedded list reference and try to update it to an non-empty list using the object API.

**Comment by tglman** [comment] 2017-05-08 13:34
hi @dalegarv,

I did a small test case for reproduce it and it works correctly, here it is:
test:
```

  private ODatabaseObject db;

  @Before
  public void before() {
    db = new OObjectDatabaseTx("memory:test");
    db.create();
  }

  @After
  public void after() {
    db.drop();
  }

  @Test
  public void test() {
    db.getEntityManager().registerEntityClass(EmbedEntity.class);
    EmbedEntity entity = new EmbedEntity();
    entity.setEmbeddeds(null);
    EmbedEntity ent = db.save(entity);

    db.getLocalCache().clear();
    List<EmbedEntity> res = db.query(new OSQLSynchQuery<EmbedEntity>("select from EmbedEntity"));
    assertEquals(res.size(), 1);
    assertNull(res.get(0).getEmbeddeds());

  }
```
entity:
```
public class EmbedEntity {

  @Embedded
  private List<EmbeddedEntity> embeddeds;

  public List<EmbeddedEntity> getEmbeddeds() {
    return embeddeds;
  }

  public void setEmbeddeds(List<EmbeddedEntity> embeddeds) {
    this.embeddeds = embeddeds;
  }

}

public class EmbeddedEntity {
  private String some;

}
```

do you have any more detailed info on how to reproduce the case or a test case ?

Regards

**Comment by dalegarv** [comment] 2017-05-08 15:33
My apologies. I had some of the details confused with another problem, so I updated the title and description to be more accurate.  We've since switched from the Object API to the Document API, but I wanted to report the problem in case it affects other.

**Comment by lucafrosini** [comment] 2017-05-09 13:25
In general updating embeddedlist has some issues.  See 
https://github.com/orientechnologies/orientdb/issues/7354

**Comment by tglman** [comment] 2017-06-05 15:51
Hi all,

I'm going to close this, because it cannot be reproduced, anyway the other bugs are tracked in other issues.

Regards

**Closed by tglman** 2017-06-05 15:51 UTC
Labels: bug
