### ISSUE TITLE
java.lang.IllegalArgumentException: Cluster 1018 is null [ONetworkProtocolHttpDb]

### ISSUE THREAD

**Issue by ernestas-poskus** [orientechnologies/orientdb#5543] opened 2015-12-31 15:59 UTC
2015-12-31 18:56:58:876 SEVER Internal server error:
java.lang.IllegalArgumentException: Cluster 1018 is null [ONetworkProtocolHttpDb]

After DB restart this happens every time (only cluster ID is different). I have over 1000 clusters related to single class.

Tested with:
 - 2.1.8
 - 1.7.9

**Comment by luigidellaquila** [comment] 2016-01-04 07:53
Hi @ernestas-poskus 

it's not easy to replicate the problem, do you think you can share the db or some deterministic way to make the problem happen?

Thanks

Luigi

**Comment by ernestas-poskus** [comment] 2016-01-06 18:09
@luigidellaquila here is gzipped DB https://www.dropbox.com/s/3wljmqf9diavvpn/db.tgz?dl=0

**Comment by jaklec** [comment] 2016-01-20 12:27
We are also experiencing this problem.

It appeared after network problems followed by restarting the database. Unfortunately we were logging with too granular level when the problems first occurred, so I can't tell if the database was shutdown cleanly.

Listing the classes in the console shows there are no (0) records for the class where the cluster is null.

OrientDB version: 2.1.2

**Comment by ernestas-poskus** [comment] 2016-02-03 16:49
Hey @luigidellaquila any progress?

**Comment by luigidellaquila** [comment] 2016-02-04 10:08
Hi @ernestas-poskus 

sorry, I lost your db and it seems the Dropbox link is not available anymore, could you please share it again?
I'll check it as soon as you send it

Thanks

Luigi

**Comment by ernestas-poskus** [comment] 2016-02-06 05:01
@luigidellaquila 

Here it is https://www.dropbox.com/s/3wljmqf9diavvpn/db.tgz?dl=0

**Comment by luigidellaquila** [comment] 2016-02-08 11:36
Hi @ernestas-poskus 

ok, I could reproduce the problem. I fixed the db just removing the non-existing clusters from the class definition, eg.
```
ALTER CLASS wn REMOVECLUSTER 1478
```

Now the problem is to understand wow could it happen... I tried to add 2000 clusters to a class and drop them manually, I also killed the server while creating the clusters, but I was not able to reproduce this situation.

Could you please describe a bit how you are managing clusters? How are you creating and dropping them?

BTW, I see you are using clusters to represent high level concepts in your data model, while clusters should be used only as low level, storage related concepts. I suggest you to use subclasses instead

Thanks

Luigi

**Comment by ernestas-poskus** [comment] 2016-03-17 11:14
@luigidellaquila sorry was on vacation. 

I never drop clusters, OrientDB lives in Docker container and it happens every time I start container for example after PR shutdown.

I use clustering to split/assign clusters for corresponding servers.

**Comment by fortu-nato** [comment] 2016-05-11 02:56
Is there any progress on this?
I got this same problem when trying to update between 2.1.x versions in a non-distributed installation.

**Comment by tglman** [comment] 2016-06-22 16:41
hi @fortu-nato,

This is an issue create before and when you port the db to 2.1 it show you the error message, in case it show that error plese remove the cluster from the class as luigi specified: `ALTER CLASS TheClass REMOVECLUSTER 1478` with the newer version of the database this should not happen, as well if you do an export import procedure, the not existent clusters should be removed.

Hope this help to solve your case.

**Comment by lvca** [comment] 2016-08-27 19:18
Closing because no answer after months. In case please reopen/comment this.

**Closed by lvca** 2016-08-27 19:18 UTC
Labels: bug, waiting reply
