### ISSUE TITLE
concurrent addEdge function seems to corrupt the database.

### ISSUE THREAD

**Issue by jingjingbic** [orientechnologies/orientdb#5240] opened 2015-10-28 17:31 UTC
Hi OrientDB team,

I am seeing this in OrientDB 2.1.4 in Linux version. I have 2 concurrent threads running the following code to add a "ownedBy" edge from the same user node ( for example #16:1) to a new task node. The code is something like this:

void createTask(ODatabaseDocumentTx dbConn) 
{
OrientBaseGraph graph = new OrientGraph(this.db,false);
		graph.setAutoScaleEdgeType(true);
		graph.setEdgeContainerEmbedded2TreeThreshold(40);
		graph.setUseLightweightEdges(true);

ODocument taskDoc = new ODocument("task")
                  .fields("UUID", newTask.getExternalId().toString(),
					''creation", newTask.getCreationTime());
taskDoc = taskDoc.save();

ODocument userDoc = getRecordByAccountName("user1", "user");
			
String userUUID = userDoc.field(NdexClasses.ExternalObj_ID);

taskDoc = taskDoc.field("ownerUUID", userUUID).save();
			
OrientVertex taskV = graph.getVertex(taskDoc);
			
OrientVertex userV = this.graph.getVertex(userDoc.reload());
for	(int retry = 0;	retry <	maxRetries;	++retry)	{
    try	{
					taskV.addEdge("ownedBy", userV );
					break;
		} catch(ONeedRetryException	e)	{
					logger.warning("Retry creating task add edge.");
					taskV.reload();
					userV.reload();
		}
}
graph.commit();
}

The function is called in the same time from 2 different threads using 2 different connections from the connection pool. The second thread will throw an OConcurrentModificationException exception when calling taskV.addEdge("ownedBy", userV ) because the other thread modified the same userV record. This is expected, but the "out_ownedBy" field was still added to the record of taskV, even after I called taskV.reload(). So when the code run the retry, the taskV now has two identical values in the "out_ownedBy" field. The record of userV record has only on pointer to taskV vertex in its "in_ownedBy" field.  After the 2 threads are finished, the record for "user1" (id #16:1) has this list [#15:502, #15:503] in its "in_ownedBy" field. This is correct, but in the task record #15:503, I have [#16:1,#16:1] in the "out_ownedBy" field. I was expecting to see a single value #16:1 in the "out_ownedBy" field. Did I do anything wrong or this is a bug in OrientDB?

**Comment by maggiolo00** [comment] 2015-10-28 18:18
@jingjingbic can you isolate a test case to reproduce this behaviour?

**Comment by lvca** [comment] 2016-05-12 07:18
Closing because not reproducible

**Closed by lvca** 2016-05-12 07:18 UTC
Labels: bug
