### ISSUE TITLE
Abnormal memory consumption with 2.2.x and IBM WebSphere 8.5

### ISSUE THREAD

**Issue by fredfortier** [orientechnologies/orientdb#6498] opened 2016-08-02 17:01 UTC
## OrientDB Version, operating system, or hardware.
- v2.2.5

## Operating System
- [ ] Linux
- [ ] MacOSX
- [x] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
I am using OrientDB in embedded distributed mode with only one node. Currently, the reason for using the distributed mode is to connect with plocal and remote concurrently.

In the Hazelcast config, I am using tcp/ip instead of multicast. All other config parameters are basically the default distributed config.

I am using a document database primarily through the Java Object API.

After upgrading from 2.1.6 to 2.2.5, I noticed that the memory usage of Java process corresponding to the WAS server containing my embedded app kept growing (which typically signifies a memory leak). 

I generated a heap dump and analyzed it. The results looked "normal" but the heap size was just a fraction of the memory used by the Java process. I see that 2.2.x uses "direct memory" which, by deduction, must relate to the issue. 

Have you done any testing with WebSphere? Do you have any idea of what might be causing the behavior?

For now, I downgraded to 2.1.20 which seems to cure the side-effects observed following the upgrade, including abnormal memory consumption.

**Comment by lvca** [comment] 2016-08-02 17:32
I don't know how WebSphere counts the RAM, but I think this is not a problem as far as it's not heap. Did you experience any problem with 2.2?

**Comment by laa** [comment] 2016-08-02 17:49
@fredfortier, first of all, let's check that there is a  memory leak. What RAM size do you have, what is  your DB size and what was memory consumption when you noticed that memory was consumed more than you expected ?

**Comment by fredfortier** [comment] 2016-08-02 18:04
I do not have experience with other Java EE applications using native memory instead of heap. I am only aware of memory analysis tools for heap dumps, not for the native memory.  Unfortunately, even if the observer behavior were considered normal, WebSphere administrators would take issue with an application using several times the memory figure allocated to heap.

I could see the memory grow on the Java process corresponding to the JVM in the Windows Task Manager, not using some WebSphere tools. I let the memory grow to 5GB before pulling the plug. The db usage volume was minimal although the few records affected were relatively large (~1MB). The database size was small (~2MB). I was basically adding, reading and deleting a single record. The heap size was 1024MB. The physical memory available on the server was approximately 5GB.

Now, I did open issue #6493 which could well be related. Since deleting a record results in error, I suppose that it could factor in that record being preserved in memory.

**Comment by laa** [comment] 2016-08-02 18:19
@fredfortier and that is completely reproducible, is not it ? I mean if I will install WebSphere and your app I will see the same result. Is it correct ?

**Comment by fredfortier** [comment] 2016-08-02 18:24
No unfortunately, my app is not easily portable in that it is an extension to an "evolved" (aka bloated) IBM framework. You won't be able to use it as-is in isolation. I did attach my exact configuration to issue #6493.

**Comment by laa** [comment] 2016-08-02 18:44
Do not think that configuration will help. But may we create debug session to fix your issue when all participants will have free time slots ?

**Comment by fredfortier** [comment] 2016-08-02 19:25
Yes, that could work. Please let me know when you guys are available. I am working during business hours on Eastern Standard Time.

**Comment by taburet** [comment] 2016-08-05 08:11
Hi @fredfortier! We have time zone difference of 12 hours, so debugging session will be our last resort :)

Let's confirm the problem with the direct memory first. Could you please inspect the direct memory usage stats in VisualVM's JMX console as described here https://blogs.oracle.com/alanb/entry/monitoring_direct_buffers. You may need to install VisualVM's JMX plugin before that.

Also, if you don't mind, I may create a customised 2.2.x version with a detailed logging about direct memory allocations.

**Comment by taburet** [comment] 2016-08-11 06:46
@fredfortier, do you have any updates? Could you please also inspect the com.orientechnologies.common.directmemory.OByteBufferPoolMXBean JMX bean? It provides information about OrienDB's direct memory allocations.

**Comment by taburet** [comment] 2016-08-11 14:30
Leak detection was pushed to the 2.2.x branch, it will emit an error message to the log, if a leak is detected, the message is prefixed with the `DIRECT-TRACK:` string. You may build it from the 2.2.x branch or wait for 2.2.7 release, it will be there.

**Comment by laa** [comment] 2016-08-11 16:21
@fredfortier in order to switch on leak detection you need to provide follwoing system property ```-Dmemory.directMemory.trackMode=true```

**Comment by fredfortier** [comment] 2016-08-11 16:59
@taburet and @laa , I will try this as soon as I can.

**Comment by lvca** [comment] 2016-08-27 19:32
Closing because no answer after a while. In case please reopen/comment this.

**Closed by lvca** 2016-08-27 19:32 UTC
Labels: bug, storage team, waiting reply
