### ISSUE TITLE
Async and nonblocking queries leak connections when upgrading from 2.1.17 to 2.2.14

### ISSUE THREAD

**Issue by temilmg** [orientechnologies/orientdb#7045] opened 2016-12-27 11:29 UTC
## OrientDB Version, operating system, or hardware.
- v2.2.14

## Operating System
- [ ] Linux

## Expected behavior and actual behavior

Orientdb is leaking connections when upgrading from 2.1.17 to 2.2.14.
In 2.1.17 we were using Async queries and there was no problem with concurrent connections
after upgrading to 2.2.13 and  2.2.14 the application becomes unresponsive after less than an hour. 
Please note we are shutting all connections after use with finally {graph.shutdown();} and this was all working perfectly in 2.1.17. The same thing is happening when using non-blocking queries!

This is definitely a show stopper and prevents us from upgrading to 2.2.x

When looking at the orientdb logs at first its empty, even though its not possible to connect to the db, then when trying to connect with orientdb studio below warnings show up.  It seems like it has reached max connections long before its actually showing the warning in the log file, the first warning starts with current=4984 which seems odd. The connections are not released again and the db has to be restarted before it will accept new connections.

2016-12-27 09:20:18:166 WARNI Reached maximum number of concurrent connections (max=1000, current=4984), reject incoming connection from /109.53.171.60:58086 [OServerNetworkListener]
2016-12-27 09:20:18:268 WARNI Reached maximum number of concurrent connections (max=1000, current=4984), reject incoming connection from /109.53.171.60:58087 [OServerNetworkListener]
2016-12-27 09:20:18:371 WARNI Reached maximum number of concurrent connections (max=1000, current=4984), reject incoming connection from /109.53.171.60:58088 [OServerNetworkListener]
2016-12-27 09:20:19:612 WARNI Reached maximum number of concurrent connections (max=1000, current=4984), reject incoming connection from /109.53.171.60:58093 [OServerNetworkListener]
2016-12-27 09:20:19:714 WARNI Reached maximum number of concurrent connections (max=1000, current=4984), reject incoming connection from /109.53.171.60:58092 [OServerNetworkListener]
2016-12-27 09:20:19:962 WARNI Reached maximum number of concurrent connections (max=1000, current=4984), reject incoming connection from /109.53.171.60:58094 [OServerNetworkListener]
2016-12-27 09:20:25:202 WARNI Reached maximum number of concurrent connections (max=1000, current=4984), reject incoming connection from /109.53.171.60:58109 [OServerNetworkListener]
2016-12-27 09:20:55:596 WARNI Reached maximum number of concurrent connections (max=1000, current=4992), reject incoming connection from /109.53.171.60:58170 [OServerNetworkListener]

## Steps to reproduce the problem
Use async or non blocking queries

**Comment by leosimoesp** [comment] 2017-01-04 16:24
I've the same problem. 

http://stackoverflow.com/questions/41465470/orientdb-dosent-close-tcp-connections

**Comment by tglman** [comment] 2017-01-04 17:18
hi @leosimoesp,

It seems you published your user and password online.

For the problem it seems you both rely on the pool, can you make sure that you acquire and release the session from the same thread, and in case can you try to do a test without the pool ? so we can quick determine if the problem is in the pool.

I'll double check the pools as well.

Bye

**Comment by leosimoesp** [comment] 2017-01-04 17:30
No, it's a fake username and password. 
I've tried many different test using pool and with ODatabaseDocumentTx. Nothing works. The concurrent conections are increasing and aplications crasches.

The log error is:

WARNI Reached maximum number of concurrent connections (max=1000, current=2136), reject incoming connection from /152.250.203.168:54289 [OServerNetworkListener]

**Comment by temilmg** [comment] 2017-01-04 23:35
hi @tglman,
In 2.1.17 I was not using the pool. When I first upgraded to 2.2.13 I was not using a pool either and I saw the same connection problem as I see now when using the pool in 2.2.13-14, so Im thinking maybe its not the pool. 

I did a little experimentation I made a small web app using vert.x (http://vertx.io/)
I ran an async query inside a for loop 1000 times (see below), I was making sure to close the connection every time. When the request is done the db becomes unresponsive (it get the connection problem)
I should say I am using remote mode.
I did a little monitoring of the objects created. It creates lots of OStorageRemoteSession and OStorageRemoteNodeSession objects. (8000 and 1000 objects)

![profilenb](https://cloud.githubusercontent.com/assets/3005511/21662918/22159cb6-d2dd-11e6-845c-279861e0a770.png)

for(int i = 0; i < 1000; i++) {
        OrientGraphFactory graphFactory = new OrientGraphFactory(DBUtil.CONNECTION_URL + "test2", DBUtil.USER, DBUtil.PASSWORD);
        OrientGraph graph = graphFactory.getTx();

        try {

            String query = "select from data limit 1";

            graph.command(new OSQLAsynchQuery<Vertex>(query,
                    new OCommandResultListener() {

                int resultCount = 0;

                @Override
                public boolean result(Object iRecord) {

                    resultCount++;
                    ODocument oDoc = (ODocument) iRecord;
                    System.out.println("TEST=" + oDoc.toJSON(""));
                    return resultCount < 1;
                }
                @Override
                public void end() {
                }
                public Object getResult() {
                    return null;
                }
            }
            )).execute();

        } catch (Exception e) {

            e.printStackTrace();

        } finally {
            graphFactory.close();
            if (graph != null) {
                graph.shutdown();
            }
        }
}

I dont know if you can use any of this information but I hope its helpful!

**Comment by temilmg** [comment] 2017-01-05 18:56
I tested the code above against 2.1.17 and 2.2.13 here it only fails against 2.2.13
Then I tested above code but replacing the OrientGraphFactory code part with OrientGraph graph = new OrientGraph(DBUtil.CONNECTION_URL + "test2", DBUtil.USER, DBUtil.PASSWORD);
In this case both 2.1.17 and 2.2.13 work. 
So it seems somewhere between 2.1.17 and 2.2.13 OrientGraphFactory changed so its not safe to call it more times (at least not a 1000 times :-). 

There is the following problem:
If we have more than 1000 accounts connecting to different databases there will be a connection problem.
In our app using 2.2.13 we are now using below code to connect to many different accounts
graphFactory = new OrientGraphFactory(DBUtil.CONNECTION_URL + account, DBUtil.USER, DBUtil.PASSWORD).setupPool(10, 100); 

If you still need a vert.x test project let me know and I will try to get it for you tomorrow!

**Comment by tglman** [comment] 2017-01-06 17:44
hi @temilmg,

Thanks for the check, i was suspecting about issue in the OrientGraphFactory, yes the test project would be very useful still.

Bye

**Comment by temilmg** [comment] 2017-01-07 13:04
Ok I have attached a simple vertx maven project that  runs the above code. 
For running the server, change db connection to your own, run the main method and then make a request to localhost:8890/service/test
[OrientGraphFactory.zip](https://github.com/orientechnologies/orientdb/files/691491/OrientGraphFactory.zip)

**Comment by leosimoesp** [comment] 2017-01-09 15:49
Hi @tglman,

I created a play scala project to test. There is README file with instructions into zip file.
I hope it helps.
Bye,

[play-scala-orientdb.zip](https://github.com/orientechnologies/orientdb/files/693875/play-scala-orientdb.zip)

**Comment by tglman** [comment] 2017-01-09 16:34
Thank You both of you, i'll come back to you soon with some  answers

**Comment by tglman** [comment] 2017-01-10 16:09
hi all,

@temilmg I couldn't reproduce the problem you have in 2.2.14, this can be due to some fix on async query we did on that specific release, can you try 2.2.14 ?

@leosimoesp in your test i saw that you use `val p = new OPartitionedDatabasePoolFactory()` but you don't close it, you need to close also that.

Just to say, if you get and drop the pools each request is not worth use them, just use `new OrientGraph(..)` or `new  ODatabaseDocumentTx()`, the pools are good only if are shared cross multiple multithread executions.

Hope this help

**Comment by temilmg** [comment] 2017-01-10 17:58
Hi @tglman ,
I am testing it on db v 2.2.14 and client v 2.2.14 maybe I should tell you how i test it.
I can consistently reproduce it like this:
I make the request to localhost:8890/service/test
It runs the loop and finishes just fine. Then when I open a new tab and try to connect to the database with studio its completely frozen and when I look in the log i get WARNI Reached maximum number of concurrent connections (max=1000, current=1000), reject incoming connection from ...
If I put the requestfactory outside the loop it works fine (but that case wont simulate having more than 1000 accounts).
Probably whats confusing you is that you can run localhost:8890/service/test multiple times without a problem, at least its confusing me! Threading?!
 
If i request:
localhost:8890/service/test two times one after the other and then open a new tab with studio
then the log shows 
 WARNI Reached maximum number of concurrent connections (max=1000, current=2000), reject incoming connection from ....
Funny thing here is that it starts from current=2000 it doesnt show any warnings from 1000-2000

I hope this will help you reproduce it!

**Comment by temilmg** [comment] 2017-01-15 13:27
I should clarify that i left out the graphFactory.close() in the above failed test in order to simulate that I have more than 1000 accounts (probably not the best simulation because its connecting to the same account 1000 times :-) ).
If I put in the graphFactory.close() it does work as long as its after the graph.shutdown().

**Closed** 2020-05-26 19:19 UTC
Labels: bug
