### ISSUE TITLE
Proposal: Use gRPC for the binary protocol

### ISSUE THREAD

**Issue by dennwc** [orientechnologies/orientdb#5119] opened 2015-10-14 12:16 UTC
#### Preface

[gRPC](http://www.grpc.io/) is a official extension of protobuf. It uses flow control from [HTTP2](https://http2.github.io/) to implement RPC with protobufs as a message serialization format.

In fact, this proposal is a variation of [#3240](https://github.com/orientechnologies/orientdb/issues/3240) with a few key differences.

I tried to make it as short as possible, but it is a large topic to discuss. If you have any questions on one of the statements, feel free to ask for a full description or context.
#### Proposal

Use gRPC as an alternative/experimental protocol listener for OrientDB 2.x. There is not so much effort needed to implement it. There is also no need to replace current binary protocol entirely. Current binary protocol may be dropped later in 3.x branch, for example, if gRPC will prove the effort. I believe it definitely will.
#### Problems with current protocol
- It's tricky to implement binary protocol client for a new language.
- Have to write everything from scratch: flow control, serialization, pooling.
- Wrong protocol spec/documentation.
- Protocol change may break existing implementations.
- Hard to track protocol changes.

All these problems were already described [here](https://github.com/codemix/orientdb-protobufs).

I will assume, that all of this is enough, to state that OrientDB needs some other protocol implementation.
#### Why use protobuf?
- Industry standard.
- Extendable.
- Nearly any language have a library for it.
- Declarative syntax for protocol (acts as a spec).
- Generated code is efficient for each language (thanks to large number of contributors).

All the benefits were already described [here](https://github.com/codemix/orientdb-protobufs).

But switching from current protocol serialization format to protobuf will solve only a half of the problem. It may require a huge effort to implement protobuf listener, as code from current protocol cannot be reused. So, we'll have another custom protocol flow implementation which must be implemented for every language. This will not happen anytime soon, I believe.
#### Why use gRPC?

gRPC uses new [HTTP2](https://http2.github.io/) standard for a reliable request-response flow control. HTTP2 is a binary protocol. It allows to create any number of request-response streams inside one HTTP2 connection. Each stream is being split into frames, so concurrent requests will not interfere with each other. That's it - one connection can be used for any number of concurrent client requests. gRPC will automatically take care of connection failures.
On a second layer, there is a protobuf-defined messages that are being passed over HTTP2. So, we have all messages described in a `.proto` files, like this:

``` protobuf
message RID {
    sint64 clusterId = 1;
    sint64 clusterPos = 2;
}

message ReadRecordMetadataRequest {
    UserInfo info = 1;
    RID rid = 2;
}
```

We could generate message encoders/decoders from that files for any language using `protoc` (protobuf compiler)... But we can omit this step and let gRPC to generate entire client/server code that uses these messages for communication. Protoc starting from version 3 supports gRPC services definition:

``` protobuf
service Storage {
    rpc ReadRecordMetadata(ReadRecordMetadataRequest) returns (ReadRecordMetadataResponse);
}
```

We can describe whole remote storage API using this format. Then, we need a single command to generate code for any language, that gRPC supports (C, C++, Java, Go, Node.js, Python, Ruby, Obj-C, PHP, C#).

But we will lose control over transport layer, right? Things like [streamed result sets](https://github.com/orientechnologies/orientdb/commit/3b7bb8c4c8eba775f22d0111a2bdcc3c41352c33) will not be supported at all? Wrong. In gRPC you can describe an API which relies on results and/or arguments streams:

``` protobuf
service Storage {
    rpc ReadRecordMetadata(ReadRecordMetadataRequest) returns (stream ReadRecordMetadataResponse);
}
```

Code, that will be generated from this description will define `ReadRecordMetadata` API function that accepts one  `ReadRecordMetadataRequest` object and returns back a stream of `ReadRecordMetadataResponse` objects.

As an additional feature, gRPC defines an authorization scheme with several builtin implementations: insecure (disabled), TLS certs, OAuth2. Optionally you can easily implement a new one, or just use insecure and implement auth on RPC level (as current binary protocol does).

The question is: why not to use such powerful tool?
#### Benefits
- Standard protocol: protobuf over HTTP2.
- API is described in `.proto` file, which can be used to generate both server and client implementations with that API.
- Whole API can be described, including types, errors, enums, streaming, etc.
- Easy to maintain for both server and client libs.
- Framing: connections will not block on a large request/responses.
- Streams: any number of request/responses over one connection. No need for pooling (HTTP2 will use pooling automatically if it is necessary).
- Built in authentication support (TLS, OAuth2, bypass, custom). Can be managed on API level as well.
- Protocol implementation is supported by a large community.
#### Drawbacks
- Requires some effort to integrate (but a much less, than integration of protobuf itself!).
- Performance can be affected on serialization level (may be neglectible, because user applications will run much faster due to streaming and framing of requests: one request will not affect others; also protobuf is pretty fast itself).
- @phpnode also stated that code generation can be a drawback. But it allows to generate a faster code for some languages. 
- Anything else?
#### Implementation

I already described a half of binary protocol API in a terms of gRPC. I even implemented a gRPC-to-BinaryProtocol proxy to test the spec. But I have no experience in Java to fill PR with actual integration. Also there are a few questions with protocol, which I want to discuss, if you would like the idea in overall. For short, there is a few options:
1. Just describe BinaryProtocol API in gRPC. Use authentication on API level (`Connect` and `OpenDatabase`). Requests have no sessionId, as it is managed by HTTP2. Need to pass token to every request for client identification. API is not so convenient, but has a little effort for integration.
2. Optimize API for gRPC. Use native auth scheme (may implement some custom module for OrientDB tokens). Requests without tokens and sessionId. API is convenient, but requires some additional effort to integrate with OrientDB server.

Also I want to point, that were is no need to dispatch requests/responses in a manner described in [previous proposal](http://codemix.github.io/orientdb-protobufs/). We can just describe API and all the types that it accepts and returns and let gRPC to dispatch them to appropriate handlers.

Pinging @phpnode as he might be interested in this change and @tglman as it seems that he is responsible for network stuff.

Waiting to hear what do you think about it :)

**Comment by laa** [comment] 2015-10-14 12:37
Hi Denis ,
I think you speak Russian fluently ? Could you connect with me to the Skype
lomakin_andrey . So we will discuss this topic .

**Comment by a-unite** [comment] 2015-10-14 14:21
+1 for standards based binary protocol implementation and another chance to deliver drivers robustness.

**Comment by mahtuag** [comment] 2015-12-22 16:22
@dennwc Wow! You said the exact same thing I wanted to say.

Let me add a few of my own points.

## Why gRPC, HTTP/2 and Protocol Buffers

### HTTP/2 is the Future

HTTP/2 clients are coming in all languages' standard libraries. Java 9 and Go 1.6 are examples where it is there by default. Until then great reference implementations exist.

### gRPC is just HTTP/2 and pprotobuf3

gRPC is just HTTP/2 with static routing (easy to parse) and Protocol Buffers for serialization. It is as simple as it sounds and while not very well documented (until it hits 1.0) it should not be very hard to figure out how to write a client in a language that isn't currently supported, like Rust.

### Autogenerated POJOs

Protocol Buffers autogenerate POJOs (or the equivalent in non-Java language). Less human efforts and errors.

### Ubiquity of Protocol Buffers

Protocol Buffers are available in nearly every language. The C binding can be (and has been) wrapped by almost every language which supports C modules.

### Zero LOC Clients for gRPC

gRPC is available in 10 languages where the effort to write client code is 0 lines of code. Just a few build-time automations can publish these clients to appropriate repositories or the users can generate them by themselves.

### On-wire Efficiency

Protocol Buffers is extremely efficient on-wire. It omits serializing fields w/ default values (0 for numbers). I use an enum for error code which defaults to 0 for success thus in non-error cases the payload is ultra light!

### HTTP/2 Goodies

HTTP/2 is fully binary and supports 2-way data streaming and multiplexing multiple connections. One connection per backend server instance is enough.

This has added benefit of bringing server-push feature to all languages instead of just Java and Node.js. (I prefer Go and I feel left out right now).

Also note that since HTTP/2 is supported in latest Firefox and Chrome and there is a JavaScript Protocol Buffers plugin coming soon, you can access OrientDB directly from the browser. I see this as being a direction the database could take in the future as a self-hosted Firebase alternative.

### Add Fields without breaking old clients

Protocol Buffers is easy to use as a platform where structures can have new fields added to them without breaking backwards compatibility. This is quintessential for a fast growing project like OrientDB.

### Huge Money Savings!

Money saved is money earned. Time saved is features earned.

Time saved working on binary protocol and client drivers can be spent improving database performance and adding new features.

## The Starting Point

What we do now to begin with is to implement the client binary protocol definition in a single .proto file and share it with everyone to get an opinion. Once the protocol is finalized (and possibly with some review help from the gRPC Java team @ Google) we can quickly generate the server.

*PS: I am willing to help out make the migration. Stereotypical of an opensource project, I am not a very good Java developer since it has been a while since I last used it. I am also not very familiar with OrientDB but this should be fun to implement!*

@lvca: Could you share some good starting point for a quick developer setup where I can try to grok the OrientDB codebase and see if this is within my abilities ?

**Comment by dennwc** [comment] 2015-12-22 17:22
@mahtuag Good point! We already started experimenting on PB with @laa. You can check serialization implementation in [protobuf](https://github.com/orientechnologies/orientdb/tree/protobuf) branch. Also, feel free to comment or propose features for [gRPC service definition](https://github.com/dennwc/orientdb-protobuf/tree/master/src/main/java). It was the first draft and I haven't finished it yet, but I will continue it after vacation.

**Comment by mahtuag** [comment] 2015-12-22 17:29
@dennwc Thanks! I still need a good way to setup OrientDB itself for development though. Any docs leading to that path ? Like recommended IDE setup, debug tools, etc ?

**Comment by dennwc** [comment] 2015-12-22 17:51
@mahtuag I'm also a Go developer, so I have nearly nothing to suggest. At least I can tell that IntelliJ IDEA creates project for OrientDB pretty easily. But you may have to resolve few dependencies by hand.
If you want more details, it would be better to switch to PM (den.nwc in Skype, or you may ping me in Gophers Slack also).

**Comment by smolinari** [comment] 2015-12-23 04:50
If this proposal, if carried out, would get a more stable, fun to support and performant interface into ODB, so the 3rd party driver support can be considerably improved, I am all for it!

:+1: 

Scott

**Comment by mindplay-dk** [comment] 2015-12-31 00:15
:+1: this sounds brilliant :-)

**Comment by smolinari** [comment] 2015-12-31 05:15
@luigidellaquila - one more. :smiley: 

Scott

**Comment by zinuga** [comment] 2016-05-27 21:46
are you guys using gRPC now?

**Comment by smolinari** [comment] 2016-05-28 03:11
Nope. If you look through the issue, you can see it is slated for 3.0. 

Maybe @lvca could make a statement about gRPC actually being implemented or not. I think, with my limited knowledge, that it would be a very nice change to look forward to in 3.0. 

Saying that, I also understand such a decision's wide-reaching implications. Namely, that all the current language drivers would be rendered useless, if gRPC were to be implemented. So, it is a very tough decision. Maybe, if the decision is made early enough and made public, some external devs could also jump in and help? (that was a question for the community :smile: ) 

Scott

**Comment by gzsombor** [comment] 2016-06-17 11:01
If the new protocol could be implemented independently from the current one - so the server could use both, concurrently, then the upgrade will be smooth, and clients can be independently upgraded to the new one, without breaking everything. So the obvious problems could be eliminated - maybe there are other problems with this solution, which I can't see

**Comment by smolinari** [comment] 2016-09-22 06:38
Hey @lvca, 

I'm going to ask first, but 

1. Are you still contemplating rebuilding the binary protocol interface with gRPC?
2. If yes, would you like me to put up an OEP for this too?

I'd be really glad too. 😄 

Scott

**Comment by smolinari** [comment] 2016-09-27 10:58
@lvca - friendly ping and bump. :smile: 

Scott

**Comment by tglman** [comment] 2016-09-27 14:18
Hi,

for the binary protocol so far i've been the responsible for it, and the last threshold to replace it with a different solution.

Let me make a few points

Pro:
- Have a new implementation on something ~standard will speedup the development of new drivers, and will improve the documentation overall.
- A new implementation may have less design bugs because we alredy know what we need.
- We may earn improvements for free from the thirdy party tools evolutions.

Cons:

- We will have 3 implementation to maintains (http,binary,gRPC), also if we declare deprecate the old binary we need to maintain it for at least one more major (all 3.x)
- We need to rewrite (almost from scratch) most of the clients, or in any case maintain the old clients and new clients.
- We have done already few tests on protobuf ecc, and they are not going to outperform our raw implmentation, so we will decrease perfomance overall


In any case we are very happy to welcome contribution from the community, but each peace we add to the project have a cost on maintenace that often is not done by the community ;).

Alternative solution:
We are going to try to stabilize the binary protocol in 3.0 and improve the documentation, I've already a development roadmap (not yet made public).

On Long term we need to improve the support on http, including http 2.0 and additional way to serialize request and response (Not only Json), this could include also the support of protobuf, that in this way will replicate the stack of gRPC.

So in future people could use (as some is already doing) our http protocol as a replacement in lighter clients of the binary protocol, keeping the number of interface that orient expone to still 2 (http,binary).

So as explained IMHO gRPC at this momemnt of the project is not a good choice.

Bye

**Comment by smolinari** [comment] 2016-09-27 15:13
Thanks for the explanation @tglman. 

I am not the expert, but from what I understand of gRPC, maintenance of the client side drivers would be relatively easy. It is basically a matter of a simple console command to generate the client code. Or am I misunderstanding how gRPC works or what is actually necessary?

And out of curiosity, how much worse did protobuf perform? 5%, 10%, 25%? 

Scott

**Comment by tglman** [comment] 2016-09-27 15:33
hi @smolinari,

From my experience there is not just the cost of the writing the code of the messages, that is usually the 30-40% of the bootstrap cost and 10-20% of maintance cost, there is as well a cost to provide a meaningful api for the environment (see nodejs callbacks programming style) and hide implementation details, like each record has a version that you should not change, you need to keep a sessionId and a token for each session ecc, sometime we do expose this details but is usually troubling for the evolution+compatibility of the protocol.

For the specific case of protobuff we did a POC for replace the record serialization with protobuf, protobuff was 5% faster on cpu using a custom implementation and not generated code (not sure is a good practice) and it was using ~30% of more space.

Bye

**Comment by dennwc** [comment] 2016-09-27 15:35
@tglman Thanks for your response, I thought the idea of this proposal was abandoned long ago.

I want to add a few things regarding cons:

* Binary protocol would be maintained in it's current state for 3.x in any case, thus it should not be a problem. Especially if it will be in freezed state.

* As one of driver developers, I really can't wait to see old binary protocol deprecated, so I can mark the old driver deprecated as well and write a new clean implementation at last :) Also, since old binary protocol will be maintained for some time, this, again, should not be a problem for existing drivers - they can still use an old one for a long time. Further, code for gRPC can be generated with one simple command, which will handle all the connection-related stuff, so the "rewrite" will only touch a connection layer (assuming document serialization is the same).

* The original proposal was intended to replace whole serialization format to protobufs, but as I can see this will not happen anytime soon. A new proposal would be: replace the connection layer and commands handling with protobufs and leave document serialization as-is. This might be a good first step toward clean API surface. Maybe after some time protobufs serialization would also be contributed by someone :)

Regarding alternative solution of stabilizing protocol and docs, this would be a one-time fix and then we might expect some other incompatible changes. Protobufs were designed to be backward-compatible, thus it would be easier for developers to track changes to protocol and update drivers accordingly. This will not be that easy with custom protocol. Things will break, devs will feel a lack of docs and OrientDB devs will have to update this docs, as a separate maintenance cost. Does it worth it? You may have a one command for all this.

Raw HTTP2 will not going to be a 1-to-1 replacement. gRPC declares a way to send streams from both client and server, thus live queries and results streams will benefit from this. Also it declares a way to handle authentication, connections, retrials and so on. With a proposed H1 -> H2 upgrade this will turn out to be just another custom protocol layer on top of H2 with lack of docs ;)

Worth to mention, gRPC supports a way to generate REST-compatible APIs (OpenAPI/Swagger) from service definitions. Thus it can one protocol (gRPC) and a REST reflection of it.

**Comment by mindplay-dk** [comment] 2016-10-25 06:50
Here's yet another option for encoding:

https://github.com/arangodb/velocypack

This one was designed for another document database, and has features such as packing common keys in large sets, and a compression protocol that is simpler and faster than gz - it may share some goals and requirements with Orient. Worth a look maybe, if you're not happy with any of the other options.

**Comment by smolinari** [comment] 2016-11-30 07:11
Not sure if this is relevant, but I just learned that gRPC got a huge performance boost in their June update. They went from approximately 350K streaming messages/ second @32 cores (both client and server) to 2M. Their goal, which they are working on currently and should be done by the end of the year, is to get to 100K streaming messages per core per second or 3.2M @32 cores. 

I am not sure how that relates to ODB's performance on API throughput, but those numbers, and the fact Google itself is constantly working on this, are pretty compelling things to know. Knowing that and knowing what the protobuf format actually means in terms of API maintainability and flexibility, one must admit, it is a great technology. Throw on top of all that Kubernetes with Docker container management, which all work hand in hand, and we're talking some really cool stuff.   

Again, I am not sure how good or efficient or well fit it is for ODB's purposes, so I am a bad judge for that. I just understand the advantages of gRPC as an API system and they are really intriguing. 

One other note, protobuf 3 also supports JSON structures too, which might not have been in the equation, when Arango built Velocypack (Protobuf 3 just came out in July). The information Arango provides about Velocypack is also quite interesting. 

One things is for sure though, Velocypack doesn't even come close to the portability given through Protobuf and especially gRPC (supports 8 languages currently) . From a personal perspective and if I at all had anything to say about ODB's direction, which I obviously don't, I'd just be very wary to implement any technology made by a pure competitor. That is just my opinion. 😄  

Scott

**Comment by jpstrikesback** [comment] 2017-04-18 18:59
Here is an interesting contender... https://capnproto.org/

**Comment by lvca** [comment] 2017-08-03 22:54
Not relevant anymore, closing it.

**Closed by lvca** 2017-08-03 22:54 UTC
Labels: enhancement

**Comment by prcamp** [comment] 2017-08-11 00:50
I'm very disappointed to see that this is not relevant anymore. Orientdb is very attractive, but as a rust developer, I'm hesitant to use it. capnproto would be fantastic as well. @lvca Can you please clarify why it isn't relevant, and what the best way to interface with a rust program natively would be? Cheers!

**Comment by tglman** [comment] 2017-08-15 09:52
hi @prcamp,

I'm very interested in rust as well and I'm the responsible of the binary protocol, I've been playing with rust in my free time and with @maggiolo00 we did some experiment related with OrientDB as well, feel free to get in touch with us for more informations.

Regards

**Comment by lvca** [comment] 2017-08-15 10:11
@prcamp It's not in our plans to support gRPC, unless some contribution arrives from the community. You can use OrientDB through the C driver.
