### ISSUE TITLE
Threads in park mode consuming CPU

### ISSUE THREAD

**Issue by thiagopm** [orientechnologies/orientdb#4678] opened 2015-07-29 14:20 UTC
Hi,

We just start to get this error below.

in the OrientDB server:
<code>
java.net.SocketException: Socket closed
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:116)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at java.io.DataOutputStream.flush(DataOutputStream.java:123)
	at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinary.flush(OChannelBinary.java:387)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.handleConnectionError(OBinaryNetworkProtocolAbstract.java:397)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.handleConnectionError(ONetworkProtocolBinary.java:1811)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:212)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:71)
Error during closing of output stream
java.net.SocketException: Socket closed
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:116)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at java.io.DataOutputStream.flush(DataOutputStream.java:123)
	at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
	at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinary.close(OChannelBinary.java:406)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.shutdown(OBinaryNetworkProtocolAbstract.java:109)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.shutdown(ONetworkProtocolBinary.java:149)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:79)
	Suppressed: java.net.SocketException: Socket closed
		at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:116)
		at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
		at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
		at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
		at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
		at java.io.FilterOutputStream.close(FilterOutputStream.java:159)
		... 4 more
</code>

in the driver (client side):
<code>
Cannot write to a BufferedStream while the read buffer is not empty if the underlying stream is not seekable. Ensure that the stream underlying this BufferedStream can seek or avoid interleaving read and write operations on this BufferedStream.
   at Orient.Client.Protocol.Connection.Send(Byte[] rawData)
   at Orient.Client.Protocol.Connection.ExecuteOperationInternal(IOperation operation)
   at Orient.Client.Protocol.Connection.ExecuteOperation(IOperation operation)
   at Orient.Client.ODatabase.Query(String sql, String fetchPlan)
   at ILang.OrientDB.ILangGraphOperation.RemoveEdge(Int32 userOrganizationId, Int32 classDisciplineId, EdgeType edge)
   at ILang.Objects.Queue.Processor.ClassDisciplineStudentProcessor.ProcessQueueMessage(Object queueMessage)
</code>

This problem happens when we turn on our Sync service, it process high number of DB write. 
After we stops the service, we stop to get this error, but seems that the threads keeps in a loop, because CPU and number of threads keeps high.

Here is the heap dump.

https://s3.amazonaws.com/a-several/heapdump-1438122505121.7z

Thanks

**Comment by thiagopm** [comment] 2015-07-30 18:38
Hi,

It happened again.. Seems some threads are in deadlock or looping consuming cpu...

Dump:
https://s3.amazonaws.com/a-several/threaddump-1438280115390.7z

Thanks

**Comment by tglman** [comment] 2015-08-03 15:32
Hi @thiagopm 

What version are you using ?

**Comment by tglman** [comment] 2015-08-03 16:09
Hi @thiagopm 

I checked both the  heap and threads dump, and i didn't find anything wrong, from the stack trace seems there is something wrong on the network level, but could be also just a dropped connection, do you have more details?

Thank You

**Comment by thiagopm** [comment] 2015-08-03 16:35
Hi, 
We are using a community SNAPSHOT from 7/28/2015 3:56pm.

After this error some threads status was changed to "Parking" mode, did not return to "running" and neither stopped.

The CPU average increases 30%.

I kept OrientDB service on for 4 days within this situation.

In the dump you can see some threads in waiting...

Thanks

**Comment by tglman** [comment] 2015-08-04 17:31
hi @thiagopm,

I see your point, anyway the thread in waiting should not use cpu, i saw some threads that where running some select, and as well the waiting threads could be waiting on the running query.

In any case the exception on the remote protocol cannot be the cause of this issue.

Will be cool if you can provide some steps to arrive to this state.

**Comment by thiagopm** [comment] 2015-08-04 17:52
Ok,

Probably there is no relation between this error and this problem, because today we got this error again,  but CPU and threads are ok.

I don't know how to reproduce, it happened twice when we were running our sync service (high number of updates) . 

Even after I turned off all services that connects to OrientDB, these threads and CPU kept high.

If you want to close this issue no problem, any news I tell you.

Thanks

**Comment by thiagopm** [comment] 2015-08-19 22:11
Hi @tglman,

We are trying to use OrientDB in production, but when we have high number of sync calls (inserts and Updates) we get this problem. 

Last weekend I had to point the connections of Orient to SQL Server because We had this problem again.

I turned off all services that connect to OrientDB, but it continue using almost 90% of CPU.

I think that we probably have some problem on the client/driver (connection manager), but the server garbage collector should clean this 500 unused threads that is lost and consuming CPU, no?

Isn't there a timeout for this connections?

Here is the last dump with no one connected to the Orient:
https://s3.amazonaws.com/a-several/heapdump-1440020379756.rar

![high_cpu noconnections](https://cloud.githubusercontent.com/assets/850424/9370353/03def64e-46a6-11e5-91c1-d34a299d9ac4.PNG)




Thanks,
Thiago

**Comment by thiagopm** [comment] 2015-08-20 15:09
Guys, 

If you want to check anything in the server, I can create an account to you.

This server is isolated by the firewall, none of the other server can connect to the OrientDB. And it keeps in the same scenario.

![high_cpu noconnections_2](https://cloud.githubusercontent.com/assets/850424/9386916/3f381444-4734-11e5-88bc-b5539a19ee7c.PNG)

**Comment by tglman** [comment] 2015-08-27 10:42
Hi @thiagopm,

I checked your dumps and i discovered that the were many threads reading data from the disc due to a bug on the fetch plan, i backported that fix to 2.0.x will be out with the next release.

closing

**Comment by thiagopm** [comment] 2015-08-27 16:06
Hi @tglman, 

We are using version 2.1 SNAPSHOT of july, 28. I think this is almost the 2.1 GA.

I can install 2.1 GA. Are you sure it's corrected in this version?

Which version should I use?

thanks,
Thiago

**Comment by tglman** [comment] 2015-08-28 09:18
Hi @thiagopm,

The issue i thought fixed this problem is this: https://github.com/orientechnologies/orientdb/commit/17bfb36b1ad852f3e3aa86a822b0dfb61128fc2c 

but this is already in the version you are using.

reopening

**Comment by tglman** [comment] 2015-08-28 13:09
Fixed now in 2.1.x and 2.0.x closing

**Closed by tglman** 2015-08-28 13:09 UTC
