### ISSUE TITLE
transaction blocked in java code when there is a binary node inside to delete

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#5614] opened 2016-01-20 15:07 UTC
considering the bug # 5613

there is another bug related to previous one

in my java code 

i have a transaction deleting 
a binary document A   and a document B with a link to A. 

commit function block indefinitely the thread executing the code

specular  transaction for inserting /updating works well. The problems seams in delection.

**Comment by luigidellaquila** [comment] 2016-01-21 14:08
Hi @publicocean0 

could you please share a thread dump? (a kill -3 of the process will do the trick). It will help us to understand where the problem is

Thanks

Luigi

**Comment by publicocean0** [comment] 2016-01-21 22:31
<pre>
"http-nio-8080-exec-7" #122 daemon prio=5 os_prio=0 tid=0x00007ffaa465f000 nid=0xee5 waiting on condition [0x00007ffaf6e97000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x000000008a5c8918> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
	at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:209)
	at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:285)
	at com.orientechnologies.common.concur.lock.OAdaptiveLock.lock(OAdaptiveLock.java:99)
	at com.orientechnologies.orient.enterprise.channel.OChannel.acquireReadLock(OChannel.java:121)
	at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:182)
	at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:171)
	at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:2153)
	at com.orientechnologies.orient.client.remote.OStorageRemote.commit(OStorageRemote.java:1381)
	at com.orientechnologies.orient.client.remote.OStorageRemoteThread.commit(OStorageRemoteThread.java:453)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:596)
	at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:156)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2659)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2628)
	at com.itiboss.dao.orientdb.BoDAO.removeObject(BoDAO.java:1540)

</pre>

**Comment by laa** [comment] 2016-01-25 09:30
Hi, 
In stack trace we can find only classes of remote storage , assigned to @tglman

**Comment by publicocean0** [comment] 2016-01-26 08:36
eventually if you can t find the bug ... i ll build a example in java code creating the block.

**Comment by tglman** [comment] 2016-01-26 11:08
@publicocean0 

That will be amazing, we are struggling a bit to reproduce.

**Comment by publicocean0** [comment] 2016-01-27 10:16
i investigated in all the transaction code ... deleting in alternate way block of code .... now i can block also the console using javascript :)
<pre>
 js var a=db.command("select from #33:341"); db.begin(); db.delete(a[0].identity); db.commit();
</pre>

now i trying to delete different nodes....

**Comment by publicocean0** [comment] 2016-01-27 14:02
solved. 
The problem was inside a trigger on delete giving a exception. When exception is thrown is called db.rollback().  
1) the exception is related with another bug : select from #3:10 where 3:10 is a binary bytes gives no result in any case. 
2) maybe it is to emprove the behaviour of transaction in case there is a nested transaction just for evoiding thread blocks. Anyway now i removed it. 
 2.a If the nested transaction throws a error what does it happen? 
2.b  If the nested transaction execute a rollback , the parent transaction in what status goes?i suppose when nested transaction executed a rollback , the parent transaction status goes in a incosistent status. It is better throw a exception but not blocking thread.

**Comment by tglman** [comment] 2016-02-04 10:46
Hi,

In oriendb there is no concept of nested transaction, the begin();commit(); block works as a "require transaction" so if one is already running it countinue it if not it create it and commit at the end.

Knowing that if an error happen somewhere, the whole transaction is rollbacked.

for the problem with the select of binary content we are checking that, track it in the other issue, anyway you can load a binary record with db.load(new ORecordId(33,341));

by the way, can we close this ?

**Comment by publicocean0** [comment] 2016-02-04 14:30
Hi , i know that nested transaction is not handled for now in orientdb. But as you told it might work continuing the transaction normally.... In that old block code i opened a nested transaction. it gives a exception , so rolling back in the try cach of nested transaction.... and thread was blocked . The issue is related to a block of thread .... a suggestion  to verify if in that condition all is ok. Apparently in this case the status of transaction is inconsistent.

**Comment by publicocean0** [comment] 2016-03-03 11:54
i found the problem.

There is a Class A with a trigger on delete.
a is a instance of A.
i call      ' delete  a   '    inside a transaction.
When orientdb enter in trigger 
 it calls a second js function with a body as this
<pre>
db.begin()
try{
....
}catch(e){
db.rollback(); throw e;
}
</pre>
writing a lot of trancing log... i saw that after is called db.begin()... the Thread get blocked on remote client

For now for evoiding the block of thread ... i m using in js

var txcount=db.transaction.amountOfNestedTxs() for understanding if i m in a transaction or not.

**Comment by laa** [comment] 2016-03-03 11:57
Hi @publicocean0 
Please do not make double rollbacks (inside of catch) it is done automatically if exception is thrown from ODB code itself and issue will be fixed without of hacks.

Does this solution works for you ?

**Comment by publicocean0** [comment] 2016-03-05 09:50
in this way ?

db.begin()

....

if (error) throw "error";

**Comment by laa** [comment] 2016-03-05 13:14
Hi ,
Yes exactly .

сб, 5 Мар 2016, 11:50 publicocean0 <notifications@github.com>:

> in this way ?
>
> db.begin()
>
> ....
>
> if (error) throw "error";
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/5614#issuecomment-192614701>
> .
>
-- 
Best regards,
Andrey Lomakin, R&D lead.
OrientDB Ltd

twitter:@Andrey_Lomakin linkedin:https://ua.linkedin.com/in/andreylomakin

**Comment by tglman** [comment] 2016-05-18 15:11
can we close this ?

**Comment by publicocean0** [comment] 2016-05-18 19:08
Hi sorry if I can t answer in this period . I m working in another project very hard. No time. I will write asap. You can close if you want eventually I will reopen

**Comment by lvca** [comment] 2016-05-19 03:09
Closing it, in case reopen it. Thanks.

**Closed by lvca** 2016-05-19 03:09 UTC
Labels: bug
