### ISSUE TITLE
missing config.cd file

### ISSUE THREAD

**Issue by florian-stoica-tlabs** [orientechnologies/orientdb#9562] opened 2021-03-15 06:47 UTC
## Expected behavior  
Database should not be corrupt

## Actual behavior  
From time to time I get my database throwing this:
com.orientechnologies.orient.core.exception.OStorageException: File with name config.cd does not exist in storage default
at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.loadFile(OWOWCache.java:732) ~[orientdb-core-3.0.22.jar:3.0.22]
at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.openFile(ODurableComponent.java:188) ~[orientdb-core-3.0.22.jar:3.0.22]
at com.orientechnologies.orient.core.storage.cluster.v1.OPaginatedClusterV1.open(OPaginatedClusterV1.java:204) ~[orientdb-core-3.0.22.jar:3.0.22]
at com.orientechnologies.orient.core.storage.config.OClusterBasedStorageConfiguration.load(OClusterBasedStorageConfiguration.java:192) ~[orientdb-core-3.0.22.jar:3.0.22]
at com.orientechnologies.orient.core.storage.disk.OLocalPaginatedStorage.initConfiguration(OLocalPaginatedStorage.java:455) ~[orientdb-core-3.0.22.jar:3.0.22]
at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:385) ~[orientdb-core-3.0.22.jar:3.0.22]
at com.orientechnologies.orient.core.db.OrientDBEmbedded.open(OrientDBEmbedded.java:281) ~[orientdb-core-3.0.22.jar:3.0.22]
at com.orientechnologies.orient.core.db.OrientDB.open(OrientDB.java:205) ~[orientdb-core-3.0.22.jar:3.0.22]
at com.orientechnologies.orient.core.db.OrientDB.open(OrientDB.java:190) ~[orientdb-core-3.0.22.jar:3.0.22]
at org.apache.tinkerpop.gremlin.orientdb.OrientGraphFactory.getDatabase(OrientGraphFactory.java:153) ~[orientdb-gremlin-3.0.22.jar:3.0.22]

## Steps to reproduce  
Did not find any reproduction paths...I don't know why this happens...

My real question is how can I recover my database if it's at this point?

**Comment by florian-stoica-tlabs** [comment] 2021-03-16 09:01
It seems that there is also an old report of more of the same issue https://github.com/orientechnologies/orientdb/issues/9391 with no attention/solution...is this in any way on any radar?  Or I can just kiss my data goodby?

**Comment by andrii0lomakin** [comment] 2021-03-16 13:47
Hi @florian-stoica-tlabs , your data are not lost, But unfortunately, all team is busy with issues from commercial clients. Once we deal with them we will work on issues from the OS version.

**Comment by andrii0lomakin** [comment] 2021-03-16 13:48
@florian-stoica-tlabs do you see this file inside of the database folder?

**Comment by andrii0lomakin** [comment] 2021-03-16 13:50
That could be one of the issues which we already fixed, did you try to update to the 3.0.37 version and check?

**Comment by florian-stoica-tlabs** [comment] 2021-03-19 07:50
Hi @laa Sorry for the long wait until I responded. I do have the following files inside:
config_13174512.bd
config_1983382051.nd
config_2061034952.cd
config_1506633995.ccm

Also updating to 3.0.37 did not help the same error is thrown.

**Comment by florian-stoica-tlabs** [comment] 2021-03-22 07:33
@laa is there anything else I can try to recover the database?

**Comment by ebanchio** [comment] 2021-06-17 11:24
Hi! I had the same problem using orient 3.1.5. Any news about this?

	DWL:database: block size = 4096 bytes, maximum segment size = 347 MB [DoubleWriteLogGL]Exception `18748728` in storage `plocal:/path/to/database`: 3.1.5 - Veloce (build 846eeb77dcb175a9fbd7ed534e039424322f44a7, branch 3.1.x)
	com.orientechnologies.orient.core.exception.OStorageException: Exception during execution of atomic operation inside of storage database
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideAtomicOperation(OAtomicOperationsManager.java:195)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:422)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.open(OrientDBEmbedded.java:483)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.open(OrientDBEmbedded.java:418)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:979)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:947)
	at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeDatabaseOpen37(OConnectionBinaryExecutor.java:1369)
	at com.orientechnologies.orient.client.remote.message.OOpen37Request.execute(OOpen37Request.java:75)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:355)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:239)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:67)
	Caused by: com.orientechnologies.orient.core.exception.OStorageException: Exception during execution of component operation inside component config.cd in storage database
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideComponentOperation(OAtomicOperationsManager.java:221)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideComponentOperation(OAtomicOperationsManager.java:206)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.executeInsideComponentOperation(ODurableComponent.java:102)
	at com.orientechnologies.orient.core.storage.cluster.v2.OPaginatedClusterV2.open(OPaginatedClusterV2.java:211)
	at com.orientechnologies.orient.core.storage.config.OClusterBasedStorageConfiguration.load(OClusterBasedStorageConfiguration.java:250)
	at com.orientechnologies.orient.core.storage.disk.OLocalPaginatedStorage.initConfiguration(OLocalPaginatedStorage.java:558)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.lambda$open$1(OAbstractPaginatedStorage.java:433)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideAtomicOperation(OAtomicOperationsManager.java:189)
	... 10 more
	Caused by: com.orientechnologies.orient.core.exception.OStorageException: File with name config.cd does not exist in storage database
	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.loadFile(OWOWCache.java:760)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationBinaryTracking.loadFile(OAtomicOperationBinaryTracking.java:372)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.openFile(ODurableComponent.java:193)
	at com.orientechnologies.orient.core.storage.cluster.v2.OPaginatedClusterV2.lambda$open$1(OPaginatedClusterV2.java:216)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperationsManager.executeInsideComponentOperation(OAtomicOperationsManager.java:214)
	... 17 more

**Comment by ghost** [comment] 2021-08-17 10:18
I am seeing this issue with 3.2.0.  I have no idea what trigger this. Is there any update on this?  

orientdb> connect plocal:/data/databases/dbname abc 123

Connecting to database [plocal:/data/databases/dbname] with user 'abc'...
Error: com.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database 'dbname'
Error: com.orientechnologies.orient.core.exception.OStorageException: Exception during execution of atomic operation inside of storage dbname
Error: com.orientechnologies.orient.core.exception.OStorageException: Exception during execution of component operation inside component config.cd in storage dbname
Error: com.orientechnologies.orient.core.exception.OStorageException: File with name config.cd does not exist in storage dbname

In the database directories, I am assuming these are correct:
root@uat-db-001:/opt/orientdb/log# ls -la /data/databases/dbname/config_*
-rw-r--r-- 1 orientdb orientdb 132096 Aug 16 19:50 /data/databases/dbname/config_1863402051.cd
-rw-r--r-- 1 orientdb orientdb 132096 Aug 16 19:50 /data/databases/dbname/config_2029091032.ccm
-rw-r--r-- 1 orientdb orientdb 132096 Aug 16 19:50 /data/databases/dbname/config_27966618.bd
-rw-r--r-- 1 orientdb orientdb  66560 Jun 24 06:15 /data/databases/dbname/config_415755639.nd
-rw-r--r-- 1 orientdb orientdb 132096 Aug 16 19:50 /data/databases/dbname/config_671038889.fcm

**Comment by andrii0lomakin** [comment] 2021-08-17 14:16
Hi @pa-chris , could you send me your database to check?

**Comment by ghost** [comment] 2021-08-17 14:26
How would you like me to send it?

**Comment by andrii0lomakin** [comment] 2021-08-17 14:34
I need a link to the database data on my email lomakin.andrey@gmail.com .

**Comment by andrii0lomakin** [comment] 2021-08-17 14:38
@pa-chris Just to clarify, did you work only with 3.2.0 version and then experienced this problem? I mean did you create a database and work with it using the same version of the distribution, did not you?

**Comment by ghost** [comment] 2021-08-17 14:40
Yes, that is correct.  This particular one was only every on 3.2.0.

**Comment by andrii0lomakin** [comment] 2021-08-18 14:57
Hi @pa-chris , thank you.
It was very informative. I have found a durability issue in the procedure of storing the registry of files of the database during close. 
I will provide a fix ASAP.

**Comment by ghost** [comment] 2021-08-18 14:58
Thank you very much.  

@laa One last question, the data I sent, will it be repaired?

**Comment by andrii0lomakin** [comment] 2021-08-18 15:53
@pa-chris data are not touched, but unfortunately, that is quite a time-consuming procedure, so only for commercial customers. I am sorry for that. It implies manual repair of data. I am running tests now to be sure that changes do not break anything and will commit.

**Comment by ghost** [comment] 2021-08-18 17:16
@laa , If you can point me to how to do the manual repair, that is no problem at all. That would be kindly appreciated

**Comment by andrii0lomakin** [comment] 2021-09-02 09:56
Fixed in develop branch. Will fix it later in 3.1 branch.

**Comment by andrii0lomakin** [comment] 2021-10-21 07:05
Fixed by PR above.

**Closed as completed by andrii0lomakin** 2021-10-21 07:05 UTC
Labels: bug
