### ISSUE TITLE
Error on client connection (GC overhead limit exceeded)

### ISSUE THREAD

**Issue by thiagopm** [orientechnologies/orientdb#4367] opened 2015-06-15 16:54 UTC
Hi,
Today our OrientDB Server started to get this error:
<code>
java.lang.OutOfMemoryError: GC overhead limit exceeded
{db=ilang} Exception during commit of active transaction.
com.orientechnologies.orient.core.exception.ODatabaseException: Database 'plocal:D:/orientdb-community-2.1-SNAPSHOT/databases/ilang' is closed
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.checkOpeness(ODatabaseDocumentTx.java:2703)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2464)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.close(ODatabaseDocumentTx.java:1107)
	at com.orientechnologies.orient.server.OClientConnection.close(OClientConnection.java:50)
	at com.orientechnologies.orient.server.OClientConnectionManager.cleanExpiredConnections(OClientConnectionManager.java:103)
	at com.orientechnologies.orient.server.OClientConnectionManager$1.run(OClientConnectionManager.java:62)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
</code>

Questions:
1. Do you know why it happens? Is it a memory leak or Should I increase the max heap size? (today is 512mb)

2. When it happened, it locked the web server because it is no returning an error, is holding the connection/thread. 
There is a timeout for Open connection?

We are using 2.1 SNAPSHOT.

Thank You,

**Comment by tglman** [comment] 2015-06-17 09:55
From the traces look like it was going in out of memory while cleaning pending connections, it's really probable that was just a moment of overhead and you need to increase the heap size to handle your load.
What was doing the server while this happened?


the client has a quite long timeout for wait that the all request is complete, and it will receive an answer from the server in any case.

**Comment by thiagopm** [comment] 2015-06-17 17:45
Our UserOnline service was running. On the OrientDB is basically a class where we keep online users with a connection (edge) to the Academic graph. 
We insert and delete online Users, Update lastAction and query all user academic conections (friends) are online. This class is our cache of users online, constantly changed.

About heap size, I increased it to 1024 mb. After 6 hour it was totally allocated and average of 700mb used, then maintained well.

**Comment by lvca** [comment] 2015-06-17 20:41
Ok, so I'm closing this issue. In case please reopen/comment it.

**Closed by lvca** 2015-06-17 20:41 UTC
Labels: question

**Comment by thiagopm** [comment] 2015-06-17 20:49
Luca, I got this error again right now using 1024 mb of max heap size.
I'm sending you some info...

**Comment by thiagopm** [comment] 2015-06-17 20:51
![gc memory_2015 06 17 17_40](https://cloud.githubusercontent.com/assets/850424/8218466/7edbdf24-1519-11e5-98f6-9c0264061221.PNG)

**Comment by lvca** [comment] 2015-06-17 20:54
Do you know what's happened on 5:34pm?

**Comment by thiagopm** [comment] 2015-06-17 20:57
Nothing special...
I'm sending the dump in support@orientdb.com, ok?

**Comment by lvca** [comment] 2015-06-17 21:25
Ok.

**Comment by laa** [comment] 2015-06-23 11:19
Fixed in email.

**Comment by vogtstep** [comment] 2015-07-17 10:33
I have seen similar GC behaviour in my application.
How did you resolve this problem and what was the cause?
