### ISSUE TITLE
Unexpected token }  orientdb 2.0.7

### ISSUE THREAD

**Issue by Elad-L** [orientechnologies/orientdb#3977] opened 2015-04-20 18:24 UTC
running the following gremlin command using gremlin rest api issue the "Unexpected token } " error
u1 = [];
u = new GremlinPipeline(g.getVertices("name", "zyx")).next();
u.as("u").out("Wrote").both("On").in("Wrote").except("u").dedup()[0..40].fill(u1);
[u1._().as("u1").out("Wrote").both("On").in("Wrote").retain(u1).except("u1").dedup().as("u2").select(["u1", "u2"]){ it.id }]

server error:
Fetching error on record #-1:-1
java.lang.NullPointerException

Without the last brackets (surrounding last line) it works fine, also this query works fine on orientdb 1.7.9

**Comment by luigidellaquila** [comment] 2015-07-17 10:38
Hi @Elad-L 

could you provide a simple dataset to reproduce the issue?
I tried it with my data, on v 2.1 snapshot and it seems to work fine

**Comment by Elad-L** [comment] 2015-07-28 13:18
Hi luigidellaquila,

Please find a link to a sample dataset to recreate this bug with the above query.
https://drive.google.com/folderview?id=0B43_FeXLAUxsfjFUTHdtamNMckR1Rm94T2VSblJ2elQydGpMUzFhOVRUYkFDZi04d3o3Zkk&usp=sharing

**Comment by luigidellaquila** [comment] 2015-07-28 14:03
Hi @Elad-L 

Thanks, I just sent a request to access the file

**Comment by Elad-L** [comment] 2015-07-28 15:18
I modified the link, so no access is needed now.

**Comment by luigidellaquila** [comment] 2015-07-29 12:55
Hi @Elad-L 

I tried your dataset on develop branch and the query does not throw any exceptions.
Could you please confirm that it's fixed?

Thanks

**Comment by Elad-L** [comment] 2015-08-03 14:51
I tested it on the new version 2.0.13 and the problem still exist.
I tested it through REST client.

Full exception:
2015-08-03 17:28:44:906 INFO  {db=testset} --> OK, indexed 505 items in 197 ms [OIndexRebuildOutputListener]{db=testset} Fetching error on record #-1:-1
java.lang.NullPointerException
        at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.getEdgeClassNames(OrientBaseGraph.java:294)
        at com.tinkerpop.blueprints.impls.orient.OrientVertex.getEdges(OrientVertex.java:1005)
        at com.tinkerpop.blueprints.impls.orient.OrientVertex.getEdges(OrientVertex.java:988)
        at com.tinkerpop.blueprints.util.DefaultVertexQuery$DefaultVertexQueryIterable.<init>(DefaultVertexQuery.java:110)
        at com.tinkerpop.blueprints.util.DefaultVertexQuery.vertices(DefaultVertexQuery.java:84)
        at com.tinkerpop.pipes.transform.VertexQueryPipe.processNextStart(VertexQueryPipe.java:113)
        at com.tinkerpop.pipes.transform.VertexQueryPipe.processNextStart(VertexQueryPipe.java:19)
        at com.tinkerpop.pipes.AbstractPipe.next(AbstractPipe.java:89)
        at com.tinkerpop.pipes.transform.VertexQueryPipe.processNextStart(VertexQueryPipe.java:85)
        at com.tinkerpop.pipes.transform.VertexQueryPipe.processNextStart(VertexQueryPipe.java:19)
        at com.tinkerpop.pipes.AbstractPipe.next(AbstractPipe.java:89)
        at com.tinkerpop.pipes.transform.VertexQueryPipe.processNextStart(VertexQueryPipe.java:85)
        at com.tinkerpop.pipes.transform.VertexQueryPipe.processNextStart(VertexQueryPipe.java:19)
        at com.tinkerpop.pipes.AbstractPipe.next(AbstractPipe.java:89)
        at com.tinkerpop.pipes.filter.CollectionFilterPipe.processNextStart(CollectionFilterPipe.java:35)
        at com.tinkerpop.pipes.AbstractPipe.next(AbstractPipe.java:89)
        at com.tinkerpop.pipes.filter.CollectionFilterPipe.processNextStart(CollectionFilterPipe.java:35)
        at com.tinkerpop.pipes.AbstractPipe.next(AbstractPipe.java:89)
        at com.tinkerpop.pipes.filter.DuplicateFilterPipe.processNextStart(DuplicateFilterPipe.java:34)
        at com.tinkerpop.pipes.AbstractPipe.next(AbstractPipe.java:89)
        at com.tinkerpop.pipes.util.AsPipe.processNextStart(AsPipe.java:42)
        at com.tinkerpop.pipes.AbstractPipe.next(AbstractPipe.java:89)
        at com.tinkerpop.pipes.transform.SelectPipe.processNextStart(SelectPipe.java:54)
        at com.tinkerpop.pipes.transform.SelectPipe.processNextStart(SelectPipe.java:21)
        at com.tinkerpop.pipes.AbstractPipe.hasNext(AbstractPipe.java:98)
        at com.tinkerpop.pipes.util.Pipeline.hasNext(Pipeline.java:105)
        at com.orientechnologies.orient.core.serialization.serializer.OJSONWriter.iteratorToJSON(OJSONWriter.java:189)
        at com.orientechnologies.orient.core.serialization.serializer.OJSONWriter.writeValue(OJSONWriter.java:128)
        at com.orientechnologies.orient.core.serialization.serializer.OJSONWriter.iteratorToJSON(OJSONWriter.java:192)
        at com.orientechnologies.orient.core.serialization.serializer.OJSONWriter.writeValue(OJSONWriter.java:130)
        at com.orientechnologies.orient.core.serialization.serializer.OJSONWriter.writeAttribute(OJSONWriter.java:410)
        at com.orientechnologies.orient.core.serialization.serializer.OJSONWriter.writeAttribute(OJSONWriter.java:376)
        at com.orientechnologies.orient.core.fetch.json.OJSONFetchListener.processStandardField(OJSONFetchListener.java:38)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.processRecord(OFetchHelper.java:304)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.fetch(OFetchHelper.java:72)
        at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerJSON.toString(ORecordSerializerJSON.java:337)
        at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerStringAbstract.toString(ORecordSerializerStringAbstract.java:665)
        at com.orientechnologies.orient.core.record.ORecordAbstract.toJSON(ORecordAbstract.java:192)
        at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.formatMultiValue(OHttpResponse.java:385)
        at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.writeRecords(OHttpResponse.java:335)
        at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.writeResult(OHttpResponse.java:231)
        at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:103)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:175)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:580)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)

**Comment by luigidellaquila** [comment] 2015-08-04 12:24
@Elad-L ah, ok. It's fixed in develop branch (2.1), but i have to check it on 2.0.13. 
Moving back release tag to 2.0.x

Thanks

**Comment by luigidellaquila** [comment] 2015-09-22 13:42
issue was moved to latest stable (2.1), could you confirm that in this release it is already fixed?

**Comment by prjhub** [comment] 2015-10-07 11:42
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.

**Closed by prjhub** 2015-10-07 11:42 UTC
Labels: bug, waiting reply
