### ISSUE TITLE
OrientDB 2.0: Regression in creation of non-lightweight edges

### ISSUE THREAD

**Issue by srgg** [orientechnologies/orientdb#3481] opened 2015-01-27 18:18 UTC
We found that one of our test cases which was shared in  scope of  https://github.com/orientechnologies/orientdb/issues/2582 fails because in_ and out_ edges are switched. It seems that something wrong with edge direction.

**Comment by lvca** [comment] 2015-06-18 15:09
Are you able to reproduce this issue on 2.1-rc4?

**Comment by lvca** [comment] 2015-07-03 22:52
Closing because no answer. In case please reopen/comment this issue.

**Closed by lvca** 2015-07-03 22:52 UTC
Labels: waiting reply
