### ISSUE TITLE
Edge unique index lead to deadlock when insert vertex and edge

### ISSUE THREAD

**Issue by kinssun** [orientechnologies/orientdb#7589] opened 2017-07-26 18:31 UTC
## Expected behavior  
I am trying to build a social relation network with orientdb graph(remotely connect plocal graph database). I defined the vertex and edge class with their unique index on their property 'memberId' and 'name' respectively (Note: the value of the parameter 'name' for edge class is combined with the value of parameter 'memberId' for fromVertex and toVertex).

In my app, I also added a method to create these vertexes and edges , and ensure that there is only one edge between specific both of vertexes. Then I executed a performance test towards this method and expected vertexes and edges could be built susccessfully.

## Actual behavior  
However, orientdb encountered deadlock soon. I can't find the root cause but doubt that the edge index lead to this issue. In fact, If all of edges  between tested vertex have been built up, deadlock will disappear after I re-run the test. On the other hand, If I created only verstexes during test, this issue is also can't be reproduced. 

## Steps to reproduce  
mentioned in the analysis above.

**Comment by laa** [comment] 2017-07-26 18:51
HI @kinssun could you send us full thread dump as a gist?

**Comment by laa** [comment] 2017-07-26 19:03
@kinssun is it also possible for you to share the code of benchmak which you used?

**Comment by kinssun** [comment] 2017-07-27 02:23
@laa thanks for your quick response. My code fragment is listed below(I executed performance test towards the method 'addFollowRelation()', the parameter fromMemberId and toMemberId have initial 
input value with random integer from 0 to 10000 )  :
/**
     * Add the follow relation between fromMemberId and toMemberId
     * @param fromMemberId 
     * @param toMemberId 
     */
    public void addFollowRelation(String fromMemberId, String toMemberId) {
        OrientGraph graph = orientGraphFactory.getTx();
        try {
            boolean hasFollowRelation = isEdgeExisted(graph, fromMemberId, toMemberId);
            // if relation is not existed, insert it.
            if (!hasFollowRelation) {
                OrientVertex fromV = createMemberVertex(graph, fromMemberId);
                OrientVertex toV = createMemberVertex(graph, toMemberId);
                fromV.addEdge(null, toV, "FollowEdge" ,null, "fName", fromMemberId + ">" + toMemberId);
                graph.commit();
            }
        } finally {
            graph.shutdown();
        }
    }

    private OrientVertex createMemberVertex(OrientGraph graph, String memberId) {
        OrientVertex v = retrieveMemberVertex(graph, memberId);
        if (null == v) {
            v = graph.addVertex("class:Person", "memberId", memberId);
            graph.commit();
        }
        return v;
    }

    private OrientVertex retrieveMemberVertex(OrientGraph graph, String memberId) {
        OrientVertex v = null;
        Iterator<Vertex> it = graph.query().has("memberId",memberId).vertices().iterator();
        if (it.hasNext()) {
            v = (OrientVertex) it.next();
        }
        return v;
    }

    private boolean isEdgeExisted(OrientGraph graph, String fromMemberId, String toMemberId) {
        boolean result = false;
        Iterable<Edge> it = graph.getEdges("FollowEdge.fName",fromMemberId + ">" + toMemberId);
        if (it.iterator().hasNext()) {
            result = true;
        }
        return result;
    }



BTW, also post my database initialization scripts:
OrientGraphFactory factory = new OrientGraphFactory("remote:localhost/plocalgraph01", "root", "123456").setupPool(1,10);
OrientGraphNoTx graphNoTx = factory.getNoTx();
graphNoTx.command(new OCommandSQL("ALTER DATABASE DATETIMEFORMAT \"yyyyMMddHHmmss\"\n")).execute();
graphNoTx.command(new OCommandSQL("CREATE CLASS Person EXTENDS V\n")).execute();
graphNoTx.command(new OCommandSQL("CREATE PROPERTY Person.memberId STRING (MANDATORY TRUE)\n")).execute();
graphNoTx.command(new OCommandSQL("CREATE INDEX Person.memberId ON Person (memberId) UNIQUE\n")).execute();
graphNoTx.command(new OCommandSQL("CREATE CLASS FollowEdge EXTENDS E\n")).execute();
graphNoTx.command(new OCommandSQL("CREATE PROPERTY FollowEdge.fName STRING (MANDATORY TRUE)\n")).execute();
graphNoTx.command(new OCommandSQL("CREATE PROPERTY FollowEdge.createdDate DATETIME (MANDATORY TRUE, default sysdate(\"yyyyMMddHHmmss\"))\n")).execute();
graphNoTx.command(new OCommandSQL("CREATE INDEX FollowEdge.fName ON FollowEdge (fName) UNIQUE\n")).execute();

**Comment by kinssun** [comment] 2017-07-27 05:02
@laa thread dump:  https://gist.github.com/kinssun/5be7bcf0561ad9d7095341fd8d4773a0

**Comment by kinssun** [comment] 2017-07-27 05:06
BTW, I disabled the WAL via JVM parameter '-Dstorage.useWAL=false -Dstorage.wal.syncOnPageFlush=false'

**Comment by laa** [comment] 2017-07-27 05:45
Hi, @kinssun thank you very much for the detailed information, I suppose the problem of the issue is following, we made big refactoring so even if WAL is disabled you still run inside of transaction but without durability feature. We do not recommend to disable WAL because of risks of data loss in case of a server crash and users typically never switch it off, that I suppose is the reason why this issue was never reported before. Probably because you will run the server in production with durability feature switched on I would recommend you to make benchmarks with WAL enabled. In any case, I will start to work on this issue since tomorrow.

**Comment by kinssun** [comment] 2017-07-27 07:03
@laa ok, I will enable WAL to test again.

**Comment by kinssun** [comment] 2017-07-27 08:56
@laa If enable WAL , deadlock won't appear. However, I will do a futher test to ensure this issue can be worked around.

**Comment by laa** [comment] 2017-07-27 09:34
@kinssun sure, thank you very much. I will set the priority of this issue as a low because it will never affect real production case. But I will very appreciate if you provide me additional information during bug fixing.

**Comment by kinssun** [comment] 2017-07-27 11:05
@laa Thanks for your help. During the performance test, I found another problem, the orientdb server will hang several seconds , and has no any response. I found this phenomena is led by WAL file flush. Could you help to tell me how to avoid ?  The following is snapshot from my test client. It is obvious that the orientdb hung periodically.
![qq 20170727185626](https://user-images.githubusercontent.com/5126424/28667560-98e957ee-72fe-11e7-8db9-f4e4e1f78758.png)

**Comment by kinssun** [comment] 2017-07-28 02:56
@Iaa If feel free, pls have a look at the question above. thanks. I think it is the same one as mentioned in #4144

**Comment by kinssun** [comment] 2017-07-28 02:56
@Iaa If feel free, pls have a look at the question above. thanks. I think it is the same one as mentioned in #4144. Thanks

**Comment by laa** [comment] 2017-07-28 10:15
Hi @kinssun . The issue which you see should be fixed in 3.0. About 2.2.x, it is caused by the following.

WAL reaches its boundary and it should be truncated, but it can not be truncated because write cache contains data which are not yet flushed to the disk but operations on which are stored at the begging of WAL. So we stop operations to flush data from write cache and truncate WAL. How to avoid it? Increase WAL size limits. You can use two approaches to do that. First (recommended one) is move WAL to the HDD and set a limit of WAL size about 80% of HDD size. In such case data writes will not interfere with WAL writes and write cache will have more time to write its content to disk. The other solution is to calculate approximate size of your DB on disk. Let suppose your DB will consume 50% of disk space. Then you can allocate 30% for WAL. For that, you can use following parameters: `storage.wal.path` - location of wal, `storage.wal.maxSize` wal size limit in MB. Let me know if it works.

**Comment by kinssun** [comment] 2017-07-28 12:56
Hi, @laa I set the storage.wal.maxSize from default 4000MB to 8000MB, server pause time got a little of limited enhancement but I think it is only a work around. If we use orientdb to build heavy traffic social network, this issue shouldn't be accepted. I wish Version 3.0 could be GA soon and get better test results .

**Comment by kinssun** [comment] 2017-08-04 14:01
@Iaa I executed the same tests with orientdb 3.0.0m2, and got a not good performance result: QPS is only 8/s, shall I made some special performance tuning?

**Comment by kinssun** [comment] 2017-08-04 14:33
sorry, I downloaded the orientdb-community-tp3-3.0.0m2.tar.gz, so I suppose I should use orientdb-community-tp2-3.0.0m2.tar.gz to have a test?

**Comment by laa** [comment] 2017-08-04 14:59
Hi @kinssun on storage tests such as YCSB tests writes are much faster than reads. But graph layer may contain some issues in tp 3. Please try with tp2 if you still will have slower performance please fill in a separate issue in 3.0 we will look on it next week and fix possible problems if there will be any.

**Comment by laa** [comment] 2017-08-04 15:25
@kinssun here some data of our latest YCSB benchmark 3.0 M2 against 2.2.x version on 50M records (DB size on disk 80 GB and RAM cache is 40 GB)

Data load:  25086 vs 6840 QPS
Load A (50% reads and 50% writes): 9454 vs 3808 QPS
Load B (90% reads and 10% writes): 20998 vs 15601 QPS
Load C (100% reads) :  29610 vs 30556 QPS

so as you can see reads a little bit slower but in general write speed was noticeably improved. So if you will have got opposite data I am looking forward to analyzing and fixing possible an issue.

**Comment by laa** [comment] 2017-08-04 15:27
@kinssun anyway looking forward to you latest tests results.

**Comment by kinssun** [comment] 2017-08-05 09:46
@Iaa, thanks for your quick response, This bug should be closed due to the issue title is not suitable to disscuss 3.0m2 performance problem. I will reopen a issue to track it.

**Closed** 2017-08-05 09:46 UTC
Labels: bug, storage team
