### ISSUE TITLE
truncate error

### ISSUE THREAD

**Issue by weickdev** [orientechnologies/orientdb#7936] opened 2017-12-15 10:54 UTC
### OS: CentOS

When I run 'truncate class invest unsafe', then the console is blocked, and the db cant reach on the web. When I input CTRL+C, I get this message:
```
orientdb {db=test}> truncate class invest unsafe

Error: java.lang.IllegalStateException: Connection cannot be released because the pool doesn't exist anymore
```

**Comment by luigidellaquila** [comment] 2017-12-15 10:59
Hi @weickdev 

Thank you for reporting, I'm checking it now. Is it plocal or remote connection?

Thanks

Luigi

**Comment by laa** [comment] 2017-12-15 10:59
@weickdev sorry for my response by truncate class is unsafe by definition it can cause bad side effects as you see it. That is why you can not execute it without unsafe.

**Comment by luigidellaquila** [comment] 2017-12-15 11:04
Hi @weickdev 

I just tried it and I was not able to reproduce the problem. Any additional information on how to reproduce?

Thanks

Luigi

**Comment by weickdev** [comment] 2017-12-15 12:54
@luigidellaquila I meet it again. It seems before I run truncate command, the db server is run into error status. I can't connect it by code. At this time, I can open the main web page and the demodb page, but I cann't open my test db. And there is no error message in the server log.

**Comment by weickdev** [comment] 2017-12-15 13:57
@luigidellaquila I find the error:
```
2017-12-15 21:54:59.386  INFO 23660 --- [pool-4-thread-3] c.o.orient.client.remote.OStorageRemote  : Caught Network I/O errors on 218.17.162.184:2424/test, trying an automatic reconnection... (error: com.orientechnologies.orient.core.exception.OCoreException; local class incompatible: stream classdesc serialVersionUID = 5729406522061692260, local class serialVersionUID = 8829149802207954818)
2017-12-15 21:54:59.388  INFO 23660 --- [pool-4-thread-9] c.o.orient.client.remote.OStorageRemote  : Caught Network I/O errors on 218.17.162.184:2424/test, trying an automatic reconnection... (error: Channel is closed)
```
When I run massive inserting operation there is a error log. After this, my test db can't work until restart the db server

**Comment by tglman** [comment] 2017-12-15 14:01
hi @weickdev,

about :`Connection cannot be released because the pool doesn't exist anymore` i fixed this problem and will be included in the RC.

Regards

**Comment by weickdev** [comment] 2017-12-15 14:57
@tglman Thanks! Can I pull the last code on develop branch to fix this issue?

**Closed** 2017-12-16 06:09 UTC
