### ISSUE TITLE
[Feature Request] Field alias and/or view

### ISSUE THREAD

**Issue by matanshukry** [orientechnologies/orientdb#4979] opened 2015-09-17 12:23 UTC
I was wondering if there is any desire for a field alias or a view feature.
#### Field Alias

The field alias I was thinking about is a simple second name for a field. Unlike the current aliases in the query, the field alias I am referring to can be used to query a field with a different name. Something like

```
CREATE CLASS User EXTENDS V
CREATE PROPERTY User.id INTEGER
CREATE PROPERTY User.username STRING
CREATE PROPERTY ALIAS User.key_field id

CREATE VERTEX User SET id=0, username="Mat";

SELECT key_field FROM User
// Will select key_field with value 0
```
#### View

I am talking about the same video as most RDBMS have these days; That is, a simple object that stores a (probably optimized-ish version of) query. Something like:

```
CREATE PROPERTY User.id INTEGER
CREATE PROPERTY User.username STRING
CREATE PROPERTY ALIAS User.key_field id

CREATE VIEW UserBasic AS Select id as key_field from USER
```
#### Reasoning

My specific use case for any of the above is I have a field of type LINK, that can point to different classes, dependent on the row. When querying the field though, I would like to query some small information, displaying a short text (name) and linking it to the object page.

Currently, I am simply querying everything, and checking what isn't null at the application level.
Something like (assuming 'user' has a field 'friend' that can point to either 'user' or 'animal')

```
SELECT user_id,username, friend.user_id, friend.username, friend.animal_id, friend.animal_name FROM User
```

p.s.
I don't mind working on this feature, assuming it will be merged and I won't work for nothing.

**Comment by luigidellaquila** [comment] 2015-09-18 13:40
Hi @matanshukry 

I think views would be nice to have. I have some more doubts about aliases, even though I understand your use case.
My only concern is about record identities in views: in relational databases the problem does not arise, because join operations are based on property values, but in OrientDB relationships rely on immutable RIDs, so how should a view manage its RIDs? 
In particular in the general case, when the view is a projection/aggregation of data, how should RIDs be assigned and re-calculated when the query result changes? 

About the merge, of course we do not like to waste contributors resources, so any piece of code that makes sense and that is well implemented will eventually be merged. 
The problem is "when"...
What I mean is that the roadmap for 2.2 is well defined and very rich, so it's unlikely that we will be able to merge this feature in that release. Maybe it will be merged in 3.0, more likely in 3.1, so take it into consideration in your decision.

Thanks

Luigi

**Comment by matanshukry** [comment] 2015-09-18 14:55
I might misunderstand you a bit, since it sounds to me like you're wondering how a view would store it's data; But the thing is, views (usually, anyway) don't store anything beside the query it self (or some optimized version of it, as possible as it may be).

Regarding the RIDs, although I didn't dig deep enough, as far as I can tell there are temporary RIDs which are assigned when you're querying for arbitrary data, such as when using functions or querying fields over links (as far as I can tell, they have negative values; but that's just from the few queries I ran, so I could be wrong).

**Comment by luigidellaquila** [comment] 2015-09-18 15:35
my concern is more conceptual than practical, a view can store physical data or not (eg. materialized view in RDBMS), but the real problem is to accept or not that a document in a view has its own (immutable) identity, so that this document can be used as a regular one, like being linked from another document. In this case a temporary ID would not be enough.
Of course, this is just a choice, we could just decide that documents in views do not have an identity, so they cannot be linked by other documents

**Comment by matanshukry** [comment] 2015-09-18 15:46
Oh, I was referring to the simple view then. In my opinion, a view should be a simple query. There are some other objects that can be created, that resemble view, such as mview (materialized view) as you said, and snapshots (a copied yet updateable of the table; something like a git commit I guess).

That said, I'll try to see how soon I can start working on the simple view.

**Comment by lvca** [comment] 2017-08-03 22:49
Not relevant anymore, closing it.

**Closed by lvca** 2017-08-03 22:49 UTC
Labels: enhancement

**Comment by RPCMoritz** [comment] 2017-08-05 14:40
Could you explain why it isn't relevant anymore and what exactly deprecated it? I was consdering using views, and would like to know what supplanted them.

**Comment by lvca** [comment] 2017-08-05 19:47
Because the last comment on this was 2 years ago, nobody did +1 on this and no PR has been made. Today you can simply write a query as SQL Function an invoke the function.
