### ISSUE TITLE
ArrayIndexOutOfBoundsException: 256 when trying to create a user with latest console to a 3.0.0m2 server

### ISSUE THREAD

**Issue by anthony-o** [orientechnologies/orientdb#7901] opened 2017-11-26 23:00 UTC
## Expected behavior
```
CREATE USER `my-user` IDENTIFIED BY password ROLE admin
```
should create `my-user`

## Actual behavior  
```
Error: com.orientechnologies.orient.core.exception.OStorageException: Error on executing command: create USER `my-user` IDENTIFIED BY password ROLE admin
	DB name="test"

Error: java.lang.ArrayIndexOutOfBoundsException: 256
```

## Steps to reproduce  
In one terminal, run:
```
docker run -it --name db -e ORIENTDB_ROOT_PASSWORD=rootpass orientdb:3.0.0m2
```

In another one, run:
```
docker run -it --rm --link db:db -e ORIENTDB_ROOT_PASSWORD=rootpass maven bash
```
And then execute this:
```
ORIENTDB_VERSION=3.0.0-SNAPSHOT
cd /tmp && mkdir orientdb && mvn dependency:get -Ddest=./ -DremoteRepositories=sonatype-nexus-snapshots::::https://oss.sonatype.org/content/repositories/snapshots -Dartifact=com.orientechnologies:orientdb-community:$ORIENTDB_VERSION:tar.gz && tar -xvzf orientdb-community-$ORIENTDB_VERSION.tar.gz -C /tmp/orientdb --strip-components=1 && rm orientdb-community-$ORIENTDB_VERSION.tar.gz
mv /tmp/orientdb /opt/
/opt/orientdb/bin/console.sh "CREATE DATABASE remote:db/test root $ORIENTDB_ROOT_PASSWORD PLOCAL; CREATE USER \`my-user\` IDENTIFIED BY password ROLE admin;"
```

**Comment by laa** [comment] 2017-11-27 04:36
Please provide full stack trace, it is really hard to understand what is going on without it.

**Comment by anthony-o** [comment] 2017-11-27 09:36
Could you tell me how to activate more log or debug information in the `console.sh`? Normally you should easily reproduce the problem if you have Docker.

**Comment by anthony-o** [comment] 2017-11-27 10:04
I switched to `FINER` on the server and got:
```
2017-11-27 09:54:49:150 FINE  {db=test} Request id:3 type:45 [ONetworkProtocolBinary]
2017-11-27 09:54:49:274 FINE  {db=test} Sent run-time exception to the client /172.17.0.3:49172: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error parsing query:

     ^
Encountered " <CREATE> "create "" at line 1, column 1.
Was expecting one of:
    <IF> ...
    <FOREACH> ...
    ";" ...
    <IF> ...
    
	DB name="test"
	Error Code="1" [ONetworkProtocolBinary]
2017-11-27 09:54:51:596 FINE  [OClientConnectionManager] found and removed pending closed channel 3 (null) [OClientConnectionManager]
```
But what is weird is that with 2.2.30 (just replace `ORIENTDB_VERSION=3.0.0-SNAPSHOT` with `ORIENTDB_VERSION=2.2.30` in my steps to reproduce) I don't have this issue:
```
orientdb {db=test}> CREATE USER `my-user` IDENTIFIED BY password ROLE admin

User created successfully.
```

This should be linked perhaps with https://github.com/orientechnologies/orientdb/issues/7898 ?

**Comment by laa** [comment] 2017-12-01 07:22
@luigidellaquila could you look on that?

**Comment by luigidellaquila** [comment] 2017-12-01 13:10
Hi @anthony-o @laa 

I don't seem to be able to reproduce this problem on latest snapshot.

I see you are using the Docker image for OrientDB 3.0m2 and running it as a server, while you are connecting with the console from the 3.0.0-SNAPSHOT. I think the problem is in some changes that make the snapshot incompatible with the M2

Please let me know if I missed something

Thanks

Luigi

**Comment by anthony-o** [comment] 2017-12-01 14:46
Hi @luigidellaquila  & @laa ,

I've just managed to reproduce it on Docker on my Ubuntu 16.04.
Here is a oneliner to reproduce the bug (trying to create a database & user from a 3.0.0-SNAPSHOT client connecting to a 3.0.0m2 server):
```bash
docker run -d --name db -e ORIENTDB_ROOT_PASSWORD=rootpass orientdb:3.0.0m2 && docker run -it --rm --link db:db -e ORIENTDB_ROOT_PASSWORD=rootpass -e ORIENTDB_VERSION=3.0.0-SNAPSHOT maven bash -c 'cd /tmp && mkdir orientdb && mvn dependency:get -Ddest=./ -DremoteRepositories=sonatype-nexus-snapshots::::https://oss.sonatype.org/content/repositories/snapshots -Dartifact=com.orientechnologies:orientdb-community:$ORIENTDB_VERSION:tar.gz && tar -xvzf orientdb-community-$ORIENTDB_VERSION.tar.gz -C /tmp/orientdb --strip-components=1 && rm orientdb-community-$ORIENTDB_VERSION.tar.gz && mv /tmp/orientdb /opt/ && /opt/orientdb/bin/console.sh "CREATE DATABASE remote:db/test root $ORIENTDB_ROOT_PASSWORD PLOCAL; CREATE USER \`my-user\` IDENTIFIED BY password ROLE admin;"'
```
Whereas this oneliner creates the database & user correctly (from a 3.0.0-SNAPSHOT client connecting to a 3.0.0m2 server)
```bash
docker run -d --name db -e ORIENTDB_ROOT_PASSWORD=rootpass orientdb:3.0.0m2 && docker run -it --rm --link db:db -e ORIENTDB_ROOT_PASSWORD=rootpass -e ORIENTDB_VERSION=2.2.30 maven bash -c 'cd /tmp && mkdir orientdb && mvn dependency:get -Ddest=./ -DremoteRepositories=sonatype-nexus-snapshots::::https://oss.sonatype.org/content/repositories/snapshots -Dartifact=com.orientechnologies:orientdb-community:$ORIENTDB_VERSION:tar.gz && tar -xvzf orientdb-community-$ORIENTDB_VERSION.tar.gz -C /tmp/orientdb --strip-components=1 && rm orientdb-community-$ORIENTDB_VERSION.tar.gz && mv /tmp/orientdb /opt/ && /opt/orientdb/bin/console.sh "CREATE DATABASE remote:db/test root $ORIENTDB_ROOT_PASSWORD PLOCAL; CREATE USER \`my-user\` IDENTIFIED BY password ROLE admin;"'
```

**Comment by luigidellaquila** [comment] 2017-12-04 10:40
Hi @anthony-o 

Could you please try to run a 3.0.0-SNAPSHOT server instead of M2? The problem should be already solved

Thanks

Luigi

**Comment by anthony-o** [comment] 2017-12-04 14:12
@luigidellaquila yes with 3.0.0-SNAPSHOT as server, this bug disappear.
But what I don't really understand is why with 3.0.0m2 server, we can correctly create a DB & a user on it with a 2.2.30 client, but not with a 3.0.0-SNAPSHOT (nor a 3.0.0m2) client...

**Comment by luigidellaquila** [comment] 2017-12-04 14:53
Hi @anthony-o 

I guess it's a matter of changes in communication protocol. What matters anyway is that, as you confirmed, it's already fixed in latest snapshot

Thanks

Luigi

**Comment by luigidellaquila** [comment] 2017-12-28 09:50
Hi @anthony-o 

OrientDB v 3.0.0RC1 was released a few days ago. 
This issue is fixed is if you use both client and server from that version

Closing

Thanks

Luigi

**Closed by luigidellaquila** 2017-12-28 09:50 UTC
Labels: analyzing

**Comment by anthony-o** [comment] 2018-01-05 10:51
@luigidellaquila thank you, this issue seems to have disappeared, but a new one appeared: https://github.com/orientechnologies/orientdb/issues/7985
