### ISSUE TITLE
OCommandExecutionException during import of JSON file

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientdb#5227] opened 2015-10-26 20:26 UTC
Orientdb 2.1.4

- with clean database

```
Importing database database ../tt_prod-new.gz...
Started import of database 'plocal:../databases/tt_prod' from ../tt_prod-new.gz...
Non merge mode (-merge=false): removing all default non security classes
- Class _studio was removed.
- Class E was removed.
- Class V was removed.
- Class OTriggered was removed.
- Class ORestricted was removed.
- Class OSchedule was removed.
- Class ORIDs was removed.
- Class OFunction was removed.
Removed 8 classes.
Importing database info...OK
Importing clusters...
- Creating cluster 'internal'...OK, assigned id=0
- Creating cluster 'default'...OK, assigned id=3
- Creating cluster 'orole'...OK, assigned id=4
- Creating cluster 'ouser'...OK, assigned id=5
- Creating cluster 'ofunction'...OK, assigned id=6
- Creating cluster 'oschedule'...OK, assigned id=7
- Creating cluster 'orids'...OK, assigned id=8
- Creating cluster 'v'...OK, assigned id=9
- Creating cluster 'e'...OK, assigned id=10
- Creating cluster '_studio'...OK, assigned id=11
- Creating cluster 'node'...OK, assigned id=12
- Creating cluster 'root'...OK, assigned id=13
- Creating cluster 'broughtintoright'...OK, assigned id=14
- Creating cluster 'broughtintoleft'...OK, assigned id=15
- Creating cluster 'fitness'...OK, assigned id=16
- Creating cluster 'shopuser'...OK, assigned id=17
- Creating cluster 'de_business'...OK, assigned id=18
- Creating cluster 'de_root'...OK, assigned id=19
- Creating cluster 'de_shopuser'...OK, assigned id=20
- Creating cluster 'de_fitness'...OK, assigned id=21
- Creating cluster 'de_broughtintoleft'...OK, assigned id=22
- Creating cluster 'de_broughtintoright'...OK, assigned id=23
Rebuilding indexes of truncated clusters ...
- Cluster content was updated: rebuilding index 'ORole.name'... Index ORole.name was successfully rebuilt.
- Cluster content was updated: rebuilding index 'OUser.name'... Index OUser.name was successfully rebuilt.
Done 2 indexes were rebuilt.
Done. Imported 22 clusters
Importing database schema...{db=tt_prod} Error on importing schema
com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.select count(*) from `Node` where `Active`.type() not in ["BOOLEAN"] and `Active` is not null
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1465)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1433)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
        at com.orientechnologies.orient.core.metadata.schema.OClassImpl.checkPersistentPropertyType(OClassImpl.java:1899)
        at com.orientechnologies.orient.core.metadata.schema.OClassImpl.addPropertyInternal(OClassImpl.java:1595)
        at com.orientechnologies.orient.core.metadata.schema.OClassImpl.addProperty(OClassImpl.java:2292)
        at com.orientechnologies.orient.core.metadata.schema.OClassImpl.createProperty(OClassImpl.java:752)
        at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importProperty(ODatabaseImport.java:992)
        at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importSchema(ODatabaseImport.java:878)
        at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importDatabase(ODatabaseImport.java:430)
        at com.orientechnologies.orient.console.OConsoleDatabaseApp.importDatabase(OConsoleDatabaseApp.java:1711)
        at com.orientechnologies.orient.graph.console.OGremlinConsole.importDatabase(OGremlinConsole.java:126)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at com.orientechnologies.common.console.OConsoleApplication.execute(OConsoleApplication.java:392)
        at com.orientechnologies.common.console.OConsoleApplication.executeCommands(OConsoleApplication.java:253)
        at com.orientechnologies.common.console.OConsoleApplication.run(OConsoleApplication.java:142)
        at com.orientechnologies.orient.graph.console.OGremlinConsole.main(OGremlinConsole.java:64)
Caused by: java.lang.IllegalArgumentException: Class 'Node' was not found in database schema
        at com.orientechnologies.orient.core.iterator.ORecordIteratorClass.<init>(ORecordIteratorClass.java:75)
        at com.orientechnologies.orient.core.iterator.ORecordIteratorClass.<init>(ORecordIteratorClass.java:63)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.searchInClasses(OCommandExecutorSQLResultsetAbstract.java:469)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.searchInClasses(OCommandExecutorSQLResultsetAbstract.java:458)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchInClasses(OCommandExecutorSQLSelect.java:877)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.assignTarget(OCommandExecutorSQLResultsetAbstract.java:207)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.assignTarget(OCommandExecutorSQLSelect.java:474)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:456)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:427)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:90)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1452)
        ... 19 more
ERROR (4 entries): com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.select count(*) from `Node` where `Active`.type() not in ["BOOLEAN"] and `Active` is not null
Rebuild of stale indexes...
Start rebuild index ouser.name
Rebuild  of index ouser.name is completed.
Start rebuild index orole.name
Rebuild  of index orole.name is completed.
Stale indexes were rebuilt...
Deleting RID Mapping table...OK


Database import completed in 1432 ms
```

**Comment by luigidellaquila** [comment] 2015-10-29 16:57
Hi @StarpTech 

can you provide a sample export to reproduce the problem?

Thanks

Luigi

**Comment by StarpTech** [comment] 2015-10-31 16:22
@luigidellaquila  I can't because I removed the database and did an drag & drop replacement. But once I can reproduce this error again I will provide sample data. Thanks!

**Comment by luigidellaquila** [comment] 2015-11-02 15:37
Ok, thanks a lot!

Luigi

**Comment by maggiolo00** [comment] 2016-02-02 16:19
@StarpTech 

are you able to reproduce this?

**Comment by maggiolo00** [comment] 2016-05-18 16:23
@StarpTech 

do you still need help on this issue?

**Comment by lvca** [comment] 2016-05-26 20:48
Closing because no answer. In case please reopen/comment it.

**Closed by lvca** 2016-05-26 20:48 UTC
Labels: bug, waiting reply
