### ISSUE TITLE
Frozen threads found (potential deadlock) Orient 2.1.15

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#6090] opened 2016-05-05 16:05 UTC
Orient DB 2.1.15 running on Java 8 _66 Not sure if this is a Yourkit false positive, however, it is reporting a frozen thread. 

Frozen threads found (potential deadlock)
 
It seems that the following threads have not changed their stack for more than 10 seconds.
These threads are possibly (but not necessarily!) in a deadlock or hung.
 
message threading-2 <--- Frozen for at least 2d 0h 51m 24 sec
sun.misc.Unsafe.arrayBaseOffset(Class) Unsafe.java (native)
com.orientechnologies.common.directmemory.OUnsafeMemoryJava7.get(long, int) OUnsafeMemoryJava7.java:31
com.orientechnologies.common.directmemory.OUntrackedDirectMemoryPointer.get(long, int) OUntrackedDirectMemoryPointer.java:85
com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.getBinaryValue(int, int) ODurablePage.java:113
com.orientechnologies.orient.core.storage.impl.local.paginated.OClusterPage.getRecordVersion(int) OClusterPage.java:192
com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.readRecord(long) OPaginatedCluster.java:511
com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doReadRecord(OCluster, ORecordId) OAbstractPaginatedStorage.java:2021
com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OCluster, ORecordId) OAbstractPaginatedStorage.java:1752
com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(ORecordId, String, boolean, ORecordCallback) OAbstractPaginatedStorage.java:780
com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx$SimpleRecordReader.readRecord(OStorage, ORecordId, String, boolean, ORecordVersion) ODatabaseDocumentTx.java:3092
com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ORecordId, ORecord, ORecordVersion, String, boolean, boolean, boolean, OStorage$LOCKING_STRATEGY, ODatabaseDocumentTx$RecordReader) ODatabaseDocumentTx.java:1820
com.orientechnologies.orient.core.tx.OTransactionOptimistic.loadRecord(ORID, ORecord, String, boolean, boolean, boolean, OStorage$LOCKING_STRATEGY) OTransactionOptimistic.java:243
com.orientechnologies.orient.core.tx.OTransactionOptimistic.loadRecord(ORID, ORecord, String, boolean, boolean, OStorage$LOCKING_STRATEGY) OTransactionOptimistic.java:217
com.orientechnologies.orient.core.tx.OTransactionOptimistic.loadRecord(ORID, ORecord, String, boolean) OTransactionOptimistic.java:347
com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ORID) ODatabaseDocumentTx.java:1564
com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ORID) ODatabaseDocumentTx.java:122
com.orientechnologies.orient.core.id.ORecordId.getRecord() ORecordId.java:324
com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.getElement(Object) OrientBaseGraph.java:1520
..
java.util.concurrent.Executors$RunnableAdapter.call() Executors.java:511
java.util.concurrent.FutureTask.runAndReset() FutureTask.java:308
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor$ScheduledFutureTask) ScheduledThreadPoolExecutor.java:180
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run() ScheduledThreadPoolExecutor.java:294
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor$Worker) ThreadPoolExecutor.java:1142
java.util.concurrent.ThreadPoolExecutor$Worker.run() ThreadPoolExecutor.java:617
java.lang.Thread.run() Thread.java:745

**Comment by laa** [comment] 2016-05-05 17:42
Hi @jamieb22 ,
Do you have full thread dump ? What is your memory consumption ? Seems like you read data from memory swapped to disk.

**Comment by laa** [comment] 2016-05-24 08:15
Hi @jamieb22 any updates ?

**Comment by laa** [comment] 2016-06-10 05:22
Close it as duplication

**Closed by laa** 2016-06-10 05:22 UTC
Labels: storage team, waiting reply

**Comment by smolinari** [comment] 2016-06-10 05:39
@laa - Hey Andrey. Duplicate of what? Can you reference the other issue please? :smile: 

Thanks....

Scott
