### ISSUE TITLE
Unexpected behaviour of SELECT SKIP/LIMIT

### ISSUE THREAD

**Issue by crmayer** [orientechnologies/orientdb#4511] opened 2015-07-04 16:18 UTC
Using the SQL SKIP/LIMIT feature to navigate thru huge datasets chunk by chunk managed to bring down the memory requirements on the client side to a limited value independently of the target data sets cardianlity.
The server side to this approach, OTOH, delivered out of memory condition when the SKIP value went over a certain (huge) value. Looking at the dumps suggests that all SKIP records go live on the server side (memory wise), even if the client explicitly side shows no retrival intent.
Until being teached otherwise, it looks like this SKIP/LIMIT is only of limited (as the keyword already says :-) ) usability when it comes to real huge data sets. 
Technically, the solution "Use the RID-LIMIT" as presented in http://orientdb.com/docs/last/Pagination.html finally does the job pretty well, but from a simple user point of view, a scalable behavior might be expected from the plain SKIP/LIMIT approach as well.

**Comment by nagarajasr** [comment] 2015-07-07 06:19
Which version of OrientDB?

**Comment by crmayer** [comment] 2015-07-07 06:54
orientdb-community-2.0.12
orientdb-community-2.0.11

**Comment by luigidellaquila** [comment] 2015-07-08 14:09
Hi @crmayer 

could you please describe your use case? We know it can happen on queries with ORDER BY or particular subqueries (these operations are executed in memory in some situations), but I'd like to verify if it also happens on simple use cases.

Thanks

**Comment by crmayer** [comment] 2015-07-08 15:43
database structure (excerpt)
It was a very simple statement,
// SQL Statement entered into  OrientDB Workbench
SELECT FROM APage where propagated=false skip 500000 limit 10000
As the development advanced and the server infrastructure has been changed in the meantime, the problem refuses to appear instantly by trying to construct it and provoke it via Workbench Query.
It will take a while to rewind the test application and database, so this information here is just in advance of a more exact reconstruction of the factual reallity. 
Bottom line: It was a simple statement, details to follow.
Kind Regards

------ some additional info regarding the schema  -----
// mentioned for reasons of completeness, but supposed to be of no relevance for the outcome
alter database custom useLightweightEdges=false;
alter database DATETIMEFORMAT yyyy-MM-dd HH:mm:ss:SSS

CREATE class    DClosure extends V;
CREATE PROPERTY DClosure.created               DATE;
CREATE PROPERTY DClosure.completed             DATE;
CREATE PROPERTY DClosure.comment               STRING;
ALTER PROPERTY  DClosure.created               MANDATORY true;
CREATE PROPERTY DClosure.propagated            BOOLEAN;
ALTER PROPERTY  DClosure.propagated            MANDATORY true;

// needed for the @rid last based work around. 
// mentioned for reasons of completeness, but supposed to be of no relevance for the outcome
CREATE INDEX    DClosure.propagated ON DClosure (@rid, propagated) unique_hash_index;

CREATE class APage             extends DClosure;

**Comment by luigidellaquila** [comment] 2015-07-10 16:28
Hi @crmayer 

I was not able to reproduce it locally with a few tens of GB of data (on a simple PC) and with OrientDB v2.1 
If you could provide a deterministic way of reproducing it, it would help a lot

Thanks

**Comment by crmayer** [comment] 2015-07-13 08:09
I can confirm that it's not as trivial to reproduce as I suggested, so it might not happen too often in the wild. . Right now it's on my things-to-do stack. Thank you for now.

**Comment by luigidellaquila** [comment] 2015-07-13 09:20
Ok, thanks a lot. In the meantime I'm moving it to 2.2 
If you have news please let me know and I'll check it again

Thanks

**Closed** 2015-10-07 11:43 UTC
Labels: waiting reply
