### ISSUE TITLE
console.sh infinite error loop on 'connect remote:http://localhost root'

### ISSUE THREAD

**Issue by thoke** [orientechnologies/orientdb#4810] opened 2015-08-17 16:17 UTC
When inadvertently including a protocol scheme on the path portion of the url, an seemingly infinite Java exception loop occurs.  It's easy enough to reproduce and here is a transcript:

# /opt/orientdb/bin/console.sh

OrientDB console v.2.1.0 (build UNKNOWN@r; 2015-08-05 13:38:23+0000) www.orientdb.com
Type 'help' to display all the supported commands.
Installing extensions for GREMLIN language v.2.6.0

orientdb> connect remote:http://localhost root
Enter password:

Connecting to database [remote:http://localhost] with user 'root'...Can not open database with url http:/localhost
com.orientechnologies.common.io.OIOException: Cannot open a connection to remote server: http:/localhost
	at com.orientechnologies.orient.client.remote.OStorageRemote.getAvailableNetwork(OStorageRemote.java:2114)
	at com.orientechnologies.orient.client.remote.OStorageRemote.openRemoteDatabase(OStorageRemote.java:1841)
	at com.orientechnologies.orient.client.remote.OStorageRemote.open(OStorageRemote.java:222)
	at com.orientechnologies.orient.client.remote.OStorageRemoteThread.open(OStorageRemoteThread.java:89)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:249)
	at com.orientechnologies.orient.console.OConsoleDatabaseApp.connect(OConsoleDatabaseApp.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.orientechnologies.common.console.OConsoleApplication.execute(OConsoleApplication.java:392)
	at com.orientechnologies.common.console.OConsoleApplication.executeCommands(OConsoleApplication.java:253)
	at com.orientechnologies.common.console.OConsoleApplication.run(OConsoleApplication.java:142)
	at com.orientechnologies.orient.graph.console.OGremlinConsole.main(OGremlinConsole.java:64)
Caused by: com.orientechnologies.common.io.OIOException: Error on connecting to http:/localhost
	at com.orientechnologies.orient.client.remote.ORemoteConnectionManager.createNetworkConnection(ORemoteConnectionManager.java:246)
	at com.orientechnologies.orient.client.remote.ORemoteConnectionManager$1.createNewResource(ORemoteConnectionManager.java:80)
	at com.orientechnologies.orient.client.remote.ORemoteConnectionManager$1.createNewResource(ORemoteConnectionManager.java:77)
	at com.orientechnologies.common.concur.resource.OResourcePool.getResource(OResourcePool.java:94)
	at com.orientechnologies.orient.client.remote.ORemoteConnectionManager.acquire(ORemoteConnectionManager.java:101)
	at com.orientechnologies.orient.client.remote.OStorageRemote.getAvailableNetwork(OStorageRemote.java:2103)
	... 13 more
Caused by: java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:504)
	at java.lang.Integer.parseInt(Integer.java:527)
	at com.orientechnologies.orient.client.remote.ORemoteConnectionManager.createNetworkConnection(ORemoteConnectionManager.java:231)
	... 18 more
Can not open database with url http:/localhost
com.orientechnologies.common.io.OIOException: Cannot open a connection to remote server: http:/localhost
	at com.orientechnologies.orient.client.remote.OStorageRemote.getAvailableNetwork(OStorageRemote.java:2114)
	at com.orientechnologies.orient.client.remote.OStorageRemote.openRemoteDatabase(OStorageRemote.java:1841)
	at com.orientechnologies.orient.client.remote.OStorageRemote.open(OStorageRemote.java:222)
	at com.orientechnologies.orient.client.remote.OStorageRemoteThread.open(OStorageRemoteThread.java:89)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:249)
	at com.orientechnologies.orient.console.OConsoleDatabaseApp.connect(OConsoleDatabaseApp.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.orientechnologies.common.console.OConsoleApplication.execute(OConsoleApplication.java:392)
	at com.orientechnologies.common.console.OConsoleApplication.executeCommands(OConsoleApplication.java:253)
	at com.orientechnologies.common.console.OConsoleApplication.run(OConsoleApplication.java:142)
	at com.orientechnologies.orient.graph.console.OGremlinConsole.main(OGremlinConsole.java:64)
Caused by: com.orientechnologies.common.io.OIOException: Error on connecting to http:/localhost
	at com.orientechnologies.orient.client.remote.ORemoteConnectionManager.createNetworkConnection(ORemoteConnectionManager.java:246)
	at com.orientechnologies.orient.client.remote.ORemoteConnectionManager$1.createNewResource(ORemoteConnectionManager.java:80)
	at com.orientechnologies.orient.client.remote.ORemoteConnectionManager$1.createNewResource(ORemoteConnectionManager.java:77)
	at com.orientechnologies.common.concur.resource.OResourcePool.getResource(OResourcePool.java:94)
	at com.orientechnologies.orient.client.remote.ORemoteConnectionManager.acquire(ORemoteConnectionManager.java:101)
	at com.orientechnologies.orient.client.remote.OStorageRemote.getAvailableNetwork(OStorageRemote.java:2103)
	... 13 more
Caused by: java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:504)
	at java.lang.Integer.parseInt(Integer.java:527)
	at com.orientechnologies.orient.client.remote.ORemoteConnectionManager.createNetworkConnection(ORemoteConnectionManager.java:231)
	... 18 more
... repeat until CTRL-C ...

**Comment by xvik** [comment] 2015-08-17 17:13
I can confirm that acquiring remote client connection goes to infinite loop if target is not available. Affects both 2.1 and 2.0.14. 
I looked source (for both) and it seems that this is not a bug, but assumed behaviour. 

Such behaviour is not appropriate in many cases, for example:
1. Console connection (case above)
2. Unit testing remote connection failure (case from my tests)
3. Starting application with bad configuration (visually app will simply hang)

For me, it should be possible to enable inifinite retries, but not enabled by default.

**Comment by lvca** [comment] 2015-08-18 09:32
@xvik infinite retries is not the expected behavior, so this is definitely a bug. Did you find where the infinite loop happens in the code?

**Comment by xvik** [comment] 2015-08-18 16:00
for 2.1.0:
orientdb-client-2.1.0-sources.jar!/com/orientechnologies/orient/client/remote/OStorageRemote.java:1841
```java
network = getAvailableNetwork(currentURL);
```
Fails with OIOException. Exception catched here (lines 1892-1901)
```java
} catch (OIOException e) {
          if (network != null) {
            // REMOVE THE NETWORK CONNECTION IF ANY
            engine.getConnectionManager().remove(network);
            network = null;
          }
          OLogManager.instance().error(this, "Can not open database with url " + currentURL, e);
        }
```
And while condition (line 1919) restarts process
```java
} while (engine.getConnectionManager().getAvailableConnections(currentURL) > 0);
```

**Comment by xvik** [comment] 2015-08-18 16:07
for 2.0.14:
orientdb-client-2.0.14-sources.jar!/com/orientechnologies/orient/client/remote/OStorageRemote.java:1608
```java
network = getAvailableNetwork(currentURL);
```
1659-1665
```java
} catch (OIOException e) {
          if (network != null) {
            // REMOVE THE NETWORK CONNECTION IF ANY
            engine.getConnectionManager().remove(network);
            network = null;
          }
        }
```
1676
```java
} while (engine.getConnectionManager().getAvailableConnections(currentURL) > 0);
```

**Comment by lvca** [comment] 2015-08-19 16:00
Ok, here the key condition is:
```java
{} while (engine.getConnectionManager().getAvailableConnections(currentURL) > 0);
```
It should be exit when the available connections are 0. In case of error, this is executed:

```java
engine.getConnectionManager().remove(network);
```

That removes the current connection, so soon or later the connections should be 0. Please could you debug in your case which connections are still available?

**Comment by xvik** [comment] 2015-08-19 16:41
```java
network = getAvailableNetwork(currentURL);
```
Fails, so network is always null and
```java
engine.getConnectionManager().remove(network);
```
never happens
```java
} while (engine.getConnectionManager().getAvailableConnections(currentURL) > 0);
```
is always `while(100>0)`

It could work correctly if  `getAvailableNetwork` (actually `engine.getConnectionManager().acquire`) would not store pool until connection is checked. 
But in situation when pool is regestired and now url is unreachable (e.g. db go down after some time) there will still be infinite loop.

Honestly I dont see how this supposed to be working and cant suggest a fix

**Comment by tglman** [comment] 2015-09-03 11:12
this issue was caused by this fix: https://github.com/orientechnologies/orientdb/commit/d0eb90b4b0d9b27fb5f5540d1bd788328abdddce

now should be fixed, leaving open for missing test case.

**Comment by tglman** [comment] 2015-09-03 12:08
added test case closing

**Closed by tglman** 2015-09-03 12:08 UTC
Labels: bug, waiting reply

**Comment by bmcustodio** [comment] 2015-09-15 11:26
@lvca I believe this was the cause of #4771.
