### ISSUE TITLE
(Client=55) Index with ignoreNullValues:false not being used

### ISSUE THREAD

**Issue by garrett-gottlieb** [orientechnologies/orientdb#3239] opened 2014-12-19 08:34 UTC
With the following index:
```sql
CREATE INDEX Post.photo ON Post (photo) NOTUNIQUE_HASH_INDEX METADATA {ignoreNullValues : false}
```

And running the following query:
```sql
explain select from post where photo is not null
```

I get this result, where the reads are the size of my table (but most posts don't have photos):
```js
{
    "result": [
        {
            "@type": "d",
            "@version": 0,
            "documentReads": 717111,
            "current": "#19:720042",
            "documentAnalyzedCompatibleClass": 717111,
            "recordReads": 717111,
            "fetchingFromTargetElapsed": 9808,
            "evaluated": 717111,
            "elapsed": 9808.427,
            "resultType": "collection",
            "resultSize": 72514,
            "@fieldTypes": "documentReads=l,documentAnalyzedCompatibleClass=l,recordReads=l,fetchingFromTargetElapsed=l,evaluated=l,elapsed=f"
        }
    ],
    "notification": "Query executed in 9.816 sec. Returned 1 record(s)"
}
```

It shows that the index is not being used. Why?

**Comment by laa** [comment] 2015-01-06 06:24
It is sql issue assigned to  @luigidellaquila

**Comment by luigidellaquila** [comment] 2015-01-08 14:56
Hi @garrett-gottlieb 
This issue cannot be fixed by design: HashIndex implementations apply filters based on hashes (obviously) but a "not null" condition does not correspond to a single value, so it doesn't have a hash value...
Implementing this using a hash index would mean iterating on index keys and discarding only one (null), that in the average case would be comparable to iterating on the whole class.

I'm closing this, but if I missed something please reopen

**Closed by luigidellaquila** 2015-01-08 14:56 UTC
Labels: bug, client
