### ISSUE TITLE
Need to use gremlin in studio first in order to use in groovy in server side functions

### ISSUE THREAD

**Issue by kstock** [orientechnologies/orientdb#3906] opened 2015-04-09 20:19 UTC
In the studio, if I write a groovy function I am not able to use gremlin until I run a gremlin query in the studio console.
------

I've reproduced this in 2.0.5 and 2.0.4

This issue I created (Gremlin queries close database for session) is similar to
https://github.com/orientechnologies/orientdb/issues/3866
but that issue doesn't occur in 2.0.4 so I think it is a separate bug.

-----
How to replicate:

1) connect to a database in the studio.
2) go to the functions tab, create a function with the following code:
    `orient.getGraph().getVertices()._()[0]`

3)  The following error appears:

```
Erroronparsingscriptatposition#0: ErroronexecutionofthescriptScript: whuy------^org.codehaus.groovy.runtime.InvokerInvocationException: groovy.lang.MissingMethodException: Nosignatureofmethod: com.tinkerpop.blueprints.impls.orient.OrientElementScanIterable._()isapplicableforargumenttypes: ()values: [
]Possiblesolutions: is(java.lang.Object),
any(),
use([
    Ljava.lang.Object;),
    any(groovy.lang.Closure),
    use(java.lang.Class,
    groovy.lang.Closure),
    use(java.util.List,
    groovy.lang.Closure)groovy.lang.MissingMethodException: Nosignatureofmethod: com.tinkerpop.blueprints.impls.orient.OrientElementScanIterable._()isapplicableforargumenttypes: ()values: [       
    ]Possiblesolutions: is(java.lang.Object),
    any(),
    use([
        Ljava.lang.Object;),
        any(groovy.lang.Closure),
        use(java.lang.Class,
        groovy.lang.Closure),
        use(java.util.List,
        groovy.lang.Closure)Nosignatureofmethod: com.tinkerpop.blueprints.impls.orient.OrientElementScanIterable._()isapplicableforargumenttypes: ()values: [            
        ]Possiblesolutions: is(java.lang.Object),
        any(),
        use([
            Ljava.lang.Object;),
            any(groovy.lang.Closure),
            use(java.lang.Class,
            groovy.lang.Closure),
            use(java.util.List,
            groovy.lang.Closure)
```
4) click browse in studio, execute the following:

`g.V[0]`

5) return to functions, retry running the function again.
    `orient.getGraph().getVertices()._()[0]`
 It will work.

**Comment by wcraigtrader** [comment] 2015-05-18 18:39
Studio probably needs to make a call to `Gremlin.load()` during its startup; presumably the browser tab is making the call, but not soon enough for the function tab to take advantage.

**Comment by tglman** [comment] 2015-07-07 17:15
Hi the issue is that the function `_` is a gremlin specific api and is not declared in the basic groovy functions, but when you run some gremlin api become available in the global classloader so it can be used also from other groovy functions.

so is wrong use that api from groovy functions.

We could anyway add the support of gremlin specific api in the functions, in future, but we can open another issue for that, i'm closing this.

**Closed by tglman** 2015-07-07 17:15 UTC
Labels: bug
