### ISSUE TITLE
NullPointerException when select records

### ISSUE THREAD

**Issue by DaisyShi** [orientechnologies/orientdb#7893] opened 2017-11-20 05:31 UTC
## Expected behavior  
Select records 

## Actual behavior  
java.lang.NullPointerException
$ANSI{green {db=test}} Fetching error on record #118:2120472
java.lang.NullPointerException
$ANSI{green {db=test}} Fetching error on record #118:2914162
java.lang.NullPointerException
$ANSI{green {db=test}} Fetching error on record #118:2914162
java.lang.NullPointerException
$ANSI{green {db=test}} Fetching error on record #118:2914162
java.lang.NullPointerException
$ANSI{green {db=test}} Exception `720835B2` in storage `test`
com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.select @class , $depth , risk_type, remark_type, count(*) as count , sum(OUT().size()) as out_edgenum, sum(IN().size()) as in_edgenum from  (TRAVERSE OUT(),IN() FROM #595:671186 MAXDEPTH 3 LIMIT 3000 STRATEGY BREADTH_FIRST) group by @class , $depth, risk_type, remark_type
        DB name="test"
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:3229)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:3146)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
        at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:106)
        at com.orientechnologies.orient.graph.server.command.OServerCommandPostCommandGraph.execute(OServerCommandPostCommandGraph.java:37)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:169)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:621)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Caused by: java.lang.NullPointerException
$ANSI{green {db=test}} Exception `720835B2` in storage `test`
com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.select @class , $depth , risk_type, remark_type, count(*) as count , sum(OUT().size()) as out_edgenum, sum(IN().size()) as in_edgenum from  (TRAVERSE OUT(),IN() FROM #595:671186 MAXDEPTH 3 LIMIT 3000 STRATEGY BREADTH_FIRST) group by @class , $depth, risk_type, remark_type
        DB name="test"
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:3229)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:3146)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
        at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:106)
        at com.orientechnologies.orient.graph.server.command.OServerCommandPostCommandGraph.execute(OServerCommandPostCommandGraph.java:37)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:169)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:621)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Caused by: java.lang.NullPointerException
Internal server error:

## Steps to reproduce  
When we use the database, the disk suddenly filled. Then we restarted the service and released the cache. After that, we executed the normal query operation (select) ,but got many null point exceptions.

**Comment by luigidellaquila** [comment] 2017-11-20 07:41
Hi @DaisyShi 

My quick advice is to upgrade to 2.2.30, we fixed a lot of problems since 2.2.23, maybe this is one of them.

Is there a chance for me to have a copy of the DB (or of a DB with the same problem) so that I can debug and fix it? It's likely related to some dangling pointers (eg. edges that point to non existing  vertices), but unfortunately the stack trace does not give any hint on where the problem is exactly happeing...

Thanks

Luigi

**Comment by luigidellaquila** [comment] 2017-11-27 16:21
Hi @DaisyShi 

Any news on this issue? Did you have a chance to try latest version?

Thanks

Luigi

**Comment by DaisyShi** [comment] 2017-11-28 07:21
Hi @luigidellaquila 
Thanks a lot for you kindly reply, we haven't upgrade our version because of the request of business side.

**Comment by DaisyShi** [comment] 2017-11-28 07:22
Hi @
Thanks a lot for you kindly reply, we haven't upgrade our version because of the request of business side.

DaisyShi

**Comment by DaisyShi** [comment] 2017-11-28 07:22
Hi luigidellaquila
Thanks a lot for you kindly reply,we haven't upgrade our version because of the request of business side.

DaisyShi

**Comment by luigidellaquila** [comment] 2017-12-28 09:51
Hi @DaisyShi 

Did you have a chance to try latest OrientDB versions? It's pretty hard for me to help you if you cannot upgrade to a fixed version...

Thanks

Luigi

**Comment by luigidellaquila** [comment] 2018-01-19 15:15
Hi @DaisyShi 

I'm closing this issue, as I have no way to reproduce it. Please feel free to re-open if you have an update

Thanks

Luigi

**Closed by luigidellaquila** 2018-01-19 15:15 UTC
Labels: waiting reply
