### ISSUE TITLE
OrientDB generates temporaty @rid during transaction

### ISSUE THREAD

**Issue by schernolyas** [orientechnologies/orientdb#6120] opened 2016-05-11 14:41 UTC
OrientDB generates temporaty @rid during transaction.  In this way, Hibernate OGM  links entities by the @rid. And .... the link is incorrect after transaction commited.

Test examle is [OrientDbLinkTest.java](https://github.com/schernolyas/hibernate-ogm/blob/use_links/orientdb/src/test/java/org/hibernate/datastore/ogm/orientdb/OrientDbLinkTest.java). At the example, Entity 'Card' has incorrect links (see row 108)

Full hibernate ogm debug output attached.
[org.hibernate.datastore.ogm.orientdb.OrientDbLinkTest-output.txt](https://github.com/orientechnologies/orientdb/files/259545/org.hibernate.datastore.ogm.orientdb.OrientDbLinkTest-output.txt)

**Comment by schernolyas** [comment] 2016-05-11 14:47
Version of orientdb: 2.2.0-rc1

**Comment by tglman** [comment] 2016-05-11 15:19
Thanks @schernolyas we will check ASAP

**Comment by schernolyas** [comment] 2016-05-14 03:27
Hi @tglman !
Have You any progress? Which milestone will contains fix?

**Comment by lvca** [comment] 2016-05-16 11:34
Do you have logs? My theory is that the first time it creates a new class in background and to do this operation, the TX is committed and restarted.

@schernolyas Could you please check it? Could you create the OrientDB class before the TX?

**Comment by schernolyas** [comment] 2016-05-16 12:13
HI @lvca !
I attached full hibernate ogm log already. You can see file OrientDbLinkTest-output.txt. The file contains a tons of text. But You can fond usefull information by search word "insert".

JPA EntityManager can not work without transaction and throw Exception.

**Comment by lvca** [comment] 2016-05-16 12:41
I cannot find `must be executed outside active transaction`. When do you create the respective OrientDB classes?

**Comment by schernolyas** [comment] 2016-05-16 12:44
@lvca Can You return to hangout?

**Comment by schernolyas** [comment] 2016-05-16 12:59
@lvca 

Copy from hangout (chat):
_______________
Luca  please find row by " 14:01:42,248 DEBUG"
it is start of orientdb transaction N 1 in connection
during transaction N1 I execute "insert" query insert into Card content {"pan":"4444"} return @rid  (at 14:01:42,244)
and at  14:01:42,233  I get result: Key: @rid (#45:-2)
and transaction N1 was commited at 14:01:42,261
and 3 rows was persisted
_________________________
About  "I cannot find must be executed outside active transaction" ....What do You mean?

**Comment by schernolyas** [comment] 2016-05-16 13:22
@lvca 
Copy from hangout
___________________________
Yes  YOu are right absolutly
And ...  How we can fix the situation?
I guess  that OrientDB  have to create persistent RecordId at once
I offer next algorithm
1) create persistent RecordId for new record during transaction and the recordid as "used"
2) if transaction commited .... then all right
3) if transaction rollbacked ... then mark the recordid as "free" and link the recordid with other row
is the  algorithm implementable?
__________________________________

**Comment by schernolyas** [comment] 2016-05-16 15:47
@lvca 
____________________________
And it was without transaction.  I know  that OrientDB not allow change schema during transaction
About terms
Class is same a table
Entity  (is JPA term) is same data in table/class
Schema (tables/classes, indexes, sequences ans stored procedues) created during EntityManager instantiation
It occurs at this https://github.com/schernolyas/hibernate-ogm/blob/use_links/orientdb/src/test/java/org/hibernate/datastore/ogm/orientdb/OrientDbLinkTest.java#L50
Transaction for create new entities and links them is https://github.com/schernolyas/hibernate-ogm/blob/use_links/orientdb/src/test/java/org/hibernate/datastore/ogm/orientdb/OrientDbLinkTest.java#L80:L105
_____________________________

**Comment by schernolyas** [comment] 2016-05-17 09:52
Hi @lvca !

Have You any questions about the problem?

**Comment by schernolyas** [comment] 2016-05-17 17:46
Hi @lvca !

Have You any questions about the problem?

**Comment by schernolyas** [comment] 2016-05-21 17:41
Hi @lvca !

Have You any progress?  Which milestone will conteins fix for the issue?

A lot of thanks!

**Comment by lvca** [comment] 2016-05-24 13:00
To recap, what's the sql you execute? just 1 statement insert? Can you copy and paste only the relevant snippet here?

**Comment by schernolyas** [comment] 2016-05-24 13:23
Hi @lvca !
During transaction, I execute queries:
1) select executeQuery('insert into Card content {"pan":"4444"} return @rid');
   result RID #45:-2
2) select executeQuery('insert into Payment content {"created":"2016-05-11 14:01:42","sum":"1"} return @rid') ; result RID: #61:-3
3) select executeQuery('insert into Payment content {"created":"2016-05-11 14:01:42","sum":"2"} return @rid') ; result RID: #62:-4

Body of stored procedure executeQuery:
CREATE FUNCTION executeQuery "return orient.getDatabase().command(insertQuery);" PARAMETERS [insertQuery] LANGUAGE GROOVY

Problem that there RID is actual during the transaction only.

**Comment by lvca** [comment] 2016-05-24 13:25
Why are you creating a new function in Groovy just to execute that SQL?

**Comment by schernolyas** [comment] 2016-05-24 13:27
@lvca , because OrientDB implenentation of JDBC driver not allow to execute queries like mine

**Comment by lvca** [comment] 2016-05-24 13:30
Why not? Have you tried:

```
ResultSet rs = conn.createStatement().executeQuery("insert into Card content {"pan":"4444"} return @rid");
```

**Comment by schernolyas** [comment] 2016-05-24 13:32
@lvca   Yes of course!  It is first that I did.  I got exception.

**Comment by lvca** [comment] 2016-05-24 14:07
Ok, just created: https://github.com/orientechnologies/orientdb/issues/6205

**Comment by lvca** [comment] 2016-05-24 14:19
Done: https://github.com/orientechnologies/orientdb/issues/6205

**Comment by lvca** [comment] 2016-05-24 14:20
Could you try it (it's in last develop branch)

**Comment by schernolyas** [comment] 2016-05-24 14:33
@lvca  Okey. I will try.  I will attach results .

**Comment by schernolyas** [comment] 2016-05-24 14:47
@lvca I got exception. See part of stack trace

Caused by: com.orientechnologies.orient.core.exception.OCommandExecutionException: Cannot execute non idempotent command
        Storage URL="memory:test"
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:2489)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:2474)
        at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:78)
        at com.orientechnologies.orient.core.sql.query.OSQLAsynchQuery.run(OSQLAsynchQuery.java:74)
        at com.orientechnologies.orient.core.sql.query.OSQLSynchQuery.run(OSQLSynchQuery.java:85)
        at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.query(ODatabaseDocumentTx.java:672)
        at com.orientechnologies.orient.jdbc.OrientJdbcPreparedStatement.executeQuery(OrientJdbcPreparedStatement.java:75)

**Comment by lvca** [comment] 2016-05-24 15:23
I created this test case and passed:
```java
@Test
  public void testInsertRIDReturning() throws Exception {
    conn.createStatement().executeQuery("CREATE CLASS Insertable ");
    ResultSet result = conn.createStatement().executeQuery("INSERT INTO Insertable(id) VALUES(1) return @rid");

    assertThat(result.next()).isTrue();
    assertThat(result.getObject("id")).isNotNull();
  }
```

**Comment by schernolyas** [comment] 2016-05-24 15:52
@lvca 
 I guess that You do it in non-transactional environment.
I using pooled connection and transaction.

The exception show all

**Comment by schernolyas** [comment] 2016-05-25 13:35
Hi @lvca 

I sended to You some presentation that describe a problem with issue 6120
I hope ...  You will not a have a questions.
But .... main question is ... Can I use @RID as primary key ?

**Comment by schernolyas** [comment] 2016-05-31 15:13
Hi @lvca !

Have You any decision about the issue?
Can I help?

**Comment by schernolyas** [comment] 2016-06-03 14:50
Hi @lvca !

What is status of the bug?

**Comment by lvca** [comment] 2017-02-18 08:04
I'd like to follow up on this. Is this issue still relevant? Can I close it?

**Comment by schernolyas** [comment] 2017-02-18 10:34
Hi Luca!
If You think that it is not bug than close it.

With best regards, Sergey Chernolyas

18.02.2017 11:04 пользователь "Luca Garulli" <notifications@github.com>
написал:

**Comment by lvca** [comment] 2017-02-22 12:52
Forwarding to @luigidellaquila.

**Comment by luigidellaquila** [comment] 2017-02-22 13:26
Hi @lvca 

This issue is specific to tx behavior, that is a basic behavior in OrientDB so it cannot be changed.
I think the problem here is that when the transaction is committed, there is no callback mechanism to notify that the RID was updated.
For sure the issue is still there, for sure it's hard to fix in v 2.x, maybe we can do something in 3.0 but I have to check with @tglman (for the tx lifecycle) and @robfrank (for JDBC implications). 

Thanks

Luigi

**Comment by schernolyas** [comment] 2017-02-26 17:50
HI @luigidellaquila 

I demonstate the problem.

For example Entity A and Entity B have 'one-to-many' link.
1) hibernate open transaction
2) hibernate persist entity a and save it to own cache with @rid 21:-1
3) hibernate persist entity b ans save it to own cache with @rid 22:-1
4) hibernate update entity b and store link to entity a (  link to @rid 21:-1)
5) hibernate commit the transaction
6) ORIENTDB CHANGE @RID OF THESE ENTITIES AND NOW ENTITY WITH @RID 22:-1 NOT EXISTS!!!
The feature make impossible to use system field @rid as primary key.

**Closed** 2021-08-05 10:59 UTC
Labels: bug
