### ISSUE TITLE
How to update "out" or "in" of a EDGE 

### ISSUE THREAD

**Issue by petervavro** [orientechnologies/orientdb#8878] opened 2019-05-25 17:57 UTC
### OS: 10.14.4  

I am trying to update "out" value of a EDGE class, e.g. : 
`UPDATE EDGE TableEdge SET out=#53:23 WHERE out.name="a";`

## Actual behavior  
I can see the update here : `SELECT out FROM TableEdge WHERE out=#53:23;`
**But there is no change here** : ```SELECT out(`TableEdge`) as outValue FROM #53:23;```
so, `outValue = "[]"`

TableEdge is defined like : 
```
CREATE CLASS TableEdge IF NOT EXISTS EXTENDS E;
ALTER CLASS TableEdge SUPERCLASS +OTriggered;
CREATE PROPERTY TableEdge.out LINK;
ALTER PROPERTY TableEdge.out MANDATORY TRUE;
CREATE PROPERTY TableEdge.in LINK;
ALTER PROPERTY TableEdge.in MANDATORY TRUE;
CREATE PROPERTY TableEdge.someValue SHORT;
```

What is wrong here please ?

**Comment by luigidellaquila** [comment] 2019-05-27 08:06
Hi @petervavro 

I just tested v 3.0.19 with your schema plus the following:

```
create class Person extends V;

create vertex Person set name = 'a'; /* #57:0 */
create vertex Person set name = 'b'; /* #58:0 */
create vertex Person set name = 'c'; /* #59:0 */

create edge TableEdge from (select from person where name = 'a') to (select from person where name = 'b'); /* #45:0 */

UPDATE EDGE TableEdge SET out=#59:0 WHERE out.name="a";
```

and it seems to work fine. Any clue on how to reproduce?

Thanks

Luigi

**Comment by tglman** [comment] 2020-06-03 16:56
Hi,

Cannot reproduce and not more infos, closing

**Closed by tglman** 2020-06-03 16:56 UTC
