### ISSUE TITLE
Unable to store data to the database using orient db etl

### ISSUE THREAD

**Issue by vlnj** [orientechnologies/orientdb#6419] opened 2016-07-14 11:34 UTC
## Expected behavior and actual behavior

Im running oetl.bat to import data to database using json file. The oetl process will success, but it did not store data to the database, Im using document type database 

## Note

Here is my etl_config.json and input json file

{  
   "config":{  
      "log":"debug"
   },   
   "begin": [],  
   "source":{  
      "file":{  
         "path":"C:/Users/lnvithanage/Desktop/Testting/server/webserver/bin/work/reports/report.json"
      }
   },
   "extractor":{  
      "json":{}
   },  
   "transformers" : [],  
   "loader":{  
      "orientdb":{  
         "dbURL":"remote:localhost/Test",
         "dbUser":"root",
         "serverUser":"root",
         "serverPassword":"root",
         "dbPassword":"root",
         "standardElementConstraints":false,
         "tx":false,
         "wal":false,
         "batchCommit":1000,
         "dbType":"document"
		 
      }
   },  
     "end": []
}

----------------------------------------------------------------------------------------------------

[  
   {  
      "@type":"d",
      "@version":1,
      "@class":"Project",
      "moduleName":"HibernateExample",
      "isSuccess":false,
      "fromDate":"1970-01-01 05:30:00",
      "toDate":"2016-06-21 14:22:47"
   },
   {  
      "@type":"d",
      "@version":1,
      "@class":"Project",
      "moduleName":"HibernateExample",
      "isSuccess":false,
      "fromDate":"1970-01-01 05:30:00",
      "toDate":"2016-06-21 14:30:43"
   },
   {  
      "@type":"d",
      "@version":1,
      "@class":"Project",
      "moduleName":"HibernateExample",
      "isSuccess":false,
      "fromDate":"1970-01-01 05:30:00",
      "toDate":"2016-06-21 14:32:04"
   },{  
      "@type":"d",
      "@version":1,
      "@class":"UpdateDetails",
      "moduleName":"HibernateExample",
      "toolName":"Hibernate",
      "timeOfLastRun":"2016-06-21 14:34:44",
      "timeOfLastSuccess":"2016-06-21 14:34:44",
      "timeOfFirstRun":"2016-06-21 14:34:44",
      "timeOfLastFullRun":"2016-06-21 14:34:44"
   }
   ]

### Runninng Mode
- [ ] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [x] Remote

### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition
- [x] orientdb-community single server

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [x] v2.2.x - Please specify last number: orientdb-community-2.2.4

### Operating System
- [ ] Linux
- [ ] MacOSX
- [x] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [ ] 7
- [x] 8

**Comment by robfrank** [comment] 2016-07-14 16:25
my sugestion is to change dbuser/dbpassword to "admin","admin"

**Comment by vlnj** [comment] 2016-07-15 02:35
I tried with "admin","admin" but it did not work

Here is the console out put


C:\Project\OrientDB\orientdb-community-2.2.4\bin>oetl.bat etl_config.json
OrientDB etl v.2.2.4 (build 2.2.x@rf5282664db9300ef3358fb4d7e2066ad418c2e61; 2016-07-08 12:30:59+0000) www.orientdb.com
BEGIN ETL PROCESSOR
[file] INFO Reading from file C:/Users/lnvithanage/Desktop/Testting/server/webserver/bin/work/reports/report.json with encoding UTF-8
Started execution with 1 worker threads
Start extracting
[orientdb] INFO committing
Pipeline worker done without errors:: true
all items extracted
END ETL PROCESSOR
extracted 4 entries (0 entries/sec) - 4 entries -> loaded 4 documents (0 documents/sec) Total time: 523ms [0 warnings, 0 errors]

**Comment by vlnj** [comment] 2016-07-16 02:31
Any update on this

**Comment by vlnj** [comment] 2016-07-18 05:33
@robfrank hi any update about this issue?

**Comment by robfrank** [comment] 2016-07-18 13:41
hi, there's a bug for sure, because the ETL works properly with 2.1.x and doesn't load documents on 2.2.4.

**Comment by robfrank** [comment] 2016-07-19 08:37
Hi, bug is solved and will be on 2.2.5, but you need at least to modify your configuration
```
{
  "config": {
    "log": "debug"
  },
  "begin": [],
  "source": {
    "file": {
      "path": "/Users/frank/local/orientdb/gh-6419/report.json"
    }
  },
  "extractor": {
    "json": {}
  },
  "transformers": [
    {
      "log": {}
    }
  ],
  "loader": {
    "orientdb": {
      "dbURL": "plocal:YOUR PATH",
      "dbUser": "admin",
      "dbPassword": "admin",
      "cluster": "fucked",
      "serverUser": "root",
      "serverPassword": "root",
      "standardElementConstraints": false,
      "tx": false,
      "wal": false,
      "batchCommit": 1000,
      "dbType": "document",
      "classes": [
        {
          "name": "Project"
        },
        {
          "name": "UpdateDetails"
        }
      ]
    }
  },
  "end": []
}

```

note the **classes** section

**Comment by vlnj** [comment] 2016-07-20 01:57
@robfrank Thank you for your help, I will try it with the latest version.

**Comment by vlnj** [comment] 2016-07-25 06:32
@robfrank, 

I was able to extract data using latest etl (2.2.5) for schemaless classes but, it did not work for schemaful classes

**Comment by robfrank** [comment] 2016-07-25 08:41
Maybe it's time for another issue? BTW, can you send me more details: sample data, configuration, step to reproduce the problem. The better would be a failing test case  :)

**Comment by vlnj** [comment] 2016-07-25 09:44
Im using the same data set related to previous issue. I changed the configurations as well.  here is the console output.

C:\Project\OrientDB\orientdb-community-2.2.5\bin>oetl.bat etl_config.json
OrientDB etl v.2.2.5 (build 2.2.x@r393af9c5a3e4a4408440a9376283a26d2d3d3c7b; 2016-07-20 06:03:46+0000) www.orientdb.com
BEGIN ETL PROCESSOR
[file] INFO Reading from file C:/Users/lnvithanage/Desktop/Testting/server/webserver/bin/work/reports/report.json with encoding UTF-8
Started execution with 1 worker threads
[orientdb] DEBUG orientdb: found 0 documents in class 'null'
[orientdb] DEBUG orientdb: found 0 documents in class 'null'
Start extracting
[0:log] DEBUG Transformer input: Project{moduleName:HibernateExample,isSuccess:false,fromDate:1970-01-01 05:30:00,toDate:2016-06-21 14:22:47}
[0:log] INFO Project{moduleName:HibernateExample,isSuccess:false,fromDate:1970-01-01 05:30:00,toDate:2016-06-21 14:22:47}
[0:log] DEBUG Transformer output: Project{moduleName:HibernateExample,isSuccess:false,fromDate:1970-01-01 05:30:00,toDate:2016-06-21 14:22:47}
Error in Pipeline execution: com.orientechnologies.orient.core.exception.ODatabaseException: Error during saving of record with rid #-1:-1
        DB name="Test"
ETL process has problem: java.util.concurrent.ExecutionException: com.orientechnologies.orient.etl.OETLProcessHaltedException: Halt
END ETL PROCESSOR
+ extracted 4 entries (0 entries/sec) - 4 entries -> loaded 0 documents (0 documents/sec) Total time: 404ms [0 warnings, 1 errors]

**Comment by robfrank** [comment] 2016-07-25 10:17
ok, but what do you mean for "I was able to extract data using latest etl (2.2.5) for schemaless classes but, it did not work for schemaful classes", Please be more specific. How did you define the  schema? When you define it? I'm sorry, but I need details. thanks

**Comment by vlnj** [comment] 2016-07-25 11:03
I mean, without creating a classes and fields in the database it works (etl automatically create the classes and store data). if there is predefined classes in the database it does not work.

**Comment by robfrank** [comment] 2016-07-25 11:49
If you have a predefined schema, strip out the classes part from the config.

**Comment by vlnj** [comment] 2016-07-25 13:10
I removed the classes but it did not work.

**Comment by robfrank** [comment] 2016-07-25 13:43
please, describe your scenario. Are you pumping data on an empty database? Have you got indexes? Constraints? or did you create empty classes?

**Comment by vlnj** [comment] 2016-07-25 14:11
I have two classes with the fields.

when i define classes in the database etl does not work. but without classes it successfully inserted data to the database . (to an empty database)

**Comment by vlnj** [comment] 2016-07-25 14:22
let me explain simply.

I have two schemaful classes in my database.
Im trying to insert data to database using json file, but etl process failed.

then i removed the classes from the database and ran the etl, then etl successfully inserted data to database

**Comment by vlnj** [comment] 2016-07-29 02:09
@robfrank any update on this?

**Comment by robfrank** [comment] 2016-07-29 06:46
can you post the schema you cretated on db?

**Comment by vlnj** [comment] 2016-08-01 09:03
Hi sorry for the delay, here is the schema

CREATE CLASS Project
CREATE PROPERTY Project.moduleName STRING
CREATE PROPERTY Project.isSuccess BOOLEAN
CREATE PROPERTY Project.fromDate DATETIME
CREATE PROPERTY Project.toDate DATETIME

CREATE CLASS UpdateDetails
CREATE PROPERTY UpdateDetails.moduleName STRING
CREATE PROPERTY UpdateDetails.toolName STRING
CREATE PROPERTY UpdateDetails.timeOfLastRun DATETIME
CREATE PROPERTY UpdateDetails.timeOfLastSuccess DATETIME
CREATE PROPERTY UpdateDetails.timeOfFirstRun DATETIME
CREATE PROPERTY UpdateDetails.timeOfLastFullRun DATETIME

**Comment by robfrank** [comment] 2016-08-01 10:06
thx, I'll write a tests in the afternoon.

**Comment by robfrank** [comment] 2016-08-02 09:21
Hi, I've added a (green) test that mimic your scenario. 

https://github.com/orientechnologies/orientdb/commit/4581ed0b07c0d55a3b68f890a0c280abd5dd7b91

**Comment by vlnj** [comment] 2016-08-02 12:28
Hi @robfrank,

Can you check whether your test cases pass for this **json**.

[  
   {  
      "@class":"User",
      "birthday":"1970-01-01 05:30:00"
   }
   ]

Note that this json has _not only strings but also datetime and boolean_ fields

**Comment by vlnj** [comment] 2016-08-02 12:32
Also check for **CSV** with a boolean field.

**Comment by vlnj** [comment] 2016-08-03 08:42
Hi @robfrank ,

Any update on this

**Comment by robfrank** [comment] 2016-08-03 08:48
I'm on this right now

**Comment by robfrank** [comment] 2016-08-03 08:48
I'm on this right now

**Comment by robfrank** [comment] 2016-08-03 09:44
I found a bug on boolean type inference.
Added some tests to avoid regressions. 
This fix will be part of 2.2.7, or you can use snapshots that will be available in a couple of hours.

**Closed by robfrank** 2016-08-03 09:44 UTC
Labels: bug, waiting reply

**Comment by vlnj** [comment] 2016-08-03 10:10
@robfrank not only boolen fileds but also datetime fields with json source.

**Comment by robfrank** [comment] 2016-08-03 11:44
just added a test for json type mapping: https://github.com/orientechnologies/orientdb/commit/3d512d0ef497467dfa2edff3dda0ea9a1f9fc03e

all is ok

**Comment by vlnj** [comment] 2016-08-03 14:31
@robfrank 
Thank you for your help, i will check with the 2.2.7
