### ISSUE TITLE
Cannot open Studio in IE11

### ISSUE THREAD

**Issue by arkolesnik** [orientechnologies/orientdb#7660] opened 2017-08-16 08:43 UTC
## Expected behavior  
Once the server up and running, Studio should open in all supported browsers, including Internet Explorer. 

## Actual behavior  
Studio doesn't open in IE11, while everything is ok in other browsers, including Edge.
JS error: 
SCRIPT5007: Unable to get property 'apply' of undefined or null reference

## Steps to reproduce  
1. Start the server.
2. Try to open Studio in Internet Explorer 11 by http://localhost:2480/studio/index.html

<img width="959" alt="ie_studio" src="https://user-images.githubusercontent.com/4200801/29354959-e3ab9804-8277-11e7-82bd-fa458a5a5e02.png">

**Comment by santo-it** [comment] 2017-08-16 09:36
Hi,

Thanks - This is a duplicate of https://github.com/orientechnologies/orientdb/issues/7209

**Closed by santo-it** 2017-08-16 09:36 UTC
