### ISSUE TITLE
v2.1.8 produces lots of warnings

### ISSUE THREAD

**Issue by mriehl** [orientechnologies/orientdb#5496] opened 2015-12-21 11:48 UTC
After upgrading from v2.1.7 to v2.1.8 I'm seeing a lot of errors like this:

```
2015-12-21 12:46:08:784 WARNI ->xx.xx.xx.xx: Error on invalid content:

 [ONetworkProtocolHttpDb]
```

Looking through the code I see that the invalid content is actually appended to the log message, but it seems to be empty in this case.
I have no idea what is causing this, but I have disabled all loadbalanced traffic to the node. So this seems to be caused by some internal processes e.G. hazelcast maybe?

Note that everything seems to work fine, it's just that my log is full of WARNINGs.

**Comment by tglman** [comment] 2016-05-09 15:09
hi @mriehl,

Did you try a more recent version? do you still have this warnings ?

**Comment by mriehl** [comment] 2016-05-09 18:22
Hi,

Thanks for checking back @tglman .
I still see the warnings in the latest stable version. I am pretty sure it's due to the loadbalancer health monitor which runs even when the node is disabled.

I commented out the warning message before packaging so it's not really an issue for me. Do you want me to close it?

**Comment by tglman** [comment] 2016-05-10 13:43
Hi @mriehl,

Looking to the code it seems the issue is on the http request, that  is not actually what orient expect, is there any chance that you can send us some information of which kind of request is going wrong, i think is some http "OPTIONS" or similar kind of request not supported by orientdb today.

**Comment by tglman** [comment] 2016-06-22 15:25
closing this

**Closed by tglman** 2016-06-22 15:25 UTC
Labels: bug, wontfix
