### ISSUE TITLE
can't start orientdb server

### ISSUE THREAD

**Issue by AhrimanSefid** [orientechnologies/orientdb#7773] opened 2017-09-26 13:35 UTC
### OrientDB Version: <version here>  
orientdb-community-2.2.14
### Java Version: <version here>  
8
### OS: <os here>  
win 2012 x64

Hi,

We can't start orientdb server send Error Log:

```
2017-09-26 07:38:38:712 INFO  Loading configuration from: C:/orientdb-community-2.2.14/config/orientdb-server-config.xml... [OServerConfigurationLoaderXml]
2017-09-26 07:38:39:712 INFO  OrientDB Server v2.2.14 (build 2.2.x@r483093384e4fdbe825e2de0950f007776ee27a84; 2016-12-22 14:57:07+0000) is starting up... [OServer]
2017-09-26 07:38:39:759 INFO  Databases directory: C:\orientdb-community-2.2.14\databases [OServer]Error during initialization of engine 'plocal', engine will be removed
java.lang.reflect.InaccessibleObjectException: Unable to make public long com.sun.management.internal.OperatingSystemImpl.getTotalPhysicalMemorySize() accessible: module jdk.management does not "opens com.sun.management.internal" to unnamed module @39d1a739
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Unknown Source)
	at java.base/java.lang.reflect.Method.setAccessible(Unknown Source)
	at com.orientechnologies.common.util.OMemory.getPhysicalMemorySize(OMemory.java:66)
	at com.orientechnologies.orient.core.engine.OMemoryAndLocalPaginatedEnginesInitializer.configureDefaultDiskCacheSize(OMemoryAndLocalPaginatedEnginesInitializer.java:80)
	at com.orientechnologies.orient.core.engine.OMemoryAndLocalPaginatedEnginesInitializer.configureDefaults(OMemoryAndLocalPaginatedEnginesInitializer.java:63)
	at com.orientechnologies.orient.core.engine.OMemoryAndLocalPaginatedEnginesInitializer.initialize(OMemoryAndLocalPaginatedEnginesInitializer.java:52)
	at com.orientechnologies.orient.core.engine.local.OEngineLocalPaginated.startup(OEngineLocalPaginated.java:56)
	at com.orientechnologies.orient.core.Orient.startEngine(Orient.java:858)
	at com.orientechnologies.orient.core.Orient.loadStorage(Orient.java:466)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(ODatabaseDocumentTx.java:172)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(ODatabaseDocumentTx.java:153)
	at com.orientechnologies.orient.server.OSystemDatabase.init(OSystemDatabase.java:151)
	at com.orientechnologies.orient.server.OSystemDatabase.<init>(OSystemDatabase.java:44)
	at com.orientechnologies.orient.server.OServer.initSystemDatabase(OServer.java:1283)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:350)
	at com.orientechnologies.orient.server.OServerMain$1.run(OServerMain.java:46)
Error during engine shutdown
java.lang.NullPointerException
	at com.orientechnologies.orient.core.engine.local.OEngineLocalPaginated.shutdown(OEngineLocalPaginated.java:112)
	at com.orientechnologies.orient.core.Orient.startEngine(Orient.java:864)
	at com.orientechnologies.orient.core.Orient.loadStorage(Orient.java:466)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(ODatabaseDocumentTx.java:172)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.<init>(ODatabaseDocumentTx.java:153)
	at com.orientechnologies.orient.server.OSystemDatabase.init(OSystemDatabase.java:151)
	at com.orientechnologies.orient.server.OSystemDatabase.<init>(OSystemDatabase.java:44)
	at com.orientechnologies.orient.server.OServer.initSystemDatabase(OServer.java:1283)
	at com.orientechnologies.orient.server.OServer.activate(OServer.java:350)
	at com.orientechnologies.orient.server.OServerMain$1.run(OServerMain.java:46)

```

**Comment by laa** [comment] 2017-09-26 13:38
@AhrimanSefid did you try latest ODB?

**Comment by AhrimanSefid** [comment] 2017-09-26 13:42
no

**Comment by laa** [comment] 2017-09-26 13:45
@AhrimanSefid we can apply fixes only to the latest version, could you check it? if you still have an issue we will fix it for you.

**Comment by AhrimanSefid** [comment] 2017-09-26 14:02
ok.
thank you i try to last v.

**Comment by laa** [comment] 2017-09-26 14:50
@AhrimanSefid in the issue you indicated that you use JDK 8 but from the log, I see that you use JDK 9. Your issue will be fixed in 2.2.28 release, which will be published in few hours.

**Comment by maggiolo00** [comment] 2017-09-29 07:53
hi @AhrimanSefid 

did you try the 2.2.28 releases with JDK 9?

It should solve this

**Comment by odbuser2** [comment] 2017-10-07 08:30
OSX
Oracle JDK 9+181
ODB 2.2.29

I am getting this error with 2.2.29 and JDK9.

```java.lang.reflect.InaccessibleObjectException: Unable to make public long com.sun.management.internal.OperatingSystemImpl.getTotalPhysicalMemorySize() accessible: module jdk.management does not "opens com.sun.management.internal" to unnamed module @cfd5cd2```

**Comment by laa** [comment] 2017-10-09 11:42
@odbuser2 does it prevent you to use a database or you see this error on console only?

**Comment by odbuser2** [comment] 2017-10-09 23:26
I just checked server.sh and it is working even though the errors are printed.
However, I'm using the embedded server and that is failing.

**Comment by laa** [comment] 2017-10-10 06:11
@odbuser2 they both use the same code and server.sh is console command to start the same class. How do you start your server? Could you elaborate more, what does it mean that embedded server does not work?

**Comment by odbuser2** [comment] 2017-10-10 06:14
Sorry, after more testing, I've determined that OrientDB is not the source of the error that I'm having.  My application exists right after the embdedded server is created and I mistakenly read the warnings as the cause.

**Comment by laa** [comment] 2017-10-10 06:20
@odbuser2 cool. Anyway, next versions will use another way to fetch physical memory size and you will not see this warning anymore.

**Comment by laa** [comment] 2017-10-10 13:02
Fixed. Release notes _In previous versions of OrientDB to get the total amount of physical memory on PC we used reflection to call a method of a class which is placed inside "sun" package. In the new version, we merely requesting attribute value of JMX bean from JMX server avoiding any limitations of JDK 9 module system._

**Closed by laa** 2017-10-10 13:02 UTC
Labels: enhancement
