### ISSUE TITLE
DB going to "Read Only Mode"

### ISSUE THREAD

**Issue by mindnuts** [orientechnologies/orientdb#8031] opened 2018-01-29 06:41 UTC
### OrientDB Version: <version here>  
2.2.30
### Java Version: <version here>  
openjdk 8u151
### OS: <os here>  
Alpine (Docker image)
## Expected behavior  
SQL exceptions should not make the DB go into "Ready Only mode"
## Actual behavior  
Please see the attached gist for error on Orientdb Console:

[Error log](https://gist.github.com/mindnuts/7738aef08b5654531554538cebf6a012)

The error logged by the OrientJs client:

```
 "message": "JVM error 'TokenMgrError : Lexical error at line 1, column 40.  Encountered: \"\\n\" (10), after : \"\\'\"' occurred during data processing, storage is switched to 'read-only' mode. To prevent this exception please restart the JVM and check data consistency by calling of 'check database' command from database console.\r\n\tDB name=\"DbData\"",
```

## Steps to reproduce  
The logs are not that verbose to be able to identify which command caused the error

**Comment by laa** [comment] 2018-01-29 09:51
Hi, it is already fixed in 2.2.31.Please update the version.

**Comment by mindnuts** [comment] 2018-01-29 09:58
@laa Are there any breaking changes if we migrate from 2.2.30 to 2.2.31?

**Comment by laa** [comment] 2018-01-29 10:14
no. nothing breaking.

**Comment by mindnuts** [comment] 2018-01-30 08:13
@laa Thanks for your response. Any idea how can i reproduce the JVM error? We are yet to reproduce that error on our production machine. I have created a test machine with production data running Orientdb version 2.2.31.

**Comment by laa** [comment] 2018-01-30 10:22
@mindnuts I suppose I should clarify. If you encounter JVM Error inside of storage, you will be switched off to the read-only mode. Historically SQL parser also throws JVM error. That is why you see that in case of JVM Error DB was switched to read-only mode. We fixed this issue. So now parser does not cause the switch to read-only mode. So if you do not see a problem using the same query, then the issue is fixed.

**Comment by rdelangh** [comment] 2018-07-31 12:12
I got exactly the same situation, but in version 2.2.37 (so well passed the suggested fix of version 2.2.31) : 

- the client program got the following reply from the server, while trying to insert new data:
```
com.orientechnologies.orient.core.exception.OPageIsBrokenException: Following files and pages are detected to be broken ['cl_cdr_af_20180520_p0.pcl' :1;], storage is switched to 'read only' mode. Any modification operations are prohibited. 
```
- in the server logs:
```
...
2018-07-30 12:06:19:426 WARNI ->10.110.37.7: Command not found: GET.profiler/metadata [ONetworkProtocolHttpDb]$ANSI{green {db=cdrarch}} Error during
 data read for file 'cl_cdr_af_20180520_p0.pcl' 1-th attempt
java.nio.channels.ClosedChannelException
        at sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:110)
        at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:721)
        at com.orientechnologies.common.io.OIOUtils.readByteBuffer(OIOUtils.java:361)
        at com.orientechnologies.orient.core.storage.fs.OFileClassic.read(OFileClassic.java:149)
        at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.loadFileContent(OWOWCache.java:1550)
        at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.load(OWOWCache.java:773)
        at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.updateCache(O2QCache.java:1156)
        at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.doLoad(O2QCache.java:361)
        at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.load(O2QCache.java:294)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.loadPage(ODurableComponent.java:145)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.readRecordBuffer(OPaginatedCluster.java:766)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.readRecord(OPaginatedCluster.java:742)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.readRecord(OPaginatedCluster.java:721)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doReadRecord(OAbstractPaginatedStorage.java:4220)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:3807)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:1410)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx$SimpleRecordReader.readRecord(ODatabaseDocumentTx.java:3395)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:2008)
        at com.orientechnologies.orient.core.tx.OTransactionNoTx.loadRecord(OTransactionNoTx.java:97)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:1757)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:103)
        at com.orientechnologies.orient.core.iterator.OIdentifiableIterator.readCurrentRecord(OIdentifiableIterator.java:300)
        at com.orientechnologies.orient.core.iterator.ORecordIteratorCluster.begin(ORecordIteratorCluster.java:235)
        at com.orientechnologies.orient.core.iterator.ORecordIteratorCluster.<init>(ORecordIteratorCluster.java:91)
        at com.orientechnologies.orient.core.iterator.ORecordIteratorCluster.<init>(ORecordIteratorCluster.java:40)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.scanClusterWithIterator(OCommandExecutorSQLSelect.java:1805)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.access$300(OCommandExecutorSQLSelect.java:94)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect$1.run(OCommandExecutorSQLSelect.java:1708)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

Not sure what caused that dbase file to become "switched to read-only", maybe any interactive session did invoke a wrong SQL statement (referring to your comment above that the parser would be involved).

-> not yet fixed in 2.2.3* up till and include v2.2.37, or this is a new problem

**Comment by wells-chen** [comment] 2018-08-30 16:00
2.2.36
centos 7
the same problems
2018-08-29 01:25:40:185 INFO  + extracted 1,545,415 rows (0 rows/sec) - 1,545,415 rows -> loaded 1,525,875 vertices (0 vertices/sec) Total time: 5673502ms [0 warnings, 24 errors] [OETLProcessor]
2018-08-29 01:25:40:185 SEVER {db=enterprise} ETL process has problem: java.util.concurrent.ExecutionException: com.orientechnologies.orient.core.exception.OJVMErrorException: JVM error 'OutOfMemoryError : GC overhead limit exceeded' occurred during data processing, storage is switched to 'read-only' mode. To prevent this exception please restart the JVM and check data consistency by calling of 'check database' command from database console.

**Comment by wells-chen** [comment] 2018-08-30 16:02
orientdb {db=enterprise}> create property company.name STRING                                

Error: com.orientechnologies.orient.core.exception.OPageIsBrokenException: Following files and pages are detected to be broken ['e_shares_7.cpm' :194;], storage is switched to 'read only' mode. Any modification operations are prohibited. To restore database and make it fully operational you may export and import database to and from JSON.

**Comment by wells-chen** [comment] 2018-08-30 16:16
@laa  Once the error occurs when you import data, it is necessary for data backup, re-import, which looked not necessary , how to repair the bad file only

backup.sh to export data  too slowly  about  6G/hour

**Closed** 2021-08-06 10:55 UTC

**Comment by sblommers** [comment] 2024-05-01 09:25
2.2.36 we have this a few times a year but in production only. Seems related to large databases with much read write. For us a reason to upgrade soon. This unfortunatrly will take a lot of time. It would be better if something would fix it the easy way. Just restarting fixes the read only lock for a couple of weeks that way gives some time to breathe and migrate.
