### ISSUE TITLE
Orient - Page File index placed in wrong list Warning

### ISSUE THREAD

**Issue by rbaarathinms** [orientechnologies/orientdb#7971] opened 2017-12-28 09:34 UTC
### Java Version:  jdk1.8.0_121

Hi team 
 We are getting the following  below warnings
2017-12-28 12:58:30:546 WARNI {db=rcainv} Page in file der_pat_open_circuit.pcl with index 112 was placed in wrong free list, this error will be fixed automatically. [OPaginatedCluster]

2017-12-28 12:58:30:546 WARNI {db=rcainv} Page in file der_pat_open_circuit.pcl with index 220 was placed in wrong free list, this error will be fixed automatically. [OPaginatedCluster]

Can you please tell us why we get such warnings ? 
Such warnings take some definite amount (appros: 7 -8 GB) of GB from our heap , is there any way to skip such warnings from getting logged ?

**Comment by laa** [comment] 2017-12-29 00:33
Hi @rbaarathinms this issue is already fixed in latest version of the 2.2.x version it was concurrence issue if I remember correctly. Please do the following. Export data to JSON in 2.2.20 then upgrade to 2.2.31 version and then import data again and you will never see this issue again. We had similar issues in other users so I pretty sure that this approach will fix your problems.

**Comment by laa** [comment] 2018-01-24 03:14
Hi, @rbaarathinms did an approach which I proposed fix your issue?

**Comment by laa** [comment] 2018-02-03 07:05
Hi, @rbaarathinms did an approach which I proposed fix your issue?

**Comment by laa** [comment] 2018-02-09 08:52
Close issue because of no reply. If you reproduce given issue and have information which is requested in issue feel free to reopen it.

**Closed by laa** 2018-02-09 08:52 UTC
Labels: analyzing

**Comment by zzllkk2003** [comment] 2021-06-24 09:34
We are using version 3.3.1 and got a similar error. How can I solve it?

2021-06-24 09:34:16,693+0000 WARN  [event-12-thread-2]  anonymous com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster - $ANSI{green {db=component}} Page in file browse_node_1.pcl with index 3 was placed in wrong free list, this error will be fixed automatically
2021-06-24 09:34:16,693+0000 WARN  [event-12-thread-2]  anonymous com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster - $ANSI{green {db=component}} Page in file browse_node_1.pcl with index 144 was placed in wrong free list, this error will be fixed automatically
2021-06-24 09:34:16,693+0000 WARN  [event-12-thread-2]  anonymous com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster - $ANSI{green {db=component}} Page in file browse_node_1.pcl with index 249 was placed in wrong free list, this error will be fixed automatically
2021-06-24 09:34:16,693+0000 WARN  [event-12-thread-2]  anonymous com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster - $ANSI{green {db=component}} Page in file browse_node_1.pcl with index 333 was placed in wrong free list, this error will be fixed automatically
2021-06-24 09:34:16,693+0000 WARN  [event-12-thread-2]  anonymous com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster - $ANSI{green {db=component}} Page in file browse_node_1.pcl with index 345 was placed in wrong free list, this error will be fixed automatically

**Comment by elnurm** [comment] 2021-07-22 10:19
@zzllkk2003 , could u finally resolve the issue? i have the same warnings.

**Comment by Simoran95** [comment] 2022-06-23 08:49
Hi, has there been a solution to this problem please? We are experiencing it also on 3.37.1
