### ISSUE TITLE
 error in sub query with $parent.$current

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#3956] opened 2015-04-18 21:17 UTC
```
select $p from #41:7
 let $p = ( select rid from index:index_1 where key = $parent.$current )

----+-----+----
#   |@RID |$p  
----+-----+----
0   |#-2:1|[0] 
----+-----+----
```

but 

```
select rid from index:index_1 where key = #41:7
```

give rows

**Comment by luigidellaquila** [comment] 2015-05-22 14:06
Hi @publicocean0 

this should be fixed in 2.1-SNAPSHOT, could you please double check? (or give me some additional info about your db to reproduce the issue)

Thanks

**Comment by lvca** [comment] 2015-07-03 22:36
Closed because no futher feedback. In case, please comment it.

**Closed by lvca** 2015-07-03 22:36 UTC
Labels: waiting reply

**Comment by publicocean0** [comment] 2015-07-08 09:54
Hi , sorry for the delay. I tried with a similar query in my db . It seams to work correctly :)
