### ISSUE TITLE
Allow Select from multiple clusters of a Class

### ISSUE THREAD

**Issue by darkredz** [orientechnologies/orientdb#1901] opened 2013-12-19 08:41 UTC
Currently there's no way to select from more than one cluster. If a class is partition into a few clusters, the only way to query is to select from the class which will include all the clusters which is inefficient if the record is known to be in a range of only a few clusters. 

It would be nice to have select from more than one cluster of a class:

SELECT FROM cluster:ProductA,ProductB WHERE code='xxxxxxx'

https://groups.google.com/forum/#!topic/orient-database/EXH-99CdHwM

**Comment by lvca** [comment] 2015-04-26 08:05
Duplicate of #1222

**Closed by lvca** 2015-04-26 08:05 UTC
Labels: enhancement
