### ISSUE TITLE
toJSON does not work on lists

### ISSUE THREAD

**Issue by lukeworthtkbt** [orientechnologies/orientdb#4107] opened 2015-05-08 01:35 UTC
```
orientdb {db=Ice}> update element set data = {"Hello":"World"}  

Updated record(s) '1' in 0.024000 sec(s).

orientdb {db=Ice}> select data.toJSON() from Element            

----+------+------------------------------------------
#   |@CLASS|data                                      
----+------+------------------------------------------
0   |null  |{"@type":"d","@version":0,"Hello":"World"}
----+------+------------------------------------------

1 item(s) found. Query executed in 0.015 sec(s).
orientdb {db=Ice}> update element set data = [{"Hello":"World"}]

Updated record(s) '1' in 0.002000 sec(s).

orientdb {db=Ice}> select data.toJson() from Element            

----+------
#   |@CLASS
----+------
0   |null  
----+------

1 item(s) found. Query executed in 0.002 sec(s).
```
I expected the second select query to return a list structure. Also, how do I disable the @type and @version from the standard JSON? The documentation is unclear.

**Comment by luigidellaquila** [comment] 2015-05-08 13:40
Hi @lukeworthtkbt I'm on it

**Comment by luigidellaquila** [comment] 2015-05-08 15:05
Hi @lukeworthtkbt 

there the problem is that toJson() is a method of ODocument, and lists do not have such a method.

There are a couple of work-arounds for this:

```
select $current.toJSON() from (select element from V)

select $current.toJSON("fetchPlan:data:-1 *:-2") from element
```

Now I'm verifying if we can implement a new method for that also on lists

**Comment by luigidellaquila** [comment] 2015-12-02 09:19
Hi @lukeworthtkbt 

I finally managed to fix it in develop branch.
It is considered a new feature, so probably I won't be able to backport it to 2.1.x
I'm closing this, please reopen if you need further help or info

Thanks

Luigi

**Closed by luigidellaquila** 2015-12-02 09:19 UTC
Labels: bug, in progress
