### ISSUE TITLE
Any open source projects using OrientDB?

### ISSUE THREAD

**Issue by hansgru** [orientechnologies/orientdb#1635] opened 2013-08-21 01:25 UTC
Are there any open source projects using OrientDB?

I mean **real** and working open source projects that make use of OrientDB as a database/persistence. I haven't really found something usable so far :(.

I don't mean the plug-ins listed here: https://github.com/orientechnologies/orientdb/wiki/Plugins

regards.

**Comment by hansgru** [comment] 2015-05-19 11:56
@giastfader thank you for the link!

Are there any more projects?
A WIKI page with the projects using it would be helpful. There is one for commercial use, but those are not helpful to see how stuff is done.

**Comment by lvca** [comment] 2016-01-21 08:16
This is a duplicate of this question: https://github.com/orientechnologies/orientdb/issues/4806

**Closed by lvca** 2016-01-21 08:16 UTC
Labels: question, wontfix
