### ISSUE TITLE
Changed superclass causes objects to be unqueryable with index

### ISSUE THREAD

**Issue by obi1kenobi** [orientechnologies/orientdb#5743] opened 2016-02-17 18:24 UTC
On OrientDB 2.1.9:
```
CREATE CLASS Main ABSTRACT
CREATE PROPERTY Main.uuid String
CREATE INDEX Main.uuid UNIQUE_HASH_INDEX

CREATE CLASS Base EXTENDS Main ABSTRACT

CREATE CLASS Derived EXTENDS Main
INSERT INTO Derived SET uuid='abcdef'

SELECT * FROM Derived WHERE uuid='abcdef'  // returns the one object

ALTER CLASS Derived SUPERCLASSES Base
SELECT * FROM Derived WHERE uuid='abcdef'  // returns no objects!!

REBUILD INDEX Main.uuid
SELECT * FROM Derived WHERE uuid='abcdef'  // returns no objects!!

DROP INDEX Main.uuid
SELECT * FROM Derived WHERE uuid='abcdef'  // returns the one object, but there's no index -- table scan

CREATE INDEX Main.uuid UNIQUE_HASH_INDEX
SELECT * FROM Derived WHERE uuid='abcdef'  // returns no objects!!
```

This is quite obviously incorrect behavior -- the results should never be different depending on whether an index is used or not.

**Comment by smolinari** [comment] 2016-02-18 07:09
I can confirm this problem is the same with 2.1.11.

The queries on "Derived" start working correctly, when an index is created on Derived.uuid.  

I am wondering, is it really proper to create indexes on an abstract class? Because, no records would ever be stored in an abstract class, right? So, there are two possibilities

If I tell ODB "CREATE INDEX Class.property" and the class is abstract, maybe ODB could take that as,"If a concrete class is created from an abstract class, automatically create the defined indexes for the properties from the abstract class". I'd also leave a "back door" to stop auto-index creation, just incase the new class shouldn't get the predefined indexes.

Or, 

just stop the ability to create an index on abstract classes with a warning. 

It makes no sense in the current form.

Scott

**Comment by lodrion** [comment] 2016-02-18 16:41
I think it's reasonable to have an index on the abstract class. All this construct is saying is that all classes derived from Main should have uuids and they should be generally unique. 

This is totally in line with the mixin/trait idea in https://github.com/orientechnologies/orientdb/issues/2939

**Comment by obi1kenobi** [comment] 2016-02-18 16:43
Two things @smolinari :
- Keep in mind that indexes are not bound to a particular class or table -- they can be compound, and even span different tables in some databases. As such, an index on an abstract class is just an index that indexes the same field in multiple tables (classes).

The fact that no records are stored in an abstract class is thus beside the point. This is also not equivalent to having separate indexes created for all non-abstract classes derived from the abstract class with the defined index. I can still query on an abstract class, and I expect the answer to be given by consulting the *one index I defined* rather than by consulting a bunch of different indexes, one per derived class. There is a very significant semantic and performance difference between the two.

- Let's change `Main` to not be abstract -- the problem I reported remains:
```
CREATE CLASS Main
CREATE PROPERTY Main.uuid String
CREATE INDEX Main.uuid UNIQUE_HASH_INDEX

CREATE CLASS Base EXTENDS Main ABSTRACT

CREATE CLASS Derived EXTENDS Main
INSERT INTO Derived SET uuid='abcdef'

SELECT * FROM Derived WHERE uuid='abcdef'  // returns the one object

ALTER CLASS Derived SUPERCLASSES Base
SELECT * FROM Derived WHERE uuid='abcdef'  // returns no objects!!

REBUILD INDEX Main.uuid
SELECT * FROM Derived WHERE uuid='abcdef'  // returns no objects!!

DROP INDEX Main.uuid
SELECT * FROM Derived WHERE uuid='abcdef'  // returns the one object, but there's no index -- table scan

CREATE INDEX Main.uuid UNIQUE_HASH_INDEX
SELECT * FROM Derived WHERE uuid='abcdef'  // returns no objects!!
```

**Comment by smolinari** [comment] 2016-02-18 17:12
> As such, an index on an abstract class is just an index that indexes the same field in multiple tables (classes).

That was what I meant with my first "possibility". If an index is created on a property of an abstract class, then any concrete classes with data stored in the inherited property should also be indexed automatically. Thus, the query on the Derived class wouldn't fail. 

> Let's change Main to not be abstract -- the problem I reported remains:

Ohh... that is not good. 

@luigidellaquila - I think this needs your attention. :smile: 

Scott

**Comment by obi1kenobi** [comment] 2016-02-18 18:10
Cool, I just wanted to make sure the distinction between having separate indexes for each class vs one index for all derived classes is clear.

**Comment by smolinari** [comment] 2016-02-22 12:05
@lvca @luigidellaquila 

Hey guys. Just want to get your attention on this issue.

Scott

**Comment by luigidellaquila** [comment] 2016-02-22 12:21
Hi Scott,

Thanks a lot, I'll manage it in short

Thanks

Luigi

**Comment by luigidellaquila** [comment] 2016-02-23 16:24
Hi guys,

I just pushed a fix on branch 2.1.x, it will be released with 2.1.12.
Now I'm porting the fix to 2.2 (develop)

Thanks

Luigi

**Comment by obi1kenobi** [comment] 2016-02-23 16:24
Thank you, much appreciated!

**Comment by smolinari** [comment] 2016-02-23 16:28
:+1: Thanks Luigi! 

Scott

**Comment by smolinari** [comment] 2016-02-25 07:27
Just a small update. I tested this on 2.2.0-beta and it also has the same behavior. 

Scott

**Comment by luigidellaquila** [comment] 2016-02-25 09:11
Hi Scott,

Yes, I'm working on it, it seems that the patch I applied on 2.1 causes some problems to 2.2 (some tests failing), I have to investigate it a bit

Thanks

Luigi

**Comment by smolinari** [comment] 2016-02-25 09:51
No problem Luigi. I just wanted to note the problem exists in the new version too. 

Btw, what is the "proper" behavior for an index created on an abstract class?

Scott

**Comment by luigidellaquila** [comment] 2016-02-25 09:53
Hi Scott,

And index on an abstract class will just contain references to all the records in the hierarchy of that abstract class, there is no difference compared to normal classes

Thanks

Luigi

**Comment by smolinari** [comment] 2016-02-25 10:37
Ok. That is what I would have expected too. 

Thanks!

Scott

**Comment by luigidellaquila** [comment] 2016-02-25 16:08
Fixed in develop branch as well. Closing

Thanks!

Luigi

**Closed by luigidellaquila** 2016-02-25 16:08 UTC
Labels: bug
