### ISSUE TITLE
Snappy uncompression error during LOAD RECORD op

### ISSUE THREAD

**Issue by kowalot** [orientechnologies/orientdb#3421] opened 2015-01-18 22:30 UTC
Snapshot-dev 2.0RC:746f1ccdf30b3090b67f7831b210406261a656ab (19th Dec)

``` sql

Sent run-time exception to the client /127.0.0.1:10238: com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #46:105 (cluster: XXX)
com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #46:105 (cluster: XXX)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1601)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.loadRecord(OTransactionNoTx.java:80)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:1433)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:117)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearchRecord(OCommandExecutorSQLSelect.java:485)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.fetchFromTarget(OCommandExecutorSQLSelect.java:1301)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:434)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:392)
	at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:64)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1172)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1161)
	at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:71)
	at com.orientechnologies.orient.core.sql.query.OSQLSynchQuery.run(OSQLSynchQuery.java:85)
	at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1179)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:385)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:216)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)
Caused by: com.orientechnologies.orient.core.exception.ODatabaseException: Error during data decompression.
	at com.orientechnologies.orient.core.compression.impl.OSnappyCompression.uncompress(OSnappyCompression.java:58)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.OPaginatedCluster.readRecord(OPaginatedCluster.java:558)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doReadRecord(OAbstractPaginatedStorage.java:1789)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:1421)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:690)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1568)
	... 17 more
Caused by: java.io.IOException: FAILED_TO_UNCOMPRESS(5)
	at org.xerial.snappy.SnappyNative.throw_error(SnappyNative.java:84)
	at org.xerial.snappy.SnappyNative.rawUncompress(Native Method)
	at org.xerial.snappy.Snappy.rawUncompress(Snappy.java:444)
	at org.xerial.snappy.Snappy.uncompress(Snappy.java:480)
	at com.orientechnologies.orient.core.compression.impl.OSnappyCompression.uncompress(OSnappyCompression.java:54)
	... 22 more

```

After that I upgraded database server to latest snapshot (18th of Jan) and received following error on that database:

``` sql

2015-01-18 23:24:38:061 INFO  {db=XXX} FULL checkpoint found. [OLocalPaginatedStorage]
2015-01-18 23:24:38:062 INFO  {db=XXX} Data restore procedure from full checkpoint is started. Restore is performed from LSN OLogSequenceNumber{segment=0, position=5475348} [OLocalPaginatedStorage]{db=XXX} Exception during storage data restore.
java.lang.IllegalArgumentException: Invalid integer format.
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OPageChanges.deserializeCompressedInteger(OPageChanges.java:180)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OPageChanges.fromStream(OPageChanges.java:102)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OUpdatePageRecord.fromStream(OUpdatePageRecord.java:86)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OWALRecordsFactory.fromStream(OWALRecordsFactory.java:111)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.ODiskWriteAheadLog.read(ODiskWriteAheadLog.java:942)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.restoreFrom(OAbstractPaginatedStorage.java:2321)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.restoreFromFullCheckPoint(OAbstractPaginatedStorage.java:2289)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.restoreFromCheckPoint(OAbstractPaginatedStorage.java:2278)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.restoreFromWAL(OAbstractPaginatedStorage.java:2229)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.restoreIfNeeded(OAbstractPaginatedStorage.java:1558)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:202)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:243)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:623)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.openDatabase(ONetworkProtocolBinary.java:651)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:282)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:216)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:65)

```

btw. Do you see any way to recover database after such critical error?

**Comment by laa** [comment] 2015-01-19 17:55
Hi, 
@kowalot do you have Skype to udnerstand how did you get this issue ?

**Comment by laa** [comment] 2015-01-19 18:13
I moved it to 2.1, but with good probability it will be hotfix, if we confirm that it is not compatibility bug but real issue.

**Comment by laa** [comment] 2015-01-20 07:42
Seems like the reason of this bug is that we go into swap and have memory errors. I will provide fix today. Also Pawel confirmed that he was able to restore db if he does not switch between versions.
I propose to close this bug now and check whether new disk cache allocation policy will fix it. Otherwise it will be super time consuming to fix it especially if my suggestion that bug was caused by wrong memory management policy is correct.
WDYT ?

**Comment by kowalot** [comment] 2015-01-20 09:17
As for me I am fine with that. Since now I will use latest snapshot and let you know if it happen any time again.

**Comment by lvca** [comment] 2015-03-14 20:17
Ok, I'm closing it.

**Closed by lvca** 2015-03-14 20:17 UTC
Labels: bug
