### ISSUE TITLE
Take down of single orientdb instance in 3 node cluster results in read operations failing until timeout

### ISSUE THREAD

**Issue by arsalan-khan** [orientechnologies/orientdb#5915] opened 2016-04-01 01:15 UTC
OrientDB Server v2.1.13 (build 2.1.x@r9bc1a54a4a62c4de555fc5360357f446f8d2bc84; 2016-03-14 17:00:05+0000)

We have a cluster of 3 orientdb servers with a read quorum of 1 and write quorum of 2. If we power off one of the machines all the read requests fail with the following exceptions, until the heartbeat timeout happens. 
Is this the expected behavior?
Is the entire cluster really expected to be un-useable for the duration of the timeout (which is 5mins in this case)?
Shouldn't the read operations keep going through since the read quorum is 1 and there is more than 1 node in the cluster?

```
These logs are from the device with ip 10.0.1.38, the device that we took down was 10.0.1.32

2016-03-31 17:09:45:859 WARNI [10.0.1.38]:2434 [orientdb] [3.5.3] No response for 120000 ms. InvocationFuture{invocation=Invocation{ serviceName='hz:impl:mapService', op=GetOperation{orientdb}, partitionId=19, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=60000, target=Address[10.0.1.32]:2434, backupsExpected=0, backupsCompleted=0}, response=null, done=false} [Invocation]
2016-03-31 17:09:45:859 WARNI [10.0.1.38]:2434 [orientdb] [3.5.3] Asking if operation execution has been started: Invocation{ serviceName='hz:impl:mapService', op=GetOperation{orientdb}, partitionId=19, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=60000, target=Address[10.0.1.32]:2434, backupsExpected=0, backupsCompleted=0} [Invocation][10.0.1.38]:2434 [orientdb] [3.5.3] While asking 'is-executing': Invocation{ serviceName='hz:impl:mapService', op=GetOperation{orientdb}, partitionId=19, replicaIndex=0, tryCount=250, tryPauseMillis=500, invokeCount=1, callTimeout=60000, target=Address[10.0.1.32]:2434, backupsExpected=0, backupsCompleted=0}
java.util.concurrent.TimeoutException: Call Invocation{ serviceName='hz:impl:mapService', op=com.hazelcast.spi.impl.operationservice.impl.operations.IsStillExecutingOperation{serviceName='hz:impl:mapService', partitionId=-1, callId=11468, invocationTime=1459469391551, waitTimeout=-1, callTimeout=5000}, partitionId=-1, replicaIndex=0, tryCount=0, tryPauseMillis=0, invokeCount=1, callTimeout=5000, target=Ad
dress[10.0.1.32]:2434, backupsExpected=0, backupsCompleted=0} encountered a timeout
        at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveApplicationResponse(InvocationFuture.java:366)
        at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.resolveApplicationResponseOrThrowException(InvocationFuture.java:334)
        at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:225)
        at com.hazelcast.spi.impl.operationservice.impl.IsStillRunningService.isOperationExecuting(IsStillRunningService.java:85)        at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.waitForResponse(InvocationFuture.java:275)
        at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:224)
        at com.hazelcast.spi.impl.operationservice.impl.InvocationFuture.get(InvocationFuture.java:204)
        at com.hazelcast.map.impl.proxy.MapProxySupport.invokeOperation(MapProxySupport.java:456)        at com.hazelcast.map.impl.proxy.MapProxySupport.getInternal(MapProxySupport.java:275)        at com.hazelcast.map.impl.proxy.MapProxyImpl.get(MapProxyImpl.java:82)        at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.getNodeConfigurationById(OHazelcastPlugin.java:271)        at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.getClusterConfiguration(OHazelcastPlugin.java:264)        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.openDatabase(ONetworkProtocolBinary.java:808)        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:293)        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:223)        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)

2016-03-25 18:39:00:959 WARNI [10.0.1.38]:2434 [orientdb] [3.5.3] Removing Member [10.0.1.32]:2434 because it has not sent any heartbeats for 300000 ms. [ClusterService]
2016-03-25 18:39:01:959 WARNI [10.0.1.38]:2434 [orientdb] [3.5.3] This node does not have a connection to Member [10.0.1.38]:2434 [ClusterService]
2016-03-25 18:39:01:959 WARNI [10.0.1.38]:2434 [orientdb] [3.5.3] Removing Member [10.0.1.32]:2434 because it has not sent any heartbeats for 300000 ms. [ClusterService]
2016-03-25 18:39:01:959 INFO  [10.0.1.38]:2434 [orientdb] [3.5.3] Connecting to /10.0.1.32:2434, timeout: 0, bind-any: true [SocketConnector]
2016-03-25 18:39:03:960 INFO  [10.0.1.38]:2434 [orientdb] [3.5.3] Connection [Address[10.0.1.32]:2434] lost. Reason: Socket explicitly closed [TcpIpConnection]
2016-03-25 18:39:03:960 INFO  [10.0.1.38]:2434 [orientdb] [3.5.3] Removing Member [10.0.1.32]:2434 [ClusterService]
```

**Comment by lvca** [comment] 2016-04-06 13:30
Are you using sharding?

**Comment by arsalan-khan** [comment] 2016-04-06 20:11
No, all the nodes are suppose to have all the data.

Here is the default-distributed-db-config.json we use:

{"autoDeploy":true,"hotAlignment":false,"executionMode":"synchronous","readQuorum":1,"writeQuorum":2,"failureAvailableNodesLessQuorum":false,"readYourWrites":true,"servers":{"\*":"master"},"clusters":{"internal":{},"index":{},"*":{"servers":["<NEW_NODE>"]}}}

**Comment by sol50** [comment] 2016-04-21 10:20
We have serious problems in production because of exactly this (some nodes have started to fail due to unrelated OOM bugs in OrientDB, so it's critical that clustering/failover works!!!)

For my own sake, I really hope the team is working around the clock on this one.

**Comment by lvca** [comment] 2016-04-21 17:05
It looks like that is an Hazelcast problem (the thread is stuck in Hazelcast). We already resolved this problem in v2.2.0-SNAPSHOT (`develop` branch). Applying this in v2.1 it's not easy. What release of Hazelcast do you have in OrientDB libs directory? Could you please replace the jars with the `3.6.1`, the same we have under v2.2?

**Comment by realms50** [comment] 2016-04-21 17:32
@lvca Thanks you for suggesting this, 3.6.1 jars solves the problem! I can now stop a node without issue.

Of course, the OOM issues remains.

**Comment by lvca** [comment] 2016-04-21 18:00
Cool, what OOM? Do you have any log?

**Comment by realms50** [comment] 2016-04-21 18:04
Can post a log next time it happens (should be soon enough) Happens when sorting on non indexed fields mostly, or bulk inserts.

**Comment by lvca** [comment] 2016-06-24 05:18
After a while I'm closing this because not reproducible. In case, please reopen/comment it.

**Closed by lvca** 2016-06-24 05:18 UTC
Labels: question, waiting reply
