### ISSUE TITLE
Restore is not dealing with existing collections_<>.sbc files

### ISSUE THREAD

**Issue by rtm81** [orientechnologies/orientdb#4590] opened 2015-07-16 14:35 UTC
I had the same bug as in issue #4439 with Orientdb version 2.0.10.
And when i found the bug was fixed, i switch to version 2.0.12. 
Now my tests are running, but i am concerned of this log message.

Jul 16, 2015 4:02:57 PM com.orientechnologies.common.log.OLogManager log
SCHWERWIEGEND: {db=database} File collections_48.sbc is not registered in 'file name - id' map but exists in file system, probably you work in distributed storage. If it is not true, please create bug in bug tracker https://github.com/orientechnologies/orientdb/issues .

I am **not** using distributed storage, it is plocal.

Here is my scenario:
I am running integration tests that are changing the database. 
In order to have a clean database before every new test run, i am restoring a known database zip before each test.
For the restore i use this method:
com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.restore(InputStream, Map<String, Object>, Callable<Object>, OCommandOutputListener)

In my zip there is just one collections_<>.sbc file.
![backup-zip](https://cloud.githubusercontent.com/assets/1322712/8725848/e7167e36-2bd6-11e5-86b8-57b85bce45bd.png)

After the restore is finished my database folder contains 3 such files.
![after-restore](https://cloud.githubusercontent.com/assets/1322712/8725867/0a0283f4-2bd7-11e5-985a-c601ab1801f4.png)

Now i fear that some old data is still persistent after the restore.

**Comment by laa** [comment] 2015-07-16 16:28
HI,
That is  not a bug , your zip  archive contains broken mapping file. 
That is why you got this exception.

You may fix it without problems.
Unzip database, open it, close and zip again.
Your exception will never appear.

**Comment by rtm81** [comment] 2015-07-16 16:55
my zip is not the issue. It is generated by Orient-DB backup mechanism.

You did some hack in this commit 3525f8f61407bdd3b880c73bef15c1174a9cc9a3
And the mentioned error message is coming now in my log.
Please check again.

**Comment by laa** [comment] 2015-07-17 05:58
Hi,
Backup mechanism exactly one which is used for distributed storage to send db to other instance, no surprise that you have issue using it, till it will not be fixed you will have this problem.  But it is interesting finding I put you comment in "root" issue. If you wish to work with fixed database ,  you may repeat steps I outlined above.

**Comment by laa** [comment] 2015-07-17 06:11
I have question how did you perform backup ? Could you outline more steps to reproduce this issue ?
BTW May you send your db and test to reproduce it on our side ?

**Comment by laa** [comment] 2015-07-17 06:34
I mean do  you delete previous database before restoring old one from zip file ?

**Comment by rtm81** [comment] 2015-07-17 06:40
This is my backup routine. This is triggered via JMX from outside the server JVM.
```java
    public void backup(String path) {
        try (com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx db = orientGraphFactory.openDatabase()) {
            OCommandOutputListener listener = new OCommandOutputListener() {

                @Override
                public void onMessage(String iText) {
                    LOGGER.info(iText);
                }
            };

            try (OutputStream out = new FileOutputStream(path)) {
                db.backup(out, null, null, listener, BACKUP_COMPRESSION_LEVEL, BACKUP_BUFFER_SIZE);
            }
        } catch (Throwable e) {
            String msg = "Failed to backup [" + path + "].";
            LOGGER.error(msg, e);
            throw new RuntimeException(msg + CHECK_THE_LOG_FOR_DETAILS_LOG_MESSAGE);
        }
    }
```

**Comment by rtm81** [comment] 2015-07-17 06:47
The server JVM with the OrientDB is just running without a stop.
Right after the server start, i fetch a backup zip to have a clean state.

The integration tests are running on a different JVM to simulate client interaction.
Before every single test, i restore the backup zip with ODatabaseDocumentTx.restore.

There is no deletion of the database before restoring. How would i do so on a running server?

**Comment by laa** [comment] 2015-07-17 08:02
If you do not delete db, you will have this error. Before restore you should drop old one, create new db and call restore method.
Could you try it.

**Comment by rtm81** [comment] 2015-07-17 10:21
When i drop the database, create a new one and call restore, then there is no such error.

**Comment by laa** [comment] 2015-07-17 11:25
Good, restore is not designed to be applied to existing database , close this issue.

**Closed by laa** 2015-07-17 11:25 UTC
Labels: wontfix

**Comment by rtm81** [comment] 2015-07-17 12:31
The documentation (http://orientdb.com/docs/last/Console-command-Restore.html) says:
"Executes a restore of current opened database."

There is no word of saying: drop database before.

**Comment by lvca** [comment] 2015-07-17 17:34
@rtm81 You're absolutely right: the documentation is not clear.

**Comment by lvca** [comment] 2015-07-17 17:46
Updated documentation, thanks for reporting it.
