### ISSUE TITLE
using sequence gives "Error in transactional processing"

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#6842] opened 2016-10-25 12:27 UTC
## OrientDB Version, operating system, or hardware.
- v2.2.12

## Operating System
- [x] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
The following SQL statement has been working for some 1000's of times, but suddenly it aborts with the below error:
```
INSERT INTO files_loaded SET FILENAME='ICX001ICX20161019155500.095588', FILE_ID=sequence('seq_files_loaded').next(), WHEN_LOADED='2016-10-25 14:14:00.000', ENV= 'prod'
```

The error: 
```
com.orientechnologies.orient.core.exception.OSequenceException: Error in transactional processing of seq_files_loaded.next()
```

The class "files_loaded" contains these 4 properties FILENAME, FILE_ID, WHEN_LOADED and ENV; there is a unique index on FILENAME, but no record exists yet with this same FILENAME.

**Comment by maggiolo00** [comment] 2016-10-25 12:32
@rdelangh 

can you check in OrientDB logs if you see more detail about this exception?

Thanks

**Comment by rdelangh** [comment] 2016-10-25 12:34
@maggiolo00 
The logs contain no more than this single error message line (a few times now, cos I retried a few times)

**Comment by maggiolo00** [comment] 2016-10-25 12:38
@rdelangh 

do you have a script to reproduce it?

**Comment by rdelangh** [comment] 2016-10-25 12:42
I have never encountered this error before, so there is no indication what might have lead to this situation. The programs have been loading in parallel the contents of many 10,000's of files into the database, and each filename got inserted into this class FILES_LOADED using that very same sequence SEQ_FILES_LOADED.
Now there is no program running anymore, from the web interface and from the console CLI I try this very same INSERT command and still get the same error.

**Comment by rdelangh** [comment] 2016-10-25 13:10
grr, very disturbing glitch that I would like to see explained, so that we know if
- it is a bug that can/needs to be resolved
- we can avoid the situation

I don't have time to wait days for this to be resolved, so
1) I dropped the sequence,
2) recreated it
3) created an identical class "FILES_LOADED1"'
4) used the sequence to assign a FILE_ID for all 1.2M files which have already been loaded:
```
insert into files_loaded1  FROM SELECT FILENAME, sequence('seq_files_loaded').next() AS FILE_ID, ENV, WHEN_LOADED FROM files_loaded
Inserted record '1268753' in 150.748993 sec(s).

select count(*) from files_loaded1
+----+-------+
|#   |count  |
+----+-------+
|0   |1268753|
+----+-------+

select max(FILE_ID) from files_loaded1
+----+-------+
|#   |max    |
+----+-------+
|0   |1268753|
+----+-------+
```
5) drop old class FILES_LOADED
6) renamed new class FILES_LOADED1 into FILES_LOADED
7) created the unique index again on FILENAME
-> operational again

**Comment by lvca** [comment] 2016-10-27 09:30
@rdelangh I've just pushed a fix. I can't be sure if the problem 'com.orientechnologies.orient.core.exception.OSequenceException: Error in transactional processing of seq_files_loaded.next()' has been fixed because I couldn't reproduce it, but I fixed a severe bug on using sequence by multiple threads.

@rdelangh could you please pull 2.2.x branch and retry it?

**Comment by rdelangh** [comment] 2016-10-27 12:33
@lvca 
the latest 2.2.x snapshot I find is 
orientdb-community-2.2.13-20161026.231503-8

-> is this the one I should try ?

**Comment by lvca** [comment] 2016-10-27 13:33
Updated now. Try this: https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-community/2.2.13-SNAPSHOT/orientdb-community-2.2.13-20161027.133116-9.tar.gz.

**Comment by rdelangh** [comment] 2016-10-27 13:54
@lvca 
Got that 'orientdb-community-2.2.13-20161026.231503-8' snapshot, starting it, will see how it behaves.

**Comment by rdelangh** [comment] 2016-10-27 14:07
@lvca  ok, getting 2.2.13-20161027.133116-9 ...
(btw : are there any other fixes in this snapshot, for the other issues that I have opened?)

**Comment by lvca** [comment] 2016-10-27 14:39
Ok, closing this. I've just created a snapshot from last 2.2.x, so if any issue has ben closed before 1h ago, it's in.

**Closed by lvca** 2016-10-27 14:39 UTC
Labels: bug, resolved
