### ISSUE TITLE
ODatabaseSession().command(String query, Object... args)  unsupport for DROP?

### ISSUE THREAD

**Issue by tonglsh** [orientechnologies/orientdb#9627] opened 2021-06-18 02:45 UTC
### maven dependency: orientdb-client 3.2.0

i want to drop  class named "zzz"

#### can work:
```
        ODatabaseSession session = pool.acquire();
        OResultSet rs = session.command("drop class zzz");
        rs.close();
```
#### not work:
```
        ODatabaseSession session = pool.acquire();
        OResultSet rs = session.command("drop class ?" ,"zzz");
        rs.close();
```

#### is it unsupported ? 

```
Exception in thread "main" com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error parsing query:
drop class ?
   ^
Encountered " <DROP> "drop "" at line 1, column 1.
Was expecting one of:
    <SELECT> ...
    <TRAVERSE> ...
    <MATCH> ...
    <INSERT> ...
    <RETURN> ...
    <FIND> ...
    <REBUILD> ...
    <OPTIMIZE> ...
    <GRANT> ...
    <REVOKE> ...
    <BEGIN> ...
    <COMMIT> ...
    <ROLLBACK> ...
    <IF> ...
    <SLEEP> ...
    <CONSOLE> ...
    <MOVE> ...
    <SELECT> ...
    <SELECT> ...
    <TRAVERSE> ...
    <MATCH> ...
    <FIND> ...
    <INSERT> ...
    <MOVE> ...
    
	DB name="cmdb"
	Error Code="1"
	DB name="cmdb"
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleException(OChannelBinaryAsynchClient.java:355)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:303)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:325)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:209)
	at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:167)
	at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:2006)
	at com.orientechnologies.orient.client.remote.OStorageRemote.lambda$networkOperationRetryTimeout$2(OStorageRemote.java:390)
	at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:455)
	at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperationRetryTimeout(OStorageRemote.java:370)
	at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperation(OStorageRemote.java:410)
	at com.orientechnologies.orient.client.remote.OStorageRemote.query(OStorageRemote.java:1098)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentRemote.query(ODatabaseDocumentRemote.java:379)
	at com.example.orientdbclient.OrientDBController.main(OrientDBController.java:27)


```

**Comment by luigidellaquila** [comment] 2021-06-18 07:12
Hi @tonglsh 

`db.query()` is only for queries that do not modify the state (ie. SELECT, TRAVERSE, MATCH...). 
For DROP you have to use `db.command()`

Thanks

Luigi

**Comment by tonglsh** [comment] 2021-06-18 07:15
wait please...
db.command(String query, Object... args)  throw the exception too.

**Comment by tonglsh** [comment] 2021-06-18 07:16
@luigidellaquila

**Comment by luigidellaquila** [comment] 2021-06-18 07:36
Oh yes, sorry, I got it...
The problem is the parameter. No, it's not supported for DROP CLASS in the new SQL executor, but I can implement it right away, it's pretty easy.
It will be in v 3.2.1

Thanks

Luigi

**Comment by tonglsh** [comment] 2021-06-18 07:41
got it ,thank you.

**Closed as completed** 2021-06-18 09:16 UTC
