### ISSUE TITLE
SQL javascript API: 'ORDER BY' conflicting with 'SKIP'

### ISSUE THREAD

**Issue by dmarcelino** [orientechnologies/orientdb#3141] opened 2014-12-06 23:24 UTC
Hi,

When I try to run SQL queries through Oriento with both ORDER BY and SKIP clauses I get 0 results from the DB. For example:
```
this.db.query('SELECT name, title, @rid, createdAt, updatedAt FROM customerTable  WHERE name.toLowerCase() = "hasmany find pop"  ORDER BY @rid ASC SKIP 1')
```

Both studio and console.sh handle the query fine. 

I've raised the issue in Oriento's github page ([Issue #158](https://github.com/codemix/oriento/issues/158)) and @phpnode confirmed the issue was not in Oriento. I've written a test case [here](https://github.com/dmarcelino/oriento/blob/158-orderby-skip/test/bugs/158-orderby-skip.js) that you can use to reproduce the issue.

Tested in versions 1.7.9 and 2.0-M2.

**Comment by dmarcelino** [comment] 2015-07-04 14:16
Regarding the latest 2.1-rc5 announcement:
> If no critical issues are raised in the upcoming days, OrientDB 2.1 will be made Generally Available.

Will this issue be fixed until then?

**Comment by luigidellaquila** [comment] 2015-07-06 11:29
HI @dmarcelino yes, it should be fixed in 2.1
I tried to reproduce it in Java and also there it works fine... the problem seems to be strictly related to how OrientJS sends the query to OrientDB. I'll let you know

**Comment by luigidellaquila** [comment] 2015-07-13 09:56
Hi @dmarcelino 

I added your test case to OrientJS test suite and it seems to work fine.
Probably the issue was fixed in last days (thanks to increased bug fixing efforts for final release)
I'm closing it, please reopen in case I missed something

Thanks a lot

Luigi

**Comment by dmarcelino** [comment] 2015-07-13 09:57
Sounds fair, thanks!

**Closed by luigidellaquila** 2015-07-13 09:56 UTC
