### ISSUE TITLE
Weird issue with LINKLIST consistency

### ISSUE THREAD

**Issue by PhantomYdn** [orientechnologies/orientdb#6147] opened 2016-05-17 04:59 UTC
## Expected behavior and actual behavior

Got the following error:

```
com.orientechnologies.orient.core.exception.OValidationException: The field 'LegalEntity.activityPlaces' has been declared as LINKLIST but contains a null record (probably a deleted record?)
    at com.orientechnologies.orient.core.record.impl.ODocument.validateLink(ODocument.java:436)
    at com.orientechnologies.orient.core.record.impl.ODocument.validateLinkCollection(ODocument.java:417)
    at com.orientechnologies.orient.core.record.impl.ODocument.validateField(ODocument.java:287)
    at com.orientechnologies.orient.core.record.impl.ODocument.validate(ODocument.java:2005)
    at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1085)
    at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:604)
    at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:156)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2612)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2580)
```

The problem is that this field is being modified. Probably link was broken before, but due to this error there is no way to fix the issue.
## Steps to reproduce the problem

Hard to say, but probably the following will work:

1) Create entities A and B
2) Entity A through property of type LINKLIST should reffer to B
3) Delete B
4) Try to modify A
## Important Questions

Issue looks quite severe. Why during save db can't just simply remove broken "null" references?
### Runninng Mode
- [x] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [ ] Remote
### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition
### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [x] v2.1.x - Please specify last number:  2.1.16
- [ ] v2.2.x - Please specify last number: 
### Operating System
- [x] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 
### Java Version
- [ ] 6
- [ ] 7
- [x] 8

**Comment by luigidellaquila** [comment] 2016-05-17 08:39
Hi @PhantomYdn 

I tried to reproduce the problem with this code, but it seems to work fine:

```
  @Test
  public void testODocumentValidation() {
    String url = "plocal:/tmp/ODocumentValidation";
    ODatabaseDocumentTx db = new ODatabaseDocumentTx(url).create();
    try {

      OClass foo = db.getMetadata().getSchema().createClass("Foo");
      foo.createProperty("linklist", OType.LINKLIST);

      OClass bar = db.getMetadata().getSchema().createClass("Bar");

      ODocument bar1 = new ODocument(bar);
      bar1.save();
      ODocument bar2 = new ODocument(bar);
      bar2.save();

      ODocument foo1 = new ODocument(foo);
      List linklist = new ArrayList();
      linklist.add(bar1);
      linklist.add(bar2);
      foo1.field("linklist", linklist);
      foo1.save();

      bar1.delete();
      foo1.field("name", "foo");
      foo1.save();

    } finally {
      db.close();
    }
```

Can you please suggest a way to reproduce it? 
(I also tried via SQL, still no errors...)

Thanks

Luigi

**Comment by lvca** [comment] 2016-05-30 16:27
@PhantomYdn closing this issue because no answer. In case, please reopen/comment it.

**Comment by PhantomYdn** [comment] 2016-05-30 17:06
@lvca , sure - I would be able to reopen, but it seems that the ability to reopen issue by common users is disabled. So only OrientTechnology team can reopen.

**Comment by lvca** [comment] 2016-05-30 21:26
I thought if you create an issue you can reopen it. Is there any setting for it? Anyway, in case comment this issue and somebody will reopen it.

**Comment by PhantomYdn** [comment] 2016-05-30 22:09
It seems there is such settings. Regarding reopening. Please help to reopen this one: #6157 - can't move to 2.2.0 without fixing of those issues.

**Comment by luigidellaquila** [comment] 2016-05-31 07:21
Hi @PhantomYdn 

I just reopened both issues.
Do you have any hint on how to reproduce this one?

Thanks

Luigi

**Comment by santo-it** [comment] 2017-07-04 10:24
Hi,

I'm closing this now. If you have additional details on how to reproduce this, please let us know.

Many thanks,

**Closed by santo-it** 2017-07-04 10:24 UTC
Labels: can not reproduce
