### ISSUE TITLE
Query output columns in Web UI don't respect sequence in query

### ISSUE THREAD

**Issue by bodiam** [orientechnologies/orientdb#5272] opened 2015-11-04 12:58 UTC
When I run the following query in the web console of OrientDB:

````
select category as a, count(*) as count
from asin 
group by category
order by count desc
````

The output of the query will swap around the sequence of the columns. This doesn't happen to all queries, but to some. I tried using aliases, etc, but the sequence keeps the wrong way: it first displays the count, then the category (See attached screenshot)

<img width="1655" alt="screen shot 2015-11-04 at 13 52 19" src="https://cloud.githubusercontent.com/assets/46468/10938642/224b1080-82fc-11e5-8dbb-f73ad66260da.png">

**Comment by maggiolo00** [comment] 2015-11-04 18:29
@bodiam 

can you post also the screenshot of the raw section?

**Comment by bodiam** [comment] 2015-11-04 18:55
What is that, the raw section?

**Comment by smolinari** [comment] 2015-11-04 19:10
At the bottom of the results there is a tab to change to the view for the raw json output. 

![image](https://cloud.githubusercontent.com/assets/3314957/10948867/1b58899a-8330-11e5-8465-a5aaa37b5fc4.png)


Scott

**Comment by bodiam** [comment] 2015-11-04 20:05
Ah, thanks. Well, I could do that, but I cannot reproduce the problem now anymore. It depends on the dataset I have, and my dataset is changing every time. I tried it again, but right now it works, also when I switch around the columns

**Comment by maggiolo00** [comment] 2016-06-09 17:12
@bodiam 
i cannot reproduce it. Studio does some manipulation of the result set like for edges but the fields should be in the same position as the raw json.

**Comment by maggiolo00** [comment] 2016-06-15 16:03
@bodiam 
Closing this

**Closed** 2016-06-16 11:01 UTC
Labels: bug, waiting reply
