### ISSUE TITLE
Object API: Updating child via parent

### ISSUE THREAD

**Issue by diegomtassis** [orientechnologies/orientdb#6783] opened 2016-10-05 09:37 UTC
## OrientDB Version, operating system, or hardware.
- v2.2.X
## Operating System
- MacOSX
- Windows
## Expected behavior and actual behavior

I think the behavior I'm going to describe is closely related to this issue:
https://github.com/orientechnologies/orientdb/issues/6729.

I have a very simple domain model consisting of 2 entities related via a one-to-one relationship. Entity A has a reference to entity B. The fields in both entities are @Basic, all but the reference in A to B.

I have a repository service which uses OrientDB Object API to perform CRUD and list operations on the previous domain model. The repository instantiates and access a Plocal database.

This code uses OrientDB 2.1.x and is in production. Everything works fine. We have a bunch of integration tests (junit) for all the operations in the repository.

Now we are trying to upgrade to OrientDB 2.2.X.

First, we upgraded to OrientDB 2.2.10 and all the integration tests passed, but when deploy the application to tomcat we experience a problem:
- Create an instance of A and its related B and do save A. Fine. Both A and B are stored.
- Update a field in B and do a save in A. An OConcurrentModificationException is thrown.

`Error updating job. JobID: 0e426fe2-0a8c-41e8-8455-b3c8abec5443. Cannot UPDATE the record #43:5 because the version is not the latest. Probably you are updating an old record or it has been modified by another user (db=v3 your=v2)`

What is odd is that the record is saved, so I assume OrientDB is trying to save it twice, the first time works and the second fails because obviously it has been already been saved and thus the version has been increased.

What is even odder, when we try to to the same operation in the same record it fails again, but if we keep trying it eventually stops failing, and from that moment on it works well.

I have been trying but have not been able to reproduce this behavior on an integration test, it only happens when we deploy the application in Tomcat.

**Yesterday I upgraded to OrientDB 2.2.11** and now the exception is thrown **much less often**, but still happens sometimes. That's why I assume is something related to what was reported and fixed in https://github.com/orientechnologies/orientdb/issues/6729.

**Comment by diegomtassis** [comment] 2016-11-25 11:00
This is critical for us, we have a product using the object API which we can not migrate to 2.2.x due to this bug, that's why I'm spending myself some time on it to try to understand what is happening.

It's clear that it's something related to the `ODirtyManager` because it was introduced in 2.2.0 and as I said, 2.1.x works fine for us.

I'm trying to understand the code in order to be able to create an integration test reproducing the bug, but so far I have not managed to do it (I mean create the IT reproducing the bug).

But I have observed something which I think is the clue to find what is failing, and it has nothing to do with the object API but with the document API.

Given the following scenario:

1. a document A is created
2. a document B is created
3. a relatioship A->B is created
4. A is saved

The result is not deterministic, the version of A at the end might be v1 or v2, and it depends on what the `ODirtyManager` returns when `com.orientechnologies.orient.core.record.impl.ODirtyManager.getNewRecords()` is invoked.

This operation returns a set, which does not guaranteed the order of the elements. If, when iterating the set, A is returned first then in the end A is saved 2 times (so in the end A is v2), but if B is returned first then A is only saved once (A v1).

The same happens with `com.orientechnologies.orient.core.record.impl.ODirtyManager.getUpdateRecords()`.

At some place there is a check on the versions of the saved document and that's what is causing the exception we are experiencing. I will try to create a failing IT, but it's not easy because the result of the 2 methods I mentioned is not deterministic.

**Comment by tglman** [comment] 2016-11-25 15:59
hi @diegomtassis,

I understand your point, in any case the version can happen that get increased to a number bigger that +1, for example in some case when you use a merge strategy, in addition to the case that you listed, so the fact that it get a bigger value should not be an issue, I think the issue is on the way it get propagated up to the Object layer.

I'll double check the object flow as well to see if there are wrong flows or double saves.

Regards

**Comment by diegomtassis** [comment] 2016-11-25 16:28
hi @tglman 

Thanks for paying attention to this.

I've been working on it some more time and after some tests I have to agree with you, it's a problem in the object layer.

I think on Monday I will be able to commit an integration test showing a failing scenario. It has to do with how relations one-to-one are treated.

However, I don't know whether this odd behavior is the final cause for the OConcurrentModificationException we are experiencing, and that's the effective reason why we can not migrate our product to 2.2.x. I mean the object we want to update is updated, we could as a workaround do a try catch and ignore the exception when the object has been saved but we don't want to go that way.

**Comment by tglman** [comment] 2016-11-25 16:33
Hi @diegomtassis,

As soon we have a test case we can figure out and fix easily, so we will try to fix it as soon as we have it.

Regards

**Comment by diegomtassis** [comment] 2016-11-28 14:23
I'm not 100% sure, but I think this bug might be related to the fact that the 2 objects are related via a bidirectional one-to-one relationship.

I've created an integration test for this scenario, this is create 2 objects related A->B, B->A and then do save A.

[Using OrientDB 2.1.15](https://github.com/CompartAG/orientdb-tryouts/blob/4e2f98e42b0295a48582abe9f37143735530932a/2.1.x/src/test/java/com/compart/tec/orientdb/object/SaveOneToOnePojoIT.java) A is saved 2 times and B only once.

Using [OrientDB 2.2.13](https://github.com/CompartAG/orientdb-tryouts/blob/4e2f98e42b0295a48582abe9f37143735530932a/2.2.x/src/test/java/com/compart/tec/orientdb/object/SaveOneToOnePojoIT.java) A is saved once and B 2 times.

If the relationship is not bidirectional then both documents are saved only once (both with 2.1.x and 2.2.x)

If the bug is not related to this then I do not know, but the change of behavior happened between 2.1.x and 2.2.x, and when you fixed the bug mentioned in the first message the error started to happen much seldomly, that's why I think it is something related to the ODirtyManager.

**Comment by tglman** [comment] 2016-11-28 14:39
hi @diegomtassis,

Yes if two object are linked to each other when you create them, for solve correctly the links one of them should be "created mock" first to generate the rid, this in 2.1.x was managed by recursion, and in 2.2.x is solved with a "link tracking algorithm", so yes definitly the behaviour is changed.

This is the method that solve the double linking in 2.2.x: https://github.com/orientechnologies/orientdb/blob/2.2.x/core/src/main/java/com/orientechnologies/orient/core/tx/OTransactionNoTx.java#L202

by the way the double save in 2.2.x is used only in case of notTx, for the Tx cases we have a internal rid allocation on commit phase that not need the double save.
Hope this help to find the source of the problem.

Regards

**Comment by diegomtassis** [comment] 2016-11-28 15:33
We use Tx everywhere (except in some ITests), then I've been following the wrong track.

We will try to get rid of the bidirectional relationships between our pojos and then test the application again to see if the exception disappears.

**Comment by tglman** [comment] 2016-12-13 15:39
hi @diegomtassis,

One poitner that may help you is this : https://github.com/orientechnologies/orientdb/blob/2.2.x/core/src/main/java/com/orientechnologies/orient/core/storage/impl/local/OAbstractPaginatedStorage.java#L1410

here is where we notify for the changed ids in the upper layers, so i guess something is missing on top of that, in any case if you have an example test cases we can try to fix this.

Regards

**Comment by diegomtassis** [comment] 2017-01-31 10:09
I have been busy with other topics, but now I can confirm that the bug is due to the bidirectional relationship.

We got rid of the bidirectional relationship in our product (we were not using it, it was there because an over engineered design) and the exception vanished.

**Comment by tglman** [comment] 2017-02-27 13:30
hi @diegomtassis,

I fixed an issue on wrong dirty managment in the object database layer, that could cause a that two instance of the same record where retained in memory and on save this would have caused a wrong MVCC exception, here is the commit: https://github.com/orientechnologies/orientdb/commit/5c782646fc078d072acd86712b2dfc66a291c387, so because of this i believe this issue has been fixed, the fix will be released in 2.2.19, with some other fixes on the object layer.

Regards

**Comment by tglman** [comment] 2017-06-05 15:49
Hi,

This should have been fixed a while ago, I'm going to close this.

Re-open if still happen.

Regards

**Closed by tglman** 2017-06-05 15:49 UTC
Labels: bug, resolved
