### ISSUE TITLE
NullPointerException when Check Database

### ISSUE THREAD

**Issue by Bankde** [orientechnologies/orientdb#7881] opened 2017-11-13 09:22 UTC
## Expected behavior  
Check Database should always return a result gracefully (either success or fail)

## Actual behavior  
Check Database return Error: java.lang.NullPointerException

## Steps to reproduce  
I have corrupted database (very same as #7722). After having upgraded most databases in testing team from 2.4 to 2.29, we encounter that issue again. The problem probably lies within compatibility of orientdb core between 2.4 and 2.23+ (hopefully we don't have to discuss that issue again). I went straight to Check Database, it returned a lot (around 17k) of corrupted edge and ended at Error: java.lang.NullPointerException

Check Database is done in 2.29

**Comment by laa** [comment] 2017-11-13 10:57
@Bankde could you return a full stack trace of NPE, preferably as separate gist?

**Comment by Bankde** [comment] 2017-11-14 02:53
@laa Hi, where can I find or enable full stack trace ? Couldn't find it anywhere.

**Comment by laa** [comment] 2017-11-14 04:57
@Bankde did you run it in the console, did not you?
Could you change file orientdb-client-log.properties as following https://gist.github.com/laa/43dfc8d6cdbb83092588a7195f6aed2e  and then run check database again?

**Comment by Bankde** [comment] 2017-11-14 06:01
There is now log when connect to db
```
2017-11-14 12:55:32:466 INFO  OrientDB auto-config DISKCACHE=1,040MB (heap=989MB direct=524,288MB os=4,078MB) [OMemoryAndLocalPaginatedEnginesInitializer]
2017-11-14 12:55:33:555 SEVER {db=cw_database} Magic number verification failed for page '61' of 'transaction.pcl'. [OWOWCache]
and so on
```
Log after calling check database
```
2017-11-14 12:55:52:666 WARNI {db=cw_database} Unrecognized option database, skipped [OGremlinConsole]
-- lot of found corrupted edge here --
Error: java.lang.NullPointerException
```
still no stacktrace.

**Comment by laa** [comment] 2017-11-14 07:55
@Bankde could you switch to the debug mode and set breakpoint for NPE exception and send me the line number where it happens?

**Comment by Bankde** [comment] 2017-11-14 09:01
@laa I and my team have never debug java before. Do you have any suggested guide ?

**Comment by laa** [comment] 2017-11-14 09:05
@Bankde did you check files in the log folder?

**Comment by Bankde** [comment] 2017-11-14 10:21
sure I did, I even changed log destination to /tmp and orient-console.log already appears there but there's no stacktrace in that log.

**Comment by laa** [comment] 2017-11-14 10:24
@Bankde I see so that is exception above the storage, I will send you new distribution soon, in few days, so we can log full stack trace.

**Comment by Bankde** [comment] 2017-11-15 02:56
Hi @laa From jdb
https://gist.github.com/Bankde/ab873abaa9c75a0ba09a240db5f6e3bc

**Comment by laa** [comment] 2017-11-15 06:33
Hi @Bankde, do you have original database not opened on this server? I suggest you do following - export database to json using 2.2.4 version and then import in 2.2.30 version. Either edge file is broken or it merely does not exist. The big problem here is that we can not reproduce it again. But I am pretty sure that those steps will fix the issue.

**Comment by Alidstar** [comment] 2017-11-17 11:36
I will handle this issue instead of @Bankde 
I need a couple days to test after import.
Then I will reply to you again.

**Comment by laa** [comment] 2017-11-17 13:05
Hi @Alidstar , glad to e-meet you. Will be waiting for your response then.

**Comment by Bankde** [comment] 2017-11-20 13:09
Hi @laa, sry for inconvenient. My team @Alidstar has done exactly what you suggested and tested for 2 days. As far as we know, there is no error yet.

Do you think export/import when changing ordb version produces more stable database ? What is the best practice to upgrade ordb version ?

**Comment by laa** [comment] 2017-11-20 13:13
HIi @Bankde , as you already guessed, I suppose, the most reliable way to upgrade from one version to another is the use of export in old version and import in the new one. 
If you follow such approach you will also unlock all new features of new updates.

**Comment by laa** [comment] 2017-12-27 06:31
Closing this issue because seems like the problem is fixed.

**Closed by laa** 2017-12-27 06:31 UTC
Labels: bug
