### ISSUE TITLE
Post request don't work after changing to version 2.2.0

### ISSUE THREAD

**Issue by lucevers** [orientechnologies/orientdb#6178] opened 2016-05-21 04:55 UTC
### Runninng Mode
- [ ] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [x] Remote

### Misc
- [x] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition

### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [ ] v2.1.x - Please specify last number: 
- [x] v2.2.x - Please specify last number: 

### Operating System
- [x] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

### Java Version
- [ ] 6
- [ ] 7
- [x] 8

**Comment by lucevers** [comment] 2016-05-21 05:05
1) Orient: 2.1.3
         test:  golang program sends a post request:
              http://195.13.20.2:2480/command/pops/sql/create class nps
       (with the right syntax %20 ..+ sending the credentials)
        Result:  oke

2) Orient: 2.2.0
       same request but then I got:
       Bad HTTP response %v 204

There are fundamental changes in rest for orient 2.2.0.
We need to return to 2.1.3!
The test is done for one server and  cluster, same problems.

**Comment by lucevers** [comment] 2016-05-21 07:09
More info

   It seems that the problem is cause by using the old datase (version 2.13)
   There are no problems if I start a clean install of orient 2.2.0 and start the golang program.
   
   So, how can I move de databases from version 2.1.3 to 2.2.0 ?

**Comment by lvca** [comment] 2016-05-21 10:09
@tglman do you have any idea why such incompatibility?

**Comment by tglman** [comment] 2016-05-24 14:48
hi @lucevers,

Do you have some more detail about the error ? any stack trace on the server side ?

It could be an encoding issue or something like that, will be amazing if you could send us the db that has this problem, it will speed up a lo the fix.

Regards

**Comment by tglman** [comment] 2016-05-24 14:48
hi @lucevers,

Do you have some more detail about the error ? any stack trace on the server side ?

It could be an encoding issue or something like that, will be amazing if you could send us the db that has this problem, it will speed up a lo the fix.

Regards

**Comment by tglman** [comment] 2016-05-24 14:48
hi @lucevers,

Do you have some more detail about the error ? any stack trace on the server side ?

It could be an encoding issue or something like that, will be amazing if you could send us the db that has this problem, it will speed up a lo the fix.

Regards

**Comment by lucevers** [comment] 2016-05-26 08:01
I cannot send the internal database because of sensitive client data. Because we decided to use Orientdb I shall start more tests if a new release is coming up and send you more details.
 Sorry about this.

**Comment by lvca** [comment] 2016-05-26 11:48
Ok, closing this issue because is not reproducible. In case reopen it.

**Closed by lvca** 2016-05-26 11:48 UTC
