### ISSUE TITLE
Studio: improve schema editor

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#7027] opened 2016-12-20 11:09 UTC
The schema editor should make easier to create and modify a schema-full graph. I'm referring in particular on modelling edges with out/in as LINKs to vertex properties, using the polymorphism too.

Some of the feature I'd like to see:
- ad-hoc form to create vertex class:
  - by auto setting V as base class by default and filtering only the vertices classes in the superclass field
- ad-hoc form to create edge class
  - by auto setting E as base class by default and filtering only the edges classes in the superclass 
  - define out and in with constraints to vertex classes
- in any case, support a custom number of pre-created clusters

**Comment by santo-it** [comment] 2017-01-12 16:51
Thanks. Closing as duplicate of this https://github.com/orientechnologies/orientdb-studio/issues/431

**Closed by santo-it** 2017-01-12 16:51 UTC
Labels: duplicate, enhancement, studio
