### ISSUE TITLE
ORecordNotFoundException with -2 cluster under stress conditions

### ISSUE THREAD

**Issue by benjaminbillet** [orientechnologies/orientdb#6852] opened 2016-10-27 09:10 UTC
## OrientDB Version, operating system, or hardware.

OrientDB 2.2.12, MacOS Sierra, Java API
## Expected behavior and actual behavior

Hi, 
I work with a query generator that produces type-clustered Breadth First Search queries, such as : 
`SELECT $_root.nextVertices AS _root, $_layerA AS _layerA LET $_root = map('nextVertices', (SELECT FROM RootType)), $_layerA = (SELECT @rid AS parentId, out('rootToA') AS nextVertices FROM $_root.nextVertices) FETCHPLAN _root:1 _layerA:2` (in this example, $_root will contains the set of root nodes and $_layerA will contains the nodes of type TypeA that are direct descendant of the root nodes).

Such requests creates a lot of "fake" nodes (#-2:*) and, under stress conditions (large dataset or loop), an ORecordNotFoundException is thrown (see stack trace below).

The problem never happens when I run my queries in Studio.

```
Exception in thread "main" com.orientechnologies.orient.core.exception.ORecordNotFoundException: The record with id '#-2:3561' was not found
    DB name="testDatabase"
    DB name="testDatabase"
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
    at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.throwSerializedException(OChannelBinaryAsynchClient.java:428)
    at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:379)
    at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:261)
    at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:153)
    at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:2132)
    at com.orientechnologies.orient.client.remote.OStorageRemote$9.execute(OStorageRemote.java:663)
    at com.orientechnologies.orient.client.remote.OStorageRemote$9.execute(OStorageRemote.java:645)
    at com.orientechnologies.orient.client.remote.OStorageRemote$2.execute(OStorageRemote.java:196)
    at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:228)
    at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperation(OStorageRemote.java:193)
    at com.orientechnologies.orient.client.remote.OStorageRemote.readRecord(OStorageRemote.java:645)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx$SimpleRecordReader.readRecord(ODatabaseDocumentTx.java:3238)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1888)
    at com.orientechnologies.orient.core.tx.OTransactionNoTx.loadRecord(OTransactionNoTx.java:115)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:1628)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:103)
    at com.orientechnologies.orient.core.id.ORecordId.getRecord(ORecordId.java:330)
    at com.tinkerpop.blueprints.impls.orient.OrientElementIterator.next(OrientElementIterator.java:62)
    at com.tinkerpop.blueprints.impls.orient.OrientElementIterator.next(OrientElementIterator.java:35)
    at Test7.main(Test7.java:41)
Caused by: java.lang.IllegalArgumentException: Cluster segment #-2 does not exist in database 'testDatabase'
    at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.checkClusterSegmentIndexRange(OAbstractPaginatedStorage.java:3739)
    at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.getClusterById(OAbstractPaginatedStorage.java:2424)
    at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OAbstractPaginatedStorage.java:1081)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx$SimpleRecordReader.readRecord(ODatabaseDocumentTx.java:3238)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1888)
    at com.orientechnologies.orient.core.tx.OTransactionNoTx.loadRecord(OTransactionNoTx.java:97)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:1651)
    at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:103)
    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.readRecord(ONetworkProtocolBinary.java:1791)
    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:533)
    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:321)
    at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:197)
    at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
```

Given that the proplem occurs only when I stress the database, it may be a race condition somewhere in the Java API.
## Steps to reproduce the problem

Here is a snippet for reproducing the problem. You can vary the number of nodes with the nbRoots variable. With my computer, the problem occurs around nbRoots >= 4000. However, if I increase the number of branches (more layers), the exception can be thrown with less than 100 root nodes.

``` java
OrientGraph graph = ...
graph.begin();

graph.command(new OCommandSQL("DELETE VERTEX V")).execute();
graph.commit();

int nbRoots = 4000;
for (int i = 0; i < nbRoots; i++) {
    OrientVertex root = graph.addVertex("class:RootType");
    OrientVertex child = graph.addVertex("class:TypeA");
    root.addEdge("rootToA", child);
}
graph.commit();

String query = "SELECT $_root.nextVertices AS _root, $_layerA AS _layerA LET $_root = map('nextVertices', (SELECT FROM RootType)), $_layerA = (SELECT @rid AS parentId, out('rootToA') AS nextVertices FROM $_root.nextVertices) FETCHPLAN _root:1 _layerA:2";
Iterable<OrientVertex> results = graph.command(new OCommandSQL(query)).execute();
OrientVertex first = results.iterator().next();

Iterable<OrientVertex> vertices = first.getProperty("_layerA");
for (OrientVertex vertex : vertices) {
    vertex.getProperties();
}
```

**Comment by laa** [comment] 2016-10-27 09:41
Hi @benjaminbillet , is it correct that you run this code in single thread mode on remote storage, and as result you get ORecordNotFoundException ?

**Comment by benjaminbillet** [comment] 2016-10-27 11:21
Hi,
I run this code on remote storage and the code snippet I provided is executed in a single thread. Just to be sure, here is how I create my OrientGraph object:

```javacode
OrientGraphFactory factory = new OrientGraphFactory("remote:localhost/testDatabase", "root", "password");
factory.setAutoStartTx(false);
factory.setMaxRetries(100);
OrientGraph graph = factory.getTx();
```

**Comment by tglman** [comment] 2016-10-27 11:44
hi @benjaminbillet,

A similar bag has been solved recently, can you check with the last hotfix, 2.2.12.

Thank you

**Comment by benjaminbillet** [comment] 2016-10-27 12:08
Hi @tglman 
I have exactly the same problem with 2.2.12 (I updated my first post).
Thank you.

**Comment by benjaminbillet** [comment] 2016-10-27 12:33
Just to be sure, I tried to convert the query to a script, but it didn't solve the problem.

```
BEGIN
LET rootNodes = SELECT FROM RootType FETCHPLAN *:1
LET layerA = SELECT @rid AS parentId, out('rootToA') AS nextVertices FROM $rootNodes FETCHPLAN *:2
RETURN { roots: $rootNodes, layerA: $layerA }
```

**Comment by tglman** [comment] 2016-10-27 13:32
hi @benjaminbillet, 

I think the problem is related to the fetch plan can you try to write the query in a different way ex:
`SELECT $_root.nextVertices AS _root, {'parentId': $_layerA.@rid, 'nextVertices':$_layerA.out('rootToA')} AS _layerA LET $_root = map('nextVertices', (SELECT FROM RootType)), $_layerA = (SELECT FROM $_root.nextVertices) FETCHPLAN _root:1 _layerA:2`

this should not cause your problem, anyway double check the query, i don't have the data for try it.

Bye

**Comment by benjaminbillet** [comment] 2016-10-27 14:55
I tried the query and it returns `_layerA = {"nextVertices":null,"parentId":null}` in Studio (however, the $_layerA variable contains the proper results).

If you want to try it yourself, my dataset is generated with this simple code:
```java
int nbRoots = 4000;
for (int i = 0; i < nbRoots; i++) {
    OrientVertex root = graph.addVertex("class:RootType");
    OrientVertex child = graph.addVertex("class:TypeA");
    root.addEdge("rootToA", child);
}
```

Anyway, it is very strange that the problem occurs only when the database is stressed.

Thanks

**Comment by benjaminbillet** [comment] 2016-10-28 10:47
@tglman By the way, even a simple request like `SELECT {items: $allVertices} AS items LET $allVertices = (SELECT FROM V)` returns `{"items":null}`. Do you want me to open another issue for this new problem?

**Comment by tglman** [comment] 2016-10-28 12:47
hi @benjaminbillet,

I figured out a way to retain in the client the temporary records (the one with clusterId -2) so a fixed this case, is going to be released with 2.2.13.

bye

**Comment by benjaminbillet** [comment] 2016-10-28 13:38
@tglman Very good, thank you. Regarding the failure of `SELECT {items: $allVertices} AS items LET $allVertices = (SELECT FROM V)` (the result is null), should I open another issue?

**Comment by tglman** [comment] 2016-10-28 14:17
hi,

Yes i think is a good idea to open another issue about that.

Bye

**Comment by tglman** [comment] 2016-11-17 13:46
fixed and released, closing

**Closed by tglman** 2016-11-17 13:46 UTC
Labels: bug, resolved

**Comment by benjaminbillet** [comment] 2017-01-18 08:14
Hi,

Unfortunately, the problem still occurs with 2.2.13 and 2.2.14.

To be fair, the exception is more rarely thrown than with 2.2.12. I had to increase `nbRoots` to 100000 to see the exception. However, if I increase the number of branches (more layers), the exception can be thrown with less than 1000 root nodes.

Could it be a memory problem (in which case I would expect an OutOfMemoryException) ?

**Comment by benjaminbillet** [comment] 2017-01-18 09:23
Hi again,
I tried something new for reproducing the problem: instead of increasing the number of root nodes, I increased the number of sequential requests. It makes the problem very easy to reproduce.

```java
OrientGraph graph = factory.getTx();
graph.begin();

graph.command(new OCommandSQL("DELETE VERTEX V")).execute();
graph.commit();

int nbRoots = 1000;
for (int i = 0; i < nbRoots; i++) {
    OrientVertex root = graph.addVertex("class:RootType");
    OrientVertex child = graph.addVertex("class:TypeA");
    root.addEdge("rootToA", child);
}
graph.commit();
graph.shutdown();

int nbRuns = 50;
for (int i = 0; i < nbRuns; i++) {
    graph = factory.getTx();

    String query = "SELECT $_root.nextVertices AS _root, $_layerA AS _layerA LET $_root = map('nextVertices', (SELECT FROM RootType)), $_layerA = (SELECT @rid AS parentId, out('rootToA') AS nextVertices FROM $_root.nextVertices) FETCHPLAN _root:1 _layerA:2";
    Iterable<OrientVertex> results = graph.command(new OCommandSQL(query)).execute();
    OrientVertex first = results.iterator().next();

    Iterable<OrientVertex> vertices = first.getProperty("_layerA");
    for (OrientVertex vertex : vertices) {
        vertex.getProperties();
    }

    graph.shutdown();
}
```
