### ISSUE TITLE
Lucene indexes are removed if lucene plugin is not installed

### ISSUE THREAD

**Issue by rmuller** [orientechnologies/orientdb#3522] opened 2015-02-04 10:21 UTC
When the lucene plugin is not installed a error is logged:
`Error on loading index by configuration: {type:FULLTEXT,name:Party.text ,... com.orientechnologies.orient.core.index.OIndexException: Engine type: 'LUCENE' is not supported. Types are [SBTREE,MVRBTREE]. Please check the engine name or verify that the engine 'LUCENE' is installed correctly`

This is correct and expected. However, when the database is started with the lucene engine installed, the lucene index is not present anymore. IMO this is not expected, the index should be ignored/unavailable, not removed

**Comment by maggiolo00** [comment] 2015-09-22 12:58
hi @rmuller 
as it fails the first time to create the index OrientDB engine remove the index from the configuration. So when the plugins is installed. The index is longer available. As the lucene plugin now is in bundle with the OrientDB distribution i think we can close this. WDYT

**Comment by prjhub** [comment] 2015-10-07 11:42
The issue has been closed because no response has been received after a while. In case the issue is still valid, please reopen it or write a comment that explains why it's still valid and a way to reproduce it. Thank you.

**Closed by prjhub** 2015-10-07 11:42 UTC
Labels: bug, waiting reply
