### ISSUE TITLE
OrientDb killed itself without any abnormal log, while database is corruted.

### ISSUE THREAD

**Issue by efenzha** [orientechnologies/orientdb#8884] opened 2019-05-29 07:04 UTC
## Expected behavior  
No error during high concurrent writing

## Actual behavior  
crashes after around 3 hours silently.
The test is done twice, both of them crashed when around 10million vertices are inserted.

## Steps to reproduce  
adding vertex and edges with Spark, around 15000 records writing per second, WAL is disabled.

Config:
ORIENTDB_OPTS_MEMORY="-Xms2G -Xmx4G"
JAVA_OPTS_SCRIPT="-Djna.nosys=true -XX:+HeapDumpOnOutOfMemoryError -XX:MaxDirectMemorySize=512G -Djava.awt.headless=true -Dfile.encoding=UTF8 -Drhino.opt.level=9"
ORIENTDB_SETTINGS="-Dstorage.useWAL=false"

The last line log on server.sh:
INFO  Created database 'fromMongo1' of type 'plocal' [OConnectionBinaryExecutor]**Killed**

Error after restart:
2019-05-29 08:49:06:885 SEVER Magic number verification failed for page `1` of `config.bd`. [OWOWCache]
2019-05-29 08:49:06:886 SEVER Magic number verification failed for page `1` of `config.bd`.
java.lang.Exception
	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.dumpStackTrace(OWOWCache.java:2294)
	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.verifyMagicAndChecksum(OWOWCache.java:2252)
	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.loadFileContent(OWOWCache.java:2152)
	at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.load(OWOWCache.java:1125)
	at com.orientechnologies.orient.core.storage.cache.chm.AsyncReadCache.lambda$doLoad$0(AsyncReadCache.java:150)
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853)
	at com.orientechnologies.orient.core.storage.cache.chm.AsyncReadCache.doLoad(AsyncReadCache.java:147)
	at com.orientechnologies.orient.core.storage.cache.chm.AsyncReadCache.loadForRead(AsyncReadCache.java:115)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.loadPageForRead(ODurableComponent.java:140)
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurableComponent.loadPageForRead(ODurableComponent.java:134)
	at com.orientechnologies.orient.core.storage.index.sbtree.singlevalue.OCellBTreeSingleValue.findBucket(OCellBTreeSingleValue.java:1264)
	at com.orientechnologies.orient.core.storage.index.sbtree.singlevalue.OCellBTreeSingleValue.get(OCellBTreeSingleValue.java:178)
	at com.orientechnologies.orient.core.storage.config.OClusterBasedStorageConfiguration.readProperty(OClusterBasedStorageConfiguration.java:1657)
	at com.orientechnologies.orient.core.storage.config.OClusterBasedStorageConfiguration.readConfiguration(OClusterBasedStorageConfiguration.java:832)
	at com.orientechnologies.orient.core.storage.config.OClusterBasedStorageConfiguration.load(OClusterBasedStorageConfiguration.java:195)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:377)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthenticate(OrientDBEmbedded.java:236)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthenticate(OrientDBEmbedded.java:59)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:936)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:913)
	at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeDatabaseOpen37(OConnectionBinaryExecutor.java:1187)
	at com.orientechnologies.orient.client.remote.message.OOpen37Request.execute(OOpen37Request.java:77)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:304)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:206)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
 [OWOWCache]

 [OWOWCache]Exception `47285CE8` in storage `plocal:/repo/flocxdev/apps/orientdb-3.0.18/databases/fromMongo1`: 3.0.18 - Veloce (build 747595e790a081371496f3bb9c57cec395644d82, branch 3.0.x)
com.orientechnologies.orient.core.storage.index.sbtree.singlevalue.OCellBTreeSingleValueException: We reached max level of depth of SBTree but still found nothing, seems like tree is in corrupted state. You should rebuild index related to given query.
	Component Name="config"
	at com.orientechnologies.orient.core.storage.index.sbtree.singlevalue.OCellBTreeSingleValue.findBucket(OCellBTreeSingleValue.java:1259)
	at com.orientechnologies.orient.core.storage.index.sbtree.singlevalue.OCellBTreeSingleValue.get(OCellBTreeSingleValue.java:178)
	at com.orientechnologies.orient.core.storage.config.OClusterBasedStorageConfiguration.readProperty(OClusterBasedStorageConfiguration.java:1657)
	at com.orientechnologies.orient.core.storage.config.OClusterBasedStorageConfiguration.readConfiguration(OClusterBasedStorageConfiguration.java:832)
	at com.orientechnologies.orient.core.storage.config.OClusterBasedStorageConfiguration.load(OClusterBasedStorageConfiguration.java:195)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.open(OAbstractPaginatedStorage.java:377)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthenticate(OrientDBEmbedded.java:236)
	at com.orientechnologies.orient.core.db.OrientDBEmbedded.openNoAuthenticate(OrientDBEmbedded.java:59)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:936)
	at com.orientechnologies.orient.server.OServer.openDatabase(OServer.java:913)
	at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeDatabaseOpen37(OConnectionBinaryExecutor.java:1187)
	at com.orientechnologies.orient.client.remote.message.OOpen37Request.execute(OOpen37Request.java:77)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:304)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:206)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)

**Comment by efenzha** [comment] 2019-05-29 11:00
I did a new test, which only inserts vertex, without any edges. No any error logs.

OrientDb still kills itself after around 11-12 million vertices.

**Comment by luigidellaquila** [comment] 2019-05-29 11:21
Hi @efenzha 

Do you see any exception in the logs, before the process goes down?
If you don't see anything, probably it's not OrientDB that is killing itself, but the operating system that is killing it (because of low memory typically).
I'd suggest to explicitly set the heap and the disk cache size, see https://orientdb.org/docs/3.0.x/tuning/Performance-Tuning.html#server-and-embedded-settings

Thanks

Luigi

**Comment by efenzha** [comment] 2019-05-29 11:47
Hi @luigidellaquila ,

Thanks for the reply.

There is no exception in the log.

The node I am using has 32 G memory. I changed server.sh as below. How do you think?

`
ORIENTDB_OPTS_MEMORY="-Xms2G -Xmx4G"
JAVA_OPTS_SCRIPT="XX:MaxDirectMemorySize=512G ...."
ORIENTDB_SETTINGS="-Dstorage.useWAL=false -Dstorage.diskCache.bufferSize=8000"
`

**Comment by laa** [comment] 2019-05-29 12:04
Hi, to understand what was the cause of the issue (very likey that was OOM killer) I need logs from the start of the server.

**Comment by efenzha** [comment] 2019-05-29 12:10
Hi @laa ,

There is no exception in the log, but on the **console** of server.sh, there is '**Killed**' attached at the end.

_INFO Created database 'fromMongo1' of type 'plocal' [OConnectionBinaryExecutor]**_Killed**

`

2019-05-29 12:17:29:603 INFO  Detected limit of amount of simultaneously open files is 8192,  limit of open files for disk cache will be set to 3584 [ONative]
2019-05-29 12:17:29:604 WARNI Value of limit of simultaneously open files is too small, recommended value is 262144 [ONative]
2019-05-29 12:17:29:613 INFO  Loading configuration from: /repo/flocxdev/apps/orientdb-3.0.18/config/orientdb-server-config.xml... [OServerConfigurationLoaderXml]
2019-05-29 12:17:29:775 INFO  OrientDB Server v3.0.18 - Veloce (build 747595e790a081371496f3bb9c57cec395644d82, branch 3.0.x) is starting up... [OServer]
2019-05-29 12:17:29:820 INFO  33669881856 B/32110 MB/31 GB of physical memory were detected on machine [ONative]
2019-05-29 12:17:29:820 INFO  Soft memory limit for this process is set to -1 B/-1 MB/-1 GB [ONative]
2019-05-29 12:17:29:821 INFO  Hard memory limit for this process is set to -1 B/-1 MB/-1 GB [ONative]
2019-05-29 12:17:29:821 INFO  Path to 'memory' cgroup is '/' [ONative]
2019-05-29 12:17:29:823 INFO  Mounting path for memory cgroup controller is '/cgroup/memory' [ONative]
2019-05-29 12:17:29:823 INFO  cgroup soft memory limit is 9223372036854775807 B/8796093022207 MB/8589934591 GB [ONative]
2019-05-29 12:17:29:823 INFO  cgroup hard memory limit is 9223372036854775807 B/8796093022207 MB/8589934591 GB [ONative]
2019-05-29 12:17:29:824 INFO  Detected memory limit for current process is 33669881856 B/32110 MB/31 GB [ONative]
2019-05-29 12:17:29:824 INFO  JVM can use maximum 3641MB of heap memory [OMemoryAndLocalPaginatedEnginesInitializer]
2019-05-29 12:17:29:825 INFO  Because OrientDB is running outside a container 12% of memory will be left unallocated according to the setting 'memory.leftToOS' not taking into account heap memory [OMemoryAndLocalPaginatedEnginesInitializer]
2019-05-29 12:17:29:825 INFO  OrientDB auto-config DISKCACHE=24,615MB (heap=3,641MB os=32,110MB) [orientechnologies]
2019-05-29 12:17:29:826 INFO  System is started under an effective user : `flocxdev` [OEngineLocalPaginated]
2019-05-29 12:17:29:854 INFO  WAL maximum segment size is set to 6,144 MB [OrientDBDistributed]
2019-05-29 12:17:29:855 INFO  Databases directory: /repo/flocxdev/apps/orientdb-3.0.18/databases [OServer]
2019-05-29 12:17:30:098 INFO  Storage 'plocal:/repo/flocxdev/apps/orientdb-3.0.18/databases/OSystem' is opened under OrientDB distribution : 3.0.18 - Veloce (build 747595e790a081371496f3bb9c57cec395644d82, branch 3.0.x) [OLocalPaginatedStorage]
2019-05-29 12:17:30:406 INFO  Listening binary connections on 0.0.0.0:2424 (protocol v.37, socket=default) [OServerNetworkListener]
2019-05-29 12:17:30:408 INFO  Listening http connections on 0.0.0.0:2480 (protocol v.10, socket=default) [OServerNetworkListener]
2019-05-29 12:17:30:415 INFO  Installing dynamic plugin 'orientdb-neo4j-importer-plugin-3.0.18-dist.jar'... [OServerPluginManager]
2019-05-29 12:17:30:419 INFO  Installing dynamic plugin 'orientdb-studio-3.0.18.zip'... [OServerPluginManager]
2019-05-29 12:17:30:420 INFO  Installing dynamic plugin 'orientdb-teleporter-3.0.18.jar'... [OServerPluginManager]
2019-05-29 12:17:30:424 INFO  Installing dynamic plugin 'orientdb-etl-3.0.18.jar'... [OServerPluginManager]
2019-05-29 12:17:30:427 INFO  ODefaultPasswordAuthenticator is active [ODefaultPasswordAuthenticator]
2019-05-29 12:17:30:427 INFO  OServerConfigAuthenticator is active [OServerConfigAuthenticator]
2019-05-29 12:17:30:428 INFO  OSystemUserAuthenticator is active [OSystemUserAuthenticator]
2019-05-29 12:17:30:428 INFO  [OVariableParser.resolveVariables] Property not found: distributed [orientechnologies]
2019-05-29 12:17:30:434 WARNI Authenticated clients can execute any kind of code into the server by using the following allowed languages: [sql] [OServerSideScriptInterpreter]
2019-05-29 12:17:30:435 INFO  OrientDB Studio available at http://147.214.146.87:2480/studio/index.html [OServer]
2019-05-29 12:17:30:435 INFO  OrientDB Server is active v3.0.18 - Veloce (build 747595e790a081371496f3bb9c57cec395644d82, branch 3.0.x). [OServer]
2019-05-29 12:17:39:809 INFO  Storage 'plocal:/repo/flocxdev/apps/orientdb-3.0.18/databases/fromMongo1' is created under OrientDB distribution : 3.0.18 - Veloce (build 747595e790a081371496f3bb9c57cec395644d82, branch 3.0.x) [OLocalPaginatedStorage]
2019-05-29 12:17:40:705 INFO  Created database 'fromMongo1' of type 'plocal' [OConnectionBinaryExecutor]
`

**Comment by laa** [comment] 2019-05-29 13:08
Hi, @efenzha could you add 10 million vertexes and provide heap dump for me and also show me total memory consumption of ODB server process?

**Comment by efenzha** [comment] 2019-05-29 13:28
Hi Andery,

I will be on vacation 4 days, and do the test next week.

Are there any pages which could guide me collecting heap dump and memory
consumption? I didn't try this before.

Andrey Lomakin <notifications@github.com> 于 2019年5月29日周三 15:08写道：

**Comment by laa** [comment] 2019-05-29 13:36
I see that can be done using the command: `jmap -dump:format=b,file=<file-path> <pid>`. Where `<file-path>` is path to the file in which heap dump will be stored.

**Comment by efenzha** [comment] 2019-05-29 13:51
Ok, I will type this command when it has 10 million vertices.

Which command can be used to collect memory consumption?

Andrey Lomakin <notifications@github.com> 于 2019年5月29日周三 15:36写道：

**Comment by laa** [comment] 2019-05-29 13:57
@efenzha that is the same command.

**Comment by laa** [comment] 2019-05-29 13:59
@efenzha sorry, not the same. Please use `sudo pmap <pid>` command.

**Comment by efenzha** [comment] 2019-06-04 11:46
@luigidellaquila , @laa 

The problem is solved after explicitly setting MaxDirectMemorySize and Dstorage.diskCache.bufferSize

Thank you all!

**Comment by laa** [comment] 2019-06-04 12:01
Good to hear that :-). I am closing the issue then.

**Closed by laa** 2019-06-04 12:01 UTC

**Comment by ragnarkurmwunder** [comment] 2021-11-11 10:20
I'd say the issue is semi-solved.
Because the database just dies,
instead of properly reporting the problem,
and leaving the database intact.

**Comment by andrii0lomakin** [comment] 2021-11-11 12:07
Hi @ragnarkurmwunder , let me add a few comments:
1. If you disable the WAL database can not guarantee the durability of the database. WAL is used to restore the database after the crash.
2. According to the last message database instance was killed by the OS OOM monitoring process. DB does not know anything about this process and can not provide any logs. But I suppose you have messages in the system log from the OOM monitor.
