### ISSUE TITLE
OutOfMemoryError when making multiple insertions with remote access

### ISSUE THREAD

**Issue by BrunoSupiot** [orientechnologies/orientdb#4259] opened 2015-06-01 10:15 UTC
We are currently testing multiple insertions batches, with a binary field of 18Mo size. In our scenario, we are creating 1000 objects containing this blob field. At approximatively 290 objects created, we have an OutOfMemoryError on the client size (remote access), not on the server side. This problem doesnt arrive when we are working localy (PLOCAL access). Note that we udses the OrientGraphNoTx (without transactions) access.

**Comment by lvca** [comment] 2016-05-26 22:00
@BrunoSupiot How can I reproduce it?

**Comment by tglman** [comment] 2016-09-29 16:20
hi @BrunoSupiot,

Just a simple question, did you chage the memory settings of the server ? by default the size of the server heap is 512MB it can be not enough for your case, are you doing the creation using TX or NoTX ?

**Comment by tglman** [comment] 2016-11-18 15:24
Hi @BrunoSupiot,

Did you have any change to try the suggested solution ?

Bye

**Comment by tglman** [comment] 2016-12-27 15:18
hi @BrunoSupiot,

I'm going to close this, because is pending since a while, please reopen if you still have problems.

Regards

**Closed by tglman** 2016-12-27 15:18 UTC
Labels: bug
