### ISSUE TITLE
unable to find a way working for passing a bytearray to a server

### ISSUE THREAD

**Issue by publicocean0** [orientechnologies/orientdb#6629] opened 2016-08-29 13:28 UTC
version 2.2.6
## Operating System
- [x ] Linux
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
	                HashMap<String,Object> m=new HashMap();
			m.put("a", new byte[]{1,2,3});
		         db.command(new OCommandSQL("select insertBlock(:a)  ")).execute(m);

seams to pass ::a instead byte array

**Comment by publicocean0** [comment] 2016-08-29 13:31
i trying to search to find a way for passing a bytearray to server for executing a kind of  script/command in server directly

**Comment by luigidellaquila** [comment] 2016-09-25 08:32
Hi @publicocean0 

I'm doing a little fix to support this, I'll keep you posted. The problem is limited to binary parameters

Thanks

Luigi

**Comment by publicocean0** [comment] 2016-09-25 10:02
cool , thanks Luigi

**Comment by luigidellaquila** [comment] 2016-09-25 11:27
Hi @publicocean0 

I just pushed a fix on 2.2.x branch, now the basic syntax works correctly.
I'm not porting the fix on develop just because there it will work natively with the new executor

Thanks

Luigi

**Closed by luigidellaquila** 2016-09-25 11:27 UTC
Labels: bug
