### ISSUE TITLE
Transactions and OTraverse

### ISSUE THREAD

**Issue by c-klinger** [orientechnologies/orientdb#3068] opened 2014-11-17 19:38 UTC
Hey guys,

i currently working with transactions and OTraverse in an application and sometimes i got some unexplainable and hard to reproduce behaviour.

I wrote the following unit test which fails at the second assert (you can test this code by copy and paste to com.orientechnologies.orient.test.database.auto.TransactionConsistencyTest). 

Two possibilities: i get something wrong or there is a bug. can someone else please check this?

	@Test
	public void testName() throws Exception {
	
		database1 = new ODatabaseDocumentTx(url).open("admin", "admin");
		database2 = new ODatabaseDocumentTx(url).open("admin", "admin");
	
		database1.begin();
	
		ODocument doc1 = database1.newInstance();
		doc1.field(NAME, "docA");
		database1.save(doc1);
	
		ODocument doc2 = database1.newInstance();
		doc2.field(NAME, "docB");
		doc2.field("out_prev", doc1);
		database1.save(doc2);
	
		ODocument doc3 = database1.newInstance();
		doc3.field(NAME, "docC");
		doc3.field("out_prev", doc2);
		database1.save(doc3);
	
		database2.begin();
		ODocument doc4 = database2.newInstance();
		doc4.field(NAME, "docD");
		doc4.field("out_prev", doc3);
		database2.save(doc4);
	
		List<OIdentifiable> resultList1 = new ArrayList<OIdentifiable>();
		for (OIdentifiable id : new OTraverse().target(doc3).field("out_prev")) {
			resultList1.add(id);
		}
		// three documents in uncommited transaction
		Assert.assertEquals(resultList1.size(), 3);
	
		List<OIdentifiable> resultList2 = new ArrayList<OIdentifiable>();
		for (OIdentifiable id : new OTraverse().target(doc4).field("out_prev")) {
			resultList2.add(id);
		}
		// one document, transaction of database1 still not comitted, working with database2 via doc4
		Assert.assertEquals(resultList1.size(), 1);
	
		database1.commit();
	
		// now database1 transaction is commited, expecting 4 docs even when working with database2 via doc4
		List<OIdentifiable> resultList3 = new ArrayList<OIdentifiable>();
		for (OIdentifiable id : new OTraverse().target(doc4).field("out_prev")) {
			resultList3.add(id);
		}
		Assert.assertEquals(resultList3.size(), 4);
	
		database2.commit();
		
		// now everything is commited, expecting 4 docs when working with database2 via doc4
		List<OIdentifiable> resultList4 = new ArrayList<OIdentifiable>();
		for (OIdentifiable id : new OTraverse().target(doc4).field("out_prev")) {
			resultList4.add(id);
		}
		Assert.assertEquals(resultList4.size(), 4);
	}

**Comment by lvca** [comment] 2015-06-18 15:20
I think the problem is on setting the current database on thread local. Starting from 2.1-rc4 we introduced db.activateOnCurrentThread() api call to switch between database on the same thread. Could you try it?

**Comment by lvca** [comment] 2015-07-03 22:56
Closing because no answer. In case please reopen/comment this issue.

**Closed by lvca** 2015-07-03 22:56 UTC
Labels: waiting reply
