### ISSUE TITLE
[3.2.0] JS function invocation issues

### ISSUE THREAD

**Issue by MarttiR** [orientechnologies/orientdb#9596] opened 2021-04-29 19:51 UTC
### OrientDB Version: 3.2.0 (docker)

Errors are produced when executing custom JS functions that call documented "built-in" functions such as `orient.getDatabase()`.

Setting `script.polyglot.useGraal = false` does not make a difference.

--- 
### Errors

The following error is seen in Studio:

>Error on parsing script at position #0: Error on execution of the script
>Script: test
>------^
>
>org.graalvm.polyglot.PolyglotException: TypeError: invokeMember (getDatabase) on com.orientechnologies.orient.core.command.script.OScriptOrientWrapper@2db24b13 failed due to: Unknown identifier: getDatabase

Executing a similar function from a SQL batch script causes the same error:
> Error on parsing script at position #0: Error on execution of the script

... as well as this stack trace:
```
orientdb_1       | java.lang.IllegalArgumentException: object is not an instance of declaring class
orientdb_1       | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
orientdb_1       | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
orientdb_1       | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
orientdb_1       | 	at java.lang.reflect.Method.invoke(Method.java:498)
orientdb_1       | 	at com.orientechnologies.orient.core.command.script.OCommandExecutorUtility.transformResult(OCommandExecutorUtility.java:63)
orientdb_1       | 	at com.orientechnologies.orient.core.command.script.OCommandExecutorFunction.executeInContext(OCommandExecutorFunction.java:106)
orientdb_1       | 	at com.orientechnologies.orient.core.metadata.function.OFunction.executeInContext(OFunction.java:161)
orientdb_1       | 	at com.orientechnologies.orient.core.metadata.function.ODatabaseFunction.execute(ODatabaseFunction.java:46)
orientdb_1       | 	at com.orientechnologies.orient.core.sql.parser.OFunctionCall.execute(OFunctionCall.java:131)
orientdb_1       | 	at com.orientechnologies.orient.core.sql.parser.OFunctionCall.execute(OFunctionCall.java:82)
orientdb_1       | 	at com.orientechnologies.orient.core.sql.parser.OLevelZeroIdentifier.execute(OLevelZeroIdentifier.java:52)
orientdb_1       | 	at com.orientechnologies.orient.core.sql.parser.OBaseIdentifier.execute(OBaseIdentifier.java:62)
orientdb_1       | 	at com.orientechnologies.orient.core.sql.parser.OBaseExpression.execute(OBaseExpression.java:111)
orientdb_1       | 	at com.orientechnologies.orient.core.sql.parser.OExpression.execute(OExpression.java:102)
orientdb_1       | 	at com.orientechnologies.orient.core.sql.parser.OLetStatement.executeSimple(OLetStatement.java:29)
orientdb_1       | 	at com.orientechnologies.orient.core.sql.executor.OSingleOpExecutionPlan.executeInternal(OSingleOpExecutionPlan.java:95)
orientdb_1       | 	at com.orientechnologies.orient.core.sql.executor.ScriptLineStep.syncPull(ScriptLineStep.java:37)
orientdb_1       | 	at com.orientechnologies.orient.core.sql.executor.OScriptExecutionPlan.executeFull(OScriptExecutionPlan.java:208)
orientdb_1       | 	at com.orientechnologies.orient.core.sql.executor.ForEachStep.syncPull(ForEachStep.java:53)
orientdb_1       | 	at com.orientechnologies.orient.core.sql.executor.OSelectExecutionPlan.fetchNext(OSelectExecutionPlan.java:34)
orientdb_1       | 	at com.orientechnologies.orient.core.sql.executor.OUpdateExecutionPlan.executeInternal(OUpdateExecutionPlan.java:41)
orientdb_1       | 	at com.orientechnologies.orient.core.sql.executor.ScriptLineStep.syncPull(ScriptLineStep.java:33)
orientdb_1       | 	at com.orientechnologies.orient.core.sql.executor.OScriptExecutionPlan.executeFull(OScriptExecutionPlan.java:208)
orientdb_1       | 	at com.orientechnologies.orient.core.sql.parser.WhileStep.syncPull(WhileStep.java:45)
orientdb_1       | 	at com.orientechnologies.orient.core.sql.executor.OSelectExecutionPlan.fetchNext(OSelectExecutionPlan.java:34)
orientdb_1       | 	at com.orientechnologies.orient.core.sql.executor.OUpdateExecutionPlan.executeInternal(OUpdateExecutionPlan.java:41)
orientdb_1       | 	at com.orientechnologies.orient.core.sql.executor.ScriptLineStep.syncPull(ScriptLineStep.java:33)
orientdb_1       | 	at com.orientechnologies.orient.core.sql.executor.OScriptExecutionPlan.executeUntilReturn(OScriptExecutionPlan.java:180)
orientdb_1       | 	at com.orientechnologies.orient.core.sql.executor.OScriptExecutionPlan.doExecute(OScriptExecutionPlan.java:75)
orientdb_1       | 	at com.orientechnologies.orient.core.sql.executor.OScriptExecutionPlan.fetchNext(OScriptExecutionPlan.java:39)
orientdb_1       | 	at com.orientechnologies.orient.core.sql.parser.OLocalResultSet.fetchNext(OLocalResultSet.java:36)
orientdb_1       | 	at com.orientechnologies.orient.core.sql.parser.OLocalResultSet.<init>(OLocalResultSet.java:27)
orientdb_1       | 	at com.orientechnologies.orient.core.command.OSqlScriptExecutor.executeInternal(OSqlScriptExecutor.java:126)
orientdb_1       | 	at com.orientechnologies.orient.core.command.OSqlScriptExecutor.execute(OSqlScriptExecutor.java:65)
orientdb_1       | 	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.execute(ODatabaseDocumentEmbedded.java:786)
orientdb_1       | 	at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeQuery(OConnectionBinaryExecutor.java:1358)
orientdb_1       | 	at com.orientechnologies.orient.client.remote.message.OQueryRequest.execute(OQueryRequest.java:143)
orientdb_1       | 	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:355)
orientdb_1       | 	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:239)
orientdb_1       | 	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:67)
```

## Steps to reproduce  
Create a JS function containing the following line, and execute it.
```
var db = orient.getDatabase();
```

**Comment by luigidellaquila** [comment] 2021-04-30 07:51
Hi @MarttiR 

Thank you very much for reporting, I'll check it ASAP.

Thanks

Luigi

**Comment by lvca** [comment] 2021-04-30 16:14
Ok, in case of using GraalVM, that piece of code should be skipped because it's for Nashorn (legacy). Fixed.

**Comment by luigidellaquila** [comment] 2021-05-11 15:27
It seems it's not fixed yet. Tested on Java 8 and the problem is still there

**Comment by lvca** [comment] 2021-05-11 16:21
In case you have both engines (Nashorn and Graal), the user should decide which one to use with the setting `OGlobalConfiguration.SCRIPT_POLYGLOT_USE_GRAAL` to true or false.

**Comment by luigidellaquila** [comment] 2021-05-11 16:25
The problem is that the ScriptEngineManager is not aware of that setting. 
When you ask `scriptEngineManager.getEngineByName("javascript")`, it just picks from a hashset the first engine that supports js, and depending on the JVM version it could still be Graal (that is what happens on my side).

We can force the usage of nashorn with `scriptEngineManager.getEngineByName("nashorn")` in case SCRIPT_POLYGLOT_USE_GRAAL is set to false. 

I'm pushing a little fix for this, but it will probably need a review, because I still see some tests failing

**Comment by luigidellaquila** [comment] 2021-05-12 08:50
Here we go https://github.com/orientechnologies/orientdb/commit/376fda55aa65d6bbfe8331fc6ba59b85de2fa620

I tried disabling SCRIPT_POLYGLOT_USE_GRAAL, but some tests are failing.
Needs some further investigation

**Comment by KirubakaranSP** [comment] 2021-06-07 11:26
Is there any update on this ?

**Comment by lvca** [comment] 2021-06-15 05:35
@KirubakaranSP Yep, just pushed a fix. Now with SCRIPT_POLYGLOT_USE_GRAAL = false everything works. Note: Nashorn returns ClassNotFoundException instead of ScriptException in case the Java class cannot be accessed.

**Closed as completed by lvca** 2021-06-15 05:35 UTC
Labels: bug

**Comment by KirubakaranSP** [comment] 2021-06-15 13:42
Hi Luca,
  Can you please check this
<https://github.com/orientechnologies/orientdb/issues/9624> issue?As it is
very urgent,kindly update me on this.
Thanks and Regards
Kirubakaran S P

**Comment by janosmathe** [comment] 2021-08-04 23:13
@lvca > KirubakaranSP Yep, just pushed a fix. Now with SCRIPT_POLYGLOT_USE_GRAAL = false everything works. Note: Nashorn returns ClassNotFoundException instead of ScriptException in case the Java class cannot be accessed.

I am using 3.2.0 via Docker and I was trying to follow your recommendation, thus I naively added the following line to the 
orientdb-server-config.xml file:
`<entry value="false" name="OGlobalConfiguration.SCRIPT_POLYGLOT_USE_GRAAL"/>`

However, I get the warning message below:
`Ignored storage configuration because not supported: SCRIPT_POLYGLOT_USE_GRAAL=null [OClusterBasedStorageConfiguration]`

What I am doing wrong?
Also, do you know when the fix would be coming out?
