### ISSUE TITLE
OOM Exception on Fetching Records with the help of functions

### ISSUE THREAD

**Issue by NaveenAlapati** [orientechnologies/orientdb#8135] opened 2018-03-02 10:22 UTC
### OS: ubuntu

Basic Sample Query: Select *, price() as price from Books
Where price returns simply an integer or some value
## Expected behavior  
Fetch all the records from Books Class along with price column

## Actual behavior  
UnsuportedOperationException: Operation is not supported because may cause OOM Exception

## Steps to reproduce  
1. create a function that returns a value, could be string or integer or what ever
2. Execute select from Class query
3. Now add function as additional column to select query
Basic Sample Query: Select *, price() as price from Books
Basic Sample Function(javascript): price(){
return 5;
}

In my older version 2.2.17 all the functions are working fine. The issue is only with 2.2.32
@laa @lvca @luigidellaquila Please respond ASAP. thanks.

**Comment by luigidellaquila** [comment] 2018-03-02 10:33
Hi @NaveenAlapati 

I don't seem to be able to reproduce this problem with latest snapshot. I suspect it's due to something we already fixed (see commit bd1497125a8db05a74434ca4569f77730dd618e2) .

Are you running in distributed mode?

Thanks

Luigi

**Comment by NaveenAlapati** [comment] 2018-03-02 11:40
Sorry, thats my bad. 
Sample Query: Select expand(test2()) from Store
Sample function(Javascript): test2(){
var query = "Select * from Books skip 0 limit 10;
var db = orient.getDatabase();
var result = db.query(query);
return result;
}

At the moment we are running in Standard mode.

**Comment by luigidellaquila** [comment] 2018-03-02 11:43
Ok, testing it now

Thanks

Luigi

**Comment by luigidellaquila** [comment] 2018-03-02 12:03
Hi @NaveenAlapati 

I fixed the problem, the fix is already on 2.2.x branch and the snapshot will be available in a few minutes. It will be released with 2.2.33

Thanks

Luigi

**Closed by luigidellaquila** 2018-03-02 12:03 UTC

**Comment by NaveenAlapati** [comment] 2018-03-04 02:38
@luigidellaquila this is a crucial bug right, when can we expect 2.2.33?

**Comment by luigidellaquila** [comment] 2018-03-05 09:22
Hi @NaveenAlapati 

We are releasing it now, it should be out in a few hours

Thanks

Luigi

**Comment by luigidellaquila** [comment] 2018-03-05 15:31
Hi @NaveenAlapati 

OrientDB v 2.2.33 is already available on Maven repositories. In the next few hours also the binary distribution will be on the website

Thanks

Luigi
