### ISSUE TITLE
OrientDB 2.1 Migration - newlines in quoted SQL string

### ISSUE THREAD

**Issue by glennirwin** [orientechnologies/orientdb#4837] opened 2015-08-21 18:25 UTC
I am migrating to 2.1 and I noticed that the SQL parser gives me an error when I try to give it a data string (wrapped in quotes) with a newline or \r in it.  I am just trying to update the field that was inserted directly with Java API which accepted the data just fine with the newlines.  But when I update it using SQL, it doesn't accept it.

Exception in thread "Thread-8" com.orientechnologies.orient.core.sql.parser.TokenMgrError: Lexical error at line 1, column 68.  Encountered: "\r" (13), after : "\"/\* horizontal menu style */"
at com.orientechnologies.orient.core.sql.parser.OrientSqlTokenManager.getNextToken(OrientSqlTokenManager.java:3370)
at com.orientechnologies.orient.core.sql.parser.OrientSql.getToken(OrientSql.java:12758)
at com.orientechnologies.orient.core.sql.parser.OrientSql.Expression(OrientSql.java:4167)
at com.orientechnologies.orient.core.sql.parser.OrientSql.UpdateItem(OrientSql.java:2403)
at com.orientechnologies.orient.core.sql.parser.OrientSql.UpdateOperations(OrientSql.java:2220)
at com.orientechnologies.orient.core.sql.parser.OrientSql.UpdateStatement(OrientSql.java:2053)
at com.orientechnologies.orient.core.sql.parser.OrientSql.Statement(OrientSql.java:571)
at com.orientechnologies.orient.core.sql.parser.OrientSql.parse(OrientSql.java:79)

any advice as to what I can do?  Is there any way to encode a newline in a string in OrientDB SQL?

**Comment by luigidellaquila** [comment] 2015-09-21 06:02
Hi @glennirwin 

could you please provide a simple SQL statement to reproduce the problem?

Thanks

**Comment by cedricdv** [comment] 2016-01-09 01:02
I'm experiencing the same issue. I'm trying to insert in a string-property. I'm using pyOrient for this. The query is
```
insert into pastebin set UniqueID = 'sCtZv2fs',
paste = 'this is a test\r\n of a newline'
```

The response I get is
```
com.orientechnologies.orient.core.sql.parser.TokenMgrError - Lexical error at line 1, column 79.  Encountered: "\r" (13), after : "\'this is a test"
```

**Comment by luigidellaquila** [comment] 2016-05-24 13:33
Guys, this seems to work fine in both 2.1.16 and 2.2 GA, could you please confirm that it's already fixed?

Thanks

Luigi

**Comment by luigidellaquila** [comment] 2016-06-09 15:47
Hi guys, 

I'm closing this issue, please reopen if you still see any similar problems

Thanks

Luigi

**Comment by xvik** [comment] 2016-09-28 20:02
The issue appears in 2.2.10 (and all 2.2.x versions below).

For example, query:
```
insert into Sample set name = "\rbla"
```
Fails with error:
```
com.orientechnologies.orient.core.sql.parser.TokenMgrError: Lexical error at line 1, column 32.  Encountered: "\r" (13), after : "\""
```

Error appear when "\n" or "\r" used, but pass correctly for "\t".

**Comment by lvca** [comment] 2016-09-28 22:37
@luigidellaquila seems that @xvik was able to reproduce the issue. Reopened.

**Comment by AubryLegrand** [comment] 2016-10-06 09:20
Hi, i have the same issue with \r and \n into a string record.

**Comment by parimal-padture** [comment] 2017-01-18 04:59
+1

**Comment by igasparetto** [comment] 2017-02-06 17:45
+1
Same problem here.

**Comment by igasparetto** [comment] 2017-02-06 19:55
I noticed also that \s and \anything is causing trouble

**Comment by orientNewbie** [comment] 2017-03-01 14:20
I noticed it is causing problem wih \c as well. Version used is 2.2.15

**Comment by gpneuma** [comment] 2017-03-27 14:01
Hope this helps: I am running OrientDB v 2.2.16.

I do not encounter this problem when creating or updating records via the Studio Browse interface.

I also do not encounter this problem when creating or updating records with the Java client's `document`. For example, this does not throw an exception (I'm using Scala):

```scala
var document = db.query(new OSQLSynchQuery[ODocument]("SELECT FROM TestModel WHERE id=1")).head
document.field("name", "test\rname")
document.save
```

I do encounter the problem, however, when updating records with the Java client's `command`. For example:

```scala
val command = new OCommandSQL("UPDATE TestModel SET name='test\rname' where id=1")
val commandRequest: OCommandRequest = db.command(command)
commandRequest.execute()
```

The code above results in the same exception others are seeing:

```scala
Caused by: com.orientechnologies.orient.core.sql.parser.TokenMgrError: Lexical error at line 1, column 34.  Encountered: "\r" (13), after : "\'test"
        at com.orientechnologies.orient.core.sql.parser.OrientSqlTokenManager.getNextToken(OrientSqlTokenManager.java:6140)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_scan_token(OrientSql.java:26923)
        at com.orientechnologies.orient.core.sql.parser.OrientSql.jj_3R_289(OrientSql.java:24189)
...
```

**Comment by TropicalPenguin** [comment] 2017-04-16 08:34
Also encounter this with v 2.2.18, via pyorient and its 'CommandMessage', when attempting to execute a CREATE FUNCTION statement.

pyorient.exceptions.PyOrientCommandException: com.orientechnologies.orient.core.sql.parser.TokenMgrError - Lexical error at line 1, column 42.  Encountered: "\n" (10), after : "\'a = JSON.parse(a);"

**Comment by k-sok** [comment] 2017-08-01 19:36
For me it works when using `pyorient.ogm.property.PropertyEncoder`. Example:

`from pyorient.ogm.property import PropertyEncoder`
`sql = 'UPDATE {} SET prop={}'.format('#65:2', PropertyEncoder.encode_value('line1\nline2'))`
`graph.client.command(sql)`

**Comment by igasparetto** [comment] 2017-08-02 10:30
Would be great if you could test it also with Teleporter. I run into the problem because I was migrating the data from a MySQL DB. HTML content stored in TEXT columns were the ones causing most trouble here.
Thanks

**Comment by G4br13l3** [comment] 2017-08-02 11:12
Hi @igasparetto, 
did you encounter this issue using Teleporter with orientdb 2.1.x or 2.2.x?

Thanks,

Gabriele

**Comment by igasparetto** [comment] 2017-08-02 16:39
No, I haven't encountered this issue in Teleporter Gabriele. However, the issue happened when run a migration script I wrote myself. So I am just concerned that we might experience the same issue in Teleporter. Do you need some DB dump for testing?

**Closed** 2021-08-04 13:13 UTC
Labels: bug
