### ISSUE TITLE
ODB 'Frozen' Issue

### ISSUE THREAD

**Issue by rcramu** [orientechnologies/orientdb#6653] opened 2016-09-04 15:30 UTC
Hi,

Receiving below error after upgrading the version of OrientDB from 2.0.x to 2.1.16. Not immediately but after 30hours of update.

Sep 04, 2016 7:34:32 PM com.orientechnologies.common.log.OLogManager log
WARNING: DB is frozen will wait for 10000 ms. and then retry.
Sep 04, 2016 7:34:32 PM com.orientechnologies.common.log.OLogManager log
WARNING: DB is frozen will wait for 10000 ms. and then retry.
Sep 04, 2016 7:34:32 PM com.orientechnologies.common.log.OLogManager log
WARNING: DB is frozen will wait for 10000 ms. and then retry.
Sep 04, 2016 7:34:32 PM com.orientechnologies.common.log.OLogManager log
WARNING: DB is frozen will wait for 10000 ms. and then retry.
Sep 04, 2016 7:34:32 PM com.orientechnologies.common.log.OLogManager log
WARNING: DB is frozen will wait for 10000 ms. and then retry.
Sep 04, 2016 7:34:32 PM com.orientechnologies.common.log.OLogManager log
WARNING: DB is frozen will wait for 10000 ms. and then retry.
Sep 04, 2016 7:34:32 PM com.orientechnologies.common.log.OLogManager log
WARNING: DB is frozen will wait for 10000 ms. and then retry.
Sep 04, 2016 7:34:32 PM com.orientechnologies.common.log.OLogManager log
WARNING: DB is frozen will wait for 10000 ms. and then retry.
Sep 04, 2016 7:34:32 PM com.orientechnologies.common.log.OLogManager log
WARNING: DB is frozen will wait for 10000 ms. and then retry.
Sep 04, 2016 7:34:32 PM com.orientechnologies.common.log.OLogManager log
WARNING: DB is frozen will wait for 10000 ms. and then retry.
Sep 04, 2016 7:34:33 PM com.orientechnologies.common.log.OLogManager log
WARNING: DB is frozen will wait for 10000 ms. and then retry.
Sep 04, 2016 7:34:33 PM com.orientechnologies.common.log.OLogManager log
WARNING: DB is frozen will wait for 10000 ms. and then retry.
Sep 04, 2016 7:34:33 PM com.orientechnologies.common.log.OLogManager log
WARNING: DB is frozen will wait for 10000 ms. and then retry.
Sep 04, 2016 7:34:33 PM com.orientechnologies.common.log.OLogManager log
WARNING: DB is frozen will wait for 10000 ms. and then retry.
Sep 04, 2016 7:34:33 PM com.orientechnologies.common.log.OLogManager log
WARNING: DB is frozen will wait for 10000 ms. and then retry.
Sep 04, 2016 7:34:33 PM com.orientechnologies.common.log.OLogManager log
WARNING: DB is frozen will wait for 10000 ms. and then retry.
Sep 04, 2016 7:34:33 PM com.orientechnologies.common.log.OLogManager log
WARNING: DB is frozen will wait for 10000 ms. and then retry.
Sep 04, 2016 7:34:33 PM com.orientechnologies.common.log.OLogManager log
WARNING: DB is frozen will wait for 10000 ms. and then retry.
Sep 04, 2016 7:34:34 PM com.orientechnologies.common.log.OLogManager log
WARNING: DB is frozen will wait for 10000 ms. and then retry.
Sep 04, 2016 7:34:34 PM com.orientechnologies.common.log.OLogManager log
WARNING: DB is frozen will wait for 10000 ms. and then retry.
Sep 04, 2016 7:34:34 PM com.orientechnologies.common.log.OLogManager log
WARNING: DB is frozen will wait for 10000 ms. and then retry.

**Comment by rcramu** [comment] 2016-09-04 15:32
Would like to add:
This is the first time we receive this issue in our staging environment.
We have similar setup available in QA & Performance Engineering envs.

**Comment by laa** [comment] 2016-09-05 06:45
Hi, it means that you made a backup of a system but for some reasons, database release was not performed. Could you call ```release database``` on this database to fix the issue?

**Comment by rcramu** [comment] 2016-09-05 07:56
Thanks, Laa.  Would check on this & update this thread shortly.

**Comment by rcramu** [comment] 2016-09-05 08:10
Hi, Team has used 'release database' last night & the issue raised again now. Can we have a webex on this issue  immediately...? It is too critical for us, as the Stakeholders are performing UAT in staging environment.

**Comment by rcramu** [comment] 2016-09-05 08:11
Please join the webex at: ciscosales.webex.com/meet/rchencha

**Comment by rcramu** [comment] 2016-09-05 08:25
Hi Team,
Anybody joining the call?, we are waiting on the bridge.

**Comment by rcramu** [comment] 2016-09-05 08:34
Hi There, Is there any update on this?? Anybody joining the call?

**Comment by laa** [comment] 2016-09-05 08:41
Hi @rcramu, sorry missed your message. But call will not help to solve the issue.  I may join the call but there is no additional information to discuss.  At this stage, we do not know a reason why it happens. Could you send us a log of your server and thread dump of a server? We will analyse it and in couple of hours will send you solution or will request additional information​.

**Comment by rcramu** [comment] 2016-09-05 08:48
Hi Laa, This is exactly why I am asking to join the call. We keep moving the timeline without any success; When you join the call, you can in fact can go through all info you need, we will allow you to get into the system through webex. Please join. With team's past experience - sharing logs & waiting for your team's response did not work well.

Also, I have hardly very short time to get the RCA & fix for this very critical issue.
Please join, we are still in bridge.

**Comment by rcramu** [comment] 2016-09-05 10:21
Hi Team,
Thanks for joining the webex call.

Here is the error log as requested:

com.orientechnologies.common.io.OIOException: Found unknown session

Error executing requestcom.orientechnologies.common.io.OIOException: Found unknown session 199857at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.onBeforeRequest(ONetworkProtocolBinary.java:240)at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:214)


com.orientechnologies.common.io.OIOException: Found unknown session 199857
at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.onBeforeRequest(ONetworkProtocolBinary.java:240)
at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:214)
at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Error executing request
com.orientechnologies.common.io.OIOException: Found unknown session 199858
at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.onBeforeRequest(ONetworkProtocolBinary.java:240)
at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:214)
at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Error executing request
com.orientechnologies.common.io.OIOException: Found unknown session 199859
at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.onBeforeRequest(ONetworkProtocolBinary.java:240)
at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:214)
at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Error executing request
com.orientechnologies.common.io.OIOException: Found unknown session 199860
at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.onBeforeRequest(ONetworkProtocolBinary.java:240)
at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:214)
at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Error executing request
com.orientechnologies.common.io.OIOException: Found unknown session 199861
at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.onBeforeRequest(ONetworkProtocolBinary.java:240)
at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:214)
at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Error executing request
com.orientechnologies.common.io.OIOException: Found unknown session 199862
at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.onBeforeRequest(ONetworkProtocolBinary.java:240)
at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:214)
at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Error executing request

and the above set repeats....

**Comment by rcramu** [comment] 2016-09-05 10:25
MoM (in webex call):
1.  Support member Verified the ODB backup script.
2.  Support member Verified the recent backup log - no errors found
3.  Performed 'relaase database' and successfully executed (checked the server log)
4.  L2 team  restarted the ODB (as suggested by support member) & restarted the auth components (CK) as the DB has been restarted

Next Step:
The ODB support team would analyse the above log & update us on the critical issue

**Comment by laa** [comment] 2016-09-05 11:07
Hi @tglman could you take a look ?

**Comment by rcramu** [comment] 2016-09-06 10:13
Hi Team, 
Any update on this?

**Comment by tglman** [comment] 2016-09-06 10:27
hi @rcramu,

Yes i ran a few test with the lvm backup, but i couldn't reproduce this issue.

I'm going to run some tests with the server under load, i'll let you know as soon as i've some results.

Regards

**Comment by rcramu** [comment] 2016-09-06 10:30
Hi, Thanks for prompt response.

Sure, please keep us posted, as it holds back our delivery pipeline to Production.

**Comment by tglman** [comment] 2016-09-06 13:37
Hi @rcramu,

so far i could not reproduce the issue with a working backup, in any case if the backup fail (for example creating the lvm snapshot), it could leave the database in frozen state, do you have the log of the backup.sh execution ?

Thanks

**Comment by laa** [comment] 2016-09-06 13:58
Hi, @rcramu , could you send us logs of backs since the moment DB was frozen, did you execute single backup or several backups during this period of time ?

**Comment by rcramu** [comment] 2016-09-06 17:54
Hi, we execute single backup at any given time.(once in a day)

**Comment by tglman** [comment] 2016-09-07 12:41
Hi @rcamu,

Let me explain in details, as soon as the backup script run, it freeze the database, create a lvm snapshot, and release the database, all freeze and release operation are logged in the `orientdb-server.log`. The only thing that can happne that leave database frozen is a failure to create a lvm snaptshot, or a failure to connect to the server after the lvm snapshot is done, both of this error should be logged by the backup script. even if a different error happen server side in case of release, that should be logged in both the `orientdb-server.log` and by the backup script.

So far the only logs that we have are the `Found unknown session ` that is quite unluckely to be the source of the problem and in any case eny connection problem is reported by the backup script.

If you are running the backup script by a scheduler tool like cron, please double check that it run with the right permission for create the lvm snapshots.

Hope this help to find out the root fo the problmen.

Kind Regards

**Comment by tglman** [comment] 2016-11-17 14:00
Hi @rcramu,

Do you have news on this issue? did you try lastest hotfix? do you still have problems ?

**Comment by tglman** [comment] 2016-12-27 15:12
hi @rcramu,

We fixed some related issue in 2.2.x so this should not occur anymore, i'm going to close this issue, please reopen if you still have problem.

Regards

**Closed by tglman** 2016-12-27 15:12 UTC
Labels: bug, waiting reply
