### ISSUE TITLE
java.lang.NullPointerException at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.deserializeFromDirectMemory(ODurablePage.java:164)

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#7074] opened 2017-01-12 15:34 UTC
## OrientDB Version, operating system, or hardware.
- v2.2.14

## Operating System
- [X ] Linux

java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b15, mixed mode)

## Expected behavior and actual behavior

```
2017-01-12 15:17:07 t.c.s.a.c.e.AbstractEWSExchangeLink [ERROR] failed to create item

Caused by: java.lang.NullPointerException: null
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.deserializeFromDirectMemory(ODurablePage.java:164)
        at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiBucket.getEntry(OSBTreeBonsaiBucket.java:280)
        at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.findBucket(OSBTreeBonsaiLocal.java:1359)
        at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.loadEntriesMajor(OSBTreeBonsaiLocal.java:774)
        at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.getRealBagSize(OSBTreeBonsaiLocal.java:1462)
        at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag.updateSize(OSBTreeRidBag.java:1029)
        at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag.size(OSBTreeRidBag.java:748)
        at com.orientechnologies.orient.core.db.record.ridbag.ORidBag.size(ORidBag.java:191)
        at com.tinkerpop.blueprints.impls.orient.OrientVertex.getEdges(OrientVertex.java:840)
        at com.tinkerpop.blueprints.impls.orient.OrientVertex.getEdges(OrientVertex.java:768)
        at com.tinkerpop.blueprints.util.DefaultVertexQuery$DefaultVertexQueryIterable.<init>(DefaultVertexQuery.java:110)
        at com.tinkerpop.blueprints.util.DefaultVertexQuery.edges(DefaultVertexQuery.java:80)
        at com.tinkerpop.pipes.transform.VertexQueryPipe.processNextStart(VertexQueryPipe.java:113)
        at com.tinkerpop.pipes.transform.VertexQueryPipe.processNextStart(VertexQueryPipe.java:19)
        at com.tinkerpop.pipes.AbstractPipe.hasNext(AbstractPipe.java:98)
        at com.tinkerpop.pipes.transform.OrderPipe.processNextStart(OrderPipe.java:86)
        at com.tinkerpop.pipes.AbstractPipe.next(AbstractPipe.java:89)
        at com.tinkerpop.pipes.filter.FilterFunctionPipe.processNextStart(FilterFunctionPipe.java:23)
        at com.tinkerpop.pipes.AbstractPipe.hasNext(AbstractPipe.java:98)
        at com.tinkerpop.pipes.util.Pipeline.hasNext(Pipeline.java:105)
        at 
```

Here are startup options

```
export CATALINA_OPTS="-Dversion=enterpriseedition -Xmx6g -Xms256m -XX:MaxDirectMemorySize=512g -Dgraphdb.cache.size=64 -Dstorage.diskCache.bufferSize=409
6 -Xloggc:/var/log/gc-$(date +%Y_%m_%d-%H_%M).log -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=5 -XX:GCLogFileSize=1G -XX:+PrintGCDetails -XX:+PrintG
CTimeStamps -XX:+PrintGCDateStamps -XX:+PrintTenuringDistribution -XX:+PrintGCApplicationStoppedTime -XX:HeapDumpPath=/mnt/archive-four/java_pid%p.hprof 
-XX:+HeapDumpOnOutOfMemoryError"
```

Note: -XX:MaxDirectMemorySize=512g

```
>get -i *
#mbean = java.nio:type=BufferPool,name=direct:
Name = direct; (Name)

Count = 431; (Count)

TotalCapacity = 5275964398; (TotalCapacity)

MemoryUsed = 5275964398; (MemoryUsed)

ObjectName = java.nio:type=BufferPool,name=direct; (ObjectName)

$>bean java.lang:type=Memory
#bean is set to java.lang:type=Memory
$>get -i *
#mbean = java.lang:type=Memory:
Verbose = true; (Verbose)
#mbean = java.lang:type=Memory:
HeapMemoryUsage = { 
  committed = 5974261760; (committed)
  init = 268435456; (init)
  max = 5974261760; (max)
  used = 2898740464; (used)
 }; (HeapMemoryUsage)
NonHeapMemoryUsage = { 
  committed = 323182592; (committed)
  init = 2555904; (init)
  max = -1; (max)
  used = 313671344; (used)
 }; (NonHeapMemoryUsage)
ObjectPendingFinalizationCount = 0; (ObjectPendingFinalizationCount)
ObjectName = java.lang:type=Memory; (ObjectName)
$>bean com.orientechnologies.common.directmemory:type=OByteBufferPoolMXBean
#bean is set to com.orientechnologies.common.directmemory:type=OByteBufferPoolMXBean
$>get -i *
#mbean = com.orientechnologies.common.directmemory:type=OByteBufferPoolMXBean:
OverflowBufferCount = 0; (OverflowBufferCount)
AllocatedMemory = 4294967296; (AllocatedMemory)
BufferSize = 65536; (BufferSize)
AllocatedBufferCount = 55772; (AllocatedBufferCount)
AllocatedMemoryInGB = 4.0; (AllocatedMemoryInGB)
BuffersInThePool = 67; (BuffersInThePool)
AllocatedMemoryInMB = 4096; (AllocatedMemoryInMB)
$>bean java.nio:name=mapped,type=BufferPool
#bean is set to java.nio:name=mapped,type=BufferPool
$>get -i *
#mbean = java.nio:name=mapped,type=BufferPool:
Name = mapped; (Name)
Count = 2058; (Count)
TotalCapacity = 97291919684; (TotalCapacity)
MemoryUsed = 97291919684; (MemoryUsed)
ObjectName = java.nio:type=BufferPool,name=mapped; (ObjectName)
```

**Comment by laa** [comment] 2017-01-13 13:37
Duplicate of https://github.com/orientechnologies/orientdb/issues/7053

**Closed by laa** 2017-01-13 13:37 UTC
Labels: bug, storage team
