### ISSUE TITLE
Exception when deploying 2 client in same container

### ISSUE THREAD

**Issue by prm2612** [orientechnologies/orientdb#4954] opened 2015-09-11 00:56 UTC
Hi,
We have 2 apps running under same container which are accessing Orient DB. When we have both the apps running and we redeploy one of the apps, we get following exception:

javax.management.InstanceNotFoundException: com.orientechnologies.orient.core.storage.cache.local:type=O2QCacheMXBean
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean(DefaultMBeanServerInterceptor.java:1095) ~[?:1.7.0_60]
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.exclusiveUnregisterMBean(DefaultMBeanServerInterceptor.java:427) ~[?:1.7.0_60]
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.unregisterMBean(DefaultMBeanServerInterceptor.java:415) ~[?:1.7.0_60]
        at com.sun.jmx.mbeanserver.JmxMBeanServer.unregisterMBean(JmxMBeanServer.java:546) ~[?:1.7.0_60]
        at au.com.foxsports.subscription.utils.GraphConnectionPool.destroy(GraphConnectionPool.java:105) [subscription-service-api-1.0.0-SNAPSHOT.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_60]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_60]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_60]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_60]
        at org.springframework.beans.factory.support.DisposableBeanAdapter.invokeCustomDestroyMethod(DisposableBeanAdapter.java:328) [spring-beans-3.2.10.RELEASE.jar:3.2.10.RELEASE]
        at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:254) [spring-beans-3.2.10.RELEASE.jar:3.2.10.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:510) [spring-beans-3.2.10.RELEASE.jar:3.2.10.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:486) [spring-beans-3.2.10.RELEASE.jar:3.2.10.RELEASE]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:747) [spring-beans-3.2.10.RELEASE.jar:3.2.10.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:455) [spring-beans-3.2.10.RELEASE.jar:3.2.10.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1090) [spring-context-3.2.10.RELEASE.jar:3.2.10.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1064) [spring-context-3.2.10.RELEASE.jar:3.2.10.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:1010) [spring-context-3.2.10.RELEASE.jar:3.2.10.RELEASE]
        at org.mule.config.spring.SpringRegistry.doDispose(SpringRegistry.java:105) [mule-module-spring-config-3.6.1.jar:3.6.1]
        at org.mule.config.spring.SpringRegistryLifecycleManager$SpringContextDisposePhase.applyLifecycle(SpringRegistryLifecycleManager.java:91) [mule-module-spring-config-3.6.1.jar:3.6.1]
        at org.mule.lifecycle.RegistryLifecycleManager$RegistryLifecycleCallback.onTransition(RegistryLifecycleManager.java:241) [mule-core-3.6.1.jar:3.6.1]
        at org.mule.lifecycle.RegistryLifecycleManager.invokePhase(RegistryLifecycleManager.java:152) [mule-core-3.6.1.jar:3.6.1]
        at org.mule.lifecycle.RegistryLifecycleManager.fireLifecycle(RegistryLifecycleManager.java:123) [mule-core-3.6.1.jar:3.6.1]
        at org.mule.registry.AbstractRegistry.dispose(AbstractRegistry.java:69) [mule-core-3.6.1.jar:3.6.1]
        at org.mule.registry.AbstractRegistryBroker$2.onTransition(AbstractRegistryBroker.java:58) [mule-core-3.6.1.jar:3.6.1]
        at org.mule.registry.AbstractRegistryBroker$2.onTransition(AbstractRegistryBroker.java:53) [mule-core-3.6.1.jar:3.6.1]
        at org.mule.lifecycle.RegistryLifecycleManager.invokePhase(RegistryLifecycleManager.java:152) [mule-core-3.6.1.jar:3.6.1]
        at org.mule.lifecycle.RegistryBrokerLifecycleManager.fireDisposePhase(RegistryBrokerLifecycleManager.java:78) [mule-core-3.6.1.jar:3.6.1]
        at org.mule.registry.AbstractRegistryBroker.dispose(AbstractRegistryBroker.java:52) [mule-core-3.6.1.jar:3.6.1]
        at org.mule.registry.MuleRegistryHelper.fireLifecycle(MuleRegistryHelper.java:132) [mule-core-3.6.1.jar:3.6.1]
        at org.mule.lifecycle.MuleContextLifecycleManager$MuleContextLifecycleCallback.onTransition(MuleContextLifecycleManager.java:91) [mule-core-3.6.1.jar:3.6.1]
        at org.mule.lifecycle.MuleContextLifecycleManager$MuleContextLifecycleCallback.onTransition(MuleContextLifecycleManager.java:87) [mule-core-3.6.1.jar:3.6.1]
        at org.mule.lifecycle.MuleContextLifecycleManager.invokePhase(MuleContextLifecycleManager.java:69) [mule-core-3.6.1.jar:3.6.1]
        at org.mule.lifecycle.MuleContextLifecycleManager.fireLifecycle(MuleContextLifecycleManager.java:61) [mule-core-3.6.1.jar:3.6.1]
        at org.mule.DefaultMuleContext.dispose(DefaultMuleContext.java:329) [mule-core-3.6.1.jar:3.6.1]
        at org.mule.module.launcher.application.DefaultMuleApplication.doDispose(DefaultMuleApplication.java:404) [mule-module-launcher-3.6.1.jar:3.6.1]
        at org.mule.module.launcher.application.DefaultMuleApplication.dispose(DefaultMuleApplication.java:287) [mule-module-launcher-3.6.1.jar:3.6.1]
        at org.mule.module.launcher.artifact.ArtifactWrapper$1.execute(ArtifactWrapper.java:39) [mule-module-launcher-3.6.1.jar:3.6.1]
        at org.mule.module.launcher.artifact.ArtifactWrapper.executeWithinArtifactClassLoader(ArtifactWrapper.java:129) [mule-module-launcher-3.6.1.jar:3.6.1]
        at org.mule.module.launcher.artifact.ArtifactWrapper.dispose(ArtifactWrapper.java:34) [mule-module-launcher-3.6.1.jar:3.6.1]
        at org.mule.module.launcher.DefaultArtifactDeployer.tryToDisposeArtifact(DefaultArtifactDeployer.java:65) [mule-module-launcher-3.6.1.jar:3.6.1]
        at org.mule.module.launcher.DefaultArtifactDeployer.undeploy(DefaultArtifactDeployer.java:47) [mule-module-launcher-3.6.1.jar:3.6.1]
        at org.mule.module.launcher.DefaultArchiveDeployer.guardedUndeploy(DefaultArchiveDeployer.java:475) [mule-module-launcher-3.6.1.jar:3.6.1]
        at org.mule.module.launcher.DefaultArchiveDeployer.undeploy(DefaultArchiveDeployer.java:417) [mule-module-launcher-3.6.1.jar:3.6.1]
        at org.mule.module.launcher.DefaultArchiveDeployer.undeployArtifact(DefaultArchiveDeployer.java:120) [mule-module-launcher-3.6.1.jar:3.6.1]
        at org.mule.module.launcher.MuleDeploymentService.undeploy(MuleDeploymentService.java:186) [mule-module-launcher-3.6.1.jar:3.6.1]
        at com.mulesoft.mmc.agent.service.impl.ApplicationServiceImpl.undeploy(ApplicationServiceImpl.java:398) [mmc-agent-impl-3.6.1.jar:3.6.1]
        at com.mulesoft.mmc.agent.service.impl.ApplicationServiceImpl.deploy(ApplicationServiceImpl.java:291) [mmc-agent-impl-3.6.1.jar:3.6.1]
        at sun.reflect.GeneratedMethodAccessor137.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_60]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_60]
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317) [spring-aop-3.2.10.RELEASE.jar:3.2.10.RELEASE]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:198) [spring-aop-3.2.10.RELEASE.jar:3.2.10.RELEASE]
        at com.sun.proxy.$Proxy41.deploy(Unknown Source) [?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_60]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_60]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_60]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_60]
        at org.springframework.remoting.support.RemoteInvocation.invoke(RemoteInvocation.java:205) [spring-context-3.2.10.RELEASE.jar:3.2.10.RELEASE]
        at com.mulesoft.common.remoting.RemoteInvocationDecorator.invoke(RemoteInvocationDecorator.java:107) [spring-remoting-stream-support-1.0.6.jar:?]
        at org.springframework.remoting.support.DefaultRemoteInvocationExecutor.invoke(DefaultRemoteInvocationExecutor.java:38) [spring-context-3.2.10.RELEASE.jar:3.2.10.RELEASE]
        at org.springframework.remoting.support.RemoteInvocationBasedExporter.invoke(RemoteInvocationBasedExporter.java:78) [spring-context-3.2.10.RELEASE.jar:3.2.10.RELEASE]
        at com.mulesoft.common.remoting.StreamSupportingHttpInvokerServiceExporter.invokeAndCreateResult(StreamSupportingHttpInvokerServiceExporter.java:122) [spring-remoting-stream-support-1.0.6.jar:?]
        at org.springframework.remoting.httpinvoker.HttpInvokerServiceExporter.handleRequest(HttpInvokerServiceExporter.java:73) [spring-web-3.2.10.RELEASE.jar:3.2.10.RELEASE]
        at com.mulesoft.mmc.agent.remoting.HttpInvokerServiceExporter.handleRequest(HttpInvokerServiceExporter.java:50) [mmc-agent-impl-3.6.1.jar:3.6.1]
        at org.springframework.web.servlet.mvc.HttpRequestHandlerAdapter.handle(HttpRequestHandlerAdapter.java:49) [spring-webmvc-3.2.10.RELEASE.jar:3.2.10.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:919) [spring-webmvc-3.2.10.RELEASE.jar:3.2.10.RELEASE]
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:851) [spring-webmvc-3.2.10.RELEASE.jar:3.2.10.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:953) [spring-webmvc-3.2.10.RELEASE.jar:3.2.10.RELEASE]
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:855) [spring-webmvc-3.2.10.RELEASE.jar:3.2.10.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:595) [geronimo-servlet_3.0_spec-1.0.jar:1.0]
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:829) [spring-webmvc-3.2.10.RELEASE.jar:3.2.10.RELEASE]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:668) [geronimo-servlet_3.0_spec-1.0.jar:1.0]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:696) [jetty-servlet-9.0.7.v20131107.jar:9.0.7.v20131107]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1515) [jetty-servlet-9.0.7.v20131107.jar:9.0.7.v20131107]
        at com.mulesoft.mmc.agent.web.ConsoleClientCertFilter.doFilter(ConsoleClientCertFilter.java:138) [mmc-agent-impl-3.6.1.jar:3.6.1]
        at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1495) [jetty-servlet-9.0.7.v20131107.jar:9.0.7.v20131107]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:519) [jetty-servlet-9.0.7.v20131107.jar:9.0.7.v20131107]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138) [jetty-server-9.0.7.v20131107.jar:9.0.7.v20131107]
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:564) [jetty-security-9.0.7.v20131107.jar:9.0.7.v20131107]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:213) [jetty-server-9.0.7.v20131107.jar:9.0.7.v20131107]
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1097) [jetty-server-9.0.7.v20131107.jar:9.0.7.v20131107]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:448) [jetty-servlet-9.0.7.v20131107.jar:9.0.7.v20131107]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:175) [jetty-server-9.0.7.v20131107.jar:9.0.7.v20131107]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1031) [jetty-server-9.0.7.v20131107.jar:9.0.7.v20131107]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136) [jetty-server-9.0.7.v20131107.jar:9.0.7.v20131107]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [jetty-server-9.0.7.v20131107.jar:9.0.7.v20131107]
        at org.eclipse.jetty.server.Server.handle(Server.java:446) [jetty-server-9.0.7.v20131107.jar:9.0.7.v20131107]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:271) [jetty-server-9.0.7.v20131107.jar:9.0.7.v20131107]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:246) [jetty-server-9.0.7.v20131107.jar:9.0.7.v20131107]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.run(AbstractConnection.java:358) [jetty-io-9.0.7.v20131107.jar:9.0.7.v20131107]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601) [jetty-util-9.0.7.v20131107.jar:9.0.7.v20131107]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532) [jetty-util-9.0.7.v20131107.jar:9.0.7.v20131107]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_60]

**Comment by ucappellini** [comment] 2015-09-11 01:05
We took the issue in charge and we are working on it. We will provide a feedback soon.

**Comment by valeriotarenghi** [comment] 2015-09-14 10:41
The Problem is related to the fact that both instances of OrientDB want to deregister single JMX bean. Users shutdown Orient engine when only first app stops to working but second application still is working. They need to call shutdown only when both applications are stopped. JMX bean of read cache is unregistered when cache is destroyed, cache is shared between all storages.

**Comment by prm2612** [comment] 2015-09-15 00:59
Thanks valeriotarenghi, so what is the solution to this? We have 2 apps for interacting with Orient DB: Subscriber and Notification. Subscriber app is what clients use to subscribe to events. Notification app finds out subscribers for an event and sends them the notification. Being 2 separate apps, we can't call shutdown when both apps are stopped. Both the apps follow different release cycle. At any point of time either 1 or both apps can be deployed.

**Comment by valeriotarenghi** [comment] 2015-09-16 04:18
Hi,
As a solution you may want to avoid this deployment scenario.
We reccomend to avoid deploying more webapps on a single servlet container.

**Comment by valeriotarenghi** [comment] 2015-09-16 04:18
I ask her to represent the application design and
distribution in as much detail as possible to enable us to find a
best solution. Thanks

**Comment by luigidellaquila** [comment] 2015-09-17 10:22
Hi @prm2612 

In the stack trace I see that the exception comes from 
```
au.com.foxsports.subscription.utils.GraphConnectionPool.destroy(GraphConnectionPool.java:105)
```

Does this class extend and OrientDB class? Is it possible to take a look at your code?

Thanks

Luigi

**Comment by prm2612** [comment] 2015-09-21 00:02
Hi Luigi,

Following is the code you are after. We invoke the destroy method through spring while deregistering:

{code}
public class GraphConnectionPool {
	private static final Logger logger = LoggerFactory
			.getLogger(GraphConnectionPool.class);

	static {
		OGlobalConfiguration.RID_BAG_EMBEDDED_TO_SBTREEBONSAI_THRESHOLD.setValue(-1);
	}

	private String connectionUrl;
	private int minConnection = 1;
	private int maxConnection = 30;
	private OrientGraphFactory orientGraphFactory;
	private FramedGraphFactory framedGraphFactory;

	private AtomicBoolean logConnection = new AtomicBoolean(true);
	private int poolPrintIntervalMillis = 1000 * 60 * 2;
	private ExecutorService executorService;

	public OrientGraphFactory constructPool() {


		return orientGraphFactory;
	}

	public void init() {
		logger.info("************************************INIT GRAPH CONNECTION[{}] {} {}***************************************************",connectionUrl, minConnection, maxConnection);
		executorService = Executors.newSingleThreadExecutor();
//		try {
//			final MBeanServer server = ManagementFactory.getPlatformMBeanServer();
//			final ObjectName mbeanName;
//
//			mbeanName = new ObjectName(O2QCache.MBEAN_NAME);
//			server.unregisterMBean(mbeanName);
//		} catch (Exception e) {
//			logger.warn("Exception: " + e);
//		}



		orientGraphFactory = new OrientGraphFactory(connectionUrl).setupPool(minConnection, maxConnection);

		framedGraphFactory = new FramedGraphFactory(

				new TypedGraphModuleBuilder()
						.withClass(Device.class)
						.withClass(User.class)
						.withClass(Root.class)
						.withClass(Event.class)
						.build(), new GremlinGroovyModule(), new JavaHandlerModule()

		);

		new Thread(new Runnable() {
			@Override
			public void run() {
				while (logConnection.get()) {
					final boolean testResult = testConnection();
					logger.info("[event:CONNECTION_STAT] [created:{}] [free:{}] [testResult:{}]", orientGraphFactory.getCreatedInstancesInPool() ,
							orientGraphFactory.getAvailableInstancesInPool(), testResult);
					try {

						Thread.sleep(poolPrintIntervalMillis);
					} catch (InterruptedException e) {
						e.printStackTrace();
					}
				}
			}
		},"GraphConnectionLogger").start();

	}

	public void destroy() {
		logConnection.set(false);
		orientGraphFactory.close();
//
//		try {
//			final MBeanServer server = ManagementFactory.getPlatformMBeanServer();
//			final ObjectName mbeanName;
//
//			mbeanName = new ObjectName(O2QCache.MBEAN_NAME);
//			server.unregisterMBean(mbeanName);
//		} catch (Exception e) {
//			logger.warn("Exception",e);
//		}

	}
	
	
    public  FramedGraphFactory framedGraph() {
		return framedGraphFactory;
    }
	
	
	public String getConnectionUrl() {
		return connectionUrl;
	}
	public void setConnectionUrl(String connectionUrl) {
		this.connectionUrl = connectionUrl;
	}
	public int getMinConnection() {
		return minConnection;
	}
	public void setMinConnection(int minConnection) {
		this.minConnection = minConnection;
	}
	public int getMaxConnection() {
		return maxConnection;
	}
	public void setMaxConnection(int maxConnection) {
		this.maxConnection = maxConnection;
	}
	
	
	public void setLogConnection(boolean logConnection1) {
		this.logConnection.set(logConnection1);
	}

	public void setPoolPrintIntervalMillis(int poolPrintIntervalMillis) {
		this.poolPrintIntervalMillis = poolPrintIntervalMillis;
	}



	public boolean testConnection() {

		Callable<Boolean> r = new Callable<Boolean>() {
			@Override
			public Boolean call() {
				final OrientGraphNoTx noTx = orientGraphFactory.getNoTx();

				try {
					final long usercount = noTx.getRawGraph().countClass("User");
					logger.debug("[event:TEST_CONNECTION] [USER_COUNT:{}]",usercount );
					return true;
				}  catch (Exception e) {
					logger.error("ERROR TRYING TO ACCESS GRAPH ", e);
					return false;
				}
				finally {
					noTx.shutdown();
				}
			}
		};

		final Future<Boolean> submit = executorService.submit(r);

		try {
			final Boolean success = submit.get(1000 * 50, TimeUnit.MILLISECONDS);
			return success;
		}catch (Exception e) {
			logger.error("ERROR TRYING TO GET COUNT: ", e);
			return false;
		}
	}


}
{code}

**Comment by luigidellaquila** [comment] 2015-09-21 08:28
Hi @prm2612 

so you are manually unregistering O2QCache.MBEAN_NAME MBean (actually now the code is commented).
I'll double check it, but probably there is no need to do this

Thanks

Luigi

**Comment by prm2612** [comment] 2015-09-24 00:57
Hi Luigi,

Ya we commented out this part of code as we have 2 apps sharing the sample platform MBean. If you have just 1 app then it will work but the problem happens if we have 2 apps.

Thanks
Prashant

**Comment by laa** [comment] 2015-09-24 07:57
I will take it, it is pretty dangerous case because probably it means that you start 2 engine instances at the same time.

**Comment by prm2612** [comment] 2015-09-25 00:50
@laa Just FYI, we are connecting to a remote DB not anything local standalone. Are you saying 2 clients on same JVM cannot connect to a remote DB?

**Comment by laa** [comment] 2015-09-25 13:54
Sure, it is possible , I merely do not understand why it leads to behaviour when you start Orient engine twice.

**Comment by laa** [comment] 2015-10-19 12:39
Hi, sorry for delay. I am back there from liven incremental backup change.
Could you do me favor. Could you explain in more details why you manually deregister 2Q_CACHE bean ?

**Comment by laa** [comment] 2015-10-19 12:39
Hi, sorry for delay. I am back there from liven incremental backup change.
Could you do me favor. Could you explain in more details why you manually deregister 2Q_CACHE bean ?

**Comment by prm2612** [comment] 2015-10-21 00:37
@laa We aren't deregistering it now. That part of code is commented out. We added that code to see if it helps us with the exception but it doesn't.

**Comment by laa** [comment] 2015-10-28 17:15
Hi, OK.
Could you add then logging inside of com.orientechnologies.orient.core.storage.cache.local.O2QCache#registerMBean method. 

Such one which will print stacktrace.
I mean something like this:
new Trhrowable().printStackTrace();

and send result of this logging to me.

**Comment by prm2612** [comment] 2015-10-29 05:50
Hi @laa, what do you mean? com.orientechnologies.orient.core.storage.cache.local.O2QCache is an Orient class. How can I add in statement there? Do you mean to say add any command line argument to get this stacktrace? Also isn't the stacktrace at the top of issue of any use to you?

**Comment by laa** [comment] 2015-11-05 14:40
Hi @prm2612 , I do not see in stack trace any code from OrientDB project, I mean all classes not from package "com.orientechnologies" with exception of bean name itself. That is why I have reasonable question which I try to resolve, how this current exception related to behaviour of bean managament inside of OrientDB code.

**Comment by laa** [comment] 2015-11-27 12:07
Closing because of no answer

**Closed by laa** 2015-11-27 12:07 UTC
Labels: bug, waiting reply
