### ISSUE TITLE
Orient client blocked

### ISSUE THREAD

**Issue by sajid2045** [orientechnologies/orientdb#4936] opened 2015-09-09 00:51 UTC
Please find the stacktrace :

https://dl.dropboxusercontent.com/u/5968302/orient_not_responding.txt

The threads 'get test' is blocked forever trying to load a vertex! 
NOTE: this happened after the client been idle for 10+ hours and then we try to access the db. Please comment if this is supposed to be fixed with 2.1.2. 

"get test" daemon prio=10 tid=0x00007f1d14835000 nid=0x4974 waiting on condition [0x00007f1cd5efb000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x0000000796566250> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:186)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:834)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:867)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1197)
        at java.util.concurrent.locks.ReentrantLock$NonfairSync.lock(ReentrantLock.java:214)
        at java.util.concurrent.locks.ReentrantLock.lock(ReentrantLock.java:290)
        at com.orientechnologies.common.concur.lock.OAdaptiveLock.lock(OAdaptiveLock.java:99)
        at com.orientechnologies.orient.enterprise.channel.OChannel.acquireReadLock(OChannel.java:121)
        at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:182)
        at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:171)
        at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:2136)
        at com.orientechnologies.orient.client.remote.OStorageRemote.command(OStorageRemote.java:1188)
        at com.orientechnologies.orient.client.remote.OStorageRemoteThread.command(OStorageRemoteThread.java:439)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:63)
        at au.com.foxsports.subscription.service.SubscriptionServiceImpl.findVertexByProperty(SubscriptionServiceImpl.java:1193)
        at au.com.foxsports.subscription.service.SubscriptionServiceImpl.loadBySubscriptionId(SubscriptionServiceImpl.java:1111)
        at au.com.foxsports.subscription.service.SubscriptionServiceImpl.get(SubscriptionServiceImpl.java:134)
        at sun.reflect.GeneratedMethodAccessor472.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)

**Comment by valeriotarenghi** [comment] 2015-09-09 01:43
Hi @sajid2045 
We started the analysis of log file to find the problem

**Comment by tglman** [comment] 2015-09-09 12:05
the cause of this is this issue: https://github.com/orientechnologies/orientdb/issues/4940 that left the network in a dirty state.

so is fixed in 2.1.2

**Closed by tglman** 2015-09-09 12:05 UTC
Labels: bug, in progress
