### ISSUE TITLE
UNIQUE HAS INDEX getting corrupted

### ISSUE THREAD

**Issue by lvca** [orientechnologies/orientdb#3743] opened 2015-03-10 19:02 UTC
Attached is the zip of cluster #2 which was isolated by emanuel and reproduced in our environment. i have sanitized most of the sensetive data, but as mentioned before --- please consider this data with utmost sensitivity, usage of this data is sole for debugging purposes and nothing else. Lastly you would delete all and every copy of the data once debugging is over. 

zip file attached.

**Comment by lvca** [comment] 2015-03-10 19:03
Attached the broken cluster via email at "UNIQUE HAS INDEX getting corrupted"

**Comment by tglman** [comment] 2015-03-10 19:52
hi, 
I did some investigation on this, the problem is not in the hash index.

in the sent cluster are present two RID that point to the same disk page area, this can be caused by an error during rollback or using transaction without WAL, also not shutdown the server in a proper way can lead to rollback problem, and to this issue.

we know that the new wal design(with release target 2.1) will solve the problem by increasing stability in case of server crash/kill.

I wrote a few test case to try to reproduce this problem in a systematic way with no success, so the only source of information we have til now is the sent broken cluster that lead us to the previous conclusion.

**Comment by laa** [comment] 2015-03-11 06:06
@tglman thank you that you spared my time to write conclusion.

**Comment by lvca** [comment] 2015-03-11 07:50
Ok, so this will be addresses in 2.1. Moving milestone...

**Comment by tglman** [comment] 2015-03-12 16:12
hi all,

doing some more test on the unique index i found some problem when we mixed up tx and noTx, just fixed, it is on develop and 2.0.x branch can you try that on your development environmet ?

bye

**Comment by johnmelba** [comment] 2015-03-31 19:58
btw this came up again in another of our class/cluster today and the entire table was corrupted with tons of duplicate records going in with a unique hash index field. In this particular case we were NOT using mix mode (i.e. TX and non-TX mode together) it was purely using TX mode and still this issue happened. 
We had to restore from the daily backup and manually move selected data one by one -- quite painful.

I hope this is resolved in 2.1 for real ! thanks.

**Comment by lvca** [comment] 2015-04-02 00:07
Hi,
Please could you try your sw against OrientDB 2.1-SNAPSHOT? It's under the
"develop" branch or on sonatype archives.

I'd like to release 2.1-rc1 tomorrow and your feedback would be fundamental
to understand if this problem is completely resolved.

Thanks,
Lvc@

**Comment by lvca** [comment] 2015-04-23 14:29
Can we close this issue?

**Comment by laa** [comment] 2015-06-03 13:27
closed because of no reply

**Closed by laa** 2015-06-03 13:27 UTC
Labels: waiting reply
