### ISSUE TITLE
[2.1.6] HTTP batch operation with multiple SQL select queries returns only 1 result

### ISSUE THREAD

**Issue by haibison** [orientechnologies/orientdb#5429] opened 2015-12-06 11:31 UTC
I'm using v2.1.6. HTTP batch operation with multiple `select` queries returns only 1 result. I think it's a bug.

I know there is another way for making queries. But since within a batch operation, I can make a single SQL query. So in theory it should be able to make multi queries for a batch operation.

Thanks,

P.S: Just a small note: if you could, please make tag `bug` red (by default it's red).

**Comment by luigidellaquila** [comment] 2015-12-06 11:38
Hi @haibison 

what do you mean exactly when you say that you are having only one result?

Are you receiving only one record or only the result of last statement?

The second one is the expected result, if you also need results from the other queries you can use LET clauses and functions to aggregate results, eg.

```
LET $a = select from foo;
LET $b = select from bar;
RETURN unionAll($a, $b)
```

Thanks

Luigi

**Comment by haibison** [comment] 2015-12-06 11:53
@luigidellaquila 

Thanks for your reply.

I've made my test again, here is the query:

```json
{
    "transaction": true,
    "operations": [
        {
            "type": "script",
            "language": "sql",
            "script": [
                "select utc_raw_offset from City where int_geohash >= 553586014660072528 order by int_geohash limit 1",
                "select utc_raw_offset from City where int_geohash >= 937093821111331561 order by int_geohash limit 1",
                "select utc_raw_offset from City where int_geohash >= 1067607278032234590 order by int_geohash limit 1",
                "select utc_raw_offset from City where int_geohash >= 940507792210735818 order by int_geohash limit 1",
                "select utc_raw_offset from City where int_geohash >= 890690375334637396 order by int_geohash limit 1",
                "select utc_raw_offset from City where int_geohash >= 1041613195570409909 order by int_geohash limit 1",
                "select utc_raw_offset from City where int_geohash >= 553095157998951188 order by int_geohash limit 1",
                "select utc_raw_offset from City where int_geohash >= 457089099049571409 order by int_geohash limit 1",
                "select utc_raw_offset from City where int_geohash >= 458443367084669051 order by int_geohash limit 1",
                "select utc_raw_offset from City where int_geohash >= 940764177988617094 order by int_geohash limit 1",
                "select utc_raw_offset from City where int_geohash >= 1012725506953832174 order by int_geohash limit 1"
            ]
        }
    ]
}
```

Here is the result:

```json
{
    "result": [
        {
            "@type": "d",
            "@rid": "#-2:0",
            "@version": 0,
            "utc_raw_offset": 25200000,
            "@fieldTypes": "utc_raw_offset=l"
        }
    ]
}
```

The result is for the last statement.

**Comment by luigidellaquila** [comment] 2015-12-06 13:24
Hi @haibison 

I can confirm, it's the expected behavior, not a bug. Query scripts always return the result of last statement.

You can execute multiple statements in the same query and merge the results using a query like following:

```
select expand(union) from (
   select unionAll($a, $b, $c) as union LET 
   $a = (select from foo), 
   $b = (select from bar), 
   $c = (select from baz) 
)

```

I'm closing this, please reopen in case you find any other strange behavior or if you need further info

Thanks

Luigi

**Closed by luigidellaquila** 2015-12-06 13:24 UTC

**Comment by haibison** [comment] 2015-12-06 13:51
Hi @luigidellaquila 

Thank you for your great sample code. It works very well  :+1: 

And thanks to the team for a great DB. Have a great weekend  :-)

Hai
