### ISSUE TITLE
NullPointerException at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.deserializeFromDirectMemory(ODurablePage.java:164)

### ISSUE THREAD

**Issue by wellpeng** [orientechnologies/orientdb#7369] opened 2017-04-26 01:31 UTC
## Expected behavior  and Actual behavior  
<pre>java.lang.NullPointerException
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.deserializeFromDirectMemory(ODurablePage.java:164)
	at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiBucket.getEntry(OSBTreeBonsaiBucket.java:280)
	at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.findBucket(OSBTreeBonsaiLocal.java:1359)
	at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.loadEntriesMajor(OSBTreeBonsaiLocal.java:774)
	at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.getRealBagSize(OSBTreeBonsaiLocal.java:1462)
	at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag.updateSize(OSBTreeRidBag.java:1029)
	at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag.size(OSBTreeRidBag.java:748)
	at com.orientechnologies.orient.core.db.record.ridbag.ORidBag.size(ORidBag.java:191)
	at com.tinkerpop.blueprints.impls.orient.OrientVertex.getEdges(OrientVertex.java:862)
	at com.tinkerpop.blueprints.impls.orient.OrientVertex.getEdges(OrientVertex.java:804)
</pre>

jvm: 
`-Xms20G -Xmx20G -Djna.nosys=true -XX:+HeapDumpOnOutOfMemoryError -XX:MaxDirectMemorySize=512g`

## Steps to reproduce  
1.   In the plocal mode about 12 minutes into the 140 million vertex, and then build a unique index.
2.   After the previous step is completed, reboot and insert the edge.
3.   Vertex and edge inserts are made in multithreading.
4.   With the index side of the bulk insert no problem, but slow. An exception occurs if the edge is created without an index.

I don't find the answer in #7074 and #7053
Constructing a vertex index takes 1.5 hours, and the vertex and index occupy disk 27G.

**Comment by wellpeng** [comment] 2017-04-26 02:19
In order to fast insert WAL is disabled.

**Comment by laa** [comment] 2017-04-26 05:30
Hi @wellpeng , thank you for a report.  But some of the steps to reproduce issue are not clear for me what does it mean "After the previous step is completed, reboot and insert the edge." what is rebooted, could you clarify a bit more?

**Comment by wellpeng** [comment] 2017-04-26 05:55
The vertices and edges are inserted in two phases. Insert the vertex and build the index after the check, no problem, then the edge of the insert. There is a stop between these two steps.

**Comment by wellpeng** [comment] 2017-04-26 06:42
@laa I used jdb to catch NPE in com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.deserializeFromDirectMemory after finding that the parameter binarySerializer is NULL.

**Comment by laa** [comment] 2017-04-26 06:46
@wellpeng Appreciate your help,  do you use specific data set or that is randomly generated vertexes. If that is randomly generated vertexes could you share a code for it? What do you do during a stop between index and vertex insertion? Do you close storage and reopen it or you only start the build of the new index?

**Comment by wellpeng** [comment] 2017-04-26 07:17
The following is the main code:
1. init factory
<pre>
OrientGraphFactory factory = new OrientGraphFactory(PLOCAL).setupPool(30, 1000);
OGlobalConfiguration.USE_WAL.setValue(false);
OGlobalConfiguration.DISK_CACHE_SIZE.setValue(51200);
OGlobalConfiguration.INDEX_EMBEDDED_TO_SBTREEBONSAI_THRESHOLD.setValue(-1);
factory.setConnectionStrategy(OStorageRemote.CONNECTION_STRATEGY.ROUND_ROBIN_CONNECT.toString());
</pre>

2. init vertex class
<pre>
OrientGraphNoTx db = factory.getNoTx();
OClass vcls = db.createVertexType("testv", "V", 20);
vcls.createProperty("my_id", OType.STRING);
... ... other fields
db.getRawGraph().close();
db.shutdown();
</pre>

3. bulk load by mutil threads 
<pre>
OrientBaseGraph db = factory.getNoTx();
db.getRawGraph().setValidationEnabled(false);
db.getRawGraph().setRetainRecords(false);
... ... bulk insert testv
db.declareIntent(null);
db.shutdown();
</pre>

4. build index, after check vertex testv, everything is normal.
<pre>
OrientGraphNoTx db = factory.getNoTx();
OClass cls = db.getVertexType("testv");
cls.createIndex("i_uin_idtype", INDEX_TYPE.UNIQUE, "my_id");
db.getRawGraph().close();
db.shutdown();
</pre>

6. stop app

7. start app switch to init edge class after initialization factory.
<pre>
OClass ecls = db.createEdgeType("teste", "E", 20);
cls.createProperty("e_id", OType.STRING);
// cls.createIndex("i_uin_eid", INDEX_TYPE.UNIQUE, "e_id");
... ... other fields
</pre>

8. bulk load by mutil threads 
<pre>
OrientBaseGraph db = factory.getNoTx();
db.getRawGraph().setValidationEnabled(false);
db.getRawGraph().setRetainRecords(false);
... ... bulk insert teste
db.declareIntent(null);
db.shutdown();
</pre>

That all.

**Comment by wellpeng** [comment] 2017-04-26 07:33
@laa This is a singleton class under multi thread.
<pre>
public class OdbGraphFactoryTest2 {
    private static volatile OdbGraphFactoryTest2 instance = null;
    private final static OrientGraphFactory factory = new OrientGraphFactory("plocal:databases/TestGraph").setupPool(30, 1000);
    private volatile static long st = System.currentTimeMillis();
    
    private OdbGraphFactoryTest2() {
    	this(false, false);
    }
    
    private OdbGraphFactoryTest2(boolean initV, boolean initE) {
    	globalConfig(initV, initE);
    }
    
    public static OdbGraphFactoryTest2 getInstance(boolean initV, boolean initE) {
    	OdbGraphFactoryTest2 inst = instance;
        if(inst == null) {
            synchronized (OdbGraphFactoryTest2.class) {
                inst = instance;
                if(inst == null) {
                    inst = new OdbGraphFactoryTest2(initV, initE);
                    instance = inst;
                }
            }
        }
        return inst;
    }
    
    private void globalConfig(boolean initV, boolean initE) {
        setConnectionStrategy();
        
        OGlobalConfiguration.USE_WAL.setValue(false);
        OGlobalConfiguration.DISK_CACHE_SIZE.setValue(51200);
        
        OGlobalConfiguration.INDEX_EMBEDDED_TO_SBTREEBONSAI_THRESHOLD.setValue(-1);
        
        if(initV || initE) {
	        OrientBaseGraph db = factory.getNoTx();
	        initVE(db, initV, initE);
	        System.out.println("DB Init ok!");
        }
    }
    
    private void setConnectionStrategy() {
        factory.setConnectionStrategy(OStorageRemote.CONNECTION_STRATEGY.ROUND_ROBIN_CONNECT.toString());
    }
    
    public OrientBaseGraph getFactoryNoTx() {
        OrientBaseGraph db = factory.getNoTx();
        
        db.getRawGraph().setValidationEnabled(false);
        db.getRawGraph().setRetainRecords(false);
        return db;
    }
    
    private void initVE(OrientBaseGraph db, boolean initV, boolean initE) {
    	if(initV) initV(db);
    	if(initE) initE(db);
    }
    
    private void initV(OrientBaseGraph db) {
    	if(db.getVertexType("testv") != null) {
    		try {
    			db.getVertexType("testv").truncate();
				db.dropVertexType("testv");
				
	    		System.out.println("drop testv");
			} catch (IOException e) {
				e.printStackTrace();
				return;
			}
    	}
    	
    	OClass vcls = db.createVertexType("testv", "V", 20); // 20
		initCFields(vcls);
    	
    	System.out.println("create testv");
    }
    
    private void initE(OrientBaseGraph db) {
    	if(db.getEdgeType("teste") != null) {
    		try {
	    		db.getEdgeType("teste").truncate();
	    		db.dropEdgeType("teste");
	    		
	    		System.out.println("drop teste");
	    	} catch (IOException e) {
				e.printStackTrace();
				return;
			}
    	}
    	
		OClass ecls = db.createEdgeType("teste", "E", 20);
    	initRFields(ecls);
    	
    	System.out.println("create teste");
    }
    
    private void initCFields(OClass cls) {
    	cls.setShortName("C");
    	cls.createProperty("v_id", OType.STRING);
    	cls.createProperty("name", OType.STRING);
    }
    
    private void initRFields(OClass cls) {
    	cls.setShortName("R");
    	cls.createProperty("e_id", OType.STRING);
//    	cls.createIndex("i_uin_rid", INDEX_TYPE.UNIQUE, "r_id");
    }
    
    public void rebuildVIndex() {
    	int maxRetries = 10;
    	OrientGraphNoTx db = factory.getNoTx();
    	
    	System.out.println("rebuild index testv i_uin_idtype begin...");
    	for (int retry = 0; retry < maxRetries; retry++) {
	    	try {
	    		long st = System.currentTimeMillis();
	    		
		    	OClass cls = db.getVertexType("testv");
		    	
		    	if(cls.areIndexed("i_uin_idtype")) {
		    		cls.getClassIndex("i_uin_idtype").rebuild();
		    	} else {
		    		cls.createIndex("i_uin_idtype", INDEX_TYPE.UNIQUE, "v_id");
		    	}
		    	db.getRawGraph().close();
		        db.shutdown();
		        
		        System.out.println("rebuild index testv i_uin_idtype ok! time: " + (System.currentTimeMillis() - st));
		        break;
	    	} catch(ORecordDuplicatedException orde) {
	    		System.out.println(orde.getRid().getRecord().toString() + ", time: " + (System.currentTimeMillis() - st));
	    		db.getVertex(orde.getRid()).getRecord().delete();
	    		continue;
	        } catch(Exception e) {
	        	e.printStackTrace();
	        	break;
	        }
    	}
    }
    
}
</pre>

**Comment by laa** [comment] 2017-04-26 08:12
Hi, @wellpeng thank you very much, I will try to reproduce the issue and give you feedback in a couple of hours.

**Comment by laa** [comment] 2017-04-26 15:32
@wellpeng I am trying to reproduce the issue. From stack trace that is obvious that you call getEdges method. Could you describe how do you insert edges? Because I see you do not use an index to find vertexes for edges. Also, the target of calling of getEdges is not clear for me.

**Comment by wellpeng** [comment] 2017-04-27 02:25
Hi @laa thank you very much, The following is the insert edges code in mutil thread:
<pre>
public class EdgeOnlyToOrientdbTest2 implements Runnable {
	private final static OdbGraphFactoryTest2 odbGraphFactory = OdbGraphFactoryTest2.getInstance(false, true);
	private List<String> list;
	public EdgeOnlyToOrientdbTest2() {}
	public EdgeOnlyToOrientdbTest2(List<String> list) {
		this.list = list;
	}
	
	@Override
	public void run() {
		OrientBaseGraph db = odbGraphFactory.getFactoryNoTx();
		
		try {
			db.declareIntent(new OIntentMassiveInsert());
			Iterator<String> iterator = list.iterator();
			while (iterator.hasNext()) {
				String line = iterator.next();
				String[] row = line.split("\t");
				RelationTest r = new RelationTest();
				String idStr = row[0];
				r.setFrom(idStr);
				String idToStr = row[1];
				r.setTo(idToStr);
				addVertexEdgeNoTx(db, r);
			}
			db.declareIntent(null);
		} catch (Exception se) {
			se.printStackTrace();
			db.rollback();
        } finally {
        	db.shutdown();
        }
	}
	
    private void addVertexEdgeNoTx(OrientBaseGraph db, RelationTest r) {
        Vertex fromV = null;
        Vertex toV = null;
        int maxRetries = 100;
        
        fromV = getVertexByCId(db, r.getFrom());
        if(fromV == null) {
            return;
        }
        
        toV = getVertexByCId(db, r.getTo());
        if(toV == null) {
            return;
        }
        
        // edge ===============
        // edge > 100 then return
        Iterable<Edge> it1 = null;
        try {
	        it1 = fromV.getEdges(Direction.BOTH, "teste"); // NPE break here
	    } catch(NullPointerException npe) {
	    	Integer oldVer = fromV.getProperty("@version");
	    	fromV = getVertexByCId(db, r.getFrom());
	    	System.out.println("fromV fail! fromV: " + r.getFrom() + ", oldVer: " + oldVer +  ", newVer: " + fromV.getProperty("@version"));
	    	npe.printStackTrace();
	    	return;
	    }
        
        if(it1 != null) {
            Iterator<Edge> f1 = it1.iterator();
            if(f1 != null) {
            	int edgesCount = 0;
                while (f1.hasNext()) {
                    f1.next();
                    
                    if(edgesCount > 100) {
                    	break;
                    }
                    
                    edgesCount++;
                }
                
                if(edgesCount > 100) {
                	return;
                }
            }
        }
        
        Iterable<Edge> it2 = null;
        try {
        	it2 = toV.getEdges(Direction.BOTH, "teste"); // NPE break here
        } catch(NullPointerException npe) {
	    	Integer oldVer = fromV.getProperty("@version");
	    	toV = getVertexByCId(db, r.getTo());
	    	System.out.println("toV fail! toV: " + r.getTo() + ", oldVer: " + oldVer + ", newVer: " + toV.getProperty("@version"));
	    	npe.printStackTrace();
	    	return;
	    }
        
        if(it2 != null) {
            Iterator<Edge> f1 = it2.iterator();
            if(f1 != null) {
            	int edgesCount = 0;
                while (f1.hasNext()) {
                    f1.next();
                    
                    if(edgesCount > 100) {
                    	break;
                    }
                    
                    edgesCount++;
                }
                
                if(edgesCount > 100) {
                	return;
                }
            }
        }
        
        for (int retry = 0; retry < maxRetries; retry++) {
            try {
                Map<String, Object> props = new HashMap<String, Object>();
                props.put("e_id", r.getFrom() + r.getTo());
                ((OrientVertex) fromV).addEdge("teste", (OrientVertex) toV, "teste", null, props);
                break;
            } catch (ORecordDuplicatedException orde) {
                break;
            } catch (Exception e) {
            	if(retry < 3) {
            		fromV = db.getVertex(fromV.getId());
            		toV = db.getVertex(toV.getId());
            	}
            	
                if(retry > 95) {
                	fromV = db.getVertex(fromV.getId());
            		toV = db.getVertex(toV.getId());
            		
            		System.out.println("create edge fail");
                }
            }
        }
    }
    
    private Vertex getVertexByCId(OrientBaseGraph db, String vId) {
    	Vertex v = null;
    	try {
        	Iterable<Vertex> vit = db.getVertices("testv.v_id", vId);
        	
        	if(vit != null) {
        		Iterator<Vertex> vi = vit.iterator();
        		if(vi.hasNext()) {
        			v = vi.next();
        		}
        	}
        } catch (Exception e) {
    		System.out.println("get vertex fail");
        }
    	return v;
    }
}

class RelationTest {
	private String from;
	private String to;
	public String getFrom() {
		return from;
	}
	public void setFrom(String from) {
		this.from = from;
	}
	public String getTo() {
		return to;
	}
	public void setTo(String to) {
		this.to = to;
	}
}
</pre>

**Comment by wellpeng** [comment] 2017-04-27 06:32
```java
public class EdgeOnlyToOrientdbTest2 implements Runnable {
	private final static OdbGraphFactoryTest2 odbGraphFactory = OdbGraphFactoryTest2.getInstance(false, true);
	private List list;
	public EdgeOnlyToOrientdbTest2() {}
	public EdgeOnlyToOrientdbTest2(List list) {
		this.list = list;
	}
	
	@Override
	public void run() {
		OrientBaseGraph db = odbGraphFactory.getFactoryNoTx();
		
		try {
			db.declareIntent(new OIntentMassiveInsert());
			Iterator iterator = list.iterator();
			while (iterator.hasNext()) {
				String line = iterator.next();
				String[] row = line.split("\t");
				RelationTest r = new RelationTest();
				String idStr = row[0];
				r.setFrom(idStr);
				String idToStr = row[1];
				r.setTo(idToStr);
				addVertexEdgeNoTx(db, r);
			}
			db.declareIntent(null);
		} catch (Exception se) {
			se.printStackTrace();
			db.rollback();
        } finally {
        	db.shutdown();
        }
	}
	
    private void addVertexEdgeNoTx(OrientBaseGraph db, RelationTest r) {
        Vertex fromV = null;
        Vertex toV = null;
        int maxRetries = 100;
        
        fromV = getVertexByCId(db, r.getFrom());
        if(fromV == null) {
            return;
        }
        
        toV = getVertexByCId(db, r.getTo());
        if(toV == null) {
            return;
        }
        
        // edge ===============
        // edge > 100 then return
        Iterable it1 = null;
        try {
	        it1 = fromV.getEdges(Direction.BOTH, "teste"); // NPE break here
	    } catch(NullPointerException npe) {
	    	Integer oldVer = fromV.getProperty("@version");
	    	fromV = getVertexByCId(db, r.getFrom());
	    	System.out.println("fromV fail! fromV: " + r.getFrom() + ", oldVer: " + oldVer +  ", newVer: " + fromV.getProperty("@version"));
	    	npe.printStackTrace();
	    	return;
	    }
        
        if(it1 != null) {
            Iterator f1 = it1.iterator();
            if(f1 != null) {
            	int edgesCount = 0;
                while (f1.hasNext()) {
                    f1.next();
                    
                    if(edgesCount > 100) {
                    	break;
                    }
                    
                    edgesCount++;
                }
                
                if(edgesCount > 100) {
                	return;
                }
            }
        }
        
        Iterable it2 = null;
        try {
        	it2 = toV.getEdges(Direction.BOTH, "teste"); // NPE break here
        } catch(NullPointerException npe) {
	    	Integer oldVer = toV.getProperty("@version");
	    	toV = getVertexByCId(db, r.getTo());
	    	System.out.println("toV fail! toV: " + r.getTo() + ", oldVer: " + oldVer + ", newVer: " + toV.getProperty("@version"));
	    	npe.printStackTrace();
	    	return;
	    }
        
        if(it2 != null) {
            Iterator f1 = it2.iterator();
            if(f1 != null) {
            	int edgesCount = 0;
                while (f1.hasNext()) {
                    f1.next();
                    
                    if(edgesCount > 100) {
                    	break;
                    }
                    
                    edgesCount++;
                }
                
                if(edgesCount > 100) {
                	return;
                }
            }
        }
        
        for (int retry = 0; retry < maxRetries; retry++) {
            try {
                Map props = new HashMap();
                props.put("e_id", r.getFrom() + r.getTo());
                ((OrientVertex) fromV).addEdge("teste", (OrientVertex) toV, "teste", null, props);
                break;
            } catch (ORecordDuplicatedException orde) {
                break;
            } catch (Exception e) {
            	if(retry < 3) {
            		fromV = db.getVertex(fromV.getId());
            		toV = db.getVertex(toV.getId());
            	}
            	
                if(retry > 95) {
                	fromV = db.getVertex(fromV.getId());
            		toV = db.getVertex(toV.getId());
            		
            		System.out.println("create edge fail");
                }
            }
        }
    }
    
    private Vertex getVertexByCId(OrientBaseGraph db, String vId) {
    	Vertex v = null;
    	try {
        	Iterable vit = db.getVertices("testv.v_id", vId);
        	
        	if(vit != null) {
        		Iterator vi = vit.iterator();
        		if(vi.hasNext()) {
        			v = vi.next();
        		}
        	}
        } catch (Exception e) {
    		System.out.println("get vertex fail");
        }
    	return v;
    }
}

class RelationTest {
	private String from;
	private String to;
	public String getFrom() {
		return from;
	}
	public void setFrom(String from) {
		this.from = from;
	}
	public String getTo() {
		return to;
	}
	public void setTo(String to) {
		this.to = to;
	}
}

**Comment by laa** [comment] 2017-04-27 13:02
@wellpeng I have created an application and have been running it for 4 hours without exceptions https://gist.github.com/laa/c56dc3d36f2eee6dc2b1c10e7b375b70 . Could you check code and modify it, so I will be able to reproduce exception.

**Comment by laa** [comment] 2017-04-27 13:35
@wellpeng I will be absent till 2-d of May, but I will appreciate your help and looking forward to fixing it once I will be back.

**Comment by laa** [comment] 2017-05-03 07:47
@wellpeng could you check the code and write what is wrong with it?

**Comment by laa** [comment] 2017-05-04 07:06
@wellpeng if that is time-consuming for you to check test which I provided. Could you send me your project so I will be able to reproduce the issue on my side?

**Comment by wellpeng** [comment] 2017-05-05 01:41
@laa Sorry, I have to deal with other matters first. Recently discovered that the OrientDB consumes too much disk IO.

**Comment by laa** [comment] 2017-05-05 05:24
@wellpeng what do you mean by too much disk IO could you elaborate more?

**Comment by laa** [comment] 2017-05-07 10:31
Hi @wellpeng could you elaborate what do you mean? Hopefully, we may help you.

**Comment by laa** [comment] 2017-08-17 08:20
Will try to reproduce it anyway

**Comment by laa** [comment] 2017-08-17 08:20
Will try to reproduce it anyway

**Comment by laa** [comment] 2017-08-18 08:41
@wellpeng could you kindly provide the source code of project which you created for ODB testing it will help us a lot to reproduce given issue?

**Comment by laa** [comment] 2017-09-16 06:37
closing because cannot reproduce for a long time

**Closed by laa** 2017-09-16 06:37 UTC
Labels: reproducing, storage team
