### ISSUE TITLE
Enhancement Request: Save query output to CSV from the console.

### ISSUE THREAD

**Issue by william76** [orientechnologies/orientdb#6697] opened 2016-09-14 19:48 UTC
## OrientDB Version, operating system, or hardware.
- [X] v2.2.9
## Operating System
- [X] Linux
- [X] MacOSX
- [X] Windows
- [ ] Other Unix
- [ ] Other, name? 
## Enhancement Request

Per email thread [https://groups.google.com/forum/#!topic/orient-database/rAfYoQMBs1g](https://groups.google.com/forum/#!topic/orient-database/rAfYoQMBs1g) I am posting this enhancement request.

The ability to save the results of a query into a CSV table exists in Studio, but to my knowledge it is not currently available from the console.sh app.  The ability to execute a query and save its result into a delimited text file (CSV, TSV, etc.) from the console is desirable for environments like ours in which we would like to be able to run a query using a script that executes a query or series of queries and saves the output into CSV files that can be easily ingested into other tools.

Just a thought, this could possibly be done via the SET command to the console... since it's just a key-value pair... something like the following sequence might be reasonable:

```
SET OUTPUT_MODE "CSV"
SET OUTPUT_FILE "filename.csv"
SELECT FROM V
```

or perhaps in one command if the <property-value> entries can be parsed:

```
SET OUTPUT "CSV;filename.csv"
SELECT FROM V
```

In any case, however it's implemented it would be handy to have a way to save the output from a query to a CSV file from the console so that it could be done via scripts or other batch commands.

Thanks!

**Comment by manmohanp** [comment] 2017-04-10 17:24
I feel this is quite essential for practical situations for people to take out data for reporting or sharing out of the database. Studio too should have, else no way to share either, just copying with clipboard isn't workable.

**Comment by william76** [comment] 2017-04-27 16:55
Just bumping this... this is becoming an increasingly important thing.  

In other databases like SQLite, it's pretty trivial to create a script that can dump the results of a query to a CSV file from the console for sharing and/or to pull into excel or a stats tool like JMP.  It'd be nice to have this feature added to OrientDB.

Currently, the only option I have is to run a query and get the ASCII table and manually fix the data to be delimited text so we can pull it into other tools.

**Comment by manmohanp** [comment] 2017-04-27 18:27
As of now I had to write query and dump data using CSV utility using Java API, not idle but no other way to extract query output which I feel is must have for Studio/Console.sh.

**Comment by grv87** [comment] 2019-11-09 19:38
Duplicate of #5435

**Closed** 2021-08-05 11:18 UTC
Labels: enhancement

**Comment by stephanemartin** [comment] 2024-05-29 12:56
Hello, this enhancement looks like done. But I can't find how to export csv in console with query in the documentation. 
https://orientdb.com/docs/3.2.x/

Any help is appreciated. Thx
