### ISSUE TITLE
Index collation not applied with OR clause

### ISSUE THREAD

**Issue by ataylor284** [orientechnologies/orientdb#7216] opened 2017-03-06 23:53 UTC
## Expected behavior  
When a class has an index with case insensitive collation, that index is properly applied for a simple query.  

When querying two possibilities in an OR clause, the should be used and the index's collation property should be applied.

## Actual behavior  
The index appears appears to be identified, but not used and the collation property is ignored.

## Steps to reproduce  

In orientdb console:
```
create class C
create property C.name
create index C_IDX on C(name collate ci) NOTUNIQUE
insert into C(name) values ('test')

select count(*) from C where name = 'TEST'
 +----+-----+
 |#   |count|
 +----+-----+
 |0   |1    |
 +----+-----+
explain select count(*) from C where name = 'TEST'
 {"@type":"d","@version":0,"projectionElapsed":0,"limit":-1,"compositeIndexUsed":0,"user":"#5:0","involvedIndexes":["C_IDX"],"elapsed":0.325355,"resultType":"collection","resultSize":1,"@fieldTypes":"projectionElapsed=l,compositeIndexUsed=l,user=x,involvedIndexes=e,elapsed=f"}

select count(*) from C where name = 'TEST' or name = 'TEST1'
 +----+-----+
 |#   |count|
 +----+-----+
 |0   |0    |
 +----+-----+
explain select count(*) from C where name = 'TEST' or name = 'TEST1'
 {"@type":"d","@version":0,"documentReads":1,"fullySortedByIndex":false,"documentAnalyzedCompatibleClass":1,"recordReads":1,"fetchingFromTargetElapsed":0,"indexIsUsedInOrderBy":false,"compositeIndexUsed":2,"current":"#25:0","involvedIndexes":["C_IDX"],"projectionElapsed":0,"limit":-1,"evaluated":1,"groupByElapsed":0,"user":"#5:0","elapsed":0.468799,"resultType":"collection","resultSize":1,"@fieldTypes":"documentReads=l,documentAnalyzedCompatibleClass=l,recordReads=l,fetchingFromTargetElapsed=l,compositeIndexUsed=l,current=x,involvedIndexes=e,projectionElapsed=l,evaluated=l,groupByElapsed=l,user=x,elapsed=f"}
```

May be related to https://github.com/orientechnologies/orientdb/issues/6014

**Comment by luigidellaquila** [comment] 2017-03-08 09:27
Closing, as a duplicate of http://www.prjhub.com/#/issues/8399

Thanks

Luigi

**Closed by luigidellaquila** 2017-03-08 09:27 UTC
Labels: bug
