### ISSUE TITLE
drop index, create it, says that index already exists

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#6948] opened 2016-11-25 12:02 UTC
## OrientDB Version, operating system, or hardware.
- v2.2.14-SNAPSHOT-20161118.121331-4

## Operating System
- [x] Linux

## Expected behavior and actual behavior

1. started the non-distributed mode of the server, and login via "console.sh"
2. I drop an index
3. I create it again but with different columns
4. at the end, the logs say that index is properly created:
```
2016-11-25 12:41:48:422 INFO  {db=cdrarch} --> OK, indexed 38,150,465 items in 9,770,022 ms [OIndexRebuildOutputListener]
```
5. in console, the command terminates with
```
orientdb {db=cdrarch}> drop index idx_cdr_icx_20161113_0                                                               
Removing index...
Dropped index in 4.377000 sec(s).
Index removed successfully
orientdb {db=cdrarch}> create index idx_cdr_icx_20161113_0 on cdr_icx_20161113(ENV,PRT_DATE,FILENAME,RECORD_NUMBER) UNIQUE
Creating index...
Error: com.orientechnologies.orient.core.index.OIndexException: Index with name idx_cdr_icx_20161113_0 already exists.
        DB name="cdrarch"
        DB name="cdrarch"
```
6. if I ask status of the index in console, it say that it do not exist?!
```
orientdb {db=cdrarch}> desc cdr_icx_20161113
...
INDEXES (1 altogether)
+----+----------------------+----------+
|#   |NAME                  |PROPERTIES|
+----+----------------------+----------+
|0   |idx_cdr_icx_20161113_1|[FILENAME]|
+----+----------------------+----------+
```

**Comment by tglman** [comment] 2016-11-25 16:27
hi @rdelangh,

I can drop and create indexes without problems using the console, i was not able to reproduce it at all, can you give me a complete list of steps that reproduce it from scratch ?

Thank you in advance.

Bye

**Comment by vtliem** [comment] 2016-11-28 00:15
I have seen the same issue.
1.I upgraded OrientDB from 2.0 -> 2.1 -> 2.2
2.When I recreated index (Drop and create it to add some fields)
"index already exists" exception raised.

I did export/import db and recreate index without this issue.

**Comment by rdelangh** [comment] 2016-11-28 09:17
@tglman
previously, this server was started in distributed mode, in an attempt to get a 2nd server added in its 'group' (see #6666)
So I guess there is some inconsistency entered in the database during the replication attempts with that 2nd server node ...

I now started this server in standalone (= not distributed) mode, and get this problem on different classes:
```
orientdb {db=cdrarch}> desc cdr_icx_20161120
...
INDEXES (2 altogether)
+----+----------------------+-------------------------------------+
|#   |NAME                  |PROPERTIES                           |
+----+----------------------+-------------------------------------+
|0   |idx_cdr_icx_20161120_1|[FILENAME]                           |
|1   |idx_cdr_icx_20161120_0|[ENV,FILENAME,RECORD_NUMBER,PRT_DATE]|
+----+----------------------+-------------------------------------+
orientdb {db=cdrarch}> drop index idx_cdr_icx_20161120_0
Removing index...
Dropped index in 3.822000 sec(s).
Index removed successfully
orientdb {db=cdrarch}> create index idx_cdr_icx_20161120_0 on cdr_icx_20161120(ENV,PRT_DATE,FILENAME,RECORD_NUMBER) UNIQUE
Creating index...
Error: com.orientechnologies.orient.core.index.OIndexException: Index with name idx_cdr_icx_20161120_0 already exists.
        DB name="cdrarch"
        DB name="cdrarch"

orientdb {db=cdrarch}> desc cdr_icx_20161120
...
INDEXES (2 altogether)
+----+----------------------+-------------------------------------+
|#   |NAME                  |PROPERTIES                           |
+----+----------------------+-------------------------------------+
|0   |idx_cdr_icx_20161120_1|[FILENAME]                           |
|1   |idx_cdr_icx_20161120_0|[ENV,PRT_DATE,FILENAME,RECORD_NUMBER]|
+----+----------------------+-------------------------------------+
```

**Comment by tglman** [comment] 2016-11-30 11:19
hi,

this should be already fixed in the current 2.2.x branch, and should be released in 2.2.14.

Regards

**Comment by rdelangh** [comment] 2016-12-01 09:55
@tglman 
We run now already a version 2.2.14, be it a snapshot version : build number 
"UNKNOWN@rf1d3ed9d4b31253918b017fac1d82f6cf9173f75; 2016-11-18 09:52:27+0000"

-> is that fix included in this snapshot ?

**Comment by lvca** [comment] 2016-12-27 15:01
@rdelangh could you please try it with 2.2.14 GA?

**Comment by rdelangh** [comment] 2017-01-05 11:30
@lvca 
hi Luca, now we run snapshot version 2.2.14-20161222.152236-78 ; does the GA version (also from Dec-22) contain same, less, or more fixes than this snapshot version ?
In other words: will I lose some fixes if I replace that snapshot version by the GA version ?

**Comment by tglman** [comment] 2017-01-05 13:24
hi @rdelangh,

The relase include exactly the same fixes of the snapshot, here is the log : https://github.com/orientechnologies/orientdb/commits/2.2.14

Hope this help.

Regards

**Comment by rdelangh** [comment] 2017-01-05 14:36
With version 2.2.14-20161222.152236-78 , this issue with the index is still happening:

1) dropped index idx_cdr_eno_20161218_2
2) then re-create it:
orientdb {db=mobile}> create index idx_cdr_eno_20161218_2 on cdr_eno_20161218(FILENAME) FULLTEXT METADATA { "indexRadix": false, "ignoreChars": "", "separatorChars" : "", "stopWords": [] }
Creating index...
Error: com.orientechnologies.orient.core.index.OIndexException: Index with name idx_cdr_eno_20161218_2 already exists.
        DB name="mobile"
        DB name="mobile"

(This is not a Lucene index, if that would matter)

**Comment by lvca** [comment] 2017-01-30 21:29
@rdelangh any news on this?

**Closed** 2017-01-30 21:30 UTC
Labels: bug, resolved

**Comment by rdelangh** [comment] 2017-01-31 13:32
Haven't been in a similar situation anymore, now running 2.2.15

Will comment again if this occurs once more.

thx for your help so far!
