### ISSUE TITLE
Cannot delete class 'Liked UNSAFE'

### ISSUE THREAD

**Issue by larryaasen** [orientechnologies/orientdb#6460] opened 2016-07-23 18:56 UTC
Hi,

I have somehow created a class with the name 'Liked UNSAFE' that has the space character in the name. I am not able to select from or delete this class. Can you help me delete this class?

From the console I see these messages:
```
> info class 'Liked UNSAFE'
CLASS 'Liked UNSAFE'

Super classes........: [E]
Default cluster......: liked unsafe (id=21)
Supported clusters...: liked unsafe(21)
Cluster selection....: round-robin
Oversize.............: 0.0
```

```
> select from `Liked UNSAFE`

Error: com.orientechnologies.orient.core.exception.OQueryParsingException: Error on parsing query at position #7: Error on parsing command at position #0: Error on parsing query
Query:  `Liked UNSAFE`
------------^

Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Class '`LIKED' was not found in current database
```

```
> info
CLASSES
---------------------+----------------------+------------+----------------+
 NAME                | SUPERCLASS | CLUSTERS   | RECORDS        |
---------------------+----------------------+----- --+----------------+
Liked                    | [E] | 28 | 1619 |
Liked UNSAFE               | [E] | 21 | 892 |
```

```
> delete edge `Liked UNSAFE` where out=#24:22033

Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error on parsing command at position #0: Class '`LIKED' was not found
```

## OrientDB Version, operating system, or hardware.
OrientDB console v.2.1.10 (build 2.1.x@r877c28613f3b79e91ee40f58e551f3b82d814bcf; 2016-02-04 17:14:18+0000) www.orientdb.com

## Operating System:
Linux

**Comment by luigidellaquila** [comment] 2016-07-25 07:02
Hi @larryaasen 

I think the problem is already solved in latest release (I mean, the problem of being able to create classes with spaces).
I'm afraid the only way you have to fix the problem is to connect via Java in embedded mode and delete the class from the schema:

```
db.getMetadata().getSchema().dropClass("Liked UNSAFE");
```

thanks

Luigi

**Comment by larryaasen** [comment] 2016-07-25 09:52
Hi @luigidellaquila 

Thanks for the response. I am not sure how to connect via Java in embedded mode. I am using the Go client https://github.com/istreamdata/orientgo and don't use Java. I can use the Console app with 2.2.5 and see if that works. Does that connect via Java?

**Comment by luigidellaquila** [comment] 2016-07-25 12:55
Hi @larryaasen 

I'm afraid from the console you won't be able to do it.
The complete Java code to do it is

```
import com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx;

public class Test {
  public static void main(String[] agrs){
    ODatabaseDocumentTx db = new ODatabaseDocumentTx("plocal:/your/db/folder");
    db.open("admin", "admin");
    db.getMetadata().getSchema().dropClass("Liked UNSAFE");
    db.close();
  }
}
```

I strongly suggest you to at least update to 2.1.20 (latest stable in 2.1.x branch), that contains important fixes compared to 2.1.10

Thanks

Luigi

**Comment by smolinari** [comment] 2016-07-25 13:35
@luigidellaquila - a wild shot in the dark, but could a function do this kind of schema manipulation? It would be a wicked workaround, if it could. :smile: 

Scott

**Comment by luigidellaquila** [comment] 2016-07-25 13:49
Ah, right! Thanks Scott!!!
Let me write a simple function to do it, I'll be back in short

Thanks

Luigi

**Comment by luigidellaquila** [comment] 2016-07-25 13:53
Here it is

```
db = orient.getGraphNoTx();
db.getRawGraph().getMetadata().getSchema().dropClass("your class name here");
```

Just copy-paste this in OrientDB Studio function editor, give the function a name and choose Javascript as the function programming language. Then save and run it

Let me know if it works

Thanks

Luigi

**Comment by smolinari** [comment] 2016-07-25 14:28
The server side functions and triggers are really cool features. It is a shame the documentation doesn't cover them a lot better. Is there a way to read into the Java code to understand what is possible with with the server-side functions? If there is, and you could point me in the right directions, I'd be willing to help with making better docs for the functions feature. I could open another issue, should it be possible. 

Scott

**Comment by larryaasen** [comment] 2016-09-09 03:31
Hi Luigi,

I used this command to drop the class 'Liked UNSAFE' and it worked:
`
jss orient.getGraphNoTx().getRawGraph().getMetadata().getSchema().dropClass("Liked UNSAFE");end;
`
I first had to enable server side Javascript, restart the OrientDB server, reconnect with the console, and then enter that command into the console.

Thanks for your help.

Larry

**Comment by luigidellaquila** [comment] 2016-09-09 07:11
Great, I'm closing this issue then, as the problem should not occur anymore in v 2.2

Thanks

Luigi

**Closed by luigidellaquila** 2016-09-09 07:11 UTC
Labels: bug
