### ISSUE TITLE
Export/import from 2.2.4 to 2.2.10 failed

### ISSUE THREAD

**Issue by yeoedward** [orientechnologies/orientdb#6759] opened 2016-09-29 22:26 UTC
## OrientDB Version, operating system, or hardware.
v2.2.4 and v2.2.10

## Operating System
Linux

## Expected behavior and actual behavior
Expected: Successful import of database into 2.2.10 that was exported from 2.2.4
Actual: Empty database after import

## Steps to reproduce the problem
I'm not able to release the database, and I haven't been able to reproduce the problem on another database. Export/import within 2.2.4 works fine. It seems like the import process somehow runs twice, and in the second time deletes all the previously imported data. This is the output:

Command:
`import database <path to export file> -preserveClusterIDs=true`

Output:
```
Started import of database 'plocal:<path to database folder> from /tmp/...
Non merge mode (-merge=false): removing all non security classes
- Class OFunction was removed.
- Class ....
...
...
Removed # classes.
Importing database info...OK
Importing clusters...
- Creating cluster <cluster name>...OK, assigned id=0
...
...
...
Rebuilding indexes of truncated clusters ...
--- Cluster content was updated ... successfully rebuilt
Done # indexes were rebuilt.
Done. Imported # clusters.
Importing database schema...OK (# classes)

Importing records...
- Imported # records into clusters:...
...
...
Started import of database 'plocal:/<path to databases>' from /tmp/...
Non merge mode (-merge=false): removing all non security classes
- Class <class name> was removed.
- Class ....
...
...
<Here all the classes that were imported were removed!>
Removed # classes
Rebuild of stale indexes...
...
Deleting RID Mapping table...OK

Database import completed in # ms

```

**Comment by obi1kenobi** [comment] 2016-09-30 00:21
Might be related to #6687, I was seeing something similar.

**Comment by tglman** [comment] 2016-09-30 11:04
hi @yeoedward,

I tried to reproduce this without success, do you have an example export?

if is needed you can even share privately.

bye

**Comment by yeoedward** [comment] 2016-09-30 19:21
Hello @tglman, sorry I am unable to share my database as it contains proprietary data. I couldn't reproduce this on another example database. Is there anything else I can do to help track down this problem?

Just to highlight something I noticed (in case you missed it), after all the records were imported, it seems the import process restarted and deleted all the classes (as it normally does when it starts).

**Comment by obi1kenobi** [comment] 2016-10-03 14:39
I believe this is not related to the version upgrade, and that `IMPORT DATABASE` via the remote protocol has a bug that is triggered by some workloads -- see #6758 for details.

Would you mind checking the server logs for any error messages that might have been printed during the import? #6758 printed some errors and stack traces, and I was wondering if they are the same.

**Comment by yeoedward** [comment] 2016-10-04 13:47
@obi1kenobi I tried importing again just to be sure (which takes several hours), and there were no error messages in the server logs. But looking at #6758, it seems like we have the same problem! I am also using remote import.

**Comment by obi1kenobi** [comment] 2016-10-04 14:06
When I import into 2.2.11 there are also no error messages -- the errors only appeared on 2.2.8 so my guess is something in the import logic changed between those two versions. Thanks for double-checking!

**Comment by tglman** [comment] 2016-10-04 14:24
Hi All,

I think i found out the source of the problem, it was the generic retry used by all the remote operations, i disabled the retry for the import, and improved the server side logs, so in case of disconnection you can check if the import goes correctly on the server log and retry if it fail.

bye

**Comment by yeoedward** [comment] 2016-10-04 18:08
@tglman I just tried to build the 2.2.x branch to test it but there are tests failing:

```
Tests run: 1622, Failures: 12, Errors: 0, Skipped: 6, Time elapsed: 134.347 sec <<< FAILURE! - in TestSuite
shouldCheckPlainPasswordAgainstHashWithSalt(com.orientechnologies.orient.core.security.OSecurityManagerTest)  Time elapsed: 0.013 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[tru]e> but was:<[fals]e>
        at com.orientechnologies.orient.core.security.OSecurityManagerTest.shouldCheckPlainPasswordAgainstHashWithSalt(OSecurityManagerTest.java:46)

testSalt(com.orientechnologies.orient.core.metadata.security.HashSaltTest)  Time elapsed: 0.002 sec  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
        at com.orientechnologies.orient.core.metadata.security.HashSaltTest.testSalt(HashSaltTest.java:23)

testSelectDeleteBinary on testSelectDeleteBinary(com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery)(com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery)  Time elapsed: 0.002 sec  <<< FAILURE!
com.orientechnologies.orient.core.exception.OStorageExistsException:
Cannot create new storage 'memory:test' because it is not closed
        DB name="test"
        at com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery.before(TestBinaryRecordsQuery.java:29)

testSelectDeleteBinary on testSelectDeleteBinary(com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery)(com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery)  Time elapsed: 0.002 sec  <<< FAILURE!
com.orientechnologies.orient.core.exception.ODatabaseException:
Database 'memory:test' is closed
        DB name="test"
        at com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery.after(TestBinaryRecordsQuery.java:35)

testSelectRidBinary on testSelectRidBinary(com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery)(com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery)  Time elapsed: 0.001 sec  <<< FAILURE!
com.orientechnologies.orient.core.exception.OStorageExistsException:
Cannot create new storage 'memory:test' because it is not closed
        DB name="test"
        at com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery.before(TestBinaryRecordsQuery.java:29)

testSelectRidBinary on testSelectRidBinary(com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery)(com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery)  Time elapsed: 0.001 sec  <<< FAILURE!
com.orientechnologies.orient.core.exception.ODatabaseException:
Database 'memory:test' is closed
        DB name="test"
        at com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery.after(TestBinaryRecordsQuery.java:35)

testSelectBinary on testSelectBinary(com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery)(com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery)  Time elapsed: 0 sec  <<< FAILURE!
com.orientechnologies.orient.core.exception.OStorageExistsException:
Cannot create new storage 'memory:test' because it is not closed
        DB name="test"
        at com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery.before(TestBinaryRecordsQuery.java:29)

testSelectBinary on testSelectBinary(com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery)(com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery)  Time elapsed: 0.001 sec  <<< FAILURE!
com.orientechnologies.orient.core.exception.ODatabaseException:
Database 'memory:test' is closed
        DB name="test"
        at com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery.after(TestBinaryRecordsQuery.java:35)

testDeleteFromSelectBinary on testDeleteFromSelectBinary(com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery)(com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery)  Time elapsed: 0 sec  <<< FAILURE!
com.orientechnologies.orient.core.exception.OStorageExistsException:
Cannot create new storage 'memory:test' because it is not closed
        DB name="test"
        at com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery.before(TestBinaryRecordsQuery.java:29)

testDeleteFromSelectBinary on testDeleteFromSelectBinary(com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery)(com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery)  Time elapsed: 0 sec  <<< FAILURE!
com.orientechnologies.orient.core.exception.ODatabaseException:
Database 'memory:test' is closed
        DB name="test"
        at com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery.after(TestBinaryRecordsQuery.java:35)

testDeleteBinary on testDeleteBinary(com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery)(com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery)  Time elapsed: 0.001 sec  <<< FAILURE!
com.orientechnologies.orient.core.exception.OStorageExistsException:
Cannot create new storage 'memory:test' because it is not closed
        DB name="test"
        at com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery.before(TestBinaryRecordsQuery.java:29)

testDeleteBinary on testDeleteBinary(com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery)(com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery)  Time elapsed: 0.001 sec  <<< FAILURE!
com.orientechnologies.orient.core.exception.ODatabaseException:
Database 'memory:test' is closed
        DB name="test"
        at com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery.after(TestBinaryRecordsQuery.java:35)

Oct 04, 2016 5:42:28 PM com.orientechnologies.common.log.OLogManager log
INFO: Orient Engine is shutting down...
Oct 04, 2016 5:42:28 PM com.orientechnologies.common.log.OLogManager log
INFO: OrientDB Engine shutdown complete

Results :

Failed tests:
  HashSaltTest.testSalt:23 expected [true] but found [false]
  OSecurityManagerTest.shouldCheckPlainPasswordAgainstHashWithSalt:46 expected:<[tru]e> but was:<[fals]e>
com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery.testDeleteBinary on testDeleteBinary(com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery)(com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery)
  Run 1: TestBinaryRecordsQuery.before:29 » OStorageExists Cannot create new storage 'm...
  Run 2: TestBinaryRecordsQuery.after:35 » ODatabase Database 'memory:test' is closed
...

com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery.testDeleteFromSelectBinary on testDeleteFromSelectBinary(com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery)(com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery)
  Run 1: TestBinaryRecordsQuery.before:29 » OStorageExists Cannot create new storage 'm...
  Run 2: TestBinaryRecordsQuery.after:35 » ODatabase Database 'memory:test' is closed
...

com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery.testSelectBinary on testSelectBinary(com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery)(com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery)
  Run 1: TestBinaryRecordsQuery.before:29 » OStorageExists Cannot create new storage 'm...
  Run 2: TestBinaryRecordsQuery.after:35 » ODatabase Database 'memory:test' is closed
...

com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery.testSelectDeleteBinary on testSelectDeleteBinary(com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery)(com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery)
  Run 1: TestBinaryRecordsQuery.before:29 » OStorageExists Cannot create new storage 'm...
  Run 2: TestBinaryRecordsQuery.after:35 » ODatabase Database 'memory:test' is closed
...

com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery.testSelectRidBinary on testSelectRidBinary(com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery)(com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery)
  Run 1: TestBinaryRecordsQuery.before:29 » OStorageExists Cannot create new storage 'm...
  Run 2: TestBinaryRecordsQuery.after:35 » ODatabase Database 'memory:test' is closed
...


Tests run: 1617, Failures: 7, Errors: 0, Skipped: 6

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] OrientDB ........................................... SUCCESS [ 41.707 s]
[INFO] OrientDB Test Commons .............................. SUCCESS [ 32.124 s]
[INFO] OrientDB Core ...................................... FAILURE [03:05 min]
[INFO] OrientDB Client .................................... SKIPPED
[INFO] OrientDB Object .................................... SKIPPED
[INFO] OrientDB Tools ..................................... SKIPPED
[INFO] OrientDB Server .................................... SKIPPED
[INFO] OrientDB GraphDB ................................... SKIPPED
[INFO] OrientDB Tests ..................................... SKIPPED
[INFO] OrientDB Distributed Server ........................ SKIPPED
[INFO] OrientDB Lucene full text index .................... SKIPPED
[INFO] OrientDB JDBC Driver ............................... SKIPPED
[INFO] OrientDB ETL ....................................... SKIPPED
[INFO] OrientDB Community Distribution .................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:19 min
[INFO] Finished at: 2016-10-04T17:42:29+00:00
[INFO] Final Memory: 44M/1931M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project orientdb-core: There are test failures.
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :orientdb-core

```

**Comment by tglman** [comment] 2016-10-05 08:36
hi @yeoedward,

Strange i can build with no problem, and here it is our CI : http://helios.orientdb.com/job/orientdb-2.2.x/

**Comment by yeoedward** [comment] 2016-10-05 15:00
@tglman Thanks for checking. It builds now -- I did not set JAVA_HOME. I'm guessing it defaulted to the wrong version when building which caused hashing problems. Will test your fix and get back to you.

**Comment by yeoedward** [comment] 2016-10-05 17:26
@tglman Import now works on the 2.2.x branch. Thanks for the fix! This will be in the 2.2.12 release? Roughly when is that scheduled for?

@obi1kenobi Thanks for the help!

**Comment by obi1kenobi** [comment] 2016-10-05 19:54
@yeoedward could you check out the 2.2.11 tag and run it in the same way that you verified that import works on the 2.2.x branch? I'm asking because the 2.2.11 tag in the repo loads my data correctly even before the fix, and I want to make sure the test success isn't a side-effect of the test configuration itself.

Fingers crossed!

**Comment by yeoedward** [comment] 2016-10-05 21:43
@obi1kenobi What do you mean by test configuration? Also I'm not sure I understand, you mentioned here https://github.com/orientechnologies/orientdb/issues/6758#issuecomment-251148841 that the import didn't work on 2.2.11?

**Comment by obi1kenobi** [comment] 2016-10-05 22:22
When I test released versions (e.g. 2.2.11), I install that version of OrientDB inside a Docker container, then from inside the container I connect to it via `console.sh` and perform the test. This is how I tested 2.2.11 in #6758 when I said it fails.

However, I then cloned the OrientDB repository, and checked out the 2.2.11 tag. I then ran the server and console from the **repository** and the test succeeded. When you tested 2.2.x, I assume you did the same.

I was suggesting that you also check out the 2.2.11 tag from the **repository** and perform the same test you did in your 2.2.x run. Since the new changes @tglman made are only in 2.2.x and not at the 2.2.11 tag, the bug is only really fixed by the new changes if both:
- you don't run into the bug when running the 2.2.x database, and also
- you verify that you run into the bug when running the 2.2.11 tag *in the same manner*.
So far, I believe you only checked the first condition. I attempted to check the second condition and was not able to confirm it, which is why it would be great if you could see if you get a different result.

**Comment by yeoedward** [comment] 2016-10-05 22:31
@obi1kenobi Ah I see. I did not use docker, but I did run 2.2.x from the repository, and 2.2.10 from the distribution tarball, so there could conceivably be some subtle configuration difference that is masking the bug. I have more urgent experiments to run on OrientDB 2.2.x right now related to data corruption, but I'll add this to my queue.

**Comment by yeoedward** [comment] 2016-10-06 23:01
@obi1kenobi I am unable to build the commit tagged as the 2.2.11 release because of 5 of the 7 test failures which I posted above. Setting JAVA_HOME to point to JDK8 fixed 2 of them (the tests related to hashing). The other five were fixed when I pulled the latest 2.2.x commits, which is why I could build 2.2.x. It's probably some configuration issue with my build environment that somehow resolved with the latest commits. Sorry I'm not sure if I have the time to find the problem, but let me know if there is anything else I can help with. These are the failed tests:

```
Failed tests: 
com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery.testDeleteBinary on testDeleteBinary(com.orientechnologies.orient.core.sql.select.T
estBinaryRecordsQuery)(com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery)
  Run 1: TestBinaryRecordsQuery.before:29 » OStorageExists Cannot create new storage 'm...
  Run 2: TestBinaryRecordsQuery.after:35 » ODatabase Database 'memory:test' is closed
...

com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery.testDeleteFromSelectBinary on testDeleteFromSelectBinary(com.orientechnologies.orie
nt.core.sql.select.TestBinaryRecordsQuery)(com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery)
  Run 1: TestBinaryRecordsQuery.before:29 » OStorageExists Cannot create new storage 'm...
  Run 2: TestBinaryRecordsQuery.after:35 » ODatabase Database 'memory:test' is closed
...

com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery.testSelectBinary on testSelectBinary(com.orientechnologies.orient.core.sql.select.T
estBinaryRecordsQuery)(com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery)
  Run 1: TestBinaryRecordsQuery.before:29 » OStorageExists Cannot create new storage 'm...
  Run 2: TestBinaryRecordsQuery.after:35 » ODatabase Database 'memory:test' is closed
...

com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery.testSelectDeleteBinary on testSelectDeleteBinary(com.orientechnologies.orient.core.
sql.select.TestBinaryRecordsQuery)(com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery)
  Run 1: TestBinaryRecordsQuery.before:29 » OStorageExists Cannot create new storage 'm...
  Run 2: TestBinaryRecordsQuery.after:35 » ODatabase Database 'memory:test' is closed
...

com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery.testSelectRidBinary on testSelectRidBinary(com.orientechnologies.orient.core.sql.se
lect.TestBinaryRecordsQuery)(com.orientechnologies.orient.core.sql.select.TestBinaryRecordsQuery)
  Run 1: TestBinaryRecordsQuery.before:29 » OStorageExists Cannot create new storage 'm...
  Run 2: TestBinaryRecordsQuery.after:35 » ODatabase Database 'memory:test' is closed
...

```

**Comment by obi1kenobi** [comment] 2016-10-07 02:10
@yeoedward thanks for giving it a shot! I don't actually run the tests, so perhaps that is why I didn't run into the same issue. I simply configured my development environment to use Java 8 to start the following two classes:
- `com.orientechnologies.orient.server.OServerMain` in `orientdb-server` for the server
- `com.orientechnologies.orient.console.OConsoleDatabaseApp` in `orientdb-tools` for the console

If you have time, you might be able to do the same for your environment and bypass the failing tests. I totally understand if you have higher-priority items though.

**Comment by tglman** [comment] 2016-10-26 10:33
Hi,
the relase 2.2.12 has been done with the fix, i'll close this, reopen if you still have problems.

Bye

**Closed by tglman** 2016-10-26 10:33 UTC
Labels: bug
