### ISSUE TITLE
Orient db - shuts down automatically Reason: java.io.EOFException[Remote socket closed!] 

### ISSUE THREAD

**Issue by skonka** [orientechnologies/orientdb#6452] opened 2016-07-21 14:07 UTC
I have a distributed setup with 3 servers on 3 different hosts. I'm using the Enterprise Edition 2.1.16 on RHEL 6 with JDK 8. The orient db shuts down automatically with below error. What's the root cause?

```
2016-07-21 07:55:51:800 INFO  [XXX.XXX.XXX.XX]:5435 [cms-api-odb-clusterb] [3.5.3] Connection [Address[XXX.XXX.XXX.XX]:5435] lost. Reason: java.io.EOFException[Remote socket closed!] [TcpIpConnection]
2016-07-21 07:55:51:802 WARNI [XXX.XXX.XXX.XX]:5435 [cms-api-odb-clusterb] [3.5.3] hz._hzInstance_1_cms-api-odb-clusterb.IO.thread-in-0 Closing socket to endpoint Address[XXX.XXX.XXX.XY]:5435, Cause:java.io.EOFException: Remote socket closed! [ReadHandler]
2016-07-21 07:55:52:910 INFO  [XXX.XXX.XXX.XX]:5435 [cms-api-odb-clusterb] [3.5.3] Connecting to /XXX.XXX.XXX.XY:5435, timeout: 0, bind-any: true [SocketConnector]
```

**Comment by tglman** [comment] 2016-07-22 09:32
hi @skonka, 

the eror listed are not the cause of the shutdown they are just some failure on closing socket while the database is shutting down, this is normal if there are socket already closed, do you have any other error before this one ?

**Comment by skonka** [comment] 2016-07-22 12:55
I saw this issue today as well. Below is the complete trace.

2016-07-21 23:54:40:283 INFO  OrientDB Server v2.1.16 (build 2.1.x@r13efec7610a3eceb539db5ebfb31dea2534aa819; 2016-04-19 10:56:07+0000) is active. [OServer]
2016-07-22 04:47:37:076 INFO  [XXX.XXX.XXX.XX]:5435 [odb-clusterb] [3.5.3] Connection [Address[XXX.XXX.XXX.XZ]:5435] lost. Reason: java.io.EOFException[Remote socket closed!] [TcpIpConnection]
2016-07-22 04:47:37:077 WARNI [XXX.XXX.XXX.XX]:5435 [odb-clusterb] [3.5.3] hz._hzInstance_1_odb-clusterb.IO.thread-in-1 Closing socket to endpoint **Address[XXX.XXX.XXX.XZ]:5435, Cause:java.io.EOFException: Remote socket closed! [ReadHandler]****
2016-07-22 04:47:37:356 INFO  [XXX.XXX.XXX.XX]:5435 [odb-clusterb] [3.5.3] Connection [Address[XXX.XXX.XXX.XY]:5435] lost. Reason: java.io.EOFException[Remote socket closed!] [TcpIpConnection]
2016-07-22 04:47:37:356 WARNI [XXX.XXX.XXX.XX]:5435 [odb-clusterb] [3.5.3] hz._hzInstance_1_odb-clusterb.IO.thread-in-0 Closing socket to endpoint **Address[XXX.XXX.XXX.XY]:5435, Cause:java.io.EOFException: Remote socket closed! [ReadHandler]**
**2016-07-22 04:47:37:357 INFO  OrientDB Server is shutting down... [OServer]Exception in thread "Timer-1" com.hazelcast.core.HazelcastInstanceNotActiveException: Hazelcast instance is not active!**
        at com.hazelcast.spi.AbstractDistributedObject.getService(AbstractDistributedObject.java:93)
        at com.hazelcast.map.impl.proxy.MapProxySupport.toData(MapProxySupport.java:1143)
        at com.hazelcast.map.impl.proxy.MapProxyImpl.put(MapProxyImpl.java:95)
        at com.hazelcast.map.impl.proxy.MapProxyImpl.put(MapProxyImpl.java:87)
        at com.orientechnologies.agent.profiler.OEnterpriseProfiler$18.run(OEnterpriseProfiler.java:787)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)

**Comment by lvca** [comment] 2016-07-23 15:41
This problems come from Hazelcast. It looks like it wasn't started correctly. Can you find in the logs the reason?

**Comment by skonka** [comment] 2016-07-26 06:45
I have only the exceptions that I shared earlier. I enabled additional logging now, but did not see server going down. Even if it's hazelcast issue - where the instances are not able to synchronise, it should not bring down all the instances in the cluster down. There should be some retry or timeout configuration.

**Comment by lvca** [comment] 2016-09-01 21:04
Without a proper log it's impossible for us to determine the cause. Closing it because not reproducible. In case you have more information, please reopen/comment this. Thanks.

**Closed by lvca** 2016-09-01 21:04 UTC
