### ISSUE TITLE
SUM Aggregation issue

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientdb#5288] opened 2015-11-06 14:40 UTC
orientdb 2.1.5

I have class with a `Points` property from type `double`. When I want to aggregate my traverse path with this query.

```
begin
LET t0 = SELECT SUM(BinPoints) as Total FROM ( TRAVERSE References FROM #18:0 ) WHERE $depth = 1 AND BinaryQualified = false
commit retry 100
return [$t0]
``` 

it leads to an empty result `[]` instead to default value `value=0` because some of my vertices don't have the binaryQualified property explicit to false and cannot be matched
although they belong to the same class.

*This only takes effect in batch mode (studio and binary)*

**Comment by luigidellaquila** [comment] 2015-11-06 14:54
Hi @StarpTech 

can you provide a simple dataset (or a script to create it) to reproduce the problem? 
I'm not sure I understand the problem, if some records do not have the binaryQualified property, they should just be filtered by the WHERE condition...

Thanks

Luigi

**Comment by StarpTech** [comment] 2015-11-06 15:16
@luigidellaquila yes how can I send it to you?

**Comment by luigidellaquila** [comment] 2015-11-06 15:28
Hi @StarpTech 

it depends on how big it is, you can share a Dropbox or GoogleDrive link or you can send it via email to l dot dellaquila at orientdb.com

**Comment by StarpTech** [comment] 2015-11-06 15:43
@luigidellaquila I send you the export json file as annex

**Comment by StarpTech** [comment] 2015-11-06 20:06
@luigidellaquila  perhaps related to this https://github.com/orientechnologies/orientdb/issues/5289 ?

**Comment by StarpTech** [comment] 2015-11-06 20:07
Sry my mistake. Leave open.

**Comment by luigidellaquila** [comment] 2015-11-24 14:52
Hi @StarpTech 

from what I can see on your db, the main inner query

```
TRAVERSE References FROM #18:0 
```

just returns no results, so the outer query starts from an empty target and returns an empty result set (the ```sum()``` function is never executed)

If you execute this alone:

```
SELECT SUM(BinPoints) as Total FROM ( TRAVERSE References FROM #18:0 ) WHERE $depth = 1 AND BinaryQualified = false
``` 

you will just have no results. 

What is the expected result you expect? A zero instead?

Thanks

Luigi

**Comment by StarpTech** [comment] 2015-11-26 19:43
yes I see two issues here:

1. Studio and the binary protocal process the data differently. In Studio I get `value=0` and but in batch an empty array `[]`.
2. I expect a number when I want to process an aggregation on numbers. The default value of sum() should be a number.

**Comment by luigidellaquila** [comment] 2015-11-26 19:52
The difference from Studio and batch must be a matter of protocol implementation, I'll check it.

I think I can find a way to always return zero and make it consistent

**Comment by luigidellaquila** [comment] 2015-12-11 09:38
Hi @StarpTech 

I struggled on this issue for a while, it seems to be really complex. 
It means completely changing the execution flow of the select statement only in the particular case of sum() as a single projection

Moreover a return of zero in case of no results from the subquery will completely break backward compatibility.

I found a work-around though, you can change your query this way:

```
LET $t0 = SELECT eval("0 + $total[0].Total) LET $total = (SELECT SUM(BinPoints) as Total FROM ( TRAVERSE References FROM #18:0 ) WHERE $depth = 1 AND BinaryQualified = false)
```

This will always return an integer as a value, zero in case the subquery returns not results

I hope it helps

Thanks

Luigi

**Comment by StarpTech** [comment] 2015-12-11 14:18
@luigidellaquila thanks but this is a hack and no workaround. In my opinion it is not a feature it is bad design to return no (number) default value for a function which aggregate numbers. I still with the solution to respect a [] value as 0 in case of a SUM aggregation. 

What I dont understand is why the NOT batch command interpret this correctly? Why is the implementation so different?

**Comment by luigidellaquila** [comment] 2015-12-11 15:55
@StarpTech there is one thing I'm missing (probably I left it behind concentrating on the batch script), which is the non batch script that returns a zero?

If I do a 

```
select sum(foo) from #12:0
```
and foo just does not exist, I get no results, even in Studio

Thanks

Luigi

**Comment by StarpTech** [comment] 2015-12-11 16:07
@luigidellaquila I must correct myself no query returns a zero as value. I think this was a mistake during testing on dev and prod.

**Comment by LucaSon90** [comment] 2016-02-27 10:01
Hi @StarpTech,

could you let us know if we can close this issue ?

Thanks

**Closed** 2016-05-23 10:43 UTC
Labels: bug, waiting reply
