### ISSUE TITLE
NullPointerException when querying vertex

### ISSUE THREAD

**Issue by ylopotun** [orientechnologies/orientdb#4297] opened 2015-06-04 20:35 UTC
When we perform the following query (e.g. via console): select from 13:83 the following exception is thrown: 

2015-06-04 16:33:31,211 [OrientDB HTTP Connection /0:0:0:0:0:0:0:1:2480<-/0:0:0:0:0:0:0:1:62113] ERROR com.orientechnologies - {db=MirandaDS} Fetching error on record #13:83
java.lang.NullPointerException
	at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.deserializeFromDirectMemory(ODurablePage.java:127)
	at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiBucket.getEntry(OSBTreeBonsaiBucket.java:273)
	at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.findBucket(OSBTreeBonsaiLocal.java:1235)
	at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.loadEntriesMajor(OSBTreeBonsaiLocal.java:729)
	at com.orientechnologies.orient.core.index.sbtreebonsai.local.OSBTreeBonsaiLocal.getRealBagSize(OSBTreeBonsaiLocal.java:1335)
	at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag.updateSize(OSBTreeRidBag.java:953)
	at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OSBTreeRidBag.size(OSBTreeRidBag.java:692)
	at com.orientechnologies.orient.core.db.record.ridbag.ORidBag.size(ORidBag.java:182)
	at com.orientechnologies.common.collection.OMultiValue.getSize(OMultiValue.java:80)
	at com.orientechnologies.common.collection.OMultiValue.getFirstValue(OMultiValue.java:105)
	at com.orientechnologies.orient.core.fetch.OFetchHelper.processRecord(OFetchHelper.java:299)
	at com.orientechnologies.orient.core.fetch.OFetchHelper.fetch(OFetchHelper.java:72)
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerJSON.toString(ORecordSerializerJSON.java:338)
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerStringAbstract.toString(ORecordSerializerStringAbstract.java:668)
	at com.orientechnologies.orient.core.record.ORecordAbstract.toJSON(ORecordAbstract.java:192)
	at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.formatMultiValue(OHttpResponse.java:386)
	at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.writeRecords(OHttpResponse.java:335)
	at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.writeResult(OHttpResponse.java:231)
	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:103)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:175)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:612)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:71)

I'll send our sample DB via e-mail.

**Comment by lvca** [comment] 2015-06-04 20:57
Reproduced. The `repair database` command simply ignore the error because is not on iterator but on calling getSize() against ORidBag. Forwarded.

**Comment by laa** [comment] 2015-06-08 10:07
HI it is fixed in develop. Now we are working on tool which will restore broken edges.

**Comment by tglman** [comment] 2015-06-11 09:42
this is the same problem of : https://github.com/orientechnologies/orientdb/issues/4282 closing

**Closed by tglman** 2015-06-11 09:42 UTC
Labels: bug
