### ISSUE TITLE
Performance Issue with 2.2

### ISSUE THREAD

**Issue by rishi3195** [orientechnologies/orientdb#6276] opened 2016-06-09 13:29 UTC
## Expected behavior and actual behavior

With 2.2, performance is supposed to improve but has worsened..
I have a huge flat file with lakhs of records. I want to load same in orientDB. with 2.1.8, it used to take 4 hours but with 2.2, it was not even completed in 12 hours.
## Steps to reproduce the problem

[LoadUII.txt](https://github.com/orientechnologies/orientdb/files/306968/LoadUII.txt)
### Runninng Mode
- [x] Embedded, using PLOCAL access mode
- [ ] Embedded, using MEMORY access mode
- [ ] Remote
### Misc
- [ ] I have a distributed setup with multiple servers. How many? 
- [ ] I'm using the Enterprise Edition
### OrientDB Version
- [ ] v2.0.x - Please specify last number: 
- [x] v2.1.x - Please specify last number: 2.1.8
- [x] v2.2.x - Please specify last number: 2.2.0
### Operating System
- [x] Linux-yes
- [ ] MacOSX
- [ ] Windows
- [ ] Other Unix
- [ ] Other, name? 
### Java Version
- [ ] 6
- [ ] 7
- [x] 8-yes

**Comment by maggiolo00** [comment] 2016-06-09 13:37
hi @rishi3195 

can you share also the file or part of it?

Thanks

**Comment by rishi3195** [comment] 2016-06-09 13:55
file has 9252936  no records.
It is CSV file, with just 2 String columns
SERVICE_INSTANCE_ID,ROOT_SERVICE_INSTANCE_ID
BBEU00017258,IPSV00008878
BBEU00017290,IPSV00014566

**Comment by maggiolo00** [comment] 2016-06-09 14:00
are your you working in remote right?

**Comment by rishi3195** [comment] 2016-06-09 14:01
Yes

**Comment by maggiolo00** [comment] 2016-06-09 14:06
With the same code in 2.2. is slower?
I'm trying to run your code. i will  keep you posted

**Comment by maggiolo00** [comment] 2016-06-09 14:06
Do you have some stats of records/secs?

**Comment by maggiolo00** [comment] 2016-06-09 14:23
Do you have the same schema?
check the indexes

**Comment by rishi3195** [comment] 2016-06-10 05:00
on 2.1.8 : 25 K records/minute
2.2 : ranges from 5 minutes to 10 minutes.. as size grows larger
Schema and index are exaclty same

**Comment by laa** [comment] 2016-06-10 06:12
@rishi3195 do you use embedded database, do not you ?

**Comment by rishi3195** [comment] 2016-06-10 06:46
No.. for either version

**Comment by laa** [comment] 2016-06-10 07:06
@rishi3195 in such case to identify the problem, could you run your benchmark on embedded database too? Please do not forget to set   --XX:MaxDirectMemory:512g parameter to avoid performance slowdown.

**Comment by rishi3195** [comment] 2016-06-10 09:11
@laa if on 2.1.8 wihout embedded database its giving me 25k/minute it is supposed to improve on 2.2 and not worsen with same configuration i.e. without embedded database

**Comment by laa** [comment] 2016-06-10 09:13
@rishi3195 I am trying to understand whether problem is located inside of storage or inside of remote storage. Could you kindly help me on that ?

**Comment by rishi3195** [comment] 2016-06-10 09:17
i have already posted my code, you can create a sample DB class and give it a try at your end please

**Comment by rishi3195** [comment] 2016-06-14 07:13
any updates??

**Comment by laa** [comment] 2016-06-14 12:30
@rishi3195 once we will have a free time slot to look at the issue we will take it. Probably it will be the end of this week.

**Comment by laa** [comment] 2016-07-06 10:57
Hi @rishi3195 , I tried to reproduce your load test case.
But it is not clear for me what is under
```OrientUtils.getUDFVertex(graph, "CustomerService", "Name", cs)``` method ? 
Could you publish code for that method ?

**Comment by laa** [comment] 2016-07-08 10:30
Hi @rishi3195 could you provide such information ?

**Comment by laa** [comment] 2016-07-11 10:32
HI @rishi3195 , could you kindly provide such information ?

**Comment by rishi3195** [comment] 2016-07-11 11:40
public static Vertex getUDFVertex(OrientGraph graph, String className, String field, String value) {
		try {
			if (graph != null) {
				Iterable<Vertex> vertices = graph.getVertices(className, new String[] { field },
						new Object[] { value });
				for (Vertex vertex : vertices) {
					if (vertex != null)
						return vertex;
				}
			}
		} catch (Exception e) {
			logger.log(Level.SEVERE, "Error in OrientGraph getUDFVertex ", e);
		}
		return null;
	}

	public static Vertex getUDFVertex(OrientGraphNoTx graph, String className, String field, String value) {
		try {
			if (graph != null) {
				Iterable<Vertex> vertices = graph.getVertices(className, new String[] { field },
						new Object[] { value });
				for (Vertex vertex : vertices) {
					if (vertex != null)
						return vertex;
				}
			}
		} catch (Exception e) {
			logger.log(Level.SEVERE, "Error in OrientGraphNoTx getUDFVertex ", e);
		}
		return null;
	}

**Comment by rishi3195** [comment] 2016-10-25 06:11
any updates?

**Comment by taburet** [comment] 2016-11-23 10:28
Hi @rishi3195, sorry for such a long delay. Benchmarked a load similar to yours on 2.1.8 and latest 2.2.x, on 2.2.x it is ≈1.7 times faster, could please retest your code on it?

Also, please provide full information about your system/configuration/schema/indexes and the contents of `BBEU_try.csv` file. There may be some conner cases that are hard to reproduce w/o full information, for example the graph described by the `BBEU_try.csv` file may have very high connectivity on some vertices, that may have huge impact on the performance.

**Comment by taburet** [comment] 2016-12-07 07:07
Closing because of no reply.

**Closed by taburet** 2016-12-07 07:07 UTC
Labels: in progress, performance, storage team, waiting reply
