### ISSUE TITLE
Index cannot be created for properties with non-simplified identifier names

### ISSUE THREAD

**Issue by muneebshere** [orientechnologies/orientdb#8761] opened 2019-02-10 03:24 UTC
## Expected behavior  
It is possible to create properties with non-simplified identifier names, such as names containing spaces. Such names are surrounded by back-ticks, e.g. \`First Name\`. It should also be possible to create indexes on such properties.

## Actual behavior  
When attempting to create an index on a property which has spaces in its names, the OrientDB engine throws an exception whether or not the back-ticks are added: 
java.lang.IllegalArgumentException: Illegal field name format, should be '<property> [by key|value]' but was '\`First Name\`'

## Steps to reproduce  
CREATE VERTEX Customer
CREATE PROPERTY  Customer.\`First Name\` STRING
CREATE PROPERTY Customer.\`Last Name\` STRING
CREATE INDEX Name ON Customer( \`First Name\`, \`Last Name\` ) UNIQUE

**Comment by muneebshere** [comment] 2019-03-04 19:54
Any update? Could you replicate the issue?

**Comment by luigidellaquila** [comment] 2019-03-08 09:37
Hi @muneebshere 

I just pushed a fix, it will be released with v 3.0.18

Thanks

Luigi

**Closed** 2019-03-08 09:36 UTC

**Comment by muneebshere** [comment] 2019-03-11 07:58
Thanks.
By the way, I'm just curious, but I looked at your commit and I couldn't see exactly how the issue was resolved. Could you point out the fix to me?

**Comment by luigidellaquila** [comment] 2019-03-11 09:00
Hi @muneebshere 

The actual fix is only these ten lines of code https://github.com/orientechnologies/orientdb/commit/8de5efa93f5190be2adfd9a97d0f0a6f549b61d9#diff-66768ef3a31ffa04a5036f7d9855fb6aR87

Thanks

Luigi

**Comment by muneebshere** [comment] 2019-03-11 09:11
> Hi @muneebshere
> 
> The actual fix is only these ten lines of code [8de5efa#diff-66768ef3a31ffa04a5036f7d9855fb6aR87](https://github.com/orientechnologies/orientdb/commit/8de5efa93f5190be2adfd9a97d0f0a6f549b61d9#diff-66768ef3a31ffa04a5036f7d9855fb6aR87)
> 
> Thanks
> 
> Luigi


Yes, but how does that parse `` when it wasn't doing that before? Does it have to do with `FILED_NAME_PATTERN.split(fieldDefinition)`?

**Comment by luigidellaquila** [comment] 2019-03-11 11:02
Hi @muneebshere 

The problem is not at query parsing, it's in the index factory. There is a legacy API to create indexes by key or by value (on maps) like `Create index ... on x (theMap by key)`, and the API does a split by blank spaces. Before the fix, it just discarded all the fields with blank spaces, now it works also for them.

Thanks

Luigi
