### ISSUE TITLE
Error defining MIN value on a DATETIME property

### ISSUE THREAD

**Issue by andreyvk** [orientechnologies/orientdb#3805] opened 2015-03-25 07:54 UTC
Hi,

Im getting an error on OrientDB 2.0.5 when creating a DATETIME property with MIN value on a Studio:

![datetime-error](https://cloud.githubusercontent.com/assets/1415506/6820031/445afcc6-d2fd-11e4-8534-25970b08954b.png)

There error in the log is as follows:

``
2015-03-25 07:37:58:928 SEVERE Internal server error:
com.orientechnologies.orient.core.exception.OSchemaException: Invalid datetime format while formatting date 'Mon Mar 02 2015 00:00:00 GMT+0700 (SE Asia Standard Time)'
--> java.text.ParseException: Unparseable date: "Mon Mar 02 2015 00:00:00 GMT+0700 (SE Asia Standard Time)" [ONetworkProtocolHttpDb]
``

However, if I manually try to set the MIN value afterwards to, say, "00:00:00 03/25/2015", then it seems to work (i.e. no error is thrown), but then when I refresh the screen, value goes away:

![datetime-error2](https://cloud.githubusercontent.com/assets/1415506/6820178/679990d4-d2fe-11e4-85b9-aff50ee61ad3.png)

Also, I havent tested doing this from console. So I am not sure if the error is in database itself of just the Studio.

**Comment by mmacfadden** [comment] 2016-01-08 03:43
I can confirm that this is not just an issue with the STUDIO applications form:  Executing this query:

```SQL
DROP CLASS DateMinTest
CREATE CLASS DateMinTest
CREATE PROPERTY DateMinTest.dt DATETIME
ALTER PROPERTY DateMinTest.dt MIN DATE('2015-02-02 12:00:00')
```
or

```SQL
DROP CLASS DateMinTest
CREATE CLASS DateMinTest
CREATE PROPERTY DateMinTest.dt DATETIME
ALTER PROPERTY DateMinTest.dt MIN '2015-02-02 12:00:00'
```

Results in an exception:

 "com.orientechnologies.orient.core.exception.OSchemaException: Invalid datetime format while formatting date ''2015-02-02 12:00:00''
 --> java.text.ParseException: Unparseable date: "'2015-02-02 12:00:00'" 

If some one  the OrientDB team can let me know what the intended syntax is, then I can fix this bug.  I am trying to update the CREATE Property syntax to allow setting the MIN, MAX, and DEFAULT.  It is working, but this bug is preventing setting MIN, MAX.

Note that the following query works:

```SQL
DROP CLASS DateMinTest
CREATE CLASS DateMinTest
CREATE PROPERTY DateMinTest.dtDefault DATETIME
ALTER PROPERTY DateMinTest.dtDefault DEFAULT '2015-02-02 12:00:00'
```

The issues seems to be in the OPropertyImpl class.  The "setDefaultValueInternal" method does not check that the value itself is exactly a parsable date.  Wherease setMaxInternal and setMinInternal call checkForDateFormat.  It seems like Min and Max what the string itself to be a parseable date, whereas Default simply requires that the expression eventually can be resolved to a date / datetime.

One obvious issue is that is seems like we must "quote" the datetime string.  If we do not, then the parser will see the space between the date and time, and only parse the former.  However, when you quote the string, then the OPropertyImpl tries to parse the string  '2015-02-02 12:00:00' (containing the quotes).  The quotes cause the unparseable date issue.

Again if @lvca @luigidellaquila or some one else on the Orient team lets me know what the indented valid syntaxes are, I will fix this issue.

Thanks.

**Comment by luigidellaquila** [comment] 2016-01-15 09:17
Hi @andreyvk @mmacfadden 

IMHO for consistency the second syntax should be supported  (`ALTER PROPERTY DateMinTest.dt MIN '2015-02-02 12:00:00'`), but I like the first one as well (even more, actually)

Thanks a lot!

Luigi

**Comment by maggiolo00** [comment] 2016-06-20 15:58
Fixed in Studio develop branch

**Closed by maggiolo00** 2016-06-20 15:58 UTC
Labels: bug
