### ISSUE TITLE
Distributed coordination failure

### ISSUE THREAD

**Issue by lukeasrodgers** [orientechnologies/orientdb#5401] opened 2015-11-30 17:13 UTC
We are running two orientdb nodes (odb1 and odb2) in distributed mode and observed a confusing failure scenario recently. I know we should be running some odd number of nodes >= 3, but I don't believe that our setup was responsible for this particularly failure.

Here is my attempted recreation of what went wrong. All log messages are from odb logfiles, except for the second one below, which is from `/var/syslog`.

```
2015-11-29 01:58:45:451 - odb1 reports no response from odb2 in 120s
2015-11-29 01:59:29 prod-orientdb1 kernel: [987840.192067] INFO: task jbd2/xvda1-8:164 blocked for more than 120 seconds. 
2015-11-29 01:58:30:832 - odb2 reports no response from odb1 in 120s

odb2 spits out a bunch of hazelcast errors, seemingly related to attempting to coordinate with odb1

2015-11-29 02:01:47:475 - odb2 attempts to remove odb1 from cluster, though still gets quorum errors; continues handling requests (I believe)
2015-11-29 02:01:47:501 - odb2 updates/logs new distributed config, with itself as the only node

odb2 continues to log errors related to coordination with odb1, even though AFAICT odb1 is no longer part of its cluster, e.g. 2015-11-29 02:02:18:607 WARNI [prod-orientdb2] timeout (30001ms) on waiting for synchronous responses from nodes=[prod-orientdb2, prod-orientdb1] responsesSoFar=[prod-orientdb2] request=id=1167444 from=prod-orientdb2 task=tx [OHazelcastDistributedDatabase]

nothing happens on odb2 until 2015-11-29 02:21:26:866, when odb2 establishes a socket with odb1, then:

2015-11-29 02:24:06:359 - odb1 removes odb2 after no heartbeat for 300s
2015-11-29 02:24:06:359 - odb1 removes odb2 from cluster
2015-11-29 02:24:06:364 - odb1 gets conn attempt from odb2, which fails due to timeout
2015-11-29 02:24:07:837 - odb1 has removed odb2 from cluster
2015-11-29 02:24:14:305 - odb1 appears to be attempting to merge its cluster with odb2 cluster
2015-11-29 02:24:14:319 - odb2 re-establishes connection with odb1, adds to cluster
2015-11-29 02:24:14:319 - odb1 re-establishes connection with odb2, adds it to cluster
2015-11-29 02:24:20:317 - odb2 now logs that odb1 is part of its cluster, though it seems to have thought this all along. the new server configuration is never updated and logged, however, as it is when a node successfully joins the cluster.
2015-11-29 02:24:22:320 - odb1 believes it is merged to odb2

from here on, odb1 logs lots of errors about failure to reach quorum, detecting 1 node in timeout/conflict, and lots of these: Op: com.hazelcast.queue.impl.PollOperation@2a518de2, com.hazelcast.spi.exception.WrongTargetException: WrongTarget! this:Address[172.31.20.171]:2434, target:Address[172.31.19.146]:2434, partitionId: 226, replicaIndex: 0, operation: com.hazelcast.spi.impl.WaitNotifyServiceImpl$WaitingOp, service: hz:impl:queueService [WaitNotifyServiceImpl$WaitingOp]
odb2, meanwhile, seems to be handling requests just fine, AFAICT. it has a readquorum and writequorum of 1, so any requests *should* succeed.

2015-11-29 02:25        - this is when we start seeing lots of odb-related application errors

odb1 is manually restarted

2015-11-29 10:18:43:535 - odb2 loses connection with odb1, removes it from cluster
2015-11-29 10:18:51:191 - odb1 comes back up after restart by Jai
2015-11-29 10:18:53:414 - odb2 re-establishes connection with odb1, adds to cluster
2015-11-29 10:20:15:463 - odb1 advertises itself as back online
```

Happy to provide more details if they would be useful. Thanks.

**Comment by lvca** [comment] 2015-12-01 16:10
Could you please provide logs?

**Comment by lukeasrodgers** [comment] 2015-12-01 17:07
Sure, here are truncated logs for our two nodes for the relevant time frame. I've truncated repetitive parts, as they would otherwise add up to about 20 megs.

node 1: https://gist.github.com/lukeasrodgers/6205f83e468e4035054f (this is the one we eventually restarted)
node 2: https://gist.github.com/lukeasrodgers/142701f10e0e3b4d016b

thanks

**Comment by lvca** [comment] 2015-12-04 08:39
By reading the logs you have problems with timeout: hazelcast can't communicate to other nodes. What kind of network do you have?

**Comment by lukeasrodgers** [comment] 2015-12-04 14:09
Thanks for looking into this @lvca.

They are ec2 nodes on AWS, in general network issues are rare and transient. In any case, shouldn't hazelcast be able to recover from such issues?

**Comment by lvca** [comment] 2015-12-04 15:09
Yes, it should be able. Are you using v2.1.6? We updated HZ in that release. Also, are you using AWS auto discovering plugin?

**Comment by lukeasrodgers** [comment] 2015-12-04 15:11
Yes, we are using AWS auto-discover plugin. We just recently upgraded to 2.1.5. If possible, could you point me to the relevant changes in the HZ upgrade? We will look into upgrading shortly. Thanks.

**Comment by lvca** [comment] 2016-05-12 06:51
@lukeasrodgers it's been a while. Does the upgrade solved the problem?

**Comment by lukeasrodgers** [comment] 2016-05-12 14:14
We have not upgraded yet, and are back to running in standalone mode, which seems more stable. We are evaluating the feasibility of replacing orientdb with neo4j, and so I think we aren't putting any more efforts into upgrading orientdb unless it looks like switching to neo4j won't be possible for us.

**Comment by lvca** [comment] 2016-05-17 17:54
Closing this issue because there is no way to reproduce it. All other users on AWS don't report such problem. In case anybody is experiencing the same problem, please reopen/comment it.

**Closed by lvca** 2016-05-17 17:54 UTC
Labels: bug
