### ISSUE TITLE
OrientDB seems to be locked

### ISSUE THREAD

**Issue by thiagopm** [orientechnologies/orientdb#4645] opened 2015-07-24 22:55 UTC
Hi,

Today OrientDB Threads started to increase and after some minutes Orient stopped responding.
I wait 30 min, but as it do not stop to increase I stopped all services that uses OrientDB and I tried to stop at 4:30 pm (image below)

![seems _orientdb_locked](https://cloud.githubusercontent.com/assets/850424/8885718/962ebe08-3238-11e5-81df-2c17580c7d5a.PNG)

But OrientDB Server didn't stop (image below 2 hrs after ). 

![seems _orientdb_locked_after_2hrs](https://cloud.githubusercontent.com/assets/850424/8885807/6de65fcc-3239-11e5-86f9-af7bc0ba04c9.PNG)

If you need I can send you some dumps I got.

Do you know what is it?

Thanks

**Comment by compensator** [comment] 2015-07-25 22:14
@thiagopm Can you provide configuration details?  

I ask because I have been testing OrientDB over the past two weeks as part of a product evaluation.  Can you provide:

OrientDB Version and Edition
Execution 
Number of Vertices and Edges in the database (also which API is used to execute CRUD commands along with the type of records created - Object, Document, Graph and Lightweight vs. Full Edges)
Type and algorithm of workload against the database
Number of concurrent threads that were executing database commands
Host server configuration (CPU, RAM)
O/S and O/S Version


My tests have been with 2.0.12 Community and 2.0.13  Enterprise.   In testing the limits of the database, on a 2009 Mac Pro running OS X 10.9 with 2x4-core Xeon CPUs and 32 GB of RAM and 7200rpm disks, I generated 4 million person vertices followed by 20,000 pseudo-randomly distributed edges with a Java data generator program that uses Tinkerpop Frames for Vertex/Edge most CRUD operations.  I plan to increase the Edge count in steps between tests.  I then increased the JVM heap max from the default of 512 MB to 2 GB (I modified the values in ORIENTDB_HOME/bin/server.sh).  I then monitored the OrientDB JVM memory with Yourkit while executing a Gremlin g.V command from the Gremlin console while executing g.V in OrientDB Studio.  The server eventually used up all available heap and died with an OOME.  I increased the JVM heap max to 8GB and re-ran the two queries.  All results returned and the JVM heap grew to 3.2 GB with a max utilization of 2.2 GB.

**Comment by laa** [comment] 2015-07-27 13:46
Hi,
If you wish us to provide enough information could you provide a link to the thread dump.
We fixed similar issue in 2.0.x latest branch and I wish to check whether it is fixed.

P.S. Could you send thread dump as separate thread, do not put it inside body of comment.

**Comment by thiagopm** [comment] 2015-07-27 14:41
Hi @compensator and @laa,

I'm using a community SNAPSHOT that Andrey sent to me last week (july 22).

It's running on windows server 2012 (AWS instance server type m4.2xlarge 8CPU 32GB Memory)

Max Heap size is 4GB and Max disk cache 24GB.

Here is two dumps, the first one is when server was running and other after I tried to stop. https://s3.amazonaws.com/a-several/Dumps_20150724.7z

I'm getting more info for you, I'll send you latter.

Thanks

**Comment by laa** [comment] 2015-07-27 14:53
We have 2 of them which one is related to this issue ?

**Comment by thiagopm** [comment] 2015-07-27 15:49
Both, First one I got before I tried to stop OrientDB service. The second is after I tried to stop, then some threads had been stopped

**Comment by thiagopm** [comment] 2015-07-27 18:35
Hi,

I turn the services on again, after some time threads started to increase and I got a DEADLOCK.
Here is the dump. https://s3.amazonaws.com/a-several/threaddump-1438019262963.7z

![deadlock 20150727](https://cloud.githubusercontent.com/assets/850424/8914321/f79e287a-3474-11e5-871f-b2efc72f3651.PNG)

**Comment by compensator** [comment] 2015-07-27 20:47
Thanks for the info, @thiagopam.  I'll be watching this issue since Andrey is working it.

**Comment by laa** [comment] 2015-07-28 14:17
https://www.dropbox.com/s/xs2w59sncv9ln4m/orientdb-community-2.1-SNAPSHOT-distribution.zip?dl=0 could you try this one ?

**Comment by thiagopm** [comment] 2015-07-28 21:18
Hi Andrey,

OrientDB is working well... We just start to get this error below, but OrientDB service is working.
It seems to be something in the client. 

in the driver (client side):
<code>
Cannot write to a BufferedStream while the read buffer is not empty if the underlying stream is not seekable. Ensure that the stream underlying this BufferedStream can seek or avoid interleaving read and write operations on this BufferedStream.
   at Orient.Client.Protocol.Connection.Send(Byte[] rawData)
   at Orient.Client.Protocol.Connection.ExecuteOperationInternal(IOperation operation)
   at Orient.Client.Protocol.Connection.ExecuteOperation(IOperation operation)
   at Orient.Client.ODatabase.Query(String sql, String fetchPlan)
   at ILang.OrientDB.ILangGraphOperation.RemoveEdge(Int32 userOrganizationId, Int32 classDisciplineId, EdgeType edge)
   at ILang.Objects.Queue.Processor.ClassDisciplineStudentProcessor.ProcessQueueMessage(Object queueMessage)
</code>

in the OrientDB server:
<code>
java.net.SocketException: Socket closed
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:116)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at java.io.DataOutputStream.flush(DataOutputStream.java:123)
	at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinary.flush(OChannelBinary.java:387)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.handleConnectionError(OBinaryNetworkProtocolAbstract.java:397)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.handleConnectionError(ONetworkProtocolBinary.java:1811)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:212)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:71)
Error during closing of output stream
java.net.SocketException: Socket closed
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:116)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at java.io.DataOutputStream.flush(DataOutputStream.java:123)
	at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
	at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinary.close(OChannelBinary.java:406)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.shutdown(OBinaryNetworkProtocolAbstract.java:109)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.shutdown(ONetworkProtocolBinary.java:149)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:79)
	Suppressed: java.net.SocketException: Socket closed
		at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:116)
		at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
		at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
		at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
		at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
		at java.io.FilterOutputStream.close(FilterOutputStream.java:159)
		... 4 more
</code>

Do you know what is this?
I'll investigate here too.

Thank you

**Comment by thiagopm** [comment] 2015-07-28 23:08
Hi,

This problem happens when we turn on our Sync service, it process high number of DB write. 
After we stops the service, we stop to get this error, but seems that the threads keeps in a loop, because CPU and number of threads keeps high.

Here is the heap dump.

https://s3.amazonaws.com/a-several/heapdump-1438122505121.7z

Thanks

**Comment by laa** [comment] 2015-07-29 08:10
Hi
That is another issue relate to remote protocol.
Could you close this one and open new issue if of course you can confirm
that original issue is fixed .

ср, 29 Июл 2015, 2:08, thiagopm <notifications@github.com>:

**Comment by thiagopm** [comment] 2015-07-29 14:27
Ok Andrey...

OrientDB server in running until now with no errors, but the threads continue to consume CPU.

I created a new Issue #4678.

Thanks

**Comment by laa** [comment] 2015-07-29 17:29
OK I close issue, if you will reproduce issue feel free to reopen it.

**Closed by laa** 2015-07-29 17:29 UTC
Labels: bug, in progress
