### ISSUE TITLE
Some ClusterPositions are negative after commit if a select query is performed before

### ISSUE THREAD

**Issue by arkolesnik** [orientechnologies/orientdb#7702] opened 2017-08-31 11:25 UTC
## Expected behavior  
All clusterPositions become positive after commit.   

## Actual behavior  
Some clusterPositions remain negative after commit, if a select query is performed before (try to comment/uncomment line 128). 

## Steps to reproduce  
1. Add some number of vertexes and edges in a loop.
2. Perform some select operation inside the loop, when some vertexes and edges are added. 
3. Commit. 
4. Check vertexes clusterPositions - some of them are negative. 

Please find code example by link:
https://github.com/arkolesnik/orientdb-automation-transactions/blob/temp/src/test/java/TransactionsTest.java

Vertexes before commit: 
<img width="687" alt="before_commit" src="https://user-images.githubusercontent.com/4200801/29920991-addf28a2-8e58-11e7-9331-211723c14500.png">

Vertexes after commit: 
<img width="672" alt="after_commit" src="https://user-images.githubusercontent.com/4200801/29920996-b67a7bba-8e58-11e7-84e2-b9a2c8e24e39.png">

**Comment by tglman** [comment] 2017-09-13 17:28
Hi,

This should be already fixed in the last develop

**Comment by arkolesnik** [comment] 2017-09-15 07:41
Hi @tglman,
Still being reproduced for me.
 
(git pull and mvn clean install were done)

**Comment by tglman** [comment] 2017-09-19 14:12
Hi, 

I tried to reproduce this again with the last orientdb 3.0 snapshot, I got the "temp" branch where some assert were failing but going on debug the id where all valid, it would be cool to have an assert on the rid so we can detect directly the case.

Regards

**Comment by laa** [comment] 2017-09-19 14:19
@tglman we have one https://github.com/arkolesnik/orientdb-automation-transactions/blob/temp/src/test/java/TransactionsTest.java#L139

**Comment by laa** [comment] 2017-09-19 14:20
@tglman so you are not able to reproduce it anymore?

**Comment by tglman** [comment] 2017-12-29 12:36
Hi,

I think we can close this now.

Regards

**Closed by tglman** 2017-12-29 12:36 UTC
Labels: bug
