### ISSUE TITLE
Strange transaction (Tx) behaviour for edges created within a Tx

### ISSUE THREAD

**Issue by creisle** [orientechnologies/orientdb#8444] opened 2018-07-31 21:16 UTC
## Expected behavior  
Expected the transaction to succeed. 

## Actual behavior  
Works when not using the let statements inside a transaction. Does not work within a transaction. It appears to take issue with using the result assigned to a LET after edge creation in a subsequent statement

## Steps to reproduce  
create a new database
```
create property E.history link
create property V.history link
```
In the console attempt to perform the following transaction
```
script sql
BEGIN
    LET src = create vertex v set name = 'alice'
    LET tgt = create vertex v set name = 'bob'
    LET e1  = create edge e from $src to $tgt
    LET e2 = create edge e from $tgt to $src set history = $e1
COMMIT
end
```
you will see the following error
```
Error: com.orientechnologies.orient.core.exception.OValidationException: The field 'E.history' has been declared as LINK but the value is not a record or a record-id
	DB name="test_tx"
	DB name="test_tx"
```
However if you do the same thing without the transaction it works (18:0 is another edge and 9:0/12:0 are vertices)
```
create edge from #9:0 to #12:0 set name = 'manual second', history = #18:0 
```

**Comment by mbhulin** [comment] 2018-09-17 14:39
I have the same problem. However I get other error messages. When I run the script above with console I get this result:

orientdb> script sql
BEGIN
    LET src = create vertex v set name = 'alice'
    LET tgt = create vertex v set name = 'bob'
    LET e1  = create edge e from $src to $tgt
    LET e2 = create edge e from $tgt to $src set history = $e1
COMMIT
END
[Started multi-line command. Type just 'end' to finish and execute]

Error: java.lang.StringIndexOutOfBoundsException: String index out of range: -1

Error: java.lang.ClassCastException: com.orientechnologies.orient.core.tx.OTransactionNoTx cannot be cast to com.orientechnologies.orient.core.db.document.OTransactionOptimisticClient

Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error parsing query:

    ^
Encountered " <BEGIN> "BEGIN "" at line 1, column 1.
Was expecting one of:
    <WHILE> ...
    <IF> ...
    <FOREACH> ...
    ";" ...

        DB name="DABS_01"
        Error Code="1"
        DB name="DABS_01"

Error: com.orientechnologies.orient.core.sql.OCommandSQLParsingException: Error parsing query:

    ^
Encountered " <BEGIN> "BEGIN "" at line 1, column 1.
Was expecting one of:
    <WHILE> ...
    <IF> ...
    <FOREACH> ...
    ";" ...

        DB name="DABS_01"
        Error Code="1"
        DB name="DABS_01"
...

**Comment by luigidellaquila** [comment] 2018-09-17 15:33
Hi 

I think it's two different problems:

@mbhulin in your case you need a semicolon after each statement (I guess you are on v 3.0).

@creisle the tx problem could be related to something I fixed recentrly on v 3.0, anyway I'm checking it and I'll let you know asap

Thanks

Luigi

**Comment by mbhulin** [comment] 2018-09-17 17:12
Hi Luigi,

thank you for your answer. However I get the same error message with semicolons (I tried this first). All works fine with version 2.2.27, however I get the error mentioned above with version 3.0.7. See also issue #8419 with the same error message.

Martin

**Comment by luigidellaquila** [comment] 2018-09-18 06:48
Hi @creisle 

I found and fixed the problem, the fix is already on 3.0.x branch and will be released with v 3.0.8

Thanks

Luigi

**Comment by luigidellaquila** [comment] 2018-09-18 06:50
Hi @mbhulin 

probably the problem is with the CLI console (in Studio it seems to work fine), I'm checking it

Thanks

Luigi

**Closed** 2018-09-18 10:10 UTC
Labels: bug

**Comment by creisle** [comment] 2018-09-18 16:12
thanks @luigidellaquila!

**Comment by mbhulin** [comment] 2018-10-10 09:33
Hi Luigi,

unfortunately the error is still present in 3.0.8 when executing a SQL-script in Console. It works fine when using the batch-mode in Studio.

Martin
