### ISSUE TITLE
Exeption:  com.orientechnologies.orient.core.exception.OStorageException: File with name <> does not exist in storage

### ISSUE THREAD

**Issue by shlapkov** [orientechnologies/orientdb#4439] opened 2015-06-23 14:43 UTC
In distributed configurations with 2.0.11 on Linux host: Cent OS we are getting exception:

```
m.orientechnologies.orient.core.exception.OStorageException: File with name audit-AuditLog9_idx.irs does not exist in storage audit
INFO   | jvm 1    | 2015/06/23 10:34:55 |       at com.orientechnologies.orient.core.index.hashindex.local.cache.OWOWCache.openFile(OWOWCache.java:249) ~[orientdb-core-2.0.11.jar:2.0.11]
INFO   | jvm 1    | 2015/06/23 10:34:55 |       at com.orientechnologies.orient.core.index.hashindex.local.cache.OReadWriteDiskCache.openFile(OReadWriteDiskCache.java:159) ~[orientdb-core-2.0.11.jar:2.0.11]
INFO   | jvm 1    | 2015/06/23 10:34:55 |       at com.orientechnologies.orient.core.storage.impl.local.paginated.atomicoperations.OAtomicOperation.openFile(OAtomicOperation.java:215) ~[orientdb-core-2.0.11.jar:2.0.11]
INFO   | jvm 1    | 2015/06/23 10:34:55 |       at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OIndexRIDContainer.resolveFileIdByName(OIndexRIDContainer.java:92) ~[orientdb-core-2.0.11.jar:2.0.11]
INFO   | jvm 1    | 2015/06/23 10:34:55 |       at com.orientechnologies.orient.core.db.record.ridbag.sbtree.OIndexRIDContainer.<init>(OIndexRIDContainer.java:59) ~[orientdb-core-2.0.11.jar:2.0.11]
INFO   | jvm 1    | 2015/06/23 10:34:55 |       at com.orientechnologies.orient.core.index.OIndexMultiValues.putInSnapshot(OIndexMultiValues.java:195) ~[orientdb-core-2.0.11.jar:2.0.11]
INFO   | jvm 1    | 2015/06/23 10:34:55 |       at com.orientechnologies.orient.core.index.OIndexAbstract.applyIndexTxEntry(OIndexAbstract.java:1117) ~[orientdb-core-2.0.11.jar:2.0.11]
INFO   | jvm 1    | 2015/06/23 10:34:55 |       at com.orientechnologies.orient.core.index.OIndexAbstract.addTxOperation(OIndexAbstract.java:749) ~[orientdb-core-2.0.11.jar:2.0.11]
INFO   | jvm 1    | 2015/06/23 10:34:55 |       at com.orientechnologies.orient.core.tx.OTransactionOptimistic$CommitIndexesCallback.run(OTransactionOptimistic.java:98) ~[orientdb-core-2.0.11.jar:2.0.11]
INFO   | jvm 1    | 2015/06/23 10:34:55 |       at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:927) ~[orientdb-core-2.0.11.jar:2.0.11]
INFO   | jvm 1    | 2015/06/23 10:34:55 |       at com.orientechnologies.orient.server.distributed.ODistributedStorage.commit(ODistributedStorage.java:816) ~[orientdb-server-2.0.11.jar:2.0.11]
INFO   | jvm 1    | 2015/06/23 10:34:55 |       at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:488) ~[orientdb-core-2.0.11.jar:2.0.11]
INFO   | jvm 1    | 2015/06/23 10:34:55 |       at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:147) ~[orientdb-core-2.0.11.jar:2.0.11]
INFO   | jvm 1    | 2015/06/23 10:34:55 |       at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2430) ~[orientdb-core-2.0.11.jar:2.0.11]
INFO   | jvm 1    | 2015/06/23 10:34:55 |       at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2400) ~[orientdb-core-2.0.11.jar:2.0.11]
INFO   | jvm 1    | 2015/06/23 10:34:55 |       at com.orientechnologies.orient.server.distributed.task.OTxTask.execute(OTxTask.java:116) ~[orientdb-server-2.0.11.jar:2.0.11]
INFO   | jvm 1    | 2015/06/23 10:34:55 |       at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.executeOnLocalNode(OHazelcastPlugin.java:761) [orientdb-distributed-2.0.11.jar:2.0.11]
INFO   | jvm 1    | 2015/06/23 10:34:55 |       at com.orientechnologies.orient.server.hazelcast.ODistributedWorker.onMessage(ODistributedWorker.java:291) [orientdb-distributed-2.0.11.jar:2.0.11]
INFO   | jvm 1    | 2015/06/23 10:34:55 |       at com.orientechnologies.orient.server.hazelcast.ODistributedWorker.run(ODistributedWorker.java:121) [orientdb-distributed-2.0.11.jar:2.0.11]   However file: audit-AuditLog9_idx.irs is available in storage audit: ls -l ../app/repository/store/databases/audit/audit-AuditLog9_idx.irs
-rw-r--r--. 1 root root 1024 Jun 23 10:24 ../app/repository/store/databases/audit/audit-AuditLog9_idx.irs
```

**Comment by laa** [comment] 2015-06-24 05:39
Do you have the same issue on non distributed configuration ?

**Comment by laa** [comment] 2015-06-24 05:44
The problem of this issue is that storage is not correctly translated during explication of distributed configuration, more precisely, map  between names of files and there ids transmitted in incorrect state. As result I assign it to Luca.

**Comment by laa** [comment] 2015-06-24 05:44
The problem of this issue is that storage is not correctly translated during explication of distributed configuration, more precisely, map  between names of files and there ids transmitted in incorrect state. As result I assign it to Luca.

**Comment by laa** [comment] 2015-06-24 05:46
I will provide workaround for this, but we need real solution, current workaround will decrease ability to find bugs in code of higher level data structures.

**Comment by laa** [comment] 2015-06-24 14:02
Partially fixed.

**Comment by laa** [comment] 2015-06-24 14:02
May u try with rc5 it should be released tomorrow

**Comment by shlapkov** [comment] 2015-06-24 14:21
Can we fix it in 2.0.11 as well?

**Comment by laa** [comment] 2015-06-24 14:46
Done for both versions.

**Comment by shlapkov** [comment] 2015-06-24 15:00
Thank you, what is the plan for release 2.0.12?

**Comment by lvca** [comment] 2015-06-25 09:18
2.0.12 is scheduled on Tuesday June, 30th 2015.

**Comment by shlapkov** [comment] 2015-06-26 16:13
Issue not fixed in current dev 2.0.x branch ant might be related to: ttp://www.prjhub.com/#/issues/4633 with build from dev branch I getting:  INFO   | jvm 1    | 2015/06/26 11:41:34 | INFO  [OHazelcastPlugin] [node_vmlnxstp2_8080] class 'OUser', creation of new local cluster 'ouser_node_vmlnxstp2_8080' (id=-1)
INFO   | jvm 1    | 2015/06/26 11:41:34 | ERROR [OWOWCache] File ouser_node_vmlnxstp2_8080.pcl is not registered in 'file name - id' map but exists in file system, probably you work in distributed storage. If it is not true, please create bug in bug tracker https://github.com/orientechnologies/orientdb/issues .
INFO   | jvm 1    | 2015/06/26 11:41:34 | ERROR [OWOWCache] File ouser_node_vmlnxstp2_8080.cpm is not registered in 'file name - id' map but exists in file system, probably you work in distributed storage. If it is not true, please create bug in bug tracker https://github.com/orientechnologies/orientdb/issues .
INFO   | jvm 1    | 2015/06/26 11:41:34 | INFO  [OHazelcastPlugin] [node_vmlnxstp2_8080] class 'OUser', set mastership of cluster 'ouser_node_vmlnxstp2_8080' (id=11) to 'node_vmlnxstp2_8080'
When trying steps from 4633.

**Comment by laa** [comment] 2015-06-26 16:55
Hi, sorry but why do you think it is not fixed ?

**Comment by laa** [comment] 2015-06-26 16:56
You have log entry till we will not fix it on distributed storage level. Now we have workaround but it works. Do you still have problems during opening of file ?

**Comment by shlapkov** [comment] 2015-06-26 17:59
Once I see this exception node is stop processing transactions and require restart but yes it can be something different.

**Comment by shlapkov** [comment] 2015-06-26 18:01
It maybe the issue which I saw in: http://www.prjhub.com/#/issues/4633

**Comment by laa** [comment] 2015-07-17 05:56
According to https://github.com/orientechnologies/orientdb/issues/4590 backup mechanics does not work correctly.

**Comment by lvca** [comment] 2015-07-17 05:58
Issue #4590 was fixed. What do you mean?

**Comment by laa** [comment] 2015-07-17 05:58
It never was fixed (it has label will not fix), it is the same as current one.

**Comment by lvca** [comment] 2015-07-17 17:12
So if I understand correctly, @shlapkov was trying to restore a database on an existent database?

**Comment by laa** [comment] 2015-07-17 17:15
Yes, you are right, so previous comment is not valid. But that is related only to plocal storage.

**Comment by laa** [comment] 2015-07-17 17:15
Current issue is still valid.

**Comment by shlapkov** [comment] 2015-07-17 17:34
Use case is in http://www.prjhub.com/#/issues/4633: 1. Start node #1, Start node#2. 2. Stop node #2. 3. Start node #2.

**Comment by lvca** [comment] 2015-07-31 08:48
Hey guys, I don't understand the problem here. You cannot restore a database against an existent one. With distributed replication the database is moved under "backup" before to be restored from the network. @shlapkov please can you elaborate more the problem here?

**Comment by shlapkov** [comment] 2015-07-31 14:43
Hello @lvca I sent you the following file a month ago. Posted on github:
https://github.com/shlapkov/OrientIssues/blob/master/Orient_DB_2.0.12.docx

Please have a look. All what I did it is start node1, then node2.

**Comment by shlapkov** [comment] 2015-07-31 14:45
On "node2" I notice your "workaround" Orient DB lost track of files on "node1" exception from http://www.prjhub.com/#/issues/4633

**Comment by lvca** [comment] 2015-07-31 15:11
I'm unable to reproduce the error. Does it happen every time you start 2 nodes or under certain conditions?

**Comment by jillray7** [comment] 2015-07-31 16:05
It's reproduceable, but not everytime. He will send us better logging.

**Comment by jillray7** [comment] 2015-07-31 16:35
@shlapkov As discussed, please reproduce (perhaps by running 5 times) and send us the logging. If you have ideas as to how to reproduce, please let us know.

**Comment by shlapkov** [comment] 2015-08-04 16:38
Issue reproducible with 2.0.14-SNAPSHOT sent test applications and broken databases to @lvca via email.

**Comment by jillray7** [comment] 2015-08-04 16:51
@shlapkov thank you. @lvca Can you take a look?

**Comment by lvca** [comment] 2015-08-07 16:28
@shlapkov With last 2.0.14 I'm not able to reproduce it. I copied you "audit" and "spectrum" databases on server1, then started server1, then server2. I tried 3 times killing servers, but I've never seen that error. Are you able to reproduce with 2.0.14-SNAPSHOT? If this release is good enough I could release it as final.

**Comment by shlapkov** [comment] 2015-08-07 16:39
No issue still exist with 2.0.14-SNAPSHOT and database which i sent you. Please check my email one more time:
In attached files you can find databases in broken state. Issue consistently reproducible in this state. Steps to reproduce:

1.	Please be sure that you have databases in you ORIENTDB_HOME from attached file: servers.zip. Something like: D:\SVN\dev\tools\orientdb-cluster-test\servers\0\databases and D:\SVN\dev\tools\orientdb-cluster-test\servers\1\databases
2.	Than start OrientDBClusterReplication with the following command line: “0 2” it will start europe0. Should not be any issues database is OK.
3.	Than start OrientDBClusterReplication with the following command line: “1 2” it will start europe1 you will see error as trace bellow. Database is broken.

You may reach the broken state by running applications few times start/stop europe0, europe1 but it’s may take some time. Looks like once one of the database corrupted it is affected the whole cluster. I did not see something like this with 2.0.7.

**Comment by shlapkov** [comment] 2015-08-07 16:42
Basically there are 2 questions here:
1. Why database was broken by running this application? It make take more then 3 time to run it to reach broken state.
2. Once database broken on node 1 why it is affected node 0? Should it be just replicated across just like in your steps?

**Comment by lvca** [comment] 2015-08-07 17:28
Reproduced. The problem is that the moving of database directory doesn't work and the directory remains old, so the node is restoring a database on top of an existent directory... Working to a fix.

**Comment by lvca** [comment] 2015-08-07 17:41
Ok the problem was when OrientDB distributed cfg was run on embedded configuration. Running regular servers couldn't be reproducible. Fixed. Thanks @shlapkov for the patience.

**Closed** 2015-08-07 17:42 UTC
Labels: bug, in progress

**Comment by jillray7** [comment] 2015-08-10 15:58
@shlapkov Let us know if you have questions or comments. The fix is in the 2.0.14 snapshot.

**Comment by shlapkov** [comment] 2015-08-10 17:17
After running our application with 2.0.14-snapshot I am not able reproduce issue. Looks like fixed. Thank you.

**Comment by jillray7** [comment] 2015-08-11 08:59
@shlapkov Great!

**Comment by davseq** [comment] 2016-07-04 13:56
I'm facing what I think is very similar issue .. 

in my database residing on first node in cluster, the file **manindex.pcl** is present. 

When i start second node in cluster, the database gets copied , however, i get the following exception ..

NOTE:  EVEN if I copy the database offline into the /databases/ folder of second node and then restart, I get the same issue (it seems the file manindex.pc gets deleted  ?).

Kindly advise. 

Thanks

2016-07-04 19:08:21:209 INFO  [ODB_ravdsk070] Database copied correctly, size=3.
14MB [ODistributedAbstractPlugin$4]$ANSI{green {db=ORIENT_POLE_OD_4thJuly}} Erro
r during storage close
com.orientechnologies.orient.core.exception.OStorageException: File with name ma
nindex.pcl does not exist in storage ORIENT_POLE_OD_4thJuly
        Storage URL="plocal:D:/orientdb-community-2.2.0/databases/ORIENT_POLE_OD
_4thJuly"
        at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.openF
ile(OWOWCache.java:318)
        at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.o
penFile(O2QCache.java:195)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.O
DurableComponent.openFile(ODurableComponent.java:185)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OPagin
atedCluster.open(OPaginatedCluster.java:217)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginat
edStorage.openClusters(OAbstractPaginatedStorage.java:285)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginat
edStorage.open(OAbstractPaginatedStorage.java:208)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocal
PaginatedStorage.restore(OLocalPaginatedStorage.java:201)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.res
tore(ODatabaseDocumentTx.java:2853)
        at com.orientechnologies.orient.server.distributed.impl.ODistributedAbst
ractPlugin$9.call(ODistributedAbstractPlugin.java:1647)
        at com.orientechnologies.orient.server.distributed.impl.ODistributedAbst
ractPlugin$9.call(ODistributedAbstractPlugin.java:1636)
        at com.orientechnologies.orient.server.distributed.impl.ODistributedAbst
ractPlugin.executeInDistributedDatabaseLock(ODistributedAbstractPlugin.java:1402
)
        at com.orientechnologies.orient.server.distributed.impl.ODistributedAbst
ractPlugin.installDatabaseOnLocalNode(ODistributedAbstractPlugin.java:1636)
        at com.orientechnologies.orient.server.distributed.impl.ODistributedAbst
ractPlugin.installDatabaseFromNetwork(ODistributedAbstractPlugin.java:1279)
        at com.orientechnologies.orient.server.distributed.impl.ODistributedAbst
ractPlugin.requestDatabaseFullSync(ODistributedAbstractPlugin.java:1117)
        at com.orientechnologies.orient.server.distributed.impl.ODistributedAbst
ractPlugin.requestFullDatabase(ODistributedAbstractPlugin.java:969)
        at com.orientechnologies.orient.server.distributed.impl.ODistributedAbst
ractPlugin.installDatabase(ODistributedAbstractPlugin.java:949)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.instal
lNewDatabasesFromCluster(OHazelcastPlugin.java:853)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.startu
p(OHazelcastPlugin.java:209)
        at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.j
ava:1177)
        at com.orientechnologies.orient.server.OServer.activate(OServer.java:390
)
        at com.orientechnologies.orient.server.OServerMain.main(OServerMain.java
:41)
$ANSI{green {db=ORIENT_POLE_OD_4thJuly}} [ODB_ravdsk070] Error on starting distr
ibuted plugin
com.orientechnologies.orient.core.exception.OStorageException: Cannot open local
 storage 'D:/orientdb-community-2.2.0/databases/ORIENT_POLE_OD_4thJuly' with mod
e=rw
        Storage URL="plocal:D:/orientdb-community-2.2.0/databases/ORIENT_POLE_OD
_4thJuly"
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginat
edStorage.open(OAbstractPaginatedStorage.java:237)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocal
PaginatedStorage.restore(OLocalPaginatedStorage.java:201)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.res
tore(ODatabaseDocumentTx.java:2853)
        at com.orientechnologies.orient.server.distributed.impl.ODistributedAbst
ractPlugin$9.call(ODistributedAbstractPlugin.java:1647)
        at com.orientechnologies.orient.server.distributed.impl.ODistributedAbst
ractPlugin$9.call(ODistributedAbstractPlugin.java:1636)
        at com.orientechnologies.orient.server.distributed.impl.ODistributedAbst
ractPlugin.executeInDistributedDatabaseLock(ODistributedAbstractPlugin.java:1402
)
        at com.orientechnologies.orient.server.distributed.impl.ODistributedAbst
ractPlugin.installDatabaseOnLocalNode(ODistributedAbstractPlugin.java:1636)
        at com.orientechnologies.orient.server.distributed.impl.ODistributedAbst
ractPlugin.installDatabaseFromNetwork(ODistributedAbstractPlugin.java:1279)
        at com.orientechnologies.orient.server.distributed.impl.ODistributedAbst
ractPlugin.requestDatabaseFullSync(ODistributedAbstractPlugin.java:1117)
        at com.orientechnologies.orient.server.distributed.impl.ODistributedAbst
ractPlugin.requestFullDatabase(ODistributedAbstractPlugin.java:969)
        at com.orientechnologies.orient.server.distributed.impl.ODistributedAbst
ractPlugin.installDatabase(ODistributedAbstractPlugin.java:949)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.instal
lNewDatabasesFromCluster(OHazelcastPlugin.java:853)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.startu
p(OHazelcastPlugin.java:209)
        at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.j
ava:1177)
        at com.orientechnologies.orient.server.OServer.activate(OServer.java:390
)
        at com.orientechnologies.orient.server.OServerMain.main(OServerMain.java
:41)
Caused by: com.orientechnologies.orient.core.exception.OStorageException: File w
ith name manindex.pcl does not exist in storage ORIENT_POLE_OD_4thJuly
        Storage URL="plocal:D:/orientdb-community-2.2.0/databases/ORIENT_POLE_OD
_4thJuly"
        at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.openF
ile(OWOWCache.java:318)
        at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.o
penFile(O2QCache.java:195)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.O
DurableComponent.openFile(ODurableComponent.java:185)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OPagin
atedCluster.open(OPaginatedCluster.java:217)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginat
edStorage.openClusters(OAbstractPaginatedStorage.java:285)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginat
edStorage.open(OAbstractPaginatedStorage.java:208)
        ... 15 more
Exception in thread "main" com.orientechnologies.orient.server.distributed.ODist
ributedStartupException: Error on starting distributed plugin
        at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.startu
p(OHazelcastPlugin.java:238)
        at com.orientechnologies.orient.server.OServer.registerPlugins(OServer.j
ava:1177)
        at com.orientechnologies.orient.server.OServer.activate(OServer.java:390
)
        at com.orientechnologies.orient.server.OServerMain.main(OServerMain.java
:41)
Caused by: com.orientechnologies.orient.core.exception.OStorageException: Cannot
 open local storage 'D:/orientdb-community-2.2.0/databases/ORIENT_POLE_OD_4thJul
y' with mode=rw
        Storage URL="plocal:D:/orientdb-community-2.2.0/databases/ORIENT_POLE_OD
_4thJuly"
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginat
edStorage.open(OAbstractPaginatedStorage.java:237)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OLocal
PaginatedStorage.restore(OLocalPaginatedStorage.java:201)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.res
tore(ODatabaseDocumentTx.java:2853)
        at com.orientechnologies.orient.server.distributed.impl.ODistributedAbst
ractPlugin$9.call(ODistributedAbstractPlugin.java:1647)
        at com.orientechnologies.orient.server.distributed.impl.ODistributedAbst
ractPlugin$9.call(ODistributedAbstractPlugin.java:1636)
        at com.orientechnologies.orient.server.distributed.impl.ODistributedAbst
ractPlugin.executeInDistributedDatabaseLock(ODistributedAbstractPlugin.java:1402
)
        at com.orientechnologies.orient.server.distributed.impl.ODistributedAbst
ractPlugin.installDatabaseOnLocalNode(ODistributedAbstractPlugin.java:1636)
        at com.orientechnologies.orient.server.distributed.impl.ODistributedAbst
ractPlugin.installDatabaseFromNetwork(ODistributedAbstractPlugin.java:1279)
        at com.orientechnologies.orient.server.distributed.impl.ODistributedAbst
ractPlugin.requestDatabaseFullSync(ODistributedAbstractPlugin.java:1117)
        at com.orientechnologies.orient.server.distributed.impl.ODistributedAbst
ractPlugin.requestFullDatabase(ODistributedAbstractPlugin.java:969)
        at com.orientechnologies.orient.server.distributed.impl.ODistributedAbst
ractPlugin.installDatabase(ODistributedAbstractPlugin.java:949)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.instal
lNewDatabasesFromCluster(OHazelcastPlugin.java:853)
        at com.orientechnologies.orient.server.hazelcast.OHazelcastPlugin.startu
p(OHazelcastPlugin.java:209)
        ... 3 more
Caused by: com.orientechnologies.orient.core.exception.OStorageException: File w
ith name manindex.pcl does not exist in storage ORIENT_POLE_OD_4thJuly
        Storage URL="plocal:D:/orientdb-community-2.2.0/databases/ORIENT_POLE_OD
_4thJuly"
        at com.orientechnologies.orient.core.storage.cache.local.OWOWCache.openF
ile(OWOWCache.java:318)
        at com.orientechnologies.orient.core.storage.cache.local.twoq.O2QCache.o
penFile(O2QCache.java:195)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.O
DurableComponent.openFile(ODurableComponent.java:185)
        at com.orientechnologies.orient.core.storage.impl.local.paginated.OPagin
atedCluster.open(OPaginatedCluster.java:217)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginat
edStorage.openClusters(OAbstractPaginatedStorage.java:285)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginat
edStorage.open(OAbstractPaginatedStorage.java:208)
        ... 15 more

**Comment by nishantkumar1292** [comment] 2017-07-11 09:05
`Exception during index 'product.id' creation com.orientechnologies.orient.core.exception.OStorageException: File with given name already exists but has different id 65 vs. proposed 5678089963816616111`
      `DB name="db_development"`

Getting the above exception when creating an index over an integer field. The index was earlier there. I removed the field and recreated it.
Is there a way to override the constraints in the file. Am I missing something?

**Comment by laa** [comment] 2017-07-11 10:17
@nishantkumar1292 what version do you use? I suppose that is a binary compatibility problem.  The simplest is just to give the index a different name, do you have any reasons to keep exactly the same name? I am looking forward though to fix this issue, is it possible for you to share a version of database and database itself?

**Comment by nishantkumar1292** [comment] 2017-07-11 11:58
@laa **Version**: 2.2.21
I am just using the command `CREATE INDEX product.id NOTUNIQUE`. I haven't given it any name. Assuming it must be using some default name. No reason to keep the same name.
We are using internal company data, so I am sorry the database cannot be shared.

**Comment by laa** [comment] 2017-07-11 12:16
@nishantkumar1292 you can use command ```CREATE INDEX product_id ON product (id) NOTUNIQUE``` it should solve your problem. But I will really appreciate if you send me your database for investigation so I will fix an issue and you will not have similar problems in future.
