### ISSUE TITLE
named parameters not working in let block

### ISSUE THREAD

**Issue by mudigal** [orientechnologies/orientdb#4538] opened 2015-07-09 10:54 UTC
A Query like 

'SELECT FROM ABC 
LET $x = (SELECT FROM XYZ WHERE x = :named)
WHERE y.contains($x)'

here where in pass the map of named parameters i do not get any results, where in I should be getting some.

While debugging found out that OCommandExecutorSQLResultsetAbstract::assignLetClauses() makes a call to query method without passing the parameters.

LINE details here:
varValue = ODatabaseRecordThreadLocal.INSTANCE.get().query(subQuery);

while it should have been 
varValue = ODatabaseRecordThreadLocal.INSTANCE.get().query(subQuery, getParameters());

**Comment by nagarajasr** [comment] 2015-07-09 13:59
Which version of OrientDB ?
If you are using any of the 2.1-rc's, try changing the "=" to "in" as follows:

```sql
SELECT FROM ABC 
LET $x in (SELECT FROM XYZ WHERE x = :named)
WHERE y.contains($x)
```

see this issue #4530

**Comment by nagarajasr** [comment] 2015-07-09 14:07
Which version of OrientDB?
Does the query return the correct results if you do not use a named parameter?
Can you post a test case to reproduce the issue?

**Comment by nagarajasr** [comment] 2015-07-09 14:17
i made some assumptions about your schema and changed the query in OrientDB console to this, and it returns a result (where the original query did not return any). I am not using named parameters. I am trying to see if there is actually an issue with named parameters and let clause, or if it is simply the query formulation.

```sql
    create class ABC
    create class XYZ
    insert into XYZ set x = 10
    insert into ABC set y=[10,20,30]
    select from ABC let $x = (select x from XYZ where x=10) where y in $x
----+------+----
#   |@CLASS|$x
----+------+----
0   |null  |[1]
----+------+----

```

can you try this query with the named parameter and check if it works?

**Comment by luigidellaquila** [comment] 2015-07-10 11:08
Hi @mudigal 

it should be already fixed in 2.1, could you please confirm?

Thanks

**Comment by luigidellaquila** [comment] 2015-07-10 11:16
no, you are right, I reproduced the problem in 2.1
Fixing it right now.

**Comment by luigidellaquila** [comment] 2015-07-10 11:21
fixed in develop branch and added test case

**Closed by luigidellaquila** 2015-07-10 11:21 UTC

**Comment by Fraternel** [comment] 2017-02-17 10:31
Hello!

Are you sure that fix has been committed because I upgraded OrientDB to 2.2.16 and this issue is still reproducible.

So in the previous query `LET $x = (SELECT FROM XYZ WHERE x = :named)` named parameter is not inserted and you have no result.

Furthermore if I invoke a function (groovy/js/...) in let block it raised an exception like:
`Caused by: com.orientechnologies.common.exception.OSystemException: org.codehaus.groovy.runtime.InvokerInvocationException: groovy.lang.MissingMethodException: No signature of method: java.util.Date.parse() is applicable for argument types: (java.lang.String, com.orientechnologies.orient.core.sql.filter.OSQLFilterItemParameter) values: [yyyy-MM-dd HH:mm:ss, ::startDate]`
* here my named parameter is 'startDate' and my function (groovy) expects a string date-time value.

**Comment by luigidellaquila** [comment] 2017-02-17 10:40
Hi @Fraternel 

I have a test case for this in 2.2.x branch, it was definitely committed.
Could you please check if you have strictSql flag set to true?

Thanks

Luigi

**Comment by Fraternel** [comment] 2017-02-17 10:44
Yes I test again with a freshly created database and **it only happens when strictSql is disabled**.

**Comment by luigidellaquila** [comment] 2017-02-17 10:47
Ok, this explains the problem.

StrictSQL flag is intended only to enable (setting it to false) legacy behavior, but it's strongly suggested to leave it to true because it fixes a lot of parsing/execution issues. One of the issues is specifically about parameter binding.

I'm sorry, this won't be fixed, I'm afraid you have to keep strictSql=true to use parameters in subqueries

Thanks

Luigi

**Comment by Fraternel** [comment] 2017-02-17 10:55
Sure I understand. I will see for a workaround in non-strictSql mode for aliases (i.e.: `AS 'my-alias'`) but it's another topic! Best regards.
