### ISSUE TITLE
DEPTH_FIRST vs BREADTH_FIRST different total number of records returned

### ISSUE THREAD

**Issue by misu200** [orientechnologies/orientdb#5914] opened 2016-03-31 15:47 UTC
Same TRAVERSE query (different strategy)
traverse \* from (select \* from Firma where cui="4829576")  while $depth <=4 (strategy BREADTH_FIRST)

First result(DEPTH_FIRST..the default):
"Query executed in 3.738 sec. Returned 1172 record(s). Limit: 2000"

Second result(BREADTH_FIRST):
'Query executed in 4.475 sec. Returned 1261 record(s). Limit: 2000'

It looks to me like a bug returning different number of records here ....

**Comment by misu200** [comment] 2016-03-31 22:23
using MAXDEPTH keyword:
traverse * from (select * from Firma where cui="4829576")  maxdepth 4 strategy BREADTH_FIRST
"Query executed in 4.045 sec. Returned 1335 record(s). Limit: 2000 (change it)"

**Comment by luigidellaquila** [comment] 2016-04-01 06:56
Hi @misu200 

Can you share a dataset to reproduce the problem? It would make the fix procedure faster

Thanks

Luigi

**Comment by luigidellaquila** [comment] 2017-02-20 10:11
Hi @misu200 

I was not able to reproduce this.
Is this still valid? Any chance to have a valid dataset to reproduce the problem?

Thanks

Luigi

**Comment by santo-it** [comment] 2017-04-07 23:26
Hi @misu200,

Thanks for opening this issue. As Luigi wrote we weren't able to reproduce it. No database or further info on how to reproduce it were provided.

I am closing this issue now with label "cannot reproduce". If you see this problem again please feel free to comment

Many Thanks,

**Closed by santo-it** 2017-04-07 23:26 UTC
Labels: cannot replicate, waiting reply
