### ISSUE TITLE
Importing relational databases with Teleporter

### ISSUE THREAD

**Issue by zhangshusheng** [orientechnologies/orientdb#7467] opened 2017-06-02 06:47 UTC
## Expected behavior  
Import relational database into OrientDB with the Teleporter .

## Actual behavior  
Here is part of the import configuration file.
{
    "edges": [{
        "live": {
            "mapping": {
                "fromTable": "customer",
                "fromColumns": ["c_current_addr_sk"],
                "toTable": "customer_address",
                "toColumns": ["ca_address_sk"],
                "direction": "direct"
            }
        },
	"person_stastics": {
            "mapping": {
                "fromTable": "customer",
                "fromColumns": ["c_current_cdemo_sk"],
                "toTable": "customer_demographics",
                "toColumns": ["cd_demo_sk"],
                "direction": "direct"
            }
        },
	"house_stastics": {
            "mapping": {
                "fromTable": "customer",
                "fromColumns": ["c_current_hdemo_sk"],
                "toTable": "household_demographics",
                "toColumns": ["hd_demo_sk"],
                "direction": "direct"
            }
        },
	"income_stastics": {
            "mapping": {
                "fromTable": "household_demographics",
                "fromColumns": ["hd_income_band_sk"],
                "toTable": "income_band",
                "toColumns": ["ib_income_band_sk"],
                "direction": "direct"
            }
        },
        ......
}  

## Steps to reproduce  
In the import configuration file, there are many edge classes configured. But, it creates only one edge class -"live" when importing executed. 
Why does it happens? Is the import configuration file any problem?

**Comment by G4br13l3** [comment] 2017-06-02 10:22
Hi @zhangshusheng, can you kindly provide me the full configuration and a log?
Are you using Teleporter through the script or via studio? In both cases, can you choose debug level logging and send me the output please?

Thanks,

Gabriele

**Comment by zhangshusheng** [comment] 2017-06-03 14:45
Thanks, G4br1313.
I used Teleporter through the script, as follows:
`./oteleporter.sh -jdriver mysql -jurl jdbc:mysql://192.168.101.95:3306/bigbench 
-juser root -jpasswd mysql -ourl plocal:/opt/orientdb/databases/bigbenchgraph
-s naive -nr original -v 2 -conf /opt/data/migration-config.json`
Using debug level, it shows only 'live' edge was built. And all vertex type classes are normal.

**Comment by KishoDai** [comment] 2017-06-05 01:03
Hi @zhangshusheng,
    I also tried to use teleporter, but finally I choose to write my teleporter because my business is more complex.

**Comment by G4br13l3** [comment] 2017-06-05 06:58
@zhangshusheng can you send me the full log please, maybe something goes wrong during the input config applying. 

Thanks.

**Comment by zhangshusheng** [comment] 2017-06-06 12:16
@G4br13l3  I use debug level, the import information shows on console but no log file can be found. 
How to get the import log file ?  
Thanks.

**Comment by G4br13l3** [comment] 2017-06-07 15:44
My wrong @zhangshusheng, the old version 2.2.x of Teleporter is not updated. We are investing in the configuration for the importing in the next version 3.0.x. We will provide also a basic GUI in order to make the configuration very quick and very user-friendly (no more JSON editing). We should release in the next 2-3 weeks the M2 for orientdb 3.0.x, and the new Teleporter and the new GUI will be included.
So if you can wait some time, then you can try again with the new version of the tool.
I will let you know when M2 will be released. 

Thanks.

**Comment by zhangshusheng** [comment] 2017-06-09 08:20
Hi @G4br13l3 , the import log shows as follows (critical part).
First, in the 'Source DB Schema building' step, log content shows
------------------------------ DB SCHEMA DESCRIPTION ------------------------------

Product name: MySQL	Product version: 5.7.17
Major version: 5	Minor Version: 7
Driver major version: 5	Driver minor version: 1

Number of Entities: 23.
Number of Relationship: 0.
...
It shows that no relation was built.

Second, in the 'Graph Model building' step, log content shows
------------------------------ MODEL GRAPH DESCRIPTION ------------------------------

Number of Vertex-type: 23.
Number of Edge-type: 0.
...
It shows that no edge-type to built.

Third, int the 'OrientDB Schema writing' step, log content shows
Writing edge-types on OrientDB Schema...

Writing 'live' edge-type  (1/1)...

Edge-type 'live' wrote.
...

Finally, when the 'OrientDB importing' step completed, log content shows
SUMMARY

Source DB Schema
Entities: 23
Relationships: 1

OrientDB Schema
Vertex Type: 23
Edge Type: 1
Indexes: 23

OrientDB Importing
Analyzed Records: 22286667/27138794
Added Vertices on OrientDB: 20100574
Updated Vertices on OrientDB: 0
Added Edges on OrientDB: 99000

There is only one edge type was built. But, edges set in the configuration file more than one.
Why is this happening?

Thanks.

**Comment by G4br13l3** [comment] 2017-06-09 09:40
Hi @zhangshusheng, as you said there's a problem with the configuration applying. According to the log I guess you don't have any foreign key defined in your source database, so in the starting models mapping we have 0 relationships and 0 edge types. 
Then after the config is applied, we just have a relationship with the correspondent edge type (the first one defined as far as I can see). 
Of course all the other edges/relationhips reported in the config are ignored, we have to find out why this is happening. 
Maybe I can do something more if you share the whole config. Let me know. 

Thanks, 
Gabriele

**Comment by G4br13l3** [comment] 2017-06-09 09:41
Hi @zhangshusheng, as you said there's a problem with the configuration applying. According to the log I guess you don't have any foreign key defined in your source database, so in the starting models mapping we have 0 relationships and 0 edge types. 
Then after the config is applied, we just have a relationship with the correspondent edge type (the first one defined as far as I can see). 
Of course all the other edges/relationhips reported in the config are ignored, we have to find out why this is happening. 
Maybe I can do something more if you share the whole config. Let me know. 

Thanks, 

Gabriele

**Comment by zhangshusheng** [comment] 2017-06-10 08:40
Thanks, @G4br13l3 .
The source DB I used is generated from BigBench test dataset, which consist of 23 tables. The dataset doesn't define foreign key constraints, but there are foreign key references between tables.
The configuration file is too long, and just show some of it. As follows,
`"edges": [{
        "live": {
            "mapping": {
                "fromTable": "customer",
                "fromColumns": ["c_current_addr_sk"],
                "toTable": "customer_address",
                "toColumns": ["ca_address_sk"],
                "direction": "direct"
            }
        },
		"person_statistics": {
            "mapping": {
                "fromTable": "customer",
                "fromColumns": ["c_current_cdemo_sk"],
                "toTable": "customer_demographics",
                "toColumns": ["cd_demo_sk"],
                "direction": "direct"
            }
        },
		"house_statistics": {
            "mapping": {
                "fromTable": "customer",
                "fromColumns": ["c_current_hdemo_sk"],
                "toTable": "household_demographics",
                "toColumns": ["hd_demo_sk"],
                "direction": "direct"
            }
        },
		"income_statistics": {
            "mapping": {
                "fromTable": "household_demographics",
                "fromColumns": ["hd_income_band_sk"],
                "toTable": "income_band",
                "toColumns": ["ib_income_band_sk"],
                "direction": "direct"
            }
        },
		"price_item": {
            "mapping": {
                "fromTable": "item_marketprices",
                "fromColumns": ["imp_item_sk"],
                "toTable": "item",
                "toColumns": ["i_item_sk"],
                "direction": "direct"
            }
        },
        ...`

The rest is the edge setting also, similar to the above.

Maybe you are right, I will define foreign key constrains in source DB.
Thanks.

**Comment by G4br13l3** [comment] 2017-06-12 14:27
Hi @zhangshusheng, Teleporter should work also without foreign key if a configuration is provided like in your case, so this is a bug. If you want have a "quick" workaround yes, you can define the foreign keys in the source database till I will reproduce the bug. 

Thanks for the patience, 

Gabriele

**Comment by zhangshusheng** [comment] 2017-06-13 09:14
Thanks, @G4br13l3 .
I defined foreign key constrains in source DB, which is  an effective method .
The edge type can be built as configured.
Thank you very much.

shusheng

**Comment by G4br13l3** [comment] 2017-06-13 09:37
I am really glad to know this, btw I would be grateful if you can share with me your database (or just the schema), in this way I can quickly reproduce the issue. Let me know. 

Many thanks,

Gabriele

**Comment by zhangshusheng** [comment] 2017-06-14 09:24
The datasets generated by the BigBench - a benchmark for big data analytics. Then imports the datasets into a MySQL database. This is the database I used.

Thanks.

Shusheng

**Comment by zhangshusheng** [comment] 2017-06-21 07:40
Hi @G4br13l3 , The time is too long using Teleporter to import relational databases. There are 49 edges configured in the file.

**Comment by G4br13l3** [comment] 2017-06-21 08:19
Hi @zhangshusheng, we are working on a visual tool for this reason! ;)
I will notify you when it will be ready, so if you want you can try it out. 

Thanks, 

Gabriele

**Comment by zhangshusheng** [comment] 2017-06-22 00:46
Ok, I will try.

Thanks,

Shusheng

**Comment by G4br13l3** [comment] 2017-07-21 13:17
Hi Shusheng, you can find the visual tool in orientdb 2.2.24, both in CE and EE (but in CE you can't synch your database). Now you can define your relationships in a very easy way! ;)
I'm closing this thread, please reopen it if you need something more. 

Thanks. 

Gabriele

**Closed by G4br13l3** 2017-07-21 13:17 UTC

**Comment by zhangshusheng** [comment] 2017-08-01 07:45
@G4br13l3 , thank you .
