### ISSUE TITLE
Configuration on distributed mode

### ISSUE THREAD

**Issue by vitorenesduarte** [orientechnologies/orientdb#3572] opened 2015-02-12 11:25 UTC
Hi,

I've read [this link](http://www.orientechnologies.com/docs/last/orientdb.wiki/Distributed-Configuration.html#load-balancing) but I can't figure out how to do the __load balancing__.

I have two orientdb servers (started with __./dserver.sh__) (2424 and 2425) running on my machine (just for testing purposes). 
In the client, each database connection comes form:
```java
url = "remote:localhost/Demo";
pool = new OPartitionedDatabasePool(url, user, password);
...
pool.acquire();
```
But, for what I understand, this will only query against 2424.

How can I configure the load balancing?
Thank you,

**Comment by 8forty** [comment] 2015-02-12 16:57
That link's title is misleading, instead of **load balancing** it really only explains (and should be re-titled) how to setup **automatic client fail-over** from one server to another using a DNS trick.  

In your case orient's recommendation is usually [Sharding](http://www.orientechnologies.com/docs/last/orientdb.wiki/Distributed-Sharding.html).  You might also use a software load-balancer like [Zen Load Balancer](http://www.zenloadbalancer.com/) or [HAProxy](http://www.haproxy.org/)

**Comment by vitorenesduarte** [comment] 2015-02-12 17:10
Hi @8forty.
Can you provide an example for my case using orient's recommendation? 
Thanks,

**Comment by 8forty** [comment] 2015-02-12 17:33
I don't have an example using sharding, we decided for our project to simply use multiple identical orient servers on multiple machines, each ingesting all of the data.  This provides high-availability and fault-tolerance, and for load balancing our clients just randomly choose which one to connect to.

**Comment by vitorenesduarte** [comment] 2015-02-12 17:44
Thanks @8forty. I see you opened an issue (#3575). It would be great to have more documentation about this.

If you have __n__ machines, that means you have __n__ pools (like my example above), and the client chooses a pool randomly?
It's a good load balancing? Since on machine might be overloaded and still be chosed.

**Comment by 8forty** [comment] 2015-02-12 18:07
Yeah, it's not really a very good load balancing scheme in general but works well in our use-case since we are almost never overloaded by clients.  I think HAProxy (for example) has features that let it monitor the load of the servers it's balancing and choose the one with the lightest load.

**Comment by vitorenesduarte** [comment] 2015-02-12 18:11
Thanks again! :+1:

**Comment by lvca** [comment] 2015-04-04 15:12
Duplicate of: #3165

**Closed by lvca** 2015-04-04 15:12 UTC
Labels: distributed, duplicate, enhancement, question
