### ISSUE TITLE
Cannot create edge with new vertices in the same transaction

### ISSUE THREAD

**Issue by crossknight** [orientechnologies/orientdb#7534] opened 2017-07-07 01:44 UTC
## Expected behavior
Commit with these commands successfully via binary protocol (version 2.2.4)  
BEGIN;
CREATE VERTEX V SET num = 13
CREATE VERTEX V SET num = 14
CREATE EDGE E FROM (SELECT FROM V WHERE num = 13) TO (SELECT FROM V WHERE num = 14)
COMMIT;

## Actual behavior  
Commit failed
com.orientechnologies.orient.core.exception.OCommandExecutionException: No edge has been created because no source vertices

## Steps to reproduce  
Send commands
BEGIN;
CREATE VERTEX V SET num = 13
CREATE VERTEX V SET num = 14
CREATE EDGE E FROM (SELECT FROM V WHERE num = 13) TO (SELECT FROM V WHERE num = 14)
COMMIT;
via binary protocol (request command script "s", script language "SQL")

**Comment by maggiolo00** [comment] 2017-07-07 06:59
hi @crossknight 

do you have a script to reproduce it?

I just tried to run that batch script with orientjs against 2.2.22 and it worked.

Thanks

**Comment by crossknight** [comment] 2017-07-07 07:49
Umm,, Sorry, It's a test case from my unit test so I don't have a script to reproduce it.
I sent a message as binary via socket like this

Message (Show as string for easily read) 
4194s1771s3SQLBEGIN;\nCREATE VERTEX V SET num = 13\nCREATE VERTEX V SET num = 14\nCREATE EDGE E FROM (SELECT FROM V WHERE num = 13) TO (SELECT FROM V WHERE num = 14)\nCOMMIT;

Message description
41 - ORD_REQUEST_COMMAND
94 - SSID
s - ORD_DEFAULT_MODE_REQUEST_COMMAND
177 - payload length
1 - ORD_CLASSNAME_REQUEST_COMMAND_SCRIPT length
s - ORD_CLASSNAME_REQUEST_COMMAND_SCRIPT
3 - ORD_DEFAULT_SCRIPT_LANGUAGE lengh
SQL - ORD_DEFAULT_SCRIPT_LANGUAGE
BEGIN;\nCREATE VERTEX V SET num = 13\nCREATE VERTEX V SET num = 14\nCREATE EDGE E FROM (SELECT FROM V WHERE num = 13) TO (SELECT FROM V WHERE num = 14)\nCOMMIT; - commands

Tell me if I do something wrong, Thank you

**Comment by maggiolo00** [comment] 2017-07-07 07:52
hi @crossknight 

are you using any drivers? or just writing over the binary protocol?

which version of OrientDB exactly?

**Comment by crossknight** [comment] 2017-07-07 07:56
I just writing over the binary protocol. version of OrientDB is 2.2.22

**Comment by maggiolo00** [comment] 2017-07-07 08:00
hi @crossknight 

are you sending parameters in the batch script or only the plain text batch?

**Comment by crossknight** [comment] 2017-07-07 08:10
I'm not sure.
What is the batch script or only the plain text batch?
I followed instruction from this link
http://orientdb.com/docs/2.2.x/Network-Binary-Protocol.html
to generate binary command.

**Comment by maggiolo00** [comment] 2017-07-07 08:19
From here

http://orientdb.com/docs/2.2.x/Network-Binary-Protocol-Commands.html#script

are you sending only the text or also the parameters?

**Comment by crossknight** [comment] 2017-07-07 08:24
I sending only the text.

**Comment by maggiolo00** [comment] 2017-07-07 08:34
@crossknight 

that is strange i was not able to reproduce it via studio with batch and with
orientjs driver. Did you try with Studio in Batch Mode?

**Comment by crossknight** [comment] 2017-07-07 08:35
Can you try this?
[
![screen shot 2017-07-07 at 3 30 01 pm](https://user-images.githubusercontent.com/736201/27949952-caf65c6c-6329-11e7-9710-4fa57ed4b8e0.png)
](url)

**Comment by maggiolo00** [comment] 2017-07-07 08:43
hi @crossknight 


<img width="1275" alt="screen shot 2017-07-07 at 10 40 01" src="https://user-images.githubusercontent.com/98812/27950272-f669f2b0-6300-11e7-9455-63bb0977f906.png">

Is that a fresh db? 

if not can you provide this db, so i can try to reproduce it?

**Comment by crossknight** [comment] 2017-07-07 08:49
I changed to fresh new db and it works fine.
Do you need the problem db for checking?

**Comment by maggiolo00** [comment] 2017-07-07 08:50
Sure

you can send it to me here if it's small e.risa@orientdb.com

**Comment by crossknight** [comment] 2017-07-07 08:57
I sent you an email with the problem db.
Thank you for your help.

**Comment by crossknight** [comment] 2017-07-07 09:27
I found the command that cause this problem.
I used this command on new db.
CREATE VERTEX V SET num = 10;

then these following commands will be failed
BEGIN;
CREATE VERTEX V SET num = 13;
CREATE VERTEX V SET num = 14;
CREATE EDGE E FROM (SELECT FROM V WHERE num = 13) TO (SELECT FROM V WHERE num = 14);
COMMIT;

**Comment by maggiolo00** [comment] 2017-07-07 10:17
ok Thanks

**Comment by luigidellaquila** [comment] 2017-07-10 08:44
Hi @crossknight 

I pushed a fix for this a couple of days ago, the fix will be released with 2.2.23 in a few hours

Thanks

Luigi

**Closed by luigidellaquila** 2017-07-10 08:44 UTC
Labels: bug
