### ISSUE TITLE
Error deserializing record

### ISSUE THREAD

**Issue by vitorenesduarte** [orientechnologies/orientdb#3550] opened 2015-02-08 18:25 UTC
```bash
orientdb {db=Demo}> delete vertex #18:771545                                                

2015-02-08 18:21:59:012 WARNING {db=Demo} Error deserializing record AAxTZWFyY2gOcGljdHVyZQAAAGIHEmV2ZW50RGF0ZQAAAHgGCGRhdGEAAAB+BxBmZWF0dXJlcwAAHjcHFmluX1NlYXJjaGVzAAAefxYcb3V0X1NlYXJjaFBvc3QAAB6OFgAqd3d3LmV4YW1wbGUuY29tL3guanBnxsDk6uZS7nZ7ImN1cnJlbmN5IjoiRVVSIiwibWluUHJpY2UiOjE1MjAsIm1heFByaWNlIjoxNjM3LCJyZXN1bHRzIjpbeyJpZCI6IjItNTk0NDAiLCJ0eXBlIjoiQ2F0YWxvZ3VlUHJvZHVjdCIsIm5hbWUiOiJQcm9kdWN0IG5hbWUgIzAiLCJjYXRlZ29yeSI6WyJSb290IiwiTGVhZiJdLCJicmFuZCI6IkJyYW5kIiwiZGVzY3JpcHRpb24iOiJQcm9kdWN0IGRlc2NyaXB0aW9uIiwicHJvdmlkZXIiOiJQcm92aWRlciIsIm1lcmNoYW50IjoiTWVyY2hhbnQiLCJwaWN0dXJlIjp7InVybCI6Ind3dy5leGFtcGxlLmNvbS94LmpwZyIsIndpZHRoIjozMDAsImhlaWdodCI6NDAwfSwicHJvZHVjdFVybCI6Imh0dHA6Ly93d3cuZXhhbXBsZS5jb20vIiwicmV0YWlsUHJpY2UiOjc0NSwiY3VycmVuY3kiOiJFVVIiLCJpc1JlY29tbWVuZGVkIjpmYWxzZSwic2NvcmUiOjEuMH0seyJpZCI6IjItMTE3Mzk4IiwidHlwZSI6IkNhdGFsb2d1ZVByb2R1Y3QiLCJuYW1lIjoiUHJvZHVjdCBuYW1lICMxIiwiY2F0ZWdvcnkiOlsiUm9vdCIsIkxlYWYiXSwiYnJhbmQiOiJCcmFuZCIsImRlc2NyaXB0aW9uIjoiUHJvZHVjdCBkZXNjcmlwdGlvbiIsInByb3ZpZGVyIjoiUHJvdmlkZXIiLCJtZXJjaGFudCI6Ik1lcmNoYW50IiwicGljdHVyZSI6eyJ1cmwiOiJ3d3cuZXhhbXBsZS5jb20veC5qcGciLCJ3aWR0aCI6MzAwLCJoZWlnaHQiOjQwMH0sInByb2R1Y3RVcmwiOiJodHRwOi8vd3d3LmV4YW1wbGUuY29tLyIsInJldGFpbFByaWNlIjoxMDg5LCJjdXJyZW5jeSI6IkVVUiIsImlzUmVjb21tZW5kZWQiOmZhbHNlLCJzY29yZSI6MS4wfSx7ImlkIjoiMS01MDk1MCIsInR5cGUiOiJDYXRhbG9ndWVQcm9kdWN0IiwibmFtZSI6IlByb2R1Y3QgbmFtZSAjMiIsImNhdGVnb3J5IjpbIlJvb3QiLCJMZWFmIl0sImJyYW5kIjoiQnJhbmQiLCJkZXNjcmlwdGlvbiI6IlByb2R1Y3QgZGVzY3JpcHRpb24iLCJwcm92aWRlciI6IlByb3ZpZGVyIiwibWVyY2hhbnQiOiJNZXJjaGFudCIsInBpY3R1cmUiOnsidXJsIjoid3d3LmV4YW1wbGUuY29tL3guanBnIiwid2lkdGgiOjMwMCwiaGVpZ2h0Ijo0MDB9LCJwcm9kdWN0VXJsIjoiaHR0cDovL3d3dy5leGFtcGxlLmNvbS8iLCJyZXRhaWxQcmljZSI6MTYyMSwiY3VycmVuY3kiOiJFVVIiLCJpc1JlY29tbWVuZGVkIjpmYWxzZSwic2NvcmUiOjEuMH0seyJpZCI6IjEtOTU3NzQiLCJ0eXBlIjoiQ2F0YWxvZ3VlUHJvZHVjdCIsIm5hbWUiOiJQcm9kdWN0IG5hbWUgIzMiLCJjYXRlZ29yeSI6WyJSb290IiwiTGVhZiJdLCJicmFuZCI6IkJyYW5kIiwiZGVzY3JpcHRpb24iOiJQcm9kdWN0IGRlc2NyaXB0aW9uIiwicHJvdmlkZXIiOiJQcm92aWRlciIsIm1lcmNoYW50IjoiTWVyY2hhbnQiLCJwaWN0dXJlIjp7InVybCI6Ind3dy5leGFtcGxlLmNvbS94LmpwZyIsIndpZHRoIjozMDAsImhlaWdodCI6NDAwfSwicHJvZHVjdFVybCI6Imh0dHA6Ly93d3cuZXhhbXBsZS5jb20vIiwicmV0YWlsUHJpY2UiOjE2MTIsImN1cnJlbmN5IjoiRVVSIiwiaXNSZWNvbW1lbmRlZCI6ZmFsc2UsInNjb3JlIjoxLjB9LHsiaWQiOiIzLTE0NDczNiIsInR5cGUiOiJDYXRhbG9ndWVQcm9kdWN0IiwibmFtZSI6IlByb2R1Y3QgbmFtZSAjNCIsImNhdGVnb3J5IjpbIlJvb3QiLCJMZWFmIl0sImJyYW5kIjoiQnJhbmQiLCJkZXNjcmlwdGlvbiI6IlByb2R1Y3QgZGVzY3JpcHRpb24iLCJwcm92aWRlciI6IlByb3ZpZGVyIiwibWVyY2hhbnQiOiJNZXJjaGFudCIsInBpY3R1cmUiOnsidXJsIjoid3d3LmV4YW1wbGUuY29tL3guanBnIiwid2lkdGgiOjMwMCwiaGVpZ2h0Ijo0MDB9LCJwcm9kdWN0VXJsIjoiaHR0cDovL3d3dy5leGFtcGxlLmNvbS8iLCJyZXRhaWxQcmljZSI6MTYwMywiY3VycmVuY3kiOiJFVVIiLCJpc1JlY29tbWVuZGVkIjpmYWxzZSwic2NvcmUiOjEuMH0seyJpZCI6IjItMTIwNTQzIiwidHlwZSI6IkNhdGFsb2d1ZVByb2R1Y3QiLCJuYW1lIjoiUHJvZHVjdCBuYW1lICM1IiwiY2F0ZWdvcnkiOlsiUm9vdCIsIkxlYWYiXSwiYnJhbmQiOiJCcmFuZCIsImRlc2NyaXB0aW9uIjoiUHJvZHVjdCBkZXNjcmlwdGlvbiIsInByb3ZpZGVyIjoiUHJvdmlkZXIiLCJtZXJjaGFudCI6Ik1lcmNoYW50IiwicGljdHVyZSI6eyJ1cmwiOiJ3d3cuZXhhbXBsZS5jb20veC5qcGciLCJ3aWR0aCI6MzAwLCJoZWlnaHQiOjQwMH0sInByb2R1Y3RVcmwiOiJodHRwOi8vd3d3LmV4YW1wbGUuY29tLyIsInJldGFpbFByaWNlIjoyNDksImN1cnJlbmN5IjoiRVVSIiwiaXNSZWNvbW1lbmRlZCI6ZmFsc2UsInNjb3JlIjoxLjB9LHsiaWQiOiIzLTQxODc3IiwidHlwZSI6IkNhdGFsb2d1ZVByb2R1Y3QiLCJuYW1lIjoiUHJvZHVjdCBuYW1lICM2IiwiY2F0ZWdvcnkiOlsiUm9vdCIsIkxlYWYiXSwiYnJhbmQiOiJCcmFuZCIsImRlc2NyaXB0aW9uIjoiUHJvZHVjdCBkZXNjcmlwdGlvbiIsInByb3ZpZGVyIjoiUHJvdmlkZXIiLCJtZXJjaGFudCI6Ik1lcmNoYW50IiwicGljdHVyZSI6eyJ1cmwiOiJ3d3cuZXhhbXBsZS5jb20veC5qcGciLCJ3aWR0aCI6MzAwLCJoZWlnaHQiOjQwMH0sInByb2R1Y3RVcmwiOiJodHRwOi8vd3d3LmV4YW1wbGUuY29tLyIsInJldGFpbFByaWNlIjo4NTYsImN1cnJlbmN5IjoiRVVSIiwiaXNSZWNvbW1lbmRlZCI6ZmFsc2UsInNjb3JlIjoxLjB9LHsiaWQiOiIxLTM4NTA4IiwidHlwZSI6IkNhdGFsb2d1ZVByb2R1Y3QiLCJuYW1lIjoiUHJvZHVjdCBuYW1lICM3IiwiY2F0ZWdvcnkiOlsiUm9vdCIsIkxlYWYiXSwiYnJhbmQiOiJCcmFuZCIsImRlc2NyaXB0aW9uIjoiUHJvZHVjdCBkZXNjcmlwdGlvbiIsInByb3ZpZGVyIjoiUHJvdmlkZXIiLCJtZXJjaGFudCI6Ik1lcmNoYW50IiwicGljdHVyZSI6eyJ1cmwiOiJ3d3cuZXhhbXBsZS5jb20veC5qcGciLCJ3aWR0aCI6MzAwLCJoZWlnaHQiOjQwMH0sInByb2R1Y3RVcmwiOiJodHRwOi8vd3d3LmV4YW1wbGUuY29tLyIsInJldGFpbFByaWNlIjo2MTcsImN1cnJlbmN5IjoiRVVSIiwiaXNSZWNvbW1lbmRlZCI6ZmFsc2UsInNjb3JlIjoxLjB9LHsiaWQiOiIzLTk4MzQ2IiwidHlwZSI6IkNhdGFsb2d1ZVByb2R1Y3QiLCJuYW1lIjoiUHJvZHVjdCBuYW1lICM4IiwiY2F0ZWdvcnkiOlsiUm9vdCIsIkxlYWYiXSwiYnJhbmQiOiJCcmFuZCIsImRlc2NyaXB0aW9uIjoiUHJvZHVjdCBkZXNjcmlwdGlvbiIsInByb3ZpZGVyIjoiUHJvdmlkZXIiLCJtZXJjaGFudCI6Ik1lcmNoYW50IiwicGljdHVyZSI6eyJ1cmwiOiJ3d3cuZXhhbXBsZS5jb20veC5qcGciLCJ3aWR0aCI6MzAwLCJoZWlnaHQiOjQwMH0sInByb2R1Y3RVcmwiOiJodHRwOi8vd3d3LmV4YW1wbGUuY29tLyIsInJldGFpbFByaWNlIjoxMjI5LCJjdXJyZW5jeSI6IkVVUiIsImlzUmVjb21tZW5kZWQiOmZhbHNlLCJzY29yZSI6MS4wfSx7ImlkIjoiMy02ODY1MCIsInR5cGUiOiJDYXRhbG9ndWVQcm9kdWN0IiwibmFtZSI6IlByb2R1Y3QgbmFtZSAjOSIsImNhdGVnb3J5IjpbIlJvb3QiLCJMZWFmIl0sImJyYW5kIjoiQnJhbmQiLCJkZXNjcmlwdGlvbiI6IlByb2R1Y3QgZGVzY3JpcHRpb24iLCJwcm92aWRlciI6IlByb3ZpZGVyIiwibWVyY2hhbnQiOiJNZXJjaGFudCIsInBpY3R1cmUiOnsidXJsIjoid3d3LmV4YW1wbGUuY29tL3guanBnIiwid2lkdGgiOjMwMCwiaGVpZ2h0Ijo0MDB9LCJwcm9kdWN0VXJsIjoiaHR0cDovL3d3dy5leGFtcGxlLmNvbS8iLCJyZXRhaWxQcmljZSI6MTEyOSwiY3VycmVuY3kiOiJFVVIiLCJpc1JlY29tbWVuZGVkIjpmYWxzZSwic2NvcmUiOjEuMH0seyJpZCI6IjEtODE0NjkiLCJ0eXBlIjoiQ2F0YWxvZ3VlUHJvZHVjdCIsIm5hbWUiOiJQcm9kdWN0IG5hbWUgIzEwIiwiY2F0ZWdvcnkiOlsiUm9vdCIsIkxlYWYiXSwiYnJhbmQiOiJCcmFuZCIsImRlc2NyaXB0aW9uIjoiUHJvZHVjdCBkZXNjcmlwdGlvbiIsInByb3ZpZGVyIjoiUHJvdmlkZXIiLCJtZXJjaGFudCI6Ik1lcmNoYW50IiwicGljdHVyZSI6eyJ1cmwiOiJ3d3cuZXhhbXBsZS5jb20veC5qcGciLCJ3aWR0aCI6MzAwLCJoZWlnaHQiOjQwMH0sInByb2R1Y3RVcmwiOiJodHRwOi8vd3d3LmV4YW1wbGUuY29tLyIsInJldGFpbFByaWNlIjo0MTcsImN1cnJlbmN5IjoiRVVSIiwiaXNSZWNvbW1lbmRlZCI6ZmFsc2UsInNjb3JlIjoxLjB9LHsiaWQiOiIzLTQ0Mzk2IiwidHlwZSI6IkNhdGFsb2d1ZVByb2R1Y3QiLCJuYW1lIjoiUHJvZHVjdCBuYW1lICMxMSIsImNhdGVnb3J5IjpbIlJvb3QiLCJMZWFmIl0sImJyYW5kIjoiQnJhbmQiLCJkZXNjcmlwdGlvbiI6IlByb2R1Y3QgZGVzY3JpcHRpb24iLCJwcm92aWRlciI6IlByb3ZpZGVyIiwibWVyY2hhbnQiOiJNZXJjaGFudCIsInBpY3R1cmUiOnsidXJsIjoid3d3LmV4YW1wbGUuY29tL3guanBnIiwid2lkdGgiOjMwMCwiaGVpZ2h0Ijo0MDB9LCJwcm9kdWN0VXJsIjoiaHR0cDovL3d3dy5leGFtcGxlLmNvbS8iLCJyZXRhaWxQcmljZSI6MTM5NiwiY3VycmVuY3kiOiJFVVIiLCJpc1JlY29tbWVuZGVkIjpmYWxzZSwic2NvcmUiOjEuMH0seyJpZCI6IjItMTI1MzYzIiwidHlwZSI6IkNhdGFsb2d1ZVByb2R1Y3QiLCJuYW1lIjoiUHJvZHVjdCBuYW1lICMxMiIsImNhdGVnb3J5IjpbIlJvb3QiLCJMZWFmIl0sImJyYW5kIjoiQnJhbmQiLCJkZXNjcmlwdGlvbiI6IlByb2R1Y3QgZGVzY3JpcHRpb24iLCJwcm92aWRlciI6IlByb3ZpZGVyIiwibWVyY2hhbnQiOiJNZXJjaGFudCIsInBpY3R1cmUiOnsidXJsIjoid3d3LmV4YW1wbGUuY29tL3guanBnIiwid2lkdGgiOjMwMCwiaGVpZ2h0Ijo0MDB9LCJwcm9kdWN0VXJsIjoiaHR0cDovL3d3dy5leGFtcGxlLmM= send this data for debugging [ORecordSerializerBinary]
Error: com.orientechnologies.orient.core.exception.OCommandExecutionException: Error on execution of command: sql.delete vertex #18:771545

Error: java.lang.StringIndexOutOfBoundsException: String index out of range: 7735
```

**Comment by tglman** [comment] 2015-02-10 16:04
hi @vitorenesduarte i was trying to undestand the problem, do you still have the database with this problem ?
will help a lot have the whole database, if is possible

**Comment by vitorenesduarte** [comment] 2015-02-10 18:34
It's 17gb. Maybe compressed below 1gb. Where can I send it?

**Comment by tglman** [comment] 2015-02-11 13:02
put in any public cloud, dropbox or whatever you have ;)
and just send an email with the details to support@orientechnologies.com, don't forget to mention this issue on the mail to not get it lost ;)

Thank you

**Comment by vitorenesduarte** [comment] 2015-02-11 15:46
Done (:

**Comment by tglman** [comment] 2015-02-13 16:19
hi @vitorenesduarte 

I analized  your db and i was able to read that record properly, with some internal workaround, i would like to know if it happen sometime that the db was killed while was activlily used for write?

I couldn't do a flow to reproduce this issue, do you have any tips on that ?

**Comment by vitorenesduarte** [comment] 2015-02-13 16:33
I'm not sure I understood. If I open that database now and select from that record I'll have the WARNING described above.

I can't reproduce it either. It was a db for testing purposes, and I might have killed it while the tests were running, I'm not sure. If that's the reason, sorry for the time lost.

**Comment by tglman** [comment] 2015-02-13 16:59
@vitorenesduarte ok, tnks for the info, it's very probable that this warning come out because the database was killed, anyway also if is not critical for you i'll investigate a bit more, we want to be 100% safe also if you unplug the electricity.

**Comment by vitorenesduarte** [comment] 2015-02-20 07:19
@tglman Can you tell you can I read the record properly too?

**Comment by tglman** [comment] 2015-02-23 11:33
Hi @vitorenesduarte,

Is not so easy, you need get in the low level layer of the database,  but i can provide a fixed db if you need it.

**Comment by vitorenesduarte** [comment] 2015-02-24 09:19
Hi @tglman. Thank you for you availability.
But if this happens in production I would like to be able to recover the database as fast as possible. Is there a recovery tool, or maybe some tutorial I can follow?

**Comment by tglman** [comment] 2015-02-24 15:14
Hi @vitorenesduarte 

For this specific error there is not a standard procedure implemented yet.
we have a procedure called "repair database" that you can run from the console and if something goes wrong.

don't forget that for a database in production you should do regular backup.

by the way in the 2.0.3 we have included a couple of fix for a potential cause(https://github.com/orientechnologies/orientdb/commit/65a01dbb21a64ef5387cf2f729d27538a0162e4d,https://github.com/orientechnologies/orientdb/commit/1ed166739067dbc636f572f7101c66c616de7b93)

bacause i couldn't find a flow to reproduce this exact problem i'll leave this open for a while to collect more info, but this could be already fixed in 2.0.3

**Comment by tglman** [comment] 2015-04-01 15:08
no more report on this, closing

**Closed by tglman** 2015-04-01 15:08 UTC
Labels: bug, invalid

**Comment by vitorenesduarte** [comment] 2015-04-01 16:24
Thanks @tglman :)
