### ISSUE TITLE
after continuously pushing data to the database, orientdb eat all the memory. Same as #4807 

### ISSUE THREAD

**Issue by mingio** [orientechnologies/orientdb#6142] opened 2016-05-14 15:25 UTC
Same as #4807, we use in production. But I notice the #4807 didn't be solved.
Maybe I am the second man meet the same issue.
We have two clients continuously pushing data to the database.
The memory increase continuously.
Finally, the jvm crashed.
There is 16GB memory in machine, 64bit Ubuntu 14.04.

### Runninng Mode
-  Remote

### OrientDB Version
-  v2.1.15 - Please specify last number: 

### Operating System
-  Linux

### Java Version
-  8

**Comment by mingio** [comment] 2016-05-15 00:35
Sorry, I have to correct the information.
When orientdb eat all the memory, I have 8G ram in machine.
The command line of orientdb is: 
/mnt/data/jre1.8.0_91/bin/java -server -Xmx2400m -Xms2400m -XX:+PerfDisableSharedMem -Djna.nosys=true -XX:+HeapDumpOnOutOfMemoryError -Djava.awt.headless=true -Dfile.encoding=UTF8 -Drhino.opt.level=9 -Dprofiler.enabled=true -Dstorage.diskCache.bufferSize=3600 -Djava.util.logging.config.file=/mnt/data/orientdb/config/orientdb-server-log.properties -Dorientdb.config.file=/mnt/data/orientdb/config/orientdb-server-config.xml -Dorientdb.www.path=/mnt/data/orientdb/www -Dorientdb.build.number=2.1.x@r; 2015-10-29 16:54:25+0000 -cp /mnt/data/orientdb/lib/orientdb-server-2.1.5.jar:/mnt/data/orientdb/lib/* com.orientechnologies.orient.server.OServerMain

So I increase the memory up to 16G ram from yesterday.
I'll follow this to check whether the issue can take place.

**Comment by laa** [comment] 2016-05-15 07:48
Hi , we have already  have solution for given issue . Please use following  JVM settings `-XX:+UseLargePages -XX:LargePageSizeInBytes=2m` . Looking forward  for your feedback.

**Comment by mingio** [comment] 2016-05-15 10:07
Ok, I'll try it today.

**Comment by mingio** [comment] 2016-05-17 01:14
Hi, after used new JVM settings -XX:+UseLargePages -XX:LargePageSizeInBytes=2m,
the memory of orientdb can always be limited below 10GB.
I run the orientdb 2 days. 
I use the command 'top' to monitor the status.
The VIRT is about 10GB and the RES is about 7.8GB.
And the VIRT didn't eat more memory again.

**Comment by laa** [comment] 2016-05-17 03:45
HI @mingio ,
So we can close the issue ?

On Tue, May 17, 2016 at 4:14 AM mingio <notifications@github.com> wrote:

> Hi, after used new JVM settings -XX:+UseLargePages
> -XX:LargePageSizeInBytes=2m,
> the memory of orientdb can always be limited below 10GB.
> I run the orientdb 2 days.
> I use the command 'top' to monitor the status.
> The VIRT is about 10GB and the RES is about 7.8GB.
> And the VIRT didn't eat more memory again.
>
> —
> You are receiving this because you were assigned.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/6142#issuecomment-219593982>
>
-- 
Best regards,
Andrey Lomakin, R&D lead.
OrientDB Ltd

twitter: @Andrey_Lomakin
linkedin: https://ua.linkedin.com/in/andreylomakin
blogger: http://andreylomakin.blogspot.com/

**Comment by laa** [comment] 2016-05-17 04:21
That is duplicate of https://github.com/orientechnologies/orientdb/issues/5720

**Comment by mingio** [comment] 2016-05-18 15:01
Hi, 5 days， the memory keep increasing. The os has only 200M left.
Result of top command:
top - 22:55:47 up 5 days,  7:06,  2 users,  load average: 0.26, 0.15, 0.14
Tasks: 136 total,   1 running, 135 sleeping,   0 stopped,   0 zombie
%Cpu(s):  3.7 us,  2.2 sy,  0.0 ni, 81.8 id, 11.5 wa,  0.7 hi,  0.0 si,  0.2 st
KiB Mem:  16433080 total, 16183996 used,   249084 free,   167436 buffers
KiB Swap:        0 total,        0 used,        0 free.  4659520 cached Mem

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                 
24064 root      20   0 11.967g 9.909g   7292 S  10.6 63.2 132:21.74 java

**Comment by laa** [comment] 2016-05-23 08:14
Hi @mingio , in 2.2 we have created our own allocator to avoid this issue. Could you try it ?

**Comment by mingio** [comment] 2016-05-24 02:58
Ok, I will try 2.2. Wait for my feedback.

**Comment by laa** [comment] 2016-05-27 07:49
Hi @mingio , any updates on this topic ?

**Comment by mingio** [comment] 2016-05-29 09:52
Hi, I think the issue has been resolved in 2.2.
The memory used can be limited. 
Result has been attached.
[orientdb2.2_test.docx](https://github.com/orientechnologies/orientdb/files/288269/orientdb2.2_test.docx)

**Comment by laa** [comment] 2016-05-31 05:18
@mingio cool. I close issue then

**Closed by laa** 2016-05-31 05:18 UTC
Labels: storage team
