### ISSUE TITLE
All Orient DB 2.1.15 threads are locked up for long periods of time

### ISSUE THREAD

**Issue by jamieb22** [orientechnologies/orientdb#6126] opened 2016-05-12 13:28 UTC
java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.tryLock(long, TimeUnit) ReentrantReadWriteLock.java:871
com.orientechnologies.common.concur.resource.OSharedResourceAdaptive.acquireSharedLock() OSharedResourceAdaptive.java:142
com.orientechnologies.common.concur.resource.OSharedResourceAdaptiveExternal.acquireSharedLock() OSharedResourceAdaptiveExternal.java:44
com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(OCluster, ORecordId) OAbstractPaginatedStorage.java:1748
com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.readRecord(ORecordId, String, boolean, ORecordCallback) OAbstractPaginatedStorage.java:780
com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx$SimpleRecordReader.readRecord(OStorage, ORecordId, String, boolean, ORecordVersion) ODatabaseDocumentTx.java:3092
com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ORecordId, ORecord, ORecordVersion, String, boolean, boolean, boolean, OStorage$LOCKING_STRATEGY, ODatabaseDocumentTx$RecordReader) ODatabaseDocumentTx.java:1820
com.orientechnologies.orient.core.tx.OTransactionOptimistic.loadRecord(ORID, ORecord, String, boolean, boolean, boolean, OStorage$LOCKING_STRATEGY) OTransactionOptimistic.java:243
com.orientechnologies.orient.core.tx.OTransactionOptimistic.loadRecord(ORID, ORecord, String, boolean, boolean, OStorage$LOCKING_STRATEGY) OTransactionOptimistic.java:217
com.orientechnologies.orient.core.tx.OTransactionOptimistic.loadRecord(ORID, ORecord, String, boolean) OTransactionOptimistic.java:347
com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ORID) ODatabaseDocumentTx.java:1564
com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ORID) ODatabaseDocumentTx.java:122
com.orientechnologies.orient.core.id.ORecordId.getRecord() ORecordId.java:324
com.tinkerpop.blueprints.impls.orient.OrientElementIterator.next() OrientElementIterator.java:62
com.tinkerpop.blueprints.impls.orient.OrientElementIterator.next() OrientElementIterator.java:35
com.stimulus.archiva.database.blueprints.BluePrintDatabase.f(Database$ItemType, Database$IndexedProperty, String) MailArchiva:383
com.stimulus.archiva.database.blueprints.BluePrintDatabase.d(Database$ItemType, String) MailArchiva:367
com.stimulus.archiva.database.blueprints.BluePrintDatabase.c(Database$ItemType, String) MailArchiva:594

**Comment by laa** [comment] 2016-05-12 13:34
@jamieb22 you have already created the similar issue, what is a difference with this one ?

**Comment by laa** [comment] 2016-05-12 13:38
@jamieb22 well I see what is difference ))

**Comment by jamieb22** [comment] 2016-05-12 13:38
Sorry It must be a duplicate issue. You can close it. Sorry for bother.

**Comment by laa** [comment] 2016-05-12 13:38
@jamieb22 no, that may be different

**Comment by laa** [comment] 2016-05-12 13:39
@jamieb22 what is version do you use ?

**Comment by laa** [comment] 2016-05-12 13:41
@jamieb22 sorry for misunderstanding we will reach you soon for details.

**Comment by jamieb22** [comment] 2016-05-12 13:41
The version in question is 2.1.15. I have just upgraded to 2.1.16 in the 
hope that it will resolve.

There were eight long running threads, spending most their time locked 
up for days in the method in question.

**Comment by laa** [comment] 2016-05-12 13:48
@jamieb22 could you send full thread dump as gist ?

**Comment by jamieb22** [comment] 2016-05-12 13:50
Sorry, it was on a production server. I've already upgraded the server, 
deleted the logs and restarted the server.

**Comment by laa** [comment] 2016-05-12 13:51
let's wait for new one if happens, could you send full thread dump ?

**Comment by jamieb22** [comment] 2016-05-12 13:54
Sure...I thought this dump should be enough. It has line numbers and 
everything. What about is are you missing?

**Comment by laa** [comment] 2016-05-12 13:56
@jamieb22 that is only one thread I need full thread picture.
Or even better small yourkit snapshot for last 2-3 minutes.

**Comment by jamieb22** [comment] 2016-05-12 14:08
I'll see what I can do. I noticed you marked as performance issue. This 
seemed like a bug to me, as the threads were completely jammed.

**Comment by laa** [comment] 2016-05-12 14:27
@jamieb22 If it will be confirmed as deadlock I will change the label. We need to find the root cause to decide what type of problem it is.

**Comment by laa** [comment] 2016-05-24 08:15
Hi @jamieb22 any updates ?

**Comment by laa** [comment] 2016-06-10 05:23
Close it as duplication

**Closed by laa** 2016-06-10 05:23 UTC
Labels: performance, storage team, waiting reply
