### ISSUE TITLE
[Bug] Java Api .command(query) result in a temporary RID

### ISSUE THREAD

**Issue by matanshukry** [orientechnologies/orientdb#8949] opened 2019-07-08 14:24 UTC
## Expected behavior
The result of a create query will include a positive (real) RID

## Actual behavior  
The result of a create query includes a negative (temporary) RID

## Steps to reproduce  
```
// ODatabase session = ... // obtain a session to the database
OResultSet result = session.command("CREATE VERTEX User SET name=\"bla1\"");
// RID: result.next().getRecord().get().getIdentity()
```

**Comment by wolf4ood** [comment] 2019-07-08 14:27
Hi @matanshukry 

did you begun a transaction before the command?

`session.begin()`;

Thanks

**Comment by matanshukry** [comment] 2019-07-08 15:39
@wolf4ood Yup. Also doing .commit() after, but that's after I'm getting the recordid anyway.

**Comment by wolf4ood** [comment] 2019-07-08 16:43
Hi @matanshukry 

this works for me

```
@Test
  public void testTx() {

    OrientDB orientDB = new OrientDB("embedded:", OrientDBConfig.defaultConfig());

    orientDB.createIfNotExists("test", ODatabaseType.MEMORY);

    ODatabaseSession database = orientDB.open("test", "admin", "admin");

    database.begin();

    OVertex vertex;

    try (OResultSet resultSet = database.command("create vertex V set name = 'Test'")) {
      vertex = resultSet.next().getVertex().get();
    }

    database.commit();

    Assert.assertTrue(vertex.getIdentity().isPersistent());

  }
```

you should get the identity after the commit, since new records in tx have temporary rids

Let me know if this helps

Thanks

**Comment by matanshukry** [comment] 2019-07-09 06:50
@wolf4ood I am getting the identity before the .commit(), which seems to be issue. Although I'm using breakpoints, and although I'm getting a temporary identity at that point, if I'll query the database using another session/console, I can see the new row with a persistent identity. Hence it exist, so why can't I access it?


Also, my current flow, which I believe is a common flow, is to convert the result of a db operation immediately when I have the result. Hence:
(1) session.begin()
(2) userA = findUserBy..(...)
(3) userB = createUser..(..)
(4) session.commit()

where each method such as findUserBy/createUser would go something like this:
(1) OResult result = session.command(query, args)
(2) User user = convertFromDb(result);

**Comment by matanshukry** [comment] 2019-07-09 08:15
@wolf4ood Actually, it seems it doesn't work after the .commit() either. What I tried after your comment:

(1) session.begin()
(2) OResult result = session.command(query, args);
(3) this.user = convertResultToUser(result)
(4) this.savedResult = result
(5) session.commit()
(6) session.close()
(7) `result.getRecord().map(ORecord::getIdentity).filter(ORID::isPersistent).orElse(null);`

Line (7) is null. I can debug and see cluster position is still negative (-2).

**Comment by wolf4ood** [comment] 2019-07-09 08:23
Hi @matanshukry 

that's strange. Do you have a test case to reproduce this?

**Comment by wolf4ood** [comment] 2019-07-09 08:28
Oh i was testing using embedded and works fine. By switching to remote it remains negative

Let me check

**Comment by matanshukry** [comment] 2019-07-09 08:44
cool thx. I tried checking by saving OResultSet instead of just OResult, and even calling `.next()` only after the `.commit()`, all the same. Note it only happens when i'm calling `.begin()` and `.commit()`

**Comment by wolf4ood** [comment] 2019-07-09 08:47
@matanshukry 

yes because with begin and commit there is a server side transaction in progress. My understanding that at commit time there is no rebinding of final rids, which happens in embedded.

**Comment by matanshukry** [comment] 2019-07-09 08:51
@wolf4ood Yeah I realized that too now. Just to clarify though, when you're saying "my understanding" - are you referring to how things work, or how things should work?

Also, I do notice `ORecordAbstract.setIdentity()` is called twice when using `.begin` and `.commit()`.
Although the second time is called before the `.commit()`, in here: https://github.com/orientechnologies/orientdb/blob/develop/client/src/main/java/com/orientechnologies/orient/core/db/document/ODatabaseDocumentRemote.java#L375

According to the `OTransactionOptimisticClient.replaceContent()` code, it also looks like it's expecting a new non-temporary rid at that moment.

**Comment by wolf4ood** [comment] 2019-07-09 09:08
Hi @matanshukry 

my understanding from a debug session is that the rebind is not working properly. 
After commit the OVertex should contain the final rid

**Comment by wolf4ood** [comment] 2019-07-09 09:39
Hi @matanshukry 

i was able to fix it. I'm running the test and if passes i will push it

Thanks

**Comment by wolf4ood** [comment] 2019-07-09 09:59
Hi @matanshukry 

i've just pushed a fix. it will be available in the next release 3.0.22

Thanks

**Closed** 2019-07-09 09:59 UTC
Labels: bug

**Comment by matanshukry** [comment] 2019-07-09 10:01
@wolf4ood awesome, cool!

Since it's a client code It is a bit more difficult for me to get an updated code for it, so I'll have to wait. do you know when is 3.0.22 planned to be released?

**Comment by wolf4ood** [comment] 2019-07-09 14:23
@matanshukry 

not yet sure when. Probably next week

Thanks
