### ISSUE TITLE
Cannot create index on EMBEDDED property 

### ISSUE THREAD

**Issue by hrishirc** [orientechnologies/orientdb#8787] opened 2019-02-26 06:33 UTC
## Expected behavior  
Should create index on an OType.EMBEDDED vertex property

## Actual behavior  
Doesn't create index. Fails with error. 
java.lang.NullPointerException                                                                                                                                                  at com.orientechnologies.orient.core.storage.index.hashindex.local.OLocalHashTable.setKeySerializer(OLocalHashTable.java:208)                                           at com.orientechnologies.orient.core.storage.index.hashindex.local.OLocalHashTable.create(OLocalHashTable.java:167)                                                     at com.orientechnologies.orient.core.storage.index.engine.OHashTableIndexEngine.create(OHashTableIndexEngine.java:107)                                                  at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.addIndexEngine(OAbstractPaginatedStorage.java:2397)                                   at com.orientechnologies.orient.core.index.OIndexAbstract.create(OIndexAbstract.java:217)                                                                               at com.orientechnologies.orient.core.index.OIndexOneValue.create(OIndexOneValue.java:86)                                                                                at com.orientechnologies.orient.core.index.OIndexOneValue.create(OIndexOneValue.java:45)                                                                                at com.orientechnologies.orient.core.index.OIndexManagerShared.createIndex(OIndexManagerShared.java:167)                                                                at com.orientechnologies.orient.core.index.OIndexManagerProxy.createIndex(OIndexManagerProxy.java:90)                                                                   at com.orientechnologies.orient.core.sql.parser.OCreateIndexStatement.getoIndex(OCreateIndexStatement.java:142)                                                         at com.orientechnologies.orient.core.sql.parser.OCreateIndexStatement.execute(OCreateIndexStatement.java:110)                                                           at com.orientechnologies.orient.core.sql.parser.OCreateIndexStatement.executeDDL(OCreateIndexStatement.java:44)                                                         at com.orientechnologies.orient.core.sql.executor.ODDLExecutionPlan.executeInternal(ODDLExecutionPlan.java:55)                                                          at com.orientechnologies.orient.core.sql.parser.ODDLStatement.execute(ODDLStatement.java:42)                                                                            at com.orientechnologies.orient.core.sql.parser.OStatement.execute(OStatement.java:62)                                                                                  at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.command(ODatabaseDocumentEmbedded.java:563)                                                  at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeQuery(OConnectionBinaryExecutor.java:1293)                                                      at com.orientechnologies.orient.client.remote.message.OQueryRequest.execute(OQueryRequest.java:133)                                                                     at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:304)                                   at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:206)                                          at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)                                                                                     $ANSI{green {db=promotion}} Exception during index 'INDEX_NAME' creation                                                                                        java.lang.NullPointerException                                                                                                                                                  at com.orientechnologies.orient.core.storage.index.hashindex.local.OLocalHashTable.setKeySerializer(OLocalHashTable.java:208)                                           at com.orientechnologies.orient.core.storage.index.hashindex.local.OLocalHashTable.create(OLocalHashTable.java:167)                                                     at com.orientechnologies.orient.core.storage.index.engine.OHashTableIndexEngine.create(OHashTableIndexEngine.java:107)                                                  at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.addIndexEngine(OAbstractPaginatedStorage.java:2397)                                   at com.orientechnologies.orient.core.index.OIndexAbstract.create(OIndexAbstract.java:217)                                                                               at com.orientechnologies.orient.core.index.OIndexOneValue.create(OIndexOneValue.java:86)                                                                                at com.orientechnologies.orient.core.index.OIndexOneValue.create(OIndexOneValue.java:45)                                                                                at com.orientechnologies.orient.core.index.OIndexManagerShared.createIndex(OIndexManagerShared.java:167)                                                                at com.orientechnologies.orient.core.index.OIndexManagerProxy.createIndex(OIndexManagerProxy.java:90)                                                                   at com.orientechnologies.orient.core.sql.parser.OCreateIndexStatement.getoIndex(OCreateIndexStatement.java:142)                                                         at com.orientechnologies.orient.core.sql.parser.OCreateIndexStatement.execute(OCreateIndexStatement.java:110)                                                           at com.orientechnologies.orient.core.sql.parser.OCreateIndexStatement.executeDDL(OCreateIndexStatement.java:44)                                                         at com.orientechnologies.orient.core.sql.executor.ODDLExecutionPlan.executeInternal(ODDLExecutionPlan.java:55)                                                          at com.orientechnologies.orient.core.sql.parser.ODDLStatement.execute(ODDLStatement.java:42)                                                                            at com.orientechnologies.orient.core.sql.parser.OStatement.execute(OStatement.java:62)                                                                                  at com.orientechnologies.orient.core.db.document.ODatabaseDocumentEmbedded.command(ODatabaseDocumentEmbedded.java:563)                                                  at com.orientechnologies.orient.server.OConnectionBinaryExecutor.executeQuery(OConnectionBinaryExecutor.java:1293)                                                      at com.orientechnologies.orient.client.remote.message.OQueryRequest.execute(OQueryRequest.java:133)                                                                     at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:304)                                   at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:206)                                          at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69) 

## Steps to reproduce  
Create OType.EMBEDDED property and make an OClass.INDEX_TYPE.UNIQUE_HASH_INDEX index on it.
OClass clazz = createClass("clazz", ClassType.EDGE);
        clazz.createProperty("prop1", OType.EMBEDDED);
        clazz.createProperty("prop2", OType.STRING);
        clazz.createProperty("prop3", OType.EMBEDDEDMAP);
        clazz.createIndex("INDEX_NAME", OClass.INDEX_TYPE.UNIQUE_HASH_INDEX, "prop1"); // this line fails with above exception

forget UNIQUE_HASH_INDEX, any type of index, it is failing

**Comment by laa** [comment] 2019-02-26 09:19
Hi @hrishirc we do not index embedded properties, I will provide a meaning full message for that error. But for now this functionality is not supported. NPE here is because we can not find serializer for such types of keys.

**Comment by nanacoSai** [comment] 2019-03-11 01:35
Hi @laa, can we index  embedded properties like below? 

clazz.createIndex("INDEX_NAME", OClass.INDEX_TYPE.UNIQUE_HASH_INDEX, "prop1.field1")

**Comment by laa** [comment] 2019-03-11 10:33
@nanacoSai Short answer is no.Long is answer is we are working on this features, but that is not planned to be released in short time.

**Comment by laa** [comment] 2019-03-11 10:33
Closing this issue because it is not a bug.

**Closed by laa** 2019-03-11 10:33 UTC
