### ISSUE TITLE
$depth gives wrong result when there is more than 1 path between two nodes

### ISSUE THREAD

**Issue by gajjargaurav** [orientechnologies/orientdb#5228] opened 2015-10-27 10:02 UTC
I have user, group & role classes. 
A users can belongsTo a Group or a Role
A group can belongsTo a Role

I have a scenario as below,
<img width="396" alt="screen shot 2015-10-27 at 09 35 30" src="https://cloud.githubusercontent.com/assets/1262880/10754210/23a33abc-7c8e-11e5-83f4-94d286bc3174.png">

You can notice that Jhon is related to Admin in 3 ways,
Jhon > Admin
Jhon > Permies > Admin
Jhon > Devs2 > Permies > Admin

I want to query all the users that belongTo Admin and also the depth, the query I came up with looks like below,

```SQL
select *, $depth from (
traverse in() from (select from role where id = 1) 
) where @class = 'user'
```
the result is as below,
![t](https://cloud.githubusercontent.com/assets/1262880/10754385/1f255848-7c8f-11e5-9b87-e410d42007b8.png)

The question I have is why it gives $depth as 2? What is the logic behind it or is it a bug?

Additionally, if I alter the query slightly, 
```SQL
select *, $depth  from (
traverse in() from (select from role where id = 1) WHILE $depth <= 1
) where @class = 'user'
```
it gives me $depth of 1 for Jhon but the same fails when I try below,
```SQL
select *, $depth  from (
traverse in() from (select from role where id = 1) WHILE $depth <= 3
) where @class = 'user'
```

**Comment by gajjargaurav** [comment] 2015-10-29 12:11
@lvca thanks for marking it for the next hotfix. Can you also shed some light on what convention the solution will follow?
e.g. 
if the depth is not specified will it assume the $depth == 1?

**Comment by luigidellaquila** [comment] 2015-10-29 13:17
Hi @gajjargaurav 

to understand these values for $depth you have to take into consideration two important things:
- traversal, by default, is executed depth first (this default can be changed just adding BREADTH FIRST at the end of the traverse statement)
- the traversal skips vertices that were already traversed (mainly to avoid infinite loops)

In your case, probably, the db is traversing the nodes in this order:

Admin ($depth = 0)
Admin -> Permies ($depth = 1)
Permies -> Jhon ($depth = 2) <- here it is!
(Jhon has no incoming edges, so continuing from Permies)
Permies -> Devs2 ($depth = 2)
(Now Devs2 has an incoming edge from Jhon, but Jhon was already traversed, so it's ignored)
(back to Admin)
(again, Admin has an incoming edge from Jhon, it's ignored too)
Admin -> Contractors ($depth = 1)
Contractors -> Tom ($depth = 2)

Please, try this version:
```sql
select *, $depth from (
traverse in() from (select from role where id = 1)  depth first
) where @class = 'user'
```
you'll see that Jhon will have $depth = 1 in this case

As you can see it's not a bug, but just the way it works. 
I'm closing this, please reopen if you need further info

Thanks

Luigi

**Comment by luigidellaquila** [comment] 2015-10-29 13:18
sorry, the query to try of course is:

```sql
select *, $depth from (
traverse in() from (select from role where id = 1)  breadth first
) where @class = 'user'
```

**Closed by luigidellaquila** 2015-10-29 13:17 UTC
Labels: question

**Comment by gajjargaurav** [comment] 2015-10-29 14:37
@luigidellaquila Thanks for the explanation, I tried using the syntax you provided in the query but it doesn't seem to work with 2.1.2 version which I have, so I had to change the syntax to look like below,

```SQL
select *, $depth from (
traverse in() from (select from role where id = 1) STRATEGY BREADTH_FIRST
)  where @class = 'user'
```

**Comment by luigidellaquila** [comment] 2015-10-30 09:30
Hi @gajjargaurav 

sorry, you are right, your query is the right one

Thanks

Luigi
