### ISSUE TITLE
import with migrateLinks=true fails on links within embedded structures

### ISSUE THREAD

**Issue by zimoony** [orientechnologies/orientdb#4304] opened 2015-06-05 08:27 UTC
When importing a previously exported DB and migrateLinks is true (by default) and it happens that the importing procedure is assigning new RIDs (internal reordering starting by <clusterID>:0), then referenced RIDs within embedded structures like:

```json
{
  "someEmbeddedStructure": {
    "@type":"d",
    "@version":0,
    "@fieldTypes":"someLink=x",
    "someLink":"#<clusterID>:<ID>"
  }
}
```

are not referenced correctly. It does not matter if the links are in the first level or very deep inside the embedded document.

After the import the links are either pointing to nothing or to a wrong Entity. I am not sure if this is a bug and was intended to work - but right now our solution is to run a script which reorders and references all RIDs in the JSON file before we run the "database import" on the DB. But then for us the migrateLinks option loses its sense. We recognized that it works on links which a directly defined on an Entity but once being inside of embedded structures its a very unpredictable result. 

I guess keeping the original RIDs when importing would solve this problem too, but afaik there is no such option.

Note: This is happening on a schema-less class. Current DevRelease version we are running: community-2.1-rc3

**Comment by tglman** [comment] 2015-06-15 11:47
hi @zimoony,
I tryed to reproduce this with no success my step are(on the console) :
```
create database plocal:test admin admn
create class Test;
insert into Test content {name:"test1"} 
//return #11:0
insert into Test content {name:"test2"} 
//return #11:1
insert into Test content {name:"test3"} 
//return #11:2
insert into Test content {name:"test4", emb:{ref:'#11:2'}} 
//return #11:3
delete from #11:1
export database testdb.gz
disconnect
create database plocal:test1 admin admn
import database testdb.gz
select from Test where name='test4'
//the result is:
----+-----+------+-----+------------
#   |@RID |@CLASS|name |emb                   
----+-----+------+-----+------------
0   |#11:2|Test  |test4|{ref=#11:1}
----+-----+------+-----+------------
```

so it works correctly, can yo send me an export that create this problem?

Thank you

**Comment by zimoony** [comment] 2015-06-15 13:38
Hi tglman,

It only occurs within deeper embedded structures. Like, if you would do:
insert into Test content {name:"test4", emb1:{emb2:{ref:'#11:2’}}} //one level deeper for example
That command actually not really supports automatic linking with refs and therefor emb2.ref is saved as a simple string. If you would try to fetch it with "select from Test fetchplan emb1:3“ it will not resolve it correctly. So, the import will fail too of course. So in order to have a correct linking I insert the record like this:
insert into Test content {name:"test4", emb1:{'@type':'d', emb2:{'@type':'d', '@fieldTypes':'ref=x', ref:'#11:2'}}}
With "select from Test fetchplan emb1:3“ you will get the emb2.ref resolved into the entity of #11:2…

So, here are my final steps to reproduce my issue:
create database plocal:test admin admn
create class Test;
insert into Test content {name:"test1"} 
//return #11:0
insert into Test content {name:"test2"} 
//return #11:1
insert into Test content {name:"test3"} 
//return #11:2
insert into Test content {name:"test4", emb1:{'@type':'d', emb2:{'@type':'d', '@fieldTypes':'ref=x', ref:'#11:2'}}}
//return #11:3
select from Test where name='test4'
----+-----+------+-----+------------
#   |@RID |@CLASS|name |emb1                   
----+-----+------+-----+------------
0   |#11:3|Test  |test4|{emb2:{ref:#11:2}} //<—pointing correctly to Entity with name="test3"
----+-----+------+-----+------------
delete from #11:1
export database testdb.gz
disconnect
create database plocal:test1 admin admn
import database testdb.gz
select from Test where name='test4'
//the result is:
----+-----+------+-----+------------
#   |@RID |@CLASS|name |emb1                   
----+-----+------+-----+------------
0   |#11:2|Test  |test4|{emb2:{ref:#11:2}} //<— now pointing incorrectly to Entity with name=„test4“ (itself) must be #11:1
----+-----+------+-----+------------
I hope this helps to reproduce…

Best regards
Simon


Am 15.06.2015 um 13:47 schrieb tglman <notifications@github.com>:

> insert into Test content {name:"test4", emb:{ref:'#11:2'}}

**Comment by tglman** [comment] 2015-06-15 17:34
fixed in develop leaving it open because is missed the test case.

**Comment by tglman** [comment] 2015-06-16 10:36
added test case closing

**Closed by tglman** 2015-06-16 10:36 UTC
Labels: bug
