### ISSUE TITLE
RecordId cannot support negative cluster id. You've used: -4710

### ISSUE THREAD

**Issue by adithyank** [orientechnologies/orientdb#3206] opened 2014-12-16 05:30 UTC
Orient Version : 2.0 M3
JDK : Oracle 1.7.0_55

During our Database building exercise, this Exception is coming during commit call

```
com.orientechnologies.orient.core.exception.OStorageException
        at com.orientechnologies.orient.core.index.hashindex.local.OLocalHashTable.put(OLocalHashTable.java:442) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.index.engine.OHashTableIndexEngine.put(OHashTableIndexEngine.java:160) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.index.OIndexMultiValues.commitSnapshot(OIndexMultiValues.java:255) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.index.OIndexAbstract.commit(OIndexAbstract.java:643) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic$CommitIndexesCallback.run(OTransactionOptimistic.java:98) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:864) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:455) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:142) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2261) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2231) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at in.co.nmsworks.documenttdb.db.DocDB.commit(DocDB.java:482) ~[cygnetOTNMS.jar:?]
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.store.RcaInvWriter.addAll(RcaInvWriter.java:107) [cygnetOTNMS.jar:?]
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.store.RcaInvWriter.addAll(RcaInvWriter.java:65) [cygnetOTNMS.jar:?]
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.dao.InventoryDAO.save(InventoryDAO.java:106) [cygnetOTNMS.jar:?]
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.queue.InventoryDataPersister.saveDAOData(InventoryDataPersister.java:224) [cygnetOTNMS.jar:?]
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.queue.InventoryDataPersister.processAddition(InventoryDataPersister.java:199) [cygnetOTNMS.jar:?]
        at in.co.nmsworks.cygnet.telecom.fault.rcasia.inventory.queue.InventoryDataPersister.run(InventoryDataPersister.java:69) [cygnetOTNMS.jar:?]
Caused by: com.orientechnologies.orient.core.exception.ODatabaseException: RecordId cannot support negative cluster id. You've used: -28622
        at com.orientechnologies.orient.core.id.ORecordId.checkClusterLimits(ORecordId.java:314) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.id.ORecordId.<init>(ORecordId.java:51) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.serialization.serializer.binary.impl.OLinkSerializer.deserializeFromDirectMemoryObject(OLinkSerializer.java:112) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.serialization.serializer.stream.OStreamSerializerSBTreeIndexRIDContainer.deserializeFromDirectMemoryObject(OStreamSerializerSBTreeIndexRIDContainer
        at com.orientechnologies.orient.core.serialization.serializer.stream.OStreamSerializerSBTreeIndexRIDContainer.deserializeFromDirectMemoryObject(OStreamSerializerSBTreeIndexRIDContainer
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.deserializeFromDirectMemory(ODurablePage.java:117) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.index.hashindex.local.OHashIndexBucket.getEntry(OHashIndexBucket.java:131) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.index.hashindex.local.OHashIndexBucket$EntryIterator.next(OHashIndexBucket.java:350) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.index.hashindex.local.OHashIndexBucket$EntryIterator.next(OHashIndexBucket.java:333) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.index.hashindex.local.OLocalHashTable.splitBucketContent(OLocalHashTable.java:1891) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.index.hashindex.local.OLocalHashTable.splitBucket(OLocalHashTable.java:1953) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.index.hashindex.local.OLocalHashTable.doPut(OLocalHashTable.java:1543) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        at com.orientechnologies.orient.core.index.hashindex.local.OLocalHashTable.put(OLocalHashTable.java:434) ~[orientdb-core-2.0-M3.jar:2.0-M3]
        ... 16 more
```

The following different values are coming during this Exception

```
RecordId cannot support negative cluster id. You've used: -28622
RecordId cannot support negative cluster id. You've used: -30627
RecordId cannot support negative cluster id. You've used: -4710
```

Should I give any more information. Pls advice

**Comment by laa** [comment] 2015-01-19 17:57
Close it because it is not reporducable, but feel free to reopen it.

**Comment by pvf** [comment] 2015-03-20 19:40
Hi. it's reproducable after you change nested vertex type from embedded list to linked list(in my situation). Whole data becomes corrupted, and raises error on deleting RecordId cannot support negative cluster id. You've used: -12

**Comment by pvf** [comment] 2015-03-20 19:46
and that's actually bad when you broke old documentation links...

**Comment by lvca** [comment] 2015-04-20 10:38
@pvf Can you provide a test case to reproduce it?

**Comment by laa** [comment] 2015-05-22 07:25
is it still valid ?

**Comment by adithyank** [comment] 2015-05-28 06:04
This Exception has not come for last 4 to 5 months. It may be closed now. We will reopen it when it comes again

**Closed** 2015-05-28 06:12 UTC
Labels: waiting reply
