### ISSUE TITLE
Can't update embedded field when cluster is selected

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientdb#6033] opened 2016-04-23 10:17 UTC
Orientdb: 2.1.15
Studio: Yes

Hi,

I have one base Class called `Node` and a cluster called `de_business`. Julia is in the correct cluster I checked it twice by:

```sql
SELECT FROM cluster:[de_business]
```

Subscription is an embedded document.

This works:

```sql
UPDATE Node SET Subscription = { "test": true } WHERE Email = "julia@local"
```

This fails:

```
UPDATE CLUSTER:[de_business] SET Subscription = { "test": true } WHERE Email = "julia@local"
```

I get this exception in orientdb studio:

```
com.orientechnologies.orient.core.exception.OValidationException: The field 'Node.Subscription' has been declared as EMBEDDED but an incompatible type is used. Value: {test=true}
```

**Comment by StarpTech** [comment] 2016-04-23 10:24
@luigidellaquila @lvca looks like orientdb doesn't recognize that is from type JSON.

Update a special property of the embedded document works
```
UPDATE CLUSTER:[de_business] SET Subscription.de = true WHERE Email = "julia@local"
```

**Comment by luigidellaquila** [comment] 2016-04-26 08:31
Hi @StarpTech 

It seems to be a bug. I'm on it

Thanks

Luigi

**Comment by luigidellaquila** [comment] 2016-04-26 10:07
Hi @StarpTech 

I just pushed a fix on 2.1.x and develop.

Thanks

Luigi

**Closed by luigidellaquila** 2016-04-26 10:07 UTC
Labels: bug

**Comment by StarpTech** [comment] 2016-04-26 10:12
@luigidellaquila how can I use it in production without to try the develop branche?

**Comment by StarpTech** [comment] 2016-04-26 10:14
@luigidellaquila your Tests doesnt include the selection of multiple Clusters

**Comment by luigidellaquila** [comment] 2016-04-26 10:19
Hi @StarpTech 

The fix will be available for production in next 2.1.17.

What do you mean by selection of multiple clusters? 
I'm adding a test case where I explicitly create multiple clusters for the class, anyway, the problem is not related to multiple clusters, but only on the wrong parsing of the statement (conversion of JSON to Map instead of ODocument) when the target was a cluster.

Thanks

Luigi

**Comment by StarpTech** [comment] 2016-04-26 10:20
Hi @luigidellaquila thanks.
I mean `SELECT FROM CLUSTER:[<cluster1>,<cluster2> ]`

**Comment by luigidellaquila** [comment] 2016-04-26 10:25
Ok, I'm adding a test now

Thanks

Luigi

**Comment by luigidellaquila** [comment] 2016-04-26 10:28
You caught me... little fix coming in minutes

Thanks

Luigi

**Comment by StarpTech** [comment] 2016-04-26 10:31
:trollface:

**Comment by luigidellaquila** [comment] 2016-04-26 11:03
Here we go, fix pushed

Thanks!

Luigi

**Comment by StarpTech** [comment] 2016-04-26 11:08
Thank you @luigidellaquila one question: It is common that this command isnt parsed by JJTree ?

**Comment by luigidellaquila** [comment] 2016-04-26 11:17
Hi @StarpTech 

actually it's firstly parsed by JJTree, then it's post-processed (let's say re-parsed) by the old executor. This was the first step to completely remove old stuff, in v.2.2 we will gradually remove pieces of the old structure and in v3 it will completely disappear.

For now the advantage is that the grammar is formally validated and the statements are normalized so that the "old stuff" does not complain for additional blank spaces an so on. 

Thanks

Luigi

**Comment by StarpTech** [comment] 2016-04-26 11:30
Allright thanks @luigidellaquila
