### ISSUE TITLE
Transaction rollback not works.

### ISSUE THREAD

**Issue by schernolyas** [orientechnologies/orientdb#7050] opened 2016-12-31 04:58 UTC
## OrientDB Version, operating system, or hardware.
- v2.0 SNAPSHOT[ ] - .18[ ] .17[ ] .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.1 SNAPSHOT[ ] - .16[ ] .15[ ] .14[ ] .13[ ] .12[ ] .11[ ] .10[ ] .9[ ] .8[ ] .7[ ] .6[ ] .5[ ] .4[ ] .3[ ] .2[ ] .1[ ] .0[ ]
- v2.2 SNAPSHOT[ ] - .rc1[ ] .beta2[ ] .beta1[ ]
**v2.2.14**

## Operating System
- [ ] Linux
- [ ] MacOSX
- [x ] Windows
- [ ] Other Unix
- [ ] Other, name? 

## Expected behavior and actual behavior
I try to rollback transaction in 'i**n-memory**' database. State of transaction is:
[main] 07:51:18,184 DEBUG org.hibernate.ogm.datastore.orientdb.transaction.impl.OrientDBLocalTransactionCoordinator: transaction info: OTransactionOptimistic [id=2, status=BEGUN, **recEntries=1, idxEntries=1**]
Then I execute same code for '**rremote**' database I get next string in log:
[main] 07:54:38,332 DEBUG org.hibernate.ogm.datastore.orientdb.transaction.impl.OrientDBLocalTransactionCoordinator: transaction info: OTransactionOptimistic [id=2, status=BEGUN, **recEntries=0, idxEntries=0**]

## Steps to reproduce the problem
Try to rollback transaction by Native java API.

_____________________________________
Happy New Year! Mary Cristmas!

**Comment by schernolyas** [comment] 2016-12-31 05:41
Try to example code:
 public static void main(String[] args) {
        ODatabaseDocumentTx db = new ODatabaseDocumentTx("remote:localhost/trtest").
                open("admin", "admin");
        db.getMetadata().reload();
        System.out.println(db.getMetadata().getFunctionLibrary().getFunctionNames());
        db.begin(OTransaction.TXTYPE.OPTIMISTIC);        
        OFunction func = db.getMetadata().getFunctionLibrary().getFunction("executeQuery".toUpperCase());
        HashMap<Object,Object> funcArgs = new HashMap<>();
        funcArgs.put("insertQuery", "insert into Poem content {\"name\":\"Wazaaaaa2\",\"id\":\"84d33e4f-7f43-4181-9a69-ebeb9e628ccc\"};");
        func.execute(funcArgs);
        System.out.println(db.getTransaction().toString());
        db.rollback(true);
        //db.commit(true);

        db.close();
    }
Code of function is:
return orient.getDatabase().command(insertQuery);

Result of execution of the Java example is rollback not work and You can see new record.

**Comment by lvca** [comment] 2016-12-31 11:47
If you execute any command or function in the transaction scope, by using the remote protocol they are just sent to the server, while the transaction happens on the client only. This will be fixed in the upcoming v3.0 but it's not a bug, it's well known limitation.

**Closed by lvca** 2016-12-31 11:47 UTC
Labels: storage team
