### ISSUE TITLE
Migration to 2.2 to 3.0: Query execution on exapand does not work correclty

### ISSUE THREAD

**Issue by gianluca-valentini** [orientechnologies/orientdb#8661] opened 2018-11-15 13:13 UTC
## Expected behavior  
Let V1, V2 vertices and E an edge
V1 -> E ('edge') -> V2
Let be _status_ and _startToExist_ two numeric Edge attributes.
Now execute the query using java code
`select expand(inE('edge')[status = 1][startToExist between %d and %d].outV()) from V2`

Using as ODatabaseSession with OResultSet as OrientBaseGraph with OCommandSQL the result must be the same 

## Actual behavior  
Using as ODatabaseSession with OResultSet as OrientBaseGraph with OCommandSQL the result is different. In this situation **OResultSet** give me the correct result while **OCommandSQL iterable** is empty

**Comment by luigidellaquila** [comment] 2018-11-15 13:41
Hi @gianluca-valentini 

One of the reasons why we implemented the new SQL query executor is the difficulty to support complex projections with the old one. In this case, probably, the problem is the two subsequent square bracket filter operations.
I doubt that the old SQL executor will be fixed in the short term, so I strongly suggest you to use the new API

Thanks

Luigi

**Comment by gianluca-valentini** [comment] 2018-11-15 15:13
Thanks @luigidellaquila

**Closed** 2021-08-06 11:35 UTC
