### ISSUE TITLE
SQL - CREATE SEQUENCE not working

### ISSUE THREAD

**Issue by Dalamar** [orientechnologies/orientdb#5241] opened 2015-10-28 20:43 UTC
As I know from documentation, OrientDB will support sequences since version 2.2.
http://orientdb.com/docs/last/SQL-Create-Sequence.html

I downloaded 2.2 alpha to test this feature and came across following error when executed SQL code from the documentaion:
```
CREATE SEQUENCE idseq
```

The error is:
```
com.orientechnologies.orient.core.command.OCommandExecutorNotFoundException: Cannot find a command executor for the command request: sql.CREATE SEQUENCE idseq
```

**Comment by luigidellaquila** [comment] 2015-10-30 11:52
Hi @Dalamar 

where did you get 2.2? Is it a snapshot version or did you build it from sources?
I tried it building from "develop" branch and I get a different error (a null pointer) just because it needs sequence type, but adding it the statement works fine:

```sql
create sequence idseq type ORDERED
```

I'm going to fix docs about this
Please share some additional details, so that I can reproduce the problem

Thanks

Luigi

**Comment by Dalamar** [comment] 2015-10-30 12:04
Hi @luigidellaquila 
I got 2.2 alpha from here http://orientdb.com/download/

```Download the experimental OrientDB 2.2-alpha.```
The download link is as follows:
http://orientdb.com/download.php?email=unknown@unknown.com&file=orientdb-community-2.2-alpha.tar.gz&os=linux

**Comment by luigidellaquila** [comment] 2015-10-30 12:23
Ah, ok, that's a quite old alpha, probably sequences were not available yet at that time.
I suggest you to try a snapshot:

https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-community/2.2.0-SNAPSHOT/

I'm closing this issue (docs updated), please reopen in case you have other problems

Thanks

Luigi

**Closed by luigidellaquila** 2015-10-30 12:23 UTC
Labels: bug
