### ISSUE TITLE
Commit for OrientDB 2.2 snapshot March10 not working for linklist

### ISSUE THREAD

**Issue by cvm1ll3** [orientechnologies/orientdb#5839] opened 2016-03-16 19:55 UTC
I have a javascript function that creates a vertex and adds rids as a linklist for urls, phones, address, emailaddress. At the end of the function I execute gdb.commit() and call another function to query the newly created vertex and it returns the following result where the vertex rid that holds the linklist has the final rid but the linklist rids are either null or a temporary rid:

<code>
[

    {
        "@type": "d",
        "@rid": "#-2:0",
        "@version": 0,
       **"rid": "#102:8",**
        "birthday": "1985-01-01 00:00:00",
        "firstName": "Camille",
        "addressRID": [
           ** null,
            "#95:-29"**
        ],
        "gender": "F",
        "prefix": "Ms.",
        "phonesRID": [
           ** null,
            "#111:-42"**
        ],
        "emailAddressRID": [
            **null,
            "#104:-51"**
        ],
        "urlsRID": [
           ** null,
            "#118:-59"**
        ],
        "nickName": "Camille",
        "company": "Test Co",
        "category": "IT",
        "@fieldTypes": "rid=x,birthday=t,addressRID=z,phonesRID=z,emailAddressRID=z,urlsRID=z"
    }
]
</code>

When viewed in studio, after the function is executed, the vertex is created correctly and when I run the query function independently it returns the correct result with the final rids:

<code>
[

    {
        "@type": "d",
        "@rid": "#-2:0",
        "@version": 0,
       **"rid": "#102:8",**
        "birthday": "1985-01-01 00:00:00",
        "firstName": "Camille",
        "addressRID": [
           ** "#95:16",
            "#95:17"**
        ],
        "gender": "F",
        "prefix": "Ms.",
        "phonesRID": [
           ** "#111:16",
            "#111:17"**
        ],
        "emailAddressRID": [
          **  "#104:16",
            "#104:17"**
        ],
        "urlsRID": [
           ** "#118:16",
            "#118:17"**
        ],
        "nickName": "Camille",
        "company": "Test Co",
        "category": "IT",
        "@fieldTypes": "rid=x,birthday=t,addressRID=z,phonesRID=z,emailAddressRID=z,urlsRID=z"
    }
]
</code>

In the Orientdb 2.2 Alpha version, query after gdb.commit() returns the correct rids of the linklist. There were no changes in the functions from Orientdb 2.2 Alpha to functions I execute in Orientdb 2.2 snapshot March 10.

**Comment by tglman** [comment] 2016-03-22 01:55
hi @cvm1ll3 

when yuo start the server it print some version informations that include a commit id, can you post it here so we can get at the right point.

Will be cool if we can have a sample function for reproduce the problem, se we may add it to our test suite.

**Comment by cvm1ll3** [comment] 2016-03-22 17:31
hi @tglman,

here's the pseudo code sample function:

<code>
function: newContact
</code>

gdb = orient.getGraph();

/* creates a vertex with an address property [linklist] */
json = {};
json.class   = "Contacts";
json.cluster = "CLUSTER Contacts_" + division;
json.content = contacts;
newContact = MISC_createVertex(json);

/* creates address vertex */
json = {};
json.class   = "Address";
json.cluster = "CLUSTER Address_" + division;
json.content = address;
newAddress = MISC_createVertex(json);

/* adds the rid of the address vertex to the linklist in contacts vertex */
json = {};
json.parentRID = newContact.id;
json.property  = "address";
json.linkRID   = newAddress.id;
MISC_addToLinklist(json);

/* commit the entire transaction */
gdb.commit();

/* call another question to format query of new contact vertex */
return queryNewContact(newContact.id);

<code>
end function: newContact
</code>

<code>
function: queryNewContact
</code>

/* queryNewContact function */
gdb = orient.getGraph();
execSQL = "SELECT @rid, address as addressRID, address.include("city", "zip") FROM Contacts WHERE @rid = ?";
query = gdb.command("sql", execSQL, [rid]);
return query;

<code>
end function: queryNewContact
</code>

After commit I call the query function and it returns the linklist rids as null or temp rid. After I execute the function and check on studio, the vertices were created correctly. If I run the query function independently it would return the correct rids.

**Comment by cvm1ll3** [comment] 2016-04-06 18:28
hi @tglman,

I just did a build from sources today (04/06) and so far from my testing, this error seems to be fixed.

**Comment by tglman** [comment] 2016-04-11 17:05
hi @cvm1ll3,

This is a really good news, feel free to close the issue if you cannot reproduce it anymore.

**Comment by lvca** [comment] 2016-05-26 20:52
Closing because no answer. In case please reopen/comment it.

**Closed by lvca** 2016-05-26 20:52 UTC
Labels: bug, waiting reply
