### ISSUE TITLE
Searching Composite Lucene Index using PreparedStatement fails

### ISSUE THREAD

**Issue by hatibt** [orientechnologies/orientdb#3581] opened 2015-02-13 05:17 UTC
Hello guys,

I am using OrientDB 2.0.1 Community Edition 

My problem occurs when querying composite Lucene indexes,  via the Java API, combined with using named parameters.

eg SELECT FROM UsersWHERE [lastName, firstName] LUCENE (lastName::lastName OR firstName::firstName)

To pass named parameters in Java, the query has a double sequence of colons like "::" and i get an error "Error parsing lucene query" 

How do i get around this? is there a way of getting around the fact that Lucene searches use a colon as do preparedStatements ?

regards

Hatib

**Comment by lvca** [comment] 2015-02-13 05:54
Lvc@
Il 13/Feb/2015 06:18 "hatibt" <notifications@github.com> ha scritto:

**Comment by maggiolo00** [comment] 2015-02-27 10:56
Hi @hatibt for now is not possible preparedStatements 
because the lucene operator takes only a string

**Comment by luigidellaquila** [comment] 2015-03-06 09:16
this will be implemented with the new query executor.
Today Lucene index is like

attributeName LUCENE "stringValue" 

so it's possible to do

attributeName LUCENE :paramName

but not something like

attributeName LUCENE "foo :paramName bar"

because a parameter is not mached inside a string.
A proposed solution is to support extended syntax for Lucene operator (and maybe replace LUCENE keyword with something more generic)

eg.
attributeName LUCENE (foo = :paramName and bar = :param2)

**Comment by hatibt** [comment] 2015-05-22 01:28
Thanks for the responses guys, 

Your proposed solution seems like the way to go.

However, I have a new problem, because I upgraded from OrientDB 2.0.1 to 2.0.7 with the new Lucene 2.0.7 plugin

On 2.0.1, I was able to work around the named parameter issue in Java, with the following syntax for searching multiple fields. NB this syntax does not work for single fields as per my original query

val queryString = "select from User where [userName, firstName, lastName, email, sex] LUCENE :searchString" 

searchString being a named parameter that is retrieved from a map.

However when I upgraded to 2.0.7, it fails with the following error. Can u please explain whats changed and how i can sort this out?   thanks

com.orientechnologies.orient.core.index.OIndexEngineException: Error parsing lucene query 
--> org.apache.lucene.queryparser.classic.ParseException: Cannot parse ':Amy': Encountered " ":" ": "" at line 1, column 0.
Was expecting one of:
    <NOT> ...
    "+" ...
    "-" ...
    <BAREOPER> ...
    "(" ...
    "*" ...
    <QUOTED> ...
    <TERM> ...
    <PREFIXTERM> ...
    <WILDTERM> ...
    <REGEXPTERM> ...
    "[" ...
    "{" ...
    <NUMBER> ...
    <TERM> ...
    "*" ...
    
--> org.apache.lucene.queryparser.classic.ParseException: Encountered " ":" ": "" at line 1, column 0.
Was expecting one of:
    <NOT> ...
    "+" ...
    "-" ...
    <BAREOPER> ...
    "(" ...
    "*" ...
    <QUOTED> ...
    <TERM> ...
    <PREFIXTERM> ...
    <WILDTERM> ...
    <REGEXPTERM> ...
    "[" ...
    "{" ...
    <NUMBER> ...
    <TERM> ...
    "*" ...
     [ONetworkProtocolHttpDb]

**Comment by lvca** [comment] 2016-01-21 08:11
This seems a bug in the new parser.

**Comment by luigidellaquila** [comment] 2016-01-21 14:44
Hi @hatibt 

the problem is inside Lucene, you have some problems in your Lucene search string. Could you please post param value?

Thanks

Luigi

**Comment by luigidellaquila** [comment] 2016-03-09 16:20
Hi @hatibt 

I'm closing this issue. Please reopen if you have any additional info to reproduce it

Thanks

Luigi

**Closed by luigidellaquila** 2016-03-09 16:20 UTC
Labels: bug
