### ISSUE TITLE
Cannot drop database in distributed mode

### ISSUE THREAD

**Issue by Briksins** [orientechnologies/orientdb#3947] opened 2015-04-17 15:41 UTC
Hello

we were using 2.0.6 and latest OrientDB 2.1.SNAPSHOT - build 16 of April
this problem exists in both versions

Problem:
OrientDB refuse to drop database in distributed mode with error  "Database <db_name> is already open"

Single Instance mode:
1) Run OrientDB from bin/server.sh
2) With use of this code: http://pastebin.com/dsEQNegT we:
a) First run: create new and clean database
b) Second run: it drop old one and create new db
all is good here with single instance mode

Distributed instance mode:
1) delete all databases manually - so its all clean
2) Run OrientDB trough bin/dserver.sh
3) with with the same code as above we:
a) First run - all is ok, first clean db was created 
b) Second run - at this stage it should drop old db and create new

Expected result: database dropped
Actual result: database not dropped

Explanation: 

In code in drop database - "catch" block is not triggered and no errors produced, it thinks that database was dropped successfully and attempt to create again the same database. that cause crash because database with the same name already exists

Client crash stack:
http://pastebin.com/9aYXFGZX

Server Node stack:
http://pastebin.com/fS0tYw7Z 

It was tested with 2 Nodes, but later I start in distributed mode with single node - the same problem

**Comment by tobiemh** [comment] 2015-04-21 14:19
Possibly a duplicate of #3746 ?

**Comment by lvca** [comment] 2015-07-29 16:45
Confirm: it's a duplicate, but thanks for all the additional information.

**Closed by lvca** 2015-07-29 16:45 UTC
Labels: bug, distributed
